### ISSUE TITLE
jdk18+ crash <unknown>+0x0

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14124] opened 2021-12-09 17:23 UTC
This is using the latest source for everything, including OpenJDK. Happens quite often, I haven't been able to get a clean test run. Three tries and always 1/2 of the child jobs crashes.

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/16/ - ub18-390-2
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/16/functional_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/17/ - ub18-390-2
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/17/functional_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/18 - rh7-390-4
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/18/functional_test_output.tar.gz
```
10:52:10       [exec] Unhandled exception
10:52:10       [exec] Type=Segmentation error vmState=0x00000000
10:52:10       [exec] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=7cf59e70 Signal_Code=00000001
10:52:10       [exec] Handler1=000003FF991C8578 Handler2=000003FF990B2260 InaccessibleAddress=0006000000000000
10:52:10       [exec] gpr0=FFFFFFFFFFFFFAB6 gpr1=00000000A68F9488 gpr2=00000000000F2A00 gpr3=00000000000F5600
10:52:10       [exec] gpr4=000003FF8D1A2072 gpr5=0000000000158028 gpr6=00000000000F5600 gpr7=0000000000000008
10:52:10       [exec] gpr8=0000000000000001 gpr9=00000000A68F9488 gpr10=00000000000F2A00 gpr11=000003FF71FF4630
10:52:10       [exec] gpr12=00000000000F5600 gpr13=0000000000069700 gpr14=000003FF71FF43D6 gpr15=000003FF99FFE318
10:52:10       [exec] psw=0006000000000000 mask=0705200180000000 fpc=0008fe00 bea=000003FF71FF43D4
10:52:10       [exec] fpr0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr1 489dec8000000000 (f: 0.000000, d: 6.516833e+41)
10:52:10       [exec] fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr3 3b9a00c100000000 (f: 0.000000, d: 1.376584e-21)
10:52:10       [exec] fpr4 489dec8000000000 (f: 0.000000, d: 6.516833e+41)
10:52:10       [exec] fpr5 3e9249ac47ae147b (f: 1202590848.000000, d: 2.725092e-07)
10:52:10       [exec] fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr7 3e3a340000000000 (f: 0.000000, d: 6.100890e-09)
10:52:10       [exec] fpr8 000000002ba3e130 (f: 732160320.000000, d: 3.617353e-315)
10:52:10       [exec] fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr10 000000002ba3e488 (f: 732161152.000000, d: 3.617357e-315)
10:52:10       [exec] fpr11 0000000004b538f0 (f: 78985456.000000, d: 3.902400e-316)
10:52:10       [exec] fpr12 000003ff942f91e8 (f: 2486145536.000000, d: 2.172030e-311)
10:52:10       [exec] fpr13 0000000004b538d0 (f: 78985424.000000, d: 3.902398e-316)
10:52:10       [exec] fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
10:52:10       [exec] fpr15 000003ffbc0fe250 (f: 3155157504.000000, d: 2.172361e-311)
10:52:10       [exec] Target=2_90_20211209_159 (Linux 3.10.0-1160.25.1.el7.s390x)
10:52:10       [exec] CPU=s390x (4 logical CPUs) (0x1ec1b5000 RAM)
10:52:10       [exec] ----------- Stack Backtrace -----------
10:52:10       [exec] (0x000003FF990AE84A [libj9prt29.so+0x2e84a])
10:52:10       [exec] (0x000003FF990B33CE [libj9prt29.so+0x333ce])
10:52:10       [exec] (0x000003FF990AE8F4 [libj9prt29.so+0x2e8f4])
10:52:10       [exec] (0x000003FF990AEA0E [libj9prt29.so+0x2ea0e])
10:52:10       [exec] (0x000003FF990B33CE [libj9prt29.so+0x333ce])
10:52:10       [exec] (0x000003FF990AE6F0 [libj9prt29.so+0x2e6f0])
10:52:10       [exec] (0x000003FF991C84AE [libj9vm29.so+0x484ae])
10:52:10       [exec] (0x000003FF990B33CE [libj9prt29.so+0x333ce])
10:52:10       [exec] (0x000003FF991C86E4 [libj9vm29.so+0x486e4])
10:52:10       [exec] (0x000003FF990B24E4 [libj9prt29.so+0x324e4])
10:52:10       [exec] (0x000003FF99FFDE90 [<unknown>+0x0])
10:52:10       [exec] ---------------------------------------
```
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/String.format(String.java:4895)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Scanner.scanIdentifier(Scanner.java:952)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Scanner.xscan(Scanner.java:1125)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Scanner.scan(Scanner.java:138)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseName(Parser.java:315)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseMethod(Parser.java:837)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseClassMembers(Parser.java:1728)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseClass(Parser.java:1419)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Parser.parseFile(Parser.java:1988)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Main.compile(Main.java:255)
5XESTACKTRACE                   (entered lock: org/openjdk/asmtools/jasm/Main@0x000000002BABE608, entry count: 1)
4XESTACKTRACE                at org/openjdk/asmtools/jasm/Main.main(Main.java:328)
4XESTACKTRACE                at org/openjdk/asmtools/Main.jasm(Main.java:95)
4XESTACKTRACE                at org/openjdk/asmtools/Main.main(Main.java:55)
```

**Comment by pshipton** [comment] 2021-12-09 17:23
@joransiu I'm guessing this is a JIT problem.

**Comment by joransiu** [comment] 2021-12-09 17:38
Offhand, it looks like we took a wild branch to 000600000000000, from potentially JITCODE.  

The BEA is 2 bytes off from the GPR14 (return address) suggests a BASR call, and GPR0: FFFFFFFFFFFFFAB6 looks like a potential VFT offset (?) -- so maybe a virtual call dispatch where we got a bad object or J9Class ptr.

**Comment by joransiu** [comment] 2021-12-09 17:48
@dchopra001 , any chance you can take a look into this? Thx!

**Comment by pshipton** [comment] 2021-12-09 19:59
I don't know if this is a new OpenJ9 problem, or just exposed by the latest OpenJDK code. I'm going to go ahead and promote the latest OpenJDK code, so we may be seeing this failure regularly until it can be fixed.

**Comment by dchopra001** [comment] 2021-12-13 18:01
```
(kca) j9m  0x000003FF882F6494
J9Method for JIT Method: {java/util/Formatter.toString}
Method   {ClassPath/Name.MethodName}: {java/util/Formatter.toString}
                           Signature: ()Ljava/lang/String;
                              Access: Public
                    J9Class/J9Method: 0x0000000001118f00 / 0x0000000001118d48
               Compiled Method Start: 0x000003ff882f63aa (1016 bytes)
                      ByteCode Start: 0x000003ff5183c090 (14 bytes)
                   ROM Constant Pool: 0x000003ff5183b610 (100 entries)
                       Constant Pool: 0x00000000011183e0 (0 entries)
```

The BEA points to this method. 

The instructions leading up to the crash look like below:
```
0x3ff882f63aa {java/util/Formatter.toString} +0            E31050000004 lg        gpr1,0(,gpr5)
0x3ff882f63b0 {java/util/Formatter.toString} +6            E3E05FF8FF24 stg       gpr14,-8(,gpr5)
0x3ff882f63b6 {java/util/Formatter.toString} +12           E3505F98FF71 lay       gpr5,-104(,gpr5)
0x3ff882f63bc {java/util/Formatter.toString} +18           E350D0500021 clg       gpr5,80(,gpr13) J9VMThread.stackOverflowMark
0x3ff882f63c2 {java/util/Formatter.toString} +24           A744017B     jl        *0x2F6 C>> +782
0x3ff882f63c6 {java/util/Formatter.toString} +28           EB6C50180024 stmg      gpr6,gpr12,24(gpr5)
0x3ff882f63cc {java/util/Formatter.toString} +34           C4280000018E lgrl      gpr2,0x18E
0x3ff882f63d2 {java/util/Formatter.toString} +40           E55D20000000 clfhsi    0x0(gpr2),0x0
0x3ff882f63d8 {java/util/Formatter.toString} +46           A764008E     jc        0x6,*0x11C C>> +330
0x3ff882f63dc {java/util/Formatter.toString} +50           A7040082     jnop      *0x104 U>> +310  <<< ^+356 ^+410
0x3ff882f63e0 {java/util/Formatter.toString} +54           E30010080016 llgf      gpr0,8(,gpr1)
0x3ff882f63e6 {java/util/Formatter.toString} +60           B9020000     ltgr      gpr0,gpr0
0x3ff882f63ea {java/util/Formatter.toString} +64           A7840062     je        *0xC4 C>> +260
0x3ff882f63ee {java/util/Formatter.toString} +68           E31010080016 llgf      gpr1,8(,gpr1) <<< ^+326
0x3ff882f63f4 {java/util/Formatter.toString} +74   -1:10   E3601000003A llzrgf    gpr6,0(,gpr1)
0x3ff882f63fa {java/util/Formatter.toString} +80           C4280000016B lgrl      gpr2,0x16B
0x3ff882f6400 {java/util/Formatter.toString} +86           A7090001     lghi      gpr0,1
0x3ff882f6404 {java/util/Formatter.toString} +90           E3301000003A llzrgf    gpr3,0(,gpr1)
0x3ff882f640a {java/util/Formatter.toString} +96           E34030C80004 lg        gpr4,200(,gpr3)
0x3ff882f6410 {java/util/Formatter.toString} +102          B9820042     xgr       gpr4,gpr2
0x3ff882f6414 {java/util/Formatter.toString} +106          A7840032     je        *0x64 C>> +206
0x3ff882f6418 {java/util/Formatter.toString} +110          EC48002E017C cgij      gpr4,1,je,*0x5C C>> +202
0x3ff882f641e {java/util/Formatter.toString} +116          C04000000171 larl      gpr4,*0x2E2
0x3ff882f6424 {java/util/Formatter.toString} +122          E3E040040016 llgf      gpr14,4(,gpr4)
0x3ff882f642a {java/util/Formatter.toString} +128          B98200E3     xgr       gpr14,gpr3
0x3ff882f642e {java/util/Formatter.toString} +132          A7840025     je        *0x4A C>> +206
0x3ff882f6432 {java/util/Formatter.toString} +136          ECE80021017C cgij      gpr14,1,je,*0x42 C>> +202
0x3ff882f6438 {java/util/Formatter.toString} +142          E3E040080016 llgf      gpr14,8(,gpr4)
0x3ff882f643e {java/util/Formatter.toString} +148          B98200E3     xgr       gpr14,gpr3
0x3ff882f6442 {java/util/Formatter.toString} +152          A784001B     je        *0x36 C>> +206
0x3ff882f6446 {java/util/Formatter.toString} +156          ECE80017017C cgij      gpr14,1,je,*0x2E C>> +202
0x3ff882f644c {java/util/Formatter.toString} +162          E3E0400C0016 llgf      gpr14,12(,gpr4)
0x3ff882f6452 {java/util/Formatter.toString} +168          B98200E3     xgr       gpr14,gpr3
0x3ff882f6456 {java/util/Formatter.toString} +172          A7840011     je        *0x22 C>> +206
0x3ff882f645a {java/util/Formatter.toString} +176          ECE8000D017C cgij      gpr14,1,je,*0x1A C>> +202
0x3ff882f6460 {java/util/Formatter.toString} +182          E3E040100016 llgf      gpr14,16(,gpr4)
0x3ff882f6466 {java/util/Formatter.toString} +188          B98200E3     xgr       gpr14,gpr3
0x3ff882f646a {java/util/Formatter.toString} +192          A7840007     je        *0xE C>> +206
0x3ff882f646e {java/util/Formatter.toString} +196          ECE60077017C cgij      gpr14,1,jx'6',*0xEE C>> +434
0x3ff882f6474 {java/util/Formatter.toString} +202          A7090000     lghi      gpr0,0 <<< +110 +136 +156 +176
0x3ff882f6478 {java/util/Formatter.toString} +206          A70E0000     chi       gpr0,0 <<< +106 +132 +152 +172 +192 ^+558
0x3ff882f647c {java/util/Formatter.toString} +210          A7840066     je        *0xCC C>> +414
0x3ff882f6480 {java/util/Formatter.toString} +214          1800         lr        gpr0,gpr0 <<< ^+430
0x3ff882f6482 {java/util/Formatter.toString} +216          C004000000AD jlnop     *0x15A U>> +562
0x3ff882f6488 {java/util/Formatter.toString} +222          E3E06AB6FF04 lg        gpr14,-1354(,gpr6)
0x3ff882f648e {java/util/Formatter.toString} +228          C001FFFFFAB6 lgfi      gpr0,-0x54A
0x3ff882f6494 {java/util/Formatter.toString} +234          0DEE         basr      gpr14,gpr14
```

And here's the original java method implementation for this call:
```    
public String toString() {
        ensureOpen();
        return a.toString();
    }
```
I'm not sure where this `toString` call leads to yet since it's an interface call. I've requested access to the external machines so I can try and reproduce this on one of the crashing systems. I'm not able to reproduce this issue locally.

**Comment by dchopra001** [comment] 2021-12-13 19:09
From jdmpview, we are able to get the calling method:
```
> !stack 0x0000000000F31700
<f31700> 	!j9method 0x0000000000F5B180   java/lang/String.format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
<f31700> 	!j9method 0x00000000010FF988   org/openjdk/asmtools/jasm/Scanner.scanIdentifier([C)V
<f31700> 	!j9method 0x00000000010FF9A8   org/openjdk/asmtools/jasm/Scanner.xscan()V
<f31700> 	!j9method 0x00000000010FF788   org/openjdk/asmtools/jasm/Scanner.scan()V
<f31700> 	!j9method 0x00000000011339A8   org/openjdk/asmtools/jasm/ParserCP$ParserCPVisitor.visitMember(Lorg/openjdk/asmtools/jasm/Tables$ConstType;)Lorg/openjdk/asmtools/jasm/ConstantPool$ConstValue_Pair;
<f31700> 	!j9method 0x00000000011339E8   org/openjdk/asmtools/jasm/ParserCP$ParserCPVisitor.visitMethod(Lorg/openjdk/asmtools/jasm/Tables$ConstType;)Lorg/openjdk/asmtools/jasm/ConstantPool$ConstValue;
```

Peeking inside these methods and their implementations, nothing sticks out to me at the moment. I'm going to try limiting down to a single method to hopefully get a clearer picture.

**Comment by dchopra001** [comment] 2021-12-14 15:59
I'm not able to reproduce this issue on `ub18-390-2`. I'm using the following JDK:
```
java -version
openjdk version "18-internal" 2022-03-22
OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxOpenJDK)
Eclipse OpenJ9 VM (build master-1eee7848566, JRE 18 Linux s390x-64-Bit Compressed References 20211213_160 (JIT enabled, AOT enabled)
OpenJ9   - 1eee7848566
OMR      - 5a958d70833
JCL      - 2c58efcb217 based on jdk-18+26)
```

This JDK is from the following failing build: https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/171/

**Comment by dchopra001** [comment] 2021-12-14 18:09
It seems like the problem cannot be reproduced via grinders as well. Here are a few grinders launched by Peter:
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/456/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/459/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/460/

They are all able to compile the tests properly. So far the only place we have been able to reproduce this is in the acceptance builds.

**Comment by dchopra001** [comment] 2021-12-15 18:42
Here are a couple of acceptance builds from yesterday where the problem is no longer occurring:
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/175/ (tests run on ub20-390-2, rh7-390-4)
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/173/ (tests run on rh7-390-4, rh7-390-1)


`ub18-390-2` is currently disabled and I have access to it. However I have not been able to reproduce this issue manually on the machine either.

**Comment by dchopra001** [comment] 2021-12-15 18:45
@pshipton also ran JDKnext sanity.functional testing in https://github.com/eclipse-openj9/openj9/pull/14149 and the tests passed.

So for the time being I would say this problem is not reproduceable.

**Comment by dchopra001** [comment] 2021-12-15 18:50
@pshipton Given the above information, can we remove the blocker tag for this issue? Given that the problem is no longer seen I'm not sure if it's worth further investigating at this time. 

I propose that we re-enable ub18-390-2 and then monitor this issue over the next few days to see if the problem resurfaces again. If not then we can close it.

**Comment by pshipton** [comment] 2021-12-15 22:30
Removed the blocker label and re-enabled the machine. We'll have to wait for the next tagged jdk18 build to do another real acceptance build. What we could be doing is a nightly build, although we are short on machine resources. I'll enable one with a subset of tests.

**Comment by pshipton** [comment] 2021-12-16 14:21
There are more crashes in https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_s390x_linux_Nightly/1 - rh7-390-2

TestJlmRemoteMemoryNoAuth_0
TestIBMJlmRemoteMemoryAuth_1
TestIBMJlmRemoteMemoryNoAuth_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_sanity.system_s390x_linux_Nightly_testList_1/1/system_test_output.tar.gz

**Comment by pshipton** [comment] 2021-12-16 14:24
Other platforms are crashing in the same system tests as well, perhaps the same problem? See all the platforms at https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK18/1/

**Comment by pshipton** [comment] 2021-12-16 14:30
@0xdaryl fyi, I think this is cross platform.

**Comment by pshipton** [comment] 2021-12-20 14:46
Assuming this is the same problem.
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.functional_x86-64_mac_Nightly_testList_1/4
```
02:20:05      [javac] Compiling 2 source files to /Users/****/workspace/Test_openjdk18_j9_sanity.functional_x86-64_mac_Nightly_testList_1/aqa-tests/functional/Java9andUp/module_bin/org.openj9test.modularity.testUnreflect
02:20:06       [exec] Unhandled exception
02:20:06       [exec] Type=Segmentation error vmState=0x00000000
02:20:06       [exec] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000000
02:20:06       [exec] Handler1=00000000096380C0 Handler2=0000000007904D90
02:20:06       [exec] RDI=0000000025BF15C3 RSI=0000000025BF15C8 RAX=91A0000000000001 RBX=00000007FFE39BB8
02:20:06       [exec] RCX=000000000B7C2100 RDX=0000000025BF15C8 R8=00000007FFE39BD0 R9=00000007FFE39D00
02:20:06       [exec] R10=00000000020E0001 R11=000000000B94C900 R12=00000007FFE39D00 R13=000000000B94CC00
02:20:06       [exec] R14=0000000000000005 R15=00000007FFE39D18
02:20:06       [exec] RIP=0000000009BA25C8 GS=0000 FS=0000 RSP=000000000B820770
02:20:06       [exec] RFlags=0000000000010213 CS=002B RBP=000000000B722400 ERR=0B9750B800000000
02:20:06       [exec] TRAPNO=000000000000000D CPU=50B8000000000000 FAULTVADDR=000000000B9750B8
02:20:06       [exec] XMM0 0000000000000005 (f: 5.000000, d: 2.470328e-323)
02:20:06       [exec] XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] XMM2 000e1781000e1781 (f: 923521.000000, d: 1.959708e-308)
02:20:06       [exec] XMM3 3e3f82102f77e9d6 (f: 796387776.000000, d: 7.336042e-09)
02:20:06       [exec] XMM4 3ed0783e14ae37d8 (f: 346961888.000000, d: 3.926682e-06)
02:20:06       [exec] XMM5 fa3360d1c7907e3c (f: 3348135424.000000, d: -4.396929e+280)
02:20:06       [exec] XMM6 3fc59338d9982086 (f: 3650625792.000000, d: 1.685554e-01)
02:20:06       [exec] XMM7 402e7f9c1e980fa9 (f: 513281952.000000, d: 1.524924e+01)
02:20:06       [exec] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] XMM10 0000000000000006 (f: 6.000000, d: 2.964394e-323)
02:20:06       [exec] XMM11 0000000000000008 (f: 8.000000, d: 3.952525e-323)
02:20:06       [exec] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:20:06       [exec] Module=/Users/****/workspace/Test_openjdk18_j9_sanity.functional_x86-64_mac_Nightly_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.dylib
02:20:06       [exec] Module_base_address=00000000098DC000 Symbol=..@109.done
02:20:06       [exec] Symbol_address=0000000009BA25B0
02:20:06       [exec] Target=2_90_20211220_4 (Mac OS X 10.14.6)
02:20:06       [exec] CPU=amd64 (12 logical CPUs) (0x400000000 RAM)
02:20:06       [exec] ----------- Stack Backtrace -----------
02:20:06       [exec] ---------------------------------------
```

**Comment by pshipton** [comment] 2022-01-14 20:19
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/40
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/40
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK_testList_0/36
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK_testList_1/36

**Comment by pshipton** [comment] 2022-01-14 22:26
@0xdaryl this problem is affecting promotion of new jdk18 and jdknext levels. It's currently the only issue marked blocker in the jdk18 0.31 milestone. Today so far I can't get any test runs on zlinux that don't crash, and I've restarted 5 times already.

https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/205/

**Comment by 0xdaryl** [comment] 2022-01-16 12:46
@nbhuiyan : can you have a look at this please?  Note this is JDK 18+.

**Comment by nbhuiyan** [comment] 2022-01-18 00:08
Here's an update based on my initial investigation of this issue:

I have been unable to reproduce the failure locally on macOS, but was able to reproduce it on zLinux. If the functional test compilation job completes successfully, no failure running the tests themselves are observed. The failure is only observed when re-running `make compile` the second or third time. As I do not yet know how to pass options to the test build commands, I tried deleting the SCC after each `make compile`, and with that the failure no longer occurred. Once the failure did occur and the SCC got updated, all subsequent `make compile`s would fail until I deleted the SCC. These subsequent failures would occur early on in the compilation of the tests.

I spent some time investigating the core files, and have the same information to report as Dhruv did in his comments above from a month ago. However, since I think I know the conditions necessary to reproduce this reliably, my next step is to figure out how I can pass options to the test compilation commands and narrow down on the method(s) that are compiled in a failing run, and continue from there.

**Comment by pshipton** [comment] 2022-01-18 01:01
The easiest might be to set the OPENJ9_JAVA_OPTIONS environment variable before running `make compile`.

**Comment by 0xdaryl** [comment] 2022-01-25 13:10
Ping for status on this investigation please.

**Comment by nbhuiyan** [comment] 2022-01-25 23:04
Last week I ran into the issue of having many verbose logs generated when trying to reproduce the crash, which made it difficult to narrow down to the method(s) that have to be JIT compiled (or AOT loaded) to cause the failure. Eventually, I  have been able to single out just one method that is AOT compiled and loaded for the failure to occur:

```
+ (AOT load) java/util/Formatter.toString()Ljava/lang/String;
```

The failure does not happen with AOT disabled or forcing the method to be JIT compiled instead. I have spent some time examining the JIT log obtained (which did not cause a failure), but nothing stood out. I am now in the process of obtaining an AOT compilation log of a compile of the `Formatter.toString()` method that results in a failure and investigating that.

**Comment by pshipton** [comment] 2022-01-26 14:01
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK_testList_0/45

**Comment by pshipton** [comment] 2022-01-27 18:27
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/55/
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_1/55/

**Comment by nbhuiyan** [comment] 2022-01-27 21:21
I was able to obtain the AOT compilation log for `Formatter.toString` that resulted in a crash. Here are the relevant parts of the AOT log responsible for running into the crash:

```
...
10, JBinvokeinterface         51
...

         got fieldsig as Ljava/lang/Appendable;
IlGenerator: Generating compressedRefs anchor [000003FF03004810] for node [000003FF03004770]
ImproperInterfaceMethodFromCPRecord
	_method=0x00000000006E10C8
	_beholder=0x0000000000A65D00
	className=java/util/Formatter
	_cpIndex=51
	kind=97
	id=30
...
n12n      treetop                                                                             
n11n        acalli  java/lang/Object.toString()Ljava/lang/String;[#385  virtual Method -56] 
n10n          aloadi  <vft-symbol>[#310  Shadow] [flags 0x18607 0x0 ]                        
n7n             ==>aloadi (aloadi  java/util/Formatter.a Ljava/lang/Appendable;)
n7n           ==>aloadi   (aloadi  java/util/Formatter.a Ljava/lang/Appendable;)
...

...
LLZRGF  GPR6, Shadow[<vft-symbol>] 0(GPR1) ; Throws Implicit Null Pointer Exception
...
BRASL   GPR14, 0x000003FF03203440, targetAddr=0x000003FF744727BC (offset=0x000000000000015A)	
LG      GPR14,#406 0(GPR6)
LGFI    GPR0,0	
BASR    GPR14,GPR14 		# Call "java/lang/Object.toString()Ljava/lang/String;"	
...
```

`BRASL   GPR14, 0x000003FF03203440` is a call to the virtual unresolved call snippet, which attempts to patch the two succeeding instructions with the vtable entry address (`GPR14`) and its index (`GPR0`). Upon returning from the helper snippet, GPR14 contained a value that is not a valid method or thunk address, and and the vtable index in `GPR0` was -1354. This is obviously wrong as the vtable for the `java/lang/util/Appendable` J9Class was a lot smaller than that according to KCA. So when we get to the `BASR`, we crash trying to branch to an invalid location.

We ended up in this situation because of treating this call as an unresolved virtual method instead of an unresolved interface method, and the CP entry was not what the unresolved virtual method helper expected. @jdmpapin, who was helping with #14230 recognized the issue I was describing as possibly the same problem resulting from the `SymbolValidationManager` not treating this correctly. He is working on a fix that would fix this issue. I was able to verify that AOT compiling the `Formatter.toString` method with SVM disabled results in the call being treated as an unresolved interface call, and the failure no longer occurring.

**Comment by pshipton** [comment] 2022-01-28 15:03
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK_testList_0/47/

**Closed** 2022-02-08 21:25 UTC
Labels: comp:jit, blocker, segfault, jdk18
