### ISSUE TITLE
JDK 17/18 - Exception thrown from JIT compilation due to SHA-1 MessageDigest not available

### ISSUE THREAD

**Issue by JeffersonYu1** [eclipse-openj9/openj9#17250] opened 2023-04-23 19:03 UTC
### Java version
```
$ java -version

openjdk 17.0.6 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Linux amd64-64-Bit Compressed References 20230117_397 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

### Operating system details
```
$ cat /etc/*release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
$ uname -a

Linux luzhou 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## Description

A java.security.NoSuchAlgorithmException is thrown when running the following program. The bug affects 17.0.6.0, 18.0.2.1 using the cold and warm optlevels.

## Steps to reproduce
The following steps shows how to reproduce the bug on JDK 17.0.6.0 in a Ubuntu Linux environment.

### Compile
```
$ javac C.java
```

### Execute
```
$ java -Xjit:optlevel=cold C

Exception in thread "main" java.security.NoSuchAlgorithmException: SHA-1 MessageDigest not available
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
        at C.main(C.java:5)
```

```
$ java -Xjit:optlevel=warm C

Exception in thread "main" java.security.NoSuchAlgorithmException: SHA-1 MessageDigest not available
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
        at C.main(C.java:5)
```

```
$ java -Xnojit C

Exception in thread "main" java.security.NoSuchAlgorithmException: SHA-1 MessageDigest not available
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:185)
        at C.main(C.java:5)

// Note: Output is non-deterministic with -Xnojit. The Exception is
// sometimes thrown, while other times the program executes successfully.
```

```
$ java C

// executes successfully.
```

### Source code for an executable test case
```
// C.java

import java.security.MessageDigest;

public class C {
    public static void main(String[] args) throws Exception {
        MessageDigest.getInstance("SHA-1");
    }
}

```

### Workaround
Run with default (no options).
```
$ java C
```

### Notes
MessageDigest.java: [https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/MessageDigest.html](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/MessageDigest.html)

> Every implementation of the Java platform is required to support the following standard MessageDigest algorithms:
> - SHA-1
> - SHA-256

**Comment by pshipton** [comment] 2023-04-24 13:31
I can't reproduce this. It seems like it may be related to AOT given the described behaviour. Does it occur when running with `-Xnoaot`?

**Comment by pshipton** [comment] 2023-04-24 14:12
@dsouzai if we can't reproduce, can we provide some instructions to isolate the problem to a particular method and get the required log?

**Comment by CptGit** [comment] 2023-04-24 16:44
@pshipton Tried locating the failing method, can you try if this reproduces on your side?
```
java -Xjit:limit={'java/util/HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object;'},optlevel=cold C
```

**Comment by pshipton** [comment] 2023-04-24 17:05
I can't reproduce the problem, presumably because I don't have the bad AOT, so limiting what the JIT compiles won't help. I think we need some kind of JIT compile log from the bad AOT you have, but defer on what exactly is required to the JIT experts.

**Comment by dsouzai** [comment] 2023-04-24 17:41
I was able to reproduce it once by doing
```
./jdk-17.0.6+10/bin/java -Xshareclasses:destroyAll
./jdk-17.0.6+10/bin/javac C.java
./jdk-17.0.6+10/bin/java -Xjit:optlevel=cold C
```
but after redoing these steps, I haven't been able to reproduce it. As such, probably shouldn't delete the SCC you have.

If you were to do a run with:
```
java -Xjit:verbose={compilePerformance},vlog=limitfile,optlevel=cold C
```
you could do subsequent runs with
```
java -Xjit:optlevel=cold -Xaot:loadLimitFile=(limitfile,m,n) C
```
where `m` and `n` are line number ranges; the limit file can be used to binary search through the file to limit down to a set of methods. 

All that said, I may have a theory for this issue. When doing `javac`, we generate AOT code and populate it into the SCC. Then when we run `C`, because we're running with `-Xjit:optlevel=`, we disable CH Table optimizations; however, the AOT code that was generated in the `javac` run _did_ run with CH Table optimizations. I think this mismatch is probably what's causing the problem. This is also consistent with `-Xnojit` since that too will disable the CH Table optimizations. Just another consequence of the default SCC I suppose.

The fix is easy enough, though this issue seems to be highly intermittent (with a fresh SCC) so we may just have to wait and see if it shows up again to know if the fix didn't work.

**Comment by CptGit** [comment] 2023-04-24 18:29
@dsouzai Just to be clear, is there anything you need from us? We can upload the log or even cache if needed.

**Comment by dsouzai** [comment] 2023-04-24 18:33
> @dsouzai Just to be clear, is there anything you need from us? We can upload the log or even cache if needed.

You could upload the cache; maybe I can try to validate my theory with it.

**Comment by pshipton** [comment] 2023-04-24 18:56
It's work to re-use a cache. The paths to the libraries need to be the same. The timestamps are also checked and new classpath metadata will be added if they are different, although I don't think that will invalidate the AOT, but I'm not sure exactly what checks AOT itself does.

**Comment by dsouzai** [comment] 2023-04-24 19:00
> although I don't think that will invalidate the AOT, but I'm not sure exactly what checks AOT itself does.

AOT mainly depends on the existence of `J9ROMClasses`, specifically that the `J9ROMClass` of a `J9Class` be in the SCC; it leaves all the heavy lifting validation of timestamps and what not to the VM.

**Comment by CptGit** [comment] 2023-04-24 19:34
[sharedcc.zip](https://github.com/eclipse-openj9/openj9/files/11313998/sharedcc.zip)
Packaged `~/.cache/javasharedresources/C290M17F1A64P_sharedcc_zzq_G43L00` from my side.
@dsouzai

**Comment by pshipton** [comment] 2023-04-24 19:48
Also the JVM needs to be exactly the same version, or you can try running with `-Xshareclasses:noAutoPunt,<other options like bootClassesOnly>`, but that will only work if the ROM classes are exactly the same.

**Comment by dsouzai** [comment] 2023-04-24 20:39
```
JVMJITM004W AOT code in shared class cache cannot execute on current processor. Ignoring AOT code in shared class cache.
```
Yeah doesn't look like it'll be easy to use the existing SCC. I think we just go with the fix in https://github.com/eclipse-openj9/openj9/pull/17260 and go from there.

**Comment by 0xdaryl** [comment] 2023-06-21 12:04
@dsouzai : any updates on the next step for this one?  It is targeted for 0.40 so we will have to make a determination on it soon.

**Comment by dsouzai** [comment] 2023-06-21 14:00
I'm pretty sure https://github.com/eclipse-openj9/openj9/pull/17260 fixes this issue, so we can either close it and ask to be reopened if the issue still persists, or we leave it open until we release and it's validated.

**Comment by 0xdaryl** [comment] 2023-06-21 17:37
Thanks.  I will close this now.

**Closed by 0xdaryl** 2023-06-21 17:37 UTC
Labels: comp:jit, userRaised, comp:jit:aot
