### ISSUE TITLE
Performance issue. Runtime with openj9 188 seconds hotspot 5 seconds

### ISSUE THREAD

**Issue by thimo-seitz** [eclipse-openj9/openj9#14328] opened 2022-01-20 15:59 UTC
Java -version output
--------------------

OpenJ9:
openjdk version "11.0.13" 2021-10-19
IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8)
Eclipse OpenJ9 VM 11.0.13.0 (build openj9-0.29.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20211022_218 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 2d83aa3b76 based on jdk-11.0.13+8)

Hotspot:
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Microsoft-27990 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-27990 (build 11.0.13+8-LTS, mixed mode)

Summary of problem
------------------

A code runs 37 times slower with openj9 compared to hotspot.

I've attached a sample project which rises the issue: 
[openj9-defect.zip](https://github.com/eclipse-openj9/openj9/files/7906706/openj9-defect.zip)
The statement which runs unexpected slowly is in `src\main\java\de\seitz\thimo\Main.java` line 47
![grafik](https://user-images.githubusercontent.com/20231368/150374569-bb4eee1b-3a0b-461d-920a-66433e5d498d.png)

I've started both runs with -Xmx3g. open9j needs 188 seconds. hotspot needs 5 seconds.
Log openj9 run: 
[log-openj9.txt](https://github.com/eclipse-openj9/openj9/files/7906660/log-openj9.txt)

Log hotspot run:
[log-hotspot.txt](https://github.com/eclipse-openj9/openj9/files/7906663/log-hotspot.txt)

**Comment by pshipton** [comment] 2022-01-20 17:07
Start with JIT to narrow it down further.
@vijaysun-omr @0xdaryl fyi

**Comment by a7ehuo** [comment] 2022-01-21 01:22
@thimo-seitz Could you share the commands you used to build the sample project and to run the test? Thank you! I got the following exception when I try to run the package I built.  I just did `mvn compiler:compile` and `mvn package` under `openj9-defect`.   

```
java -cp openj9-defect-0.0.1-SNAPSHOT.jar de/seitz/thimo/Main
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at de.seitz.thimo.Main.<clinit>(Main.java:22)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

**Comment by thimo-seitz** [comment] 2022-01-21 08:23
Hello @a7ehuo 

Theres no configuration of a `fat`-jar. I should have put more emphasis on that aspect. I import the Maven projects into eclipse myself, so i miss that frequently.
You can run that by `mvn clean compile exec:java -Dexec.mainClass=de.seitz.thimo.Main`

Beste Regards
Thimo Seitz

**Comment by a7ehuo** [comment] 2022-01-21 15:15
Thanks @thimo-seitz! Now I'm able to reproduce the large gap on linux. 

HotSpot 
```
2022-01-21 15:55:20,366 INFO  [d.s.t.Main                          ] 21 seconds
```

OpenJ9
```
2022-01-21 16:12:32,550 INFO  [d.s.t.Main                          ] 239 seconds
```

**Comment by a7ehuo** [comment] 2022-01-22 22:31
I’m seeing similar perf gap with Java17 [1].  The profile from Java 11 show most ticks from walk stack frames [2]. 

[1] 
```
HotSpot Java17
2022-01-22 22:35:19,022 INFO  [d.s.t.Main                          ] 17 seconds

OpenJ9 Java17 
2022-01-22 22:34:07,613 INFO  [d.s.t.Main                          ] 248 seconds
```

[2]    
```
    TID 599258 36.46     tid_de.seitz.thimo.Main.main()_672d
     MOD 175849 10.70      /root/home/ahuo/src/issues_triage/14328_perf_spoon/sdks/openj9/jdk-11.0.13+8/lib/default/libj9vm29.so
     MOD 159890  9.73      /root/home/ahuo/src/issues_triage/14328_perf_spoon/sdks/openj9/jdk-11.0.13+8/lib/default/libj9jit29.so
     MOD  81473  4.96      JITCODE
     …
     …
    TID 599258 36.46     tid_de.seitz.thimo.Main.main()_672d
     MOD 175849 10.70      /root/home/ahuo/src/issues_triage/14328_perf_spoon/sdks/openj9/jdk-11.0.13+8/lib/default/libj9vm29.so
      SYM  52805  3.21       walkFrame
      SYM  38870  2.37       walkStackFrames
      SYM  34972  2.13       VM_BytecodeInterpreterCompressed::run(J9VMThread*)
     …
     …
     MOD 159890  9.73      /root/home/ahuo/src/issues_triage/14328_perf_spoon/sdks/openj9/jdk-11.0.13+8/lib/default/libj9jit29.so
      SYM  56059  3.41       jitGetExceptionTableFromPC
      SYM  55102  3.35       jitWalkStackFrames
      SYM  19329  1.18       jitExceptionHandlerSearch
      SYM   8022  0.49       avl_search
```

**Comment by a7ehuo** [comment] 2022-01-24 22:32
I collected `-verbose:stackwalk` closer to the following line. 
```java
var foundItems = spoonModel.getElements((CtClass<?> c) -> fqn.matches(c.getQualifiedName()));
```

I see lots of "`BEGIN STACK WALK`" are from `java/lang/ClassCastException` thrown from method `de/seitz/thimo/Main$$Lambda$375/0x0000000000000000.matches(Lspoon/reflect/declaration/CtElement;)Z` as below. 
```
<00000000009CAE00> *** BEGIN STACK WALK, flags = 00000000A42C0000, walkThread = 00000000009CAE00, walkState = 00000000009CB110 ***
<00000000009CAE00> 	INCLUDE_NATIVES
<00000000009CAE00> 	INCLUDE_CALL_IN_FRAMES
<00000000009CAE00> 	ITERATE_FRAMES
<00000000009CAE00> 	MAINTAIN_REGISTER_MAP
<00000000009CAE00> 	SKIP_INLINES
<00000000009CAE00> 	VISIBLE_ONLY
<00000000009CAE00> 	Throwing exception: java/lang/ClassCastException: spoon.reflect.factory.ModuleFactory$CtUnnamedModule incompatible with spoon.reflect.declaration.CtClass
<00000000009CAE00> Initial values: walkSP = 0000000000F76B78, PC = 0000000000000001, literals = 0000000000000000, A0 = 0000000000F76B90, j2iFrame = 0000000000F76C18, ELS = 00007F152BDFAB70, decomp = 0000000000000000
<00000000009CAE00> Generic special frame: bp = 0000000000F76B90, sp = 0000000000F76B78, pc = 0000000000000001, cp = 0000000000000000, arg0EA = 0000000000F76B90, flags = 0000000000000000
<00000000009CAE00> J2I frame: bp = 0000000000F76C18, sp = 0000000000F76B98, pc = 00007F14F9C46779, cp = 00000000011ECCC0, arg0EA = 0000000000F76C28, flags = 0000000010000000
<00000000009CAE00> 	Method: de/seitz/thimo/Main$$Lambda$375/0x0000000000000000.matches(Lspoon/reflect/declaration/CtElement;)Z (00000000011ECDA8)
```

I extracted out a list of the exceptions to the attached log:
[14328_exception_list_2022_01_24.txt](https://github.com/eclipse-openj9/openj9/files/7929231/14328_exception_list_2022_01_24.txt)

 @thimo-seitz Are these `java/lang/ClassCastException: ... incompatible with spoon.reflect.declaration.CtClass` expected?

**Comment by thimo-seitz** [comment] 2022-01-25 12:56
@a7ehuo Not really. Little mistake in the sample code. The cast should be to `CtType`. In the original project the model consists purely of CtClass. I've updated the sample project: 
[openj9-defect-v2.zip](https://github.com/eclipse-openj9/openj9/files/7933698/openj9-defect-v2.zip)
.

**Comment by thimo-seitz** [comment] 2022-01-26 11:00
Hello @a7ehuo.
Strange. Why apears that ClassCastException nowhere? Nor in stdout or stderr?
I've modified the sample so that there shouldn't be any ClassCastException and now both runs are in the same area of consumed time: 7 seconds vs. 10 seconds.
Since the interface of Filter of getElements is a GenericType is that case is not handled properly by openj9, if theres used a subtype? Trying to forcfully cast instead of testing the type at first.
There seems to be different behavior in case compared to hotspot.

Statement now doesn't use a typed filter:
[openj9-defect-v3.zip](https://github.com/eclipse-openj9/openj9/files/7941164/openj9-defect-v3.zip)

**Comment by a7ehuo** [comment] 2022-02-03 23:42
I set `-Xdump` with OpenJ9 so that when there is `java/lang/ClassCastException` from `de/seitz/thimo/Main`, a core is generated.  I traced one of the `ClassCastException`  exceptions thrown on `CtTypeReferenceImpl` [1]. Because`CtTypeReferenceImpl` does not implement `CtType`, the class cast check fails. I'm guessing the exceptions could be caught such as in `spoon/reflect/visitor/chain/CtQueryImpl$AbstractStep.accept` [2] and it might not be rethrown. That might explain why it doesn't show on stdout/stderr. I also tried to exclude the methods on the java call stack. Regardless of JIT'd methods or interpreted methods, the checkcast exception happens. 

I looked at the generated Main class file [3]. It looks to me `checkcast` has to be there since interface `Filter<T extends CtElement>` is implemented with type `Lspoon/reflect/declaration/CtType;` 

<details>
  <summary>[1]</summary>

```
	  java/lang/ClassCastException @ 0xfa4d24b0
	   fields inherited from "java/lang/Throwable":
	    private String detailMessage = "spoon.support.reflect.reference.CtTypeReferenceImpl incompatible with spoon.reflect.declaration.CtType" @ 0xfa4d2800
```

</details>

<details>
  <summary>[2]</summary>

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "de.seitz.thimo.Main.main()" J9VMThread:0x00000000009C5600, omrthread_t:0x00007FC701A6C2B0, java/lang/Thread:0x00000000A4475160, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1B, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x570C, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x00007FC6C3415000, to:0x00007FC6C3455000, size:0x40000)
3XMCPUTIME               CPU usage total: 17.234050803 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at de/seitz/thimo/Main$$Lambda$375/0x0000000000000000.matches(Bytecode PC:5)
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl$3.apply(CtQueryImpl.java:175(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl$3.apply(CtQueryImpl.java:172(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl$FunctionWrapper._accept(CtQueryImpl.java:514(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:309(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/filter/CtScannerFunction$Scanner.onElement(CtScannerFunction.java:78(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:141(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtTypeParameter(CtScanner.java:366(Compiled Code))
4XESTACKTRACE                at spoon/support/reflect/declaration/CtTypeParameterImpl.accept(CtTypeParameterImpl.java:42(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtClass(CtScanner.java:356(Compiled Code))
4XESTACKTRACE                at spoon/support/reflect/declaration/CtClassImpl.accept(CtClassImpl.java:58(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtPackage(CtScanner.java:677(Compiled Code))
4XESTACKTRACE                at spoon/support/reflect/declaration/CtPackageImpl.accept(CtPackageImpl.java:88(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtPackage(CtScanner.java:676(Compiled Code))
4XESTACKTRACE                at spoon/support/reflect/declaration/CtPackageImpl.accept(CtPackageImpl.java:88(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtPackage(CtScanner.java:676(Compiled Code))
4XESTACKTRACE                at spoon/support/reflect/declaration/CtPackageImpl.accept(CtPackageImpl.java:88(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:83(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtPackage(CtScanner.java:676(Compiled Code))
4XESTACKTRACE                at spoon/support/reflect/declaration/CtPackageImpl.accept(CtPackageImpl.java:88(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.scan(CtScanner.java:184(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:106(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/CtScanner.visitCtModule(CtScanner.java:962)
4XESTACKTRACE                at spoon/reflect/factory/ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:96)
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.doScan(EarlyTerminatingScanner.java:145(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:121(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/filter/CtScannerFunction.apply(CtScannerFunction.java:57)
4XESTACKTRACE                at spoon/reflect/visitor/filter/CtScannerFunction.apply(CtScannerFunction.java:27)
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:494)
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:309(Compiled Code))
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl.forEach(CtQueryImpl.java:95)
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl.list(CtQueryImpl.java:108)
4XESTACKTRACE                at spoon/reflect/visitor/chain/CtQueryImpl.list(CtQueryImpl.java:102)
4XESTACKTRACE                at spoon/reflect/CtModelImpl.getElements(CtModelImpl.java:131)
4XESTACKTRACE                at de/seitz/thimo/Main.main(Main.java:47)
4XESTACKTRACE                at org/codehaus/mojo/exec/ExecJavaMojo$1.run(ExecJavaMojo.java:254)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:866)
```

</details>

<details>
  <summary>[3]</summary>

```
Main.class:
  5: #242 REF_invokeStatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #285 (Lspoon/reflect/declaration/CtElement;)Z
      #287 REF_invokeStatic de/seitz/thimo/Main.lambda$main$2:(Ljava/lang/String;Lspoon/reflect/declaration/CtType;)Z
      #283 (Lspoon/reflect/declaration/CtType;)Z
```

```
method="de/seitz/thimo/Main$$Lambda$375/0x0000000000000000.matches(Lspoon/reflect/declaration/CtElement;)Z">
        0, JBaload0getfield
        1, JBgetfield
        4, JBaload1
        5, JBcheckcast 
        8, JBinvokestatic
       11, JBreturnZ
...   
n4n         aloadi  de/seitz/thimo/Main$$Lambda$375/0x0000000000000000.arg$1 Ljava/lang/String;
n3n           aload  <'this' parm Lde/seitz/thimo/Main$$Lambda$375/0x0000000000000000;>
...
n9n       checkcast [#86]                                                                    
n7n         aload  <parm 1 Lspoon/reflect/declaration/CtElement;>
n8n         loadaddr  spoon/reflect/declaration/CtType
n11n      treetop                                                                            
n10n        icall  de/seitz/thimo/Main.lambda$main$2(Ljava/lang/String;Lspoon/reflect/declaration/CtType;)Z
n4n           ==>aloadi
n7n           ==>aload
```

</details>

**Comment by thimo-seitz** [comment] 2022-05-20 14:10
In recent release it seems that this issue is fixed. Hotspot needs 6 seconds, OpenJ9 8 seconds.
```
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)
```

**Comment by 0xdaryl** [comment] 2022-09-30 13:40
The egregious performance difference originally reported no longer exists.  Closing this.

**Closed by 0xdaryl** 2022-09-30 13:40 UTC
Labels: comp:jit, perf, userRaised
