### ISSUE TITLE
JDK16 TEST: invoke/lambda/superProtectedMethod/SuperMethodTest.java - Unexpected IllegalAccessError

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11783] opened 2021-01-26 15:39 UTC
### JDK version

```
openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc.root.openj9-openjdk-jdk16)
Eclipse OpenJ9 VM (build 2816af3, JRE 16 Linux amd64-64-Bit Compressed References 20210126_000000 (JIT enabled, AOT enabled)
OpenJ9   - 2816af3
OMR      - 2ccca9b
JCL      - 5d554a1 based on jdk-16+32)
```

### Run the test

From the [JDK16 extensions repo](https://github.com/ibmruntimes/openj9-openjdk-jdk16/), execute the following command:
```
make test TEST="test/jdk/java/lang/invoke/lambda/superProtectedMethod/SuperMethodTest.java"
```

### Failure output

```
test p.SuperMethodTest.splitPackage(): failure
java.lang.IllegalAccessError: Class p/SuperMethodTest$B$$Lambda$16/0x00000000380629e0 illegally accessing "protected" member of class p/SuperMethodTest$A
        at p.SuperMethodTest$B$$Lambda$16/0x00000000380629e0.run(Unknown Source)
        at p.SuperMethodTest.splitPackage(SuperMethodTest.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:773)
        at org.testng.TestRunner.run(TestRunner.java:623)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
        at org.testng.SuiteRunner.run(SuiteRunner.java:259)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
        at org.testng.TestNG.run(TestNG.java:1018)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by tajila** [comment] 2021-01-26 21:40
The problem is that we are doing the access checks with the lambda (anonClass) which isn't a subclass of the superClass. From a language perspective the lambda is part of the class so access checks should be done with the hostClass instead. Will prepare a fix for this.

**Comment by babsingh** [comment] 2021-01-29 02:56
Confirming that the reported failure is fixed once OJDK MHs are enabled in OpenJ9. This issue should be tagged with `project:MH`.

**Comment by JasonFengJ9** [comment] 2021-08-16 14:28
Verified that this test passes a recent JDK16 build at `Test_grinder/job/Grinder/17539/console`
```
10:18:31  openjdk version "16.0.2-internal" 2021-07-20
10:18:31  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16x86-64linuxPersonal)
10:18:31  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 16 Linux amd64-64-Bit Compressed References 20210813_281 (JIT enabled, AOT enabled)
10:18:31  OpenJ9   - b49892b0b23
10:18:31  OMR      - ac3ab4821a5
10:18:31  JCL      - 44316ee515b based on jdk-16.0.2+7)
```
A PR (https://github.com/adoptium/aqa-tests/pull/2210) is already opened to re-enable the test in quesiton.

closing..

**Closed by JasonFengJ9** 2021-08-16 14:28 UTC
Labels: comp:vm, test excluded, jdk16, project:MH
