### ISSUE TITLE
Object neither in heap nor stack-allocated ASSERTION FAILED ScavengerRootScanner.hpp:109

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15885] opened 2022-09-14 13:12 UTC
This occurred on Java 19 but could be a dup of other similar issues.
https://github.com/eclipse-openj9/openj9/issues?q=is%3Aissue+is%3Aopen+%22Object+neither+in+heap+nor+stack-allocated%22

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/5
SC_Softmx_Increase_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/5/system_test_output.tar.gz

4.Jvm1.stderr
```
0000000009244100: Object neither in heap nor stack-allocated in thread load-1
0000000009244100:	O-Slot=00000000092526F0
0000000009244100:	O-Slot value=0000000008E110B0
0000000009244100:	PC=0000000022953105
0000000009244100:	framesWalked=2
0000000009244100:	arg0EA=0000000009252708
0000000009244100:	walkSP=00000000092525E8
0000000009244100:	literals=0000000008CAD858
0000000009244100:	jitInfo=00007FA3F4F0B5A8
0000000009244100:	method=0000000008CD5430 (java/lang/Thread.genThreadName()Ljava/lang/String;) (JIT)
0000000009244100:	stack=000000000924BDA8-0000000009252E50
05:43:08.857 0x8e39400    j9mm.479    *   ** ASSERTION FAILED ** at /Users/jenkins/workspace/Build_JDK19_x86-64_mac_Nightly/openj9/runtime/gc_glue_java/ScavengerRootScanner.hpp:109: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, *slotPtr, stackLocation, walkState).validate(_env)))
```
```
STF 01:43:06.140 - +------ Step 4 - Run a single workload process to fill up the initial cache
STF 01:43:06.140 - | Run foreground process
STF 01:43:06.140 - |   Program:     /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java
STF 01:43:06.140 - |   Mnemonic:    Jvm1
STF 01:43:06.140 - |   Echo:        ECHO_OFF
STF 01:43:06.140 - |   Expectation: NON_ZERO_EXIT [0, 1] within 15m
STF 01:43:06.140 - |
STF 01:43:06.140 - Running command: /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/cache -XX:SharedCacheHardLimit=20m -Xscmx1m -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump:system:events=user -classpath /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/STF/stf.load/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/STF/stf.core/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/systemtest_prereqs/log4j/log4j-api.jar:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/systemtest_prereqs/log4j/log4j-core.jar:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/systemtest_prereqs/junit/junit.jar:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/systemtest_prereqs/junit/hamcrest-core.jar:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/aqa-systemtest/openjdk.test.lang/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/aqa-systemtest/openjdk.test.util/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/aqa-systemtest/openjdk.test.math/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/aqa-systemtest/openjdk.test.classloading/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/aqa-systemtest/openjdk.test.nio/bin:/Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/jvmtest/system/openj9-systemtest/openj9.test.daa/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results -resultsPrefix 4.Jvm1. -dumpRequested false -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.sharedclasses-mix.inventoryFile /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/4.Jvm1.inventory/openj9.test.load/config/inventories/mix/sharedclasses-mix.xml -suite.sharedclasses-mix.inventoryExcludeFile /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/4.Jvm1.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.sharedclasses-mix.inventoryExcludeFile /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/4.Jvm1.inventory/openjdk.test.load/config/inventories/util/util_exclude.xml -suite.sharedclasses-mix.threadCount 11 -suite.sharedclasses-mix.totalNumberTests 600 -suite.sharedclasses-mix.selection sequential -suite.sharedclasses-mix.seed -1 -suite.sharedclasses-mix.repeatCount 1 -suite.sharedclasses-mix.thinkingTime 0ms..0ms
STF 01:43:06.140 - Redirecting stderr to /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/4.Jvm1.stderr
STF 01:43:06.140 - Redirecting stdout to /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/4.Jvm1.stdout
STF 01:43:06.148 - Monitoring processes: Jvm1
STF 01:43:08.859 - Found a dump that doesn't exist: /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/core.20220914.014308.56355.0001.dmp
STF 01:43:14.873 - Found dump at: /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/javacore.20220914.014308.56355.0002.txt
STF 01:43:15.053 - Found dump at: /Users/jenkins/workspace/Test_openjdk19_j9_extended.system_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_1663131798961/SC_Softmx_Increase_1/20220914-014303-SharedClassesWorkloadTest_Softmx_Increase/results/Snap.20220914.014308.56355.0003.trc
STF 01:43:15.154 - **FAILED** Process Jvm1 ended with exit code (255) and not the expected exit code/s (0,1)
```

@dmitripivkine

**Comment by dmitripivkine** [comment] 2022-09-14 15:55
This is duplicate of https://github.com/eclipse-openj9/openj9/issues/15251

```
> !findheader 0x8e110b0
Searching memory allocation header for 0x0000000008E110B0
Found memory allocation header, !j9x 0x8e0c188,0x8000
J9MemTag at 0x8e0c168 {
    U_32 eyeCatcher = 0xb1234567;
    U_32 sumCheck = 0xb8028429;
    UDATA allocSize = 0x8000;
    char* callSite = /Users/jenkins/workspace/Build_JDK19_x86-64_mac_Nightly/openj9/runtime/vm/segment.c:248;
    struct OMRMemCategory* category = !omrmemcategory 0x4066da0 (Classes);
}

> !allclasses | grep -i ThreadNumbering
0x0000000008E11100	0x0000000000000328	0x00007FA3F4074E68	0x00007FA3F54EF518	0	java/lang/Thread$ThreadNumbering
0x00007FA3F54EF518	0x000002B0	0x00007FA3F4074E68	0x00000020	0x0C804000	java/lang/Thread$ThreadNumbering
> !j9class 0x0000000008E11100 | grep -i stat
	0x38: volatile UDATA initializeStatus = 0x0000000000000001 (1)
	0x48: UDATA* ramStatics = !j9x 0x0000000008E110B0
	0x138: void** staticSplitMethodTable = !j9x 0x0000000000000000
To view static fields, use !j9statics 0x0000000008E11100
```

**Closed by dmitripivkine** 2022-09-14 15:55 UTC
Labels: test failure
