### ISSUE TITLE
OJDK MH: VarHandle_0 seg fault

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11938] opened 2021-02-10 04:21 UTC
### Error

Seg fault noticed while running `VarHandle_0` with OJDK MHs enabled in OpenJ9.

```
===============================================
Running test VarHandle_0 ...
===============================================
VarHandle_0 Start Time: Mon Feb  8 11:23:00 2021 Epoch Time (ms): 1612801380437
variation: NoOptions
JVM_OPTIONS:  
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_16.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FFAC3270550 Handler2=00007FFAC2FD5AC0 InaccessibleAddress=00007FFB4B5D40B0
RDI=00007FFAC43DB408 RSI=0000000000053500 RAX=0000000000044D00 RBX=00007FFAC8C14660
RCX=0000000000000000 RDX=0000000000000000 R8=000000000004FAD8 R9=00007FFAC408C5B8
R10=000000000000000E R11=00007FFA65481170 R12=000000000010BE68 R13=00000000871F8CA8
R14=0000000000393ED0 R15=00007FFA65855804
RIP=00007FFAC32C99CD GS=0000 FS=0000 RSP=00007FFAC8C142F0
EFlags=0000000000010246 CS=0033 RBP=0000000000016700 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FFB4B5D40B0
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 6c2f6176616a4c28 (f: 1634356224.000000, d: 1.320535e+213)
xmm2 00007ffac8c14690 (f: 3368109824.000000, d: 6.952249e-310)
xmm3 0000000039d7b6d9 (f: 970438336.000000, d: 4.794603e-315)
xmm4 000000003e11d716 (f: 1041356544.000000, d: 5.144985e-315)
xmm5 6f74706939477542 (f: 960984384.000000, d: 7.747090e+228)
xmm6 000000003ea30d2a (f: 1050873152.000000, d: 5.192003e-315)
xmm7 3c000000bebafeca (f: 3199926016.000000, d: 1.084203e-19)
xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm9 000000003e17cee7 (f: 1041747712.000000, d: 5.146917e-315)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
Module_base_address=00007FFAC3238000
Target=2_90_20210208_5 (Linux 3.10.0-327.el7.x86_64)
CPU=amd64 (4 logical CPUs) (0x1e4447000 RAM)
----------- Stack Backtrace -----------
(0x00007FFAC32C99CD [libj9vm29.so+0x919cd])
(0x00007FFAC32B8340 [libj9vm29.so+0x80340])
(0x00007FFAC3312462 [libj9vm29.so+0xda462])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2021/02/08 11:23:02 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/core.20210208.112302.23222.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.23247.

JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/core.20210208.112302.23222.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/javacore.20210208.112302.23222.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/javacore.20210208.112302.23222.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/Snap.20210208.112302.23222.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/Snap.20210208.112302.23222.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/jitdump.20210208.112302.23222.0004.dmp' in response to an event
JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/output_1612801376227/VarHandle_0/jitdump.20210208.112302.23222.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
```

### Failing Test Targets

1. `VarHandle_0` [extended.functional]

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment] 2021-02-10 04:22
Needs to be investigated.

This should be tagged with the `project:MH` label.

**Comment by babsingh** [comment] 2021-04-13 15:19
**Micro-test:**
```
import static java.lang.invoke.MethodHandles.*;
import java.lang.invoke.*;
import java.lang.reflect.*;

public class VarHandleTest {
        public static void main(String[] args) throws Throwable {
                Field f = VarHandleTest.class.getField("publicStaticInt");
                VarHandle vh = MethodHandles.lookup().unreflectVarHandle(f);
                if (vh == null) {
                        System.out.println("test failed: vh is null");
                } else {
                        System.out.println("vh: " + vh);
                        int result = (int)vh.getVolatile(); <-- ***** Segfault *****
                        if (result == VarHandleTest.publicStaticInt) {
                                System.out.println("test passed");
                        } else {
                                System.out.println("test failed: bad result");
                        }
                }
        }

        public static int publicStaticInt = 248;
}
```

**Run command:**
```
jdk/bin/java -Djava.lang.invoke.MethodHandle.DUMP_CLASS_FILES=true -Xint VarHandleTest.java
```

**Java call stack:**
```
at jdk/internal/misc/Unsafe.getIntVolatile(Native Method) <-- Segfault
at java/lang/invoke/VarHandleInts$FieldStaticReadOnly.getVolatile(VarHandleInts.java:431)
at java/lang/invoke/LambdaForm$DMH001/0x0000000000000000.invokeStatic001_LL_I(LambdaForm$DMH001)
at java/lang/invoke/LambdaForm$MH026/0x0000000000000000.VarHandle_invoke_MT__I(LambdaForm$MH026)
at MethodHandleTest.main(MethodHandleTest.java)
```

**Native call stack:**
```
#0  VM_BytecodeInterpreterCompressed::run (this=0x7ffff6f79160, vmThread=0x31c00) at BytecodeInterpreter.hpp:9728 <-- ***** Segfault *****
#1  0x00007ffff5fb4db5 in bytecodeLoopCompressed (currentThread=<optimized out>) at BytecodeInterpreter.inc:110
#2  0x00007ffff6067252 in c_cInterpreter () at xcinterp.s:160
#3  0x00007ffff5f4625d in sidecarInvokeReflectMethodImpl (currentThread=currentThread@entry=0x1aa00, methodRef=<optimized out>, recevierRef=<optimized out>, argsRef=0xdb240)
    at callin.cpp:1186
#4  0x00007ffff5f471f5 in sidecarInvokeReflectMethod (currentThread=0x1aa00, methodRef=<optimized out>, recevierRef=<optimized out>, argsRef=<optimized out>)
    at callin.cpp:1330
#5  0x00007fffef15f033 in JVM_InvokeMethod_Impl (env=0x1aa00, method=0xdb250, obj=0xdb248, args=0xdb240) at sunvmi.c:354
```

**`BytecodeInterpreter.hpp:9728`:** **<-- Segfault** 
https://github.com/eclipse/openj9/blob/df8bf06ae7786a7c62a600529b7959ddff4d20cb/runtime/vm/BytecodeInterpreter.hpp#L9728

**`VarHandleInts$FieldStaticReadOnly.getVolatile`:**
```
  static int getVolatile(VarHandle ob) {
      FieldStaticReadOnly handle = (FieldStaticReadOnly)ob;
      return UNSAFE.getIntVolatile(handle.base, handle.fieldOffset); // ***** Line 431 *****
  }
```

**`LambdaForm$DMH001.invokeStatic001_LL_I`:**
```
  static int invokeStatic001_LL_I(java.lang.Object, java.lang.Object);
    descriptor: (Ljava/lang/Object;Ljava/lang/Object;)I
    flags: (0x0008) ACC_STATIC
    Code:
      stack=2, locals=3, args_size=2
         0: aload_0
         1: invokestatic  #16                 // Method java/lang/invoke/DirectMethodHandle.internalMemberName:(Ljava/lang/Object;)Ljava/lang/Object;
         4: astore_2
         5: aload_1
         6: aload_2
         7: checkcast     #18                 // class java/lang/invoke/MemberName
        10: invokestatic  #24                 // Method java/lang/invoke/MethodHandle.linkToStatic:(Ljava/lang/Object;Ljava/lang/invoke/MemberName;)I
        13: ireturn

```

**`LambdaForm$MH026.VarHandle_invoke_MT__I`:**
```
  static int VarHandle_invoke_MT__I(java.lang.Object, java.lang.Object);
    descriptor: (Ljava/lang/Object;Ljava/lang/Object;)I
    flags: (0x0008) ACC_STATIC
    Code:
      stack=2, locals=4, args_size=2
         0: aload_0
         1: checkcast     #12                 // class java/lang/invoke/VarHandle
         4: dup
         5: astore_0
         6: invokestatic  #18                 // Method java/lang/invoke/Invokers.directVarHandleTarget:(Ljava/lang/invoke/VarHandle;)Ljava/lang/invoke/VarHandle;
         9: astore_2
        10: aload_0
        11: aload_1
        12: checkcast     #20                 // class java/lang/invoke/VarHandle$AccessDescriptor
        15: invokestatic  #24                 // Method java/lang/invoke/Invokers.checkVarHandleGenericType:(Ljava/lang/invoke/VarHandle;Ljava/lang/invoke/VarHandle$AccessDescriptor;)Ljava/lang/invoke/MethodHandle;
        18: astore_3
        19: aload_3
        20: invokestatic  #28                 // Method java/lang/invoke/Invokers.checkCustomized:(Ljava/lang/invoke/MethodHandle;)V
        23: aload_3
        24: aload_2
        25: invokevirtual #34                 // Method java/lang/invoke/MethodHandle.invokeBasic:(Ljava/lang/Object;)I
        28: ireturn
```

**Comment by JasonFengJ9** [comment] 2021-05-25 20:53
`VarHandle_0` passes with latest build with `ojdk_jsr292_final` branch.
It did fail with segmentation error in an earlier build though.

@babsingh @fengxue-IS do you happen to know if this has been fixed by another PR already?

**Comment by babsingh** [comment] 2021-05-25 22:06
@JasonFengJ9 I verified that the failure still occurs in my local workspace with OJDK MHs enabled.

The seg fault happens while performing an `Unsafe` operation on a `Field`. @fengxue-IS has a fix for correcting the field offset in [java_lang_invoke_MethodHandleNatives.cpp](https://github.com/eclipse-openj9/openj9/blob/master/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp). My guess is that it may fix this seg fault. Jack will confirm and post in this issue soon.

**Comment by fengxue-IS** [comment] 2021-05-26 18:01
local testing of my change fixed `VarHandle_0`, but the personal build contains test regression in other test suites, I will retest the personal build to verify if the regression is caused by my change or if my branch is not up to date

**Closed** 2021-06-02 15:37 UTC
Labels: comp:vm, project:MH
