### ISSUE TITLE
JDK19 serviceability_jvmti_j9_1_FAILED serviceability/jvmti/RedefineClasses/RedefineRunningMethodsWithBacktrace.java Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16275] opened 2022-11-07 17:05 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/24/)(`ub20x64rt4-6`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-f6c7bee4b, JRE 19 Linux amd64-64-Bit Compressed References 20221018_71 (JIT enabled, AOT enabled)
OpenJ9   - f6c7bee4b
OMR      - 357df2f80
JCL      - 110e1e7808 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F71%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F71%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F71%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-11-05-15-59.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F71%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-11-05-15-59.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-05T16:51:47.394Z] variation: Mode650
[2022-11-05T16:51:47.394Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-11-05T16:54:08.066Z] TEST: serviceability/jvmti/RedefineClasses/RedefineRunningMethodsWithBacktrace.java

[2022-11-05T16:54:08.069Z] STDOUT:
[2022-11-05T16:54:08.069Z] STDERR:
[2022-11-05T16:54:08.069Z] Unhandled exception
[2022-11-05T16:54:08.069Z] Type=Segmentation error vmState=0x00000000
[2022-11-05T16:54:08.069Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2022-11-05T16:54:08.069Z] Handler1=00007F6BE2F78250 Handler2=00007F6BE2ED2AE0 InaccessibleAddress=0000000000000000
[2022-11-05T16:54:08.069Z] RDI=00007F6BDC1CB7C0 RSI=0000000000400000 RAX=0000000024600006 RBX=00007F6BA0A8D790
[2022-11-05T16:54:08.069Z] RCX=0000000000000000 RDX=0000000000000000 R8=00007F6B54008DB0 R9=0000000000002000
[2022-11-05T16:54:08.069Z] R10=0000000000000000 R11=0000000000000003 R12=0000000000000000 R13=00007F6B54003C00
[2022-11-05T16:54:08.069Z] R14=0000000000000000 R15=00007F6BDC1CC10A
[2022-11-05T16:54:08.069Z] RIP=00007F6BE2FBA72D GS=0000 FS=0000 RSP=00007F6BA0A8CC40
[2022-11-05T16:54:08.069Z] EFlags=0000000000010202 CS=0033 RBP=0000000004600006 ERR=0000000000000004
[2022-11-05T16:54:08.069Z] TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
[2022-11-05T16:54:08.069Z] xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm1 00007f6bdc1ef4d0 (f: 3693016320.000000, d: 6.921921e-310)
[2022-11-05T16:54:08.069Z] xmm2 00007f6be14606c1 (f: 3779462912.000000, d: 6.921925e-310)
[2022-11-05T16:54:08.069Z] xmm3 0000000000000019 (f: 25.000000, d: 1.235164e-322)
[2022-11-05T16:54:08.069Z] xmm4 0000000000000018 (f: 24.000000, d: 1.185758e-322)
[2022-11-05T16:54:08.069Z] xmm5 0000003000000020 (f: 32.000000, d: 1.018558e-312)
[2022-11-05T16:54:08.069Z] xmm6 00007f6be1460691 (f: 3779462912.000000, d: 6.921925e-310)
[2022-11-05T16:54:08.069Z] xmm7 0000000000000005 (f: 5.000000, d: 2.470328e-323)
[2022-11-05T16:54:08.069Z] xmm8 00203a0079726f6d (f: 2037542784.000000, d: 4.513165e-308)
[2022-11-05T16:54:08.069Z] xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-11-05T16:54:08.069Z] Module=/home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
[2022-11-05T16:54:08.069Z] Module_base_address=00007F6BE2F3A000
[2022-11-05T16:54:08.069Z] Target=2_90_20221018_71 (Linux 5.4.0-131-generic)
[2022-11-05T16:54:08.069Z] CPU=amd64 (4 logical CPUs) (0xf5b40000 RAM)
[2022-11-05T16:54:08.069Z] ----------- Stack Backtrace -----------
[2022-11-05T16:54:08.069Z] walkStackFrames+0x45d (0x00007F6BE2FBA72D [libj9vm29.so+0x8072d])
[2022-11-05T16:54:08.069Z] walkContinuationStackFrames+0x76 (0x00007F6BE2FCF876 [libj9vm29.so+0x95876])
[2022-11-05T16:54:08.069Z] _ZN28GC_VMThreadStackSlotIterator9scanSlotsEP10J9VMThreadP8J9ObjectPvPFvP8J9JavaVMPS3_S4_P16J9StackWalkStatePKvEbb+0x46 (0x00007F6BE126BE16 [libj9gc_full29.so+0x43e16])
[2022-11-05T16:54:08.070Z] _ZN18MM_MarkingDelegate27scanContinuationNativeSlotsEP18MM_EnvironmentBaseP8J9Object+0x74 (0x00007F6BE13C2224 [libj9gc_full29.so+0x19a224])
[2022-11-05T16:54:08.070Z] _ZN32MM_ConcurrentGCIncrementalUpdate9localMarkEP18MM_EnvironmentBasem+0xdcf (0x00007F6BE137AD9F [libj9gc_full29.so+0x152d9f])
[2022-11-05T16:54:08.070Z] _ZN15MM_ConcurrentGC19conHelperEntryPointEP12OMR_VMThreadm+0x1cc (0x00007F6BE13F456C [libj9gc_full29.so+0x1cc56c])
[2022-11-05T16:54:08.070Z] con_helper_thread_proc2+0x6e (0x00007F6BE13F4AAE [libj9gc_full29.so+0x1ccaae])
[2022-11-05T16:54:08.070Z] omrsig_protect+0x2b1 (0x00007F6BE2ED3811 [libj9prt29.so+0x2a811])
[2022-11-05T16:54:08.070Z] con_helper_thread_proc+0x42 (0x00007F6BE13F27D2 [libj9gc_full29.so+0x1ca7d2])
[2022-11-05T16:54:08.070Z] thread_wrapper+0x163 (0x00007F6BE2E9B333 [libj9thr29.so+0xb333])
[2022-11-05T16:54:08.070Z] start_thread+0xd9 (0x00007F6BE3778609 [libpthread.so.0+0x8609])
[2022-11-05T16:54:08.070Z] clone+0x43 (0x00007F6BE3697133 [libc.so.6+0x11f133])
[2022-11-05T16:54:08.070Z] ---------------------------------------
[2022-11-05T16:54:08.070Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2022/11/05 09:53:50 - please wait.

[2022-11-05T16:54:08.070Z] TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
[2022-11-05T16:54:08.070Z] --------------------------------------------------
[2022-11-05T16:57:20.645Z] Test results: passed: 112; failed: 1
[2022-11-05T16:57:45.587Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-11-05T16:57:45.587Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16676666156932/serviceability_jvmti_j9_1/work
[2022-11-05T16:57:45.587Z] Error: Some tests failed or other problems occurred.
[2022-11-05T16:57:45.587Z] 
[2022-11-05T16:57:45.587Z] serviceability_jvmti_j9_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29365/) - this failure (`RedefineRunningMethodsWithBacktrace.java`) wasn't reproduced.

**Comment by tajila** [comment] 2022-11-10 18:31
looks like another dup

**Comment by babsingh** [comment] 2022-11-10 19:15
This is a duplicate of https://github.com/eclipse-openj9/openj9/issues/16212. @LinHu2016 Can you please confirm and close this issue as a duplicate?

**Comment by LinHu2016** [comment] 2022-11-10 21:48
duplicate of https://github.com/eclipse-openj9/openj9/issues/16212

**Comment by LinHu2016** [comment] 2022-11-10 21:49
@JasonFengJ9 please close the issue, Thanks

**Closed** 2022-11-10 21:49 UTC
Labels: test failure, jdk19, comp:jvmti
