### ISSUE TITLE
OpenJDK java/foreign/channels/TestAsyncSocketChannels IllegalStateException: Already closed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17619] opened 2023-06-19 15:07 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_Nightly/69
jdk_foreign_1
java/foreign/channels/TestAsyncSocketChannels.java
```
04:09:51  STDOUT:
04:09:51  Seed from RandomFactory = -7056481474570272678L
04:09:51  test TestAsyncSocketChannels.testBasicIOWithSupportedSession(shared arena): success
04:09:51  testCloseWithOutstandingRead - op
04:09:51  testCloseWithOutstandingRead - op
04:09:51  testCloseWithOutstandingRead - op
04:09:51  testCloseWithOutstandingRead - op
04:09:51  test TestAsyncSocketChannels.testCloseWithOutstandingRead(shared arena, 0): success
04:09:51  testCloseWithOutstandingRead - op
04:09:51  testCloseWithOutstandingRead - op
04:09:51  testCloseWithOutstandingRead - op
04:09:51  testCloseWithOutstandingRead - op
04:09:51  test TestAsyncSocketChannels.testCloseWithOutstandingRead(shared arena, 30): success
04:09:51  awaitNoFurtherWrites: i=2 , bytesWritten=92160
04:09:51  test TestAsyncSocketChannels.testCloseWithOutstandingWrite(shared arena, 0): failure
04:09:51  java.lang.AssertionError: Expected IllegalStateException to be thrown, but nothing was thrown
04:09:51  	at org.testng.Assert.expectThrows(Assert.java:1730)
04:09:51  	at TestAsyncSocketChannels.testCloseWithOutstandingWrite(TestAsyncSocketChannels.java:274)
04:09:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
04:09:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
04:09:51  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
04:09:51  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
04:09:51  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
04:09:51  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
04:09:51  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
04:09:51  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
04:09:51  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
04:09:51  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
04:09:51  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
04:09:51  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
04:09:51  	at org.testng.TestRunner.run(TestRunner.java:585)
04:09:51  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
04:09:51  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
04:09:51  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
04:09:51  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
04:09:51  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
04:09:51  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
04:09:51  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
04:09:51  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
04:09:51  	at org.testng.TestNG.runSuites(TestNG.java:1069)
04:09:51  	at org.testng.TestNG.run(TestNG.java:1037)
04:09:51  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:93)
04:09:51  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:53)
04:09:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
04:09:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
04:09:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
04:09:51  	at java.base/java.lang.Thread.run(Thread.java:1639)
04:09:51  	Suppressed: java.lang.IllegalStateException: Already closed
04:09:51  		at java.base/jdk.internal.foreign.MemorySessionImpl.alreadyClosed(MemorySessionImpl.java:312)
04:09:51  		at java.base/jdk.internal.foreign.SharedSession.justClose(SharedSession.java:83)
04:09:51  		at java.base/jdk.internal.foreign.MemorySessionImpl.close(MemorySessionImpl.java:243)
04:09:51  		at java.base/jdk.internal.foreign.MemorySessionImpl$1.close(MemorySessionImpl.java:89)
04:09:51  		at TestAsyncSocketChannels.testCloseWithOutstandingWrite(TestAsyncSocketChannels.java:242)
04:09:51  		... 29 more
04:09:51  STDERR:
04:09:51  java.lang.IllegalStateException: Already closed
04:09:51  	at java.base/jdk.internal.foreign.MemorySessionImpl.alreadyClosed(MemorySessionImpl.java:312)
04:09:51  	at java.base/jdk.internal.misc.ScopedMemoryAccess$ScopedAccessError.newRuntimeException(ScopedMemoryAccess.java:113)
04:09:51  	at java.base/jdk.internal.misc.ScopedMemoryAccess.putByte(ScopedMemoryAccess.java:539)
04:09:51  	at java.base/java.lang.invoke.VarHandleSegmentAsBytes.set(VarHandleSegmentAsBytes.java:118)
04:09:51  	at java.base/java.lang.foreign.MemorySegment.set(MemorySegment.java:1409)
04:09:51  	at AbstractChannelsTest.segmentBufferOfSize(AbstractChannelsTest.java:74)
04:09:51  	at AbstractChannelsTest.segmentBuffersOfSize(AbstractChannelsTest.java:82)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:264)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:259)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:160)
04:09:51  	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:759)
04:09:51  	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:382)
04:09:51  	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:415)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:266)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:259)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:160)
04:09:51  	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:759)
04:09:51  	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:382)
04:09:51  	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:415)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:266)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:259)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:160)
04:09:51  	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:759)
04:09:51  	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:382)
04:09:51  	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:415)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:266)
04:09:51  	at TestAsyncSocketChannels$1.completed(TestAsyncSocketChannels.java:259)
04:09:51  	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
04:09:51  	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:647)
04:09:51  	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:199)
04:09:51  	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
04:09:51  	at java.base/sun.nio.ch.AixPollPort$EventHandlerTask.run(AixPollPort.java:437)
04:09:51  	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
04:09:51  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
04:09:51  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
04:09:51  	at java.base/java.lang.Thread.run(Thread.java:1639)
```

**Comment by ChengJin01** [comment] 2023-06-19 20:08
FYI: @babsingh (as this is something related to `ScopedMemoryAccess`)

**Comment by babsingh** [comment] 2023-06-21 00:01
Ran a 100x grinder: https://openj9-jenkins.osuosl.org/job/Grinder/2510. The failure could not be reproduced and is highly intermittent.

**Comment by babsingh** [comment] 2023-06-21 00:35
The failure is due to a known issue with the test [1]. [2] describes in detail why the test fails. [3] is the fix, which just removes the two failing asserts associated with `drop.close()`. The fix is neither in the JDK20 nor JDK21 extension repos. Not sure if there is a plan to backport it. The failure is highly intermittent; we can just ignore the failure if it occurs again. If need be, I can manually backport the fix to the JDK20 and JDK21 extension repos.

**References:**
[1] https://bugs.openjdk.org/browse/JDK-8307411
[2] https://github.com/openjdk/jdk/pull/13866
[3] https://github.com/openjdk/jdk/commit/f92d095e164bd79b452586e49e166d1ba392632f

**Comment by pshipton** [comment] 2023-06-21 03:38
Don't bother for jdk20. We can monitor and if we see it too often on jdk21 then it would be worth it.

**Comment by pshipton** [comment] 2023-08-09 17:26
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Release_testList_0/7
jdk_foreign_0
java/foreign/channels/TestAsyncSocketChannels.java
```
02:15:55  test TestAsyncSocketChannels.testCloseWithOutstandingWrite(newSharedScope(Cleaner), 30): failure
02:15:55  java.lang.AssertionError: Expected IllegalStateException to be thrown, but nothing was thrown
02:15:55  	at org.testng.Assert.expectThrows(Assert.java:1730)
02:15:55  	at TestAsyncSocketChannels.testCloseWithOutstandingWrite(TestAsyncSocketChannels.java:273)
...
02:15:55  	Suppressed: java.lang.IllegalStateException: Already closed
02:15:55  		at jdk.incubator.foreign/jdk.internal.foreign.SharedScope.justClose(SharedScope.java:102)
02:15:55  		at jdk.incubator.foreign/jdk.internal.foreign.ResourceScopeImpl.close(ResourceScopeImpl.java:169)
02:15:55  		at TestAsyncSocketChannels.testCloseWithOutstandingWrite(TestAsyncSocketChannels.java:241)
02:15:55  		... 33 more
```

**Comment by babsingh** [comment] 2023-11-27 22:04
Closing, the fix is in
- JDK21 (openj9, v0.42.0-release and v0.43.0-release branches): https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/144e233b3d23f6e46369f169f6106230b893b265; and
- JDK-next: https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/96805d118f187505b6ff2c10aa485cb6bdaedf5f.

**Closed by babsingh** 2023-11-27 22:04 UTC
Labels: comp:test, test failure
