### ISSUE TITLE
AIX 7: rpm package zlib-1.2.12-1.ppc breaks Semeru JDK 11

### ISSUE THREAD

**Issue by B-Nebel** [eclipse-openj9/openj9#14953] opened 2022-04-22 10:57 UTC
Java -version output
--------------------
java version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Certified Edition 11.0.14.1 (build 11.0.14.1+1)
Eclipse OpenJ9 VM 11.0.14.1 (build openj9-0.30.1, JRE 11 AIX ppc64-64-Bit Compressed References 20220215_254 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - 56c3376ba
JCL      - f0981daedc based on jdk-11.0.14.1+1)

Summary of problem
------------------
On AIX 7.2(.5.3), after installing zlib library version 1.2.12 from OpenSource Toolbox, the extraction of a particular zip file with a simple Java program fails with following error:
invalid entry CRC (expected 0xafdd8e3a but got 0x960086d8)[Ljava.lang.StackTraceElement;@5470688f

The same worked fine with the former zlib library version 1.2.11.  Because the failure does not happen with any zip file, I can provide a simple reproducer kit on request.

The following facts have been figured out:
Semeru JDK11 loads the libz.a dynamically via LIBPATH, while the linked in default prefers the path /opt/freeware/lib to /lib:/usr/lib.
   The following command shows the actual path to libz.a, which is used in the current environment (Example for 'unset LIBPATH'):
   
   $ ldd java
   java needs:
         /opt/freeware/lib/libz.a(libz.so.1)           <<<<<<< default location
         /usr/lib/libpthreads.a(shr_xpg5_64.o)
         /usr/lib/libc.a(shr_64.o)
         /unix
         /usr/lib/libcrypt.a(shr_64.o)

There may exist several different versions of libz.a on AIX at the same time 
    and the LIBPATH variable determines which one is actually getting linked.
   $ rpm -q zlib (or:  yum list installed|grep zlib)
   zlib-1.2.12-1.ppc     <<<< /opt/freeware/bin/libz.a has v1.2.12-1
   $ ls /usr/lib/libz.a     <<<< /usr/lib/libz.a has v1.2.11
   /usr/lib/libz.a
   $ ls -l /usr/lib/libz.a
   lrwxrwxrwx    1 root     system           23 Apr 06 09:15 /usr/lib/libz.a -> /usr/opt/rpm/lib/libz.a
   $ lslpp -w /usr/opt/rpm/lib/libz.a
     File                                        Fileset               Type
     ----------------------------------------------------------------------------
     /usr/opt/rpm/lib/libz.a                     rpm.rte               File

The same java example program works fine, if LIBPATH is set to a libz.a v1.2.11, but
   it fails, if LIBPATH is set to a libz.a v1.2.12-1 (which is currently the latest on AIX Toolbox for Open Source Software).
   So any customer can run into this on AIX 7, with the default condition (Semeru Java 11, unset LIBPATH, 'yum update' to latest).

The same reproducer example program works fine with Adoptium JDK 11 under the same conditions, so this seems to be specific to Semeru Java.

**Comment by pshipton** [comment] 2022-04-22 11:43
A simple reproducer would be handy. Does it still fail with the Semeru 11.0.15 M2 build?
https://github.com/ibmruntimes/semeru11-binaries/releases/tag/jdk-11.0.15%2B8_openj9-0.32.0-m2

Can you pls provide details of the Adoptium JDK that works, is it also 11.0.14.1? I'm not sure why Adoptium would have different behaviour. It's the OpenJDK code that uses libz, which should be the same for Semeru and Adoptium. I wonder if Adoptium is using the system libz or finds libz differently.

**Comment by pshipton** [comment] 2022-04-22 11:49
Adoptium 11.0.14.1 is the same
```
java needs:
         /opt/freeware/lib/libz.a(libz.so.1)
```

**Comment by B-Nebel** [comment] 2022-04-22 11:55
Adoptium JDK that works was Adoptium_jdk-11.0.14.1+1. It also loads libz.a same way.

**Comment by pshipton** [comment] 2022-04-22 11:58
It may also be worth trying the reproducer on Semeru with the `-Xint` option, to determine if the behavior is affected by the JIT.

**Comment by B-Nebel** [comment] 2022-04-22 12:33
Same problem with Semeru jdk-11.0.15+8, with and without -Xint. How can I pass the reproducer tar file to you?

**Comment by pshipton** [comment] 2022-04-22 13:54
Any file sharing service will do.

**Comment by B-Nebel** [comment] 2022-04-25 08:13
I sent a gziped tar file to your Email, Peter. You need to have a Semeru JDK11, set the JAVA_EXE variable in the shell script for the same, then you can run the script right away on AIX 7.2.

**Comment by pshipton** [comment] 2022-04-25 21:43
I'm fairly certain the problem is with the crc32() function in libz v1.2.12. The Java code just calls through to that. I can duplicate the problem by using the bytes from STPInstallTreeMessages-ALL-Any.jar and using a CRC32 instance to calculate the checksum. If you call update() with all the bytes at the same time, it calculates the expected checksum. If the bytes passed in smaller chunks, such as the first 1235 followed by the last 9 (as read from the ZipInputStream), then the CRC calculation is incorrect. It's also incorrect if you pass in 1 byte at a time. This problem should be reported to the provider of libz.

 The Adoptium/Hotspot JDK loads libz from `/opt/freeware/lib/libz.a[libz.so.1]` rather than the location specified by the LIBPATH. So it would continue to use the v1.2.11 version from there.

**Comment by B-Nebel** [comment] 2022-04-26 13:27
The problematic libz.a v1.2.12 is in fact located in /opt/freeware/lib and if Adoptium loads it from there, why doesn't the reproducer fail with it? You can just copy non-working/libz.a.1.12 from the reproducer to /opt/freeware/lib/libz.a to try this.

But I also can not agree with your last sentence, because I just verified that Adoptium v11.0.14 loads the zlib.a from locations specified with LIBPATH in the same way as Semeru v11.0.14 does:
$ pwd
/opt/Adoptium/jdk-11.0.14.1+1/bin

$ ./java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

$ LIBPATH=/lib:/usr/lib ldd java
java needs:
         /lib/libz.a(libz.so.1)
         /lib/libpthreads.a(shr_xpg5_64.o)
         /lib/libc.a(shr_64.o)
         /unix
         /lib/libcrypt.a(shr_64.o)

$ LIBPATH="" ldd java
java needs:
         /opt/freeware/lib/libz.a(libz.so.1)
         /usr/lib/libpthreads.a(shr_xpg5_64.o)
         /usr/lib/libc.a(shr_64.o)
         /unix
         /usr/lib/libcrypt.a(shr_64.o)
$

**Comment by pshipton** [comment] 2022-04-26 17:19
I don't think ldd is showing where the library is actually loaded. I used `genld -l` to show the libraries loaded by the running processes. Can you pls check where the running Hotspot process loaded the library.

I don't have /opt/freeware/lib updated on the machine I have access to. 

>  You can just copy non-working/libz.a.1.12 from the reproducer to /opt/freeware/lib/libz.a to try this.

If I had root access.

**Comment by pshipton** [comment] 2022-04-26 17:24
I checked again and I see `non-working/libz.a.1.12` used now, I must have done something wrong. I'll keep looking why Semeru can't get the right crc.

**Comment by pshipton** [comment] 2022-04-26 21:38
@zl-wang do you have any ideas about this? As far as I can tell, Semeru is calling libz crc32() with the correct values. I suspect some global setting is modified by OpenJ9 which affects how libz 1.2.12 works. Hotspot works fine with the same data, and a standalone C problem also works fine.

**Comment by zl-wang** [comment] 2022-04-27 12:28
@pshipton  my thought process as follows ...

we have a fast-path implementation of CRC32.update() etc when JIT is active (42x faster than the normal).  JIT redirects these calls to the assembly routines. But I saw mentioned it can fail with -Xint too, so that I think that redirection is irrelevant in this case.

we also prefer to load the NX version of libz (this library takes advantages of hardware GZIP accelerator on the chip), as long as NX-libz is available and AIX enables NX acceleration (i.e.  AIX7.2 TL4 and later, and the machine is Power9 at least). But I felt this is irrelevant as well, since it only failed with the particular install of libz. If the NX version is the problem, it can fail without this new installation too.

Moving forward:  we need to land on exactly when it failed, otherwise it looks like the new libz being the problem itself.

**Comment by pshipton** [comment] 2022-04-27 12:39
@zl-wang it does only fail with the new libz, but only when called from OpenJ9 JNI. If I call it from a small C program it's fine. Hotspot is also fine. That's why I'm wondering if OpenJ9 changes any settings that might affect the new libz.

**Comment by pshipton** [comment] 2022-04-27 12:43
btw I checked the compile and line options for libzip.so (which contains the JNI natives) between Hotspot / Semeru and I don't see any differences (other than -qstackprotect, which is just in the latest version and not 11.0.14.1).

**Comment by zl-wang** [comment] 2022-04-27 12:56
@pshipton  yeah, OpenJ9 does change the LIBPATH setting by prepending the NX-version path before any other (if it is available and enabled). When that happened, NX-libz is definitely the version to be loaded instead of any other.  That was captured in my 2nd point above.

I cannot imagine some mixed-up scenarios happening here yet.  It is more likely the new libz build being the problem (only triggered under particular situations).

**Comment by pshipton** [comment] 2022-04-27 22:51
I don't think this is related to the NX-version path. If you run Semeru on one of our AIX machines the crc is computed correctly. If you modify the LIBPATH to put libz 1.2.12 on the path, then incorrect crc's are computed, but only from OpenJ9 JNI code. I can give you the test case if you want to try it yourself.

**Comment by pshipton** [comment] 2022-04-27 22:53
> only triggered under particular situations

This is my concern, I think somehow OpenJ9 is setting up the particular situation that causes the failure.

**Comment by pshipton** [comment] 2022-04-27 22:56
I should also mention you can run `genld -l` to see that OpenJ9 process has loaded the zlib 1.2.12, and not some NX-version.

**Comment by pshipton** [comment] 2022-05-03 20:33
Simple test case to reproduce the problem
```
import java.util.zip.*;

public class CRCTest {
        public static void main(String[] args) throws Exception {
                CRC32 crc1 = new CRC32();
                crc1.update(0x50);
                System.out.println(Long.toHexString(crc1.getValue()));
                crc1.update(0x4b);
                System.out.println(Long.toHexString(crc1.getValue()) + " should be 1a6cd7b3");
                if (args.length > 0) {
                        Object o = new Object();
                        synchronized(o) {
                                o.wait();
                        }
                }
        }
}
```

[test.zip](https://github.com/eclipse-openj9/openj9/files/8614107/test.zip)

Put the libz 1.2.12 on the LIBPATH: `export LIBPATH=non-working:/lib:/usr/lib`

Run the test:
`jdk-11.0.15+10/bin/java -cp src CRCTest`

Non-working output:
```
b969be79
e56cd7b3 should be 1a6cd7b3
```

`genld -l` can be used to show which libz is loaded (shows all running processes):
`/home/jenkins/peter/repro/non-working/libz.a[libz.so.1]`

**Comment by pshipton** [comment] 2022-05-04 02:24
I figured out how to reproduce the problem. When `crc` is declared as `int` then it doesn't work. If it's `unsigned int` or `long` then it does work. This is different behaviour from the older libz.so. The JNI natives are using `jint` for the crc. I still don't understand why Adoptium works, considering it's the same JNI code, and the types should be the same. 

test.c
```
#include <stdio.h>
#include <zlib.h>

int main(int argc, char** argv) {
        char data2[] = {0x50, 0x4b};
        int crc = crc32(0, &data2[0], 1);
        crc = crc32(crc, &data2[1], 1);
        printf("%x\n", crc);
}
```
```
xlc_r -o test -lz -q64 -qpic test.c
./test
e56cd7b3
```

**Comment by pshipton** [comment] 2022-05-04 02:44
It seems Adoptium doesn't actually call the JNI native, even when running with `-Xint`.

**Comment by B-Nebel** [comment] 2022-05-04 06:11
I've got another hint that in Adoptium the libz.a functions are linked in a different way. I created a libz from source and added some fprintf statements to its basic library functions. I verified this trace got written successfully with Semeru, but then with Adoptium the trace was not printed although I could see the correct libz path with genld in the Adoptium java process.

**Comment by zl-wang** [comment] 2022-05-04 11:31
are you saying zlib.h prototyping changed in this newer version?
sign-extension vs. zero-extension when crc parameter is passed in.  i bet that must be the problem ...

**Comment by B-Nebel** [comment] 2022-05-04 12:24
No, the prototype didn't change in zlib v1.2.12 and the docu is still valid (https://zlib.net/manual.html#Basic). I'm asking, if Semeru really does follow the prototype and pass the crc parameter as an unsigned long.

**Comment by zl-wang** [comment] 2022-05-04 13:20
i don't understand then.  if the visible prototype didn't change, i don't expect the behavior change unless the compiler used changed.  external declaration (crc data type) can change the result ... that led me to believe that internal crc32 behavior hasn't changed.

**Comment by pshipton** [comment] 2022-05-04 15:56
> Doesn't this mean Semeru is not handling the 64-bit values correctly?

It's not Semeru/OpenJ9 code, it's OpenJDK code that is wrong. OpenJDK/Adoptium would see the same problem if they actually called it.

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/native/libzip/CRC32.c
aka
https://github.com/openjdk/jdk11u/blob/master/src/java.base/share/native/libzip/CRC32.c

The code can be fixed, but atm the next release is in July, which isn't that helpful to anyone trying to use the new zlib now.

Something changed in zlib, because the older version works when using `int`, and the newer version doesn't. Although the prototype didn't change, perhaps the internal handling of the parameter did.

**Comment by pshipton** [comment] 2022-05-04 18:26
I tried it with the master zlib code from https://github.com/madler/zlib/tags
v1.2.11 works with int
v1.2.12 doesn't work with int

It's not specific to AIX, the same problem happens on x86.

**Comment by keithc-ca** [comment] 2022-05-05 15:00
I find it hard to justify the use of `uLong` in `crc32()` and `adler32()` (these are 32-bit functions), but I expect it's unlikely that zlib will be changing that anytime soon.

**Comment by pshipton** [comment] 2022-05-05 21:53
The fixes are merged.

**Closed by pshipton** 2022-05-05 21:53 UTC
Labels: userRaised, comp:jclextensions
