### ISSUE TITLE
Tests for GC rotating verbose log

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#13891] opened 2021-11-09 22:15 UTC
The test was originally added in PR https://github.com/eclipse-openj9/openj9/pull/12794/, but we still hit some internal vmfram failures (see Peter's comment https://github.com/eclipse-openj9/openj9/pull/12794#issuecomment-876819790). Currently, the test is excluded (https://github.com/eclipse-openj9/openj9/pull/13152). We need to investigate and reinclude this test. 

FYI @RSalman

**Comment by llxia** [comment] 2021-11-24 15:34
@LongyuZhang could you help with this? Thanks

**Comment by RSalman** [comment] 2021-11-25 01:07
triage slack thread @ `archives/C5TUEK814/p1625794386109700` might be helpful

**Comment by LongyuZhang** [comment] 2021-11-29 19:06
cmdLineTester_GCRegressionTests passed on Jenkins with JDK8 xlinux (hyc_grinder 19662); the failure is reproduced on Vmfarm (vmfarm/job_output.php?id=20686808):
Four tests failed with `[ERR] cat: xxxxxxxxxxx: No such file or directory`, need to further investigate on vmfarm machines about this failure.
```
Executing command: "/bluebird/builds/bld_17035/sdk/xa6480/bin/java"  -Xgcpolicy:metronome -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s,5,1 -cp /bluebird/builds/bld_17035/jvmtest/test/SE80/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s
Test start time: 2021/11/24 17:47:09 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s.005
Time spent starting: 2 milliseconds
Time spent executing: 4 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: foo%s%s%s%s%s%s.005: No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]

Executing command: rm foo*.*

Executing command: "/bluebird/builds/bld_17035/sdk/xa6480/bin/java"  -Xgcpolicy:metronome -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s1234567%s%s%s%s%s%s!@%^*%s%s%s%s%s%sabcdef.#,5,1 -cp /bluebird/builds/bld_17035/jvmtest/test/SE80/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s and other random symbols
Test start time: 2021/11/24 17:47:11 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s1234567%s%s%s%s%s%s!@%^*%s%s%s%s%s%sabcdef.005
Time spent starting: 5 milliseconds
Time spent executing: 7 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: 'foo%s%s%s%s%s%s1234567%s%s%s%s%s%s!@%^*%s%s%s%s%s%sabcdef.005': No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]

Executing command: rm foo*.*

Executing command: "/bluebird/builds/bld_17035/sdk/xa6480/bin/java"  -Xgcpolicy:metronome -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i,5,1 -cp /bluebird/builds/bld_17035/jvmtest/test/SE80/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s %c %i
Test start time: 2021/11/24 17:47:12 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i.005
Time spent starting: 3 milliseconds
Time spent executing: 6 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i.005: No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]

Executing command: rm foo*.*

Executing command: "/bluebird/builds/bld_17035/sdk/xa6480/bin/java"  -Xgcpolicy:metronome -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i1234567!@%^*%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%isabcdef.#,5,1 -cp /bluebird/builds/bld_17035/jvmtest/test/SE80/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s %c %i and other random symbols
Test start time: 2021/11/24 17:47:13 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i1234567!@%^*%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%isabcdef.005
Time spent starting: 3 milliseconds
Time spent executing: 5 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: 'foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i1234567!@%^*%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%isabcdef.005': No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]
```

**Comment by llxia** [comment] 2022-01-28 15:27
@LongyuZhang any update on this issue? Could we re-enable this test in Jenkins and exclude it on vmfarm for now? That means excluding it for JDK8 and ibm.

**Comment by LongyuZhang** [comment] 2022-01-28 15:43
@llxia Sure, I can exclude it for JDK8 and ibm for now, and work on figuring out vmfarm machines. Thanks.

**Comment by RSalman** [comment] 2022-01-31 19:09
I took a look at the failure job that you posted again and realized it's running with metronome policy. It won't generate rotating logs that we're testing for,  so it should be disabled for metronome `(cmdLineTester_GCRegressionTests_Mode301_0, JVM_OPTIONS:  -Xgcpolicy:metronome -Xnocompressedrefs)`

**Comment by RSalman** [comment] 2022-01-31 19:13
In `test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml` we have

```
<!-- Metronome does not cause multiple verboseGC logging files -->
<!--
<exclude id="GC rotating verbose log file name contains %s" platform="Mode301" shouldFix="false"><reason>Metronome does not cause multiple verboseGC logging files</reason></exclude>
<exclude id="GC rotating verbose log file name contains %s and other random symbols" platform="Mode301" shouldFix="false"><reason>Metronome does not cause multiple verboseGC logging files</reason></exclude>
<exclude id="GC rotating verbose log file name contains %s %c %i" platform="Mode301" shouldFix="false"><reason>Metronome does not cause multiple verboseGC logging files</reason></exclude>
<exclude id="GC rotating verbose log file name contains %s %c %i and other random symbols" platform="Mode301" shouldFix="false"><reason>Metronome does not cause multiple verboseGC logging files</reason></exclude>
-->
```

**Comment by LongyuZhang** [comment] 2022-02-01 21:16
Hi @RSalman , after creating the new `cmdLineTester_GCRotatingVerboseLogTests`, it now also passed Vmfarm on xlinux, win, and zos (build_id=21493), could you check if these commands are the ones we intend to test? Thanks.

**Comment by RSalman** [comment] 2022-02-02 19:38
Looks good! However, I noticed that there are 3 new jobs for each platform as a result of these new tests `cmdLineTester_GCRotatingVerboseLogTests_0-*`... Ideally the rotating log jobs are just test cases that would fall under existing `cmdLineTester_GCRegressionTests_*` test job. The reason I say this because `GCRegressionTests` seems to be running a set of tests of which includes  `Testing: -verbose:gc -Xverbosegclog:<verylong>,10,10 - use a very long log file name` this is similar to what we're introducing with rotating log tests.

**Comment by RSalman** [comment] 2022-02-02 19:40
But the test team knows best on organizing these. From my side, they are good and working

**Comment by LongyuZhang** [comment] 2022-02-02 20:11
In this case, I think we can enable the `cmdLineTester_GCRotatingVerboseLogTests` tests on vmfarm to get these new tests running first, later if needed, we can combine the two tests, since each sub-test will still run individually even combined in one single test.

**Comment by LongyuZhang** [comment] 2022-04-05 20:42
I think we can close this issue. Thanks.

**Closed** 2022-05-02 14:38 UTC
Labels: comp:test
