### ISSUE TITLE
Failure in TestResourceScope 

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13234] opened 2021-07-22 13:33 UTC
Related to the closeScope0 native

```
22:08:20  test TestResourceScope.testScopeHandles(TestResourceScope$$Lambda$95/0x00000000e409a788@a0705023): success
22:08:20  test TestResourceScope.testScopeHandles(TestResourceScope$$Lambda$96/0x00000000e4063fa8@edc2f261): success
22:08:20  test TestResourceScope.testSharedMultiThread(TestResourceScope$$Lambda$85/0x00000000e40ef7a0@d977f7e9): failure
22:08:20  java.lang.AssertionError: expected [4950] but found [4804]
22:08:20  	at org.testng.Assert.fail(Assert.java:99)
22:08:20  	at org.testng.Assert.failNotEquals(Assert.java:1037)
22:08:20  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
22:08:20  	at org.testng.Assert.assertEquals(Assert.java:122)
22:08:20  	at org.testng.Assert.assertEquals(Assert.java:907)
22:08:20  	at org.testng.Assert.assertEquals(Assert.java:917)
22:08:20  	at TestResourceScope.testSharedMultiThread(TestResourceScope.java:149)
22:08:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:08:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:08:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:08:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:08:20  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
22:08:20  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
22:08:20  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
22:08:20  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
22:08:20  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
22:08:20  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
22:08:20  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
22:08:20  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
22:08:20  	at org.testng.TestRunner$$Lambda$79/0x00000000e40cb2a8.accept(Unknown Source)
22:08:20  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
22:08:20  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
22:08:20  	at org.testng.TestRunner.run(TestRunner.java:585)
22:08:20  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
22:08:20  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
22:08:20  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
22:08:20  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
22:08:20  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
22:08:20  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
22:08:20  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
22:08:20  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
22:08:20  	at org.testng.TestNG.runSuites(TestNG.java:1069)
22:08:20  	at org.testng.TestNG.run(TestNG.java:1037)
22:08:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:08:20  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:08:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:08:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
22:08:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:08:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
22:08:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:08:20  	at java.base/java.lang.Thread.run(Thread.java:883)
22:08:20  test TestResourceScope.testSharedMultiThread(TestResourceScope$$Lambda$86/0x00000000e40ef910@d77b72f8): success
22:08:20  test TestResourceScope.testSharedMultiThread(TestResourceScope$$Lambda$87/0x00000000e40efa70@45749fcd): success
22:08:20  test TestResourceScope.testSharedSingleThread(TestResourceScope$$Lambda$85/0x00000000e40ef7a0@d977f7e9): success
22:08:20  test TestResourceScope.testSharedSingleThread(TestResourceScope$$Lambda$86/0x00000000e40ef910@d77b72f8): success
22:08:20  test TestResourceScope.testSharedSingleThread(TestResourceScope$$Lambda$87/0x00000000e40efa70@45749fcd): success
```

**Comment by tajila** [comment] 2021-07-22 13:33
@EricYangIBM please take a look.

**Comment by tajila** [comment] 2021-07-22 13:37
You can find the test here, https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestResourceScope.java

**Comment by EricYangIBM** [comment] 2021-07-22 17:32
The test starts threads 0-99 while the main thread closes the single scope. Threads 0-99 add a cleaner action (which executes upon close(), adding its thread id to an AtomicInteger so the total should be 4950) which if fails (already closed -> IllegalStateException) adds to the AtomicInteger manually.  
Regardless of if `closeScope0` returns true or false (no throw IllegalStateException or throw), the close/cleanup action isn't affected. The error comes from some threads not executing their close action which I don't think is related to closeScope0.

**Comment by tajila** [comment] 2021-07-26 20:25
I've looked at the test case more closely, it may not be related to closescope, but we still need to investigate it. We need to understand why some threads did not behave as intended. Or if this is an issue in the interaction between native scopes and cleaners.

**Comment by EricYangIBM** [comment] 2021-07-28 20:49
Where did this fail? The test passes for me locally

**Comment by tajila** [comment] 2021-07-28 21:16
JDK17 (staging repo) on x86-64

**Comment by EricYangIBM** [comment] 2021-07-29 19:21
I have reproduced the failure two or three times and never again. I believe the issue is that there are some close actions not added to the scope's resourceList. Maybe the issue is with [VarHandle.compareAndExchangeRelease](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/SharedScope.java#L138) or [VarHandle.weakCompareAndSetRelease](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/SharedScope.java#L160)?

**Comment by EricYangIBM** [comment] 2021-07-29 19:38
Changes:
```java
@Test(dataProvider = "cleaners")
public void testSharedMultiThread(Supplier<Cleaner> cleanerSupplier) {
    AtomicInteger acc = new AtomicInteger();
    Cleaner cleaner = cleanerSupplier.get();
    List<Thread> threads = new ArrayList<>();
    ResourceScope scope = cleaner != null ?
            ResourceScope.newSharedScope(cleaner) :
            ResourceScope.newSharedScope();
    AtomicReference<ResourceScope> scopeRef = new AtomicReference<>(scope);
    boolean action[] = new boolean[N_THREADS];                                                         //Change
    for (int i = 0 ; i < N_THREADS ; i++) {
        int delta = i;
        Thread thread = new Thread(() -> {
            try {
                scopeRef.get().addCloseAction(() -> {
                    // acc.addAndGet(delta);                                                                       //Change
                    System.out.println(acc.addAndGet(delta) + " close action " + delta);   //Change
                    action[delta] = true;                                                                               //Change
                });
            } catch (IllegalStateException ex) {
                // already closed - we need to call cleanup manually
                // acc.addAndGet(delta);                                                                           //Change
                System.out.println(acc.addAndGet(delta) + " manual close " + delta);    //Change
                action[delta] = true;                                                                                  //Change
            }
        });
        threads.add(thread);
    }
    assertEquals(acc.get(), 0);
    threads.forEach(Thread::start);
    // if no cleaner, close - not all segments might have been added to the scope!
    // if cleaner, don't unset the scope - after all, the scope is kept alive by threads
    if (cleaner == null) {
        while (true) {
            try {
                System.out.println("Before close " + acc.get());                                                         //Change
                scope.close();
                System.out.println("Closed scope " + acc.get());
                break;
            } catch (IllegalStateException ise) {
                System.out.println("Close Exception");
                // scope is acquired (by add) - wait some more
            }
        }
    }
    threads.forEach(t -> {
        try {
            t.join();
        } catch (InterruptedException ex) {
            fail();
        }
    });
    for (int i=0; i<N_THREADS; i++) {                                                         //Change
        if (!action[i])
            System.out.println(i);
    }
    if (cleaner == null) {
        assertEquals(acc.get(), IntStream.range(0, N_THREADS).sum());
    } else {
        scope = null;
        scopeRef.set(null);
        int expected = IntStream.range(0, N_THREADS).sum();
        while (acc.get() != expected) {
            kickGC();
        }
    }
}
```
Failing output:
```
Before close 0
108 manual close 18
318 manual close 14
81 manual close 1
538 manual close 57
644 manual close 48
80 manual close 68
481 manual close 54
175 manual close 10
157 manual close 49
243 manual close 2
374 manual close 56
596 manual close 58
287 manual close 28
90 manual close 9
696 manual close 52
304 manual close 17
241 manual close 11
696 manual close 0
230 manual close 55
12 close action 12
702 close action 6
733 close action 31
740 close action 7
745 close action 5
782 close action 37
806 close action 24
893 close action 87
916 close action 23
1013 close action 97
1108 close action 95
1202 close action 94
1240 close action 38
1333 close action 93
1419 close action 86
1504 close action 85
1587 close action 83
1668 close action 81
1756 close action 88
1789 close action 33
1866 close action 77
1950 close action 84
1982 close action 32
2029 close action 47
2068 close action 39
2148 close action 80
2191 close action 43
2213 close action 22
2259 close action 46
2299 close action 40
2374 close action 75
2456 close action 82
2501 close action 45
2542 close action 41
2615 close action 73
2635 close action 20
2711 close action 76
2785 close action 74
2827 close action 42
2871 close action 44
2960 close action 89
3050 close action 90
3149 close action 99
3212 close action 63
3310 close action 98
3314 close action 4
3375 close action 61
3441 close action 66
3491 close action 50
3512 close action 21
3539 close action 27
3590 close action 51
3616 close action 26
3635 close action 19
3726 close action 91
3741 close action 15
3837 close action 96
3929 close action 92
4008 close action 79
4086 close action 78
4158 close action 72
4193 close action 35
4264 close action 71
4289 close action 25
4319 close action 30
4353 close action 34
4423 close action 70
Closed scope 4423
259 manual close 16
427 manual close 53
165 manual close 8
3
13
29
36
59
60
62
64
65
67
69
test TestResourceScope.testSharedMultiThread(TestResourceScope$$Lambda$88/0x000000004c0f8de0@8ca2cf0f): failure
java.lang.AssertionError: expected [4950] but found [4423]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at TestResourceScope.testSharedMultiThread(TestResourceScope.java:162)
```
This looks like for some of the threads neither the close action nor manual close is run. So either the close action wasn't added but didn't throw an exception or it was added but closing the scope didn't invoke the cleanup action. The cleanup walks the linked list of cleanupactions and sets them to `ResourceCleanup.CLOSED_LIST`. Maybe the linked list wasn't set up properly so I think my previous comment may apply.

**Comment by pshipton** [comment] 2021-08-09 15:51
@tajila this is one of the failures blocking jdk17 acceptance, it needs to be resolved or excluded.

**Comment by tajila** [comment] 2021-08-09 16:02
@EricYangIBM can you please add excludes for this

**Comment by EricYangIBM** [comment] 2021-08-09 16:26
Done

**Comment by JasonFengJ9** [comment] 2021-08-19 18:53
The test in question has been excluded, moving to 0.29.

**Comment by babsingh** [comment] 2022-06-13 15:24
Moving this issue from backlog to 0.34 release (Java 19).

**Comment by EricYangIBM** [comment] 2022-06-15 19:44
Is the test failing in the nightly builds?
I tried running 20x linux x86-64 and all passed: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24999/
Something that may have allowed this test to pass now is a change in jcl from jdk 17 to 19:
jdk 17:
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/SharedScope.java#L134-L168
jdk 19:
https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/a9e93826dceb39107f5fa9d7a04604b1bcc73d68/src/java.base/share/classes/jdk/internal/foreign/SharedSession.java#L115-L149

Instead of VarHandle `compareAndExchangeRelease` and `weakCompareAndSetRelease` (what I thought was the culprit https://github.com/eclipse-openj9/openj9/issues/13234#issuecomment-889397297), it now uses `compareAndSet`

**Comment by babsingh** [comment] 2022-06-15 21:08
Closing the issue as per https://github.com/eclipse-openj9/openj9/issues/13234#issuecomment-1156857189.

**Closed by babsingh** 2022-06-15 21:08 UTC
Labels: comp:vm, project:panama
