### ISSUE TITLE
LambdaLoadTest_special_J9_5m_15 crash vmState=0x00020016

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14446] opened 2022-02-07 14:06 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_3/8 - [osx1014-x86-1](https://openj9-jenkins.osuosl.org/computer/osx1014-x86-1)
LambdaLoadTest_special_J9_5m_15
`-Xcompressedrefs -Xgcpolicy:balanced -XXgc:tarokEnableExpensiveAssertions,fvtest_tarokPGCRotateCollectors -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_3/8/system_test_output.tar.gz

```
java -Xjit:vmState=0x00020016
vmState [0x20016]: not a valid vmState
```

```
LT  stderr Type=Segmentation error vmState=0x00020016
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=000000000AA380A0 Handler2=00000000090ADC20 InaccessibleAddress=0000000001471C00
LT  stderr RDI=00007FEDE4D02F80 RSI=000000000C987610 RAX=0000000099669966 RBX=0000000001471C00
LT  stderr RCX=0000000000000001 RDX=0000000000000003 R8=0000000000000003 R9=00007FEDE7145468
LT  stderr R10=0000000701F85098 R11=00007FEDE4D02F80 R12=00007FEDE4D02F80 R13=000000070146F698
LT  stderr R14=0000000000000001 R15=00007FEDE7145468
LT  stderr RIP=000000000C8DC043 GS=0000 FS=0000 RSP=000070000EE29C40
LT  stderr RFlags=0000000000010206 CS=002B RBP=000070000EE29C70 ERR=01471C0000000004
LT  stderr TRAPNO=000000040000000E CPU=1C00000000040000 FAULTVADDR=0000000001471C00
LT  stderr XMM0 0000dfb600000000 (f: 0.000000, d: 1.215267e-309)
LT  stderr XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM2 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
LT  stderr XMM3 4330000000000000 (f: 0.000000, d: 4.503600e+15)
LT  stderr XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
LT  stderr XMM6 3fdbeb4d9da71b7c (f: 2644974336.000000, d: 4.362368e-01)
LT  stderr XMM7 401e7f9c1e980fa9 (f: 513281952.000000, d: 7.624619e+00)
LT  stderr XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00020016
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=000000000AA380A0 Handler2=00000000090ADC20 InaccessibleAddress=000000000142BE00
LT  stderr RDI=00007FEDE4D02F80 RSI=000000000C987610 RAX=0000000099669966 RBX=000000000142BE00
LT  stderr RCX=0000000000000001 RDX=0000000000000003 R8=0000000000000000 R9=00007FEDE5069C68
LT  stderr R10=0000000701C59BC8 R11=00007FEDE4D02F80 R12=00007FEDE4D02F80 R13=0000000701425638
LT  stderr R14=0000000000000001 R15=00007FEDE5069C68
LT  stderr RIP=000000000C8DC043 GS=0000 FS=0000 RSP=000070000EBCEC40
LT  stderr RFlags=0000000000010206 CS=002B RBP=000070000EBCEC70 ERR=0142BE0000000004
LT  stderr TRAPNO=000000040000000E CPU=BE00000000040000 FAULTVADDR=000000000142BE00
LT  stderr XMM0 000089c200000000 (f: 0.000000, d: 7.483430e-310)
LT  stderr XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM2 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
LT  stderr XMM3 4330000000000000 (f: 0.000000, d: 4.503600e+15)
LT  stderr XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
LT  stderr XMM6 3fc5ff3070a793d4 (f: 1890030592.000000, d: 1.718503e-01)
LT  stderr XMM7 401e7f9c1e980fa9 (f: 513281952.000000, d: 7.624619e+00)
LT  stderr XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00020016
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=000000000AA380A0 Handler2=00000000090ADC20 InaccessibleAddress=000000000147AE00
LT  stderr RDI=00007FEDE4D02F80 RSI=000000000C987610 RAX=0000000099669966 RBX=000000000147AE00
LT  stderr RCX=0000000000000001 RDX=0000000000000003 R8=0000000000000003 R9=00007FEDE710DC68
LT  stderr R10=0000000701479088 R11=00007FEDE4D02F80 R12=00007FEDE4D02F80 R13=0000000701479070
LT  stderr R14=0000000000000001 R15=00007FEDE710DC68
LT  stderr RIP=000000000C8DC043 GS=0000 FS=0000 RSP=000070000EC97C40
LT  stderr RFlags=0000000000010206 CS=002B RBP=000070000EC97C70 ERR=0147AE0000000004
LT  stderr TRAPNO=000000040000000E CPU=AE00000000040000 FAULTVADDR=000000000147AE00
LT  stderr XMM0 0000950000000000 (f: 0.000000, d: 8.094141e-310)
LT  stderr XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM2 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
LT  stderr XMM3 4330000000000000 (f: 0.000000, d: 4.503600e+15)
LT  stderr XMM4 3eb45b69d323b3d6 (f: 3542332416.000000, d: 1.213377e-06)
LT  stderr XMM5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
LT  stderr XMM6 3fe55b9354b40bcd (f: 1421085696.000000, d: 6.674287e-01)
LT  stderr XMM7 402d1cb7eea86c0a (f: 4004015104.000000, d: 1.455609e+01)
LT  stderr XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr Module=/Users/jenkins/workspace/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_3/openjdkbinary/j2sdk-image/lib/default/libj9gc29.dylib
LT  stderr Module_base_address=000000000C768000 Symbol=_ZN22MM_GlobalMarkingScheme10scanObjectEP19MM_EnvironmentVLHGCP8J9ObjectNS_10ScanReasonE
LT  stderr Symbol_address=000000000C8DC000
LT  stderr Target=2_90_20220206_93 (Mac OS X 10.14.6)
LT  stderr CPU=amd64 (12 logical CPUs) (0x400000000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr ---------------------------------------
LT  stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2022/02/06 08:42:04 - please wait.
LT  stderr Module=/Users/jenkins/workspace/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_3/openjdkbinary/j2sdk-image/lib/default/libj9gc29.dylib
LT  stderr Module_base_address=000000000C768000 Symbol=_ZN22MM_GlobalMarkingScheme10scanObjectEP19MM_EnvironmentVLHGCP8J9ObjectNS_10ScanReasonE
LT  stderr Symbol_address=000000000C8DC000
LT  stderr Target=2_90_20220206_93 (Mac OS X 10.14.6)
LT  stderr CPU=amd64 (12 logical CPUs) (0x400000000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr ---------------------------------------
LT  stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2022/02/06 08:42:04 - please wait.
LT  stderr Module=/Users/jenkins/workspace/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_3/openjdkbinary/j2sdk-image/lib/default/libj9gc29.dylib
LT  stderr Module_base_address=000000000C768000 Symbol=_ZN22MM_GlobalMarkingScheme10scanObjectEP19MM_EnvironmentVLHGCP8J9ObjectNS_10ScanReasonE
LT  stderr Symbol_address=000000000C8DC000
LT  stderr Target=2_90_20220206_93 (Mac OS X 10.14.6)
LT  stderr CPU=amd64 (12 logical CPUs) (0x400000000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr ---------------------------------------
```

@0xdaryl @dmitripivkine

**Comment by dmitripivkine** [comment] 2022-02-07 14:37
`vmState=0x00020016` is  `OMRVMSTATE_GC_CONCURRENT_MARK_TRACE`, I am not sure why test decided it is `not a valid vmState`

**Comment by pshipton** [comment] 2022-02-07 14:44
It's not the test that output `not a valid vmState`, it's `-Xjit:vmState=0x00020016` which normally shows what the state means without having to look into the code.

**Comment by dmitripivkine** [comment] 2022-02-07 17:12
```
> !mm_packet 0x0000000024B74068
MM_Packet at 0x24b74068 {
  Fields for MM_Base:
  Fields for MM_BaseNonVirtual:
	0x0: const U8* _typeId = !j9x 0x0000000000000000
  Fields for MM_Packet:
	0x8: U64* _baseAddress = !j9x 0x0000000024B7C5F8
	0x10: U64* _basePtr = !j9x 0x0000000024B7C5F8
	0x18: U64* _topPtr = !j9x 0x0000000024B7D5F8
	0x20: U64* _currentPtr = !j9x 0x0000000024B7CFE8 <-------
	0x28: U64 _sublistIndex = 0x0000000000000001 (1)
	0x30: class MM_EnvironmentBase* _owner = !mm_environmentvlhgc 0x00007FEDE710DC68
	0x38: class MM_Packet* _next = !mm_packet 0x0000000000000000
	0x40: class MM_Packet* _previous = !mm_packet 0x0000000000000000
}
> !j9x 0x0000000024B7CF80,80
0x24B7CF80 :  0000000701f96118 0000000701f96038 [ .a......8`...... ]
0x24B7CF90 :  0000000701f94688 00000007014d5dc0 [ .F.......]M..... ]
0x24B7CFA0 :  00000007014ab590 00000007014ab4f8 [ ..J.......J..... ]
0x24B7CFB0 :  0000000701d8b170 0000000701d8b298 [ p............... ]
0x24B7CFC0 :  0000000701daf758 0000000701daf770 [ X.......p....... ]
0x24B7CFD0 :  0000000701daf800 0000000701d9d738 [ ........8....... ]
0x24B7CFE0 :  00000007014790a0 0000000701479070 [ ..G.....p.G..... ] <--- bogus value
0x24B7CFF0 :  0000000701479088 00000007014790b8 [ ..G.......G..... ]

> !markmap ismarked 0x0000000701479070
Object 0x0000000701479070 is not marked

0x701479050 :  000000001370c600 0000000000000000 [ ..p............. ]
0x701479060 :  e0313e0800000002 e028c68500000004 [ .....>1.......(. ]
0x701479070 :  000000070147ae41 0000000000000808 [ A.G............. ] <-- hole
0x701479080 :  e0286a7de03ad702 e028f2731336ec00 [ ..:.}j(...6.s.(. ]
0x701479090 :  8c8f89f500000001 0000000000000000 [ ................ ]
0x7014790A0 :  e028f2891336ec00 0ac129bc00000001 [ ..6...(......).. ]
```
This is duplicate of https://github.com/eclipse-openj9/openj9/issues/14396

**Closed by dmitripivkine** 2022-02-07 17:12 UTC
Labels: comp:gc, comp:jit, test failure, segfault
