### ISSUE TITLE
jdk_vector_0_FAILED jdk/incubator/vector/Byte64VectorLoadStoreTests.java NPE at Byte64VectorLoadStoreTests.loadStoreArray(Byte64VectorLoadStoreTests.java:292)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16244] opened 2022-11-01 22:15 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_mac/22/)(`osxrt4`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-71f768a8b, JRE 19 Mac OS X amd64-64-Bit Compressed References 20221018_74 (JIT enabled, AOT enabled)
OpenJ9   - 71f768a8b
OMR      - 556374a61
JCL      - 9d79dbc153 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_vector_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F74%2Fibm-semeru-open-debugimage_x64_mac_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F74%2Fibm-semeru-open-jre_x64_mac_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F74%2Fibm-semeru-open-testimage_x64_mac_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-mac-x64-openj9%2F74%2Fibm-semeru-open-jdk_x64_mac_JDK19U_2022-10-30-16-47.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21sw.os.osx.10_11&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-10-30T20:38:29.477Z] variation: Mode150
[2022-10-30T20:38:29.477Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-10-30T20:40:04.142Z] TEST: jdk/incubator/vector/Byte64VectorLoadStoreTests.java

[2022-10-30T20:40:04.143Z] test Byte64VectorLoadStoreTests.loadStoreArray(byte[i + 1]): failure
[2022-10-30T20:40:04.143Z] java.lang.NullPointerException
[2022-10-30T20:40:04.143Z] 	at Byte64VectorLoadStoreTests.loadStoreArray(Byte64VectorLoadStoreTests.java:292)
[2022-10-30T20:40:04.143Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-10-30T20:40:04.143Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2022-10-30T20:40:04.143Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2022-10-30T20:40:04.143Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2022-10-30T20:40:04.143Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2022-10-30T20:40:04.143Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2022-10-30T20:40:04.143Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2022-10-30T20:40:04.143Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2022-10-30T20:40:04.143Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2022-10-30T20:40:04.143Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2022-10-30T20:40:04.143Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2022-10-30T20:40:04.143Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2022-10-30T20:40:04.143Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2022-10-30T20:40:04.143Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2022-10-30T20:40:04.143Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2022-10-30T20:40:04.143Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2022-10-30T20:40:04.143Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2022-10-30T20:40:04.143Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2022-10-30T20:40:04.143Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-10-30T20:40:04.143Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2022-10-30T20:40:04.143Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-10-30T20:40:04.143Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)

[2022-10-30T20:40:04.144Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2022-10-30T20:40:04.144Z] --------------------------------------------------
[2022-10-30T21:20:34.633Z] Test results: passed: 66; failed: 1
[2022-10-30T21:20:48.309Z] Report written to /Users/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16671508355425/jdk_vector_0/report/html/report.html
[2022-10-30T21:20:48.309Z] Results written to /Users/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16671508355425/jdk_vector_0/work
[2022-10-30T21:20:48.309Z] Error: Some tests failed or other problems occurred.
[2022-10-30T21:20:48.309Z] 
[2022-10-30T21:20:48.309Z] jdk_vector_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29195/) - all passed

**Comment by JasonFengJ9** [comment] 2023-02-21 23:21
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_mac/39/)(`mac11x64rt10`)
```
openjdk version "19.0.2" 2023-01-17
IBM Semeru Runtime Open Edition 19.0.2+7 (build 19.0.2+7)
Eclipse OpenJ9 VM 19.0.2+7 (build master-042864b42, JRE 19 Mac OS X amd64-64-Bit Compressed References 20230117_46 (JIT enabled, AOT enabled)
OpenJ9   - 042864b42
OMR      - b86560818
JCL      - edc950934d based on jdk-19.0.2+7)

[2023-02-18T21:43:03.001Z] variation: Mode150
[2023-02-18T21:43:03.001Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-02-18T21:44:06.890Z] TEST: jdk/incubator/vector/Byte64VectorLoadStoreTests.java

[2023-02-18T21:44:06.892Z] test Byte64VectorLoadStoreTests.loadStoreArray(byte[i + 1]): failure
[2023-02-18T21:44:06.892Z] java.lang.NullPointerException
[2023-02-18T21:44:06.892Z] 	at Byte64VectorLoadStoreTests.loadStoreArray(Byte64VectorLoadStoreTests.java:292)
[2023-02-18T21:44:06.892Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-02-18T21:44:06.892Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[2023-02-18T21:44:06.892Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[2023-02-18T21:44:06.893Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[2023-02-18T21:44:06.893Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2023-02-18T21:44:06.893Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[2023-02-18T21:44:06.893Z] 	at org.testng.TestRunner.run(TestRunner.java:585)
[2023-02-18T21:44:06.893Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[2023-02-18T21:44:06.893Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[2023-02-18T21:44:06.893Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[2023-02-18T21:44:06.893Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[2023-02-18T21:44:06.893Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[2023-02-18T21:44:06.893Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[2023-02-18T21:44:06.893Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[2023-02-18T21:44:06.893Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[2023-02-18T21:44:06.893Z] 	at org.testng.TestNG.runSuites(TestNG.java:1069)
[2023-02-18T21:44:06.893Z] 	at org.testng.TestNG.run(TestNG.java:1037)
[2023-02-18T21:44:06.893Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2023-02-18T21:44:06.893Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2023-02-18T21:44:06.893Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-02-18T21:44:06.893Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-02-18T21:44:06.893Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-02-18T21:44:06.893Z] 	at java.base/java.lang.Thread.run(Thread.java:1573)

[2023-02-18T22:06:26.205Z] jdk_vector_0_FAILED
```

**Comment by pshipton** [comment] 2023-02-22 05:43
@gita-omr fyi

**Comment by JasonFengJ9** [comment] 2023-05-08 20:59
[JDK20 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_x86-64_mac/6/)(`osxrt6`)
```
openjdk version "20.0.1" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9 (build 20.0.1+9)
Eclipse OpenJ9 VM 20.0.1+9 (build master-8f80c760e, JRE 20 Mac OS X amd64-64-Bit Compressed References 20230418_19 (JIT enabled, AOT enabled)
OpenJ9   - 8f80c760e
OMR      - de6212d59
JCL      - 66a4d4869 based on jdk-20.0.1+9)

[2023-05-08T05:21:10.117Z] variation: Mode650
[2023-05-08T05:21:10.117Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-05-08T05:27:14.642Z] TEST: jdk/incubator/vector/Byte64VectorLoadStoreTests.java

[2023-05-08T05:27:14.644Z] test Byte64VectorLoadStoreTests.loadStoreArray(byte[i + 1]): failure
[2023-05-08T05:27:14.644Z] java.lang.NullPointerException
[2023-05-08T05:27:14.644Z] 	at Byte64VectorLoadStoreTests.loadStoreArray(Byte64VectorLoadStoreTests.java:292)
[2023-05-08T05:27:14.644Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

[2023-05-08T05:27:14.645Z] jdk/incubator/vector/Byte64VectorLoadStoreTests.java
[2023-05-08T05:27:14.645Z] Total tests run: 228, Passes: 227, Failures: 1, Skips: 0

[2023-05-08T06:11:29.262Z] Test results: passed: 71; failed: 1
[2023-05-08T06:12:19.505Z] Report written to /Users/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16835041582855/jdk_vector_1/report/html/report.html
[2023-05-08T06:12:19.505Z] Results written to /Users/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16835041582855/jdk_vector_1/work
[2023-05-08T06:12:19.505Z] Error: Some tests failed or other problems occurred.
[2023-05-08T06:12:19.505Z] -----------------------------------
[2023-05-08T06:12:19.505Z] jdk_vector_1_FAILED
```

**Comment by gita-omr** [comment] 2023-06-15 17:46
Looks similar to https://github.com/eclipse-openj9/openj9/issues/17462

**Comment by gita-omr** [comment] 2023-06-15 17:49
@BradleyWood please check if it's a duplicate of #17462

**Comment by JasonFengJ9** [comment] 2023-06-19 15:30
[JDK20 0.40.0 milestone 1 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_x86-64_mac/14/)(`mac12x64rt15`)
```
[2023-06-16T18:03:19.658Z] variation: Mode650
[2023-06-16T18:03:19.658Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-06-16T18:04:25.724Z] TEST: jdk/incubator/vector/Byte64VectorLoadStoreTests.java

[2023-06-16T18:04:25.725Z] test Byte64VectorLoadStoreTests.loadStoreArray(byte[i + 1]): failure
[2023-06-16T18:04:25.725Z] java.lang.NullPointerException
[2023-06-16T18:04:25.726Z] 	at Byte64VectorLoadStoreTests.loadStoreArray(Byte64VectorLoadStoreTests.java:292)
[2023-06-16T18:04:25.726Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

[2023-06-16T18:04:25.727Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
[2023-06-16T18:04:25.727Z] --------------------------------------------------
[2023-06-16T18:24:29.400Z] Test results: passed: 71; failed: 1
[2023-06-16T18:24:45.885Z] Report written to /Users/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16869300128066/jdk_vector_1/report/html/report.html
[2023-06-16T18:24:45.886Z] Results written to /Users/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_x86-64_mac/aqa-tests/TKG/output_16869300128066/jdk_vector_1/work
[2023-06-16T18:24:45.886Z] Error: Some tests failed or other problems occurred.
[2023-06-16T18:24:45.886Z] -----------------------------------
[2023-06-16T18:24:45.886Z] jdk_vector_1_FAILED
```

**Comment by BradleyWood** [comment] 2023-07-12 14:02
I think this is a duplicate of #17462. Let me know if this issue has popped up after eclipse/omr#7047 was merged.

**Comment by pshipton** [comment] 2023-07-12 23:48
@BradleyWood the failure in https://github.com/eclipse-openj9/openj9/issues/16244#issuecomment-1597387893 is on the 0.40 branch, which doesn't contain https://github.com/eclipse/omr/pull/7047 (also the failure occurs 3 weeks ago but the PR was merged 2 weeks ago).

**Comment by pshipton** [comment] 2023-07-12 23:48
Or are you saying you think the issue is fixed since https://github.com/eclipse/omr/pull/7047? It won't be fixed in the 0.40 branch.

**Comment by BradleyWood** [comment] 2023-07-13 13:45
I think its same issue based solely on the fact that the vector API would emit a shift of 0 for vectors of type Byte64 and this issue also manifests itself as an unexpected NPE. eclipse/omr#7047 fixes handling of shift opcodes by 0. However, I didn't investigate further which is why I was asking if it has been seen recently.

**Comment by gita-omr** [comment] 2023-07-13 18:43
This most likely will be fixed by https://github.com/eclipse/omr/pull/7047. @pshipton do you think we should double deliver?

**Comment by pshipton** [comment] 2023-07-13 18:58
No, it's too late to accept more changes into 0.40.

**Comment by gita-omr** [comment] 2023-07-25 17:21
Then maybe we should just close it?

**Closed** 2023-07-25 17:23 UTC
Labels: comp:jit, test failure
