### ISSUE TITLE
jcmd Dump.system fails on macOS: pwrite() error writing segment data:: Bad address

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#14192] opened 2021-12-20 23:03 UTC
Java -version output
--------------------

Output from `java -version`:

```
% java -version
openjdk version "11.0.13" 2021-10-19
IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8)
Eclipse OpenJ9 VM 11.0.13.0 (build openj9-0.29.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20211021_224 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 2d83aa3b76 based on jdk-11.0.13+8)
```

Summary of problem
------------------

As a follow-on to [Issue 12438 (jcmd Dump.system hangs on macOS)](https://github.com/eclipse-openj9/openj9/issues/12438), `jcmd Dump.system` no longer hangs but it fails with:

```
JVMDUMP034I User requested System dump using '/Users/kevin/git/TMDA/builds/core.20211220.145445.4412.0002.dmp' through com.ibm.jvm.Dump.systemDumpToFile
pwrite() error writing segment data:: Bad address
JVMDUMP012E Error in System dump: /Users/kevin/git/TMDA/builds/core.20211220.145445.4412.0002.dmp
```

An additional problem is that `jcmd` returns success even though the dump creation failed:

```
% jcmd $(pgrep -f jca4611) Dump.system
Dump written to /Users/kevin/git/TMDA/builds/core.20211220.145445.4412.0002.dmp
% ls -l /Users/kevin/git/TMDA/builds/core.20211220.145445.4412.0002.dmp
ls: /Users/kevin/git/TMDA/builds/core.20211220.145445.4412.0002.dmp: No such file or directory
```

Steps:

1. Download TMDA:
   ```
   wget https://public.dhe.ibm.com/software/websphere/appserv/support/tools/jca/jca4611.jar
   ```
2. Download [Semeru Runtime Open Edition 11.0.13.0 JDK](https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.13%2B8_openj9-0.29.0/ibm-semeru-open-jdk_x64_mac_11.0.13_8_openj9-0.29.0.tar.gz) into some directory, run `xattr -d com.apple.quarantine ibm-semeru-open-jdk_x64_mac_11.0.13_8_openj9-0.29.0.tar.gz`, and add the `bin` directory to `PATH`:
   ```
   export PATH=/Users/kevin/work/semeruopen/macos/11.0.13.0/jdk-11.0.13+8/Contents/Home/bin/:${PATH}
   ```
3. Run TMDA:
   ```
   java -jar jca4611.jar
   ```
4. In another window, run `Dump.system`:
   ```
   jcmd $(pgrep -f jca4611) Dump.system
   ```

**Comment by pshipton** [comment] 2021-12-20 23:54
@tajila @mikezhang1234567890

**Comment by kgibm** [comment] 2021-12-21 19:09
FYI, here are software and hardward information for my mac. I'm glad to run any additional tracing or custom builds.

```
% system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 12.0.1 (21A559)
      Kernel Version: Darwin 21.1.0
      Boot Volume: MainDisk
      Boot Mode: Normal
      Computer Name: [...]
      User Name: [...]
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 40 minutes

% system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 9 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 1715.40.15.0.0 (iBridge: 19.16.10549.0.0,0)
      OS Loader Version: 540.40.4~45
      Serial Number (system): [...]
      Hardware UUID: [...]
      Provisioning UDID: [...]
      Activation Lock Status: Enabled
```

**Comment by pshipton** [comment] 2021-12-21 20:31
Trying to run the testcase over ssh results in `Exception in thread "main" java.awt.AWTError: WindowServer is not available`.

**Comment by kgibm** [comment] 2021-12-21 20:45
@pshipton Apologies. That test case is Swing-based and requires a GUI. The following simple program also reproduces the issue:

```
public class Hang {
	public static void main(String[] args) throws Throwable {
		System.out.println("Starting infinite hang");
		Object o = new Object();
		synchronized (o) {
			o.wait();
		}
	}
}
```

Compile and run and then:

```
jcmd $(pgrep -f Hang) Dump.system
```

Same result:

```
% java Hang
Starting infinite hang
JVMDUMP034I User requested System dump using '/Users/kevin/git/java_miscellaneous/bin/core.20211221.124349.2954.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
pwrite() error writing segment data:: Bad address
JVMDUMP012E Error in System dump: /Users/kevin/git/java_miscellaneous/bin/core.20211221.124349.2954.0001.dmp
```

**Comment by pshipton** [comment] 2021-12-21 21:10
We have tests that are working on the machines we have, but we don't have any macOS 12 machines in the pool. We might need to take you up on the offer to debug using your machine in the new year, depending on what the devs have for personal machines.

**Comment by mikezhang1234567890** [comment] 2022-01-05 21:28
I upgraded my Mac to macOS 12.1 and have managed to reproduce the issue. Trying to create a system dump using any method (including simply `java -Xdump:system:events=vmstart -version` will run into the same error. 

The error doesn't occur with Semeru binaries on the macOS 11.3 machines I've tried. It also does not occur when using one of the nightly builds to create a system core file.

The error suggests that the buffer with the memory segment data from `mach_vm_read` has become invalid when passed to `pwrite` to write the data to file.

**Comment by DanHeidinga** [comment] 2022-01-11 15:52
@mikezhang1234567890 can you provide an update on this for the 0.30 release?

**Comment by mikezhang1234567890** [comment] 2022-01-11 16:14
I'm still investigating why this issue only occurs with a signed application on macOS 12.

**Comment by DanHeidinga** [comment] 2022-01-18 15:45
Plan - document with an release notes for 0.30 and move forward

**Comment by pshipton** [comment] 2022-01-19 23:52
Moving to Milestone 0.32 since it's not jdk18 specific, but it's still high priority to fix this asap.

**Comment by mikezhang1234567890** [comment] 2022-01-27 18:11
I'm still not sure why memory allocated by the system function `mach_vm_read` becomes invalid in a signed app, but using stack allocated memory gets around the issue so I created https://github.com/eclipse/omr/pull/6319

**Closed** 2022-01-28 19:04 UTC
Labels: comp:vm, blocker, userRaised, os:macos
