### ISSUE TITLE
DaaLoadTest_all_CS_5m crash vmState=0x00020002

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14468] opened 2022-02-09 12:39 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly_testList_2/206 - [p8-java1-ibm08](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm08)
DaaLoadTest_all_CS_5m_0 `-Xgcpolicy:gencon -Xgc:concurrentScavenge`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly_testList_2/206/system_test_output.tar.gz
```
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00020002
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
DLT stderr Handler1=09001000A0CBADF0 Handler2=09001000A0BE94B0
DLT stderr R0=0000000620000000 R1=00000100230B3CD0 R2=09001000A0C0B650 R3=00000100101C34B0
DLT stderr R4=00000100101C9C10 R5=0000000100D91300 R6=000000000000000C R7=000000000000000A
DLT stderr R8=000000000000024B R9=000000000000024B R10=0000000000000003 R11=0000000000000000
DLT stderr R12=09000000059D1A8C R13=00000100230BC800 R14=0000000000000000 R15=0000000000000000
DLT stderr R16=0000000000000000 R17=0000000000000000 R18=0000000000000001 R19=0000000000000001
DLT stderr R20=0000000100D91300 R21=0000000000000190 R22=0000000000000180 R23=0000000000000008
DLT stderr R24=000001001136F230 R25=0000000000000001 R26=0000000000000000 R27=000001001136F150
DLT stderr R28=00000100230B8118 R29=00000100230B3ED0 R30=00000100230B8118 R31=3387108469253A99
DLT stderr IAR=09000000059D1AD8 LR=09000000059D1B84 MSR=A00000000200D032 CTR=0900000005A1E300
DLT stderr CR=2400024820000000 FPSCR=8202000000000000 XER=2000000082020000
DLT stderr FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
DLT stderr FPR2 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
DLT stderr FPR3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR5 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
DLT stderr FPR6 4070b23eed1c19ee (f: 3978041856.000000, d: 2.671404e+02)
DLT stderr FPR7 408f400000000000 (f: 0.000000, d: 1.000000e+03)
DLT stderr FPR8 410b0a6000000000 (f: 0.000000, d: 2.215160e+05)
DLT stderr FPR9 4530000000000000 (f: 0.000000, d: 1.934281e+25)
DLT stderr FPR10 408f400000000000 (f: 0.000000, d: 1.000000e+03)
DLT stderr FPR11 43300000000003e8 (f: 1000.000000, d: 4.503600e+15)
DLT stderr FPR12 4530000000000000 (f: 0.000000, d: 1.934281e+25)
DLT stderr FPR13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly_testList_2/openjdkbinary/j2sdk-image/jre/lib/ppc64/default/libj9gc29.so
DLT stderr Module_base_address=09000000058F9000
DLT stderr Target=2_90_20220209_213 (AIX 7.2)
DLT stderr CPU=ppc64 (16 logical CPUs) (0x780000000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr scanClearable__14MM_RootScannerFP18MM_EnvironmentBase+0x248 (0x09000000059C0A8C [libj9gc29.so+0xc7a8c])
DLT stderr workerCompleteGC__18MM_MarkingDelegateFP18MM_EnvironmentBase+0x1b4 (0x09000000059B76D8 [libj9gc29.so+0xbe6d8])
DLT stderr markLiveObjectsComplete__16MM_MarkingSchemeFP18MM_EnvironmentBase+0x10 (0x09000000059AF4B4 [libj9gc29.so+0xb64b4])
DLT stderr run__19MM_ParallelMarkTaskFP18MM_EnvironmentBase+0x1c0 (0x0900000005AA0724 [libj9gc29.so+0x1a7724])
DLT stderr workerEntryPoint__21MM_ParallelDispatcherFP18MM_EnvironmentBase+0x22c (0x0900000005AD6B70 [libj9gc29.so+0x1ddb70])
DLT stderr dispatcher_thread_proc2__FP14OMRPortLibraryPv+0x27c (0x0900000005AD5B00 [libj9gc29.so+0x1dcb00])
DLT stderr omrsig_protect+0x4a0 (0x09000000041FED84 [libj9prt29.so+0x59d84])
DLT stderr dispatcher_thread_proc+0x60 (0x0900000005AD68C4 [libj9gc29.so+0x1dd8c4])
DLT stderr thread_wrapper+0x544 (0x0900000003C02AE8 [libj9thr29.so+0x4ae8])
DLT stderr _pthread_body+0xe8 (0x090000000056104C [libpthreads.a+0x404c])
DLT stderr ---------------------------------------
```
@dmitripivkine

**Comment by dmitripivkine** [comment] 2022-02-09 18:47
```
mainSynchSignalHandler(??, ??, ??) at 0x9000000042017c0
scanOwnableSynchronizerObjects__27MM_MarkingSchemeRootClearerFP18MM_EnvironmentBase(??, ??) at 0x9000000059d1ad8
scanClearable__14MM_RootScannerFP18MM_EnvironmentBase(??, ??) at 0x9000000059c0a88
workerCompleteGC__18MM_MarkingDelegateFP18MM_EnvironmentBase(??, ??) at 0x9000000059b76d4
markLiveObjectsComplete__16MM_MarkingSchemeFP18MM_EnvironmentBase(??, ??) at 0x9000000059af4b0
run__19MM_ParallelMarkTaskFP18MM_EnvironmentBase(??, ??) at 0x900000005aa0720
workerEntryPoint__21MM_ParallelDispatcherFP18MM_EnvironmentBase(??, ??) at 0x900000005ad6b6c
dispatcher_thread_proc2__FP14OMRPortLibraryPv(??, ??) at 0x900000005ad5afc
omrsig_protect(??, ??, ??, ??, ??, ??, ??) at 0x9000000041fed80
dispatcher_thread_proc(??) at 0x900000005ad68c0
thread_wrapper(??) at 0x900000003c02ae4
```
this is duplicate of https://github.com/eclipse-openj9/openj9/issues/10489

**Closed by dmitripivkine** 2022-02-09 18:47 UTC
Labels: comp:jit, test failure, segfault
