### ISSUE TITLE
JDK23 SharedClasses.SCM01.MultiThreadMultiCL_1_FAILED NumberFormatException: For input string: "-Xdump:system+java:events=throw,filter=java/lang/NullPointerException#java/lang/invoke/BruteArgumentMoverHandle.permuteArguments*"

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19439] opened 2024-05-02 21:44 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.system_aarch64_linux_Personal_testList_1/10/consoleFull)(`ubu22-aarch64-1`):
```
12:04:04  SCC stderr openjdk version "23-internal" 2024-09-17
12:04:04  SCC stderr OpenJDK Runtime Environment (build 23-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
12:04:04  SCC stderr Eclipse OpenJ9 VM (build master-0a576e37d3f, JRE 23 Linux aarch64-64-Bit Compressed References 20240501_107 (JIT enabled, AOT enabled)
12:04:04  SCC stderr OpenJ9   - 0a576e37d3f
12:04:04  SCC stderr OMR      - 49ff22bb6af
12:04:04  SCC stderr JCL      - 887abee04bd based on jdk-23+20)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=SharedClasses.SCM01.MultiThreadMultiCL_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_extended.system_aarch64_linux_Personal&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F107%2FOpenJ9-JDKnext-aarch64_linux-20240501-105820.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F107%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=0a576e37d3fd0769506572b28fbdcdd3d2cc95f6&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=10&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
12:03:58  ===============================================
12:03:58  Running test SharedClasses.SCM01.MultiThreadMultiCL_1 ...
12:03:58  ===============================================
12:03:58  SharedClasses.SCM01.MultiThreadMultiCL_1 Start Time: Wed May  1 16:03:57 2024 Epoch Time (ms): 1714579437933
12:03:58  variation: Mode610
12:03:58  JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 

12:05:47  STF 16:05:46.557 - Monitoring processes: MTM1 MTM2 MTM3 MTM4 MTM5
12:05:47  MTM2 stderr java.lang.NumberFormatException: For input string: "-Xdump:system+java:events=throw,filter=java/lang/NullPointerException#java/lang/invoke/BruteArgumentMoverHandle.permuteArguments*"
12:05:47  MTM2 stderr 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
12:05:47  MTM2 stderr 	at java.base/java.lang.Integer.parseInt(Integer.java:588)
12:05:47  MTM2 stderr 	at java.base/java.lang.Integer.parseInt(Integer.java:685)
12:05:47  MTM2 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.main(LoaderSlaveMultiThreadMultiCL.java:59)

14:07:50  STF 18:07:47.697 - Monitoring Report Summary:
14:07:50  STF 18:07:47.697 -   o Process SCC ended with the expected exit code (1)
14:07:50  STF 18:07:47.698 - TEARDOWN stage completed
14:07:50  STF 18:07:47.707 - 
14:07:50  STF 18:07:47.707 - =====================   R E S U L T S   =====================
14:07:50  STF 18:07:47.707 - Stage results:
14:07:50  STF 18:07:47.707 -   setUp:     pass
14:07:50  STF 18:07:47.707 -   execute:  *fail*
14:07:50  STF 18:07:47.707 -   teardown:  pass
14:07:50  STF 18:07:47.707 - 
14:07:50  STF 18:07:47.707 - Overall result: **FAILED**
14:07:50  -----------------------------------
14:07:50  SharedClasses.SCM01.MultiThreadMultiCL_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40272/) - https://github.com/eclipse-openj9/openj9/issues/19439#issuecomment-2093374856

**Comment by pshipton** [comment] 2024-05-03 16:40
4/5 machines failed 5/10, the other failed 3/10.

@llxia pls have someone from test take the first look since it's LoaderSlaveMultiThreadMultiCL.main() trying to parse an integer. It expects args[1] to be an int, but for some reason it's a JVM argument.

I found https://github.com/eclipse-aqavit/openj9-systemtest/blob/master/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java#L257

**Comment by pshipton** [comment] 2024-05-03 16:55
Last passing build
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.system_aarch64_linux_Personal_testList_0/8
```
21:08:35  Eclipse OpenJ9 VM (build master-4998aab3ce1, JRE 23 Linux aarch64-64-Bit Compressed References 20240423_105 (JIT enabled, AOT enabled)
21:08:35  OpenJ9   - 4998aab3ce1
21:08:35  OMR      - 723d2e4b637
21:08:35  JCL      - a2f1462ae3f based on jdk-23+19)

ADOPTOPENJDK_REPO=https://github.com/adoptium/aqa-tests.git
ADOPTOPENJDK_BRANCH=6ad39d2b86de28a9805906a8cdb8569cb5631c34
TKG_REPO=https://github.com/adoptium/TKG.git
TKG_BRANCH=41c3581c810f2073908cd74ebd2050d37a72cdcb
test_REPO=git@github.ibm.com:runtimes/test.git
test_BRANCH=76308395d82c8e77861dfb74c7b14419683deded
STF_REPO=https://github.com/adoptium/STF.git
STF_BRANCH=89020fe1391aecaa6d2cf4f5402b60d200705c2a
AQA_SYSTEMTEST_REPO=https://github.com/adoptium/aqa-systemtest.git
AQA_SYSTEMTEST_BRANCH=b68aae2bd49fa693bc7b8e8b5ae19a02244b5c75
OPENJ9_SYSTEMTEST_REPO=https://github.com/eclipse/openj9-systemtest.git
OPENJ9_SYSTEMTEST_BRANCH=e8ca4718d20d6f2f147a65de55aa2714f293c6bd
```

First failing build
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.system_aarch64_linux_Personal_testList_0/9
```
00:11:03  Eclipse OpenJ9 VM (build criurestoredbg-a5a74e6b325, JRE 23 Linux aarch64-64-Bit Compressed References 20240426_106 (JIT enabled, AOT enabled)
00:11:03  OpenJ9   - a5a74e6b325
00:11:03  OMR      - 33a1542b9be
00:11:03  JCL      - d40bb40155c based on jdk-23+19)

ADOPTOPENJDK_REPO=https://github.com/adoptium/aqa-tests.git
ADOPTOPENJDK_BRANCH=61ebc47e0e2ac111057fbc09b62e7a14fc5c747a
TKG_REPO=https://github.com/adoptium/TKG.git
TKG_BRANCH=8a2e0a6dace721f1888361a983aa48c619dbe68a
test_REPO=git@github.ibm.com:runtimes/test.git
test_BRANCH=c35046cfded0855e4cb365403271e21d70971743
STF_REPO=https://github.com/adoptium/STF.git
STF_BRANCH=89020fe1391aecaa6d2cf4f5402b60d200705c2a
AQA_SYSTEMTEST_REPO=https://github.com/adoptium/aqa-systemtest.git
AQA_SYSTEMTEST_BRANCH=b68aae2bd49fa693bc7b8e8b5ae19a02244b5c75
OPENJ9_SYSTEMTEST_REPO=https://github.com/eclipse/openj9-systemtest.git
OPENJ9_SYSTEMTEST_BRANCH=e8ca4718d20d6f2f147a65de55aa2714f293c6bd
```

https://github.com/eclipse-openj9/openj9/compare/4998aab3ce1...a5a74e6b325
https://github.com/eclipse-openj9/openj9-omr/compare/723d2e4b637...33a1542b9be
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/a2f1462ae3f...d40bb40155c
https://github.com/adoptium/aqa-tests/compare/6ad39d2b86d...61ebc47e0e2
https://github.com/adoptium/TKG/compare/41c3581c810...8a2e0a6dace
https://github.ibm.com/runtimes/test/compare/76308395d82...c35046cfded0

**Comment by pshipton** [comment] 2024-05-03 17:48
Ah interesting, the NumberFormatException isn't the cause of the failure, this occurs in passing runs.

**Comment by llxia** [comment] 2024-05-03 18:13
According to the test code, the NumberFormatException will be caught. And the test will move on.
https://github.com/eclipse-aqavit/openj9-systemtest/blob/master/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThreadMultiCL.java#L57-L64

Details:
Two args ( jarName and int threadsMAX) are expected in the tests (i.e., `/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_1714758670750/SharedClasses.SCM01.MultiThreadMultiCL_1/20240503-175111-SharedClasses/tmp/classes.jar 120`). However, in some cases, extra arg is added https://github.com/eclipse-aqavit/openj9-systemtest/blob/master/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClasses.java#L257. The args[] becomes - `/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_1714758670750/SharedClasses.SCM01.MultiThreadMultiCL_1/20240503-175111-SharedClasses/tmp/classes.jar -Xdump:system+java:events=throw,filter=java/lang/NullPointerException#java/lang/invoke/BruteArgumentMoverHandle.permuteArguments* 120`. args[1] is no longer int. Therefore, we have NumberFormatException. As mentioned above, this does not fail the test.

**Comment by llxia** [comment] 2024-05-03 18:19
I do not think this PR - Add new debug options for sc mt test is valid: https://github.com/eclipse-aqavit/openj9-systemtest/commit/df3753a1d3fc24dfe71db1a7f7505f1a33071743. Instead of adding `-Xdump:system+java:events=throw,filter=java/lang/NullPointerException#java/lang/invoke/BruteArgumentMoverHandle.permuteArguments* ` to args, I think we should add it to `addJvmOption`.

@annaibm could you give it a try? Thanks

**Comment by pshipton** [comment] 2024-05-03 18:29
Actual failure `**FAILED** Process MTM1 has timed out`

Looking at the core for
https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.system_aarch64_linux_Personal_testList_0/9
SharedClasses.SCM23.SingleCL_1
```
id: 0xffffa0082528 name: VM class loader modules
        owner thread id: 2466573 name: main
        waiting thread id: 2466632 name: Common-Cleaner
id: 0xffffa00825e0 name: VM class loader blocks
id: 0xffffa0082698 name: VM class table
        owner thread id: 2466632 name: Common-Cleaner
        waiting thread id: 2466573 name: main
        waiting thread id: 2466602 name: vmthread @79616
        waiting thread id: 2466622 name: vmthread @156160

    name:          main
    Thread object: java/lang/Thread @ 0xfff040e0
    ID:            2 (0x2)
    Priority:      -1
    Thread.State:  BLOCKED
    JVMTI state:   ALIVE BLOCKED_ON_MONITOR_ENTER
      waiting to enter: "VM class table" with ID 0xffffa0082698 owner name: "Common-Cleaner" owner id: 2466632
    Java stack frames:
     bp: 0x000000000010f150  method: void java/lang/Module.defineModule0(Module, boolean, String, String, Object[])  (Native Method)
      objects: 0xfff39f20 0x84076060 0xfff39f98 0xfff39fc8                                                                   bp: 0x000000000010f1b8  method: void java/lang/Module.<init>(ModuleLayer, ClassLoader, module.ModuleDescriptor, java.net.URI)  source: Module.java:145                                                                                           objects: <no objects in this frame>                                                                                    bp: 0x000000000010f1f8  method: Module java/lang/Access.defineModule(ClassLoader, module.ModuleDescriptor, java.net.URI)  source: Access.java:244                                                                                                objects: 0xfff39f20                                                                                                    bp: 0x000000000010f228  method: Module jdk/internal/module/Modules.defineModule(ClassLoader, module.ModuleDescriptor, java.net.URI)  source: Modules.java:82                                                                                     objects: <no objects in this frame>                                                                                    bp: 0x000000000010f328  method: ModuleLayer jdk/internal/module/ModuleBootstrap.boot2()  source: ModuleBootstrap.java:274                                                                                                                        objects: 0xfff00510 0xfff00510 0xfff1a028 0xfff32368                                                                   bp: 0x000000000010f350  method: ModuleLayer jdk/internal/module/ModuleBootstrap.boot()  source: ModuleBootstrap.java:179

    name:          Common-Cleaner
    Thread object: jdk/internal/misc/InnocuousThread @ 0xfff35f70
    ID:            3 (0x3)
    Priority:      -1
    Thread.State:  BLOCKED
    JVMTI state:   ALIVE BLOCKED_ON_MONITOR_ENTER
      waiting to enter: "VM class loader modules" with ID 0xffffa0082528 owner name: "main" owner id: 2466573
    Java stack frames:
     bp: 0x0000000000140ce8  method: Class java/lang/VMAccess.findClassOrNull(String, ClassLoader)  (Native Method)
      objects: 0xfff41010 0xfff0ee80
     bp: 0x0000000000140d18  method: Class java/lang/ClassLoader.loadClass(String)  source: ClassLoader.java:1093
      objects: 0xfff41010
     bp: 0x0000000000140da8  method: void java/lang/Object.wait(long, int)  source: Object.java:253
      objects: 0xfff358d0
     bp: 0x0000000000140dd8  method: void java/lang/Object.wait(long)  source: Object.java:221
      objects: <no objects in this frame>
     bp: 0x0000000000140e20  method: ref.Reference java/lang/ref/ReferenceQueue.remove(long)  source: ReferenceQueue.java:137
      objects: 0xfff358d0 0xfff358d0
     bp: 0x0000000000140e58  method: void jdk/internal/ref/CleanerImpl.run()  source: CleanerImpl.java:140
      objects: 0xfff358c0 0xfff35f70
     bp: 0x0000000000140e88  method: void java/lang/Thread.runWith(Object, Runnable)  source: Thread.java:1600
      objects: 0x840727c8
     bp: 0x0000000000140eb8  method: void java/lang/Thread.run()  source: Thread.java:1587
      objects: <no objects in this frame>
     bp: 0x0000000000140ed8  method: void jdk/internal/misc/InnocuousThread.run()  source: InnocuousThread.java:186
      objects: <no objects in this frame>
```

[threads.txt](https://github.com/eclipse-openj9/openj9/files/15203717/threads.txt)

**Comment by pshipton** [comment] 2024-05-03 19:23
@keithc-ca fyi this is why https://github.com/eclipse-openj9/openj9/pull/19417 made a difference, it avoided loading Blocker early in bootstrap, which is no longer loaded elsewhere.

**Comment by pshipton** [comment] 2024-05-03 19:38
@tajila pls assign, the deadlock condition needs to be fixed.

**Comment by pshipton** [comment] 2024-05-03 19:55
I don't have native stack traces, but this could be what's going on.

findClassOrNull() calls loadNonArrayClass() and on classsupport.c  : 1034 locks classTableMutex
calls arbitratedLoadClass(), calls callLoadClass(), calls internalFindKnownClass() 
internalFindKnownClass() locks classLoaderModuleAndLocationMutex on line 1260

JVM_DefineModule() locks classLoaderModuleAndLocationMutex at the start of the function java11vmi.c : 768
calls allClassesStartDo() which locks classTableMutex

**Comment by pshipton** [comment] 2024-05-03 20:08
@llxia @annaibm whatever problem we were trying to get diagnostics for via https://github.com/eclipse-aqavit/openj9-systemtest/commit/df3753a1d3fc24dfe71db1a7f7505f1a33071743 seems obsolete now. I think we should remove the change rather than fix it.

**Comment by tajila** [comment] 2024-05-03 22:19
> I don't have native stack traces, but this could be what's going on.

If its easily reproduceable I can make a patch to address that case.

**Comment by pshipton** [comment] 2024-05-05 04:48
> If its easily reproduceable I can make a patch to address that case.

It failed 23/50 in the grinder.

**Comment by tajila** [comment] 2024-05-07 17:55
A grinder with test build https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40366/

**Comment by tajila** [comment] 2024-05-09 13:37
Rebuild https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40428/

**Comment by llxia** [comment] 2024-05-09 13:39
just for the record, re https://github.com/eclipse-openj9/openj9/issues/19439#issuecomment-2093690251, -Xdump options is removed. See https://github.com/eclipse-aqavit/openj9-systemtest/pull/153

**Comment by tajila** [comment] 2024-05-09 17:04
Passed 50/50 with the https://github.com/eclipse-openj9/openj9/pull/19458 changes

**Comment by tajila** [comment] 2024-05-13 18:06
Closing this as changes are in

**Closed by tajila** 2024-05-13 18:06 UTC
Labels: comp:vm, test failure, jdk23
