### ISSUE TITLE
The order of analysis is different for OpenJ9 and Hotspot

### ISSUE THREAD

**Issue by TemporaryRepos** [eclipse-openj9/openj9#19140] opened 2024-03-14 13:08 UTC
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Linux Ubuntu20.04

Java -version output under Linux

```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b06)
Eclipse OpenJ9 VM (build openj9-0.43.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240131_861 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 0fa9d9c532 based on jdk8u402-b06)
```

```
openjdk version "11.0.22" 2024-01-16
IBM Semeru Runtime Open Edition 11.0.22.0 (build 11.0.22+7)
Eclipse OpenJ9 VM 11.0.22.0 (build openj9-0.43.0, JRE 11 Linux amd64-64-Bit Compressed References 20240131_966 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 7876cac747 based on jdk-11.0.22+7)
```

```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)
Eclipse OpenJ9 VM 17.0.10.0 (build openj9-0.43.0, JRE 17 Linux amd64-64-Bit Compressed References 20240116_670 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 2aad089841f based on jdk-17.0.10+7)
```

## Problem summary

The test cases BasicChar and BasicLong extend from Basic. Where BasicChar contains a NoClassDefFoundError and BasicLong contains a NumberFormatException. The order of analysis differs between Hotspot and OpenJ9, with Hotspot reporting a NumberFormatException and OpenJ9 reporting a NoClassDefFoundError. Are both behaviors correct?

Steps to Reproduce
```
java/bin/java javaT.nio.Buffer.BasicLong
```
Expected Result
```
NumberFormatException 
```
Actual Result
```
NoClassDefFoundError
```

Code 
```
public class Basic {
    public static void main(String[] var0) {
        BasicChar.test();
        BasicLong.test();
    }
}

public class BasicChar extends Basic {
    static {
        new Test8007722();
    }
}

public class BasicLong extends Basic {
    static {
        new Float("");
    }
}
```
## Attachment

[202403142107.zip](https://github.com/eclipse-openj9/openj9/files/14602591/202403142107.zip)

**Comment by pshipton** [comment] 2024-03-14 14:09
@tajila fyi

**Comment by tajila** [comment] 2024-03-18 18:51
@singh264 Please take a look

**Comment by singh264** [comment] 2024-03-27 22:45
> The test cases BasicChar and BasicLong extend from Basic. Where BasicChar contains a NoClassDefFoundError and BasicLong contains a NumberFormatException. The order of analysis differs between Hotspot and OpenJ9, with Hotspot reporting a NumberFormatException and OpenJ9 reporting a NoClassDefFoundError. Are both behaviors correct?

Both openj9 and the RI behaviours seem to be valid based on section [5.2 Java Virtual Machine Startup](https://docs.oracle.com/javase/specs/jvms/se22/html/jvms-5.html#jvms-5.2) in the spec.

```
The Java Virtual Machine starts up by creating an initial class or interface using the
bootstrap class loader (5.3.1) or a user-defined class loader (5.3.2). The Java
Virtual Machine then links the initial class or interface, initializes it, and invokes
the public static method void main(String[]). The invocation of this method drives all
further execution. Execution of the Java Virtual Machine instructions constituting the
main method may cause linking (and consequently creation) of additional classes and
interfaces, as well as invocation of additional methods.

The initial class or interface is specified in an implementation-dependent manner. For
example, the initial class or interface could be provided as a command line argument.
Alternatively, the implementation of the Java Virtual Machine could itself provide an
initial class that sets up a class loader which in turn loads an application. Other
choices of the initial class or interface are possible so long as they are consistent
with the specification given in the previous paragraph.
```

The spec does not define a specific order for creating classes beyond the initial class and the invocation of the main method. For `java javaT.nio.Buffer.BasicLong`, it seems like the RI initializes the superclass `Basic` and the subclass `BasicLong` before invoking `Basic.main`. A `NumberFormatException` is reported by the RI during the creation of `BasicLong`. In contrast, openj9 initializes the superclass `Basic` before invoking `Basic.main`, and the initialization of the subclasses `BasicChar` and `BasicLong` occur in the order they appear during program execution. A `NoClassDefFoundError` is thrown by openj9 during the initialization of `BasicChar` as `BasicChar.test` is invoked before `BasicLong.test` in `Basic.main`. This behaviour aligns with section [5.5 Initialization](https://docs.oracle.com/javase/specs/jvms/se22/html/jvms-5.html#jvms-5.5) in the spec.

```
A class or interface C may be initialized only as a result of:

• The execution of any one of the Java Virtual Machine instructions new,
  getstatic, putstatic, or invokestatic that references C (new, getstatic, putstatic,
  invokestatic).

  Upon execution of a new instruction, the class to be initialized is the class
  referenced by the instruction.

  Upon execution of a getstatic, putstatic, or invokestatic instruction, the class or
  interface to be initialized is the class or interface that declares the resolved field
  or method.
```

The jvm initializes a class as a result of certain actions, which includes the execution of `invokestatic` instructions that reference the class. In the provided class files, `BasicChar.test` is invoked before `BasicLong.test` in `Basic.main`, which indicates that the initialization of the subclass `BasicChar` would occur before the initialization of the subclass `BasicLong` during program execution. For example, when running `java javaT.nio.Buffer.BasicChar` or `java javaT.nio.Buffer.Basic` both openj9 and the RI report a `NoClassDefFoundError`. @TemporaryRepos I would like access to the source code to verify if openj9 reports a `NumberFormatException` when `BasicLong.test` is invoked before `BasicChar.test` in `Basic.main`.


```
javap -c Basic.class
public class javaT.nio.Buffer.Basic {
  static java.io.PrintStream out;

  static {};
    Code:
       0: getstatic     #13                 // Field java/lang/System.err:Ljava/io/PrintStream;
       3: putstatic     #15                 // Field out:Ljava/io/PrintStream;
       6: return

  public javaT.nio.Buffer.Basic();
    Code:
       0: aload_0
       1: invokespecial #18                 // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: invokestatic  #25                 // Method javaT/nio/Buffer/BasicChar.test:()V
       3: invokestatic  #28                 // Method javaT/nio/Buffer/BasicLong.test:()V
       6: return
}
```

**Comment by singh264** [comment] 2024-03-27 22:49
@tajila @gacholio I would like to know if we should match the RI based on https://github.com/eclipse-openj9/openj9/issues/19140#issuecomment-2024109936.

**Comment by tajila** [comment] 2024-03-28 12:11
The steps to reproduce say BasicLong.

> java/bin/java javaT.nio.Buffer.BasicLong

My expectation is that Basic would be initialized first because its the superclass of BasicLong. Then BasicLong needs to be initialiazed since that is the initial class. After that, `Basic::main(..)` is run. So  ...
 
>  In contrast, openj9 initializes the superclass Basic before invoking Basic.main, and the initialization of the subclasses BasicChar and BasicLong occur in the order they appear during program execution. 

I would expect that to be done after BasicLong is initialized.

Can you dump the bytecodes for `BasicLong`

**Comment by singh264** [comment] 2024-03-28 14:53
> Can you dump the bytecodes for BasicLong

```
javap -c BasicLong.class 
public class javaT.nio.Buffer.BasicLong extends javaT.nio.Buffer.Basic {
  static {};
    Code:
       0: new           #8                  // class java/lang/Float
       3: ldc           #10                 // String
       5: invokespecial #14                 // Method java/lang/Float."<init>":(Ljava/lang/String;)V
       8: return

  public javaT.nio.Buffer.BasicLong();
    Code:
       0: aload_0
       1: invokespecial #16                 // Method javaT/nio/Buffer/Basic."<init>":()V
       4: return

  public static void test();
    Code:
       0: return
}
```

**Comment by tajila** [comment] 2024-03-28 18:01
@singh264 Can you look into how we launch the main Class. We must be calling `LauncherHelper::getApplicationClass` which should return `BasicLong`. I wonder if we do any initialization there? That may be a difference between us and RI.

After we would do `(*env)->GetStaticMethodID(env, mainClass, "main",...`. This will find the method in the super, but again perhaps there is an initialization done in RI that we are not doing.

**Comment by singh264** [comment] 2024-04-01 15:57
When we run `java javaT.nio.Buffer.BasicLong`, the `appClass` is the subclass `BasicLong`, but it is not initialized when we call `LauncherHelper.getApplicationClass`. After, the `mainClass` is `BasicLong` when we call 
`(*env)->GetStaticMethodID(env, mainClass, "main", ...)` and the initial class is initialized. We consider the initial class to be the superclass `Basic`, as it includes the `main` method, instead of `BasicLong` which is passed to the java command. The initialization of the other classes occur in the order they appear during program execution after the invocation of the main method.

**Comment by tajila** [comment] 2024-04-01 18:14
Can you add some prints to the application to see if RI initialization order pre-main is the same as ours

**Comment by singh264** [comment] 2024-04-01 19:59
I am unable add print statements to the user-provided application since I lack access to its source code, and I have requested @TemporaryRepos for access. Alternatively, I have utilized a test application resembling the user-provided application, where I replaced the erroneous code in the static blocks with print statements.

```
class B
class Basic extends B
class BasicChar extends Basic
class BasicLong extends Basic
class BasicLongLong extends BasicLong

Basic.main { BasicChar.test -> BasicLongLong.test -> BasicLong.test }
```

The results of the running the test application indicates that the pre-main initialization order of the RI is not the same as openj9. The initialization order of the RI depends on the class (initial class) that is provided to java command, whereas for openj9 the initialization order is consistent as `Basic` is always considered the initial class. Both the RI and openj9 throw an error when `B` is passed to the java command as the `main` method is not in `B` or any of its superclasses.

```
// openj9

java BasicLong, BasicChar, BasicLongLong or Basic

In B static block
In Basic static block
In Basic.main
In BasicChar static block
In BasicChar.test
In BasicLong static block
In BasicLongLong static block
In BasicLongLong.test
In BasicLong.test
```

```
// RI

java BasicLong

In B static block
In Basic static block
In BasicLong static block
In Basic.main
In BasicChar static block
In BasicChar.test
In BasicLongLong static block
In BasicLongLong.test
In BasicLong.test

java BasicChar

In B static block
In Basic static block
In BasicChar static block
In Basic.main
In BasicChar.test
In BasicLong static block
In BasicLongLong static block
In BasicLongLong.test
In BasicLong.test

java BasicLongLong

In B static block
In Basic static block
In BasicLong static block
In BasicLongLong static block
In Basic.main
In BasicChar static block
In BasicChar.test
In BasicLongLong.test
In BasicLong.test

java Basic

In B static block
In Basic static block
In Basic.main
In BasicChar static block
In BasicChar.test
In BasicLong static block
In BasicLongLong static block
In BasicLongLong.test
In BasicLong.test
```

**Comment by tajila** [comment] 2024-04-01 20:20
> The results of the running the test application indicates that the pre-main initialization order of the RI is not the same as openj9. The initialization order of the RI depends on the class (initial class) that is provided to java command, whereas for openj9 the initialization order is consistent as Basic is always considered the initial class. Both the RI and openj9 throw an error when B is passed to the java command as the main method is not in B or any of its superclasses.

Can you run RI with debugger to determine which part of java launcher (java.c) triggers the initialization of the initialclass. It will likely be one of the steps I indicated in https://github.com/eclipse-openj9/openj9/issues/19140#issuecomment-2025810171

**Comment by singh264** [comment] 2024-04-01 20:43
The RI java launcher triggers the initialization of the initial class when obtaining the `mainID` with 
`(*env)->GetStaticMethodID(env, mainClass, "main", ...)`.

**Comment by singh264** [comment] 2024-04-12 14:55
This issue can be closed and it was addressed by:
- https://github.com/eclipse-openj9/openj9/pull/19256

**Closed by singh264** 2024-04-12 14:55 UTC
Labels: comp:vm, userRaised
