### ISSUE TITLE
OpenJDK java/foreign/TestSegmentAllocators.java crash vmState=0x00000000

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16484] opened 2022-12-15 21:05 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_OpenJDK17/38
jdk_foreign_0 
java/foreign/TestSegmentAllocators.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_OpenJDK17/38/openjdk_test_output.tar.gz
```
15:11:43  Type=Segmentation error vmState=0x00000000
15:11:43  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFB104D059F ContextFlags=0010005f
15:11:43  Handler1=00007FFB106B94F0 Handler2=00007FFB1059AA50 InaccessibleReadAddress=0000000000000030
15:11:43  RDI=0000000000000010 RSI=00007FFB107DCD4C RAX=0000000000000000 RBX=000002112610D1E3
15:11:43  RCX=000000006D76396A RDX=00007FFB107E0A8C R8=0000000000000004 R9=00007FFB2134140A
15:11:43  R10=00007FFB21340000 R11=0000000000000246 R12=0000000000000010 R13=0000000000000000
15:11:43  R14=000002112610C8C0 R15=000000000037D680
15:11:43  RIP=00007FFB104D059F RSP=0000006F1B4FE750 RBP=0000006F1B4FE7D9 EFLAGS=0000000000010212
15:11:43  FS=0053 ES=002B DS=002B
15:11:43  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:11:43  Module=F:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_OpenJDK17\openjdkbinary\j2sdk-image\bin\default\j9trc29.dll
15:11:43  Module_base_address=00007FFB104C0000 Offset_in_DLL=000000000001059f
15:11:43  Target=2_90_20221215_50 (Windows Server 2019 10.0 build 17763)
15:11:43  CPU=amd64 (8 logical CPUs) (0x3ffb9c000 RAM)
15:11:43  ----------- Stack Backtrace -----------
15:11:43  JVM_OnUnload+0x71ef (0x00007FFB104D059F [j9trc29+0x1059f])
15:11:43  JVM_OnUnload+0x799b (0x00007FFB104D0D4B [j9trc29+0x10d4b])
15:11:43  JVM_OnUnload+0x3589 (0x00007FFB104CC939 [j9trc29+0xc939])
15:11:43  JVM_OnUnload+0x1561 (0x00007FFB104CA911 [j9trc29+0xa911])
15:11:43  J9_GetInterface+0x39c33 (0x00007FFB10700573 [j9vm29+0x110573])
15:11:43  Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0+0xec (0x00007FFB1026D1BC [jclse29+0x4d1bc])
15:11:43  (0x00007FFAF9655935)
15:11:43  (0x0000000000382C01)
15:11:43  (0x00000000FFED99B8)
15:11:43  (0x0000000000000001)
15:11:43  (0x00000000FFF52928)
15:11:43  (0x00000000FFF52FB0)
15:11:43  (0x00000000001F0800)
15:11:43  (0x0000000000000001)
15:11:43  (0x0000000000000001)
15:11:43  (0x00000000FFF39040)
15:11:43  (0x00000000001F0800)
15:11:43  (0x00000000001F0800)
15:11:43  (0x0000006F1B4FEF00)
15:11:43  (0x0000000000382C00)
15:11:43  (0x00000000FFED99B8)
15:11:43  (0x00007FFAF9E242A8)
15:11:43  (0x00007FFAF9E240AC)
15:11:43  (0x0000000000000018)
15:11:43  (0x00007FFAF9E242B8)
15:11:43  (0x0000006F1B4FF038)
15:11:43  (0x0000006F1B4FF050)
15:11:43  (0x0000000000382C00)
15:11:43  ---------------------------------------
```

@ChengJin01

**Comment by ChengJin01** [comment] 2022-12-15 23:40
The dump shows there was problem with `ScopedMemoryAccess` in the Foreign Memory Access API (the test suite is irrelevant to FFI downcall & upcall)

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "MainThread" J9VMThread:0x00000000001F0800, omrthread_t:0x00000211121C9AD0, java/lang/Thread:0x00000000E00A6020, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1A, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x00000000E004F060)
3XMTHREADINFO1            (native thread ID:0xE5C, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00041020)
3XMCPUTIME               CPU usage total: 3.765625000 secs, user: 2.859375000 secs, system: 0.906250000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=1801992 (0x1B7F08)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/ScopedMemoryAccess.closeScope0(Native Method)
4XESTACKTRACE                at jdk/internal/misc/ScopedMemoryAccess.closeScope(ScopedMemoryAccess.java:87)
4XESTACKTRACE                at jdk/internal/foreign/SharedScope.justClose(SharedScope.java:106(Compiled Code))
4XESTACKTRACE                at jdk/internal/foreign/ResourceScopeImpl.close(ResourceScopeImpl.java:169)
4XESTACKTRACE                at TestSegmentAllocators.testAllocation(TestSegmentAllocators.java:89)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
4XESTACKTRACE                at jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:568)

```
against the native code at
```
15:11:43  Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0+0xec (0x00007FFB1026D1BC [jclse29+0x4d1bc])
```

@babsingh  & @EricYangIBM,  please check your code at https://github.com/eclipse-openj9/openj9/blob/12945d24501bbc87fb20c747abd71cf69e5d8f97/runtime/jcl/common/jdk_internal_misc_ScopedMemoryAccess.cpp#L76 to see whether the crash was triggered by the changes merged recently.

**Comment by babsingh** [comment] 2023-01-05 19:50
> See whether the crash was triggered by the changes merged recently.

The failure is very intermittent. I could not reproduce it on my local Linux machine. The core file associated to this issue is generated on Windows. @ChengJin01 Were you able to open the core and inspect the native stack in windbg? I don't have a Windows machine.

**Comment by ChengJin01** [comment] 2023-01-05 20:14
@babsingh, the core dump on my side didn't indicate exactly where it crashed in `Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0` except the stack traces mentioned in the description.

**Comment by ChengJin01** [comment] 2023-01-05 20:37
In theory, the crash should occur on any other platforms given there is no platform-specific code in `Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0`.  So I suggest to close this issue for the moment unless the crash is triggered on other platforms, which will be easier for us to investigate.

**Comment by ChengJin01** [comment] 2023-01-05 23:04
Close this issue for now unless we have more decent information for debugging on other platforms.

**Closed by ChengJin01** 2023-01-05 23:04 UTC
Labels: comp:vm, test failure

**Comment by babsingh** [comment] 2023-01-06 18:56
Agreeing with @ChengJin01's above comments. From the Windows core file, there is no clear indication where the seg fault occurred and what is corrupted. The failure could not be reproduced on Linux for further investigation. 

The top frames are JIT compiled. I didn't find any corruption in the `!stackslots` output. Due to the extremely intermittent nature of the failure and noting that `ScopedMemoryAccess.closeScope0` does not have platform specific code, the corruption may have propagated from the JIT. Currently, I don't have any evidence to prove this theory. So, we can reopen the issue when better diagnostic information is available.

### Top Frames are JIT compiled

```
> !stackslots 0x1f0800
<1f0800> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x00000000001F0800 ***
<1f0800> 	ITERATE_O_SLOTS
<1f0800> 	RECORD_BYTECODE_PC_OFFSET
<1f0800> Initial values: walkSP = 0x00000000002385B8, PC = 0x0000000000000006, literals = 0x0000000000000000, A0 = 0x00000000002386B8, j2iFrame = 0x00000000002386A8, ELS = 0x0000006F1B4FEF70, decomp = 0x0000000000000000
<1f0800> JIT JNI call-out frame: bp = 0x00000000002385D8, sp = 0x00000000002385B8, pc = 0x0000000000000006, cp = 0x00000000000DED20, arg0EA = 0x00000000002386B8, flags = 0x0000000020000000
<1f0800> 	Method: jdk/internal/misc/ScopedMemoryAccess.closeScope0(Ljdk/internal/misc/ScopedMemoryAccess$Scope;Ljdk/internal/misc/ScopedMemoryAccess$Scope$ScopedAccessError;)Z !j9method 0x00000000000DBE98
<1f0800> JIT frame: bp = 0x0000000000238608, pc = 0x00007FFAF9655935, unwindSP = 0x00000000002385E0, cp = 0x00000000000DED20, arg0EA = 0x0000000000238620, jitInfo = 0x0000021125C75928
<1f0800> 	Method: jdk/internal/misc/ScopedMemoryAccess.closeScope0(Ljdk/internal/misc/ScopedMemoryAccess$Scope;Ljdk/internal/misc/ScopedMemoryAccess$Scope$ScopedAccessError;)Z !j9method 0x00000000000DBE98
<1f0800> 	Bytecode index = -1, inlineDepth = 0, PC offset = 0x00000000000000D9
<1f0800> 	stackMap=0x0000021125C75A21, slots=I16(0x0003) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0003), localBaseOffset=I16(0x0000)
<1f0800> 	Described JIT args starting at 0x0000000000238610 for U16(0x0003) slots
<1f0800> 		O-Slot: : a2[0x0000000000238610] = 0x00000000E017A920
<1f0800> 		O-Slot: : a1[0x0000000000238618] = 0x00000000FFED99B8
<1f0800> 		O-Slot: : a0[0x0000000000238620] = 0x00000000E00492E0
<1f0800> 	Described JIT temps starting at 0x0000000000238608 for IDATA(0x0000000000000000) slots
<1f0800> 	JIT-RegisterMap = UDATA(0x0000000000000000)
<1f0800> 	JIT-Frame-RegisterMap[0x00000000002385F8] = UDATA(0x00000000FFED99B8) (jit_rbx)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238600] = UDATA(0x0000000000000000) (jit_r9)
<1f0800> I2J values: PC = 0x00000211127F9369, A0 = 0x00000000002386B8, walkSP = 0x0000000000238628, literals = 0x00000000000DBE78, JIT PC = 0x00007FFB0D74A850, pcAddress = 0x0000006F1B4FEF98, decomp = 0x0000000000000000
<1f0800> J2I frame: bp = 0x00000000002386A8, sp = 0x0000000000238628, pc = 0x00000211127F9369, cp = 0x00000000000DED20, arg0EA = 0x00000000002386B8, flags = 0x0000000010000000
<1f0800> 	Method: jdk/internal/misc/ScopedMemoryAccess.closeScope(Ljdk/internal/misc/ScopedMemoryAccess$Scope;)Z !j9method 0x00000000000DBE78
<1f0800> 	Bytecode index = 5
<1f0800> 	Using local mapper
<1f0800> 	Locals starting at 0x00000000002386B8 for 0x0000000000000002 slots
<1f0800> 		I-Slot: a0[0x00000000002386B8] = 0x00000000E00492E0
<1f0800> 		I-Slot: a1[0x00000000002386B0] = 0x00000000FFED99B8
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238650] = UDATA(0x00000000FFED99B8) (jit_rbx)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238688] = UDATA(0x0000000000000000) (jit_r9)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238680] = UDATA(0x0000000000000004) (jit_r10)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238678] = UDATA(0x0000006F1B4FEC00) (jit_r11)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238670] = UDATA(0x0000000000000001) (jit_r12)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238668] = UDATA(0x00000000FFF52928) (jit_r13)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238660] = UDATA(0x0000000000000001) (jit_r14)
<1f0800> 	JIT-J2I-RegisterMap[0x0000000000238658] = UDATA(0x00000000FFF528D0) (jit_r15)
<1f0800> JIT frame: bp = 0x00000000002386E8, pc = 0x00007FFAF9C11DF5, unwindSP = 0x00000000002386B0, cp = 0x0000000000382EE0, arg0EA = 0x00000000002386F0, jitInfo = 0x0000021125CB9068
<1f0800> 	Method: jdk/internal/foreign/SharedScope.justClose()V !j9method 0x0000000000383210
<1f0800> 	Bytecode index = 46, inlineDepth = 0, PC offset = 0x0000000000000175
<1f0800> 	stackMap=0x0000021125CB920F, slots=I16(0x0001) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0001), localBaseOffset=I16(0x0000)
<1f0800> 	Described JIT args starting at 0x00000000002386F0 for U16(0x0001) slots
<1f0800> 		O-Slot: : a0[0x00000000002386F0] = 0x00000000FFED99B8
<1f0800> 	Described JIT temps starting at 0x00000000002386E8 for IDATA(0x0000000000000000) slots
<1f0800> 	JIT-RegisterMap = UDATA(0x0000000000000002)
<1f0800> 		JIT-RegisterMap-O-Slot[0x0000000000238650] = 0x00000000FFED99B8 (jit_rbx)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238688] = UDATA(0x0000000000000000) (jit_r9)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238680] = UDATA(0x0000000000000004) (jit_r10)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238678] = UDATA(0x0000006F1B4FEC00) (jit_r11)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238670] = UDATA(0x0000000000000001) (jit_r12)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238668] = UDATA(0x00000000FFF52928) (jit_r13)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238660] = UDATA(0x0000000000000001) (jit_r14)
<1f0800> 		JIT-RegisterMap-I-Slot[0x0000000000238658] = UDATA(0x00000000FFF528D0) (jit_r15)
<1f0800> 	JIT-Frame-RegisterMap[0x00000000002386D8] = U64(0x0000000000382C00) (jit_rbx)
<1f0800> 	JIT-Frame-RegisterMap[0x00000000002386E0] = U64(0x00000000FFF53010) (jit_r9)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238680] = UDATA(0x0000000000000004) (jit_r10)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238678] = UDATA(0x0000006F1B4FEC00) (jit_r11)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238670] = UDATA(0x0000000000000001) (jit_r12)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238668] = UDATA(0x00000000FFF52928) (jit_r13)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238660] = UDATA(0x0000000000000001) (jit_r14)
<1f0800> 	JIT-Frame-RegisterMap[0x0000000000238658] = UDATA(0x00000000FFF528D0) (jit_r15)
<1f0800> I2J values: PC = 0x0000021112D6D741, A0 = 0x0000000000238718, walkSP = 0x00000000002386F8, literals = 0x00000000003826D8, JIT PC = 0x00007FFB0D74A820, pcAddress = 0x0000000000238640, decomp = 0x0000000000000000
<1f0800> Bytecode frame: bp = 0x0000000000238708, sp = 0x00000000002386F8, pc = 0x0000021112D6D741, cp = 0x00000000003821D0, arg0EA = 0x0000000000238718, flags = 0x0000000000000000
<1f0800> 	Method: jdk/internal/foreign/ResourceScopeImpl.close()V !j9method 0x00000000003826D8
<1f0800> 	Bytecode index = 1
<1f0800> 	Using local mapper
<1f0800> 	Locals starting at 0x0000000000238718 for 0x0000000000000002 slots
<1f0800> 		O-Slot: a0[0x0000000000238718] = 0x00000000FFED99B8
<1f0800> 		I-Slot: t1[0x0000000000238710] = 0x00000000002387E8
...
```
