### ISSUE TITLE
Fail to restore image on Intel machine when the checkpoint image created on AMD 

### ISSUE THREAD

**Issue by tam512** [eclipse-openj9/openj9#15865] opened 2022-09-09 22:23 UTC
Build Open Liberty checkpoint image on an RHEL9 with AMD chip then restore the image on RHEL9 Intel chip and it fails with the following
```
Unhandled exception
Type=Illegal instruction vmState=0x00040000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=00000002
Handler1=00007F9841F74B20 Handler2=00007F98435446F0

Unhandled exception in signal handler. Protected function: writeCrashDataToConsole (0x0)

----------- Stack Backtrace -----------
0x00007F9843483C5C
0x00007F97A7DF5D93
0x00007F97A7DF60C9
0x00007F97A7DF7B8F
0x00007F9823C12E77
0x00007F98420F05EA
0x00007F98420EF782
0x00007F9841FDD6A2
0x00007F9841FC947D
0x00007F984207EAE2
---------------------------------------

Unhandled exception in signal handler. Protected function: generateDiagnosticFiles (0x0)
```

**Comment by tam512** [comment] 2022-09-09 22:24
I have provided needed trace to @tajila

**Comment by tajila** [comment] 2022-09-12 14:02
Some more details from the internal reproduction

```
00:36:12  Type=Illegal instruction vmState=0x00200003
00:36:12  J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=00000002
00:36:12  Handler1=00007F934D132E60 Handler2=00007F934E7006B0
00:36:12  RDI=0000000000000008 RSI=00007F934E8384D0 RAX=00000000000000EE RBX=00007F934E838490
00:36:12  RCX=0000000000000000 RDX=0000000000000000 R8=0000000000000000 R9=0000000000000000
00:36:12  R10=0000000000000022 R11=0000000000000000 R12=00007F934E8384D0 R13=00007F934835CAC8
00:36:12  R14=0000000000000008 R15=00007F934833CB90
00:36:12  RIP=00007F934E63EC5C GS=0000 FS=0000 RSP=00007F934E838100
00:36:12  EFlags=0000000000010246 CS=0033 RBP=00007F934E838598 ERR=0000000000000000
00:36:12  TRAPNO=0000000000000006 OLDMASK=0000000000000000 CR2=0000000000000000
00:36:12  xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  xmm1 ffff000000000000 (f: 0.000000, d: -nan)
00:36:12  xmm2 00000000b7654321 (f: 3076866816.000000, d: 1.520174e-314)
00:36:12  xmm3 00007f934c87f100 (f: 1283977472.000000, d: 6.930289e-310)
00:36:12  xmm4 00007f934c87f138 (f: 1283977472.000000, d: 6.930289e-310)
00:36:12  xmm5 0000003000000020 (f: 32.000000, d: 1.018558e-312)
00:36:12  xmm6 00740053002f0067 (f: 3080295.000000, d: 1.780172e-306)
00:36:12  xmm7 0000003000000020 (f: 32.000000, d: 1.018558e-312)
00:36:12  xmm8 0067006e00690072 (f: 6881394.000000, d: 1.023609e-306)
00:36:12  xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  xmm10 2020000000202020 (f: 2105376.000000, d: 5.966673e-154)
00:36:12  xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:36:12  Module=/lib64/ld-linux-x86-64.so.2
00:36:12  Module_base_address=00007F934E63D000
00:36:12  Target=2_90_20220911_23 (Linux 3.10.0-1160.76.1.el7.x86_64)
00:36:12  CPU=amd64 (4 logical CPUs) (0x1e8d07000 RAM)
00:36:12  ----------- Stack Backtrace -----------
00:36:12  _dl_runtime_resolve_xsavec+0x6c (0x00007F934E63EC5C [ld-linux-x86-64.so.2+0x1c5c])
00:36:12  send_req_and_recv_resp_sk.isra.1+0xce (0x00007F933C841DDE [libcriu.so.2+0x8dde])
00:36:12  send_req_and_recv_resp.constprop.7+0x59 (0x00007F933C8420C9 [libcriu.so.2+0x90c9])
00:36:12  criu_local_dump+0x5f (0x00007F933C843B8F [libcriu.so.2+0xab8f])
00:36:12  Java_org_eclipse_openj9_criu_CRIUSupport_checkpointJVMImpl+0x15c5 (0x00007F933CA4FCD5 [libj9criu29.so+0x3cd5])
00:36:12  ffi_call_unix64+0x52 (0x00007F934D2B05CA [libj9vm29.so+0x1bb5ca])
00:36:12  ffi_call_int+0x1a2 (0x00007F934D2AF762 [libj9vm29.so+0x1ba762])
00:36:12  _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x14212 (0x00007F934D19D662 [libj9vm29.so+0xa8662])
00:36:12  bytecodeLoopCompressed+0xad (0x00007F934D18943D [libj9vm29.so+0x9443d])
00:36:12   (0x00007F934D23EAC2 [libj9vm29.so+0x149ac2])
```

I added a custom vmstate `vmState=0x00200003`, this indicates that the criu_dump operation did not complete, the native stack trace confirms this.

**Comment by tajila** [comment] 2022-09-12 14:02
FYI @ymanton @vijaysun-omr

**Comment by tajila** [comment] 2022-09-12 14:03
This failure seems to be caused by xsave portability, which should be fixed with

```
export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC_Usable,-XSAVE_Usable,-AVX2_Usable,-ERMS,-AVX_Usable,-AVX_Fast_Unaligned_Load
```

**Comment by tajila** [comment] 2022-09-13 13:47
This issue is solved by using changing the tuneables options to `GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load`

**Closed by tajila** 2022-09-13 13:47 UTC
Labels: comp:vm, criu
