### ISSUE TITLE
jdk23 concurrent/tck/JSR166TestCase crash vmState=0x00000000

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19366] opened 2024-04-23 13:42 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/2
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#forkjoinpool-common-parallelism

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/2/openjdk_test_output.tar.gz
```
00:57:48  STARTED    ClassSource [className = 'ForkJoinTask8Test', filePosition = null] 'testAbnormalQuietlyInvoke'
00:57:48  Unhandled exception
00:57:48  Type=Segmentation error vmState=0x00000000
00:57:48  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
00:57:48  Handler1=0000FFFFA6231854 Handler2=0000FFFFA6197BF0 InaccessibleAddress=00000000000004B0
00:57:48  R0=00000000000004A0 R1=00000000002010E4 R2=0000FFFFA616F940 R3=0000FFFFA69BC2F0
00:57:48  R4=0000000000000001 R5=0000FFFF9FDFFEB8 R6=0000FFFE9C005FC0 R7=0000FFFEED48071C
00:57:48  R8=0000000000000062 R9=0000FFFFA45DF0E4 R10=0000000000000020 R11=0000000000000092
00:57:48  R12=0000FFFF9FDE3F58 R13=0000000000000092 R14=0000000000000000 R15=0000000000000000
00:57:48  R16=0000FFFFA616F058 R17=0000FFFFA6999BF0 R18=000000083EE4000F R19=0000000000000000
00:57:48  R20=0000FFFE54012C30 R21=00000000000004B0 R22=0000FFFFA616E000 R23=0000FFFF9FDE3EE0
00:57:48  R24=000000083EE4000F R25=0000FFFF9FDE3F58 R26=0000000000000010 R27=0000FFFF9FE02EB8
00:57:48  R28=000000000000000D R29=0000FFFF1D7C6000 R30=0000FFFFA61495C0 R31=0000FFFF1D7C6000
00:57:48  PC=0000FFFFA6999C00 SP=0000FFFF1D7C6000 PSTATE=0000000040001000
00:57:48  V0 0000000000000005 (f: 5.000000, d: 2.470328e-323)
00:57:48  V1 408f400000000000 (f: 0.000000, d: 1.000000e+03)
00:57:48  V2 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
00:57:48  V3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V4 0000000100000001 (f: 1.000000, d: 2.121996e-314)
00:57:48  V5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V6 386b7361546e696f (f: 1416522112.000000, d: 6.453629e-37)
00:57:48  V7 7469736f50656c69 (f: 1348824192.000000, d: 5.831091e+252)
00:57:48  V8 000003c10000745f (f: 29791.000000, d: 2.039238e-311)
00:57:48  V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V16 4010040140100401 (f: 1074791424.000000, d: 4.003911e+00)
00:57:48  V17 feff000000000000 (f: 0.000000, d: -5.314683e+303)
00:57:48  V18 8000000000000000 (f: 0.000000, d: -0.000000e+00)
00:57:48  V19 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
00:57:48  V20 2182491194aab6bc (f: 2494215936.000000, d: 2.860073e-147)
00:57:48  V21 5b562fdf986fa411 (f: 2557453312.000000, d: 9.842758e+131)
00:57:48  V22 ac804d9cb0232fc6 (f: 2955096064.000000, d: -2.442438e-94)
00:57:48  V23 0000000000000008 (f: 8.000000, d: 3.952525e-323)
00:57:48  V24 3fd6666666666666 (f: 1717986944.000000, d: 3.500000e-01)
00:57:48  V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V26 0000000000000001 (f: 1.000000, d: 4.940656e-324)
00:57:48  V27 000000000000000a (f: 10.000000, d: 4.940656e-323)
00:57:48  V28 0000000000000001 (f: 1.000000, d: 4.940656e-324)
00:57:48  V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:57:48  V30 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
00:57:48  V31 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
00:57:48  Module=/lib/aarch64-linux-gnu/libpthread.so.0
00:57:48  Module_base_address=0000FFFFA6990000 Symbol=pthread_mutex_lock
00:57:48  Symbol_address=0000FFFFA6999BF0
00:57:48  Target=2_90_20240423_56 (Linux 5.4.0-176-generic)
00:57:48  CPU=aarch64 (8 logical CPUs) (0x1efe7e000 RAM)
00:57:48  ----------- Stack Backtrace -----------
00:57:48  pthread_mutex_lock+0x10 (0x0000FFFFA6999C00 [libpthread.so.0+0x9c00])
00:57:48  omrthread_interrupt+0x50 (0x0000FFFFA61495C0 [libj9thr29.so+0xa5c0])
00:57:48  Java_java_lang_Thread_interruptImpl+0x144 (0x0000FFFFA45DF228 [libjclse29.so+0x4b228])
00:57:48   (0x0000FFFF24DCAA28 [<unknown>+0x0])
00:57:48  ---------------------------------------
```

**Comment by pshipton** [comment] 2024-04-23 13:47
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/2
jdk_util_1
java/util/concurrent/tck/JSR166TestCase.java#others

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/2/openjdk_test_output.tar.gz
```
00:02:41  STARTED    ForkJoinTaskTest::testAbnormalForkGet 'testAbnormalForkGet'
00:02:41  Unhandled exception
00:02:41  Type=Segmentation error vmState=0x00000000
00:02:41  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=98d67ed5 Signal_Code=00000001
00:02:41  Handler1=000003FFA264A3B8 Handler2=000003FFA2531AB0 InaccessibleAddress=0000000000000000
00:02:41  gpr0=0000000000000019 gpr1=000003FF94C53FD8 gpr2=000003FF9C01EF70 gpr3=0000000000000028
00:02:41  gpr4=000003FFA09D7E08 gpr5=000003FE9C019340 gpr6=000003FF94C53FD0 gpr7=0000000000000052
00:02:41  gpr8=000003FF9C01EF70 gpr9=000003FFA2D51F90 gpr10=000003FEB87CAC00 gpr11=000003FEA4012200
00:02:41  gpr12=000003FF1AAA0328 gpr13=000003FEA4012200 gpr14=000003FFA09D7E08 gpr15=000003FFA0A7E400
00:02:41  psw=000003FFA09D7E82 mask=0705200180000000 fpc=0008fe00 bea=000003FFA208329C
00:02:41  fpr0 3dd0e96b00000000 (f: 0.000000, d: 6.152473e-11)
00:02:41  fpr1 4929ed0000000000 (f: 0.000000, d: 2.890821e+44)
00:02:41  fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:02:41  fpr3 3c3b26a600000000 (f: 0.000000, d: 1.471857e-18)
00:02:41  fpr4 4929ed0000000000 (f: 0.000000, d: 2.890821e+44)
00:02:41  fpr5 3e924c4100000000 (f: 0.000000, d: 2.726595e-07)
00:02:41  fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:02:41  fpr7 3e3a383500000000 (f: 0.000000, d: 6.104717e-09)
00:02:41  fpr8 000003ffa26aaa10 (f: 2724899328.000000, d: 2.172148e-311)
00:02:41  fpr9 000000000060ba08 (f: 6339080.000000, d: 3.131922e-317)
00:02:41  fpr10 000003ff9c01ef70 (f: 2617372416.000000, d: 2.172095e-311)
00:02:41  fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
00:02:41  fpr12 000616bb9e587a48 (f: 2656598528.000000, d: 8.467519e-309)
00:02:41  fpr13 000003fee8061288 (f: 3892712192.000000, d: 2.170603e-311)
00:02:41  fpr14 000003fff9bfb084 (f: 4190089472.000000, d: 2.172872e-311)
00:02:41  fpr15 000003fee8079538 (f: 3892811008.000000, d: 2.170603e-311)
00:02:41  Module=/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/lib/default/libjclse29.so
00:02:41  Module_base_address=000003FFA0980000 Symbol=Java_java_lang_Thread_interruptImpl
00:02:41  Symbol_address=000003FFA09D7DE0
00:02:41  Target=2_90_20240422_129 (Linux 3.10.0-1160.95.1.el7.s390x)
00:02:41  CPU=s390x (4 logical CPUs) (0x1ec1b1000 RAM)
00:02:41  ----------- Stack Backtrace -----------
00:02:41  Java_java_lang_Thread_interruptImpl+0xa2 (0x000003FFA09D7E82 [libjclse29.so+0x57e82])
00:02:41   (0x000003FF1AAA0274 [<unknown>+0x0])
00:02:41  ---------------------------------------
```

**Comment by tajila** [comment] 2024-04-25 12:52
FYI @babsingh

**Comment by knn-k** [comment] 2024-05-27 06:21
[The SEGV in `pthread_mutex_lock` on AArch64 Linux](https://github.com/eclipse-openj9/openj9/issues/19366#issue-2258922999) looks the same as #19544.
On the other hand, I am not sure if [the SEGV in `Java_java_lang_Thread_interruptImpl` on s390x Linux](https://github.com/eclipse-openj9/openj9/issues/19366#issuecomment-2072367626) is the same problem or not.

**Comment by babsingh** [comment] 2024-06-10 17:56
This is a duplicate of https://github.com/eclipse-openj9/openj9/issues/19544. See https://github.com/eclipse-openj9/openj9/issues/19544#issuecomment-2134060600 for more details.

**Closed by babsingh** 2024-06-10 17:56 UTC
Labels: comp:vm, test failure, jdk23
