### ISSUE TITLE
java.lang.IllegalArgumentException: Wrong type at constant pool index thrown after retransforming class

### ISSUE THREAD

**Issue by urisimchoni** [eclipse-openj9/openj9#13071] opened 2021-06-27 05:53 UTC
We have a Java agent which re-transforms Spring bean classes for the purpose of instrumentation. When Spring later pokes at those classes prior to instantiating the bean (looking for annotations and whatnot), we get a VM exception:

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration': Unexpected exception during bean creation; nested exception is java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.1.jar!/:2.5.1]
        at com.example.cpidx.sb.SbApplication.main(SbApplication.java:24) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_302-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_302-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_302-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_302-internal]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [sb-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [sb-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [sb-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [sb-1.0-SNAPSHOT.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration': Unexpected exception during bean creation; nested exception is java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:610) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$185/0x00000000ecb826e0.getObject(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:217) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[spring-boot-2.5.1.jar!/:2.5.1]
        ... 16 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration': Unexpected exception during bean creation; nested exception is java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:537) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$185/0x00000000ecb826e0.getObject(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$185/0x00000000ecb826e0.getObject(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:671) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getWebServerFactoryCustomizerBeans(WebServerFactoryCustomizerBeanPostProcessor.java:87) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getCustomizers(WebServerFactoryCustomizerBeanPostProcessor.java:78) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:70) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.8.jar!/:5.3.8]
        ... 25 common frames omitted
Caused by: java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:77) ~[na:1.8.0_302-internal]
        at java.lang.reflect.Executable.declaredAnnotations(Executable.java:602) ~[na:1.8.0_302-internal]
        at java.lang.reflect.Executable.declaredAnnotations(Executable.java:600) ~[na:1.8.0_302-internal]
        at java.lang.reflect.Executable.getAnnotation(Executable.java:570) ~[na:1.8.0_302-internal]
        at java.lang.reflect.Method.getAnnotation(Method.java:622) ~[na:1.8.0_302-internal]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.lambda$determineCandidateConstructors$0(AutowiredAnnotationBeanPostProcessor.java:268) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$$Lambda$299/0x00000000ece4ebe0.doWith(Unknown Source) ~[na:na]
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:324) ~[spring-core-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1284) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1201) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar!/:5.3.8]
        ... 48 common frames omitted
Caused by: java.lang.IllegalArgumentException: Wrong type at constant pool index
        at sun.reflect.ConstantPool.getClassAt0(Native Method) ~[na:1.8.0_302-internal]
        at sun.reflect.ConstantPool.getClassAt(ConstantPool.java:37) ~[na:1.8.0_302-internal]
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:244) ~[na:1.8.0_302-internal]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_302-internal]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_302-internal]
        ... 60 common frames omitted
```

The modified class bytes seem valid and this doesn't happen with HotSpot VM - I suspect it might be related somehow to some stale copy of the old, pre-transformation constant pool.

This happens with all AdoptOpenJDK versions that I've tried, specifically:
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210421_1000 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)
```
I was unable so far to reproduce this using a stripped-down  version of our agent, so the next best thing that may give a clue as to the root cause or at least how to reproduce is a core dump. I set up a (gdb) breakpoint at the point where the VM is throwing this exception, and generated a core file. The run was with -Xint, in the hope that it might improve debuggability or reduce JIT noise, and with own-built JDK. I'm not proficient enough with DDR Interactive (an awsome tool!) to figure this out, so I thought someone might help.

The core file is at https://drive.google.com/file/d/1CRtPwCCTmFeOZISt3Zoq9Y0g9DNrg8LK/view?usp=sharing . The tarball includes core file and unmodified+modified class files.

Please note that while the printed exception is failure of getClassAt0, the root failure is actually getUTF8At0. The getClassAt0 is attempted by the JDK as a fallback. The core file is at the failing getUTF8At0 (JDK trying to retrieve a string from the constant pool in order to parse annotations of a method)

Thanks,
Uri

**Comment by pshipton** [comment] 2021-06-28 17:02
@tajila fyi

**Comment by DanHeidinga** [comment] 2021-06-28 17:11
This looks like https://github.com/eclipse-openj9/openj9/issues/10026

**Comment by urisimchoni** [comment] 2021-06-28 17:34
> This looks like #10026

@DanHeidinga It might be, but it appears to be 100% repeatable with what I believe is single-threaded Java code (Spring-boot initialization process). OTOH, what does look like a multi-threading effect is that if I load and retransform the class before initializing spring-boot it doesn't happen - it only happens when the class is retransfromed right before creating the Spring bean (using an aspectJ advice on the bean creation)

**Comment by urisimchoni** [comment] 2021-07-01 07:33
OK I have a reproducer - this is different than #10026 IMHO.

I've created a small project to demonstrate the issue:

https://gitlab.com/urisimchoni/constant-pool-issue-demo

What happens here is that Spring caches java.lang.reflect.Method objects. Those objects have an annotation buffer and an indirect reference to a constant pool through the declaring class. After retransforming, the Method has the "old" annotation buffer, but the declaring class points to a different constant pool, hence the indices in the annotation buffer are invalid.

I've no idea why this doesn't happen with HotSpot VM - the Method class seems to be identical and the class object remains the same throughout the re-transformation, so it would seem logical to have the same issue with HotSpot, but it doesn't occur there.

I'll be looking at ways to clear the Spring cache as a workaround, but it seems Method caching is all over the place there, not just this ReflectionUtils cache.

**Comment by DanHeidinga** [comment] 2021-07-01 16:06
> I've no idea why this doesn't happen with HotSpot VM - the Method class seems to be identical and the class object remains the same throughout the re-transformation, so it would seem logical to have the same issue with HotSpot, but it doesn't occur there.

I've been told that Hotspot keeps the constantpool indices stable across retransforms (basically, only appending new cp entries) which isn't really a viable solution for J9 due to how we treat cp entries.  In particular, primitive data like longs / doubles are sorted to the end of the cp and only exist in the romclass so we don't waste space in the ramClass with duplicate data.

> After retransforming, the Method has the "old" annotation buffer, but the declaring class points to a different constant pool, hence the indices in the annotation buffer are invalid.

This hits the nail on the head and is the same root cause as #10026.  I think the solution proposed there would likely address both:
> Hack getDeclaredAnnotationsData to include the j9class pointer in the byte array in some way so we have the matching j9class for the data. Appending it would be the simplest if we can lie about the size of the data.

**Comment by urisimchoni** [comment] 2021-07-01 17:25
> This hits the nail on the head and is the same root cause as #10026. I think the solution proposed there would likely address both:
> 
> > Hack getDeclaredAnnotationsData to include the j9class pointer in the byte array in some way so we have the matching j9class for the data. Appending it would be the simplest if we can lie about the size of the data.

It seems like applying the fix for this issue would require a change in Method (which seems to be an unmodified OpenJDK class), whereas with #10026 the modification is in Class which is already an OpenJ9 implementation.

A possible workaround for us is to transform the class in such a way that indices remain the same - pretty much as you suggest HotSpot is doing internally. I'll look into that.
Thanks!
Uri

**Comment by urisimchoni** [comment] 2021-07-07 12:05
I've created a class transformer that keeps the existing constant pool intact. This still doesn't solve the problem - it fixes things for some classes but when loading a Spring-boot application, I still get some mismatches between Method's cached annotations and the constant pool.

If I use ASM library tree API to read the class into a ClassNode, then re-generate the byte code without any changes, then (with some minor ASM library tweaks) I get to a point where the old and new bytecode are the same, except for some class refs in the StackMapTables, which point to a different location in the constant pool, which defines the same class (assume we have two Class_Info entries in the constant pool, pointing to the same class name, then the modified class file only changes some StackMapTable entries to use the alternate index for Class_Info, and that's the only change). With this minor transformation, which is logically the same bytecode, I get the exception on some classes.

Could this be related to the fact that when the J9 VM retransforms a loaded class, it starts off with bytecode that's different from the on-disk bytecode? Seems like there used to be an -XX:-StoreIntermediateClassfile option which is no longer there (only appears in comment, traces and message translations)

**Comment by DanHeidinga** [comment] 2021-07-07 12:59
J9 does a lot of re-ordering of the constant pool to save space.  If a class has the following constants:
```
1 Class: A
2 utf8: foo
3 utf8: ()v
4 NaS: [2,3]
5 MethodRef: [1,4]
6 long: 5
```
and a new constant is added by a retransformation:
```
7 MethodRef: [1, 8]
8 NaS: [9, 10]
9 utf8: newMethod
10 utf8: ()Z
```

J9 will resort the cp to keep the `6 long: 5` at the end of the cp and get something like:
```
1 Class: A
2 utf8: foo
3 utf8: ()v
4 NaS: [2,3]
5 MethodRef: [1,4]
6 MethodRef: [1, 8]
7 NaS: [9, 10]
8 utf8: newMethod
9 utf8: ()Z
10 long: 5
```

So annotations that previously stored the index "6" to get the long value will now get a MethodRef.  And the actual transformations are more complex then this as things like NaS get removed almost entirely.

Is there a way for you to hook into the Spring-boot cache of Method objects?  If so, calling `getDeclaredAnnotations` on the methods before the retransform will reify the Annotation objects and cache them on the java heap.  Otherwise, a VM solution that saves the J9Class pointer in the annotation data in some way is needed.

**Comment by tajila** [comment] 2021-12-14 14:26
This has been fixed in 0.30

**Closed by tajila** 2021-12-14 14:26 UTC
Labels: comp:vm, userRaised

**Comment by bvsvas** [comment] 2023-04-24 11:51
Is it fixed? I get the same error `AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index` It comes while hitting REST Endpoint in Spring Boot application deployed in WebSphere Liberty. It only comes when call was made after class retransformation by java agent. This error doesn't come if endpoint hits before class retransformation. 

**JDK used:**
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 8.0.8.0 - pxa6480sr8-20230314_01(SR8))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230313_47323 (JIT enabled, AOT enabled)
OpenJ9   - 4d03a8c
OMR      - 49526cb
IBM      - 7187a01

**Error stack trace:**

```
Caused by: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.ConstantPool.getClassAt0(Native Method)
	at sun.reflect.ConstantPool.getClassAt(ConstantPool.java:49)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:256)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:238)
	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations2(AnnotationParser.java:196)
	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations(AnnotationParser.java:173)
Caused by: java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.annotation.AnnotationParser.parseParameterAnnotations(AnnotationParser.java:179)
	at java.lang.reflect.Executable.parseParameterAnnotations(Executable.java:91)
	at java.lang.reflect.Executable.sharedGetParameterAnnotations(Executable.java:566)
	at java.lang.reflect.Method.getParameterAnnotations(Method.java:660)
	at org.springframework.core.MethodParameter.getParameterAnnotations(MethodParameter.java:635)
	at org.springframework.web.method.HandlerMethod$HandlerMethodParameter.getParameterAnnotations(HandlerMethod.java:541)
	at org.springframework.core.MethodParameter.getParameterAnnotation(MethodParameter.java:668)
	at org.springframework.core.MethodParameter.hasParameterAnnotation(MethodParameter.java:683)
	at org.springframework.web.method.annotation.ModelFactory.findSessionAttributeArguments(ModelFactory.java:182)
	at org.springframework.web.method.annotation.ModelFactory.initModel(ModelFactory.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:872)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
```

**Comment by tajila** [comment] 2023-04-24 13:05
@bvsvas Can you send us a test application to reproduce?

**Comment by bvsvas** [comment] 2023-04-25 03:37
Opened a new issue# https://github.com/eclipse-openj9/openj9/issues/17265

**Comment by bvsvas** [comment] 2023-04-26 05:40
Provided test application to reproduce this issue in the issue# https://github.com/eclipse-openj9/openj9/issues/17265

**Comment by 123liuziming** [comment] 2023-07-06 06:10
Does the problem only appear while using Spring due to the Method Cache of the Spring?
