### ISSUE TITLE
DaaLoadTest_all_special_5m_9_FAILED testLessThanOrEqualsPackedDecimal(net.openj9.test.arithmetics.TestArithmeticInline):ClassCastException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19884] opened 2024-07-19 20:47 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_special.system_ppc64le_linux_testList_6/16/)(`ubu22lert-3`):
```
java version "11.0.24-beta" 2024-07-16
IBM Semeru Runtime Certified Edition 11.0.24+7-202407130107 (build 11.0.24-beta+7-202407130107)
Eclipse OpenJ9 VM 11.0.24+7-202407130107 (build master-d2b02cf3c7, JRE 11 Linux ppc64le-64-Bit Compressed References 20240713_896 (JIT enabled, AOT enabled)
OpenJ9   - d2b02cf3c7
OMR      - de311dd2b
JCL      - 10dcb53639 based on jdk-11.0.24+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=DaaLoadTest_all_special_5m_9&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_special.system_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F896%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK11U_2024-07-13-01-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=745&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-07-13T03:09:48.962Z] variation: Mode187
[2024-07-13T03:09:48.962Z] JVM_OPTIONS:  -Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs 

[2024-07-13T03:11:05.803Z] DLT 03:11:04.541 - suite.isCreateDump() : false
[2024-07-13T03:11:05.803Z] DLT 03:11:04.600 - Test failed
[2024-07-13T03:11:05.803Z] DLT   Failure num.  = 1
[2024-07-13T03:11:05.803Z] DLT   Test number   = 3
[2024-07-13T03:11:05.803Z] DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestArithmeticInline]'
[2024-07-13T03:11:05.803Z] DLT   Suite number  = 0
[2024-07-13T03:11:05.803Z] DLT   Thread number = 20
[2024-07-13T03:11:05.803Z] DLT >>> Captured test output >>>

[2024-07-13T03:11:05.803Z] DLT testFailure: testLessThanOrEqualsPackedDecimal(net.openj9.test.arithmetics.TestArithmeticInline): java.lang.ClassCastException@7b912d0c
[2024-07-13T03:11:05.803Z] DLT java.lang.IllegalArgumentException: java.lang.ClassCastException@7b912d0c
[2024-07-13T03:11:05.803Z] DLT 	at jdk.internal.reflect.GeneratedMethodAccessor3153.invoke(Unknown Source)
[2024-07-13T03:11:05.803Z] DLT 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-07-13T03:11:05.803Z] DLT 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-07-13T03:11:05.803Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2024-07-13T03:11:05.804Z] DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2024-07-13T03:11:05.804Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
[2024-07-13T03:11:05.804Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2024-07-13T03:11:05.804Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-07-13T03:11:05.804Z] DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-07-13T03:11:05.804Z] DLT 	at java.base/java.lang.Thread.run(Thread.java:839)

[2024-07-13T03:11:07.319Z] DaaLoadTest_all_special_5m_9_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42206/) - 2 failures reproduced at the same machine [ubu22lert-3](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/4058/consoleFull)
```
17:45:33  DLT java.lang.IllegalArgumentException: object is not an instance of declaring class
17:45:33  DLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:45:33  DLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:45:33  DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:45:33  DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:572)
17:45:33  DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
17:45:33  DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
17:45:33  DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
17:45:33  DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
17:45:33  DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
17:45:33  DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
17:45:33  DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
17:45:33  DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
17:45:33  DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
17:45:33  DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
17:45:33  DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
17:45:33  DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
17:45:33  DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
17:45:33  DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
17:45:33  DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
17:45:33  DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
17:45:33  DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
17:45:33  DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
17:45:33  DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
17:45:33  DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
17:45:33  DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
17:45:33  DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
17:45:33  DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
17:45:33  DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
17:45:33  DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
17:45:33  DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
17:45:33  DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
17:45:33  DLT 	at java.base/java.lang.Thread.run(Thread.java:839)
17:45:33  DLT testFinished: testConvert1234Unsigned(net.openj9.test.decimals.TestPD2UD)
17:45:33  DLT 
17:45:33  DLT JUnit Test Results for: net.openj9.test.decimals.TestPD2UD
17:45:33  DLT   Ran    : 9
17:45:33  DLT   Passed : 0
17:45:33  DLT   Failed : 9
17:45:33  DLT   Ignored: 0
17:45:33  DLT   Result : FAILED
17:45:33  DLT <<<
```

**Comment by pshipton** [comment] 2024-07-23 17:36
If investigating this, see also https://github.com/eclipse-openj9/openj9/issues/19882

**Comment by vij-singh** [comment] 2024-09-19 14:47
@zl-wang FYI

**Comment by zl-wang** [comment] 2024-09-19 15:01
@ishitaR88  please investigate

**Comment by vij-singh** [comment] 2024-09-24 12:42
Any new updates for this issue?

**Comment by ishitaR88** [comment] 2024-09-24 12:45
I am still investigating this.

**Comment by ishitaR88** [comment] 2024-09-30 15:43
This intermittent test failure is so far reproducible only on ubu22lert-3 machine. Errors are different for each failure. But they all are related to invalid pointer. To look more into this issue I will run this test physically on ubu22lert-3.

**Comment by pshipton** [comment] 2024-09-30 17:20
FYI https://github.com/eclipse-openj9/openj9/issues/20261

**Comment by rmnattas** [comment] 2024-10-11 16:59
Suggesting moving to 0.49 or closing.
Couldn't confirm if this is a duplicate of #20263 or a separate issue. Running a 50x [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44081/) with the fix on `ubu22lert-3`.
#20263 fixed patching ConstantSnippets. Although this is not in P10 (where ConstantSnippets is used mainly instead of pTOC), previous POWER HW uses ConstantSnippets when the pTOC is filled.
If duplicate then solved, if separate then its low frequency and risk failure by itself and can be moved to 0.49 as no time before deadline.

**Comment by pshipton** [comment] 2024-10-11 17:11
Trying a grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3892/
Given the results https://github.com/eclipse-openj9/openj9/issues/20261#issuecomment-2407812159 I expect to close this.

**Comment by pshipton** [comment] 2024-10-11 18:58
Closing as the previous two grinders have passed.

**Closed by pshipton** 2024-10-11 18:58 UTC
Labels: comp:jit, test failure
