### ISSUE TITLE
DBBLoadTest_5m OutOfMemoryError Java heap space  and Cannot invoke "java.util.List.size()" because "this.inputArrayOfLinkedLists[i]" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17574] opened 2023-06-12 13:29 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_aarch64_linux_Nightly_testList_0/464
DBBLoadTest_5m_0 `-XX:+UseCompressedOops`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_extended.system_aarch64_linux_Nightly_testList_0/464/system_test_output.tar.gz
```
DBLT java.lang.OutOfMemoryError: Java heap space
DBLT 	at java.nio.HeapLongBuffer.<init>(HeapLongBuffer.java:64) ~[?:?]
DBLT 	at java.nio.LongBuffer.allocate(LongBuffer.java:363) ~[?:?]
DBLT 	at net.adoptopenjdk.test.nio.NioBuffersTest$Buffers$BufferThread.run(NioBuffersTest.java:913) ~[bin/:?]
DBLT 	at java.lang.Thread.run(Thread.java:857) [?:?]
```

```
DBLT 19:57:03.882 - Test failed
DBLT   Failure num.  = 1
DBLT   Test number   = 3
DBLT   Test details  = 'ArbitraryJava[net.adoptopenjdk.test.nio.NioBuffersTest run]'
DBLT   Suite number  = 0
DBLT   Thread number = 5
DBLT >>> Captured test output >>>
DBLT null Convert: Loop Count =  0
DBLT starting thread 0.............
DBLT starting thread 1.............
DBLT ------------------------------------------ my name is thread 0
DBLT starting thread 2.............
DBLT Thread 0 - nTypeOfBuffer = long
DBLT starting thread 3.............
DBLT Thread 0 - dRandomNumber2 = 0.7848441127214913
DBLT Thread 0 - creating a buffer of size 822968 bytes
DBLT Thread 0 - nNumberOfBytes per type = 8
DBLT Thread 0 - after capping - nNumberOfRandomNumbers = 10
DBLT starting thread 4.............
DBLT ------------------------------------------ my name is thread 2
DBLT starting thread 5.............
DBLT Thread 2 - nTypeOfBuffer = short
DBLT Thread 0 - have created char buffer by wrapping an array with space for 102871 longs
DBLT ------------------------------------------ my name is thread 3
DBLT ------------------------------------------ my name is thread 4
DBLT Thread 3 - nTypeOfBuffer = short
DBLT Thread 2 - dRandomNumber2 = 0.24499333253380673
DBLT Thread 3 - dRandomNumber2 = 0.5616704213979157
DBLT ------------------------------------------ my name is thread 5
DBLT Thread 3 - creating a buffer of size 588954 bytes
DBLT Thread 0 has now created a ByteBuffer of size 822968 bytes
DBLT Thread 5 - nTypeOfBuffer = short
DBLT Thread 4 - nTypeOfBuffer = long
DBLT Thread 3 - nNumberOfBytes per type = 2
DBLT Thread 5 - dRandomNumber2 = 0.6901452111624643
DBLT Thread 3 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 2 - creating a buffer of size 256894 bytes
DBLT Thread 3 - have created char buffer by wrapping an array with space for 294477 shorts
DBLT Thread 5 - creating a buffer of size 723669 bytes
DBLT Thread 2 - nNumberOfBytes per type = 2
DBLT Thread 4 - dRandomNumber2 = 0.8000173491472538
DBLT Thread 3 has now created a ByteBuffer of size 588954 bytes
DBLT Thread 4 - creating a buffer of size 838878 bytes
DBLT Thread 5 - nNumberOfBytes per type = 2
DBLT Thread 4 - nNumberOfBytes per type = 8
DBLT Thread 5 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 4 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 2 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 4 - have created char buffer by wrapping an array with space for 104859 longs
DBLT Thread 5 - have created char buffer by wrapping an array with space for 361834 shorts
DBLT ------------------------------------------ my name is thread 1
DBLT Thread 2 - have created char buffer by wrapping an array with space for 128447 shorts
DBLT Thread 1 - nTypeOfBuffer = long
DBLT Thread 5 has now created a ByteBuffer of size 723669 bytes
DBLT Thread 4 has now created a ByteBuffer of size 838878 bytes
DBLT Thread 1 - dRandomNumber2 = 0.7211298451621307
DBLT Thread 2 has now created a ByteBuffer of size 256894 bytes
DBLT Thread 1 - creating a buffer of size 756159 bytes
DBLT Thread 1 - nNumberOfBytes per type = 8
DBLT starting thread 6.............
DBLT Thread 1 - after capping - nNumberOfRandomNumbers = 10
DBLT ------------------------------------------ my name is thread 6
DBLT starting thread 7.............
DBLT starting thread 8.............
DBLT starting thread 9.............
DBLT Thread 6 - nTypeOfBuffer = double
DBLT ------------------------------------------ my name is thread 8
DBLT Thread 6 - dRandomNumber2 = 0.35381325741201264
DBLT Thread 6 - creating a buffer of size 371000 bytes
DBLT Thread 8 - nTypeOfBuffer = char
DBLT Thread 6 - nNumberOfBytes per type = 8
DBLT Thread 6 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 8 - dRandomNumber2 = 0.0066037547838221355
DBLT Thread 6 - have created char buffer by wrapping an array with space for 46375 doubles
DBLT Thread 8 - creating a buffer of size 6924 bytes
DBLT Thread 8 - nNumberOfBytes per type = 2
DBLT Thread 6 has now created a ByteBuffer of size 371000 bytes
DBLT Thread 8 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 8 - have created char buffer by wrapping an array with space for 3462 chars
DBLT Thread 8 has now created a ByteBuffer of size 6924 bytes
DBLT ------------------------------------------ my name is thread 9
DBLT Thread 9 - nTypeOfBuffer = short
DBLT Thread 9 - dRandomNumber2 = 0.26861822417038317
DBLT Thread 9 - creating a buffer of size 281666 bytes
DBLT Thread 9 - nNumberOfBytes per type = 2
DBLT Thread 9 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 9 - have created char buffer by wrapping an array with space for 140833 shorts
DBLT Thread 9 has now created a ByteBuffer of size 281666 bytes
DBLT ------------------------------------------ my name is thread 7
DBLT Thread 7 - nTypeOfBuffer = char
DBLT Thread 7 - dRandomNumber2 = 0.8646880827067245
DBLT Thread 7 - creating a buffer of size 906691 bytes
DBLT Thread 7 - nNumberOfBytes per type = 2
DBLT Thread 7 - after capping - nNumberOfRandomNumbers = 10
DBLT Thread 7 - have created char buffer by allocating space for 453345 chars ( = 906690 bytes)
DBLT Thread 7 has now created a ByteBuffer of size 906691 bytes
DBLT All threads have now died..............................................
DBLT typeOfBuffer[0] = 5
DBLT numberOfBytes[0] = 8
DBLT sizeOfBufferInBytes[0] = 822968
DBLT numberOfRandomNumbers[0] = 10
DBLT inputArrayOfLinkedLists[i].size() = 10
DBLT typeOfBuffer[1] = 5
DBLT numberOfBytes[1] = 8
DBLT sizeOfBufferInBytes[1] = 756159
DBLT numberOfRandomNumbers[1] = 10
DBLT Test failed:
DBLT java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.inputArrayOfLinkedLists[i]" is null
DBLT 	at net.adoptopenjdk.test.nio.NioBuffersTest$Buffers.work(NioBuffersTest.java:247)
DBLT 	at net.adoptopenjdk.test.nio.NioBuffersTest.run(NioBuffersTest.java:103)
DBLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DBLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
DBLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DBLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
DBLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
DBLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
DBLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
DBLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
DBLT 	at java.base/java.lang.Thread.run(Thread.java:857)
```

Changes from previous build.
https://github.com/eclipse-openj9/openj9/compare/bad620fcdfe0...fd647ffb085
https://github.com/eclipse-openj9/openj9-omr/compare/8cdf471e9aa...06fe1c3b915

**Comment by dmitripivkine** [comment] 2023-06-12 17:36
Looks like the problem is GC has not expanded heap as expected. Investigating.

**Comment by dmitripivkine** [comment] 2023-06-12 17:46
We have observed similar behaviour with optthruput https://github.com/eclipse-openj9/openj9/issues/17116

**Comment by pshipton** [comment] 2023-06-19 17:52
@dmitripivkine did you mean to close this yet? We shouldn't use close keywords in commit comments, but only in the PR descriptions.

**Comment by dmitripivkine** [comment] 2023-06-27 17:29
This issue should be fixed by https://github.com/eclipse/omr/pull/7040

**Closed by dmitripivkine** 2023-06-27 17:29 UTC
Labels: comp:gc, test failure
