### ISSUE TITLE
SC_Softmx_JitAot_1 crash vmState=0x0002000f

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14119] opened 2021-12-09 13:08 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/169
SC_Softmx_JitAot_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/169/system_test_output.tar.gz
```
STF 00:06:09.083 - +------ Step 16 - Run Jvm4 workload process
STF 00:06:09.083 - | Run foreground process
STF 00:06:09.083 - |   Program:     F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdkbinary/j2sdk-image/bin/java
STF 00:06:09.083 - |   Mnemonic:    jvm4
STF 00:06:09.083 - |   Echo:        ECHO_OFF
STF 00:06:09.083 - |   Expectation: NON_ZERO_EXIT [0, 1] within 30m
STF 00:06:09.083 - |
STF 00:06:09.083 - Running command: F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdkbinary/j2sdk-image/bin/java -Xshareclasses:addtestjithints,verbose,name=SCC_SysTest_Workload_Cache,cacheDir=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16390272801172\SC_Softmx_JitAot_1\20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot\results\cache -Xaot:forceAot,disableAsyncCompilation,count=0 -Xcompressedrefs -Xjit -Xgcpolicy:gencon -classpath F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\STF\stf.load\bin;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\STF\stf.core\bin;F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/systemtest_prereqs/log4j/log4j-api.jar;F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/systemtest_prereqs/log4j/log4j-core.jar;F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/systemtest_prereqs/junit/junit.jar;F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/systemtest_prereqs/junit/hamcrest-core.jar;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\aqa-systemtest\openjdk.test.lang\bin;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\aqa-systemtest\openjdk.test.util\bin;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\aqa-systemtest\openjdk.test.math\bin;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\aqa-systemtest\openjdk.test.classloading\bin;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\aqa-systemtest\openjdk.test.nio\bin;F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\jvmtest\system\openj9-systemtest\openj9.test.daa\bin net.adoptopenjdk.loadTest.LoadTest -resultsDir F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16390272801172\SC_Softmx_JitAot_1\20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot\results -resultsPrefix 16.jvm4. -dumpRequested false -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.sharedclasses-mix.inventoryFile F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/aqa-tests/TKG/output_16390272801172/SC_Softmx_JitAot_1/20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results/16.jvm4.inventory/openj9.test.load/config/inventories/mix/sharedclasses-mix.xml -suite.sharedclasses-mix.inventoryExcludeFile F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/aqa-tests/TKG/output_16390272801172/SC_Softmx_JitAot_1/20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results/16.jvm4.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.sharedclasses-mix.inventoryExcludeFile F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/aqa-tests/TKG/output_16390272801172/SC_Softmx_JitAot_1/20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results/16.jvm4.inventory/openjdk.test.load/config/inventories/util/util_exclude.xml -suite.sharedclasses-mix.threadCount 7 -suite.sharedclasses-mix.totalNumberTests 500 -suite.sharedclasses-mix.selection sequential -suite.sharedclasses-mix.seed -1 -suite.sharedclasses-mix.repeatCount 1 -suite.sharedclasses-mix.thinkingTime 0ms..0ms
STF 00:06:09.083 - Redirecting stderr to F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/aqa-tests/TKG/output_16390272801172/SC_Softmx_JitAot_1/20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results/16.jvm4.stderr
STF 00:06:09.083 - Redirecting stdout to F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/aqa-tests/TKG/output_16390272801172/SC_Softmx_JitAot_1/20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results/16.jvm4.stdout
STF 00:06:09.085 - Monitoring processes: jvm4
STF 00:06:28.348 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16390272801172\SC_Softmx_JitAot_1\20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot\results\core.20211209.000628.3484.0001.dmp
STF 00:06:29.161 - Found dump at: F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\aqa-tests\TKG\output_16390272801172\SC_Softmx_JitAot_1\20211209-000544-SharedClassesWorkloadTest_Softmx_Increase_JitAot\results\core.20211209.000628.3484.0002.dmp
STF 00:06:29.796 - **FAILED** Process jvm4 ended with exit code (4294967295) and not the expected exit code/s (0,1)
STF 00:06:29.796 - Monitoring Report Summary:
STF 00:06:29.796 -   o Process jvm4 has crashed unexpectedly
```

16.jvm4.stderr
```
JVMJITM018W Async Compilation feature mismatch. Ignoring AOT code in shared class cache.
Unhandled exception
Type=Segmentation error vmState=0x0002000f
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFAFAF101C3 ContextFlags=0010005f
Handler1=00007FFAFC61A7D0 Handler2=00007FFAFD0B93B0 InaccessibleReadAddress=0000000000000018
RDI=000000B5AA59EFB8 RSI=000000B5A6E23950 RAX=000000B5A6249558 RBX=0000000000000000
RCX=0000000000000000 RDX=000000B5AA59EFB8 R8=000000B5AB60EDA0 R9=000000B5A6ABB360
R10=0000000000000010 R11=000000B5AB60EA08 R12=0000000000000000 R13=000000B5AA59EFB8
R14=0000000000000000 R15=000000B5AB60EA98
RIP=00007FFAFAF101C3 RSP=000000B5AB60E990 RBP=0000000000000000 EFLAGS=0000000000010246
FS=0053 ES=002B DS=002B
XMM0 000000000000000e (f: 14.000000, d: 6.916919e-323)
XMM1 000000005f000000 (f: 1593835520.000000, d: 7.874594e-315)
XMM2 4093bc0000000000 (f: 0.000000, d: 1.263000e+003)
XMM3 3ffa9e6b5579fdbf (f: 1434058112.000000, d: 1.663677e+000)
XMM4 412a7e6be9c547a6 (f: 3922020352.000000, d: 8.681500e+005)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\openjdkbinary\j2sdk-image\jre\bin\default\j9gc29.dll
Module_base_address=00007FFAFADD0000 Offset_in_DLL=00000000001401c3
Target=2_90_20211208_172 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
Unhandled exception
Type=Segmentation error vmState=0x0002000f
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFAFAF101C3 ContextFlags=0010005f
Handler1=00007FFAFC61A7D0 Handler2=00007FFAFD0B93B0 InaccessibleReadAddress=0000000000000018
RDI=000000B5AA5B1568 RSI=000000B5A6E23950 RAX=000000B5A6249558 RBX=0000000000000000
RCX=0000000000000000 RDX=000000B5AA5B1568 R8=000000B5AB90F3E0 R9=000000B5A6ABB360
R10=0000000000000010 R11=000000B5AB90F048 R12=0000000000000000 R13=000000B5AA5B1568
R14=0000000000000000 R15=000000B5AB90F0D8
RIP=00007FFAFAF101C3 RSP=000000B5AB90EFD0 RBP=0000000000000000 EFLAGS=0000000000010246
FS=0053 ES=002B DS=002B
XMM0 3fffcae7497e5740 (f: 1233016576.000000, d: 1.987037e+000)
XMM1 000000005f000000 (f: 1593835520.000000, d: 7.874594e-315)
XMM2 4093fc0000000000 (f: 0.000000, d: 1.279000e+003)
XMM3 3fffa7c1819e90d8 (f: 2174652672.000000, d: 1.978456e+000)
XMM4 412fcae7fa85e462 (f: 4203078656.000000, d: 1.041780e+006)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\openjdkbinary\j2sdk-image\jre\bin\default\j9gc29.dll
Module_base_address=00007FFAFADD0000 Offset_in_DLL=00000000001401c3
Target=2_90_20211208_172 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
J9VMDllMain+0x13f1b3 (0x00007FFAFAF101C3 [j9gc29+0x1401c3])
J9VMDllMain+0x106116 (0x00007FFAFAED7126 [j9gc29+0x107126])
J9VMDllMain+0x102694 (0x00007FFAFAED36A4 [j9gc29+0x1036a4])
J9VMDllMain+0x10953a (0x00007FFAFAEDA54A [j9gc29+0x10a54a])
J9VMDllMain+0x16aaa (0x00007FFAFADE7ABA [j9gc29+0x17aba])
Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x500e80 (0x00007FFAFB731460 [j9jit29+0x5c1460])
Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x4ffcd8 (0x00007FFAFB7302B8 [j9jit29+0x5c02b8])
J9_GetInterface+0x2a710 (0x00007FFAFC651960 [j9vm29+0x101960])
J9VMDllMain+0x16a65 (0x00007FFAFADE7A75 [j9gc29+0x17a75])
J9VMDllMain+0x138de (0x00007FFAFADE48EE [j9gc29+0x148ee])
J9VMDllMain+0x13be3 (0x00007FFAFADE4BF3 [j9gc29+0x14bf3])
J9VMDllMain+0x12a9e (0x00007FFAFADE3AAE [j9gc29+0x13aae])
J9VMDllMain+0x10182e (0x00007FFAFAED283E [j9gc29+0x10283e])
J9VMDllMain+0x123f22 (0x00007FFAFAEF4F32 [j9gc29+0x124f32])
J9VMDllMain+0x124f9f (0x00007FFAFAEF5FAF [j9gc29+0x125faf])
j9port_isCompatible+0x180e0 (0x00007FFAFD0BA8A0 [j9prt29+0x1a8a0])
J9VMDllMain+0x1250fb (0x00007FFAFAEF610B [j9gc29+0x12610b])
omrthread_get_category+0x818 (0x00007FFAFE663D18 [j9thr29+0x3d18])
_beginthreadex+0x107 (0x00007FFAFC814F7F [msvcr120+0x24f7f])
_endthreadex+0x192 (0x00007FFAFC815126 [msvcr120+0x25126])
BaseThreadInitThunk+0x22 (0x00007FFB0E4213F2 [KERNEL32+0x13f2])
RtlUserThreadStart+0x34 (0x00007FFB0E5D54F4 [ntdll+0x154f4])
---------------------------------------
J9VMDllMain+0x13f1b3 (0x00007FFAFAF101C3 [j9gc29+0x1401c3])
J9VMDllMain+0x106116 (0x00007FFAFAED7126 [j9gc29+0x107126])
J9VMDllMain+0x102694 (0x00007FFAFAED36A4 [j9gc29+0x1036a4])
J9VMDllMain+0x10953a (0x00007FFAFAEDA54A [j9gc29+0x10a54a])
J9VMDllMain+0x16aaa (0x00007FFAFADE7ABA [j9gc29+0x17aba])
Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x500e80 (0x00007FFAFB731460 [j9jit29+0x5c1460])
Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x4ffcd8 (0x00007FFAFB7302B8 [j9jit29+0x5c02b8])
J9_GetInterface+0x2a710 (0x00007FFAFC651960 [j9vm29+0x101960])
J9VMDllMain+0x16a65 (0x00007FFAFADE7A75 [j9gc29+0x17a75])
J9VMDllMain+0x138de (0x00007FFAFADE48EE [j9gc29+0x148ee])
J9VMDllMain+0x13be3 (0x00007FFAFADE4BF3 [j9gc29+0x14bf3])
J9VMDllMain+0x12a9e (0x00007FFAFADE3AAE [j9gc29+0x13aae])
J9VMDllMain+0x10182e (0x00007FFAFAED283E [j9gc29+0x10283e])
J9VMDllMain+0x123f22 (0x00007FFAFAEF4F32 [j9gc29+0x124f32])
J9VMDllMain+0x124f9f (0x00007FFAFAEF5FAF [j9gc29+0x125faf])
j9port_isCompatible+0x180e0 (0x00007FFAFD0BA8A0 [j9prt29+0x1a8a0])
J9VMDllMain+0x1250fb (0x00007FFAFAEF610B [j9gc29+0x12610b])
omrthread_get_category+0x818 (0x00007FFAFE663D18 [j9thr29+0x3d18])
_beginthreadex+0x107 (0x00007FFAFC814F7F [msvcr120+0x24f7f])
_endthreadex+0x192 (0x00007FFAFC815126 [msvcr120+0x25126])
BaseThreadInitThunk+0x22 (0x00007FFB0E4213F2 [KERNEL32+0x13f2])
RtlUserThreadStart+0x34 (0x00007FFB0E5D54F4 [ntdll+0x154f4])
---------------------------------------
```

**Comment by pshipton** [comment] 2021-12-09 13:17
@dmitripivkine fyi. Not sure if this is a dup of an older issue such as https://github.com/eclipse-openj9/openj9/issues/10984

**Comment by dmitripivkine** [comment] 2021-12-09 18:36
yes, this looks like a duplicate of https://github.com/eclipse-openj9/openj9/issues/10984
Closing this item. I am going to update parent item with triage data

**Closed by dmitripivkine** 2021-12-09 18:36 UTC
Labels: comp:gc, test failure, segfault
