### ISSUE TITLE
Cannot invoke java.lang.invoke.MethodHandle.linkToVirtual because XX is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13129] opened 2021-07-06 17:38 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_x86-64_mac_Nightly/42
jdk11_tier1_buffer_0
JVM_OPTIONS:  -XX:+UseCompressedOops 
java/nio/Buffer/EqualsCompareTest.java
```
01:06:25  test EqualsCompareTest.testBuffers(java.nio.ByteBuffer HEAP): failure
01:06:25  java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, int, java.lang.invoke.MemberName)" because "<parameter1>" is null
01:06:25  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
01:06:25  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
01:06:25  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
01:06:25  	at EqualsCompareTest$BufferType.set(EqualsCompareTest.java:145)
01:06:25  	at EqualsCompareTest.lambda$testBuffers$1(EqualsCompareTest.java:529)
01:06:25  	at EqualsCompareTest$$Lambda$400/0x000000005a8f1628.apply(Unknown Source)
01:06:25  	at EqualsCompareTest.testBufferType(EqualsCompareTest.java:672)
01:06:25  	at EqualsCompareTest.testBuffers(EqualsCompareTest.java:534)
```

**Comment by pshipton** [comment] 2021-07-06 17:44
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_1/43
LangLoadTest_5m_1
JVM_OPTIONS:  -XX:-UseCompressedOops
```
LLT Step 1.
LLT Step 2Test failed:
LLT java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, long, java.lang.Object, java.lang.invoke.MemberName)" because "java.lang.invoke.LambdaForm$DMH.0x0000000000000000._DATA_DirectMethodHandle_1" is null
LLT 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
LLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
LLT 	at net.adoptopenjdk.test.lang.invoke.BasicTest.doTest(BasicTest.java:108)
```

**Comment by pshipton** [comment] 2021-07-07 11:28
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Nightly/45
java/nio/Buffer/EqualsCompareTest.java
```
01:56:38  test EqualsCompareTest.testBuffers(java.nio.ByteBuffer HEAP): failure
01:56:38  java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, int, java.lang.invoke.MemberName)" because "<parameter1>" is null
01:56:38  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
01:56:38  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
01:56:38  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
01:56:38  	at EqualsCompareTest$BufferType.set(EqualsCompareTest.java:145)
01:56:38  	at EqualsCompareTest.lambda$testBuffers$1(EqualsCompareTest.java:529)
01:56:38  	at EqualsCompareTest$$Lambda$400/0x0000000074120748.apply(Unknown Source)
01:56:38  	at EqualsCompareTest.testBufferType(EqualsCompareTest.java:672)
01:56:38  	at EqualsCompareTest.testBuffers(EqualsCompareTest.java:534)
```

**Comment by pshipton** [comment] 2021-07-07 11:35
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/45/
java/nio/Buffer/EqualsCompareTest.java
```
23:17:29  test EqualsCompareTest.testBuffers(java.nio.ByteBuffer HEAP): failure
23:17:29  java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, int, java.lang.invoke.MemberName)" because "<parameter1>" is null
23:17:29  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
23:17:29  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
23:17:29  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
23:17:29  	at EqualsCompareTest$BufferType.set(EqualsCompareTest.java:145)
23:17:29  	at EqualsCompareTest.lambda$testBuffers$1(EqualsCompareTest.java:529)
23:17:29  	at EqualsCompareTest$$Lambda$94/0x000000005d343458.apply(Unknown Source)
23:17:29  	at EqualsCompareTest.testBufferType(EqualsCompareTest.java:672)
23:17:29  	at EqualsCompareTest.testBuffers(EqualsCompareTest.java:534)
```

**Comment by pshipton** [comment] 2021-07-08 11:48
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.system_x86-64_mac_Nightly_testList_0/43
ObjectTreeLoadTest_5m_1
```
OLT java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, long, java.lang.Object, java.lang.invoke.MemberName)" because "java.lang.invoke.LambdaForm$DMH.0x0000000000000000._DATA_DirectMethodHandle_1" is null
OLT 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
OLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
OLT 	at net.adoptopenjdk.test.lang.invoke.BasicTest.doTest(BasicTest.java:108)
```

**Comment by pshipton** [comment] 2021-07-08 11:48
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_x86-64_mac_Nightly/44/
java/nio/Buffer/EqualsCompareTest.java

**Comment by fengxue-IS** [comment] 2021-07-09 19:29
I am unable to reproduce this issue locally without the testng frame work, will try running grinder with debug jdk

**Comment by JasonFengJ9** [comment] 2021-08-19 11:53
It is observed w/ a recent JDK16 build at `Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Personal/81/consoleFull`
```
18:08:39  openjdk version "16.0.2-internal" 2021-07-20
18:08:39  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16x86-64linuxPersonal)
18:08:39  Eclipse OpenJ9 VM (build master-cd8db74f1d4, JRE 16 Linux amd64-64-Bit Compressed References 20210818_283 (JIT enabled, AOT enabled)
18:08:39  OpenJ9   - cd8db74f1d4
18:08:39  OMR      - ac3ab4821a5
18:08:39  JCL      - 44316ee515b based on jdk-16.0.2+7)

20:46:00  ===============================================
20:46:00  Running test jdk11_tier1_buffer_1 ...
20:46:00  ===============================================
20:46:00  jdk11_tier1_buffer_1 Start Time: Wed Aug 18 17:45:58 2021 Epoch Time (ms): 1629333958989
20:46:00  "/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
20:46:00  JVMSHRC005I No shared class caches available
20:46:00  JVMSHRC005I No shared class caches available
20:46:00  cache cleanup done
20:46:00  variation: Mode650
20:46:00  JVM_OPTIONS:  -XX:-UseCompressedOops 

20:47:59  --------------------------------------------------
20:47:59  TEST: java/nio/Buffer/EqualsCompareTest.java

20:47:59  STDOUT:
20:47:59  [TestNG] Running:
20:47:59    java/nio/Buffer/EqualsCompareTest.java
20:47:59  
20:47:59  test EqualsCompareTest.testBuffers(java.nio.ByteBuffer HEAP): failure
20:47:59  java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, int, java.lang.invoke.MemberName)" because "<parameter1>" is null
20:47:59  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
20:47:59  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
20:47:59  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
20:47:59  	at EqualsCompareTest$BufferType.set(EqualsCompareTest.java:145)
20:47:59  	at EqualsCompareTest.lambda$testBuffers$1(EqualsCompareTest.java:529)
20:47:59  	at EqualsCompareTest$$Lambda$469/0x00000000e00c84c8.apply(Unknown Source)
20:47:59  	at EqualsCompareTest.testBufferType(EqualsCompareTest.java:672)
20:47:59  	at EqualsCompareTest.testBuffers(EqualsCompareTest.java:534)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
20:47:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:47:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
20:47:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
20:47:59  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
20:47:59  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
20:47:59  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
20:47:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
20:47:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
20:47:59  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
20:47:59  	at org.testng.TestRunner.run(TestRunner.java:623)
20:47:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
20:47:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
20:47:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
20:47:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
20:47:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:47:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:47:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
20:47:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
20:47:59  	at org.testng.TestNG.run(TestNG.java:1018)
20:47:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
20:47:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:47:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
20:47:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:47:59  	at java.base/java.lang.Thread.run(Thread.java:883)
20:47:59  test EqualsCompareTest.testBuffers(java.nio.ByteBuffer DIRECT): failure
20:47:59  java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, int, java.lang.invoke.MemberName)" because "<parameter1>" is null
20:47:59  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
20:47:59  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
20:47:59  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
20:47:59  	at EqualsCompareTest$BufferType.get(EqualsCompareTest.java:133)
20:47:59  	at EqualsCompareTest$BufferType.pairWiseEquals(EqualsCompareTest.java:186)
20:47:59  	at EqualsCompareTest.testBufferType(EqualsCompareTest.java:645)
20:47:59  	at EqualsCompareTest.testBuffers(EqualsCompareTest.java:534)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
20:47:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:47:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
20:47:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
20:47:59  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
20:47:59  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
20:47:59  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
20:47:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
20:47:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
20:47:59  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
20:47:59  	at org.testng.TestRunner.run(TestRunner.java:623)
20:47:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
20:47:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
20:47:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
20:47:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
20:47:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:47:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:47:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
20:47:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
20:47:59  	at org.testng.TestNG.run(TestNG.java:1018)
20:47:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
20:47:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:47:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
20:47:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:47:59  	at java.base/java.lang.Thread.run(Thread.java:883)

20:47:59  ===============================================
20:47:59  java/nio/Buffer/EqualsCompareTest.java
20:47:59  Total tests run: 35, Failures: 2, Skips: 0
20:47:59  ===============================================
20:47:59  
20:47:59  STDERR:
20:47:59  java.lang.Exception: failures: 2
20:47:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:47:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
20:47:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:47:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
20:47:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
20:47:59  	at java.base/java.lang.Thread.run(Thread.java:883)
20:47:59  
20:47:59  JavaTest Message: Test threw exception: java.lang.Exception
20:47:59  JavaTest Message: shutting down test
20:47:59  
20:47:59  
20:47:59  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
20:47:59  --------------------------------------------------
20:47:59  Test results: passed: 10; failed: 1
20:48:09  Report written to /home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Personal/jvmtest/openjdk/report/html/report.html
20:48:09  Results written to /home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_16293246664264/jdk11_tier1_buffer_1/work
20:48:09  Error: Some tests failed or other problems occurred.
20:48:09  
20:48:09  jdk11_tier1_buffer_1_FAILED
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&TARGET=jdk11_tier1_buffer_1)

**Comment by JasonFengJ9** [comment] 2021-08-30 13:00
Closing as per comment above.

**Closed by JasonFengJ9** 2021-08-30 13:00 UTC
Labels: comp:jit, test failure, project:MH
