### ISSUE TITLE
cmdLineTester_criu_nonPortableRestoreJDK11Up testThreadPark FAILED: expected park time 10000000000 ns

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16643] opened 2023-02-01 12:24 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/387 - [ub16x64j98](https://openj9-jenkins.osuosl.org/computer/ub16x64j98)
cmdLineTester_criu_nonPortableRestoreJDK11Up_0
```
TESTING:
*** Starting test suite: J9 Criu Command-Line Option Tests ***
Testing: Create CRIU checkpoint image and restore once - testThreadPark
Test start time: 2023/01/31 23:01:39 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xjit -XX:+CRIURestoreNonPortableMode  --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/openj9.internal.criu=ALL-UNNAMED" "org.openj9.criu.JDK11UpTimeoutAdjustmentTest testThreadPark" 1 1 false
Time spent starting: 161 milliseconds
Time spent executing: 24156 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] Start test name: testThreadPark
 [OUT] Before starting testThreadPark, current thread name: main, Tue Jan 31 23:01:41 EST 2023, System.currentTimeMillis(): 1675224101220, System.nanoTime(): 50763823946488282
 [OUT] testThreadPark() before park(), current thread name: Thread-0, Tue Jan 31 23:01:41 EST 2023, System.currentTimeMillis(): 1675224101697, System.nanoTime(): 50763824423775442
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Tue Jan 31 23:01:42 EST 2023, System.currentTimeMillis(): 1675224102707, System.nanoTime(): 50763825433534874
 [OUT] testThreadPark() after park(), current thread name: Thread-0, Tue Jan 31 23:01:52 EST 2023, System.currentTimeMillis(): 1675224112193, System.nanoTime(): 50763825475652552
 [OUT] FAILED: expected park time 10000000000 ns, but the actual elapsed time was: 1044861825ns with startNanoTime = 50763824430703145, and endNanoTime = 50763825475564970, CheckpointRestoreNanoTimeDelta: 9443883193
 [OUT] End testThreadPark, current thread name: main, Tue Jan 31 23:02:04 EST 2023, System.currentTimeMillis(): 1675224124192, System.nanoTime(): 50763837474455732
 [OUT] Removed testOutput file
 [OUT] finished script
 [ERR] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 40: 13597 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
>> Success condition was not found: [Output match: PASSED: expected park time]
>> Required condition was found: [Output match: Killed]
>> Required condition was found: [Output match: Start test name: testThreadPark]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: FAILED: expected sleep time]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by pshipton** [comment] 2023-02-01 12:25
@tajila fyi

**Comment by tajila** [comment] 2023-02-01 13:56
@JasonFengJ9 please take a look at this

**Comment by JasonFengJ9** [comment] 2023-02-01 14:02
Looking into it.

**Comment by JasonFengJ9** [comment] 2023-02-01 21:53
50x grinder all passed - https://openj9-jenkins.osuosl.org/job/Grinder/1959/
10x same machine grinder also passed - https://openj9-jenkins.osuosl.org/job/Grinder/1961/

Not able to reproduce it in a fyre image either.
Will see if this appears again in the nightly builds.

**Comment by pshipton** [comment] 2023-02-02 13:54
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/388 - [ub16x64j96](https://openj9-jenkins.osuosl.org/computer/ub16x64j96)
cmdLineTester_criu_nonPortableRestoreJDK11Up_0
```
[2023-02-02T06:09:04.667Z] TESTING:
[2023-02-02T06:09:05.387Z] *** Starting test suite: J9 Criu Command-Line Option Tests ***
[2023-02-02T06:09:05.387Z] Testing: Create CRIU checkpoint image and restore once - testThreadPark
[2023-02-02T06:09:06.063Z] Test start time: 2023/02/02 01:09:05 Eastern Standard Time
[2023-02-02T06:09:06.063Z] Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xjit -XX:+CRIURestoreNonPortableMode  --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/openj9.internal.criu=ALL-UNNAMED" "org.openj9.criu.JDK11UpTimeoutAdjustmentTest testThreadPark" 1 1 false
[2023-02-02T06:09:06.063Z] Time spent starting: 121 milliseconds
[2023-02-02T06:09:31.831Z] Time spent executing: 25761 milliseconds
[2023-02-02T06:09:31.831Z] Test result: FAILED
[2023-02-02T06:09:31.831Z] Output from test:
[2023-02-02T06:09:31.831Z]  [OUT] start running script
[2023-02-02T06:09:31.831Z]  [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
[2023-02-02T06:09:31.831Z]  [OUT] export LD_BIND_NOT=on
[2023-02-02T06:09:31.831Z]  [OUT] Start test name: testThreadPark
[2023-02-02T06:09:31.831Z]  [OUT] Before starting testThreadPark, current thread name: main, Thu Feb 02 01:09:06 EST 2023, System.currentTimeMillis(): 1675318146315, System.nanoTime(): 72020491765469029
[2023-02-02T06:09:31.831Z]  [OUT] testThreadPark() before park(), current thread name: Thread-0, Thu Feb 02 01:09:06 EST 2023, System.currentTimeMillis(): 1675318146670, System.nanoTime(): 72020492119999293
[2023-02-02T06:09:31.831Z]  [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Thu Feb 02 01:09:16 EST 2023, System.currentTimeMillis(): 1675318156559, System.nanoTime(): 72020502009101550
[2023-02-02T06:09:31.831Z]  [OUT] testThreadPark() after park(), current thread name: Thread-0, Thu Feb 02 01:09:19 EST 2023, System.currentTimeMillis(): 1675318159134, System.nanoTime(): 72020502043202062
[2023-02-02T06:09:31.831Z]  [OUT] FAILED: expected park time 10000000000 ns, but the actual elapsed time was: 9915898248ns with startNanoTime = 72020492127246733, and endNanoTime = 72020502043144981, CheckpointRestoreNanoTimeDelta: 2541115615
[2023-02-02T06:09:31.831Z]  [OUT] End testThreadPark, current thread name: main, Thu Feb 02 01:09:31 EST 2023, System.currentTimeMillis(): 1675318171128, System.nanoTime(): 72020514037252921
[2023-02-02T06:09:31.831Z]  [OUT] Removed testOutput file
[2023-02-02T06:09:31.831Z]  [OUT] finished script
[2023-02-02T06:09:31.831Z]  [ERR] /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 40: 28902 Killed                  $2 -XX:+EnableCRIUSupport $3 -cp "$1/criu.jar" $4 $5 $6 > testOutput 2>&1
[2023-02-02T06:09:31.831Z] >> Success condition was not found: [Output match: PASSED: expected park time]
[2023-02-02T06:09:31.831Z] >> Required condition was found: [Output match: Killed]
[2023-02-02T06:09:31.831Z] >> Required condition was found: [Output match: Start test name: testThreadPark]
[2023-02-02T06:09:31.831Z] >> Failure condition was not found: [Output match: CRIU is not enabled]
[2023-02-02T06:09:31.831Z] >> Failure condition was not found: [Output match: Operation not permitted]
[2023-02-02T06:09:31.831Z] >> Failure condition was not found: [Output match: FAILED: expected sleep time]
[2023-02-02T06:09:31.831Z] >> Success condition was not found: [Output match: Unable to create a thread:]
[2023-02-02T06:09:31.831Z] >> Success condition was not found: [Output match: Thread pid mismatch]
[2023-02-02T06:09:31.831Z] >> Success condition was not found: [Output match: do not match expected]
[2023-02-02T06:09:31.831Z] >> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by pshipton** [comment] 2023-04-26 23:06
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/523
cmdLineTester_criu_nonPortableRestoreJDK11Up_2 `-Xjit:count=0 -XX:+CRIURestoreNonPortableMode`
```
Testing: Create CRIU checkpoint image and restore once - testThreadPark
Test start time: 2023/04/26 04:56:09 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 -XX:+CRIURestoreNonPortableMode  -Xtrace:print={j9criu} --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/openj9.internal.criu=ALL-UNNAMED" "org.openj9.criu.JDK11UpTimeoutAdjustmentTest testThreadPark" 1 1 false
Time spent starting: 24 milliseconds
Time spent executing: 37155 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] Start test name: testThreadPark
 [OUT] Before starting testThreadPark, current thread name: main, Wed Apr 26 04:56:18 EDT 2023, System.currentTimeMillis(): 1682499378590, System.nanoTime(): 1682499378585091322
 [OUT] testThreadPark NO C/R before park(), current thread name: main, Wed Apr 26 04:56:22 EDT 2023, System.currentTimeMillis(): 1682499382439, System.nanoTime(): 1682499382434969902
 [OUT] testThreadPark NO C/R after park(), current thread name: main, Wed Apr 26 04:56:33 EDT 2023, System.currentTimeMillis(): 1682499393166, System.nanoTime(): 1682499393161389359
 [OUT] PASSED: expected park time 10000000000 ns, but the actual elapsed time was: 10002333379ns (~10002ms) with startNanoTime = 1682499382440909907ns, and endNanoTime = 1682499392443243286ns, CheckpointRestoreNanoTimeDelta: 0ns (~0ms)
 [OUT] testThreadPark before park(), current thread name: Thread-0, Wed Apr 26 04:56:34 EDT 2023, System.currentTimeMillis(): 1682499394244, System.nanoTime(): 1682499394239233770
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Apr 26 04:56:35 EDT 2023, System.currentTimeMillis(): 1682499395374, System.nanoTime(): 1682499395369814920
 [OUT] 08:56:35.391*0x69800          j9criu.9        > Java_org_eclipse_openj9_criu_CRIUSupport_checkpointJVMImpl
 [OUT] 08:56:35.445 0x69800          j9criu.13       - Before checkpoint, checkpointNanoTimeMonotonic = 1682499395440117500, checkpointNanoUTCTime = 1682499395445808232
 [OUT] 08:56:35.458 0x69800          j9criu.12       - Current syslogOptions: error,vital
 [OUT] 08:56:35.458 0x69800          j9criu.7        - Before checkpoint criu_dump(), j9time_nano_time() returns 1682499395453113672, j9time_current_time_nanos() returns 1682499395458804358
 [OUT] 08:56:35.473 0x69800          j9criu.15       - After checkpoint criu_dump(), j9time_nano_time() returns 1682499395468514716, j9time_current_time_nanos() returns 1682499395474205358
 [OUT] 08:56:35.473 0x69800          j9criu.10       < Java_org_eclipse_openj9_criu_CRIUSupport_checkpointJVMImpl
 [OUT] Exception in thread "main" org.eclipse.openj9.criu.SystemCheckpointException: Could not dump the JVM processes, err=-52
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVMImpl(Native Method)
 [OUT] 	at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.checkpointJVM(CRIUSupport.java:649)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:77)
 [OUT] 	at org.openj9.criu.CRIUTestUtils.checkPointJVM(CRIUTestUtils.java:65)
 [OUT] 	at org.openj9.criu.JDK11UpTimeoutAdjustmentTest.test(JDK11UpTimeoutAdjustmentTest.java:76)
 [OUT] 	at org.openj9.criu.JDK11UpTimeoutAdjustmentTest.main(JDK11UpTimeoutAdjustmentTest.java:39)
 [OUT] testThreadPark after park(), current thread name: Thread-0, Wed Apr 26 04:56:44 EDT 2023, System.currentTimeMillis(): 1682499404244, System.nanoTime(): 1682499404239951264
 [OUT] PASSED: expected park time 10000000000 ns, but the actual elapsed time was: 10000444722ns (~10000ms) with startNanoTime = 1682499394239397642ns, and endNanoTime = 1682499404239842364ns, CheckpointRestoreNanoTimeDelta: 0ns (~0ms)
 [OUT] Removed testOutput file
 [OUT] finished script
 [ERR] Error (criu/util.c:457): Can't read link of fd -404: No such file or directory
 [ERR] Error (criu/protobuf.c:75): Unexpected EOF on (null)
>> Success condition was found: [Output match: PASSED: expected park time]
>> Required condition was not found: [Output match: Killed]
>> Required condition was found: [Output match: Start test name: testThreadPark]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Failure condition was not found: [Output match: FAILED: expected sleep time]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Failure condition was not found: [Output match: Could not dump the JVM processes, err=-70]
```

**Comment by JasonFengJ9** [comment] 2023-12-08 17:46
No failure reproduced at https://github.com/eclipse-openj9/openj9/issues/16643#issuecomment-1834526283 grinder.
Closing.

**Closed by JasonFengJ9** 2023-12-08 17:46 UTC
Labels: comp:vm, test failure, criu
