### ISSUE TITLE
AIX UnsatisfiedLinkError: Failed to load library libfontmanager.so

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17759] opened 2023-07-10 14:18 UTC
OpenJDK jdk_imageio fails.

```
[2023-06-07T02:19:10.377Z] java.lang.UnsatisfiedLinkError: Failed to load library ("/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/libfontmanager.so") rtld: 0712-001 Symbol _ZNK2OT10postV2Tail6subsetEP19hb_subset_context_t was referenced
[2023-06-07T02:19:10.377Z]       from module /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/libfontmanager.so(), but a runtime definition
[2023-06-07T02:19:10.377Z]       of the symbol was not found.
[2023-06-07T02:19:10.377Z] 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
```

Seems like an issue with Harfbuzz 7.0.1 and xlc 16.1.0.11
We can try a later xlc version 16.1.0.14, which also means upgrading the runtime to a minimum of 16.1.0.10

**Comment by keithc-ca** [comment] 2023-07-11 14:08
This surprises me: I would have expected that only C linkage functions would be exported/imported across shared library boundaries.

**Comment by keithc-ca** [comment] 2023-07-11 14:51
I think the problem is in [`hb-subset.cc`](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/src/java.desktop/share/native/libharfbuzz/hb-subset.cc#L47). By not including `hb-ot-post-table-v2subset.hh` there, we have no implementation of `bool OT::postV2Tail::subset(hb_subset_context_t *)const`.

**Comment by jdekonin** [comment] 2023-07-18 21:24
Upgrading to 16.1.0.14 causes a failure in compile with libharfbuzz.

**Comment by keithc-ca** [comment] 2023-07-18 21:43
> Upgrading to 16.1.0.14 causes a failure in compile with libharfbuzz.

To clarify: It doesn't cause a failure, but if the necessary definitions are visible, compiles fail similarly as compared with the current compiler.

**Comment by pshipton** [comment] 2023-07-20 20:31
The workaround for jdk20 is in https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/71

**Comment by keithc-ca** [comment] 2023-08-02 11:57
This should be resolved by the pull requests referenced above.

**Closed by keithc-ca** 2023-08-02 11:57 UTC
Labels: comp:build, blocker, os:aix, comp:jclextensions
