### ISSUE TITLE
Foreign JDK17 failures

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13157] opened 2021-07-09 13:17 UTC
The following are failing in JDK17, we need to exclude these tests until the OJDKMH and the FFI changes are merged in JDK17

```
java/foreign/SafeFunctionAccessTest.java.SafeFunctionAccessTest
java/foreign/TestFree.java.TestFree
java/foreign/TestNULLAddress.java.TestNULLAddress
java/foreign/TestResourceScope.java.TestResourceScope
java/foreign/TestScopedOperations.java.TestScopedOperations
java/foreign/TestSegmentAllocators.java.TestSegmentAllocators
java/foreign/TestSymbolLookup.java.TestSymbolLookup
java/foreign/TestUpcallException.java.TestUpcallException
java/foreign/TestUpcallStructScope.java.TestUpcallStructScope
java/foreign/channels/TestAsyncSocketChannels.java.TestAsyncSocketChannels
java/foreign/channels/TestSocketChannels.java.TestSocketChannels
java/foreign/enablenativeaccess/TestDriver.java#panama_all_unnamed_module_native_access.TestDriver_panama_all_unnamed_module_native_access
java/foreign/enablenativeaccess/TestDriver.java#panama_comma_separated_enable.TestDriver_panama_comma_separated_enable
java/foreign/enablenativeaccess/TestDriver.java#panama_comma_separated_enable_invoke.TestDriver_panama_comma_separated_enable_invoke
java/foreign/enablenativeaccess/TestDriver.java#panama_comma_separated_enable_reflection.TestDriver_panama_comma_separated_enable_reflection
java/foreign/enablenativeaccess/TestDriver.java#panama_enable_native_access.TestDriver_panama_enable_native_access
java/foreign/enablenativeaccess/TestDriver.java#panama_enable_native_access_invoke.TestDriver_panama_enable_native_access_invoke
java/foreign/enablenativeaccess/TestDriver.java#panama_enable_native_access_reflection.TestDriver_panama_enable_native_access_reflection
java/foreign/enablenativeaccess/TestDriver.java#panama_no_all_module_path_blanket_native_access.TestDriver_panama_no_all_module_path_blanket_native_access
java/foreign/handles/Driver.java.Driver
java/foreign/malloc/TestMixedMallocFree.java.TestMixedMallocFree
java/foreign/stackwalk/TestAsyncStackWalk.java.TestAsyncStackWalk
java/foreign/virtual/TestVirtualCalls.java.TestVirtualCalls
java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
java/lang/ProcessBuilder/Basic.java#id1.Basic_id1
java/lang/System/SecurityManagerWarnings.java.SecurityManagerWarnings
java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
```

**Comment by tajila** [comment] 2021-07-09 13:18
@ChengJin01 Please take a look at this

FYI @fengxue-IS

**Comment by pshipton** [comment] 2021-07-09 13:48
Note the list is shorter now as we've already fixed some of these tests.

**Comment by pshipton** [comment] 2021-07-09 13:50
Not the latest and only one platform, but fyi https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/2/#showFailuresLink

java/lang/ProcessBuilder/Basic.java is fixed now, and I believe @JasonFengJ9 is looking at java/lang/System/SecurityManagerWarnings.java

**Comment by JasonFengJ9** [comment] 2021-07-09 13:58
> java/lang/System/SecurityManagerWarnings.java via #12760

Correct, I am going through test failures caused by a draft PR, ETA late of day or early next week.

**Comment by ChengJin01** [comment] 2021-07-13 21:18
I tried to double-check the foreign related test failures above with the build at https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_OpenJDK17/5/ with the following results:

[1] test suites with downcall: (not yet added to the code)
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/SafeFunctionAccessTest.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestFree.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestNULLAddress.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/malloc/TestMixedMallocFree.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/virtual/TestVirtualCalls.java

[2] test suites with downcall & upcall: (not yet added or implemented)
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestUpcallException.java (calling ThrowingUpcall)
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/ThrowingUpcall.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestUpcallStructScope.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/stackwalk/TestAsyncStackWalk.java (specific to Hotspot)

[3] passed test suites:
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestScopedOperations.java [PASSED]
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestSymbolLookup.java [PASSED]
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/enablenativeaccess/TestDriver.java [ALL PASSED]

[4] test suites with dumps
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestResourceScope.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestSegmentAllocators.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/channels/TestAsyncSocketChannels.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/channels/TestSocketChannels.java
```
22:52:17.164 0x1d5a00   j9jcl.347    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK17_x86-64_linux_OpenJDK17/openj9/runtime
/jcl/common/jdk_internal_misc_ScopedMemoryAccess.cpp:40: ((0 ))
```
The dumps occurred because the function related has not yet added to this build at
```
jboolean JNICALL
Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0(JNIEnv *env, jobject instance, jobject scope, jobject exception)
{
	Assert_JCL_unimplemented(); <-----
	return JNI_FALSE;
}
```
which has been implemented and added to the code later last week.

I tried with the latest build at https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_OpenJDK17/6/ but ended up with the failure with the `--enable-native-access` just added last week to the code by @JasonFengJ9.
```
STDERR:
JVMJ9VM007E Command-line option unrecognised: --enable-native-access=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
rerun:
```
So I will need to double-check the failing tests after the issue with the command line option `--enable-native-access` is fixed.

**Comment by JasonFengJ9** [comment] 2021-07-13 21:39
> I tried with the latest build at https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_OpenJDK17/6/ 

It was built with `OpenJ9` `5d3e13320967eece34881caa5804756a16bb9c35` which doesn't contain the commit `7f6a1ae4339f7f6e94924782288fea3897ec0475 JDK17 recognize --enable-native-access option`.
Please run with a JVM built with latest `master` branch.

**Comment by tajila** [comment] 2021-07-14 12:17
@ChengJin01 Can you please add excludes for [1] and [2] in jdk17 and head jdk repo

**Comment by llxia** [comment] 2021-07-14 17:44
We should update https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk17-openj9.txt for JDK17. There is no problem list for JDK18 yet.

**Comment by ChengJin01** [comment] 2021-07-14 17:47
Thanks @llxia  for confirming this,  I will need to verify my changes in the exclude list on JDK17 at https://github.com/ChengJin01/aqa-tests/commit/6fd7ad955f1bdd2c66076040ae358d7fe43bd377 to see whether it works good at this point.

**Comment by ChengJin01** [comment] 2021-07-14 19:13
PR at https://github.com/adoptium/aqa-tests/pull/2735 is created to exclude these JEP389 related tests.

**Comment by ChengJin01** [comment] 2021-07-14 19:27
I verified the follow failing tests (previously ending up with dump due to the lack of  implemented code in the build) locally with the latest changes in OpenJ9 (master branch)
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestResourceScope.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/TestSegmentAllocators.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/channels/TestAsyncSocketChannels.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9-staging/test/jdk/java/foreign/channels/TestSocketChannels.java
and all passed without any error at [jtr_tests_results.txt](https://github.com/eclipse-openj9/openj9/files/6818518/jtr_tests_results.txt)
which means the newly added native code in `/runtime/jcl/common/jdk_internal_misc_ScopedMemoryAccess.cpp` works good as expected.

**Closed** 2023-01-24 19:48 UTC
Labels: comp:vm, project:panama, perm excluded

**Comment by ChengJin01** [comment] 2023-01-24 20:37
`TestUpcallDeopt.java` (Hotspot specific test suite) is permanently excluded via https://github.com/adoptium/aqa-tests/pull/4273.
