### ISSUE TITLE
Program crashes at LastOptIndex 109 under JIT Hot Level

### ISSUE THREAD

**Issue by Qeryu** [eclipse-openj9/openj9#19080] opened 2024-03-06 11:07 UTC
Java -version output
--------------------

```bash
openjdk version "1.8.0_412-internal"
OpenJDK Runtime Environment (build 1.8.0_412-internal-xiezf_2024_03_06_10_45-b00)
Eclipse OpenJ9 VM (build master-8c1d42dad, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240306_000000 (JIT enabled, AOT enabled)
OpenJ9   - 8c1d42dad
OMR      - 8bea58e95
JCL      - 16aa7c2499 based on jdk8u412-b05)
```

Summary of problem
------------------

In the process of testing [Issue #19079](https://github.com/eclipse-openj9/openj9/issues/19079), we also discovered another issue. Since the LastOptIndex is different and the problem manifests in a different way, I opened a separate issue to report this problem. The testcase is as follows:

```java
class Test {
    int b;
    volatile byte c = 4;

    void k() {
        for (int j = 1; j < 40; j++) {
            int d = 4, e = b;
            synchronized (new Object()) {
                for (int a = 5; a < 100; a++) {
                    b >>= c;
                    int f = new g(e).h;
                    d += b;
                    for (int i = 0; i < 20000; i++) ;
                }
                b = d;
            }
        }
        System.out.println(b);
    }

    public static void main(String[] m) {
        Test o = new Test();
        for (int i = 0; i < 15; i++)
            o.k();
    }
}

class g {
    int h;

    g(int h) {
        this.h = h;
    }
}
```

When I run the following command, it causes openj9 to dump some information.

```bash
$ openj9/.../java '-Xjit:{Test.l(*)*}(optLevel=hot,lastOptIndex=109,optDetails,log=jit.log)' Test
```

The related jitdump, javacore files, and the output of the command line after running are as follows:

[jitdump.20240306.190049.870019.0004.dmp](https://github.com/eclipse-openj9/openj9/files/14508857/jitdump.20240306.190049.870019.0004.dmp)

[console_output.log](https://github.com/eclipse-openj9/openj9/files/14508855/console_output.log)

[javacore.20240306.190049.870019.0002.txt](https://github.com/eclipse-openj9/openj9/files/14508856/javacore.20240306.190049.870019.0002.txt)

**Comment by hzongaro** [comment] 2024-03-08 15:25
Extracted from [console_output.log](https://github.com/eclipse-openj9/openj9/files/14508855/console_output.log):

```
Unhandled exception
Type=Segmentation error vmState=0x0005ff04
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F212443BC70 Handler2=00007F212463CB20 InaccessibleAddress=0000000000000000
...
Method_being_compiled=Test.l()V
Target=2_90_20240306_000000 (Linux 6.5.0-21-generic)
CPU=amd64 (96 logical CPUs) (0x3ed7283000 RAM)
----------- Stack Backtrace -----------
459
9
459
9
_ZN3OMR3X8613TreeEvaluator11performCallEPN2TR4NodeEbbPNS2_13CodeGeneratorE+0x70 (0x00007F211F17E850 [libj9jit29.so+0x97e850])
_ZN3OMR13CodeGenerator8evaluateEPN2TR4NodeE+0x48 (0x00007F211ED57138 [libj9jit29.so+0x557138])
_ZN3OMR3X8613TreeEvaluator16treetopEvaluatorEPN2TR4NodeEPNS2_13CodeGeneratorE+0x21 (0x00007F211F17EF21 [libj9jit29.so+0x97ef21])
_ZN3OMR13CodeGenerator8evaluateEPN2TR4NodeE+0x48 (0x00007F211ED57138 [libj9jit29.so+0x557138])
_ZN2J913CodeGenerator22doInstructionSelectionEv+0xd97 (0x00007F211E939BE7 [libj9jit29.so+0x139be7])
```

and [jitdump](https://github.com/eclipse-openj9/openj9/files/14508857/jitdump.20240306.190049.870019.0004.dmp):

```
<optimization id=109 name=preEscapeAnalysis method=Test.l()V>
Performing 109: preEscapeAnalysis
              (Invalidating use/def info)
              (Invalidating value number info)
          Adding fake prepare n1050n to OSR induction block_25
          Adding fake prepare n1053n to OSR induction block_27
          Adding fake prepare n1056n to OSR induction block_29
```

This is a duplicate of issue #18385.  Please accept my apologies for the inconvenience this bug can cause in trying to narrow down which optimization is responsible for a test failure.

**Comment by hzongaro** [comment] 2024-03-08 15:26
Duplicates #18385

**Comment by hzongaro** [comment] 2024-03-08 15:26
Duplicates #18385

**Comment by hzongaro** [comment] 2024-03-08 15:27
Duplicate of #18385

**Closed by hzongaro** 2024-03-08 15:26 UTC
Labels: comp:jit, userRaised
