### ISSUE TITLE
Segmentation fault when JITServer can't bind server address

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse-openj9/openj9#13114] opened 2021-07-05 22:30 UTC
When one instance of JITServer already exists, and I attempt to start another JITServer at the same address and port (i.e. not specifying any options on my local machine), I frequently see segfaults right before the new server terminates.

Output:
```
>  $JAVA11_BIN/jitserver -Xjit:verbose="{JITServer}"
JITServer is currently a technology preview. Its use is not yet supported.
#JITServer: JITServer version: 1.26.0
#JITServer: JITServer Server Mode. Port: 38400. Connection Timeout 30000ms
#JITServer: Started JITServer listener thread: 000000000022B700
can't bind server address: Address already in use
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F170025DC90 Handler2=00007F16FF8141D0 InaccessibleAddress=00007F16F3CB38B0
RDI=00007F16FC772050 RSI=00007F1631F3D7D0 RAX=0000000000002225 RBX=00007F1631F3D7D1
RCX=00007F16F3CAB01C RDX=0000000000002225 R8=0000000000000000 R9=000000002F52AD54
R10=00007F1631F3D80E R11=0000000000000000 R12=00007F1631F3D7D0 R13=0000000000007D5A
R14=00007F1631F3E8C8 R15=000055855F88EBD0
```

It's unclear when this bug was first introduced. Attempts to reproduce it by running the server in gdb did not work. And since the crash happens so early into the JVM lifetime, there are no cores left for debugging.

**Comment by dmitry-ten** [comment] 2021-07-05 22:31
@mpirvu fyi.

**Comment by mpirvu** [comment] 2021-07-06 03:08
I cannot reproduce this issue with Java8 nor with Java11

**Comment by dmitry-ten** [comment] 2021-07-12 18:46
I can only reproduce this on WSL 2, with JDK11. 
I suppose since we don't officially support WSL, we can ignore this crash.

**Comment by mpirvu** [comment] 2021-07-12 21:31
Closing cased on the above remark

**Closed by mpirvu** 2021-07-12 21:31 UTC
Labels: comp:jitserver
