### ISSUE TITLE
SC_Softmx_Increase_0 net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#6840] opened 2019-08-26 01:41 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_x86-64_linux_xl_Nightly/19/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
03:19:01.467 - Starting thread. Suite=0 thread=0
03:19:01.470 - Starting thread. Suite=0 thread=1
03:19:01.471 - Starting thread. Suite=0 thread=2
03:19:09.254 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
03:19:09.263 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/mix/sharedclasses-mix.xml
03:19:09.264 - suite.isCreateDump() : false
03:19:09.266 - Test failed
  Failure num.  = 1
  Test number   = 88
  Test details  = 'JUnit[net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest]'
  Suite number  = 0
  Thread number = 2
>>> Captured test output >>>
testStarted : testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at junit.framework.Assert.assertEquals(Assert.java:234)
        at junit.framework.TestCase.assertEquals(TestCase.java:401)
        at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
        at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:831)

testFinished: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testStarted : testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to find intial provider 'memory0'
junit.framework.AssertionFailedError: Unable to find intial provider 'memory0'
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testFileSystemIsRegistered(FileSystemsTest.java:78)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
        at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:831)
testFinished: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)

JUnit Test Results for: net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest
  Ran    : 2
  Passed : 0
  Failed : 2
  Ignored: 0
  Result : FAILED
```

**Comment by adam-thorpe** [comment] 2019-08-28 09:26
Worth pointing out this is consistent across all versions and platforms using openj9

**Comment by pshipton** [comment] 2019-09-05 12:36
@Mesbah-Alam 
Not sure if this is the right issue, but AIX is failing SharedClassesAPI_0 testing, related to
```
STF 01:51:45.468 - Overall result: PASSED
/bin/sh[11]: umask: 0403-010 A specified flag is not valid for this command.
```

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/130/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly/130

**Comment by Mesbah-Alam** [comment] 2019-09-05 15:02
The test passes, but it seems one of the umask command is failing, 

```
`umask: 0403-010 A specified flag is not valid for this command.`:
```

Logged onto an internal AIX machine and tested out the umask commands used in the test manually. It seems to be working fine, couldn't reproduce the error  

```
-bash-4.4$ export original_umask_val=`umask`
-bash-4.4$ umask 0002
-bash-4.4$ umask -p
umask 0002
-bash-4.4$ umask $original_umask_val
-bash-4.4$ umask -p
umask 0022
```

The only umask command in which a umask flag is used in the test is `umask -p` - to print out the umask value after it has been set / unset. However, I am not 100% sure if `umask -p` is the command which is yielding the above error message ("umask: 0403-010 A specified flag is not valid for this command"). 

I do not have access to the eclipse.openj9 jenkins to manually test it out. 

One way forward is to use `umask` instead of `umask -p` in the command line - as both would print the current umask value. 

@hangshao0

**Comment by pshipton** [comment] 2019-09-05 17:32
On AIX 7.1
```
umask -p
umask: Improper mask.
```

**Comment by Mesbah-Alam** [comment] 2019-09-05 17:35
@pshipton - thanks for finding out. I'll have a PR where `-p` is removed.

**Comment by adam-thorpe** [comment] 2019-09-06 12:43
Seems to be stable: https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk13_j9_extended.system_x86-64_linux/45/

**Comment by Mesbah-Alam** [comment] 2019-09-06 13:38
Test passing on the failing machine after https://github.com/AdoptOpenJDK/openjdk-tests/pull/1329 is merged:  https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/483/console

**Closed** 2022-07-14 21:12 UTC
Labels: test failure
