### ISSUE TITLE
JDK19 serviceability_jvmti_j9_1_FAILED serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16246] opened 2022-11-01 22:24 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_linux/23/)(`rhel9x86-rt3-1`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-71f768a8b, JRE 19 Linux amd64-64-Bit Compressed References 20221018_68 (JIT enabled, AOT enabled)
OpenJ9   - 71f768a8b
OMR      - 556374a61
JCL      - 9d79dbc153 based on jdk-19.0.1+10)
```
[Rerun in Grinder]([Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F68%2Fibm-semeru-open-debugimage_x64_linux_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F68%2Fibm-semeru-open-jdk_x64_linux_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F68%2Fibm-semeru-open-jre_x64_linux_JDK19U_2022-10-30-16-47.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-x64-openj9%2F68%2Fibm-semeru-open-testimage_x64_linux_JDK19U_2022-10-30-16-47.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None)) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-10-30T17:14:26.203Z] variation: Mode650
[2022-10-30T17:14:26.203Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-10-30T17:16:22.045Z] TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

[2022-10-30T17:16:22.047Z] STDERR:
[2022-10-30T17:16:22.047Z] Unhandled exception
[2022-10-30T17:16:22.047Z] Type=Segmentation error vmState=0x00000000
[2022-10-30T17:16:22.047Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2022-10-30T17:16:22.047Z] Handler1=00007F8261102210 Handler2=00007F826105C990 InaccessibleAddress=0000000000000000
[2022-10-30T17:16:22.047Z] RDI=00007F825C0B21E8 RSI=00007F81C00393D0 RAX=0000000000000000 RBX=00007F825C0B21E8
[2022-10-30T17:16:22.047Z] RCX=0000000000000000 RDX=00007F8221868AD8 R8=C0FE004000000000 R9=0000000000000058
[2022-10-30T17:16:22.047Z] R10=00007F81B400A370 R11=00007F81B4000020 R12=0000000000000000 R13=00007F81C0039500
[2022-10-30T17:16:22.047Z] R14=00007F8221868AD8 R15=00007F81C00393D0
[2022-10-30T17:16:22.047Z] RIP=0000000000000000 GS=0000 FS=0000 RSP=00007F8221868A98
[2022-10-30T17:16:22.047Z] EFlags=0000000000010246 CS=0033 RBP=00007F8221868B10 ERR=0000000000000014
[2022-10-30T17:16:22.047Z] TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
[2022-10-30T17:16:22.047Z] xmm0 ffffffffffffff00 (f: 4294967040.000000, d: -nan)
[2022-10-30T17:16:22.047Z] xmm1 4747474747474747 (f: 1195853696.000000, d: 2.417371e+35)
[2022-10-30T17:16:22.047Z] xmm2 6565656565656565 (f: 1701143936.000000, d: 2.774480e+180)
[2022-10-30T17:16:22.047Z] xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm4 00ff000000000000 (f: 0.000000, d: 7.063274e-304)
[2022-10-30T17:16:22.047Z] xmm5 ffffffffffffff00 (f: 4294967040.000000, d: -nan)
[2022-10-30T17:16:22.047Z] xmm6 00ff000000000000 (f: 0.000000, d: 7.063274e-304)
[2022-10-30T17:16:22.047Z] xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm8 2f6567616d692d74 (f: 1835609472.000000, d: 2.256434e-80)
[2022-10-30T17:16:22.047Z] xmm9 ffffffffffffffff (f: 4294967296.000000, d: -nan)
[2022-10-30T17:16:22.047Z] xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:16:22.047Z] Target=2_90_20221018_68 (Linux 5.14.0-70.26.1.el9_0.x86_64)
[2022-10-30T17:16:22.047Z] CPU=amd64 (4 logical CPUs) (0x1e04a1000 RAM)
[2022-10-30T17:16:22.047Z] ----------- Stack Backtrace -----------
[2022-10-30T17:16:22.047Z] protectedBacktrace+0x12 (0x00007F8261058FD2 [libj9prt29.so+0x25fd2])
[2022-10-30T17:16:22.047Z] omrsig_protect+0x2b1 (0x00007F826105D6C1 [libj9prt29.so+0x2a6c1])
[2022-10-30T17:16:22.047Z] omrintrospect_backtrace_thread_raw+0xbb (0x00007F82610594BB [libj9prt29.so+0x264bb])
[2022-10-30T17:16:22.047Z] omrsig_protect+0x2b1 (0x00007F826105D6C1 [libj9prt29.so+0x2a6c1])
[2022-10-30T17:16:22.047Z] omrintrospect_backtrace_thread+0x7a (0x00007F8261058E4A [libj9prt29.so+0x25e4a])
[2022-10-30T17:16:22.047Z] generateDiagnosticFiles+0x8b (0x00007F8261101D3B [libj9vm29.so+0x3dd3b])
[2022-10-30T17:16:22.047Z] omrsig_protect+0x2b1 (0x00007F826105D6C1 [libj9prt29.so+0x2a6c1])
[2022-10-30T17:16:22.047Z] vmSignalHandler+0x17f (0x00007F8261101F9F [libj9vm29.so+0x3df9f])
[2022-10-30T17:16:22.047Z] mainSynchSignalHandler+0x225 (0x00007F826105CBB5 [libj9prt29.so+0x29bb5])
[2022-10-30T17:16:22.047Z]  (0x00007F826172EDB0 [libc.so.6+0x59db0])
[2022-10-30T17:16:22.047Z] ---------------------------------------
[2022-10-30T17:16:22.047Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2022/10/30 10:16:16 - please wait.

[2022-10-30T17:16:22.048Z] TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
[2022-10-30T17:16:22.048Z] --------------------------------------------------
[2022-10-30T17:18:47.788Z] Test results: passed: 112; failed: 1
[2022-10-30T17:18:48.203Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2022-10-30T17:18:48.203Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16671496798297/serviceability_jvmti_j9_1/work
[2022-10-30T17:18:48.203Z] Error: Some tests failed or other problems occurred.
[2022-10-30T17:18:48.203Z] 
[2022-10-30T17:18:48.203Z] serviceability_jvmti_j9_1_FAILED
```
Note: this occurred at a RHEL9 machine.

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29196/)

FYI @babsingh @fengxue-IS

**Comment by JasonFengJ9** [comment] 2022-11-01 22:38
Also seen on [JDK19 ppc64le_linux internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_ppc64le_linux/22/)(`sles12le-rt1-9`)
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-71f768a8b, JRE 19 Linux ppc64le-64-Bit Compressed References 20221018_68 (JIT enabled, AOT enabled)
OpenJ9   - 71f768a8b
OMR      - 556374a61
JCL      - 9d79dbc153 based on jdk-19.0.1+10)
```

```
[2022-10-30T17:44:40.548Z] variation: Mode150
[2022-10-30T17:44:40.548Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-10-30T17:47:36.749Z] TEST: serviceability/jvmti/stress/StackTrace/NotSuspended/GetStackTraceNotSuspendedStressTest.java

[2022-10-30T17:47:36.749Z] STDERR:
[2022-10-30T17:47:36.749Z] Unhandled exception
[2022-10-30T17:47:36.749Z] Type=Segmentation error vmState=0x00000000
[2022-10-30T17:47:36.749Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2022-10-30T17:47:36.749Z] Handler1=00007FFF8E01FCE0 Handler2=00007FFF8DF48980
[2022-10-30T17:47:36.749Z] R0=00007FFF6C164DCC R1=00007FFF4F48BF60 R2=00007FFF6C187F00 R3=00007FFF880BD5B8
[2022-10-30T17:47:36.749Z] R4=000000000028C910 R5=00007FFF4F48BFD0 R6=0000000000000000 R7=0000000000000000
[2022-10-30T17:47:36.750Z] R8=00007FFF0000A1A0 R9=0000000000000000 R10=0000000000000000 R11=0000000000000000
[2022-10-30T17:47:36.750Z] R12=0000000000000000 R13=00007FFF4F4968F0 R14=0000000000275AD0 R15=00007FFF00003268
[2022-10-30T17:47:36.750Z] R16=00007FFF6C166F78 R17=000000000028C910 R18=00007FFF4F48BFC8 R19=00007FFF4F48BFC0
[2022-10-30T17:47:36.750Z] R20=00007FFF4F48BFD8 R21=00007FFF4F48BFC4 R22=00007FFF8E971800 R23=00007FFF4F48BFD0
[2022-10-30T17:47:36.750Z] R24=0000000000000000 R25=00007FFF6C180018 R26=000000000028CA00 R27=00007FFF000038F8
[2022-10-30T17:47:36.750Z] R28=00007FFF880BD5B8 R29=0000000000000000 R30=0000000000000000 R31=00007FFF000038F8
[2022-10-30T17:47:36.750Z] NIP=0000000000000000 MSR=800000014280F033 ORIG_GPR3=00000000000087D0 CTR=0000000000000000
[2022-10-30T17:47:36.750Z] LINK=00007FFF6C164CBC XER=0000000020000000 CCR=0000000024444442 SOFTE=0000000000000001
[2022-10-30T17:47:36.750Z] TRAP=0000000000000400 DAR=0000000000000000 dsisr=0000000040000000 RESULT=0000000000000000
[2022-10-30T17:47:36.750Z] FPR0 00007fff8e6e0fb0 (f: 2389577728.000000, d: 6.953262e-310)
[2022-10-30T17:47:36.750Z] FPR1 4055526a00000000 (f: 0.000000, d: 8.528772e+01)
[2022-10-30T17:47:36.750Z] FPR2 3fc2f112e0000000 (f: 3758096384.000000, d: 1.479820e-01)
[2022-10-30T17:47:36.750Z] FPR3 3fc39a09e0000000 (f: 3758096384.000000, d: 1.531384e-01)
[2022-10-30T17:47:36.750Z] FPR4 3fd24924a0000000 (f: 2684354560.000000, d: 2.857143e-01)
[2022-10-30T17:47:36.750Z] FPR5 3fd99999a0000000 (f: 2684354560.000000, d: 4.000000e-01)
[2022-10-30T17:47:36.750Z] FPR6 7373616c63206465 (f: 1663067264.000000, d: 1.355073e+248)
[2022-10-30T17:47:36.750Z] FPR7 7a696c616974696e (f: 1769236864.000000, d: 4.614864e+281)
[2022-10-30T17:47:36.750Z] FPR8 6e553d3931304d56 (f: 825249088.000000, d: 3.070959e+223)
[2022-10-30T17:47:36.750Z] FPR9 6f72726520656c62 (f: 543517824.000000, d: 6.991962e+228)
[2022-10-30T17:47:36.750Z] FPR10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR13 3feec709e0000000 (f: 3758096384.000000, d: 9.617967e-01)
[2022-10-30T17:47:36.750Z] FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:36.750Z] Target=2_90_20221018_68 (Linux 4.12.14-122.136-default)
[2022-10-30T17:47:36.750Z] CPU=ppc64le (4 logical CPUs) (0x1f1360000 RAM)
[2022-10-30T17:47:36.750Z] ----------- Stack Backtrace -----------
[2022-10-30T17:47:36.750Z]  (0x0000000000000000 [<unknown>+0x0])
[2022-10-30T17:47:36.750Z] _ZL9agentProcP9_jvmtiEnvP7JNIEnv_Pv+0x2dc (0x00007FFF6C164DCC [libGetStackTraceNotSuspendedStress.so+0x4dcc])
[2022-10-30T17:47:36.750Z] agent_thread_wrapper+0x64 (0x00007FFF6C162A04 [libGetStackTraceNotSuspendedStress.so+0x2a04])
[2022-10-30T17:47:36.750Z] wrappedAgentThreadStart+0x104 (0x00007FFF8C43B264 [libj9jvmti29.so+0x3b264])
[2022-10-30T17:47:36.750Z] omrsig_protect+0x3f4 (0x00007FFF8DF49E54 [libj9prt29.so+0x39e54])
[2022-10-30T17:47:36.750Z] agentThreadStart+0x88 (0x00007FFF8C43AE48 [libj9jvmti29.so+0x3ae48])
[2022-10-30T17:47:36.750Z] thread_wrapper+0x190 (0x00007FFF8DEDCBC0 [libj9thr29.so+0xcbc0])
[2022-10-30T17:47:36.750Z] start_thread+0x108 (0x00007FFF8E9BAA68 [libpthread.so.0+0xaa68])
[2022-10-30T17:47:36.750Z] clone+0xe4 (0x00007FFF8E8C7394 [libc.so.6+0x117394])
[2022-10-30T17:47:36.750Z] ---------------------------------------
[2022-10-30T17:47:36.750Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2022/10/30 10:47:32 - please wait.

[2022-10-30T17:47:37.229Z] TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

[2022-10-30T17:47:37.230Z] STDERR:
[2022-10-30T17:47:37.230Z] Unhandled exception
[2022-10-30T17:47:37.230Z] Type=Segmentation error vmState=0x00000000
[2022-10-30T17:47:37.230Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2022-10-30T17:47:37.230Z] Handler1=00007FFF9579FCE0 Handler2=00007FFF956C8980
[2022-10-30T17:47:37.230Z] R0=00007FFF57906674 R1=00007FFF54C0BF80 R2=00007FFF57927F00 R3=00007FFF900BD528
[2022-10-30T17:47:37.230Z] R4=000000000028C930 R5=00007FFF54C0BFF8 R6=0000000000000000 R7=0000000000000000
[2022-10-30T17:47:37.230Z] R8=00007FFF0800A1A0 R9=0000000000000000 R10=0000000000000000 R11=0000000000000000
[2022-10-30T17:47:37.230Z] R12=0000000000000000 R13=00007FFF54C168F0 R14=0000000000275AB0 R15=00007FFF54C0F260
[2022-10-30T17:47:37.230Z] R16=0000000000080000 R17=00000000FFE4C518 R18=0000000000000000 R19=00007FFF180178E8
[2022-10-30T17:47:37.230Z] R20=00007FFF9565CA30 R21=00007FFF54C0BFF0 R22=00007FFF54C0BFEC R23=0000000000000000
[2022-10-30T17:47:37.230Z] R24=00007FFF960F1800 R25=00007FFF54C0BFF8 R26=0000000000000000 R27=00007FFF57920018
[2022-10-30T17:47:37.230Z] R28=000000000028CA00 R29=0000000000000000 R30=00007FFF900BD528 R31=000000000028C930
[2022-10-30T17:47:37.230Z] NIP=0000000000000000 MSR=800000014280F033 ORIG_GPR3=00000000000087D0 CTR=0000000000000000
[2022-10-30T17:47:37.230Z] LINK=00007FFF57906460 XER=0000000020000000 CCR=0000000024448442 SOFTE=0000000000000001
[2022-10-30T17:47:37.230Z] TRAP=0000000000000400 DAR=0000000000000000 dsisr=0000000040000000 RESULT=0000000000000000
[2022-10-30T17:47:37.230Z] FPR0 00007fff95e60fb0 (f: 2514882560.000000, d: 6.953268e-310)
[2022-10-30T17:47:37.230Z] FPR1 40552675e0000000 (f: 3758096384.000000, d: 8.460094e+01)
[2022-10-30T17:47:37.230Z] FPR2 3fc2f112e0000000 (f: 3758096384.000000, d: 1.479820e-01)
[2022-10-30T17:47:37.230Z] FPR3 3fc39a09e0000000 (f: 3758096384.000000, d: 1.531384e-01)
[2022-10-30T17:47:37.230Z] FPR4 3fd24924a0000000 (f: 2684354560.000000, d: 2.857143e-01)
[2022-10-30T17:47:37.230Z] FPR5 3fd99999a0000000 (f: 2684354560.000000, d: 4.000000e-01)
[2022-10-30T17:47:37.230Z] FPR6 7373616c63206465 (f: 1663067264.000000, d: 1.355073e+248)
[2022-10-30T17:47:37.230Z] FPR7 7a696c616974696e (f: 1769236864.000000, d: 4.614864e+281)
[2022-10-30T17:47:37.230Z] FPR8 6e553d3931304d56 (f: 825249088.000000, d: 3.070959e+223)
[2022-10-30T17:47:37.230Z] FPR9 6f72726520656c62 (f: 543517824.000000, d: 6.991962e+228)
[2022-10-30T17:47:37.230Z] FPR10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR13 000000000026f900 (f: 2554112.000000, d: 1.261899e-317)
[2022-10-30T17:47:37.230Z] FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2022-10-30T17:47:37.230Z] Target=2_90_20221018_68 (Linux 4.12.14-122.136-default)
[2022-10-30T17:47:37.230Z] CPU=ppc64le (4 logical CPUs) (0x1f1360000 RAM)
[2022-10-30T17:47:37.230Z] ----------- Stack Backtrace -----------
[2022-10-30T17:47:37.230Z]  (0x0000000000000000 [<unknown>+0x0])
[2022-10-30T17:47:37.230Z] _ZL9agentProcP9_jvmtiEnvP7JNIEnv_Pv+0x3a4 (0x00007FFF57906674 [libGetStackTraceSuspendedStress.so+0x6674])
[2022-10-30T17:47:37.230Z] agent_thread_wrapper+0x64 (0x00007FFF57902E44 [libGetStackTraceSuspendedStress.so+0x2e44])
[2022-10-30T17:47:37.230Z] wrappedAgentThreadStart+0x104 (0x00007FFF8FB3B264 [libj9jvmti29.so+0x3b264])
[2022-10-30T17:47:37.230Z] omrsig_protect+0x3f4 (0x00007FFF956C9E54 [libj9prt29.so+0x39e54])
[2022-10-30T17:47:37.230Z] agentThreadStart+0x88 (0x00007FFF8FB3AE48 [libj9jvmti29.so+0x3ae48])
[2022-10-30T17:47:37.230Z] thread_wrapper+0x190 (0x00007FFF9565CBC0 [libj9thr29.so+0xcbc0])
[2022-10-30T17:47:37.230Z] start_thread+0x108 (0x00007FFF9613AA68 [libpthread.so.0+0xaa68])
[2022-10-30T17:47:37.230Z] clone+0xe4 (0x00007FFF96047394 [libc.so.6+0x117394])
[2022-10-30T17:47:37.230Z] ---------------------------------------
[2022-10-30T17:47:37.230Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2022/10/30 10:47:35 - please wait.

[2022-10-30T17:47:37.231Z] TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
[2022-10-30T17:47:37.231Z] --------------------------------------------------
[2022-10-30T17:50:19.157Z] Test results: passed: 111; failed: 2
[2022-10-30T17:50:36.517Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_ppc64le_linux/jvmtest/openjdk/report/html/report.html
[2022-10-30T17:50:36.517Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16671515623681/serviceability_jvmti_j9_0/work
[2022-10-30T17:50:36.517Z] Error: Some tests failed or other problems occurred.
[2022-10-30T17:50:36.517Z] 
[2022-10-30T17:50:36.517Z] serviceability_jvmti_j9_0_FAILED
```

**Comment by babsingh** [comment] 2022-11-01 23:21
Closing, duplicate of https://github.com/eclipse-openj9/openj9/issues/16203. This test requires `JVMTI GetVirtualThread` which is part of the JVMTI extension API and not covered by the [JVMTI specification](https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html). So, we do not need to support this test for the [Java 19](https://github.com/eclipse-openj9/openj9/milestone/35) release.

**Closed by babsingh** 2022-11-01 23:21 UTC
Labels: comp:vm, test failure
