### ISSUE TITLE
[JDK18] j.l.RuntimeException: InvocationTargetException was thrown not due to error while initialization!

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14080] opened 2021-12-06 18:40 UTC
### OpenJDK Tests

```
TEST: java/lang/reflect/classInitialization/ExceptionInClassInitialization.java
```

### Error
```
[2021-11-17T18:49:53.414Z] java.lang.RuntimeException: InvocationTargetException was thrown not due to error while initialization!
[2021-11-17T18:49:53.414Z]      at ExceptionInClassInitialization.testFieldAccess(ExceptionInClassInitialization.java:72)
[2021-11-17T18:49:53.414Z]      at ExceptionInClassInitialization.main(ExceptionInClassInitialization.java:38)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:49:53.414Z]      at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.Thread.run(Thread.java:884)
[2021-11-17T18:49:53.414Z] Caused by: java.lang.reflect.InvocationTargetException
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:49:53.414Z]      at ExceptionInClassInitialization.testFieldAccess(ExceptionInClassInitialization.java:60)
[2021-11-17T18:49:53.414Z]      ... 7 more
[2021-11-17T18:49:53.414Z] Caused by: java.lang.NoClassDefFoundError: Test (initialization failure)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:134)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:178)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1169)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1148)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Field.set(Field.java:818)
[2021-11-17T18:49:53.414Z]      at Initializer.fieldAccess(Initializer.java:27)
[2021-11-17T18:49:53.414Z]      ... 12 more
[2021-11-17T18:49:53.414Z] Caused by: MyException
[2021-11-17T18:49:53.414Z]      at SuperTest.<clinit>(Test.java:29)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:49:53.414Z]      at Initializer.execMethod(Initializer.java:32)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:49:53.414Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:49:53.414Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:49:53.415Z]      at ExceptionInClassInitialization.testExecMethod(ExceptionInClassInitialization.java:43)
[2021-11-17T18:49:53.415Z]      at ExceptionInClassInitialization.main(ExceptionInClassInitialization.java:37)
[2021-11-17T18:49:53.415Z]      ... 6 more
```

Related: #13946

**Comment by DanHeidinga** [comment] 2022-01-18 15:25
Is there a spec reference for this change?

**Comment by babsingh** [comment] 2022-01-18 16:08
Test [classInitialization/ExExceptionInClassInitialization](https://github.com/ibmruntimes/openj9-openjdk-jdk18/blob/openj9/test/jdk/java/lang/reflect/classInitialization/ExceptionInClassInitialization.java) was added to verify JEP416 support which re-implements core reflection with MethodHandles. If the test passes by disabling JEP416, then there may be no spec change. Instead, we may be missing JEP416 support since the core reflection API should work the same with and without JEP416.

@EricYangIBM Can you disable JEP416 and verify if the test passes? Commit to disable JEP416: https://github.com/eclipse-openj9/openj9/pull/13890/commits/3c9e60200277f4428b3af4746050cc7026ce8def.

**Comment by babsingh** [comment] 2022-01-18 16:20
**Another perspective:** This issue may be identical to https://bugs.openjdk.java.net/browse/JDK-8048190 (**NoClassDefFoundError omits original ExceptionInInitializerError**). 45 older comments are hidden, which should be expanded to read more about the issue.

**Comment by EricYangIBM** [comment] 2022-01-18 16:26
> Can you disable JEP416 and verify if the test passes?

The test still fails

**Comment by EricYangIBM** [comment] 2022-01-18 17:40
https://bugs.openjdk.java.net/browse/JDK-8048190 looks like it is identical to this issue. The solution to it sets the cause of the `NoClassDefFoundError` to be the original `ExceptionInInitializerError`, but I don't think it is based on any spec. Not sure why this test was created as part of JEP416 but this [other test](https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/runtime/ClassInitErrors/InitExceptionUnloadTest.java) was created specifically for the solution.

**Comment by EricYangIBM** [comment] 2022-01-18 19:30
I looked at the language spec 12.4.2: https://cr.openjdk.java.net/~iris/se/18/latestSpec/java-se-18-jls-pr-diffs.pdf#page=448&zoom=100,96,678
Step 5 specifies to throw `NoClassDefFoundError` but nothing about its cause.

If this test isn't based on spec changes then is it necessary? It seems like this behaviour was only implemented by OpenJDK as an enhancement

**Comment by pshipton** [comment] 2022-01-18 19:40
It's good to match the behaviour of the reference so that user's don't experience different behaviour, that might cause problems, when moving to OpenJ9.

**Closed** 2022-01-27 17:56 UTC
Labels: comp:vm, test excluded, jdk18
