### ISSUE TITLE
JDK16 java/foreign/TestCleaner.java j9jcl.347    *   ** ASSERTION FAILED ** at common/jdk_internal_misc_ScopedMemoryAccess.cpp:40: ((0 ))

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#11360] opened 2020-12-03 22:29 UTC
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/286`
```
22:14:14  openjdk version "16-internal" 2021-03-16
22:14:14  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
22:14:14  Eclipse OpenJ9 VM (build master-9f11871a18a, JRE 16 AIX ppc64-64-Bit Compressed References 20201202_402 (JIT enabled, AOT enabled)
22:14:14  OpenJ9   - 9f11871a18a
22:14:14  OMR      - a58cd2f5687
22:14:14  JCL      - f7021059fd3 based on jdk-16+26)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:51:29  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_foreign_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:45:22  TEST: java/foreign/TestCleaner.java

23:45:22  STDERR:
23:45:22  WARNING: Using incubator modules: jdk.incubator.foreign
23:45:22  05:48:49.230 0x301c6800   j9jcl.347    *   ** ASSERTION FAILED ** at common/jdk_internal_misc_ScopedMemoryAccess.cpp:40: ((0 ))
23:45:22  JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/12/02 23:48:49 - please wait.
23:45:22  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_1606969285655/jdk_foreign_0/work/scratch/core.20201202.234849.11469214.0001.dmp' in response to an event
23:45:22  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_1606969285655/jdk_foreign_0/work/scratch/core.20201202.234849.11469214.0001.dmp
23:45:22  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_1606969285655/jdk_foreign_0/work/scratch/javacore.20201202.234849.11469214.0002.txt' in response to an event
23:45:22  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_1606969285655/jdk_foreign_0/work/scratch/javacore.20201202.234849.11469214.0002.txt
23:45:22  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_1606969285655/jdk_foreign_0/work/scratch/Snap.20201202.234849.11469214.0003.trc' in response to an event
23:45:22  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_1606969285655/jdk_foreign_0/work/scratch/Snap.20201202.234849.11469214.0003.trc
23:45:22  JVMDUMP013I Processed dump event "traceassert", detail "".

23:45:22  TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
23:45:22  --------------------------------------------------
```

**Comment by pshipton** [comment] 2020-12-03 22:44
@tajila fyi

The assert if Assert_JCL_unimplemented();

**Comment by tajila** [comment] 2020-12-03 23:07
@babsingh Might be best to exclude this test in the short term until an investigation on how to properly implement this is determined. It may not be trivial to supply an appropriate implementation here as it deals with handling race conditions when closing scopes.

**Comment by babsingh** [comment] 2020-12-04 00:11
Duplicate of https://github.com/eclipse/openj9/issues/11027#issuecomment-730849265, which reports the `ScopedMemoryAccess` failures:
```
Failed: java/foreign/TestSharedAccess.java
Failed: java/foreign/TestSpliterator.java
Failed: java/foreign/TestByteBuffer.java
Failed: java/foreign/TestHandshake.java
Failed: java/foreign/TestCleaner.java
```

> may not be trivial to supply an appropriate implementation

This is true.

> Might be best to exclude this test

The above failing tests are not blockers. Do we need to exclude these tests to stop generation of core files? Or can they continue to fail until fixed?

**Comment by pshipton** [comment] 2020-12-04 00:28
> Do we need to exclude these tests

Up to @JasonFengJ9, excluding the failures and getting green or nearly green makes it easier to analyze the test results every day.

**Comment by pshipton** [comment] 2020-12-04 00:29
> Duplicate of #11027 (comment)

Do you want this issue open or closed?

**Comment by JasonFengJ9** [comment] 2020-12-04 01:49
> Do we need to exclude these tests
>  excluding the failures and getting green or nearly green makes it easier to triage the test results every day.

There are many other failures (such as those reported via https://github.com/eclipse/openj9/issues/11135) within `sanity.openjdk`, it is a bit distance from green.
Yes, the tests should be excluded.

**Comment by babsingh** [comment] 2020-12-04 15:40
> Do you want this issue open or closed?

+1 to close. I am tracking https://github.com/eclipse/openj9/issues/11027#issuecomment-730849265 to address all five test failures.

**Comment by tajila** [comment] 2020-12-04 16:08
I would prefer to have separate issues for seperate features, ie foreign-memAccess/varhandles, sealedtypes, MH.

**Comment by tajila** [comment] 2020-12-04 16:11
Also makes it easier to determine what is fixed and what needs to be done. I see that some things in  #11135 are already fixed. 

@JasonFengJ9 is  #11135 limited to just jdk.foreign test failures now?

**Comment by JasonFengJ9** [comment] 2020-12-04 16:21
@tajila Besides `jdk.foreign` test failures (excluded via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2085), `sanity.openjdk` (#11135) still have lots of `java/lang/invoke/MethodHandles` related failures which require OpenJDK JSR292 support (#7352) as per https://github.com/eclipse/openj9/issues/11135#issuecomment-724866324.
I am going to exclude them as well.

**Comment by pshipton** [comment] 2020-12-04 16:39
@JasonFengJ9 pls help ensure we have an issue open for everything excluded. They need to be tagged with `test excluded`, which hopefully the committer will do, but pls double check.

**Comment by JasonFengJ9** [comment] 2020-12-04 17:55
This test `java/foreign/TestCleaner.java` has been excluded via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2085.

**Comment by tajila** [comment] 2021-09-21 14:11
This is working, we have seperate issues to track the race condition

**Closed by tajila** 2021-09-21 14:11 UTC
Labels: comp:vm, project:panama, test failure, test excluded, jdk16

**Comment by pshipton** [comment] 2022-12-20 18:19
Excludes were removed via https://github.com/adoptium/aqa-tests/pull/2688
