### ISSUE TITLE
Support for cgroup v2

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse-openj9/openj9#6811] opened 2019-08-22 06:58 UTC
Fedora 31 to be GA-ed on 22 Oct, 2019 (as per the schedule https://fedoraproject.org/wiki/Releases/31/Schedule) would enable cgroup v2 by default: https://fedoraproject.org/wiki/Releases/31/ChangeSet#Modify_Fedora_31_to_use_CgroupsV2_by_default
Currently OpenJ9 only recognizes cgroup v1. It would be good if it can provide support for cgroup v2 as well, by the time Fedora 31 is released.
RHEL 8 released in May 2019 already supports cgroup v2, though by default it uses cgroup v1 (https://www.redhat.com/en/blog/world-domination-cgroups-rhel-8-welcome-cgroups-v2).

I believe most of the changes for supporting cgroup v2 would be required in port library in Eclipse OMR project. This issue can be used as the anchor for the changes required for supporting cgroup v2.

**Comment by DanHeidinga** [comment] 2019-08-22 13:42
@ashu-mehra There is an release coming up in October which would be the likely candidate if cgroupv2 is to be available before the Fedora 31 GAs.  

Can you write out what's required to support cgroup v2 and what the benefits / tradeoffs would be?

**Comment by ashu-mehra** [comment] 2020-05-20 23:59
I came across this openjdk bug report: https://bugs.openjdk.java.net/browse/JDK-8230305 which says JDK15 has added support for cgroup v2

**Comment by DanHeidinga** [comment] 2020-05-21 03:34
@ashu-mehra are you able to add cgroup v2 support to openj9?

**Comment by babsingh** [comment] 2022-03-09 17:45
### Related
- https://github.com/eclipse/omr/issues/1281
- https://github.com/eclipse-openj9/openj9/issues/14190

### References
- Control Group (cgroup) v2 documentation: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html
- cgroup's man page: https://man7.org/linux/man-pages/man7/cgroups.7.html

**Comment by babsingh** [comment] 2022-03-09 17:57
### Port library API for `cgroup`

The below 13 functions are involved:

```
/**
 * Checks if the platform supports cgroup system and the port library can use it
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @return TRUE if the the cgroup system is available, otherwise FALSE
 */
BOOLEAN omrsysinfo_cgroup_is_system_available(struct OMRPortLibrary *portLibrary); 

/**
 * Returns cgroup subsystems available for port library to use
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @return bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_* indicating the
 * subsystems that are available
 */
uint64_t omrsysinfo_cgroup_get_available_subsystems(struct OMRPortLibrary *portLibrary);

/**
 * Checks if the specified cgroup subsystems are available for port library to use.
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 * @param[in] subsystemFlags bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_*
 *
 * @return bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_* indicating the
 * subsystems that are available 
 */
uint64_t omrsysinfo_cgroup_are_subsystems_available(struct OMRPortLibrary *portLibrary, uint64_t subsystemFlags); 

/**
 * Returns cgroup subsystems enabled for port library to use
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @return bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_* indicating the
 * subsystems that are enbaled
 */
uint64_t omrsysinfo_cgroup_get_enabled_subsystems(struct OMRPortLibrary *portLibrary);

/**
 * Enable port library to use specified cgroup subsystems
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 * @param[in] subsystems bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_* 
 * indicating the subsystems to be enabled 
 *                           
 * @return bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_* indicating the subsystems that are enabled
 */
uint64_t omrsysinfo_cgroup_enable_subsystems(struct OMRPortLibrary *portLibrary, uint64_t requestedSubsystems);

/**
 * Check which subsystems are enabled in port library
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 * @param[in] subsystemsFlags bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_*
 *
 * @return bitwise-OR of flags of type OMR_CGROUP_SUBSYSTEMS_* indicating the subsystems that are enabled
 */
uint64_t omrsysinfo_cgroup_are_subsystems_enabled(struct OMRPortLibrary *portLibrary, uint64_t subsystemsFlags);

/**
 * Retrieves the memory limit imposed by the cgroup to which the current process belongs.
 * The caller should ensure port library is enabled to use cgroup limits by calling
 * omrsysinfo_cgroup_enable_limits() before calling this function.
 * When the fuction returns OMRPORT_ERROR_SYSINFO_CGROUP_UNSUPPORTED_PLATFORM,
 * value of *limits is unspecified.
 * Note that 'limit' parameter must not be NULL.
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 * @param[out] limit pointer to uint64_t which successful return contains memory limit imposed by cgroup
 *
 * @return 0 on success, otherwise negative error code
 */
int32_t omrsysinfo_cgroup_get_memlimit(struct OMRPortLibrary *portLibrary, uint64_t *limit);

/**
 * Checks if memory limit is set by the process's cgroup for memory subsystem
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @return TRUE if memory limit is set by the process's cgroup, FALSE otherwise
 */
BOOLEAN omrsysinfo_cgroup_is_memlimit_set(struct OMRPortLibrary *portLibrary);

/**
 * Gets the list of subsystems available
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @return OMRCgroupEntry struct pointer of the linked list if available, NULL otherwise
 */
struct OMRCgroupEntry * omrsysinfo_get_cgroup_subsystem_list(struct OMRPortLibrary *portLibrary);

/**
 * States if Runtime is running in a container
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @return TRUE if Runtime is running in a container and FALSE if not or if an error occurs
 */
BOOLEAN omrsysinfo_is_running_in_container(struct OMRPortLibrary *portLibrary);

/**
 * Initiates the iterator to get cgroup metric values based on the cgroup subsystem
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @param[in] subsystem flag of type OMR_CGROUP_SUBSYSTEMS_* representing the cgroup subsystem
 *
 * @param[in] state Pointer to the `OMRCgroupMetricIteratorState` struct
 *
 * @return 0 on success and error code on failure
 */
int32_t omrsysinfo_cgroup_subsystem_iterator_init(struct OMRPortLibrary *portLibrary, uint64_t subsystem, struct OMRCgroupMetricIteratorState *state);

/**
 * Checks if there are any cgroup metrics in the subsystem to iterated over
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @param[in] state Pointer to the `OMRCgroupMetricIteratorState` struct
 *
 * @return TRUE if any cgroup metric available else FALSE
 */
BOOLEAN omrsysinfo_cgroup_subsystem_iterator_hasNext(struct OMRPortLibrary *portLibrary, const struct OMRCgroupMetricIteratorState *state);

/**
 * Sends the metric key at a given state of cgroup metric iterator
 * should be used after the omrsysinfo_cgroup_subsystem_iterator_hasNext check
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @param[in] state Pointer to the `OMRCgroupMetricIteratorState` struct
 *
 * @param[in/out] gets the metric key from the state of iterator
 *
 * @return 0 if any cgroup metric available else error code
 */
int32_t omrsysinfo_cgroup_subsystem_iterator_metricKey(struct OMRPortLibrary *portLibrary, const struct OMRCgroupMetricIteratorState *state, const char **metricKey);

/**
 * Reads the next cgroup metric and sets the value to return 
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @param[in] state Pointer to the `OMRCgroupMetricIteratorState` struct
 *
 * @param[in] metricElement Pointer to the `OMRCgroupMetricElement` struct
 *
 * @param[in/out] printUnits Pointer to a BOOLEAN which states if the metric has units
 *
 * @return 0 on success and error code on failure
 */
int32_t omrsysinfo_cgroup_subsystem_iterator_next(struct OMRPortLibrary *portLibrary, struct OMRCgroupMetricIteratorState *state, struct OMRCgroupMetricElement *metricElement);

/**
 * Free the memory allocated to the elements in the iterator
 *
 * @param[in] portLibrary pointer to OMRPortLibrary
 *
 * @param[in] state Pointer to the `OMRCgroupMetricIteratorState` struct
 */
void omrsysinfo_cgroup_subsystem_iterator_destroy(struct OMRPortLibrary *portLibrary, struct OMRCgroupMetricIteratorState *state);
```

**Comment by babsingh** [comment] 2022-03-09 18:36
### Next steps

1. We need to derive logic to distinguish between cgroup v1 and cgroup v2 entities using the references specified in https://github.com/eclipse-openj9/openj9/issues/6811#issuecomment-1063192011.
2. Evaluate if existing data structures, such as `OMRCgroupEntry`, `OMRCgroupMetricElement` and `OMRCgroupMetricIteratorState`, need to be updated in order to support cgroup v2.
3. Evaluate the impact and new logic for the cgroup API. E.g. cgroup v1 has `memory.limit_in_bytes` but it changes to `memory.max` in cgroup v2. Another difference: cgroup v2 follows a unified hierarchy unlike cgroup v1.

Based upon uses of `cgroup` API in downstream projects https://github.com/eclipse-openj9/openj9/issues/14190#issuecomment-1051185092, the following four functions should be prioritized for cgroup v2 support in order to effectively resolve customer issues:
1. `omrsysinfo_cgroup_enable_subsystems`
2. `omrsysinfo_cgroup_get_available_subsystems`
3. `omrsysinfo_cgroup_are_subsystems_enabled`
4. `omrsysinfo_cgroup_is_memlimit_set`

The above items can be pursued in separate issues while linking to this issue as a global tracker.

**Comment by mpirvu** [comment] 2022-03-15 16:47
I discovered that published Semeru container images do not load the embedded AOT code because of various AOT incompatibility issues. This happens because the AOT code is not in "portable" format. This is most likely due to the fact that Semeru images were built in an environment with cgroups v2 and OpenJ9 is not able to detect that is running in containers.
I used a machine with cgroups v2 and generated a javacore while running in containers. The javacore showed:
```
1CICONTINFO    Running in container : FALSE
1CICGRPINFO    JVM support for cgroups enabled : FALSE
```

I am raising the priority of this issue since many customers running OpenJ9 in containers will not be able to use AOT and experience a start-up slowdown. As I understand, we do not have much control on the dockerhub process/environment that builds the images.

**Comment by pshipton** [comment] 2022-03-15 16:54
I think this can be closed as a dup of https://github.com/eclipse-openj9/openj9/issues/14190 ?

**Comment by babsingh** [comment] 2022-03-15 16:59
I thought this was an OMR issue. Yes, it can be closed as a dup of https://github.com/eclipse-openj9/openj9/issues/14190. @EricYangIBM Can you move the important details into a new OMR Github issue (== global tracker for the OMR implementation)? After doing this, please close this issue.

**Comment by mpirvu** [comment] 2022-03-15 17:01
> Docker containers can be switched back to cgroup v1 since both cgroup v1 and v2 should be available in newer containers.

The problem is that we don't control the process of building the Semeru images. Once those images have been produced, they contain non-portable AOT.

**Comment by EricYangIBM** [comment] 2022-03-15 17:07
> new OMR Github issue

Doesn't https://github.com/eclipse/omr/issues/1281 already track this? I can update that PR with additional information

**Closed** 2022-03-15 18:05 UTC
Labels: prio:high, comp:vm, jdk15
