### ISSUE TITLE
AIX jdk-15.0.2+7_openj9-0.24.0 or jdk-16 Nightly when used to build jdk16/17 Hotspot causes jvmtiGen failure 

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse-openj9/openj9#12061] opened 2021-02-26 14:37 UTC
This is an odd intermittent (roughly 1 in 3) behaviour on AIX hotspot builds at AdoptOpenJDK built using OpenJ9 bootjdk, which fail to build due to jvmtiGen failing to produce incorrect gensrc, see issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2466
Using a jdk15/16 Hotspot bootjdk works fine.
@pshipton how do you want to approach this one as jvmtiGen is Hotspot code? It is basically a XSL XML input->output translate tool using javax.xml.transform.* .

**Comment by andrew-m-leonard** [comment] 2021-02-26 15:26
The translate either generates invalid code, or produces a NPE see here: https://github.com/AdoptOpenJDK/openjdk-build/issues/2466#issuecomment-779639008

**Comment by pshipton** [comment] 2021-02-26 21:15
@zl-wang any ideas? Considering the intermittent nature, and occurring more often on a particular machine, it may be a JIT issue.

**Comment by zl-wang** [comment] 2021-03-01 13:37
I only saw errors related to native code compilation with jvmtiEnv.hpp.   could you point me to the command line where something unexpected using OpenJ9 happened?

**Comment by andrew-m-leonard** [comment] 2021-03-01 13:49
This NPE sometimes occurs: https://github.com/AdoptOpenJDK/openjdk-build/issues/2466#issuecomment-779639008
other times the code just generates the wrong source which then fails to compile...

**Comment by rmnattas** [comment] 2021-03-12 16:30
Is there a way that I can reproduce the issue? The state when it crashed with the command line to run or some kind of some jvmtiGen mimic/test.

**Comment by andrew-m-leonard** [comment] 2021-03-15 16:22
So this is the make command being invoked: https://github.com/AdoptOpenJDK/openjdk-jdk16/blob/72dfba8053ed5c159b832349ce5290b053ed37ad/make/hotspot/gensrc/GensrcJvmti.gmk#L68

**Comment by zl-wang** [comment] 2021-03-23 17:07
we can come back to this issue later ...

**Comment by rmnattas** [comment] 2021-06-22 18:02
This issue was caused by the commit https://github.com/eclipse-openj9/openj9/pull/11091 (Nov 9), I still yet to fully understand why it ends up causing the symptoms I see (which cause the NPE in one of the build run command, and wrong generated `jvmti.h` in another run command, both from `GensrcJvmti.gmk`).
This commit was reverted https://github.com/eclipse-openj9/openj9/pull/12213 (Mar 15) as it was appeared to cause an issue running Clojure on OpenJ9 https://github.com/eclipse-openj9/openj9/issues/12191, and newer builds does not have the NPE and generating correct `jvmti.h` files when building Hotspot. 

Regarding https://github.com/adoptium/infrastructure/issues/2119 which was mentioned last here, the early stages of investigation for that issue were before the revert and it encountered this issue and was mentioned that it could be a duplicate. But the last failed mentioned https://github.com/adoptium/infrastructure/issues/2119#issuecomment-827814829 was using a build with the revert, hence its a separate issue than this one.

**Comment by fjeremic** [comment] 2021-09-07 13:34
Given the above comments I think we can close this off as fixed by #12213?

**Comment by tajila** [comment] 2021-09-07 13:37
@andrew-m-leonard ^^

**Comment by pshipton** [comment] 2021-09-09 01:16
I'll just close and it can be reopened if there is still a problem.

**Closed by pshipton** 2021-09-09 01:16 UTC
Labels: comp:jit, userRaised
