### ISSUE TITLE
OpenJDK jdk/incubator/vector tests timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17937] opened 2023-08-11 15:15 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/31/ - [cent7-x64-3](https://openj9-jenkins.osuosl.org/computer/cent7-x64-3)
jdk_vector_byte64_j9_0
    jdk/incubator/vector/Byte64VectorTests.java
jdk_vector_short128_j9_0 
    jdk/incubator/vector/Short128VectorTests.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/31/openjdk_test_output.tar.gz
```
20:56:08  "MainThread" prio=5 Id=22 RUNNABLE
20:56:08  	at jdk.incubator.vector@21-internal/jdk.incubator.vector.Byte64Vector.rearrange(Byte64Vector.java:452)
20:56:08  	at jdk.incubator.vector@21-internal/jdk.incubator.vector.Byte64Vector.rearrange(Byte64Vector.java:41)
20:56:08  	at jdk.incubator.vector@21-internal/jdk.incubator.vector.ByteVector.sliceTemplate(ByteVector.java:2289)
20:56:08  	at jdk.incubator.vector@21-internal/jdk.incubator.vector.Byte64Vector.slice(Byte64Vector.java:418)
20:56:08  	at jdk.incubator.vector@21-internal/jdk.incubator.vector.Byte64Vector.slice(Byte64Vector.java:41)
20:56:08  	at jdk.incubator.vector@21-internal/jdk.incubator.vector.ByteVector.slice(ByteVector.java:2301)
20:56:08  	at app//Byte64VectorTests.sliceByte64VectorTestsMasked(Byte64VectorTests.java:4812)
20:56:08  	at java.base@21-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:56:08  	at java.base@21-internal/java.lang.reflect.Method.invoke(Method.java:580)
20:56:08  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
20:56:08  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
20:56:08  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
20:56:08  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
20:56:08  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
20:56:08  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
20:56:08  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
20:56:08  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
20:56:08  	at java.base@21-internal/java.util.ArrayList.forEach(ArrayList.java:1596)
20:56:08  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
20:56:08  	at app//org.testng.TestRunner.run(TestRunner.java:585)
20:56:08  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
20:56:08  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
20:56:08  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
20:56:08  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
20:56:08  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
20:56:08  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
20:56:08  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
20:56:08  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
20:56:08  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
20:56:08  	at app//org.testng.TestNG.run(TestNG.java:1037)
20:56:08  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
20:56:08  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
20:56:08  	at java.base@21-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:56:08  	at java.base@21-internal/java.lang.reflect.Method.invoke(Method.java:580)
20:56:08  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
20:56:08  	at java.base@21-internal/java.lang.Thread.run(Thread.java:1595)
```
```
20:27:01  "MainThread" prio=5 Id=22 RUNNABLE
20:27:01  	at app//Short128VectorTests.unsliceShort128VectorTestsMasked(Short128VectorTests.java:4928)
20:27:01  	at java.base@21-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:27:01  	at java.base@21-internal/java.lang.reflect.Method.invoke(Method.java:580)
20:27:01  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
20:27:01  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
20:27:01  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
20:27:01  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
20:27:01  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
20:27:01  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
20:27:01  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
20:27:01  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
20:27:01  	at java.base@21-internal/java.util.ArrayList.forEach(ArrayList.java:1596)
20:27:01  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
20:27:01  	at app//org.testng.TestRunner.run(TestRunner.java:585)
20:27:01  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
20:27:01  	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
20:27:01  	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
20:27:01  	at app//org.testng.SuiteRunner.run(SuiteRunner.java:286)
20:27:01  	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
20:27:01  	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
20:27:01  	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
20:27:01  	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
20:27:01  	at app//org.testng.TestNG.runSuites(TestNG.java:1069)
20:27:01  	at app//org.testng.TestNG.run(TestNG.java:1037)
20:27:01  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
20:27:01  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
20:27:01  	at java.base@21-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:27:01  	at java.base@21-internal/java.lang.reflect.Method.invoke(Method.java:580)
20:27:01  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
20:27:01  	at java.base@21-internal/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment] 2023-08-11 15:17
Changes from previous build.
https://github.com/eclipse-openj9/openj9/compare/07388a27...67e11c621e2

@gita-omr

**Comment by pshipton** [comment] 2023-08-14 13:21
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/32
jdk_vector_int128_j9_0
jdk/incubator/vector/Int128VectorTests.java
```
19:03:52  "MainThread" prio=5 Id=26 RUNNABLE
19:03:52  	at java.base@21-internal/java.text.SimpleDateFormat.format(SimpleDateFormat.java:1001)
19:03:52  	at java.base@21-internal/java.text.SimpleDateFormat.format(SimpleDateFormat.java:971)
19:03:52  	at java.base@21-internal/java.text.DateFormat.format(DateFormat.java:339)
19:03:52  	at java.base@21-internal/java.text.Format.format(Format.java:159)
19:03:52  	at app//org.testng.util.TimeUtils.formatTimeInLocalOrSpecifiedTimeZone(TimeUtils.java:23)
19:03:52  	at app//org.testng.reporters.XMLSuiteResultWriter.getTestResultAttributes(XMLSuiteResultWriter.java:202)
19:03:52  	at app//org.testng.reporters.XMLSuiteResultWriter.addTestResult(XMLSuiteResultWriter.java:152)
19:03:52  	at app//org.testng.reporters.XMLSuiteResultWriter.addTestResults(XMLSuiteResultWriter.java:135)
19:03:52  	at app//org.testng.reporters.XMLSuiteResultWriter.writeAllToBuffer(XMLSuiteResultWriter.java:79)
19:03:52  	at app//org.testng.reporters.XMLSuiteResultWriter.writeSuiteResult(XMLSuiteResultWriter.java:54)
19:03:52  	at app//org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:146)
19:03:52  	at app//org.testng.reporters.XMLReporter.writeSuite(XMLReporter.java:108)
19:03:52  	at app//org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:76)
19:03:52  	at app//org.testng.TestNG.generateReports(TestNG.java:1099)
19:03:52  	at app//org.testng.TestNG.run(TestNG.java:1042)
19:03:52  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
19:03:52  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
19:03:52  	at java.base@21-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:03:52  	at java.base@21-internal/java.lang.reflect.Method.invoke(Method.java:580)
19:03:52  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
19:03:52  	at java.base@21-internal/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment] 2023-08-14 14:53
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_OpenJDK21_testList_2/7
jdk_vector_byte64_j9_0
jdk/incubator/vector/Byte64VectorTests.java
```
14:49:56  "MainThread" prio=5 Id=22 RUNNABLE
14:49:56  	at app//org.testng.reporters.XMLUtils.xmlOpen(XMLUtils.java:112)
14:49:56  	at app//org.testng.reporters.XMLUtils.xmlOpen(XMLUtils.java:88)
14:49:56  	at app//org.testng.reporters.XMLStringBuffer.push(XMLStringBuffer.java:99)
14:49:56  	at app//org.testng.reporters.XMLStringBuffer.push(XMLStringBuffer.java:111)
14:49:56  	at app//org.testng.reporters.XMLStringBuffer.push(XMLStringBuffer.java:149)
14:49:56  	at app//org.testng.reporters.XMLSuiteResultWriter.addTestResultOutput(XMLSuiteResultWriter.java:325)
14:49:56  	at app//org.testng.reporters.XMLSuiteResultWriter.addTestResult(XMLSuiteResultWriter.java:160)
14:49:56  	at app//org.testng.reporters.XMLSuiteResultWriter.addTestResults(XMLSuiteResultWriter.java:135)
14:49:56  	at app//org.testng.reporters.XMLSuiteResultWriter.writeAllToBuffer(XMLSuiteResultWriter.java:79)
14:49:56  	at app//org.testng.reporters.XMLSuiteResultWriter.writeSuiteResult(XMLSuiteResultWriter.java:54)
14:49:56  	at app//org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:146)
14:49:56  	at app//org.testng.reporters.XMLReporter.writeSuite(XMLReporter.java:108)
14:49:56  	at app//org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:76)
14:49:56  	at app//org.testng.TestNG.generateReports(TestNG.java:1099)
14:49:56  	at app//org.testng.TestNG.run(TestNG.java:1042)
14:49:56  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
14:49:56  	at app//com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
14:49:56  	at java.base@21-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
14:49:56  	at java.base@21-internal/java.lang.reflect.Method.invoke(Method.java:580)
14:49:56  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
14:49:56  	at java.base@21-internal/java.lang.Thread.run(Thread.java:1595)
```

jdk_vector_short128_j9_0
jdk/incubator/vector/Short128VectorTests.java
```
14:19:33  "MainThread" prio=5 Id=22 RUNNABLE
14:19:33  	at app//Short128VectorTests.unsliceShort128VectorTestsMasked(Short128VectorTests.java:4928)
```

**Comment by pshipton** [comment] 2023-08-15 13:01
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/32/
jdk/incubator/vector/Int128VectorTests.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/32
jdk/incubator/vector/Byte64VectorTests.java
jdk/incubator/vector/Short128VectorTests.java

**Comment by tajila** [comment] 2023-08-15 13:27
@gita-omr

**Comment by gita-omr** [comment] 2023-08-15 18:57
Running 50 iterations: https://openj9-jenkins.osuosl.org/job/Grinder/2744/

**Comment by pshipton** [comment] 2023-08-15 20:09
There are a bunch more in https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/567/
These failures are occurring frequently, I don't think I need to keep reporting them all.

**Comment by gita-omr** [comment] 2023-08-15 20:20
> These failures are occurring frequently, I don't think I need to keep reporting them all.

Are they all timeouts?

**Comment by pshipton** [comment] 2023-08-15 20:27
> Are they all timeouts?

Yes.

**Comment by pshipton** [comment] 2023-08-16 10:26
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK21/89/
Failures on alinux, xlinux, Windows.

**Comment by pshipton** [comment] 2023-08-16 10:29
Any chance this is caused by https://github.com/eclipse-openj9/openj9/pull/17222 ?
This change is included in the first build were the timeouts started to occur. Since the timeouts occur in almost every build (maybe every build), there must be something that changed either in that build or the previous.

**Comment by jdmpapin** [comment] 2023-08-16 15:44
Possibly. It sure looks a lot more likely than the other changes in the commit range you linked

**Comment by gita-omr** [comment] 2023-08-16 16:29
Yes, I was thinking the same but no idea yet how it can cause a timeout. We can remove that change since it's not urgent.

**Comment by 0xdaryl** [comment] 2023-08-16 16:43
> We can remove that change since it's not urgent.

Or check in a change to default it to off (the original behaviour), and then keep an eye on build timeouts afterwards.

**Comment by gita-omr** [comment] 2023-08-16 17:52
> Or check in a change to default it to off (the original behaviour), and then keep an eye on build timeouts afterwards.

OK, I will try to reproduce, but if not, will disable by the EOD.

**Comment by gita-omr** [comment] 2023-08-17 01:25
Should be fixed by https://github.com/eclipse-openj9/openj9/pull/17970

**Closed** 2023-08-18 12:41 UTC
Labels: comp:jit, test failure, blocker, jdk21
