### ISSUE TITLE
Show owner of J9VMInternals$ClassInitializationLock in javacore

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#284] opened 2017-10-10 21:03 UTC
A customer experienced a deadlock but it was difficult to diagnose. The javacore didn't detect the deadlock and the thread that was blocked was waiting on a `J9VMInternals$ClassInitializationLock`, but it showed as `<unowned>`, so it was difficult to understand which other thread was part of the deadlock (through code inspection, we deduced it was a class static initializer). Here's the thread blocking most of the threads in the JVM:

```
3XMTHREADINFO      "Thread-62" J9VMThread:0x000000000232BB00, j9thread_t:0x00007FB9C00360A0, java/lang/Thread:0x0000000080BD75E0, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x71, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x5578, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000101)
3XMTHREADINFO2            (native stack address range from:0x00007FB9C4E3F000, to:0x00007FB9C4E80000, size:0x41000)
3XMCPUTIME               CPU usage total: 2.473643599 secs, current category="Application"
3XMTHREADBLOCK     **Waiting on: java/lang/J9VMInternals$ClassInitializationLock@0x0000000081789B98 Owned by: <unowned>**
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/ibm/apc/xd/demand/predictors/APCXDDemandPredictorShim$1.cellAdded(APCXDDemandPredictorShim.java:59) [...]
```

And here's the thread that was the other half of the deadlock:

```
3XMTHREADINFO      "APCRunnable" J9VMThread:0x0000000003351B00, j9thread_t:0x00007FB9D834DE30, java/lang/Thread:0x00000000830FC468, state:B, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1D7, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x5B7F, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000201)
3XMTHREADINFO2            (native stack address range from:0x00007FB9BE87F000, to:0x00007FB9BE8C0000, size:0x41000)
3XMCPUTIME               CPU usage total: 1.717428364 secs, current category="Application"
3XMTHREADBLOCK     **Blocked on: com/ibm/ws/odc/nd/ODCTreeImpl@0x0000000080BC35F8 Owned by: "Thread-62" (J9VMThread:0x000000000232BB00, java/lang/Thread:0x0000000080BD75E0)**
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/ibm/apc/xd/demand/predictors/combined/APCXDCombinedPredictorListener.checkIfWebServerWithIMEnabledOrODRExists(APCXDCombinedPredictorListener.java:197)
4XESTACKTRACE                at com/ibm/apc/xd/demand/predictors/combined/APCXDCombinedPredictorListener.<init>(APCXDCombinedPredictorListener.java:85)
4XESTACKTRACE                at com/ibm/apc/xd/demand/predictors/APCXDDemandPredictorShim.handleConfigChange_CellAdded(APCXDDemandPredictorShim.java:83)
5XESTACKTRACE                   (entered lock: java/util/HashMap@0x0000000081789C40, entry count: 1)
4XESTACKTRACE                at com/ibm/apc/xd/demand/predictors/APCXDDemandPredictorShim.access$000(APCXDDemandPredictorShim.java:40)
4XESTACKTRACE                at com/ibm/apc/xd/demand/predictors/APCXDDemandPredictorShim$1.cellAdded(APCXDDemandPredictorShim.java:59)
4XESTACKTRACE                at com/ibm/ws/xd/container/state/odc/impl/XdCsODCHelper_Notification.notifyListeners_Cell(XdCsODCHelper_Notification.java:309)
4XESTACKTRACE                at com/ibm/ws/xd/container/state/odc/impl/XdCsODCHelper_Subscription.subscribe(XdCsODCHelper_Subscription.java:77)
5XESTACKTRACE                   (entered lock: com/ibm/apc/xd/demand/predictors/APCXDDemandPredictorShim$1@0x0000000081789C68, entry count: 1)
4XESTACKTRACE                at com/ibm/ws/xd/container/state/odc/XdCsListener_Cell.subscribe(XdCsListener_Cell.java:46)
4XESTACKTRACE                **at com/ibm/apc/xd/demand/predictors/APCXDDemandPredictorShim.<clinit>**(APCXDDemandPredictorShim.java:68) [...]
```

The proposed solution is to replace `<unowned>` with the thread doing the class static initialization:

`3XMTHREADBLOCK     Waiting on: java/lang/J9VMInternals$ClassInitializationLock@0x0000000081789B98 **Owned by: "APCRunnable" (J9VMThread [...]**`

Ideally, the javacore deadlock detection could detect this, although just adding the owner above would be sufficient.

Full javacore available internally within IBM (ask kevin.grigorenko@us.ibm.com).

**Comment by deesebas** [comment] 2017-10-17 08:10
I agree, it should be possible to show the owner of this lock in the javacore.

jdmpview/ddr command 'info lock' does show the owner of this lock, so this information is present at the time of javacore generation.

For e.g., from a different javacore+coredump where I encountered a similar deadlock, info lock shows:

```java/lang/J9VMInternals$ClassInitializationLock@**0x5f5ae3a8**
        waiting thread id: 39574 name: StatisticsManager.Alarm Pool : 0

java/lang/J9VMInternals$ClassInitializationLock@**0x5f661110**
        waiting thread id: 39040 name: server.startup : 1```

Corresponding Javacore:
```3XMTHREADINFO      "StatisticsManager.Alarm Pool : 0" J9VMThread:0x0000000081859B00, j9thread_t:0x00007FF2FC007C80, java/lang/Thread:0x0000000005C64F60, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x85, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x7B53, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000101)
3XMTHREADINFO2            (native stack address range from:0x00007FF2BE501000, to:0x00007FF2BE542000, size:0x41000)
3XMCPUTIME               CPU usage total: 0.020969484 secs
3XMTHREADBLOCK     Waiting on: java/lang/J9VMInternals$ClassInitializationLock@**0x00000000056CDA58** Owned by: <unowned>


3XMTHREADINFO      "server.startup : 1" J9VMThread:0x0000000080DED600, j9thread_t:0x00007FF3A91B2210, java/lang/Thread:0x0000000003F4CEF0, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x61, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x7ABF, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000101)
3XMTHREADINFO2            (native stack address range from:0x00007FF2BF065000, to:0x00007FF2BF0A6000, size:0x41000)
3XMCPUTIME               CPU usage total: 8.550077027 secs
3XMTHREADBLOCK     Waiting on: java/lang/J9VMInternals$ClassInitializationLock@**0x0000000005F15310** Owned by: <unowned>```

**Comment by LakshmiSwethaG** [comment] 2018-09-19 12:21
I am having a similar issue where the customer is having a hang and its difficult to get the details of the lock. Threads are waiting on ClassInitializationLock which is <unowned> : Waiting on: java/lang/J9VMInternals$ClassInitializationLock@0x0000000611EEA3C8 Owned by: <unowned>
So I tried this in ddr.

> 
> !j9objectmonitor 0x0000000611EEA3C8
J9ObjectMonitor at 0x611eea3c8 {
 Fields for J9ObjectMonitor:
       0x0: omrthread_monitor_t monitor = !j9threadmonitor 0x02DE3D8102E11B2A
       0x8: UDATA proDeflationCount = 0x7AC062C4C23BC2BE (8845178265367462590)
       0x10: UDATA antiDeflationCount = 0x0000001002EBBE00 (68768480768)
       0x18: j9objectmonitor_t alternateLockword = !j9x 0x611eea3e0
       0x1c: U32 hash = 0x00000000 (0)
}

So I checked for j9threadmonitor:
> !j9threadmonitor 0x02DE3D8102E11B2A
J9ThreadMonitor at 0x2de3d8102e11b2a {
 Fields for J9ThreadMonitor:
       0x0: uintptr_t count = <FAULT>
       0x8: struct J9Thread *volatile owner = <FAULT>
       0x10: struct J9Thread * waiting = <FAULT>
       0x18: uintptr_t flags = <FAULT>
       0x20: uintptr_t userData = <FAULT>
       0x28: struct J9ThreadMonitorTracing * tracing = <FAULT>
       0x30: char * name = !j9x <FAULT>
       0x38: uintptr_t pinCount = <FAULT>
       0x40: uintptr_t spinlockState = <FAULT>
       0x48: uintptr_t spinCount1 = <FAULT>
       0x50: uintptr_t spinCount2 = <FAULT>
       0x58: uintptr_t spinCount3 = <FAULT>
       0x60: struct J9Thread * blocking = <FAULT>
       0x68: uintptr_t sampleCounter = <FAULT>
       0x70: const struct J9ThreadCustomSpinOptions * customSpinOptions = <FAULT>
       0x78: volatile uintptr_t spinThreads = <FAULT>
       0x80: J9OSMutex mutex = !j9x 0x2de3d8102e11baa
       0xa8: struct J9Thread * notifyAllWaiting = <FAULT>
}

And the J9OSMutex,
> !j9x 0x2de3d8102e11baa
0x2DE3D8102E11BAA :  Problem running command:
com.ibm.j9ddr.corereaders.memory.MemoryFault: Memory Fault reading 0x2DE3D8102E11BAA

Do you know why is this happening? and What are the conditions for this to happen?

**Comment by kgibm** [comment] 2018-09-19 14:54
@LakshmiSwethaG Memory faults are often caused by either 1) truncated core dumps, or 2) core dumps taken during a GC without requesting exclusive access. For 1, check that core and file ulimits are unlimited and there's enough disk space (and that the size of the resulting core is the size of VSZ from ps). For 2, the best way I've found to ensure exclusive access when taking core is to set `-Xdump:system:events=user,request=exclusive`. Of course then there's no easy way to just take a javacore with the user signal, but in that case I then just use something like [Java surgery](https://www.ibm.com/developerworks/community/groups/service/html/communityview?communityUuid=7d3dc078-131f-404c-8b4d-68b3b9ddd07a) with the JavaDump command. Alternatively, just take multiple core dumps (using gcore, etc.) so that statistically you're likely to have one not during GC. You can check `!snapformat` in jdmpview to check if core dump was taken during GC.

If it's not either 1 or 2, then I don't know what it could be - you might want to reach out to the J9 VM folks on a different channel because they're probably not watching this thread.

**Comment by imkabir** [comment] 2020-04-15 10:27
Is anyone looking at this issue? I have got another instance of the issue where the application is hanging because a thread is waiting on java/lang/J9VMInternals$ClassInitializationLock, but the owner is unknown.

**Comment by imkabir** [comment] 2020-06-05 07:01
I got the same issue again, and because owner of java/lang/J9VMInternals$ClassInitializationLock is not showing up, I need to look at the stacks of all the threads and guess the owner of it. This instance was particularly difficult because there were multiple java/lang/J9VMInternals$ClassInitializationLock.

**Comment by sharanpatil123** [comment] 2020-07-24 08:13
I have got another instance of the issue with same lock java/lang/J9VMInternals$ClassInitializationLock  but owner of this lock in unknown. May I know the status of this issue and in which upcoming java release we can expect  this issue would be merged?

**Comment by smithwil** [comment] 2020-10-06 15:48
This diagnostic problem is still being hit in real user cases. It would save people a lot of time in diagnosing deadlocks if the owner of the `J9VMInternals$ClassInitializationLock` was shown in the javacore.

**Comment by paulcheeseman** [comment] 2020-10-07 08:56
Here's a reproducer:

```
public class ClassInitLockBug {
	public static void main(String[] args) {
		ClassInitThread t1 = new ClassInitThread();
		ClassInitThread t2 = new ClassInitThread();
		
		t1.setName("Class Initialization Thread 1");
		t2.setName("Class Initialization Thread 2");
		
		t1.start();
		t2.start();		
	}
	
	static class ClassInitThread extends Thread {		
		public void run() {
			try {
				Class.forName("TestClass");
			} catch (ClassNotFoundException cnfe) {}
		}
	}
}

class TestClass {
	static {
		System.out.println(Thread.currentThread() + ": entered TestClass static initializer...");
		try {
			Thread.sleep(Long.MAX_VALUE);
		} catch (InterruptedException e) {}
	}
}
```

Just compile and run `ClassInitLockBug`, then take a javacore. You will see the "unowned" `ClassInitializationLock`, but `Class Initialization Thread 2` is clearly blocked by `Class Initialization Thread 1`:

```
3XMTHREADINFO      "Class Initialization Thread 1" J9VMThread:0x000000000091A800, omrthread_t:0x00000187858ED748, java/lang/Thread:0x00000000FFFE0F78, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1B, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x5710, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000481)
3XMCPUTIME               CPU usage total: 0.0 secs, user: 0.0 secs, system: 0.0 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=4520 (0x11A8)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.sleep(Native Method)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:952)
4XESTACKTRACE                at TestClass.<clinit>(ClassInitLockBug.java:26)
4XESTACKTRACE                at java/lang/Class.forNameImpl(Native Method)
4XESTACKTRACE                at java/lang/Class.forName(Class.java:337)
4XESTACKTRACE                at ClassInitLockBug$ClassInitThread.run(ClassInitLockBug.java:16)
```

```
3XMTHREADINFO      "Class Initialization Thread 2" J9VMThread:0x000000000094F100, omrthread_t:0x00000187858EC270, java/lang/Thread:0x00000000FFFE10C8, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1C, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x1C04, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000181)
3XMCPUTIME               CPU usage total: 0.0 secs, user: 0.0 secs, system: 0.0 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/lang/J9VMInternals$ClassInitializationLock@0x00000000FFFE5988 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=4096 (0x1000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Class.forNameImpl(Native Method)
4XESTACKTRACE                at java/lang/Class.forName(Class.java:337)
4XESTACKTRACE                at ClassInitLockBug$ClassInitThread.run(ClassInitLockBug.java:16)
```

```
1LKMONPOOLDUMP Monitor Pool Dump (flat & inflated object-monitors):
2LKMONINUSE      sys_mon_t:0x0000018785924178 infl_mon_t: 0x00000187859241F8:
3LKMONOBJECT       java/lang/J9VMInternals$ClassInitializationLock@0x00000000FFFE5988: <unowned>
3LKNOTIFYQ            Waiting to be notified:
3LKWAITNOTIFY            "Class Initialization Thread 2" (J9VMThread:0x000000000094F100)
```

**Comment by keithc-ca** [comment] 2020-10-07 18:12
I believe this is working as expected.

Threads can be waiting on an object even if not currently owned by any other thread. The `ClassInitializationLock` are only locked briefly to check, and where suitable advance, their state. Only when the state changes are other threads notified; the waiting threads immediately wait again if the state hasn't become satisfying to them.

The following sample code exhibits the same (expected) behavior.
```
public class NoOwner {

	public static void main(String[] args) {
		new NoOwner().run();
	}

	private static void trace(String message) {
		System.out.println(Thread.currentThread() + message);
	}

	private boolean ready;

	private NoOwner() {
		super();
		this.ready = false;
	}

	private void awaitReady() {
		trace(": begins waiting...");

		long start = System.currentTimeMillis();

		synchronized (this) {
			while (!ready) {
				long delta = System.currentTimeMillis() - start;

				trace(": not ready after " + delta + " ms");

				try {
					wait(1000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}

		long delta = System.currentTimeMillis() - start;

		trace(": ready after " + delta + " ms");
	}

	private Thread createWaiter(String threadName) {
		return new Thread(() -> awaitReady(), threadName);
	}

	private void run() {
		Thread waiter1 = createWaiter("Waiter #1");
		Thread waiter2 = createWaiter("Waiter #2");

		waiter1.start();
		waiter2.start();

		// let the threads get started
		try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		com.ibm.jvm.Dump.JavaDump();

		synchronized (this) {
			ready = true;
			notifyAll();
		}

		try {
			waiter1.join();
			waiter2.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

}
```
As you can see, the situation doesn't necessarily indicate deadlock. This is properly classified as an enhancement request (to, perhaps, show the thread currently responsible for advancing the initialization of a class).

**Comment by yathamravali** [comment] 2022-04-25 10:24
@keithc-ca Adding the details of the class advancing the initialisation really helps as @kgibm mentioned while opening the issue rather than showing `unowned`. Could notice that the thread doing initialization can be obtained from coredump using `jdmpview
` which I'll update in next comment.

For info: Hotspot also exhibits similar behaviour (deadlock is not detected & no owner details)

Following sample code indicates deadlock scenario. In order for the static block to exit, the new thread should complete its execution as join method is invoked. That new thread has to wait for StaticInitializer to be fully initialized before it can proceed, because it's trying to set the state field... and initialization is already in progress, so it waits. However, it's going to be waiting forever, because that initialization is waiting for that new thread to terminate (Classic deadlock)

```
public class StaticInitializer {

private static int state = 10;

static {
    Thread t1 = new Thread(new Runnable() {
        @Override
        public void run() {
            state = 11;
            System.out.println("Exit Thread");
        }
    });

    t1.start();

    try {
        t1.join();
    } catch (InterruptedException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }

    System.out.println("exiting static block");
}

public static void main(String...strings) {
    System.out.println(state);
}
}
```

Neither javacore nor jdmpview tool on coredump detected deadlock.
```
Javacore shows as below
0SECTION       LOCKS subcomponent dump routine
NULL           ===============================
NULL           
1LKPOOLINFO    Monitor pool info:
2LKPOOLTOTAL     Current total number of monitors: 2
NULL           
1LKMONPOOLDUMP Monitor Pool Dump (flat & inflated object-monitors):
2LKMONINUSE      sys_mon_t:0x00007FD2243F6B08 infl_mon_t: 0x00007FD2243F6B88:
3LKMONOBJECT       java/lang/Thread@0x00000000FFFC36F0: <unowned>
3LKNOTIFYQ            Waiting to be notified:
3LKWAITNOTIFY            "main" (J9VMThread:0x000000000100C700)
2LKMONINUSE      sys_mon_t:0x00007FD2243F6BB8 infl_mon_t: 0x00007FD2243F6C38:
3LKMONOBJECT       java/lang/J9VMInternals$ClassInitializationLock@0x00000000FFFC2EC0: <unowned>
3LKNOTIFYQ            Waiting to be notified:
3LKWAITNOTIFY            "Thread-5" (J9VMThread:0x000000000111FE00)
```
```
$/root/Java8SR6FP6/bin/jdmpview -core core.20220423.104326.18558.0001.dmp

> deadlock

  deadlocks for runtime 

	 no deadlocks detected
```

**Comment by yathamravali** [comment] 2022-04-25 10:49
```
> info lock
Object Locks in use...
java/lang/Thread@0xfffc36f0
	waiting thread id: 18559 name: main
java/lang/J9VMInternals$ClassInitializationLock@0xfffc2ec0
	waiting thread id: 18579 name: Thread-5
```

Looking into the thread monitor details of  java/lang/Thread@0xfffc36f0 shows that the owner is `Thread-5`
```
> !j9threadmonitor 0xfffc36f0     
J9ThreadMonitor at 0xfffc36f0 {
  Fields for J9ThreadMonitor:
	0x0: uintptr_t count = 0x01007DB101052408 (72195793217725448)
	0x8: struct J9Thread *volatile owner = !j9thread 0x000000000111FE00 <---- **Thread-5**
	0x10: struct J9Thread * waiting = !j9thread 0x0000000000000000
	0x18: uintptr_t flags = 0x0000000000000015 (21)
	0x20: uintptr_t userData = 0x0000000000000000 (0)
	0x28: struct J9ThreadMonitorTracing * tracing = !j9threadmonitortracing 0xFFF04650FFFC4278
	0x30: char * name = !j9x 0xFFF378A0FFFC4228<FAULT>
	0x38: uintptr_t pinCount = 0xFFFAD21000000000 (-1457883698954240)
	0x40: uintptr_t spinlockState = 0x00000000FFFC4288 (4294722184)
	0x48: uintptr_t spinCount1 = 0x0000000000000000 (0)
	0x50: uintptr_t spinCount2 = 0x0000000100000000 (4294967296)
	0x58: uintptr_t spinCount3 = 0x0000000000000005 (5)
	0x60: struct J9Thread * blocking = !j9thread 0x0000000000000000
	0x68: uintptr_t sampleCounter = 0x0000000000000000 (0)
	0x70: const struct J9ThreadCustomSpinOptions * customSpinOptions = !j9threadcustomspinoptions 0x0000000000000000
	0x78: volatile uintptr_t spinThreads = 0xFFFC37780103EB00 (-1064911354205440)
	0x80: J9OSMutex mutex = !j9x 0xfffc3770
	0xa8: struct J9Thread * notifyAllWaiting = !j9thread 0x0065007A0069006C

> !threads | grep -i "111FE00"
	!stack 0x0111fe00	!j9vmthread 0x0111fe00	!j9thread 0x7fd22437f5f0	tid 0x4893 (18579) // (Thread-5)
```

Now let's look for object lock java/lang/J9VMInternals$ClassInitializationLock@0xfffc2ec0

```
> !j9object 0xfffc2ec0
!J9Object 0x00000000FFFC2EC0 {
	struct J9Class* clazz = !j9class 0x1034A00 // java/lang/J9VMInternals$ClassInitializationLock
	Object flags = 0x00000008;
	I lockword = 0x01007111 (offset = 0) (java/lang/Object) <hidden>
	Ljava/lang/Class; theClass = !fj9object 0xe0015f00 (offset = 4) (java/lang/J9VMInternals$ClassInitializationLock)
}

> !fj9object 0xe0015f00
!J9Object 0x00000000E0015F00 {
	struct J9Class* clazz = !j9class 0x1039300 // java/lang/Class
	Object flags = 0x0000003A;
	I lockword = 0x00000000 (offset = 0) (java/lang/Object) <hidden>
	J vmRef = 0x000000000115FD00 (offset = 4) (java/lang/Class)
	Ljava/lang/ClassLoader; classLoader = !fj9object 0xfff378a0 (offset = 12) (java/lang/Class)
	Ljava/security/ProtectionDomain; protectionDomain = !fj9object 0xfffc2cc8 (offset = 16) (java/lang/Class)
	Ljava/lang/String; classNameString = !fj9object 0x0 (offset = 20) (java/lang/Class)
	Ljava/lang/String; fileNameString = !fj9object 0x0 (offset = 24) (java/lang/Class)
	Ljava/lang/Class$AnnotationVars; annotationVars = !fj9object 0x0 (offset = 28) (java/lang/Class)
	Ljava/lang/ClassValue$ClassValueMap; classValueMap = !fj9object 0x0 (offset = 32) (java/lang/Class)
	Ljava/lang/Class$EnumVars; enumVars = !fj9object 0x0 (offset = 36) (java/lang/Class)
	Ljava/lang/J9VMInternals$ClassInitializationLock; initializationLock = !fj9object 0xfffc2ec0 (offset = 40) (java/lang/Class)
	Ljava/lang/Object; methodHandleCache = !fj9object 0x0 (offset = 44) (java/lang/Class)
	Ljava/lang/Class$ClassRepositoryHolder; classRepoHolder = !fj9object 0x0 (offset = 48) (java/lang/Class)
	Ljava/lang/Class$AnnotationCache; annotationCache = !fj9object 0x0 (offset = 52) (java/lang/Class)
	[Ljava/lang/Class; cachedInterfaces = !fj9object 0x0 (offset = 56) (java/lang/Class)
	Ljava/lang/Class; cachedDeclaringClass = !fj9object 0x0 (offset = 60) (java/lang/Class)
	Ljava/lang/Class; cachedEnclosingClass = !fj9object 0x0 (offset = 64) (java/lang/Class)
	Ljava/lang/Class$ReflectCache; reflectCache = !fj9object 0xfffc3560 (offset = 68) (java/lang/Class)
}

Now take the vmRef and dump the class

> !j9class 0x000000000115FD00
J9Class at 0x115fd00 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
	0x8: struct J9ROMClass * romClass = !j9romclass 0x00007FD22444AB10
	0x10: struct J9Class ** superclasses = !j9x 0x0000000001160078
	0x18: UDATA classDepthAndFlags = 0x00000000000E0001 (917505)
	0x20: U32 classDepthWithFlags = 0x00000000 (0)
	0x24: U32 classFlags = 0x00000000 (0)
	0x28: struct J9ClassLoader * classLoader = !j9classloader 0x00007FD22408E668
	0x30: j9object_t classObject = !j9object 0x00000000E0015F00 // java/lang/Class
	0x38: volatile UDATA initializeStatus = 0x000000000100C700 (16828160) <-------- **main**
	0x40: struct J9Method * ramMethods = !j9method 0x000000000115FFF8 // StaticInitializer.<init>()V
	0x48: UDATA * ramStatics = !j9x 0x00000000011600A8
	0x50: struct J9Class * arrayClass = !j9class 0x0000000000000000
	0x58: UDATA totalInstanceSize = 0x0000000000000004 (4)
	0x60: struct J9ITable * lastITable = !j9itable 0x00007FD229F77790
	0x68: UDATA * instanceDescription = !j9x 0x0000000000000001
	0x70: UDATA * instanceLeafDescription = !j9x 0x0000000000000001
	0x78: UDATA instanceHotFieldDescription = 0x0000000000000000 (0)
	0x80: UDATA selfReferencingField1 = 0x0000000000000000 (0)
	0x88: UDATA selfReferencingField2 = 0x0000000000000000 (0)
	0x90: struct J9Method * initializerCache = !j9method 0x0000000000000000
	0x98: UDATA romableAotITable = 0x00007FD223978E80 (140540516994688)
	0xa0: UDATA packageID = 0x00007FD22408E668 (140540524422760)
	0xa8: struct J9Module * module = !j9module 0x0000000000000000
	0xb0: struct J9Class * subclassTraversalLink = !j9class 0x000000000115EE00 // [Ljava/security/Principal;
	0xb8: struct J9Class * subclassTraversalReverseLink = !j9class 0x000000000115F400 // sun/launcher/LauncherHelper$FXHelper
	0xc0: void ** iTable = !j9x 0x0000000000000000
	0xc8: UDATA castClassCache = 0x0000000000000000 (0)
	0xd0: void ** jniIDs = !j9x 0x00007FD224354D80
	0xd8: UDATA lockOffset = 0x0000000000000004 (4)
	0xe0: UDATA newInstanceCount = 0x0000000000000BB8 (3000)
	0xe8: IDATA backfillOffset = 0x0000000000000008 (8)
	0xf0: struct J9Class * replacedClass = !j9class 0x0000000000000000
	0xf8: UDATA finalizeLinkOffset = 0x0000000000000000 (0)
	0x100: struct J9Class * nextClassInSegment = !j9class 0x0000000000000000
	0x108: UDATA * ramConstantPool = !j9x 0x000000000115FEA0
	0x110: j9object_t * callSites = !j9x 0x0000000000000000
	0x118: j9object_t * methodTypes = !j9x 0x0000000000000000
	0x120: j9object_t * varHandleMethodTypes = !j9x 0x0000000000000000
	0x128: struct J9VMCustomSpinOptions * customSpinOption = !j9vmcustomspinoptions 0x0000000000000000
	0x130: struct J9Method ** staticSplitMethodTable = !j9x 0x0000000000000000
	0x138: struct J9Method ** specialSplitMethodTable = !j9x 0x0000000000000000
	0x140: struct J9JITExceptionTable * jitMetaDataList = !j9jitexceptiontable 0x0000000000000000
	0x148: struct J9Class * gcLink = !j9class 0x0000000000000000
	0x150: struct J9Class * hostClass = !j9class 0x000000000115FD00 // StaticInitializer
	0x158: struct J9FlattenedClassCache * flattenedClassCache = !j9flattenedclasscache 0x0000000000000000
}

I believe initializeStatus field points to the thread doing initialization which is main
> !threads | grep -i "100C700"
	!stack 0x0100c700	!j9vmthread 0x0100c700	!j9thread 0x7fd224007d80	tid 0x487f (18559) // (main)
```

**Comment by keithc-ca** [comment] 2022-04-25 17:29
Creating new threads in the static initializer of the main class is something neither OpenJ9 nor Hotspot support (without the deadlock you notice).

**Comment by BrijeshNekkare** [comment] 2022-04-26 10:27
1. Are there valid cases wherein a deadlock cannot be detected?
2. To show the thread currently responsible for advancing the initialization of a class, could the methodology showcased by Ravali be used to confirm the lock owner?

**Comment by keithc-ca** [comment] 2022-04-28 11:43
There are numerous ways an application can be deadlocked. Any involving resources not on the heap (e.g. the native class loader lock involved for static initializers) will not be detectable by jdmpview (which only considers synchronized objects in the heap).

**Closed** 2022-08-04 16:28 UTC
Labels: enhancement

**Comment by kgibm** [comment] 2022-08-08 14:45
Thanks for the fix. Just to highlight, this adds an "Initializing thread: $THREAD_NAME" section to help identify the deadlock.

**Comment by gacholio** [comment] 2022-08-08 15:36
This should probably be added to the doc.

**Comment by yathamravali** [comment] 2022-08-09 05:35
Created: https://github.com/eclipse-openj9/openj9-docs/issues/975
