### ISSUE TITLE
jdk19 crash vmState=0x00040000 Thread_interruptImpl

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15491] opened 2022-07-05 19:06 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_s390x_linux_OpenJDK19_testList_0/5
testSCCMLTests1_openj9_1
```
Testing: Test 36: LIR 1445.1 : Debug Area PrintStats Test : Create a test cache
Test start time: 2022/07/01 10:15:04 Coordinated Universal Time
Running command: "/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OpenJDK19_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests -version
Time spent starting: 1 milliseconds
***[TEST INFO 2022/07/01 10:25:04] ProcessKiller detected a timeout after 600000 milliseconds!***
INFO: Cannot find '/usr/bin/gdb' using 'gdb' from the path.
***[TEST INFO 2022/07/01 10:25:04] executing gdb -batch -x /tmp/debugger9385972149029267514.txt /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OpenJDK19_testList_0/openjdkbinary/j2sdk-image/bin/java 18983***
java.io.IOException: Cannot run program "gdb": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:615)
	at java.base/java.lang.Runtime.exec(Runtime.java:474)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:697)
	at Test$ProcessKiller.captureCoreForProcess(Test.java:646)
	at Test$ProcessKiller.run(Test.java:596)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 6 more
***[TEST INFO 2022/07/01 10:25:04] executing kill -ABRT 18983***
***[TEST INFO 2022/07/01 10:25:04] kill -ABRT signal sent***
***[TEST INFO 2022/07/01 10:30:04] ABRT timed out***
***[TEST INFO 2022/07/01 10:30:04] executing kill -9 18983***
***[TEST INFO 2022/07/01 10:30:04] kill -9 signal sent***
***[TEST INFO 2022/07/01 10:30:04] ProcessKiller destroy test process after timeout***
 [ERR] openjdk version "19-internal" 2022-09-20
 [ERR] OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDK19s390xlinuxOpenJDK19)
 [ERR] Eclipse OpenJ9 VM (build master-79f0b73fab3, JRE 19 Linux s390x-64-Bit Compressed References 20220701_7 (JIT enabled, AOT enabled)
 [ERR] OpenJ9   - 79f0b73fab3
 [ERR] OMR      - d018241d7b8
 [ERR] JCL      - 403c2088e23 based on jdk-19+29)
 [ERR] Unhandled exception
 [ERR] Type=Segmentation error vmState=0x00040000
 [ERR] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
 [ERR] Handler1=000003FFB1943620 Handler2=000003FFB1831778 InaccessibleAddress=0000000000000000
 [ERR] gpr0=000003FF00000002 gpr1=000003FFB230A0C0 gpr2=00000000000004A0 gpr3=000003FF00000000
 [ERR] gpr4=000003FFB178C610 gpr5=000000008C1D42E4 gpr6=000003FFB19198D2 gpr7=000003FFB05562B8
 [ERR] gpr8=00000000000004A0 gpr9=000003FFB1798360 gpr10=000003FFAC284298 gpr11=0000000000000000
 [ERR] gpr12=0000000000000050 gpr13=000003FFB1B0A394 gpr14=000003FFB178C61A gpr15=000003FFB167DC50
 [ERR] psw=000003FFB230A0C0 mask=0705200180000000 fpc=00080000 bea=000003FFB17845AC
 [ERR] fpr0 000000000000c010 (f: 49168.000000, d: 2.429222e-319)
 [ERR] fpr1 000003ffb167b650 (f: 2976364032.000000, d: 2.172272e-311)
 [ERR] fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] fpr3 0000000000000006 (f: 6.000000, d: 2.964394e-323)
 [ERR] fpr4 000003ff5545b70c (f: 1430632192.000000, d: 2.171509e-311)
 [ERR] fpr5 000003ffb1c5ba40 (f: 2982525440.000000, d: 2.172275e-311)
 [ERR] fpr6 0000000000100000 (f: 1048576.000000, d: 5.180654e-318)
 [ERR] fpr7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] fpr8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] fpr9 0000000000f1af78 (f: 15839096.000000, d: 7.825553e-317)
 [ERR] fpr10 000003ffb163f000 (f: 2976116736.000000, d: 2.172272e-311)
 [ERR] fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] fpr12 0005e2bba8e9a931 (f: 2833885440.000000, d: 8.185040e-309)
 [ERR] fpr13 000003ff842f99b8 (f: 2217712128.000000, d: 2.171897e-311)
 [ERR] fpr14 000003ff840032d0 (f: 2214605568.000000, d: 2.171896e-311)
 [ERR] fpr15 000003ff843c1678 (f: 2218530304.000000, d: 2.171898e-311)
 [ERR] Module=/lib/s390x-linux-gnu/libpthread.so.0
 [ERR] Module_base_address=000003FFB2300000 Symbol=pthread_mutex_lock
 [ERR] Symbol_address=000003FFB230A0C0
 [ERR] Target=2_90_20220701_7 (Linux 4.15.0-171-generic)
 [ERR] CPU=s390x (4 logical CPUs) (0x1f70fd000 RAM)
 [ERR] ----------- Stack Backtrace -----------
 [ERR] pthread_mutex_lock+0x0 (0x000003FFB230A0C0 [libpthread.so.0+0xa0c0])
 [ERR] omrthread_interrupt+0x62 (0x000003FFB178C61A [libj9thr29.so+0xc61a])
 [ERR] Java_java_lang_Thread_interruptImpl+0x84 (0x000003FFB055633C [libjclse29.so+0x5633c])
 [ERR] ffi_call_SYSV+0x54 (0x000003FFB1B0A394 [libj9vm29.so+0x20a394])
 [ERR] ffi_call+0xa2 (0x000003FFB1B09DDA [libj9vm29.so+0x209dda])
 [ERR] _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x14c44 (0x000003FFB19B63FC [libj9vm29.so+0xb63fc])
 [ERR] bytecodeLoopCompressed+0xce (0x000003FFB19A17A6 [libj9vm29.so+0xa17a6])
 [ERR] c_cInterpreter+0x64 (0x000003FFB1A8601C [libj9vm29.so+0x18601c])
 [ERR] ---------------------------------------
```

@tajila fyi

**Comment by pshipton** [comment] 2022-09-30 01:33
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/3
J9vmTest_4

Test hung creating javacore. There is a javacore file in the artifacts, which stops in the "THREADS subcomponent" section.
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/3/functional_test_output.tar.gz

```
15:30:10  command: /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin/java  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m -verbose:sizes -Xlp:codecache:pagesize=4M,pagesize=2M   -classpath /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/../TKG/lib/asm-all.jar  j9vm.test.xlpcodecache.XlpCodeCacheOptionsTest 
15:30:10  
15:30:10  JVMJITM034I Large page size 2M is not a supported page size for the JIT codecache; using 4K instead
15:30:10    -Xmca32K        RAM class segment increment
15:30:10    -Xmco128K       ROM class segment increment
15:30:10    -Xmcrs200M      compressed references metadata initial size
15:30:10    -Xmns16M        initial new space size
15:30:10    -Xmnx48M        maximum new space size
15:30:10    -Xms64M         initial memory size
15:30:10    -Xmos64M        initial old space size
15:30:10    -Xmox64M        maximum old space size
15:30:10    -Xmx64M         memory maximum
15:30:10    -Xlp:objectheap:pagesize=4K	 large page size
15:30:10                    available large page sizes:
15:30:10                    4K
15:30:10    -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
15:30:10                    available large page sizes for JIT code cache:
15:30:10                    4K
15:30:10    -Xmso256K       operating system thread stack size
15:30:10    -Xiss2K         java thread stack initial size
15:30:10    -Xssi16K        java thread stack increment
15:30:10    -Xss1M          java thread stack maximum size
15:30:10    -XX:SharedCacheHardLimit=300M shared class cache size
15:30:10    -Xscmx64M       shared class cache soft max size
15:30:10    -Xscdmx24544K   reserved shared class cache space for class debug attributes
15:30:10    -Xscminaot0K    min reserved shared class cache space for AOT
15:30:10    -Xscmaxaot282300K max allowed shared class cache space for AOT
15:30:10    -Xscminjitdata0K min reserved shared class cache space for JIT data
15:30:10    -Xscmaxjitdata282300K max allowed shared class cache space for JIT data
15:30:10  A message from XlpCodeCacheOptionsTest class
15:30:10  Unhandled exception
15:30:10  Type=Segmentation error vmState=0x00040000
15:30:10  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=80057ed5 Signal_Code=00000001
15:30:10  Handler1=000003FF7E3444B0 Handler2=000003FF7E231A50 InaccessibleAddress=0000000000000000
15:30:10  gpr0=000003FF00000002 gpr1=000003FF7EC0A1E0 gpr2=00000000000004A0 gpr3=0000000000000000
15:30:10  gpr4=000003FF7E18C610 gpr5=0000000000000001 gpr6=0000000003F97890 gpr7=000003FF7C756700
15:30:10  gpr8=00000000000004A0 gpr9=000003FF7E198360 gpr10=000003FF78511FE8 gpr11=0000000000000000
15:30:10  gpr12=0000000000000050 gpr13=00000000000004A0 gpr14=000003FF7E18C61A gpr15=000003FF7DFFDC70
15:30:10  psw=000003FF7EC0A1EA mask=0705200180000000 fpc=0008fe00 bea=000003FF7E1845AC
15:30:10  fpr0 000000000000c010 (f: 49168.000000, d: 2.429222e-319)
15:30:10  fpr1 3e638f4400000000 (f: 0.000000, d: 3.643265e-08)
15:30:10  fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:30:10  fpr3 3bac039700000000 (f: 0.000000, d: 2.966100e-21)
15:30:10  fpr4 000003ff2145b70c (f: 558216960.000000, d: 2.171077e-311)
15:30:10  fpr5 3e9249cd00000000 (f: 0.000000, d: 2.725167e-07)
15:30:10  fpr6 0000000000100000 (f: 1048576.000000, d: 5.180654e-318)
15:30:10  fpr7 3e3a343700000000 (f: 0.000000, d: 6.101086e-09)
15:30:10  fpr8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:30:10  fpr9 00000000001385c8 (f: 1279432.000000, d: 6.321234e-318)
15:30:10  fpr10 000003ff78014200 (f: 2013348352.000000, d: 2.171796e-311)
15:30:10  fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:30:10  fpr12 0005e9d5e7d34687 (f: 3889383168.000000, d: 8.223623e-309)
15:30:10  fpr13 000003ff9416cdf8 (f: 2484522496.000000, d: 2.172029e-311)
15:30:10  fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:30:10  fpr15 000003ff942db358 (f: 2486022912.000000, d: 2.172030e-311)
15:30:10  Module=/lib64/libpthread.so.0
15:30:10  Module_base_address=000003FF7EC00000 Symbol=pthread_mutex_lock
15:30:10  Symbol_address=000003FF7EC0A1E0
15:30:10  Target=2_90_20220929_3 (Linux 3.10.0-1160.71.1.el7.s390x)
15:30:10  CPU=s390x (4 logical CPUs) (0x1ec1b4000 RAM)
15:30:10  ----------- Stack Backtrace -----------
15:30:10  pthread_mutex_lock+0xa (0x000003FF7EC0A1EA [libpthread.so.0+0xa1ea])
15:30:10  omrthread_interrupt+0x62 (0x000003FF7E18C61A [libj9thr29.so+0xc61a])
15:30:10  Java_java_lang_Thread_interruptImpl+0x84 (0x000003FF7C756784 [libjclse29.so+0x56784])
15:30:10  ffi_call_SYSV+0x54 (0x000003FF7E515F14 [libj9vm29.so+0x215f14])
15:30:10  ffi_call+0xa2 (0x000003FF7E51595A [libj9vm29.so+0x21595a])
15:30:10  _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x154c6 (0x000003FF7E3BCF46 [libj9vm29.so+0xbcf46])
15:30:10  bytecodeLoopCompressed+0xce (0x000003FF7E3A7A6E [libj9vm29.so+0xa7a6e])
15:30:10  c_cInterpreter+0x64 (0x000003FF7E4908A4 [libj9vm29.so+0x1908a4])
15:30:10  ---------------------------------------
15:30:10  JVMDUMP039I Processing dump event "gpf", detail "" at 2022/09/29 15:30:10 - please wait.
15:30:10  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/output_16644778967373/J9vmTest_4/core.20220929.153010.4431.0001.dmp' in response to an event
15:30:22  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/output_16644778967373/J9vmTest_4/core.20220929.153010.4431.0001.dmp
15:30:22  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.functional_s390x_linux_OMR_testList_0/aqa-tests/TKG/output_16644778967373/J9vmTest_4/javacore.20220929.153010.4431.0002.txt' in response to an event
```

**Comment by tajila** [comment] 2022-10-19 19:42
I think this issue is caused due to a NULL `eetop`

**Comment by tajila** [comment] 2022-10-19 19:42
```
> !j9object 0x0000000003F97890
!J9Object 0x0000000003F97890 {
	struct J9Class* clazz = !j9class 0xA8B0800 // openj9/internal/tools/attach/target/AttachHandler
	Object flags = 0x00000008;
	I lockword = 0x00000000 (offset = 0) (java/lang/Object) <hidden>
	J eetop = 0x0000000000000000 (offset = 4) (java/lang/Thread)
	J tid = 0x0000000000000012 (offset = 12) (java/lang/Thread)
	Ljava/lang/String; name = !fj9object 0x3fa5668 (offset = 36) (java/lang/Thread)
	Z interrupted = 0x00000001 (offset = 92) (java/lang/Thread)
```

**Comment by JasonFengJ9** [comment] 2022-10-19 19:55
Related to https://github.com/eclipse-openj9/openj9/issues/16121 and internal RTC workitem 148107

**Comment by dmitripivkine** [comment] 2022-10-19 20:25
> The thread was interrupted at shutdown so there may be a timing issue.
> 
> @dmitripivkine Does the GC ever clear the eetop/threadref field in java/lang/Thread ?

Not I am aware about. Can it be an indirect call when threads are registered / unregistered in JVM?

**Comment by tajila** [comment] 2022-10-19 22:18
Turns out the JCL sets this to NULL on thread shutdown

**Comment by tajila** [comment] 2022-10-20 14:38
When threadCleanup is called, the eetop field is cleared. So I guess the question is how does another thread have access to the thread object if it is being cleaned up

**Comment by tajila** [comment] 2022-10-20 14:47
@gacholio perhaps `deallocateVMThread` needs to hold exclusive VMAccess ?

**Comment by JasonFengJ9** [comment] 2022-10-20 15:02
> Do we know how reproduceable this is?

It occurred quite a few times at Windows platform [RTC 148107](https://jazz103.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/148107), appears not test specific.
Launched [a 50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28848)

**Comment by gacholio** [comment] 2022-10-20 15:19
> @gacholio perhaps `deallocateVMThread` needs to hold exclusive VMAccess ?

That would be a sledgehammer solution to an essentially irrelevant issue - who even uses interrupt at this point? Surely this can be fixed by making interrupt a bit smarter about thread state.

I've never seen this `eetop` field.

**Comment by gacholio** [comment] 2022-10-20 15:36
This might be solved simply by holding the `vmThreadListMutex` in interrupt to prevent threads dying (it prevents `deallocateVMThread` from running, but does not stop any java cleanup).

The native is called while holding the target Thread lock, so I'm not sure where the hole is. Is the native assuming the Thread is being held alive by the java code? I don't think the lock is sufficient for that.

**Comment by JasonFengJ9** [comment] 2022-10-20 18:01
> Launched [a 50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28851)

Reproduced 3 times, [failure-1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/1374/testReport) [failure-2](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/1817/testReport) [failure-3](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_3/1441/testReport)

**Comment by gacholio** [comment] 2022-10-20 18:40
At a glance, the Thread code (not ours) is doing the right locking, but I'm betting the timing hole is due to not using our version of Thread somewhere.

**Comment by tajila** [comment] 2022-10-20 20:01
@JasonFengJ9 has this been reproduced on linuxx86?

**Comment by gacholio** [comment] 2022-10-20 20:04
There may be other natives affected by this - have suspend and resume been completely removed?

**Comment by gacholio** [comment] 2022-10-20 20:20
Thread.exit is zeroing the vmThread under lock:
```
   64 aload0getfield 
   65 getfield 17 java/lang/Thread.interruptLock Ljava/lang/Object;
   68 dup 
   69 astore2 
   70 monitorenter 
   71 aload0 
   72 lconst0 
   73 putfield 120 java/lang/Thread.eetop J
   76 aload2 
   77 monitorexit 
```

**Comment by JasonFengJ9** [comment] 2022-10-20 21:18
> has this been reproduced on linuxx86?

No, this issue occurred at `s390x_linux`, [RTC 148107](https://jazz103.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/148107) is Windows platform, and https://github.com/eclipse-openj9/openj9/issues/16121 was AIX.

Launched [200x internal grinder on x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28873).

**Comment by tajila** [comment] 2022-10-20 21:55
> There may be other natives affected by this - have suspend and resume been completely removed?

Still valid for non-VThreads

**Comment by gacholio** [comment] 2022-10-20 21:56
Are we using a modified Thread? May be worth comparing it with the working one from J9 to see where we might be missing a lock.

**Comment by tajila** [comment] 2022-10-20 22:00
It looks like we do an extra interrupt

https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/lang/Thread.java#L1768

not sure if thats needed

**Comment by tajila** [comment] 2022-10-20 22:00
The second interupt is done without the lock

**Comment by JasonFengJ9** [comment] 2022-10-21 12:01
> Launched [200x internal grinder on x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28873).

The grinder passed.

**Comment by tajila** [comment] 2022-10-24 14:29
@JasonFengJ9 Does this pass with the latest jdk19 change?

**Closed** 2022-10-24 15:22 UTC
Labels: test failure, segfault, jdk19
