### ISSUE TITLE
MathLoadTest_autosimd_special_5m_18 ASSERTION FAILED gc_vlhgc/ReclaimDelegate.cpp:413: ((false && (avgCopyForwardRate > 0.0)))

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14707] opened 2022-03-14 15:17 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal_testList_1/30 - [cent7-ppcle-5](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-5)
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal_testList_4/29 - [cent7-ppcle-3](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-3)
MathLoadTest_autosimd_special_5m_18 `-XX:+UseCompressedOops -Xgcpolicy:balanced -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_special.system_ppc64le_linux_Personal_testList_4/29/system_test_output.tar.gz
```
MLT stderr 17:14:43.465 0x1c0c00    j9mm.107    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK11_ppc64le_linux_Personal/openj9/runtime/gc_vlhgc/ReclaimDelegate.cpp:413: ((false && (avgCopyForwardRate > 0.0)))
```

@dmitripivkine

**Comment by dmitripivkine** [comment] 2022-03-14 16:58
> There is a hang at system core generation, so core has not been preserved. Attempting to reproduce in the grinder https://openj9-jenkins.osuosl.org/job/Grinder/701/

Passed. Another one https://openj9-jenkins.osuosl.org/job/Grinder/702/

**Comment by dmitripivkine** [comment] 2022-03-14 20:58
> Passed. Another one https://openj9-jenkins.osuosl.org/job/Grinder/702/

There are 4 of 50 reproduction rate. Actually all failures occur at the same machine https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-4 (4 of 10) build https://openj9-jenkins.osuosl.org/job/Grinder_iteration_3/32/

Unfortunately none of failures produce system core - every time process has been cancelled before generation is complete (5 min or so). I looked to source code and there is nothing obvious wrong with `avgCopyForwardRate` calculation. I suspect memory corruption or kind of machine failure.

@llxia Do you have any suggestions how I can get system core? Can timeout be uncreased temporary (or can it be configured somehow)?

**Comment by dmitripivkine** [comment] 2022-03-14 21:06
looks like failure seen at cent7-ppcle machines only

**Comment by dmitripivkine** [comment] 2022-03-16 19:48
another grinder with `-Xtrace:print=j9mm.568` aimed to get `Trc_MM_SchedulingDelegate_copyForwardCompleted_efficiency` output  https://openj9-jenkins.osuosl.org/job/Grinder/716/

**Comment by dmitripivkine** [comment] 2022-03-16 20:59
> another grinder with `-Xtrace:print=j9mm.568` aimed to get `Trc_MM_SchedulingDelegate_copyForwardCompleted_efficiency` output https://openj9-jenkins.osuosl.org/job/Grinder/716/

There is distinct pattern in Extended Tap Results https://openj9-jenkins.osuosl.org/job/Grinder/716/tapResults/
Looks like PGC stops do Copy Forward (performing Mark Sweep only) and average copy rate drops to 0 eventually

**Comment by dmitripivkine** [comment] 2022-03-25 13:45
should be fixed in https://github.com/eclipse-openj9/openj9/pull/14771

**Closed by dmitripivkine** 2022-03-25 13:45 UTC
Labels: comp:gc, test failure
