### ISSUE TITLE
OpenJ9-11 Incorrect array optimizations

### ISSUE THREAD

**Issue by TemporaryRepos** [eclipse-openj9/openj9#19014] opened 2024-02-26 07:13 UTC
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Linux Ubuntu20.04

Java -version output under Linux

```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b06)
Eclipse OpenJ9 VM (build openj9-0.43.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240131_861 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 0fa9d9c532 based on jdk8u402-b06)
```

```
openjdk version "11.0.22" 2024-01-16
IBM Semeru Runtime Open Edition 11.0.22.0 (build 11.0.22+7)
Eclipse OpenJ9 VM 11.0.22.0 (build openj9-0.43.0, JRE 11 Linux amd64-64-Bit Compressed References 20240131_966 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 7876cac747 based on jdk-11.0.22+7)
```

```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)
Eclipse OpenJ9 VM 17.0.10.0 (build openj9-0.43.0, JRE 17 Linux amd64-64-Bit Compressed References 20240116_670 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 2aad089841f based on jdk-17.0.10+7)
```

## Problem summary

This test case mainly contains a 10000 times loop in the main function and a series of array operations inside the loop, which should not throw any Exception under normal circumstances, e.g. OpenJ9-8 and Hotspot can be executed correctly, but OpenJ9-11 and OpenJ9-17 will throw an ArrayIndexOutOfBoundsException. In addition to this, we also tried setting the parameter -Xint, which also does not throw an Exception.

```java
public class TestArrayCopy {
    public TestArrayCopy() {
    }

    public static void main(String[] var0) {
        int var1 = Integer.MIN_VALUE;

        for(int var6 = 0; var6 < 1000000; ++var6) {
            int var3 = -1;
            float[] var4 = new float[100];
            float var5 = 1.0F;
            int var2;
            if (var1 * 2 < var4.length) {
                var4[var1 * 2] = var4[var1 * 2];
                var2 = var1 + 1;
            }

            while(var3 < 10) {
                ++var3;
            }

            int[] var10;
            int[] var10000 = var10 = new int[20];
            System.arraycopy(var10000, var3, var10, var3, 1);
            var2 = var1 * var3;
            boolean var9 = false;
            System.arraycopy(var10000, var2, var10, var2, 1);
        }

        short[] var8 = new short[0];
        boolean var7 = false;
    }
}

```
Steps to Reproduce
```
java-11/bin/java compiler.c1.TestArrayCopy
```
Expected Result
```
nothing
```
Actual Result
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at compiler.c1.TestArrayCopy.main(TestArrayCopy.java)
```
## Attachment
[202402261500.zip](https://github.com/eclipse-openj9/openj9/files/14400871/202402261500.zip)

**Comment by pshipton** [comment] 2024-02-26 15:26
@hzongaro fyi. I tagged 0.44 but pls move it forward if that is not appropriate.

**Comment by hzongaro** [comment] 2024-02-26 22:10
> e.g. OpenJ9-8 and Hotspot can be executed correctly, but OpenJ9-11 and OpenJ9-17 will throw an ArrayIndexOutOfBoundsException.

I was able to reproduce the ArrayIndexOutOfBoundsException with a JDK 8 build of OpenJ9 as well.  I can reproduce the failure using lastOptIndex=47 but not lastOptIndex=46.  This appears to be a problem with Tree Simplification.

```
./openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -Xjit:limit={TestArrayCopy.main*},lastOptIndex=46,log=testarraycopy.main.idx46.log,optDetails TestArrayCopy
./openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -Xjit:limit={TestArrayCopy.main*},lastOptIndex=47,log=testarraycopy.main.idx47.log,optDetails TestArrayCopy
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at TestArrayCopy.main(TestArrayCopy.java:14)
```

I'm going to move this out of 0.45.  The test involves an array bound check for an assignment that shouldn't be executed because of an overflow involving `Integer.MIN_VALUE * 2`, so it's a bit of an edge case.

**Comment by hzongaro** [comment] 2024-02-26 22:20
@nbhuiyan, may I ask you to look at this for the 0.45 release?

**Comment by nbhuiyan** [comment] 2024-05-16 15:42
There is a duplicate issue #19139 opened where the investigation and discussions will continue. Therefore, this issue can be closed.

**Comment by hzongaro** [comment] 2024-05-16 17:44
Duplicate of #19139

**Closed** 2024-05-16 17:44 UTC
Labels: comp:jit, userRaised
