### ISSUE TITLE
verbosegc_finalizers.Mode553 crash Inside compiled method: java/lang/invoke/MethodHandleInfoImpl.getReferenceKind()I

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18373] opened 2023-10-30 17:18 UTC
[Internal test](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=70832127)
[Linux S390 64bit Compressed Pointers] 80 VM_Sanity.trace.verbosegc_finalizers.Mode553
lnxec409 - FYI https://github.ibm.com/runtimes/infrastructure/issues/8551, this machine has been disabled

Artifacts attached to the job, including a core and jitdump.

50x grinder passed (but lnxec409 was disabled).

```
1TISIGINFO     Dump Event "gpf" (00002000) received
1TIDATETIMEUTC Date: 2023/10/30 at 16:53:52:352 (UTC)
1TIDATETIME    Date: 2023/10/30 at 09:53:52:352
1TITIMEZONE    Timezone: UTC-7 (PDT)
1TINANOTIME    System nanotime: 1698684832349010838
1TIFILENAME    Javacore filename:    /tmp/bld_59921/trace.verbosegcpendingfinalizers/70832127/lnxec409-trace-m553-20231030-095206/vgc_finalizers/vgc_check-0/junit/javacore.20231030.095350.19238.0003.txt
1TIREQFLAGS    Request Flags: 0x41 (exclusive+preempt)
1TIPREPSTATE   Prep State: 0x80 (trace_disabled)
1TIPREPINFO    Exclusive VM access not taken: data may not be consistent across javacore sections
NULL           ------------------------------------------------------------------------
0SECTION       GPINFO subcomponent dump routine
NULL           ================================
2XHOSLEVEL     OS Level         : Linux 3.10.0-1160.88.1.el7.s390x
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : s390x
3XHNUMCPUS       How Many       : 4
3XHNUMASUP       NUMA is either not supported or has been disabled by user
NULL
1XHEXCPCODE    J9Generic_Signal_Number: 00000048
1XHEXCPCODE    Signal_Number: 00000004
1XHEXCPCODE    Error_Value: 00000000
1XHEXCPCODE    Signal_Code: 00000001
1XHEXCPCODE    Handler1: 000003FF8F3E48E0
1XHEXCPCODE    Handler2: 000003FF8F12CD38
NULL
NULL
1XHREGISTERS   Registers:
2XHREGISTER      gpr0: 0000000000000016
2XHREGISTER      gpr1: 0000000000000000
2XHREGISTER      gpr2: 000000000000000E
2XHREGISTER      gpr3: 0000000000068000
2XHREGISTER      gpr4: 000003FF707909AC
2XHREGISTER      gpr5: 000003FF886DE998
2XHREGISTER      gpr6: 0000000000000000
2XHREGISTER      gpr7: 0000000000002502
2XHREGISTER      gpr8: 000003FF8EC2C208
2XHREGISTER      gpr9: 000003FF881097F0
2XHREGISTER      gpr10: 00096A0000000000
2XHREGISTER      gpr11: 000003FF8E9BACF0
2XHREGISTER      gpr12: 000003FF8ED94174
2XHREGISTER      gpr13: 0000000000068000
2XHREGISTER      gpr14: 0000000000000000
2XHREGISTER      gpr15: 000003FF8FDFA550
2XHREGISTER      fpr0: 4140000000000000
2XHREGISTER      fpr1: 4140000000000000
2XHREGISTER      fpr2: 4E80000000000000
2XHREGISTER      fpr3: 4140000000000000
2XHREGISTER      fpr4: BCE1CE7D00C000D6
2XHREGISTER      fpr5: 3E924925A000C000
2XHREGISTER      fpr6: 3ECCCCCD00000000
2XHREGISTER      fpr7: 3E3A332500000000
2XHREGISTER      fpr8: 0000000092227200
2XHREGISTER      fpr9: 0000000000000000
2XHREGISTER      fpr10: 0000000000000000
2XHREGISTER      fpr11: 0000000000000000
2XHREGISTER      fpr12: 0000000000000000
2XHREGISTER      fpr13: 0000000000000000
2XHREGISTER      fpr14: 0000000000000000
2XHREGISTER      fpr15: 0000000000000000
2XHREGISTER      psw: 000003FF707909B4
2XHREGISTER      mask: 0705100180000000
2XHREGISTER      fpc: 0008FE00
2XHREGISTER      bea: 000003FF8F426638
1XHEXCPMODULE  Inside compiled method: java/lang/invoke/MethodHandleInfoImpl.getReferenceKind()I
NULL
1XHFLAGS       VM flags:0000000000000000
NULL
```

**Comment by tajila** [comment] 2023-11-06 13:40
FYI @hzongaro

**Comment by hzongaro** [comment] 2023-11-07 17:17
Rahil @r30shah, may I ask you to have someone on your team triage this.  Looking at the code where the GPF happens, it looks like an `ETND` instruction - but maybe I'm misreading, since I don't think that should result in a GPF.

**Comment by r30shah** [comment] 2023-11-07 18:37
Thanks @hzongaro , 

@VermaSh  Most likely this is the same issue we had in past which is machine specific. Can you verify that. If it is the same issue, I think we can close this one as we already have an issue opened for that. 
https://github.com/eclipse-openj9/openj9/issues/9876

**Comment by hzongaro** [comment] 2023-11-16 21:48
Duplicate of #9876

**Closed** 2023-11-16 21:48 UTC
Labels: comp:jit, userRaised, segfault
