### ISSUE TITLE
Assertion failed OMRILOps.hpp:198: isVectorOpCode() - getVectorResultDataType() can only be called on vector opcode

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15074] opened 2022-05-17 13:12 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR/115
No diagnostic artifacts for this one, see the other occurrences below.
```
08:38:32  compile:
08:38:32       [echo] Ant version is Apache Ant(TM) version 1.9.9 compiled on February 2 2017
08:38:32       [echo] ============COMPILER SETTINGS============
08:38:32       [echo] ===fork:                         yes
08:38:32       [echo] ===debug:                        on
08:38:32      [javac] Compiling 27 source files to /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR/aqa-tests/TKG/bin
08:38:33      [javac] Assertion failed at /home/jenkins/workspace/Build_JDK17_ppc64_aix_OMR/omr/compiler/il/OMRILOps.hpp:198: isVectorOpCode()
08:38:33      [javac] VMState: 0x000551ff
08:38:33      [javac] 	getVectorResultDataType() can only be called on vector opcode
08:38:33      [javac] 
08:38:33      [javac] compiling java/lang/ClassLoader.defineClass(Ljava/lang/String;Ljava/nio/ByteBuffer;Ljava/security/ProtectionDomain;)Ljava/lang/Class; at level: very-hot (profiling)
08:38:33      [javac] Unhandled exception
08:38:33      [javac] Type=Segmentation error vmState=0x000551ff
08:38:33      [javac] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
08:38:33      [javac] Handler1=09001000A0CF0E40 Handler2=09001000A0B99EC8
08:38:33      [javac] R0=0000000000000000 R1=000001002163BEF0 R2=08001000A01D8DE8 R3=000001002163BF60
08:38:33      [javac] R4=7CC802A6F8010010 R5=7CC802A6F8010010 R6=08001000A0015FC8 R7=0000000000260000
08:38:33      [javac] R8=0000000000000000 R9=000000002F436C61 R10=0000000000000004 R11=000001002164C2A8
08:38:33      [javac] R12=000000002220444B R13=0000010021657800 R14=000001002163FA30 R15=000001002163F908
08:38:33      [javac] R16=000001002163F90C R17=0000000000000080 R18=000001002163F910 R19=000001002163DD87
08:38:33      [javac] R20=000001002164B528 R21=09001000A0B99EC8 R22=09001000A0B9BD40 R23=0000000000000018
08:38:33      [javac] R24=0000000000000018 R25=00000100100BCED0 R26=0000000000000000 R27=000000000000000B
08:38:33      [javac] R28=000001002164C248 R29=08001000A01DF5C8 R30=0000000030012C00 R31=000001002163BFA0
08:38:33      [javac] IAR=09000000051767AC LR=0900000005176218 MSR=A00000000000D032 CTR=0000000000000000
08:38:33      [javac] CR=2420444000000001 FPSCR=0000000000000000 XER=0000000100000000
08:38:33      [javac] FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR1 4530000000000000 (f: 0.000000, d: 1.934281e+25)
08:38:33      [javac] FPR2 4330000000000000 (f: 0.000000, d: 4.503600e+15)
08:38:33      [javac] FPR3 40a8000000000000 (f: 0.000000, d: 3.072000e+03)
08:38:33      [javac] FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR5 000000000000005c (f: 92.000000, d: 4.545404e-322)
08:38:33      [javac] FPR6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR7 412e848000000000 (f: 0.000000, d: 1.000000e+06)
08:38:33      [javac] FPR8 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
08:38:33      [javac] FPR9 4530000000000000 (f: 0.000000, d: 1.934281e+25)
08:38:33      [javac] FPR10 412e848000000000 (f: 0.000000, d: 1.000000e+06)
08:38:33      [javac] FPR11 43300000000f4240 (f: 1000000.000000, d: 4.503600e+15)
08:38:33      [javac] FPR12 4530000000000000 (f: 0.000000, d: 1.934281e+25)
08:38:33      [javac] FPR13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:33      [javac] Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so
08:38:33      [javac] Module_base_address=0900000004385000
08:38:33      [javac] 
08:38:33      [javac] Method_being_compiled=java/lang/ClassLoader.defineClass(Ljava/lang/String;Ljava/nio/ByteBuffer;Ljava/security/ProtectionDomain;)Ljava/lang/Class;
08:38:33      [javac] Target=2_90_20220517_128 (AIX 7.2)
08:38:33      [javac] CPU=ppc64 (16 logical CPUs) (0x780000000 RAM)
08:38:33      [javac] ----------- Stack Backtrace -----------
08:38:36      [javac] Unhandled exception
08:38:36      [javac] Type=Segmentation error vmState=0x00000000
08:38:36      [javac] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
08:38:36      [javac] Handler1=09001000A0CF0E40 Handler2=09001000A0B99EC8
08:38:36      [javac] JVMPORT001E 
08:38:36      [javac] R0=0000000000000001 R1=00000100100A9780 R2=09001000A0CF49E0 R3=0000000030010700
08:38:36      [javac] R4=00000000000BABE0 R5=0000000000000005 R6=0000010010129310 R7=000000000005D5F0
08:38:36      [javac] R8=0900000006778648 R9=000000001413017D R10=0000000000000000 R11=09000000040EAF68
08:38:36      [javac] R12=000000005IAR=0900000003E8BD94 LR=0900000003E9B344 MSR=A00000000200D032 CTR=0900000000590694
08:38:36      [javac] CR=53949350E00FFFFF FPSCR=8202000000000000 XER=E00FFFFF82020000
08:38:36      [javac] JVMPORT001E 
08:38:36      [javac] FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:36      [javac] FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
08:38:36      [javac] FPR2 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
08:38:36      [javac] FPR3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
08:38:36      [javac] FPR4 0000000000000000 (f: 0.000000, d: 0.0Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_ppc64_aix_OMR/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
08:38:36      [javac] Module_base_address=0900000003E45000
08:38:36      [javac] Target=2_90_20220517_128 (AIX 7.2)
08:38:36      [javac] CPU=ppc64 (16 logical CPUs) (0x780000000 RAM)
08:38:36      [javac] ----------- Stack Backtrace -----------
08:38:36      [javac] ---------------------------------------
08:38:36      [javac] JVMDUMP039I 
08:38:36      [javac] JVMDUMP013I 
```

Also:
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_0/221
- diagnostics https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_0/221/functional_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_1/221/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_OMR_testList_0/226/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_OMR_testList_1/226/
and more https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/274/

This is blocking OMR acceptance. 
https://github.com/eclipse-openj9/openj9-omr/compare/c945d253d4...26a204282e0
@gita-omr @midronij I suspect https://github.com/eclipse/omr/pull/6489

**Comment by midronij** [comment] 2022-05-17 16:05
Looks like this was just caused by dumb mistake that occurred while I was resolving some merge conflicts. The fix is here: https://github.com/eclipse/omr/pull/6519

**Comment by midronij** [comment] 2022-05-17 16:24
@knn-k @jdmpapin when you have a chance could you please review and merge? Thanks!

**Comment by pshipton** [comment] 2022-05-18 11:24
@midronij this is not fixed. See the failures in https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/276/
Example https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_0/223/

**Comment by midronij** [comment] 2022-05-18 14:54
My bad, looks like I missed part of the problem. https://github.com/eclipse/omr/pull/6522 should fully fix it.

**Closed** 2022-05-18 15:29 UTC
Labels: comp:jit, blocker
