### ISSUE TITLE
memory not released by GC as expected

### ISSUE THREAD

**Issue by srinayak666** [eclipse-openj9/openj9#11602] opened 2021-01-08 03:42 UTC
Below are the details about issue with JRE 1.8.0_275 build.
-GC is not executing as expected.

**Platform:** Mac OS X (mojave, catalina etc)

**JRE-1**:
openjdk version "1.8.0_275"	
OpenJDK Runtime Environment (build 1.8.0_275-b01)	
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Mac OS X amd64-64-Bit 20201112_584 (JIT enabled, AOT enabled)	
OpenJ9   - 0394ef754	
OMR      - 582366ae5	
JCL      - b52d2ff7ee based on jdk8u275-b01)	

**JRE-2**:
java version "1.8.0_181"	
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_181-b13 25_Jul_2018_11_11 Mac OS X x64(SR5 FP20))	
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)	
IBM Java ORB build orb80-20180617.00	
XML build XL TXE Java 1.0.60	
XML build IBM JAXP 1.6.1	
XML build XML4J 4.5.30	

gcpolicy: concurrentScavenge
(tried with default gencon too)

**Problem:**
with JRE-1 which we use with our application. 
-GC is not executing a expected.
-There is a significant increase in memory even application is idle.
-performing tests causes increase in memory - but not released as expected.

when using JRE-2 shows significant advantage compared to JRE-1 with our application.

**Analysis:** 
**_Testing scenario: 1_**
**JRE-1**:
starting our application in consumes: 292.0MB
leave application idle for 1 hour: 28.9MB CONSUMED
After testing and final memory will be: 693.5MB 

**_Testing scenario: 2_**
**JRE-2**:
starting our application in consumes: 486.7MB
leave application idle for 1 hour: 7.7MB RELEASED
After testing and final memory will be: 315.1MB 

-Testing scenarios are same.
-Mac OS X is installed in VM environment for testing.
-Our application is standalone application which runs in Mac as well as Windows. 
-The issue is not seen with windows version of JRE.

can you please help with the issue so that we can continue with JRE-1 ?

**Comment by pshipton** [comment] 2021-01-08 04:55
@dmitripivkine

**Comment by dmitripivkine** [comment] 2021-01-08 14:46
@amicic FYI

**Comment by dmitripivkine** [comment] 2021-01-08 15:24
@srinayak666 Would you please collect and send us GC verbose logs for OpenJ9 OSX ("bad") and OpenJ9  Windows runs ("good")? GC verbose log might be requested using `-verbose:gc` and redirected to file by `-Xverbosegclog:<filename>` options. Also in case unreleased memory is not relates to GC directly it might be useful to collect number of javacore files for each run (after startup, after idle, end of the run) for each OSX and Windows runs. Javacore has "Native memory usage" report section, so it might be helpful to figure out where unreleased memory belong.
Please let us know is you need more instructions regarding collection requested data

**Comment by srinayak666** [comment] 2021-01-13 09:53
Hi @dmitripivkine ,
Thank You for the response.

attached are the verbose gc logs for both Mac and windows.

below are the details about JRE and test:

-Xgcpolicy:concurrentScavenge

GC: default (parallel)
JRE:
openjdk version "1.8.0_275"	
OpenJDK Runtime Environment (build 1.8.0_275-b01)	
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Mac OS X amd64-64-Bit 20201112_584 (JIT enabled, AOT enabled)	
OpenJ9   - 0394ef754	
OMR      - 582366ae5	
JCL      - b52d2ff7ee based on jdk8u275-b01)	

Test:
- open application
- test for few minutes (10 minutes)
- leave application idle for 1 hour.


[mac_verbose_gc.log](https://github.com/eclipse/openj9/files/5807767/mac_verbose_gc.log)
[windows_verbose_gc.log](https://github.com/eclipse/openj9/files/5807768/windows_verbose_gc.log)

**Comment by dmitripivkine** [comment] 2021-01-13 15:56
Hi @srinayak666,

There are different object heap settings between Mac/Windows runs you are comparing with:

For Mac:
```
    <vmarg name="-Xmx256m" />
    <vmarg name="-Xms48m" />
    <vmarg name="-Xmx512m" /> <--- this option is provided twice, most right wins
```

For Windows:
```
    <vmarg name="-Xmaxt0.6" />
    <vmarg name="-Xmca512k" />
    <vmarg name="-Xminf0.1" />
    <vmarg name="-Xmn7m" />
    <vmarg name="-Xms256m" />
    <vmarg name="-Xmx512m" />
```

The most significant difference is limit Nursery size to 7m on Windows by `-Xmn7m`. Despite potential performance problems related with very small Nursery (too many Local GCs) this parameter is critical for heap geometry for your test. Initial heap size `-Xms48m` for Mac vs. `-Xms256m` for Windows might have impact too. Options like `-Xmaxt` and `-Xmin` might make heap expansion/contraction dynamic different as well.

Would you please set JVM options for Mac the same way you have them tuned for Windows, do your memory measurements again and collect GC verbose log for this run.

In general at the moment I can not observe anything wrong in GC behaviour.

**Comment by srinayak666** [comment] 2021-01-15 14:57
Hi @dmitripivkine ,


- I have set JVM options for Mac the same way as Windows.
- -Xmx512m is used even -Xmx256m is shown.
- The params are passed in an array (as given in mac_gc_verbose.log)
params[0].. to .. params[86]
- verified other params from mac and windows - and are identical.
- Is there something that need to be addressed by changing GC?
- the gcpolicy: gencon in both the cases
- The memory used by application in Mac env. is not released as expected compared to windows testing.
- When we use the application in Mac, memory keeps growing- upon closing the tabs/windows in application the consumed memory is not released.
- is there some other VM params that can be set apart from the one which is in logs? so that memory gets released once its consumed?
using -Xaggressive didn't help in releasing memory.

[mac_gc_verbose.log](https://github.com/eclipse/openj9/files/5821210/mac_gc_verbose.log)
[win_gc_verbose.log](https://github.com/eclipse/openj9/files/5821211/win_gc_verbose.log)

Thanks a lot for the details.

Thank You,
Srikanth S

**Comment by dmitripivkine** [comment] 2021-01-15 15:26
@srinayak666 you can try to play with `-Xtune:virtualized -XX:+IdleTuningGcOnIdle -XX:+IdleTuningCompactOnIdle`
these options should:
- enable automatic Idle detection
- execute GC with Compaction on Idle event

**Comment by dmitripivkine** [comment] 2021-01-15 15:33
> @srinayak666 you can try to play with `-Xtune:virtualized -XX:+IdleTuningGcOnIdle -XX:+IdleTuningCompactOnIdle`
> these options should:
> 
> * enable automatic Idle detection
> * execute GC with Compaction on Idle event

Sorry, this will work for Java 11 and higher (or run in Container environment). I missed you are using Java 8

**Comment by dmitripivkine** [comment] 2021-01-20 14:35
this is not item for Java 16 release

**Comment by dmitripivkine** [comment] 2021-01-25 18:13
Hi @srinayak666,

As you can see the difference between OSX and Windows builds is much smaller with aligned options. There are more external factors in environment (number of CPUs or CPU performance for example) which make memory usage different. So eventually with all factors aligned you might get comparable results (with quite large deviation however related with highly dynamic heap expansion/contraction scenario run to run).  Also entire approach is questionable because the way how main goal to minimize used memory after startup is achieved might cause serious performance issues in further application run. For example use of very small Nursery is reduced total used memory after startup but might be a reason for significant GC overhead in actual application run.
However the problem you are addressing is legitimate indeed. We have addressed it by adding Idle functionality support when application inactivity can be detected automatically and JVM might reduce amount of occupied resources with different degree of aggressiveness. Originally this functionality has been design for JVM runs in containerized environments (for example in Docker container). This service in available in Java 8. Also as recognition of Idle might be useful in general not only containers this feature support has been added to Java 11 under `-Xtune:virtualized` option.
I believe set of the options I mentioned in https://github.com/eclipse/openj9/issues/11602#issuecomment-761011070 might improve memory usage in your case but it is available for Java 11 only. Unfortunately there is no ready to go solution in Java 8 in general.

**Comment by srinayak666** [comment] 2021-01-28 15:16
Hi @dmitripivkine ,

we shifted from IBM jvm 1.8 to open jvm 1.8, The issue with memory was not seen with IBM jvm 1.8 but after switching to open jvm 1.8 the memory issue seen.

looks like a regression issue with open jvm 1.8?

**Comment by dmitripivkine** [comment] 2021-01-28 16:41
> Hi @dmitripivkine ,
> 
> we shifted from IBM jvm 1.8 to open jvm 1.8, The issue with memory was not seen with IBM jvm 1.8 but after switching to open jvm 1.8 the memory issue seen.
> 
> looks like a regression issue with open jvm 1.8?

Just for information IBM jvm 1.8 for OSX does not use J9 implementation, so this is not a direct regression (but difference in behaviour might be not optimum)

**Comment by Ram-Krishnamurthy** [comment] 2021-01-28 19:06
We need to use open jvm 1.8 and we can't move up to 11. We need a fix for this memory growth issue. Please help.

**Comment by Ram-Krishnamurthy** [comment] 2021-01-28 21:56
Also we observe this issue only in Mac. On Windows the Open JVM 1.8 is regularly freeing up the memory as expected

**Comment by dmitripivkine** [comment] 2021-01-29 17:38
Hi @srinayak666, @Ram-Krishnamurthy, we are trying to do our best to help.

There is a very wide range of factors might have impact JVM memory usage: from different memory management models between Windows and OSX to different behaviour of Java Finalization thread(s) might keep more native memory than expected. In order to help us to investigate all these possibilities and address them we need complete and consistent set of data.

Would you please do another runs on Windows and Mac with following requirements:

- please use regular `-Xgcpolicy:gencon`, please do not use `-Xgc:concurrentScavenge`
- please use aligned (equivalent) command line options set for both runs as in a previous test
- please generate and provide one or more javacore files per run by adding `-Xdump:java:events=vmstop+user`. This option is forcing javacore generation at the end of run as well as at any "user" signal passed manually (`kill -3 <process_id>` on Mac or `<Ctrl><Break>` on Windows). The best times to generate javacore are end of startup and at the end of run.
- please do measure and provide app footprint (memory usage) for both Windows and Mac as was done originally
- additionally please try to specify `-Xmx128m` for investigation purpose only. Using smaller heap should force more Global GCs and help us to examine behaviour. Please do not use this option if 128m heap happen to be not large enough and you have OOM thrown.

**Comment by srinayak666** [comment] 2021-02-01 08:20
Hi @dmitripivkine ,
Thank You for the response. 
below are the details about testing performed in windows and Mac as per your comments.
attached zip contains all the files. 


**windows:**
Heap used:
vmarg.Xmx=-Xmx128m
vmarg.Xms=-Xms64m

-Xgcpolicy:gencon


**RUN-1:** [Normal exit]. (folder path in attached zip: memory_usage\Windows\RUN-1)
verbose gc logs: Normal_Win_GC.log
java_corefile:javacore.20210201.103758.7924.0001.txt

Testing Memory consumption:
*This memory consumption listed below is derived from Task Manager of Windows.
	- Application start:180.3 MB
	- Application use/TEST for 5 minutes (open 50 different windows in Application - close all windows) + leave Application idle for 10 minutes. 
	- Memory before stopping Application (Normal Exit):188.2 MB
	


**RUN-2**:[crashing Application]. (folder path in attached zip: memory_usage\Windows\RUN-2)
verbose gc logs: Kill_Win_GC.log
java_corefile:javacore.20210201.112112.6816.0001.txt
Testing Memory consumption:
*This memory consumption listed below is derived from Task Manager of Windows.
	- Application start:183.0 MB
	- Application use/TEST for 5 minutes (open 50 different windows in Application - close all windows) + leave Application idle for 10 minutes. 
	- Memory before crashing Application (Application will be killd abruptly):190.2 MB
============================

**Mac:**
Heap used:
vmarg.Xmx=-Xmx128m
vmarg.Xms=-Xms64m

-Xgcpolicy:gencon
*All parameters are kept identical to Windows.
Options:
    <vmarg name="-Xmx256m" />
    <vmarg name="-Xms48m" />
	can be ignored since those are overwritten with :
	vmarg.Xmx=-Xmx128m
	vmarg.Xms=-Xms64m


**RUN-1:** [Normal exit]. (folder path in attached zip: memory_usage\Mac\RUN-1)
verbose gc logs: Normal_Mac_GC.log
java_corefile:javacore.20210131.230910.87876.0001.txt

Testing Memory consumption:
*This memory consumption listed below is derived from Activity Monitor of Mac.
	- Application start:301.5 MB
	- Application use/TEST for 5 minutes (open 50 different windows in Application - close all windows) + leave Application idle for 10 minutes. 
	- Memory before stopping Application (Normal Exit):465.0 MB
	


**RUN-2:**[crashing Application]. (folder path in attached zip: memory_usage\Mac\RUN-2)
verbose gc logs: Kill_Mac_GC.log
java_corefile:javacore.20210131.235930.88001.0002.txt
Testing Memory consumption:
*This memory consumption listed below is derived from Activity Monitor of Mac.
	- Application start:277.6 MB
	- Application use/TEST for 5 minutes (open 50 different windows in Application - close all windows) + leave Application idle for 10 minutes. 
	- Memory before crashing Application (Application will be killed abruptly):447.0 MB

[memory_usage.zip](https://github.com/eclipse/openj9/files/5902680/memory_usage.zip)



Thank You!

**Comment by dmitripivkine** [comment] 2021-02-01 16:06
Comparing `NATIVEMEMINFO` sections from java cores:
for Windows (good layout) - for reference
```
NULL           ------------------------------------------------------------------------
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 297,452,868 bytes / 6409 allocations
1MEMUSER       |
2MEMUSER       +--VM: 260,646,684 bytes / 5340 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 114,801,552 bytes / 2810 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Shared Class Cache: 67,108,864 bytes / 1 allocation <--- this section does not exist for Mac
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 47,692,688 bytes / 2809 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 137,717,832 bytes / 627 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 134,279,168 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 3,438,664 bytes / 626 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 6,618,572 bytes / 125 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 376,968 bytes / 18 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 6,029,312 bytes / 17 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 212,292 bytes / 90 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,320 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 411,936 bytes / 1149 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 13,536 bytes / 115 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 1,065,936 bytes / 501 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 36,724,960 bytes / 1023 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 8,388,608 bytes / 4 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 5,767,696 bytes / 11 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 22,568,656 bytes / 1008 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 81,224 bytes / 46 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 81,224 bytes / 46 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 4,592 bytes / 8 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 384 bytes / 6 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Other: 4,208 bytes / 2 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 76,632 bytes / 38 allocations
```

for Mac:
```
NULL           ------------------------------------------------------------------------
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 520,587,144 bytes / 6990 allocations <--- total usage ~200MB larger
1MEMUSER       |
2MEMUSER       +--VM: 217,581,664 bytes / 5718 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 67,810,392 bytes / 2978 allocations <--- Shared Classes are not used
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 138,903,272 bytes / 684 allocations <--- GC uses about the same memory amount
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 134,279,168 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 4,624,104 bytes / 683 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 9,043,688 bytes / 205 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 754,520 bytes / 21 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 7,864,320 bytes / 21 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 424,848 bytes / 163 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 637,472 bytes / 1294 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 10,264 bytes / 64 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 1,158,800 bytes / 480 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 301,933,984 bytes / 1005 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation <--- !!! this is ~250MB larger
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 6,291,648 bytes / 3 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 27,206,880 bytes / 1001 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 1,071,496 bytes / 267 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 1,071,496 bytes / 267 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 4,784 bytes / 8 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 528 bytes / 6 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Other: 4,256 bytes / 2 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 1,066,712 bytes / 259 allocations
```

So from this data alone (not even discussing effectiveness of GC):
- JVM on Mac occupies ~200MB more than on Windows
- the major difference of memory usage is in JIT Code Cache - about 250MB larger on Mac that Windows
- JVM on Mac seems does not use Shared Classes (even `-Xscmx64m` is provided)
- JVM on Windows has `-Xshareclasses` option but it is missed for Mac:
```
2CIUSERARG               -Xshareclasses:name=xpdplat_.jvm,controlDir=c:/Program Files (x86)/HCL/Notes/Data/workspace/.config/org.eclipse.osgi,groupAccess,keep,singleJVM,nonfatal
```

I think that setting up Shared Classes for Mac properly might help significantly
@pshipton @hangshao0  Is there any specific recommendations for setting up SC on Mac (file location, security etc.)?

My guess using of Shared Classes would reduce size of JIT Code Cache significantly because amount of JIT compilation for startup should be reduced dramatically - so as a size for JIT Code Cache
@0xdaryl @fjeremic Is it correct? Do you have other suggestions to reduce size of JIT Code Cache?

@srinayak666 
Seems run on Mac does not use Shared Classes currently.
Would you please try to setup `-Xshareclasses` for Mac properly and repeat test again (RUN-1 for Mac should be enough) in order to get new javacore file?

Also I noticed there is another JIT related option provided for Windows but missed for Mac (I am not sure about possible impact):
```
-Xjit:exclude={lotus/domino/local/Session.FindOrCreate(*},dontInline={lotus/domino/local/Session.FindOrCreate(*}
```

**Comment by fjeremic** [comment] 2021-02-01 16:33
> @0xdaryl @fjeremic Is it correct? Do you have other suggestions to reduce size of JIT Code Cache?

There used to be an option to optimize for size but it has been removed because it was not tested well and we have not seen it used in practise ever. If you don't care about throughput performance and want the smallest footprint you can try disabling inlining which should in theory help. You can try this via `-Xjit:disableInlining`. However be aware that your throughput will _tank_ with that option. We're talking probably 30% or more.

**Comment by hangshao0** [comment] 2021-02-01 16:39
> Is there any specific recommendations for setting up SC on Mac (file location, security etc.)?

See https://www.eclipse.org/openj9/docs/shrc/#best-practices-for-using-xshareclasses. So better to use `-Xshareclasses:name=<cacheName>,cacheDir=<dir>,cacheDirPerm=<permission>,nofatal`. 

When sub-option `nofatal` is used, the JVM will ignore the error if there is a problem opening or creating the shared cache and JVM will start up without the shared cache. It is better not to use `nofatal` in the first run to see if the shared cache is successfully started up (fix any errors if not). Then add `nofatal` in subsequent runs.

**Comment by pshipton** [comment] 2021-02-01 17:03
No -Xshareclasses options are specified in this case. Shared classes is enabled by default, but won't be used if there is a problem since the default is equivalent to `-Xshareclasses:bootClassesOnly,nonfatal` . Pls try on Mac with `-Xshareclasses:bootClassesOnly,verbose -Xscmx64m` and capture the console output so we can see what's going on.

**Comment by srinayak666** [comment] 2021-02-01 17:36
Hi @pshipton ,

I have specified :
-Xshareclasses:bootClassesOnly,nonfatal

attached are the javacore and verbose logs.

I see below error in verbose logs:
JVMSHRC226E Error opening shared class cache file
JVMSHRC336E Port layer error code = -102
JVMSHRC337E Platform error message: Permission denied
JVMSHRC840E Failed to start up the shared cache.
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified

Do I need to explicitly specify any other path for shared class as said by @hangshao0?

[javacore.20210201.093015.89973.0001.txt](https://github.com/eclipse/openj9/files/5905603/javacore.20210201.093015.89973.0001.txt)
[verbose_Mac_.log](https://github.com/eclipse/openj9/files/5905604/verbose_Mac_.log)

**Comment by pshipton** [comment] 2021-02-01 18:33
The default shared cache location is the user's home directory, which seems to get permission denied. You can see the default location and name via `-Xshareclasses:bootClassesOnly,printCacheFileName`.

Please try specifying a different location for the cache. Note you can only have one `-Xshareclasses` option that includes all the sub-options, the right most option takes precedence. 

You can also add `fatal` if you like, which will fail to start the JVM any time the cache cannot be opened, since the default for `bootClassesOnly` is `nonfatal`.

**Comment by Ram-Krishnamurthy** [comment] 2021-02-01 22:20
As we work through the shared classes issue, that only addresses the 200M startup cost. Is there anything else in the logs which points to why the steady state memory keeps growing and not releasing memory?

Thanks so much!

**Comment by dmitripivkine** [comment] 2021-03-04 14:42
moving to next milestone

**Comment by dmitripivkine** [comment] 2021-09-14 15:15
@srinayak666 Can this item be closed?

**Comment by failedpeanut** [comment] 2021-09-14 15:32
> @srinayak666 Can this item be closed?

@dmitripivkine yes sure. Thank you!

**Closed** 2021-09-14 15:45 UTC
Labels: comp:gc, userRaised
