### ISSUE TITLE
Invalid class in objectPtr ASSERTION FAILED gc_vlhgc/CopyForwardScheme.cpp:1258

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14399] opened 2022-01-31 16:55 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_mac_Nightly/143
testSoftMxLocal_LP4k_3 `-Xjit -Xgcpolicy:balanced -Xnocompressedrefs`
```
Invalid class in objectPtr=000000000FB952F8
06:43:46.448 0x7fdb749b9300    j9mm.141    *   ** ASSERTION FAILED ** at /Users/jenkins/workspace/Build_JDK17_x86-64_mac_Nightly/openj9/runtime/gc_vlhgc/CopyForwardScheme.cpp:1258: ((false))
Unhandled exception
Type=Segmentation error vmState=0x0002000f
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=000000000BC38010 Handler2=000000000B280C90 InaccessibleAddress=0000000000000000
RDI=000070000E2A8AD8 RSI=000000000000D2F0 RAX=0000000000000000 RBX=0000000000000001
RCX=0000000099669966 RDX=0000000000000001 R8=00007FDB73700AA0 R9=0000000000000005
R10=0000000000000001 R11=000000000000003E R12=000000000FB9AB70 R13=000000000FB9AB70
R14=000000000F3DCFF8 R15=000000000F3DD008
RIP=000000000DA95C93 GS=0000 FS=0000 RSP=000070000E2A8AB0
RFlags=0000000000010246 CS=002B RBP=000070000E2A8B60 ERR=0000000000000004
TRAPNO=000000040000000E CPU=0000000000040000 FAULTVADDR=0000000000000000
XMM0 405a000000000000 (f: 0.000000, d: 1.040000e+02)
XMM1 4530000043300000 (f: 1127219200.000000, d: 1.934282e+25)
XMM2 4330000000000000 (f: 0.000000, d: 4.503600e+15)
XMM3 4230b9b64e400000 (f: 1312817152.000000, d: 7.183521e+10)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
XMM6 3fb075983598e471 (f: 899212416.000000, d: 6.429435e-02)
XMM7 4028f40b5ed9812d (f: 1591312640.000000, d: 1.247665e+01)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
```

@dmitripivkine

**Comment by dmitripivkine** [comment] 2022-01-31 18:04
This is exact duplicate of https://github.com/eclipse-openj9/openj9/issues/14396 (and probably https://github.com/eclipse-openj9/openj9/issues/14382)
```
Assertion

Invalid class in objectPtr=000000000FB952F8
06:43:46.448 0x7fdb749b9300    j9mm.141    *   ** ASSERTION FAILED ** at /Users/jenkins/workspace/

0x0FB952E0 :  0000000000000000 000000000f38c320 [ ........ .8..... ]
0x0FB952F0 :  0000000000000000 000000000fb96269 [ ........ib...... ] <--- hole size 0x8f8
0x0FB95300 :  00000000000008f8 000000000fb95310 [ .........S...... ]

> !j9object 0x0F3D9EE8
!J9Object 0x000000000F3D9EE8 {
	struct J9Class* clazz = !j9class 0x7FDB74C18700 // jdk/internal/math/FDBigInteger
	Object flags = 0x00000000;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	[I data = !fj9object 0xfb952f8 (offset = 8) (jdk/internal/math/FDBigInteger) <--- pointer to the hole
	I offset = 0x00000000 (offset = 16) (jdk/internal/math/FDBigInteger)
	I nWords = 0x00000019 (offset = 20) (jdk/internal/math/FDBigInteger)
	Z isImmutable = 0x00000001 (offset = 24) (jdk/internal/math/FDBigInteger)
}
> !markmap ismarked 0x0F3D9EE8
Object 0x000000000F3D9EE8 is marked

Crash:

0x0FB9AB60 :  000000000fb99118 000000000fa8dae8 [ ................ ]
0x0FB9AB70 :  0000000000000001 0000000000065490 [ .........T...... ] <--- hole address in r12/r13
0x0FB9AB80 :  000000000fb9ab88 a2a837f1dc8a1c19 [ .............7.. ]
0x0FB9AB90 :  c411a4442d409234 3e44c8fa88b5e357 [ 4.@-D...W.....D> ]

> !j9object 0x0F3DCFE0
!J9Object 0x000000000F3DCFE0 {
	struct J9Class* clazz = !j9class 0x7FDB74C18700 // jdk/internal/math/FDBigInteger
	Object flags = 0x00000000;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	[I data = !fj9object 0xfb9ab70 (offset = 8) (jdk/internal/math/FDBigInteger) <--- points to the hole
	I offset = 0x00000000 (offset = 16) (jdk/internal/math/FDBigInteger)
	I nWords = 0x00000013 (offset = 20) (jdk/internal/math/FDBigInteger)
	Z isImmutable = 0x00000001 (offset = 24) (jdk/internal/math/FDBigInteger)
}
> !markmap ismarked 0x0F3DCFE0
Object 0x000000000F3DCFE0 is marked
```

**Closed by dmitripivkine** 2022-01-31 18:04 UTC
Labels: comp:gc, test failure
