### ISSUE TITLE
aarch64 hang during test Create a non persistent cache

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse-openj9/openj9#11177] opened 2020-11-13 09:21 UTC
Testcases on various platforms hang periodically, see:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1579#issuecomment-726595987
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1579#issuecomment-726630670

The console output:
```
01:18:00  Testing: Test 26: CMVC 168131 : Create a non persistent cache
01:18:00  Test start time: 2020/11/13 01:17:59 Coordinated Universal Time
01:18:00  Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_linux/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,nonpersistent -version
01:18:00  Time spent starting: 2 milliseconds
01:28:13  ***[TEST INFO 2020/11/13 01:27:59] ProcessKiller detected a timeout after 600000 milliseconds!***
01:28:13  INFO: getUnixPID() has failed indicating this is not a UNIX System.'Debug on timeout' is currently only supported on Linux.
```

From a bit of an examination of the above test framework code, I believe the hang is here as it uses no timeout on the wait:
https://github.com/eclipse/openj9/blob/efdb86514d722cf83747d9d8badc449fe6121658/test/functional/cmdline_options_tester/src/Test.java#L227

The above console output indicates the test had timed out and ProcessKiller logic kills the process here:
https://github.com/eclipse/openj9/blob/efdb86514d722cf83747d9d8badc449fe6121658/test/functional/cmdline_options_tester/src/Test.java#L565
So I suspect the proc.waitFor() above is waiting for a process that has already terminated.

Adding a timeout to this proc.waitFor() would at least alleviate the Adopt hang please...?

**Comment by pshipton** [comment] 2020-11-13 13:44
The spec for waitFor() says "This method returns immediately if the process has already terminated.".

Adding a timeout in the waitFor() allows the non-terminated process to keep running, or there is a bug related to waitFor() if the process is terminated and waitFor() isn't returning. We need to look at the machine and see what's going on. 

@knn-k

**Comment by pshipton** [comment] 2020-11-13 13:46
Also, we could fix getUnixPID() as then the test framework attempt to attach to the running process with gdb and get a stack trace.

**Comment by 0xdaryl** [comment] 2020-12-07 19:50
Has the AArch64 problem been seen since the initial report (and whose build information is no longer available)?  @knn-k  has tried but failed to reproduce.

@pshipton : for my own edification, why is this labeled a blocker?  I'd just like to understand the criteria.

**Comment by pshipton** [comment] 2020-12-07 23:06
@0xdaryl I set it as a blocker because it was blocking the functional tests from completing, potentially hiding other problems. Also consuming machine resources until the test times out, which may impact other testing. Feel free to adjust it as desired.

**Comment by pshipton** [comment] 2020-12-11 04:19
Do we need this in the milestone plan? I'll remove it.

**Comment by pshipton** [comment] 2021-09-10 13:34
This seems obsolete, closing.

**Closed by pshipton** 2021-09-10 13:34 UTC
Labels: test failure, blocker, arch:aarch64
