### ISSUE TITLE
jdk23 UtilLoadTest_5m crash vmState=0x00040000 Java_java_lang_Thread_interruptImpl omrthread_interrupt pthread_mutex_lock

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19484] opened 2024-05-13 12:34 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_extended.system_aarch64_linux_Nightly_testList_0/10
UtilLoadTest_5m_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdknext_j9_extended.system_aarch64_linux_Nightly_testList_0/10/system_test_output.tar.gz
```
21:54:25  STF 01:54:25.042 - ====================   E X E C U T E -   ====================
21:54:25  STF 01:54:25.042 - Running execute: perl /home/jenkins/workspace/Test_openjdknext_j9_extended.system_aarch64_linux_Nightly_testList_0/aqa-tests/TKG/../TKG/output_17153911689824/UtilLoadTest_5m_0/20240511-015421-UtilLoadTest/execute.pl
21:54:25  STF 01:54:25.139 - 
21:54:25  STF 01:54:25.139 - Java version
21:54:25  STF 01:54:25.139 - Running: /home/jenkins/workspace/Test_openjdknext_j9_extended.system_aarch64_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java -version
21:54:25  openjdk version "23-internal" 2024-09-17
21:54:25  OpenJDK Runtime Environment (build 23-internal-adhoc.jenkins.BuildJDKnextaarch64linuxNightly)
21:54:25  Eclipse OpenJ9 VM (build master-df2c1c0d7f5, JRE 23 Linux aarch64-64-Bit Compressed References 20240510_65 (JIT enabled, AOT enabled)
21:54:25  OpenJ9   - df2c1c0d7f5
21:54:25  OMR      - b9a6cccd97d
21:54:25  JCL      - e746df70557 based on jdk-23+21)
21:54:25  Unhandled exception
21:54:25  Type=Segmentation error vmState=0x00040000
21:54:25  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
21:54:25  Handler1=0000FFFF8F797B64 Handler2=0000FFFF8F6FDBF0 InaccessibleAddress=00000000000004B0
21:54:25  R0=00000000000004A0 R1=00000000001ED238 R2=0000FFFF8F6D5940 R3=0000FFFF8FEEE2F0
21:54:25  R4=0000000000000001 R5=00000000FFF5FA20 R6=0000FFFF880A0598 R7=40F1233C35E9FA00
21:54:25  R8=000000000010FC20 R9=0000FFFF8DED90E4 R10=0000000000000000 R11=0000000000000008
21:54:25  R12=0000000000000010 R13=0000000000000002 R14=0000FFFF4F452C40 R15=0000000000000004
21:54:25  R16=0000FFFF8F6D5058 R17=0000FFFF8FECBBF0 R18=0000000000000000 R19=0000000000000000
21:54:25  R20=0000FFFF882498F0 R21=00000000000004B0 R22=0000FFFF8F6D4000 R23=0000000000000001
21:54:25  R24=0000000000000000 R25=0000FFFF4F452860 R26=0000FFFF4F452B88 R27=0000FFFF4F452C20
21:54:25  R28=0000000000000010 R29=0000FFFF4F452880 R30=0000FFFF8F6AF5C0 R31=0000FFFF4F452880
21:54:25  PC=0000FFFF8FECBC00 SP=0000FFFF4F452880 PSTATE=0000000060000000
21:54:25  V0=2cf6b2161400cb0f (f: 335596288.000000, d: 4.352151e-92)
21:54:25  V1=a33bc15cb73b0a53 (f: 3074099712.000000, d: -5.826775e-139)
21:54:25  V2=a33b3ea338f67919 (f: 955676928.000000, d: -5.719574e-139)
21:54:25  V3=402f1fbda155c719 (f: 2706753280.000000, d: 1.556199e+01)
21:54:25  V4=bfd00ea348b88334 (f: 1220051712.000000, d: -2.508934e-01)
21:54:25  V5=3fd5575b0be00b6a (f: 199232368.000000, d: 3.334568e-01)
21:54:25  V6=3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
21:54:25  V7=4010040140100401 (f: 1074791424.000000, d: 4.003911e+00)
21:54:25  V8=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V9=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V10=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V11=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V12=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V13=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V14=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V15=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V16=0000000044000000 (f: 1140850688.000000, d: 5.636551e-315)
21:54:25  V17=fcfcfe00fe00fe00 (f: 4261477888.000000, d: -1.157276e+294)
21:54:25  V18=8020080280000000 (f: 2147483648.000000, d: -4.458850e-308)
21:54:25  V19=3f9eb851eb851eb8 (f: 3951369984.000000, d: 3.000000e-02)
21:54:25  V20=3fb1eb851eb851ec (f: 515396064.000000, d: 7.000000e-02)
21:54:25  V21=0000000000000002 (f: 2.000000, d: 9.881313e-324)
21:54:25  V22=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V23=0000000000000008 (f: 8.000000, d: 3.952525e-323)
21:54:25  V24=3fd6666666666666 (f: 1717986944.000000, d: 3.500000e-01)
21:54:25  V25=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V26=0000000000000001 (f: 1.000000, d: 4.940656e-324)
21:54:25  V27=000000000000000a (f: 10.000000, d: 4.940656e-323)
21:54:25  V28=0000000000000001 (f: 1.000000, d: 4.940656e-324)
21:54:25  V29=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V30=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  V31=0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:54:25  Module=/lib/aarch64-linux-gnu/libpthread.so.0
21:54:25  Module_base_address=0000FFFF8FEC2000 Symbol=pthread_mutex_lock
21:54:25  Symbol_address=0000FFFF8FECBBF0
21:54:25  Target=2_90_20240510_65 (Linux 5.4.0-144-generic)
21:54:25  CPU=aarch64 (4 logical CPUs) (0x1f00f8000 RAM)
21:54:25  ----------- Stack Backtrace -----------
21:54:25  pthread_mutex_lock+0x10 (0x0000FFFF8FECBC00 [libpthread.so.0+0x9c00])
21:54:25  omrthread_interrupt+0x50 (0x0000FFFF8F6AF5C0 [libj9thr29.so+0xa5c0])
21:54:25  Java_java_lang_Thread_interruptImpl+0x144 (0x0000FFFF8DED9228 [libjclse29.so+0x4b228])
21:54:25  ffi_call_SYSV+0x50 (0x0000FFFF8F928F70 [libj9vm29.so+0x1c4f70])
21:54:25  ffi_call_int+0x204 (0x0000FFFF8F928524 [libj9vm29.so+0x1c4524])
21:54:25  bytecodeLoopCompressed+0xda78 (0x0000FFFF8F801498 [libj9vm29.so+0x9d498])
21:54:25  c_cInterpreter+0x54 (0x0000FFFF8F8B7B6C [libj9vm29.so+0x153b6c])
21:54:25  ---------------------------------------
```

**Comment by babsingh** [comment] 2024-06-10 17:56
This is a duplicate of https://github.com/eclipse-openj9/openj9/issues/19544. See https://github.com/eclipse-openj9/openj9/issues/19544#issuecomment-2134060600 for more details.

**Closed by babsingh** 2024-06-10 17:56 UTC
Labels: comp:vm, test failure, segfault, jdk23
