### ISSUE TITLE
OpenJDK test/java/math/BigInteger/PrimeTest.java x86_64_Windows JDK8

### ISSUE THREAD

**Issue by ThanHenderson** [eclipse-openj9/openj9#20251] opened 2024-09-27 16:17 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Personal_testList_2/26/ - [win2012x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2012x64-openj9-1)
`jdk_math_0`
`test/java/math/BigInteger/PrimeTest.java`
```
15:48:02          PrimeTest
15:48:02  stderr:
15:48:02  Unhandled exception
15:48:02  Type=Illegal instruction vmState=0x00000000
15:48:02  Windows_ExceptionCode=c000001d J9Generic_Signal=00000010 ExceptionAddress=00007FFE7B8CD375 ContextFlags=0010005f
15:48:02  Handler1=00007FFE90D109E0 Handler2=00007FFE9249AC50
15:48:02  RDI=0000000000000001 RSI=000000000013D4FC RAX=0000000000000008 RBX=00000000FFFBA880
15:48:02  RCX=0000000000000001 RDX=00000000000EE600 R8=0000000000004F4C R9=00000000FFFBA878
15:48:02  R10=0FFFFFFFFFFFFFFF R11=0000000000004F53 R12=0000000000000001 R13=0000000000000000
15:48:02  R14=000000000025B500 R15=00000000FFFBA0D0
15:48:02  RIP=00007FFE7B8CD375 RSP=000000000025B060 RBP=000000000025B500 EFLAGS=0000000000010217
15:48:02  FS=0053 ES=002B DS=002B
15:48:02  XMM0=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM1=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM2=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM3=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM4=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM5=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM6=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM7=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM8=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM9=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM10=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM11=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM12=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM13=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM14=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  XMM15=0000000000000000 (f: 0.000000, d: 0.000000e+00)
15:48:02  Module=
15:48:02  Module_base_address=00007FFE7B800000 Offset_in_DLL=00000000000cd375
15:48:02  
15:48:02  Compiled_method=PrimeTest.createPrimes(I)Ljava/util/BitSet;
15:48:02  Target=2_90_20240926_1321 (Windows Server 2012 R2 6.3 build 9600)
15:48:02  CPU=amd64 (4 logical CPUs) (0x3fff77000 RAM)
15:48:02  ----------- Stack Backtrace -----------
15:48:02  (0x00007FFE7B8CD375)
15:48:02  (0x00000000FFFB9F10)
15:48:02  (0x0000000000000246)
15:48:02  (0x00000000000EE100)
15:48:02  (0x00000000E00DB518)
15:48:02  (0x00000000FFF7B078)
15:48:02  (0x00000000FFFB9F10)
15:48:02  (0x00004F5300000000)
15:48:02  (0x000000000013D4FC)
15:48:02  (0x00000000FFFB9F10)
15:48:02  Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk+0x579e80 (0x00007FFE8FAB3EB0 [j9jit29+0x643eb0])
```

```
15:42:13  OpenJDK Runtime Environment (build 1.8.0_432-internal-****_2024_09_26_14_26-b00)
15:42:13  Eclipse OpenJ9 VM (build HEAD-cb3d8f891e9, JRE 1.8.0 Windows Server 2012 R2 amd64-64-Bit Compressed References 20240926_1321 (JIT enabled, AOT enabled)
15:42:13  OpenJ9   - cb3d8f891e9
15:42:13  OMR      - 44367c44d17
15:42:13  JCL      - 3f4707350a1 based on jdk8u432-b04)
```

**Comment by pshipton** [comment] 2024-09-27 22:29
@hzongaro fyi, an IllegalInstruction failures on Windows.

**Comment by hzongaro** [comment] 2024-09-30 13:15
I took a quick look at the core file.  A `vmovdqu32` instruction triggered the Illegal Instruction signal, so this looks like a duplicate of #19408.

```
00007ffe`7b8cd36b 8bcf               mov     ecx, edi
00007ffe`7b8cd36d 488d04cd00000000   lea     rax, [rcx*8]
00007ffe`7b8cd375 62f17e086f4ccb00   vmovdqu32 xmm1, xmmword ptr [rbx+rcx*8]    <<<< Illegal instruction
00007ffe`7b8cd37d 4883caff           or      rdx, 0FFFFFFFFFFFFFFFFh
00007ffe`7b8cd381 c4e1f96ec2         vmovq   xmm0, rdx
```

 @BradleyWood - FYI.

**Closed** 2024-09-30 13:16 UTC
Labels: comp:jit, test failure
