### ISSUE TITLE
mac11-aarch64-8 offline

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16210] opened 2022-10-26 21:31 UTC
I noticed https://openj9-jenkins.osuosl.org/computer/mac11%2Daarch64%2D8/ was offline due to `Disk space is too low. Only 0.925GB left on /Users/jenkins.`. There were a lot of OpenJ9 diagnostic files in /Users/jenkins, created on the 24th (likely some bug we fixed already). I deleted all the files. Not sure if an automated cleanup job should have done this, or maybe it's manual since jenkins took the machine offline.

@jdekonin @AdamBrousseau fyi

**Comment by AdamBrousseau** [comment] 2022-10-26 21:50
Re core files. I had noticed this morning but got distracted before I had a chance to ask about the errors. I looked at 7 but it didn't have any.
I was looking in regards to eclipse/omr#6774

**Comment by pshipton** [comment] 2022-10-27 00:40
Here is a termination on the same machine in the OpenJ9 builds.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_aarch64_mac_Nightly_testList_1/167/consoleFull
```
19:37:19  mac11-aarch64-8 was marked offline: Connection was broken: java.io.EOFException
19:37:19  	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:3001)
19:37:19  	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3496)
19:37:19  	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:1058)
19:37:19  	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:415)
19:37:19  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
19:37:19  	at hudson.remoting.Command.readFrom(Command.java:142)
19:37:19  	at hudson.remoting.Command.readFrom(Command.java:128)
19:37:19  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
19:37:19  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
19:37:19  Caused: java.io.IOException: Unexpected termination of the channel
19:37:19  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
19:37:19  
```

**Comment by pshipton** [comment] 2022-10-27 00:55
Seems there is something wrong with 8, I'll take it offline so it doesn't mess up more jobs than it already has.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_mac_Nightly/169/console
```
20:35:30  Running on [mac11-aarch64-8](https://openj9-jenkins.osuosl.org/computer/mac11%2Daarch64%2D8/) in /Users/jenkins/workspace/Test_openjdk17_j9_extended.functional_aarch64_mac_Nightly
[Pipeline] {
[Pipeline] cleanWs
20:35:32  [WS-CLEANUP] Deleting project workspace...
20:35:32  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
20:35:48  ERROR: Cannot delete workspace :java.io.IOException: Unexpected termination of the channel
```

**Comment by pshipton** [comment] 2022-10-27 00:56
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_mac_Nightly_testList_1/166/
```
20:54:37  ERROR: Execution failed
20:54:37  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to mac11-aarch64-8
20:54:37  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
20:54:37  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
20:54:37  		at hudson.remoting.Channel.call(Channel.java:1000)
20:54:37  		at hudson.FilePath.act(FilePath.java:1194)
20:54:37  		at hudson.FilePath.act(FilePath.java:1183)
20:54:37  		at hudson.FilePath.mkdirs(FilePath.java:1374)
20:54:37  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:97)
20:54:37  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
20:54:37  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
20:54:37  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
20:54:37  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
20:54:37  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:54:37  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
20:54:37  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
20:54:37  		at java.base/java.lang.Thread.run(Thread.java:836)
20:54:37  java.nio.file.FileSystemException: /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_aarch64_mac_Nightly_testList_1: No space left on device
20:54:37  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
20:54:37  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
20:54:37  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
20:54:37  	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
20:54:37  	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
20:54:37  	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
20:54:37  	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
20:54:37  	at hudson.FilePath.mkdirs(FilePath.java:3624)
20:54:37  	at hudson.FilePath.access$1100(FilePath.java:212)
20:54:37  	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1384)
20:54:37  	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1379)
20:54:37  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3502)
20:54:37  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
20:54:37  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
20:54:37  	at hudson.remoting.Request$2.run(Request.java:376)
20:54:37  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
20:54:37  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:54:37  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
20:54:37  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
20:54:37  	at java.base/java.lang.Thread.run(Thread.java:871)
20:54:37  Retrying
[Pipeline] {
[Pipeline] sleep
20:54:37  Sleeping for 3 min 0 sec
```

**Comment by pshipton** [comment] 2022-10-27 18:12
Made this issue dedicated to mac11-aarch64-8 offline and created https://github.com/eclipse-openj9/openj9/issues/16216 for the other problem.

**Comment by jdekonin** [comment] 2022-10-27 23:30
Upgraded to 11.7.1 as well as a `brew upgrade` for anything new that might've been problematic wrt version compatibility.

I've rebooted and its connected/active on OMR jenkins, still disabled on OpenJ9 jenkins.  I didn't want to enable and wreak nightly builds.

**Comment by pshipton** [comment] 2022-10-28 01:21
I enabled it, to give it a try, still the same problem. Whatever you did to it for OMR must have changed something.
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_mac_Nightly_testList_1/167/console
```
21:18:22  Running on [mac11-aarch64-8](https://openj9-jenkins.osuosl.org/computer/mac11%2Daarch64%2D8/) in /Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_mac_Nightly_testList_1
[Pipeline] {
[Pipeline] retry
[Pipeline] {
[Pipeline] timeout
21:18:22  Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
21:18:23  [WS-CLEANUP] Deleting project workspace...
21:18:23  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
21:18:38  ERROR: Cannot delete workspace :java.io.IOException: Unexpected termination of the channel
```

**Comment by jdekonin** [comment] 2022-10-28 02:29
Separate userid for jenkins to use, separate workspace location, different java process to connect.  I'm now even sure that there are jobs on OMR that are utilizing yet.  If that is the case we can test disabling, and stopping the jenkins agent for the OMR node and see if that changes anything.  @AdamBrousseau any comment here on either point?

**Comment by jdekonin** [comment] 2022-10-28 02:37
Confirmed [Build-linux_aarch64](https://ci.eclipse.org/omr/job/Build-linux_aarch64/) is still cross-compiled.  So I disabled on OMR jenkins, removed all labels from node on OpenJ9 jenkins and launched a grinder to test it out again.
https://openj9-jenkins.osuosl.org/job/Grinder/1463/

**Comment by jdekonin** [comment] 2022-10-28 02:47
Second try.  I noticed that the jenkins client was throwing all kinds of traceasserts as soon as the job started.  It was a very old version of java11 so I updated to 11.0.16.1.
https://openj9-jenkins.osuosl.org/job/Grinder/1464/console

**Comment by pshipton** [comment] 2022-10-28 02:51
> Whatever you did to it for OMR must have changed something.

Well I assumed the machine used to work, but I don't know that it did.

**Comment by AdamBrousseau** [comment] 2022-10-28 07:54
OMR has an amac job. It will run when code is merged or when pr builds are requested specifically for that platform. I.e. it is not included in `all`. Up until a day or two ago it was still using the jenkins ID even though we changed the jiro code to use the omr ID. I guess the node was never reconnected. It is using omr ID now.

All we did was create a new user. No installs. See infra#7003

**Comment by jdekonin** [comment] 2022-10-28 12:33
So that grinder worked fine.  I am going to connect the OMR jenkins agent, which uses a different userid, and rerun the job.  I suspect the root cause was the old version of java that was throwing the traceasserts as well as filling up the home directory with cores.
https://openj9-jenkins.osuosl.org/job/Grinder/1465/

**Comment by jdekonin** [comment] 2022-10-28 17:38
Seems to be working fine now.  I've added the labels back on so the system can start taking regular jobs again.

**Comment by AdamBrousseau** [comment] 2022-10-31 21:10
Build jobs are failing to upload to UNB Artifactory because the agent runs off the bootjdk which got updated. Cert needs to be added to the keystore. Longer term we should not run any UNB nodes with the bootjdk.

**Comment by pshipton** [comment] 2022-11-01 02:32
It's not fixed, disabled it. 
https://openj9-jenkins.osuosl.org/job/Build_JDK19_aarch64_mac_Nightly/111/

**Comment by AdamBrousseau** [comment] 2022-11-01 04:04
Sorry, I disabled 1 instead of 8 by mistake.
Working now. Both re-enabled.
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Build_JDK11_aarch64_mac_Personal&build=206)](https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Personal/206/)

**Comment by pshipton** [comment] 2022-11-02 03:41
Two (so far) test failures on [mac11-aarch64-8](https://openj9-jenkins.osuosl.org/computer/mac11-aarch64-8), disabling it.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_mac_Nightly_testList_1/172/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Nightly_testList_0/171/

**Comment by pshipton** [comment] 2022-11-02 12:04
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.system_aarch64_mac_Nightly_testList_0/42/

**Comment by pshipton** [comment] 2022-11-03 02:30
I removed the build and test labels and brought the machine back online so I could use it in a grinder.

**Comment by AdamBrousseau** [comment] 2023-03-31 18:56
Should we re-add the build/test labels to machine 8?

**Comment by pshipton** [comment] 2023-03-31 19:41
Hard to say. Every time we tried it before it (a) didn't work (b) tanked the builds. I'm happy the way it is, we're not short on amac resources atm.

**Comment by AdamBrousseau** [comment] 2023-07-18 07:18
This machine is back in the pool (in both farms) and has been upgraded to mac13. Suggest we close until we see another issue.

**Closed by AdamBrousseau** 2023-07-18 07:18 UTC
Labels: comp:infra
