### ISSUE TITLE
aarch64 openjdk StreamSpliteratorTest crash vmState=0x00000000 AsTypeHandle.invokeExact_thunkArchetype_X(I)I

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#10168] opened 2020-07-15 02:47 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Release/3
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java
```
21:43:36  Unhandled exception
21:43:36  Type=Segmentation error vmState=0x00000000
21:43:36  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
21:43:36  Handler1=0000FFFFAC3BED38 Handler2=0000FFFFAC279E24 InaccessibleAddress=0000000000000020
21:43:36  R0=00000000FFEA7698 R1=00000000E03494E0 R2=0000000000001A26 R3=00000000FFB88448
21:43:36  R4=0000000000000000 R5=00000000E01A2BD0 R6=00000000E03494E0 R7=0000FFFFAC46C110
21:43:36  R8=0000FFFF8F08B2C4 R9=00000000E01A2308 R10=000000000045CC88 R11=0000000000000003
21:43:36  R12=0000000000000005 R13=0000000000000014 R14=00000000E0184650 R15=00000000E0005B18
21:43:36  R16=0000FFFFA7824CE0 R17=0000FFFFAD23AE1C R18=0000000000000000 R19=000000000043C500
21:43:36  R20=0000000000460FD0 R21=000000002A660061 R22=0000000000003A26 R23=00000000E02D2B80
21:43:36  R24=00000000E03494E0 R25=0000000000001A26 R26=00000000FFB88448 R27=00000000E01A2BD0
21:43:36  R28=00000000FFEA7698 R29=0000FFFFAC294B6C R30=0000FFFF8F2FDB78 R31=0000FFFE3E90E300
21:43:36  PC=0000FFFF8F08B308 SP=0000FFFE3E90E300 PSTATE=0000000020000000
21:43:36  V0 405d000000000000 (f: 0.000000, d: 1.160000e+02)
21:43:36  V1 405a400000000000 (f: 0.000000, d: 1.050000e+02)
21:43:36  V2 40949c0000000000 (f: 0.000000, d: 1.319000e+03)
21:43:36  V3 00000000be454803 (f: 3192211456.000000, d: 1.577162e-314)
21:43:36  V4 000000003c9fd825 (f: 1017108544.000000, d: 5.025184e-315)
21:43:36  V5 000000003950f4bf (f: 961606848.000000, d: 4.750969e-315)
21:43:36  V6 0000000041b00000 (f: 1102053376.000000, d: 5.444867e-315)
21:43:36  V7 00000000b9ea5080 (f: 3119140864.000000, d: 1.541060e-314)
21:43:36  V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V16 000000003e53f142 (f: 1045688640.000000, d: 5.166388e-315)
21:43:36  V17 0000000000000001 (f: 1.000000, d: 4.940656e-324)
21:43:36  V18 8f1bbcdc8f1bbcdc (f: 2400959744.000000, d: -6.815449e-236)
21:43:36  V19 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
21:43:36  V20 f90986d10d097579 (f: 218723712.000000, d: -1.104739e+275)
21:43:36  V21 d400631d6757bc3c (f: 1733803008.000000, d: -4.375347e+96)
21:43:36  V22 efcdab8967452301 (f: 1732584192.000000, d: -3.598696e+230)
21:43:36  V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:43:36  V31 405d000000000000 (f: 0.000000, d: 1.160000e+02)
21:43:36  
21:43:36  Compiled_method=java/lang/invoke/AsTypeHandle.invokeExact_thunkArchetype_X(I)I
21:43:36  Target=2_90_20200714_9 (Linux 4.14.0-115.2.2.el7a.aarch64)
21:43:36  CPU=aarch64 (96 logical CPUs) (0x1fcd7e0000 RAM)
21:43:36  ----------- Stack Backtrace -----------
21:43:36  (0x0000FFFFAC296014 [libj9prt29.so+0x36014])
21:43:36  (0x0000FFFFAC27B080 [libj9prt29.so+0x1b080])
21:43:36  (0x0000FFFFAC296090 [libj9prt29.so+0x36090])
21:43:36  (0x0000FFFFAC2961AC [libj9prt29.so+0x361ac])
21:43:36  (0x0000FFFFAC27B080 [libj9prt29.so+0x1b080])
21:43:36  (0x0000FFFFAC295EF8 [libj9prt29.so+0x35ef8])
21:43:36  (0x0000FFFFAC3BE4D0 [libj9vm29.so+0x7e4d0])
21:43:36  ---------------------------------------
```

**Comment by pshipton** [comment] 2020-07-15 02:47
@knn-k fyi

**Comment by knn-k** [comment] 2020-07-15 04:30
It seems the core file is unavailable in https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Release/3/openjdk_test_output.tar.gz

**Comment by knn-k** [comment] 2020-07-15 07:39
It is intermittent, but I reproduced the crash on cent7-aarch64-1 using the binary from https://ci.eclipse.org/openj9/job/Build_JDK11_aarch64_linux_Release/9/.

```
   0xffff510857e0:      str     x0, [x20,#184]
   0xffff510857e4:      str     x1, [x20,#176]
   0xffff510857e8:      mov     x6, x1
   0xffff510857ec:      ldr     w1, [x0,#40]
   0xffff510857f0:      lsl     x18, x1, #3
   0xffff510857f4:      ldr     w1, [x18,#32] <- Crash here
   0xffff510857f8:      sub     w1, w1, #0x1
   0xffff510857fc:      str     w1, [x18,#32]
```

`x0` is the 'this' of this method.  `x1` is loaded from `[x0,#40]`, and its value is 0x0 in the register dump.
On the other hand, the memory at `[x0,#40]` in the core file contains a non-null value.

```
(gdb) x/12x 0x007FF7E1DA8 // x0 value ('this')
0x7ff7e1da8:    0x00124600      0x00000000      0x00000000      0x38030a86
0x7ff7e1db8:    0x3803d203      0x00000000      0x00000000      0x0000000d
0x7ff7e1dc8:    0x00000002      0x00000000      0x38030d15      0x00000000

(jdmpview)
> whatis 0x007FF7E1DA8 // x0 value ('this')
        heap #1 - name: Generational@ffff881938a0
                0x7ff7e1da8 is within heap segment: 7ff740000 -- 800000000
                0x7ff7e1da8 is the start of an object of type java/lang/invoke/AsTypeHandle

> whatis 0x1c01868a8 // Shift 0x38030d15 to the left by 3 bits
        heap #1 - name: Generational@ffff881938a0
                0x1c01868a8 is within heap segment: 1c0000000 -- 1c0920000
                0x1c01868a8 is the start of an object of type java/lang/invoke/DirectHandle
```

**Comment by knn-k** [comment] 2020-07-15 08:29
I ran the test on a quad-core machine 40+ times, and got no failures.

**Comment by knn-k** [comment] 2020-07-15 15:01
It looks like a memory consistency problem.  I tried inserting an `allocationFence` in a method as a quick hack, and it seems to resolve the crash.

**Comment by knn-k** [comment] 2020-07-16 01:46
The same crash seems to have ocurred with another test, java/util/stream/test/org/openjdk/tests/java/util/stream/ReduceTest in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/203/consoleText:

```
[2020-07-15T16:04:11.122Z] Unhandled exception
[2020-07-15T16:04:11.122Z] Type=Segmentation error vmState=0x00000000
[2020-07-15T16:04:11.122Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2020-07-15T16:04:11.122Z] Handler1=0000FFFF79ED7D38 Handler2=0000FFFF79DB4CC8 InaccessibleAddress=0000000000000020
[2020-07-15T16:04:11.122Z] R0=00000000FFB254A0 R1=00000000E030AF88 R2=000000000000128F R3=00000000FFAEF198
[2020-07-15T16:04:11.122Z] R4=0000000000000000 R5=00000000E01D9880 R6=00000000E030AF88 R7=0000FFFF79F84F40
[2020-07-15T16:04:11.122Z] R8=0000FFFF5C414C84 R9=00000000E01D9180 R10=00000000005761A8 R11=0000000000000003
[2020-07-15T16:04:11.122Z] R12=0000000000000005 R13=0000000000000014 R14=00000000E01D6DF8 R15=00000000E0005A90
[2020-07-15T16:04:11.122Z] R16=0000FFFF7933B64C R17=0000FFFF7AA8DFB0 R18=0000000000000000 R19=0000000000415700
[2020-07-15T16:04:11.122Z] R20=000000000057A710 R21=00000000E01D9880 R22=00000000FFB254A0 R23=00000000E01F9360
[2020-07-15T16:04:11.122Z] R24=00000000E01D9830 R25=00000000E01F8A70 R26=00000000FFCD2E10 R27=0000000000000000
[2020-07-15T16:04:11.122Z] R28=00000000FFCD2E28 R29=0000FFFF79DD18E8 R30=0000FFFF5C417244 R31=0000FFFF244BE310
[2020-07-15T16:04:11.122Z] PC=0000FFFF5C414CC8 SP=0000FFFF24E3E310 PSTATE=0000000020000000
[2020-07-15T16:04:11.122Z] V0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
... lines omitted ...
[2020-07-15T16:04:11.122Z] V31 000000003f400000 (f: 1061158912.000000, d: 5.242822e-315)
[2020-07-15T16:04:11.122Z] 
[2020-07-15T16:04:11.122Z] Compiled_method=java/lang/invoke/AsTypeHandle.invokeExact_thunkArchetype_X(I)I
```

**Comment by knn-k** [comment] 2020-07-16 02:21
Instruction sequence is different (there is no `lsl`), but it looks the same: Register dump shows null-pointer access, but the memory dump contains a valid pointer.

```
   0xffff5c414cb8:      str     x0, [x20, #184]
   0xffff5c414cbc:      str     x1, [x20, #176]
   0xffff5c414cc0:      mov     x6, x1
   0xffff5c414cc4:      ldr     w18, [x0, #40]
   0xffff5c414cc8:      ldr     w1, [x18, #32] <- Crash here with x18 being NULL
   0xffff5c414ccc:      sub     w1, w1, #0x1
   0xffff5c414cd0:      str     w1, [x18, #32]

(gdb) x/12x 0x0FFB254A0 // x0 value ('this')
0xffb254a0:     0x00112100      0x00000000      0x00000000      0xe01d8680
0xffb254b0:     0xe01f9550      0x00000000      0x00000000      0x0000000d
0xffb254c0:     0x00000006      0x00000000      0xe01f9430      0x00000000 // valid pointer is stored at [x0, #40]

(jdmpview)
> whatis 0x0FFB254A0 // x0 value ('this')
        heap #1 - name: Generational@ffff74195170
                0xffb254a0 is within heap segment: ffa60000 -- fff70000
                0xffb254a0 is the start of an object of type java/lang/invoke/AsTypeHandle

> whatis 0xe01f9430
        heap #1 - name: Generational@ffff74195170
                0xe01f9430 is within heap segment: e0000000 -- e0740000
                0xe01f9430 is the start of an object of type java/lang/invoke/DirectHandle
```

**Comment by knn-k** [comment] 2020-07-16 10:03
Optimization `localLiveRangeReduction` removes an `allocationFence` from the IL for the method `java/lang/invoke/MethodHandle.asType(Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MethodHandle;` at optlevel=hot, and that seems to cause the memory consistency problem.

Running StreamSpliteratorTest with `-Xjit:{java/lang/invoke/MethodHandle.asType*}(optlevel=hot,disableLocalLiveRangeReduction)` is OK.

**Comment by 0xdaryl** [comment] 2020-07-16 11:04
I don't have proof this is the problem yet, but this line affecting allocation fences is guarded with `isPower()` and likely needs to include AArch64:

https://github.com/eclipse/omr/blob/b99d3036d8a20592a04fdcd77bca176e794e326d/compiler/optimizer/LocalLiveRangeReducer.cpp#L494

Ideally, this will be turned into a capability query rather than a check on the architecture.

**Comment by knn-k** [comment] 2020-07-16 12:18
I opened eclipse/omr#5401 as a fix for this issue.

**Comment by knn-k** [comment] 2020-07-30 05:00
All the tests passed in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/210/.
This is an intermittent problem, and I will wait for a couple of rounds.

**Comment by knn-k** [comment] 2022-02-23 13:13
I believe this can be closed.  No new failures for 19 months.

**Closed by knn-k** 2022-02-23 13:13 UTC
Labels: comp:jit, test failure, arch:aarch64, segfault
