### ISSUE TITLE
DaaLoadTest_daa3_CS_5m_0 crash vmState=0x00020002

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13366] opened 2021-08-24 11:22 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_ppc64le_linux_Nightly_testList_0/78/
DaaLoadTest_daa3_CS_5m_0
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge 

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_sanity.system_ppc64le_linux_Nightly_testList_0/78/system_test_output.tar.gz
```
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00020002
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
DLT stderr Handler1=00003FFFA25C3EF0 Handler2=00003FFFA24FC300
DLT stderr R0=00003FFFA0DD4598 R1=00003FFF6B0EBDF0 R2=00003FFFA0EF5600 R3=0000000000000001
DLT stderr R4=00000000000001FF R5=00000000FFFFFFFF R6=00003FFF9A010000 R7=00003FFF9C053600
DLT stderr R8=000000000000000C R9=00003FFF9C02A560 R10=00003FFF9C06F320 R11=00000000000001FF
DLT stderr R12=00003FFFA0D50380 R13=00003FFF6B0F6900 R14=0000000000000000 R15=0000000000000000
DLT stderr R16=00003FFF6B070000 R17=0000000000080000 R18=00003FFFA3694390 R19=00003FFF6B0EF900
DLT stderr R20=00003FFF9C1A24E8 R21=00003FFF9C1A2950 R22=00003FFF6B0EF260 R23=00003FFF6B0EBF30
DLT stderr R24=00003FFF6B0EBE58 R25=0000000000000001 R26=00003FFF9C0E6D00 R27=00003FFF9C0E6DE0
DLT stderr R28=00000000000000F0 R29=0000000000000005 R30=00003FFF20001AC8 R31=00000000FFFFFFFF
DLT stderr NIP=00003FFFA0DD47E8 MSR=800000010280F033 ORIG_GPR3=00000000000081C8 CTR=00003FFFA0D50380
DLT stderr LINK=00003FFFA0DD4604 XER=0000000000000000 CCR=0000000024224248 SOFTE=0000000000000001
DLT stderr TRAP=0000000000000300 DAR=000000010000000B dsisr=0000000040000000 RESULT=0000000000000000
DLT stderr FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR1 405408a700000000 (f: 0.000000, d: 8.013519e+01)
DLT stderr FPR2 3fe8000000000000 (f: 0.000000, d: 7.500000e-01)
DLT stderr FPR3 bf3d4a1000000000 (f: 0.000000, d: -4.469194e-04)
DLT stderr FPR4 3f499a0000000000 (f: 0.000000, d: 7.812977e-04)
DLT stderr FPR5 bf94724ea0000000 (f: 2684354560.000000, d: -1.996730e-02)
DLT stderr FPR6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR8 3f9bc994a0000000 (f: 2684354560.000000, d: 2.713616e-02)
DLT stderr FPR9 4035000000000000 (f: 0.000000, d: 2.100000e+01)
DLT stderr FPR10 3fac900000000000 (f: 0.000000, d: 5.578613e-02)
DLT stderr FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR13 bfb7440000000000 (f: 0.000000, d: -9.088135e-02)
DLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_sanity.system_ppc64le_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
DLT stderr Module_base_address=00003FFFA0BD0000
DLT stderr Target=2_90_20210822_80 (Linux 4.4.0-173-generic)
DLT stderr CPU=ppc64le (16 logical CPUs) (0x1fe090000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr (0x00003FFFA0DD47E8 [libj9gc29.so+0x2047e8])
DLT stderr (0x00003FFFA0DD4598 [libj9gc29.so+0x204598])
DLT stderr (0x00003FFFA0C1D33C [libj9gc29.so+0x4d33c])
DLT stderr (0x00003FFFA0DCF9D8 [libj9gc29.so+0x1ff9d8])
DLT stderr (0x00003FFFA0D2DE2C [libj9gc29.so+0x15de2c])
DLT stderr (0x00003FFFA0E01010 [libj9gc29.so+0x231010])
DLT stderr (0x00003FFFA0D4F564 [libj9gc29.so+0x17f564])
DLT stderr (0x00003FFFA0D4E938 [libj9gc29.so+0x17e938])
DLT stderr (0x00003FFFA24FD708 [libj9prt29.so+0x3d708])
DLT stderr (0x00003FFFA0D4E0B0 [libj9gc29.so+0x17e0b0])
DLT stderr (0x00003FFFA24913E8 [libj9thr29.so+0x113e8])
DLT stderr (0x00003FFFA3668040 [libpthread.so.0+0x8040])
DLT stderr clone+0x98 (0x00003FFFA3543BB0 [libc.so.6+0x123bb0])
```

**Comment by pshipton** [comment] 2021-08-24 11:22
@dmitripivkine fyi

**Comment by dmitripivkine** [comment] 2021-08-24 14:13
This is known problem with corrupted Ownable Synchronizer Objects list:
```
#13 <signal handler called>
#14 0x00003fffa0dd47e8 in MM_MarkingSchemeRootClearer::scanOwnableSynchronizerObjects(MM_EnvironmentBase*) ()
   from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#15 0x00003fffa0c1d33c in MM_RootScanner::scanClearable(MM_EnvironmentBase*) () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#16 0x00003fffa0dcf9d8 in MM_MarkingDelegate::workerCompleteGC(MM_EnvironmentBase*) () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#17 0x00003fffa0d2de2c in MM_MarkingScheme::markLiveObjectsComplete(MM_EnvironmentBase*) () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#18 0x00003fffa0e01010 in MM_ParallelMarkTask::run(MM_EnvironmentBase*) () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#19 0x00003fffa0d4f564 in MM_ParallelDispatcher::workerEntryPoint(MM_EnvironmentBase*) () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#20 0x00003fffa0d4e938 in dispatcher_thread_proc2(OMRPortLibrary*, void*) () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#21 0x00003fffa24fd708 in omrsig_protect () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9prt29.so
#22 0x00003fffa0d4e0b0 in dispatcher_thread_proc () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
#23 0x00003fffa24913e8 in thread_wrapper () from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9thr29.so
#24 0x00003fffa3668040 in ?? ()
#25 0x00003fffa3543bb0 in ?? ()
(gdb) frame 14
#14 0x00003fffa0dd47e8 in MM_MarkingSchemeRootClearer::scanOwnableSynchronizerObjects(MM_EnvironmentBase*) ()
   from /team/Dmitri/13366/j2sdk-image/jre/lib/ppc64le/default/libj9gc29.so
```

**Comment by dmitripivkine** [comment] 2021-08-24 14:14
duplicate of https://github.com/eclipse-openj9/openj9/issues/10489

**Closed by dmitripivkine** 2021-08-24 14:14 UTC
Labels: comp:gc, test failure, segfault
