### ISSUE TITLE
jdk23 OpenJDK java/foreign/TestFree ClassNotFoundException org.testng.DataProviderInvocationException

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19364] opened 2024-04-23 13:31 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/2/
jdk_foreign_0
java/foreign/TestFree.java
```
01:19:10  ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.NoClassDefFoundError: org.testng.DataProviderInvocationException
01:19:10  REASON: User specified action: run testng/othervm --enable-native-access=ALL-UNNAMED TestFree 
01:19:10  TIME:   1.84 seconds
01:19:10  messages:
01:19:10  command: testng --enable-native-access=ALL-UNNAMED TestFree
01:19:10  reason: User specified action: run testng/othervm --enable-native-access=ALL-UNNAMED TestFree 
01:19:10  started: Tue Apr 23 01:18:58 EDT 2024
01:19:10  Mode: othervm [/othervm specified]
01:19:10  finished: Tue Apr 23 01:18:59 EDT 2024
01:19:10  elapsed time (seconds): 1.84
01:19:10  configuration:
01:19:10  STDOUT:
01:19:10  STDERR:
01:19:10  java.lang.NoClassDefFoundError: org.testng.DataProviderInvocationException
01:19:10  	at org.testng.internal.Invoker.<init>(Invoker.java:42)
01:19:10  	at org.testng.TestRunner.init(TestRunner.java:276)
01:19:10  	at org.testng.TestRunner.<init>(TestRunner.java:180)
01:19:10  	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
01:19:10  	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
01:19:10  	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
01:19:10  	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
01:19:10  	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
01:19:10  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
01:19:10  	at org.testng.TestNG.runSuites(TestNG.java:1069)
01:19:10  	at org.testng.TestNG.run(TestNG.java:1037)
01:19:10  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
01:19:10  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
01:19:10  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
01:19:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
01:19:10  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
01:19:10  	at java.base/java.lang.Thread.run(Thread.java:1587)
01:19:10  Caused by: java.lang.ClassNotFoundException: org.testng.DataProviderInvocationException
01:19:10  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)
01:19:10  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
01:19:10  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1102)
01:19:10  	... 17 more
01:19:10  
01:19:10  JavaTest Message: Test threw exception: java.lang.NoClassDefFoundError: org.testng.DataProviderInvocationException
01:19:10  JavaTest Message: shutting down test
```

**Comment by babsingh** [comment] 2024-04-29 18:13
A similar failure is reported in https://github.com/eclipse-openj9/openj9/issues/19373. Marking this as a duplicate of https://github.com/eclipse-openj9/openj9/issues/19373. Closing this issue; future java/foreign/TestFree will be tracked in #19373.

**Closed by babsingh** 2024-04-29 18:13 UTC
Labels: test failure, jdk23
