### ISSUE TITLE
testSoftMxDisclaimMemory crash vmState=0x00020002

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14382] opened 2022-01-27 18:25 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/128 - ub16x64j98
testSoftMxDisclaimMemory_3 `-Xjit -Xgcpolicy:balanced -Xnocompressedrefs`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/128/functional_test_output.tar.gz
```
===============================================
Running test testSoftMxDisclaimMemory_3 ...
===============================================
testSoftMxDisclaimMemory_3 Start Time: Thu Jan 27 00:04:19 2022 Epoch Time (ms): 1643259859042
variation: Mode501
JVM_OPTIONS:  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 
[IncludeExcludeTestAnnotationTransformer] [INFO] EXCLUDE_FILE environment variable: /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../TestConfig/resources/excludes/latest_exclude_17.txt,/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
[IncludeExcludeTestAnnotationTransformer] [INFO] Processing exclude file: /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../TestConfig/resources/excludes/latest_exclude_17.txt
[IncludeExcludeTestAnnotationTransformer] [INFO] Processing exclude file: /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

Unhandled exception
Type=Segmentation error vmState=0x00020002
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F533620B130 Handler2=00007F5335F67CB0 InaccessibleAddress=0000000000000000
RDI=00007F5330086C00 RSI=00007F527C0056C8 RAX=0000000099669966 RBX=0000000000000000
RCX=0000000000000001 RDX=0000000000000003 R8=00007F527C0056C8 R9=0000000000000005
R10=00007F52EF312F88 R11=00007F5330086C00 R12=0000000000000001 R13=00007F532F1E8360
R14=00007F5330086C00 R15=00007F527C0056C8
RIP=00007F532EE18891 GS=0000 FS=0000 RSP=00007F5298C5EB90
EFlags=0000000000010206 CS=0033 RBP=00007F52EF312F38 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 0000000000000bc7 (f: 3015.000000, d: 1.489608e-320)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 0000000000000bc6 (f: 3014.000000, d: 1.489114e-320)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 0000000039347648 (f: 959739456.000000, d: 4.741743e-315)
xmm6 000000003c318000 (f: 1009876992.000000, d: 4.989455e-315)
xmm7 00000000bac00c05 (f: 3133148160.000000, d: 1.547981e-314)
xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 000000003e8c05e2 (f: 1049363968.000000, d: 5.184547e-315)
xmm11 000000003c075284 (f: 1007112832.000000, d: 4.975799e-315)
xmm12 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/jenkins/workspace/Test_openjdk17_j9_extended.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9gc_full29.so
Module_base_address=00007F532ED1F000
Target=2_90_20220126_143 (Linux 4.4.0-170-generic)
CPU=amd64 (4 logical CPUs) (0x5e2f07000 RAM)
----------- Stack Backtrace -----------
(0x00007F532EE18891 [libj9gc_full29.so+0xf9891])
(0x00007F532EE1A300 [libj9gc_full29.so+0xfb300])
(0x00007F532EE1BAC4 [libj9gc_full29.so+0xfcac4])
(0x00007F532EE4CE07 [libj9gc_full29.so+0x12de07])
(0x00007F532EE4C619 [libj9gc_full29.so+0x12d619])
(0x00007F5335F68A13 [libj9prt29.so+0x2aa13])
(0x00007F532EE4C11F [libj9gc_full29.so+0x12d11f])
(0x00007F5335D314F2 [libj9thr29.so+0xe4f2])
(0x00007F5337B076BA [libpthread.so.0+0x76ba])
clone+0x6d (0x00007F533763941D [libc.so.6+0x10741d])
---------------------------------------
```

@dmitripivkine

**Comment by dmitripivkine** [comment] 2022-01-27 21:19
The problem is GC crashed an attempt to scan object `0x00007f52ef312f38` taken from Work Packet but actually the is Linked From Header at this address:
```
0x7F52EF312F38 :  0000000000000001 000000000006d0c8 [ ................ ]
```
Current Work Packet:
```
> !mm_packet 0x00007F52EB7B61E0
MM_Packet at 0x7f52eb7b61e0 {
  Fields for MM_Base:
  Fields for MM_BaseNonVirtual:
	0x0: const U8* _typeId = !j9x 0x0000000000000000
  Fields for MM_Packet:
	0x8: U64* _baseAddress = !j9x 0x00007F52EB7BDD70
	0x10: U64* _basePtr = !j9x 0x00007F52EB7BDD70
	0x18: U64* _topPtr = !j9x 0x00007F52EB7BED70
	0x20: U64* _currentPtr = !j9x 0x00007F52EB7BE8A8 <---
	0x28: U64 _sublistIndex = 0x0000000000000000 (0)
	0x30: class MM_EnvironmentBase* _owner = !mm_environmentvlhgc 0x00007F527C0056C8
	0x38: class MM_Packet* _next = !mm_packet 0x00007F52EB7B62B8
	0x40: class MM_Packet* _previous = !mm_packet 0x0000000000000000
}

> !j9x 0x00007F52EB7BE880,80
0x7F52EB7BE880 :  00007f52ef08d948 00007f52ef08d930 [ H...R...0...R... ]
0x7F52EB7BE890 :  00007f52ef20e598 00007f52ef207c88 [ .. .R....| .R... ]
0x7F52EB7BE8A0 :  00007f52ef207cc8 00007f52ef312f38 [ .| .R...8/1.R... ] <--- WP value points to the hole
0x7F52EB7BE8B0 :  00007f52ef312f60 00007f52ef312f88 [ `/1.R..../1.R... ]
0x7F52EB7BE8C0 :  00007f52ef312fb0 00007f52ef312fd8 [ ./1.R..../1.R... ]
0x7F52EB7BE8D0 :  00007f52ef313000 00007f52ef313028 [ .01.R...(01.R... ]
0x7F52EB7BE8E0 :  00007f52ef313050 00007f52ef313078 [ P01.R...x01.R... ]
0x7F52EB7BE8F0 :  00007f52ef3130a0 00007f52ef3130c8 [ .01.R....01.R... ]
```
This data in work packet is very likely taken from object `!j9indexableobject 0x00007F52EF312328 0 340` (from the end in backward order). There are many elements in WP were copied from this array.

The real problem is **this array as well as it's elements are not marked**, so it is unclear how we end up to copy them to Work packet

**Comment by pshipton** [comment] 2022-02-03 16:45
We seem to be hitting this frequently lately, between the failures recorded here and in the closed duplicate issues. Given that it started failing recently it seems a regression. I've marked it as a blocker. I'm guessing it affects jdk18 as well so this will likely get into the Java 18 milestone plan once we start running more jdk18 builds and confirm this.

**Comment by dmitripivkine** [comment] 2022-02-04 19:59
closing this as a duplicate of https://github.com/eclipse-openj9/openj9/issues/14396

**Closed by dmitripivkine** 2022-02-04 19:59 UTC
Labels: comp:gc, test failure, blocker
