### ISSUE TITLE
OpenJ9 Outputs Incorrect Results At Hot OptLevel of JIT

### ISSUE THREAD

**Issue by Qeryu** [eclipse-openj9/openj9#18919] opened 2024-02-08 13:22 UTC
Java -version output
--------------------

```bash
openjdk version "1.8.0_402-internal"
OpenJDK Runtime Environment (build 1.8.0_402-internal-user_2024_01_31_16_41-b00)
Eclipse OpenJ9 VM (build master-40a4d38b2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240131_000000 (JIT enabled, AOT enabled)
OpenJ9   - 40a4d38b2
OMR      - a74c0935b
JCL      - 33602fcbe7 based on jdk8u402-b06)

javac 1.8.0_402-internal
```
Summary of problem
------------------

When running the code below with OpenJ9, the program sometimes outputs incorrect results (with a very small probability). 

```java
class Test {
    int a() {
        int b = 8;
        return b;
    }

    void h() {
        int d = Integer.valueOf(3);
        d += --d;
        a();
        for (int i = 1; i < 50000; i++) ;
        System.out.println(d);
    }

    public static void main(String[] args) {
        Test test = new Test();
        for (int i = 0; i < 100; i++)
            test.h();
    }
}
```

After adding the `-Xjit:{Test.h(*)*}(optLevel=hot)` option, I can consistently reproduce the incorrect output results. 

Here is a comparison between the results output by OpenJ9 and the results output by other JDKs. 

```
$ diff openj9_result otherjdk_result
39,100c39,100
< 4
< 4
...
< 4
< 4
---
> 5
> 5
...
> 5
> 5
```

This issue may not be related to PRE, as the problem still exists after setting `disablePRE`.

**Comment by pshipton** [comment] 2024-02-08 13:32
@hzongaro fyi

**Comment by hzongaro** [comment] 2024-02-08 14:13
I've reproduced the problem a few times, but not consistently.  However, I suspect that this could be another example of the problem with General Store Sinking reported in issue #17033.

**Comment by hzongaro** [comment] 2024-02-08 20:03
I've found that I'm more likely to reproduce the problem with this modified version of the test:

```
class Test {
    int a() {
        int b = 8;
        return b;
    }

    void h(boolean b) {
        int d = Integer.valueOf(3);
        d += --d;
        if (b) {
            a();
            for (int i = 1; i < 50000; i++) ;
            System.out.println(d);
        }
    }

    public static void main(String[] args) {
        Test test = new Test();
        for (int i = 0; i < 10000; i++)
            test.h(true);
    }
}
```

With that version, before General Store Sinking, we have this IL in block_2:

```
Before General Store Sinking:

n13n      NULLCHK on n328n [#32] ()                                                           [0x7ff3c1102b30] bci=[-1,4,8] rc=0 vc=809 vn=- li=- udi=- nc=1 flg=0x8
n12n        icall  java/lang/Integer.intValue()I[#426  final virtual Method -64] [flags 0x20500 0x0 ] ()  [0x7ff3c1102ae0] bci=[-1,4,8] rc=2 vc=809 vn=- li=- udi=- nc=1 flg=0x8
n328n         aload  <temp slot 5>[#478  Auto] [flags 0x7 0x0 ]                               [0x7ff3c1183640] bci=[3,31,832] rc=1 vc=809 vn=- li=- udi=12 nc=0
n14n      istore  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] ()                               [0x7ff3c1102b80] bci=[-1,7,8] rc=0 vc=809 vn=- li=7 udi=2 nc=1 flg=0x8
n12n        ==>icall
n20n      treetop                                                                             [0x7ff3c1102d60] bci=[-1,9,9] rc=0 vc=809 vn=- li=- udi=- nc=1
n15n        iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )               [0x7ff3c1102bd0] bci=[-1,8,9] rc=2 vc=809 vn=- li=- udi=13 nc=0 flg=0x1000
n19n      istore  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ]                                  [0x7ff3c1102d10] bci=[-1,9,9] rc=0 vc=809 vn=- li=8 udi=3 nc=1
n18n        iadd                                                                              [0x7ff3c1102cc0] bci=[-1,9,9] rc=1 vc=809 vn=- li=- udi=- nc=2
n16n          iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )             [0x7ff3c1102c20] bci=[-1,9,9] rc=1 vc=809 vn=- li=- udi=14 nc=0 flg=0x1000
n17n          iconst -1 (X!=0 X<=0 )                                                          [0x7ff3c1102c70] bci=[-1,9,9] rc=1 vc=809 vn=- li=- udi=- nc=0 flg=0x204
n23n      istore  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ]                                  [0x7ff3c1102e50] bci=[-1,14,9] rc=0 vc=809 vn=- li=9 udi=4 nc=1
n22n        iadd                                                                              [0x7ff3c1102e00] bci=[-1,13,9] rc=1 vc=809 vn=- li=- udi=- nc=2
n15n          ==>iload
n21n          iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )             [0x7ff3c1102db0] bci=[-1,12,9] rc=1 vc=809 vn=- li=- udi=15 nc=0 flg=0x1000
n28n      ificmpne --> block_3 BBStart at n26n ()                                             [0x7ff3c1102fe0] bci=[-1,16,10] rc=0 vc=809 vn=- li=- udi=- nc=2 flg=0x20
n24n        iload  <parm 1 Z>[#422  Parm] [flags 0x40000103 0x0 ] (cannotOverflow )           [0x7ff3c1102ea0] bci=[-1,15,10] rc=1 vc=809 vn=- li=- udi=16 nc=0 flg=0x1000
n25n        iconst 0 (X==0 X>=0 X<=0 )                                                        [0x7ff3c1102ef0] bci=[-1,16,10] rc=1 vc=809 vn=- li=- udi=- nc=0 flg=0x302
n8n       BBEnd </block_2> (cold) =====                                                       [0x7ff3c11029a0] bci=[-1,16,10] rc=0 vc=809 vn=- li=- udi=- nc=0

...

n26n      BBStart <block_3> (freq 0) (cold)                                                   [0x7ff3c1102f40] bci=[0,0,735] rc=0 vc=809 vn=- li=- udi=- nc=0
n32n      treetop ()                                                                          [0x7ff3c1103120] bci=[-1,20,11] rc=0 vc=809 vn=- li=- udi=- nc=1 flg=0x8
n31n        icalli  Test.a()I[#429  virtual Method -64] [flags 0x500 0x0 ] ()                 [0x7ff3c11030d0] bci=[-1,20,11] rc=1 vc=809 vn=- li=- udi=- nc=2 flg=0x8
```

and after:

```
n13n      NULLCHK on n328n [#32] ()                                                           [0x7ff3c1102b30] bci=[-1,4,8] rc=0 vc=855 vn=- li=- udi=- nc=1 flg=0x8
n12n        icall  java/lang/Integer.intValue()I[#426  final virtual Method -64] [flags 0x20500 0x0 ] ()  [0x7ff3c1102ae0] bci=[-1,4,8] rc=2 vc=855 vn=- li=- udi=- nc=1 flg=0x8
n328n         aload  <temp slot 5>[#478  Auto] [flags 0x7 0x0 ]                               [0x7ff3c1183640] bci=[3,31,832] rc=1 vc=855 vn=- li=- udi=12 nc=0
n14n      istore  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] ()                               [0x7ff3c1102b80] bci=[-1,7,8] rc=0 vc=854 vn=- li=- udi=2 nc=1 flg=0x8
n12n        ==>icall
n20n      treetop                                                                             [0x7ff3c1102d60] bci=[-1,9,9] rc=0 vc=853 vn=- li=- udi=- nc=1
n15n        iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )               [0x7ff3c1102bd0] bci=[-1,8,9] rc=2 vc=853 vn=- li=- udi=13 nc=0 flg=0x1000
n19n      istore  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ]                                  [0x7ff3c1102d10] bci=[-1,9,9] rc=0 vc=852 vn=- li=- udi=3 nc=1
n18n        iadd                                                                              [0x7ff3c1102cc0] bci=[-1,9,9] rc=1 vc=852 vn=- li=- udi=- nc=2
n16n          iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )             [0x7ff3c1102c20] bci=[-1,9,9] rc=1 vc=852 vn=- li=- udi=14 nc=0 flg=0x1000
n17n          iconst -1 (X!=0 X<=0 )                                                          [0x7ff3c1102c70] bci=[-1,9,9] rc=1 vc=852 vn=- li=- udi=- nc=0 flg=0x204
n23n      treetop                                                                             [0x7ff3c1102e50] bci=[-1,14,9] rc=0 vc=851 vn=- li=- udi=4 nc=1
n22n        iadd                                                                              [0x7ff3c1102e00] bci=[-1,13,9] rc=1 vc=851 vn=- li=- udi=- nc=2
n15n          ==>iload
n21n          iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )             [0x7ff3c1102db0] bci=[-1,12,9] rc=1 vc=851 vn=- li=- udi=15 nc=0 flg=0x1000
n28n      ificmpne --> block_3 BBStart at n26n ()                                             [0x7ff3c1102fe0] bci=[-1,16,10] rc=0 vc=850 vn=- li=- udi=- nc=2 flg=0x20
n24n        iload  <parm 1 Z>[#422  Parm] [flags 0x40000103 0x0 ] (cannotOverflow )           [0x7ff3c1102ea0] bci=[-1,15,10] rc=1 vc=850 vn=- li=- udi=16 nc=0 flg=0x1000
n25n        iconst 0 (X==0 X>=0 X<=0 )                                                        [0x7ff3c1102ef0] bci=[-1,16,10] rc=1 vc=850 vn=- li=- udi=- nc=0 flg=0x302
n8n       BBEnd </block_2> (cold) =====                                                       [0x7ff3c11029a0] bci=[-1,16,10] rc=0 vc=820 vn=- li=- udi=- nc=0

...

n26n      BBStart <block_3> (freq 0) (cold)                                                   [0x7ff3c1102f40] bci=[0,0,735] rc=0 vc=820 vn=- li=- udi=- nc=0
n382n     istore  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ]                                  [0x7ff3c1184720] bci=[-1,14,9] rc=0 vc=851 vn=- li=- udi=4 nc=1
n383n       iadd                                                                              [0x7ff3c1184770] bci=[-1,13,9] rc=1 vc=851 vn=- li=- udi=- nc=2
n384n         iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )             [0x7ff3c11847c0] bci=[-1,8,9] rc=1 vc=853 vn=- li=- udi=13 nc=0 flg=0x1000
n385n         iload  <auto slot 2>[#427  Auto] [flags 0x3 0x0 ] (cannotOverflow )             [0x7ff3c1184810] bci=[-1,12,9] rc=1 vc=851 vn=- li=- udi=15 nc=0 flg=0x1000

```

Notice in particular the `istore` of `#427` at `n23n` that has been transformed into a `treetop`.  The old version of that stores the sum of the `iload` of `#427` at `n15n` &mdash; from before the `istore` to `#427` at `n19n` &mdash; and the `iload` of `#427` at `n21n` &mdash; from after the `istore` to `#427` at `n19n`.

After store sinking, the store at `n23n` has been moved to `block_3`, where it stores the sum of two `iload`s of `#427` from after the `istore` at `n19n`.

This appears to be a duplicate of #17033.  Once I've created a fix for that problem, I'll verify that it fixes this problem report as well.

**Comment by hzongaro** [comment] 2024-02-08 20:03
Duplicate of #17033

**Closed by hzongaro** 2024-02-08 20:03 UTC
Labels: comp:jit, userRaised
