### ISSUE TITLE
Variable length arguments of jvmtiExtensionFunction

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#14609] opened 2022-02-28 06:35 UTC
I found the following issue with the definition of `jvmtiExtensionFunction`.  There is a mismatch in the placement of the arguments for variadic functions between the caller side and the callee side.  It causes a serious problem on AArch64 macOS, but all other platforms are also affected.

`jvmtiExtensionFunction` is defined as follows in jvmti.h.  It is a function pointer with variable length arguments.

```
typedef jvmtiError (JNICALL *jvmtiExtensionFunction)
	(jvmtiEnv *jvmti_env, ...);
```

https://github.com/eclipse-openj9/openj9/blob/master/runtime/jvmti/jvmtiExtensionMechanism.c contains the bodies of JVMTI extension functions.  Look at the prototypes of some of them:

```
static jvmtiError JNICALL jvmtiGetHeapFreeMemory(jvmtiEnv* jvmti_env, jlong* heapFree_ptr, ...);
static jvmtiError JNICALL jvmtiGetHeapTotalMemory(jvmtiEnv* jvmti_env, jlong* heapTotal_ptr, ...);
static jvmtiError JNICALL jvmtiIterateSharedCaches(jvmtiEnv* env, jint version, const char *cacheDir, jint flags, jboolean useCommandLineValues, jvmtiIterateSharedCachesCallback callback, void *user_data, ...);
```

They take different numbers of arguments of different types.

Let's take a look at `jvmtiIterateSharedCaches()` for example.
Its assembly code expects `env` to be in the register `x0`, `version` in `x1`, `cacheDir` in `x2`, and so on, on AArch64 macOS.

On the other side, its test code in the system test places the arguments `version` and after that on the stack because they are `...` in the `jvmtiExtensionFunction` prototype.
https://github.com/eclipse-openj9/openj9-systemtest/blob/1338a44e1ca12ebfbfa32855bad674957081dc77/openj9.test.sharedClasses.jvmti/src/native/sharedClasses.c#L349-L355

It does not work as expected, of course.

**Comment by knn-k** [comment] 2022-02-28 06:36
I think we need to change the declarations of JVMTI extension functions and use `va_list` / `va_start` / `va_arg`, etc. in the callee side, i.e. jvmtiExtensionMechanism.c, from the C standard perspective.

**Comment by knn-k** [comment] 2022-02-28 07:05
I want comments on how to fix this from variadic function experts.

**Comment by knn-k** [comment] 2022-02-28 07:56
I wrote a small program for demonstrating the issue as attached.  [va_test.zip](https://github.com/eclipse-openj9/openj9/files/8151499/va_test.zip)

Running it on AArch64 Linux shows this.  The caller side passes arguments via registers:
```
(nil) 1 -2 3 4 5.000000
Success
```

AArch64 macOS fails as follows.  The caller side stores the arguments in the stack, except for the first argument `p`:
```
0x0 1835661824 1835661840 1835662040 0 0.000000
Unexpected result 0.000000
```

**Comment by knn-k** [comment] 2022-02-28 08:07
From Apple's documentation https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code:

> The x86_64 and arm64 architectures have different calling conventions for variadic functions—functions with a variable number of parameters. On x86_64, the compiler treats fixed and variadic parameters the same, placing parameters in registers first and only using the stack when no more registers are available. On arm64, the compiler always places variadic parameters on the stack, regardless of whether registers are available. If you implement a function with fixed parameters, but redeclare it with variadic parameters, the mismatch causes unexpected behavior at runtime.

**Comment by pshipton** [comment] 2022-02-28 14:19
@tajila @gacholio fyi

**Comment by gacholio** [comment] 2022-02-28 17:19
So the issue is not the declaration of the type, but rather how we implement the extensions. Changing the implementations to exactly match the prototype seems reasonable.

**Comment by gacholio** [comment] 2022-02-28 21:09
I'll hammer out a fix for this.

**Comment by knn-k** [comment] 2022-03-01 08:56
I did a quick hack with jvmtiExtensionMechanism.c, rewriting some of the JVMTI extension functions in it in the `va_list()` style.
The hack seems to work as expected on AArch64 macOS with SharedClassesAPI tests in extended.system.

**Comment by gacholio** [comment] 2022-03-01 16:31
OK, please go ahead with your solution. If I get mine working (and we feel it's worth doing), I can commit it later.

**Comment by knn-k** [comment] 2022-03-02 00:17
I opened #14622 as a straightforward fix for the variadic functions.

**Comment by knn-k** [comment] 2022-03-02 23:16
Who can review PR #14622?
It passes sanity.functional on all the platforms except Windows.  I didn't run the test on Windows due to limited machine resource.

**Comment by pshipton** [comment] 2022-03-03 00:27
This can be tested on Window, just run it now before the nightly builds, or late in your day so it doesn't expire before the nightly builds finish. I temporarily reduced the nightly build test load for Windows yesterday so the machines are less busy now.

**Comment by pshipton** [comment] 2022-03-03 00:28
Also I see we have more Windows machines back online now.

**Closed** 2022-03-04 16:31 UTC
Labels: comp:vm, arch:aarch64
