### ISSUE TITLE
Crash with Java 21 0.42

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18750] opened 2024-01-12 14:58 UTC
Works with m0, fails with m1 and later.

Changes between 0.42 m0 and m1
https://github.com/eclipse-openj9/openj9/compare/5756d9048...df467094a
https://github.com/eclipse-openj9/openj9-omr/compare/1b52192f5...d810fcb98
https://github.com/ibmruntimes/openj9-openjdk-jdk21/compare/0738d48b5de...f15a87536b1

Running a unit-test with mockito & bytebuddy involved
```
Unhandled exception
Type=Segmentation error vmState=0x00040000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F1D84E437D0 Handler2=00007F1D85198710 InaccessibleAddress=0000000000000017
RDI=000000000000080B RSI=0000000000000000 RAX=00007F1D800311D0 RBX=000000000000020C
RCX=0000000000000013 RDX=00007F1D8159E8A0 R8=00007F1D802CE870 R9=00000000004375D0
R10=00007F1D80034848 R11=0000000000000000 R12=00007F1D802CE870 R13=0000000000017000
R14=FFFFFFFFFFFFFFFF R15=00007F1D81626C90
RIP=00007F1D84878C59 GS=0000 FS=0000 RSP=00007F1D85626D70
EFlags=0000000000010213 CS=0033 RBP=000000000088A700 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000017
xmm0 00000000004375d0 (f: 4421072.000000, d: 2.184300e-317)
xmm1 00000000004375d0 (f: 4421072.000000, d: 2.184300e-317)
xmm2 412e848000000000 (f: 0.000000, d: 1.000000e+06)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 00007f1d84893e37 (f: 2223586816.000000, d: 6.905296e-310)
xmm6 00007f1d815322c8 (f: 2169709312.000000, d: 6.905294e-310)
xmm7 0000003000000020 (f: 32.000000, d: 1.018558e-312)
xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm9 4035555555555555 (f: 1431655808.000000, d: 2.133333e+01)
xmm10 f47c5fba00035df2 (f: 220658.000000, d: -1.300157e+253)
xmm11 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
xmm12 0000000100000001 (f: 1.000000, d: 2.121996e-314)
xmm13 0000008000000080 (f: 128.000000, d: 2.716155e-312)
xmm14 00ff00ff00ff00ff (f: 16711935.000000, d: 7.064161e-304)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/ekmf/.dkmsdev/jdk-21.0.1/lib/default/libj9jvmti29.so
Module_base_address=00007F1D8483F000
Target=2_90_20231017_77 (Linux 6.5.5-200.fc38.x86_64)
CPU=amd64 (4 logical CPUs) (0x1ef71e000 RAM)
----------- Stack Backtrace -----------
recreateRAMClasses+0x1d9 (0x00007F1D84878C59 [libj9jvmti29.so+0x39c59])
redefineClassesCommon.constprop.0+0x370 (0x00007F1D848483B0 [libj9jvmti29.so+0x93b0])
jvmtiRetransformClasses+0x3f3 (0x00007F1D8484B323 [libj9jvmti29.so+0xc323])
retransformClasses+0x1b6 (0x00007F1D85079DE6 [libinstrument.so+0x5de6])
ffi_call_unix64+0x52 (0x00007F1D8500E3CA [libj9vm29.so+0x20e3ca])
ffi_call_int+0x1a1 (0x00007F1D8500D561 [libj9vm29.so+0x20d561])
_ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x11410 (0x00007F1D84EB17E0 [libj9vm29.so+0xb17e0])
bytecodeLoopCompressed+0xca (0x00007F1D84EA03BA [libj9vm29.so+0xa03ba])
 (0x00007F1D84F9B362 [libj9vm29.so+0x19b362])
```

during maven tests
```
Unhandled exception
Type=Segmentation error vmState=0x00040000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00000000103E5FA0 Handler2=000000000FCB7B00 InaccessibleAddress=0000000000000017
RDI=00000000000001B0 RSI=00000000000022EF RAX=00007F786500D620 RBX=00007F785528CA20
RCX=0000000000000018 RDX=0000000000000014 R8=00007F785528CA20 R9=FFFFFFFF00000000
R10=00007F78648466F0 R11=00000F7833404280 R12=000000060091DBE0 R13=0000000000003D1C
R14=FFFFFFFFFFFFFFFF R15=0000000014109400
RIP=000000001014DCD0 GS=0000 FS=0000 RSP=0000700001CD8F60
RFlags=0000000000010202 CS=002B RBP=0000700001CD9100 ERR=0000001700000004
TRAPNO=000000040000000E CPU=0017000000040000 FAULTVADDR=0000000000000017
XMM0 3f50624dd2f1a9fc (f: 3539053056.000000, d: 1.000000e-03)
XMM1 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
XMM2 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
XMM3 4330000000000000 (f: 0.000000, d: 4.503600e+15)
XMM4 412e848000000000 (f: 0.000000, d: 1.000000e+06)
XMM5 0000000000ae0000 (f: 11403264.000000, d: 5.633961e-317)
XMM6 0000000000258000 (f: 2457600.000000, d: 1.214216e-317)
XMM7 0000000002c88000 (f: 46694400.000000, d: 2.307010e-316)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000006 (f: 6.000000, d: 2.964394e-323)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/Users/masson/Documents/jdks/semeru/jdk-21.0.1+12/Contents/Home/lib/default/libj9jvmti29.dylib
Module_base_address=0000000010113000 Symbol=recreateRAMClasses
Symbol_address=000000001014DAF0
Target=2_90_20231017_78 (Mac OS X 12.7)
CPU=amd64 (16 logical CPUs) (0x800000000 RAM)
----------- Stack Backtrace -----------
recreateRAMClasses+0x1e1 (0x000000001014DCD1 [libj9jvmti29.dylib+0x3acd1])
redefineClassesCommon+0x3a7 (0x000000001011D187 [libj9jvmti29.dylib+0xa187])
jvmtiRetransformClasses+0x284 (0x000000001011D934 [libj9jvmti29.dylib+0xa934])
retransformClasses+0x1d1 (0x000000000FF6A481 [libinstrument.dylib+0x4481])
ffi_call_unix64+0x52 (0x000000001061E922 [libj9vm29.dylib+0x270922])
ffi_call_int+0x304 (0x000000001061DFD4 [libj9vm29.dylib+0x26ffd4])
_ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x1ca3a (0x000000001045BBEA [libj9vm29.dylib+0xadbea])
bytecodeLoopCompressed+0xd1 (0x000000001043F1A1 [libj9vm29.dylib+0x911a1])
---------------------------------------
```

**Comment by pshipton** [comment] 2024-01-12 15:47
A reproducer app / testcase that causes a crash. Run it with `JAVA_HOME=/path/to/jdk21 mvn clean test`

[reproApp.tar.gz](https://github.com/eclipse-openj9/openj9/files/13920987/reproApp.tar.gz)

**Comment by tajila** [comment] 2024-01-12 16:47
The heapclass in `recreateRAMClasses` is corrupt

```
		j9object_t protectionDomain = J9VMJAVALANGCLASS_PROTECTIONDOMAIN(currentThread, heapClass);
```

**Comment by tajila** [comment] 2024-01-12 16:50
```
> !j9class 0x69fe00
J9Class at 0x69fe00 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
	0x8: struct J9ROMClass* romClass = !j9romclass 0x00007FCA3CA9D9E0
	0x10: void** superclasses = !j9x 0x00000000006A0048
	0x18: UDATA classDepthAndFlags = 0x00000000080E0001 (135135233)
	0x20: U32 classDepthWithFlags = 0x00000000 (0)
	0x24: U32 classFlags = 0x00000000 (0)
	0x28: struct J9ClassLoader* classLoader = !j9classloader 0x00007FCA3C0DD7E8
	0x30: struct J9Object* classObject = !j9object 0xFFFFFFFFFFFFFFFF<FAULT>
	0x38: volatile UDATA initializeStatus = 0x0000000000000000 (0)
	0x40: struct J9Method* ramMethods = !j9method 0x0000000000000000
	0x48: UDATA* ramStatics = !j9x 0x00000000006A0078
	0x50: struct J9Class* arrayClass = !j9class 0x0000000000000000
	0x58: UDATA totalInstanceSize = 0x000000000000000C (12)
	0x60: struct J9ITable* lastITable = !j9itable 0x000000000069FFF0
	0x68: UDATA* instanceDescription = !j9x 0x0000000000000005
	0x70: UDATA* instanceLeafDescription = !j9x 0x0000000000000001
	0x78: UDATA instanceHotFieldDescription = 0x0000000000000000 (0)
	0x80: UDATA selfReferencingField1 = 0x0000000000000000 (0)
	0x88: UDATA selfReferencingField2 = 0x0000000000000000 (0)
	0x90: struct J9Method* initializerCache = !j9method 0x0000000000000000
	0x98: UDATA romableAotITable = 0x00007FCA425D9D50 (140506673552720)
	0xa0: UDATA packageID = 0x00007FCA3CA9D9E1 (140506577885665)
	0xa8: struct J9Module* module = !j9module 0x0000000000000000
	0xb0: struct J9Class* subclassTraversalLink = !j9class 0x000000000069FE00 // net/bytebuddy/mirror/AccessibleObject
	0xb8: struct J9Class* subclassTraversalReverseLink = !j9class 0x000000000069FE00 // net/bytebuddy/mirror/AccessibleObject
	0xc0: void** iTable = !j9x 0x000000000069FFF0
	0xc8: UDATA castClassCache = 0x0000000000000000 (0)
	0xd0: void** jniIDs = !j9x 0x0000000000000000
	0xd8: UDATA lockOffset = 0x0000000000000004 (4)
	0xe0: U32 paddingForGLRCounters = 0x00000000 (0)
	0xe4: U16 reservedCounter = 0x0000 (0)
	0xe6: U16 cancelCounter = 0x0000 (0)
	0xe8: UDATA newInstanceCount = 0x00000000000003E8 (1000)
	0xf0: IDATA backfillOffset = 0x0000000000000010 (16)
	0xf8: struct J9Class* replacedClass = !j9class 0x0000000000000000
	0x100: UDATA finalizeLinkOffset = 0x0000000000000000 (0)
	0x108: struct J9Class* nextClassInSegment = !j9class 0x0000000000000000
	0x110: UDATA* ramConstantPool = !j9x 0x00000000006A0090
	0x118: struct J9Object** callSites = !j9x 0x0000000000000000
	0x120: struct J9Object** invokeCache = !j9x 0x0000000000000000
	0x128: struct J9Object** varHandleMethodTypes = !j9x 0x0000000000000000
	0x130: struct J9VMCustomSpinOptions* customSpinOption = !j9vmcustomspinoptions 0x0000000000000000
	0x138: void** staticSplitMethodTable = !j9x 0x0000000000000000
	0x140: void** specialSplitMethodTable = !j9x 0x0000000000000000
	0x148: struct J9JITExceptionTable* jitMetaDataList = !j9jitexceptiontable 0x0000000000000000
	0x150: struct J9Class* gcLink = !j9class 0x0000000000000000
	0x158: struct J9Class* hostClass = !j9class 0x000000000069FE00 // net/bytebuddy/mirror/AccessibleObject
	0x160: struct J9Class* nestHost = !j9class 0x0000000000000000
	0x168: struct J9FlattenedClassCache* flattenedClassCache = !j9flattenedclasscache 0x0000000000000000
	0x170: struct J9ClassHotFieldsInfo* hotFieldsInfo = !j9classhotfieldsinfo 0x0000000000000000
}
Class name: net/bytebuddy/mirror/AccessibleObject
To view static fields, use !j9statics 0x000000000069FE00
To view instance shape, use !j9classshape 0x000000000069FE00
```

has a corrupt heapObject `	0x30: struct J9Object* classObject = !j9object 0xFFFFFFFFFFFFFFFF<FAULT>`

**Comment by tajila** [comment] 2024-01-12 16:56
The test passes with `-Xgcpolicy:nogc`

**Comment by dmitripivkine** [comment] 2024-01-12 17:02
>has a corrupt heapObject 	0x30: struct J9Object* classObject = !j9object 0xFFFFFFFFFFFFFFFF<FAULT>

It its not corruption, looks like class is unloaded

**Comment by dmitripivkine** [comment] 2024-01-12 17:04
This class is unloaded indeed, traversal links are set to itself

**Comment by tajila** [comment] 2024-01-12 17:04
If we failed to allocate the classObject it would be NULL. I think -1 would be GC related.

@dmitripivkine is there a valid case for the classObject to be -1 ?

**Comment by tajila** [comment] 2024-01-12 17:13
THe thread is calling `sun/instrument/InstrumentationImpl.retransformClasses0`

THe class array contains

- java.lang.Object
- org.example.MainTest$Some

**Comment by tajila** [comment] 2024-01-12 17:17
The classpairs table has 4590 items. I assume this is because j.l.Object is the class are redefining and we must include subclasses.

**Comment by tajila** [comment] 2024-01-12 17:23
Looking at this sequence:

```
	rc = determineClassesToRecreate(currentThread, class_count, specifiedClasses, &classPairs,
			&methodPairs, jitEventDataPtr, !extensionsEnabled);
	if (rc == JVMTI_ERROR_NONE) {
#if defined(J9VM_OPT_OPENJDK_METHODHANDLE)
		/* Eliminate dark matter so that none will be encountered in prepareToFixMemberNames(). */
		UDATA savedAllowUserHeapWalkFlag = vm->requiredDebugAttributes & J9VM_DEBUG_ATTRIBUTE_ALLOW_USER_HEAP_WALK;
		vm->requiredDebugAttributes |= J9VM_DEBUG_ATTRIBUTE_ALLOW_USER_HEAP_WALK;

		/* This is to help with Metronome to avoid requesting Exclusive if we already have SafePoint, which may not look as Exclusive to the requester thread */
		vm->alreadyHaveExclusive = TRUE;

		vm->memoryManagerFunctions->j9gc_modron_global_collect_with_overrides(currentThread, J9MMCONSTANT_EXPLICIT_GC_EXCLUSIVE_VMACCESS_ALREADY_ACQUIRED);

		vm->alreadyHaveExclusive = FALSE;

		if (0 == savedAllowUserHeapWalkFlag) {
			/* Clear the flag to restore its original value. */
			vm->requiredDebugAttributes &= ~J9VM_DEBUG_ATTRIBUTE_ALLOW_USER_HEAP_WALK;
		}

		/* Identify the MemberNames needing fix-up based on classPairs. */
		memberNamesToFix = prepareToFixMemberNames(currentThread, classPairs);
#endif /* defined(J9VM_OPT_OPENJDK_METHODHANDLE) */

		/* Recreate the RAM classes for all classes */
		rc = recreateRAMClasses(currentThread, classPairs, methodPairs, extensionsUsed, !extensionsEnabled);
		
```

It is possible we create the class list in `determineClassesToRecreate`, then in `j9gc_modron_global_collect_with_overrides` we unload some classes.

Which means by the time we call `recreateRAMClasses` there may be some stale classes.

Does this make sense @gacholio

**Comment by babsingh** [comment] 2024-01-12 17:52
A potential fix for this crash: https://github.com/eclipse-openj9/openj9/pull/18752.

**Comment by babsingh** [comment] 2024-01-15 18:56
0.43 backport: https://github.com/eclipse-openj9/openj9/pull/18762

**Comment by babsingh** [comment] 2024-01-16 01:08
Closing ... fixed by:
- https://github.com/eclipse-openj9/openj9/pull/18752
- https://github.com/eclipse-openj9/openj9/pull/18762

**Closed by babsingh** 2024-01-16 01:08 UTC
Labels: comp:vm, userRaised, segfault

**Comment by pshipton** [comment] 2024-01-19 16:09
@babsingh can we add a test for this condition to avoid regressions like this in the future?

**Comment by babsingh** [comment] 2024-01-19 18:55
> can we add a test for this condition to avoid regressions like this in the future?

I tried to write a small test to reproduce this failure, but I couldn't get the classes to unload before `jvmtiRetransformClasses`. Unloading classes depends on when the GC collects the corresponding `ClassLoader`. @dmitripivkine @tajila Any ideas on how this can be achieved?

If the above is not feasible, we can try adding the provided Mockito test in https://github.com/adoptium/aqa-tests/tree/master/external since it reliably reproduces the failure each time.

**Comment by dmitripivkine** [comment] 2024-01-19 19:07
Calling System GC at appropriate moment might help too - not sure is it possible in this case.

**Comment by gacholio** [comment] 2024-01-20 04:59
> If the above is not feasible, we can try adding the provided Mockito test in https://github.com/adoptium/aqa-tests/tree/master/external since it reliably reproduces the failure each time.

This makes sense, since Mockito has exposed various issues over the years. Running with the GC options @dmitripivkine suggested above would increase the failure rate of any newly-introduced issues (though most new tests end up running across modes, so perhaps this is unncessary).

A test specifically for this change is pointless - it would guard only against someone moving the GC call back to later in the code. I can't imagine any scenario which would warrant this. Hopefully the comment would prevent this occurring (or at least trigger a more in-depth review of the change).

**Comment by babsingh** [comment] 2024-01-22 16:47
I agree with @gacholio. I will discuss with the test team on adding the provided Mockito test in aqa-test.

**Comment by babsingh** [comment] 2024-02-15 22:51
> I will discuss with the test team on adding the provided Mockito test in aqa-test.

Opened https://github.com/adoptium/aqa-tests/issues/5073 for the test case.
