### ISSUE TITLE
Unfreed blocks with  -Xcheck:memory -version

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#16148] opened 2022-10-20 15:32 UTC
```
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/control/CompilationThread.cpp:1051
First 27 bytes:
00007EFC10250260: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation
00007EFC10250270: 54 68 72 65 61 64 2D 30 30 30 00                 Thread-000.
port_shutdown_library describing block at 00007EFC1023FC30 (header at 00007EFC1023FA30):
Wrapped block size is 32, allocation number is 1049
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007EFC1023FC30: 08 90 42 F0 FB 7E 00 00 08 90 42 F0 FB 7E 00 00  ..B..~....B..~..
00007EFC1023FC40: 00 90 62 F0 FB 7E 00 00 20 F7 23 10 FC 7E 00 00  ..b..~.. .#..~..
port_shutdown_library describing block at 00007EFC1023F720 (header at 00007EFC1023F520):
Wrapped block size is 192, allocation number is 1048
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007EFC1023F720: E7 E7 20 F7 23 10 E7 E7 E7 E7 20 F7 23 10 E7 E7  .. .#..... .#...
00007EFC1023F730: E7 E7 20 F7 23 10 E7 E7 E7 E7 20 F7 23 10 E7 E7  .. .#..... .#...
port_shutdown_library describing block at 00007EFC1023E900 (header at 00007EFC1023E700):
Wrapped block size is 272, allocation number is 1045
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007EFC1023E900: 00 00 00 00 00 00 00 00 60 7F F8 0F 00 00 00 00  ........`.......
00007EFC1023E910: E7 E7 00 E9 23 10 E7 E7 E7 E7 00 E9 23 10 E7 E7  ....#.......#...
port_shutdown_library describing block at 00007EFC1023E490 (header at 00007EFC1023E290):
Wrapped block size is 32, allocation number is 1044
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007EFC1023E490: 00 90 42 F0 FB 7E 00 00 00 90 C2 F0 FB 7E 00 00  ..B..~.......~..
00007EFC1023E4A0: 00 90 42 00 FC 7E 00 00 88 58 23 10 FC 7E 00 00  ..B..~...X#..~..
port_shutdown_library describing block at 00007EFC1023DBD0 (header at 00007EFC1023D9D0):
Wrapped block size is 24, allocation number is 1042
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 24 bytes:
00007EFC1023DBD0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00007EFC1023DBE0: 00 00 00 00 01 00 00 00                          ........
port_shutdown_library describing block at 00007EFC1023D040 (header at 00007EFC1023CE40):
Wrapped block size is 352, allocation number is 1040
Block was allocated by /home/tobi/openj9-openjdk-jdk19/openj9/runtime/compiler/control/rossa.cpp:1366
First 32 bytes:
00007EFC1023D040: 70 8A 05 10 FC 7E 00 00 10 00 00 00 C0 00 00 00  p....~..........
00007EFC1023D050: DA 00 00 00 00 00 00 00 00 08 00 00 00 00 00 00  ................
Memory checker statistics:
Total blocks allocated = 15882 ( = most recent allocationNumber)
Total blocks freed = 15845
Total bytes allocated = 37276968
Total bytes freed = 37269482
Total unknown blocks ignored = 0
High water blocks allocated = 6567
High water bytes allocated = 35459677
Largest block ever allocated = size 2707512, allocation number 1334
Failed allocation attempts = 0
37 allocated blocks totaling 7486 bytes were not freed before shutdown!
```

steps to reproduce 

```
./java -Xcheck:memory -Dibm.java9.forceCommonCleanerShutdown=true -version
```

This is not jdk19 specific, I also noticed it in jdk17

**Comment by vij-singh** [comment] 2023-02-14 14:19
@tajila  Should this be moved into the 0.40 milestone given it's not JDK19 or JDK20 specific?

**Comment by tajila** [comment] 2023-02-17 14:35
Yes we can move it

**Comment by 0xdaryl** [comment] 2023-06-05 16:58
A good chunk of this was likely fixed by #16644, but needs to be confirmed.

**Comment by jmesyou** [comment] 2023-06-13 17:38
Problem still present as of:
```
$ java -Xcheck:memory -Dibm.java9.forceCommonCleanerShutdown=true -version

penjdk version "17.0.8-internal" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8-internal+0-adhoc..jdk17)
Eclipse OpenJ9 VM (build master-ca0577640, JRE 17 Linux amd64-64-Bit Compressed References 20230613_000000 (JIT enabled, AOT enabled)
OpenJ9   - 62b7250d5
OMR      - 6b19ba211
JCL      - 5c90aea743b based on jdk-17.0.8+5)
WARNING: 38 unfreed blocks remaining at shutdown!
WARNING: 0 blocks were ignored per ignoredCallsite parameter
WARNING: only 32 most recent leaked blocks will be described
port_shutdown_library describing block at 00007FDD2800A830 (header at 00007FDD2800A630):
Wrapped block size is 1168, allocation number is 20659
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/runtime/MethodMetaData.c:189
First 32 bytes:
00007FDD2800A830: 2F 00 00 00 05 00 00 00 00 00 00 00 00 28 E7 E7  /............(..
00007FDD2800A840: 4F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  O...............
port_shutdown_library describing block at 00007FDD2800A1C0 (header at 00007FDD28009FC0):
Wrapped block size is 544, allocation number is 20657
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/runtime/MethodMetaData.c:189
First 32 bytes:
00007FDD2800A1C0: 15 00 00 00 00 00 00 00 00 00 00 00 00 28 E7 E7  .............(..
00007FDD2800A1D0: 68 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  h...............
port_shutdown_library describing block at 00007FDD28009350 (header at 00007FDD28009150):
Wrapped block size is 2176, allocation number is 20656
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/runtime/MethodMetaData.c:189
First 32 bytes:
00007FDD28009350: 59 00 00 00 04 00 00 00 01 00 00 00 00 28 E7 E7  Y............(..
00007FDD28009360: 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  @...............
port_shutdown_library describing block at 00007FDD7C0177F0 (header at 00007FDD7C0175F0):
Wrapped block size is 24, allocation number is 10443
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/runtime/J9CodeCacheManager.cpp:132
First 24 bytes:
00007FDD7C0177F0: 00 00 00 00 00 00 00 00 38 D7 0D A5 DD 7F 00 00  ........8.......
00007FDD7C017800: 15 00 F0 77 01 7C E7 E7                          ...w.|..
port_shutdown_library describing block at 00007FDD7C01B340 (header at 00007FDD7C01B140):
Wrapped block size is 32, allocation number is 7492
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDD7C01B340: 00 50 88 8C DD 7F 00 00 00 50 88 8C DD 7F 00 00  .P.......P......
00007FDD7C01B350: 00 50 A8 8C DD 7F 00 00 50 DC 01 7C DD 7F 00 00  .P......P..|....
port_shutdown_library describing block at 00007FDD7C01DC50 (header at 00007FDD7C01DA50):
Wrapped block size is 192, allocation number is 7491
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDD7C01DC50: E7 E7 50 DC 01 7C E7 E7 E7 E7 50 DC 01 7C E7 E7  ..P..|....P..|..
00007FDD7C01DC60: E7 E7 50 DC 01 7C E7 E7 E7 E7 50 DC 01 7C E7 E7  ..P..|....P..|..
port_shutdown_library describing block at 00007FDDA06B3F60 (header at 00007FDDA06B3D60):
Wrapped block size is 192, allocation number is 4730
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/MethodToBeCompiled.cpp:40
First 32 bytes:
00007FDDA06B3F60: 00 00 00 00 00 00 00 00 10 A7 61 A7 DD 7F 00 00  ..........a.....
00007FDDA06B3F70: 00 00 00 00 00 00 00 00 C8 A9 8B 0C 00 00 00 00  ................
port_shutdown_library describing block at 00007FDD780169C0 (header at 00007FDD780167C0):
Wrapped block size is 32, allocation number is 4446
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDD780169C0: 00 50 68 8C DD 7F 00 00 00 50 68 8C DD 7F 00 00  .Ph......Ph.....
00007FDD780169D0: 00 50 88 8C DD 7F 00 00 70 77 01 78 DD 7F 00 00  .P......pw.x....
port_shutdown_library describing block at 00007FDD78017770 (header at 00007FDD78017570):
Wrapped block size is 192, allocation number is 4445
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDD78017770: E7 E7 70 77 01 78 E7 E7 E7 E7 70 77 01 78 E7 E7  ..pw.x....pw.x..
00007FDD78017780: E7 E7 70 77 01 78 E7 E7 E7 E7 70 77 01 78 E7 E7  ..pw.x....pw.x..
port_shutdown_library describing block at 00007FDD800105D0 (header at 00007FDD800103D0):
Wrapped block size is 32, allocation number is 2713
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDD800105D0: 00 50 48 8C DD 7F 00 00 00 50 48 8C DD 7F 00 00  .PH......PH.....
00007FDD800105E0: 00 50 68 8C DD 7F 00 00 30 F8 00 80 DD 7F 00 00  .Ph.....0.......
port_shutdown_library describing block at 00007FDD8000F830 (header at 00007FDD8000F630):
Wrapped block size is 192, allocation number is 2712
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDD8000F830: E7 E7 30 F8 00 80 E7 E7 E7 E7 30 F8 00 80 E7 E7  ..0.......0.....
00007FDD8000F840: E7 E7 30 F8 00 80 E7 E7 E7 E7 30 F8 00 80 E7 E7  ..0.......0.....
port_shutdown_library describing block at 00007FDDA025AE30 (header at 00007FDDA025AC30):
Wrapped block size is 48, allocation number is 1232
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA025AE30: 4A 49 54 20 44 69 61 67 6E 6F 73 74 69 63 20 43  JIT Diagnostic C
00007FDDA025AE40: 6F 6D 70 69 6C 61 74 69 6F 6E 20 54 68 72 65 61  ompilation Threa
port_shutdown_library describing block at 00007FDDA025A9C0 (header at 00007FDDA025A7C0):
Wrapped block size is 38, allocation number is 1231
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 32 bytes:
00007FDDA025A9C0: 4A 49 54 20 44 69 61 67 6E 6F 73 74 69 63 20 43  JIT Diagnostic C
00007FDDA025A9D0: 6F 6D 70 69 6C 61 74 69 6F 6E 20 54 68 72 65 61  ompilation Threa
port_shutdown_library describing block at 00007FDDA0258FA0 (header at 00007FDDA0258DA0):
Wrapped block size is 37, allocation number is 1210
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0258FA0: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0258FB0: 54 68 72 65 61 64 2D 30 30 36 20 53 75 73 70 65  Thread-006 Suspe
port_shutdown_library describing block at 00007FDDA0258B30 (header at 00007FDDA0258930):
Wrapped block size is 27, allocation number is 1209
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0258B30: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0258B40: 54 68 72 65 61 64 2D 30 30 36 00                 Thread-006.
port_shutdown_library describing block at 00007FDDA0258120 (header at 00007FDDA0257F20):
Wrapped block size is 37, allocation number is 1187
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0258120: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0258130: 54 68 72 65 61 64 2D 30 30 35 20 53 75 73 70 65  Thread-005 Suspe
port_shutdown_library describing block at 00007FDDA0257CB0 (header at 00007FDDA0257AB0):
Wrapped block size is 27, allocation number is 1186
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0257CB0: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0257CC0: 54 68 72 65 61 64 2D 30 30 35 00                 Thread-005.
port_shutdown_library describing block at 00007FDDA0256290 (header at 00007FDDA0256090):
Wrapped block size is 37, allocation number is 1165
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0256290: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA02562A0: 54 68 72 65 61 64 2D 30 30 34 20 53 75 73 70 65  Thread-004 Suspe
port_shutdown_library describing block at 00007FDDA0255E20 (header at 00007FDDA0255C20):
Wrapped block size is 27, allocation number is 1164
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0255E20: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0255E30: 54 68 72 65 61 64 2D 30 30 34 00                 Thread-004.
port_shutdown_library describing block at 00007FDDA0255410 (header at 00007FDDA0255210):
Wrapped block size is 37, allocation number is 1143
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0255410: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0255420: 54 68 72 65 61 64 2D 30 30 33 20 53 75 73 70 65  Thread-003 Suspe
port_shutdown_library describing block at 00007FDDA0254FA0 (header at 00007FDDA0254DA0):
Wrapped block size is 27, allocation number is 1142
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0254FA0: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0254FB0: 54 68 72 65 61 64 2D 30 30 33 00                 Thread-003.
port_shutdown_library describing block at 00007FDDA0253580 (header at 00007FDDA0253380):
Wrapped block size is 37, allocation number is 1121
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0253580: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0253590: 54 68 72 65 61 64 2D 30 30 32 20 53 75 73 70 65  Thread-002 Suspe
port_shutdown_library describing block at 00007FDDA0253110 (header at 00007FDDA0252F10):
Wrapped block size is 27, allocation number is 1120
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0253110: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0253120: 54 68 72 65 61 64 2D 30 30 32 00                 Thread-002.
port_shutdown_library describing block at 00007FDDA0252700 (header at 00007FDDA0252500):
Wrapped block size is 37, allocation number is 1099
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0252700: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0252710: 54 68 72 65 61 64 2D 30 30 31 20 53 75 73 70 65  Thread-001 Suspe
port_shutdown_library describing block at 00007FDDA0252290 (header at 00007FDDA0252090):
Wrapped block size is 27, allocation number is 1098
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0252290: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA02522A0: 54 68 72 65 61 64 2D 30 30 31 00                 Thread-001.
port_shutdown_library describing block at 00007FDDA0250810 (header at 00007FDDA0250610):
Wrapped block size is 37, allocation number is 1077
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1107
First 32 bytes:
00007FDDA0250810: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0250820: 54 68 72 65 61 64 2D 30 30 30 20 53 75 73 70 65  Thread-000 Suspe
port_shutdown_library describing block at 00007FDDA0250200 (header at 00007FDDA0250000):
Wrapped block size is 27, allocation number is 1076
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/control/CompilationThread.cpp:1106
First 27 bytes:
00007FDDA0250200: 4A 49 54 20 43 6F 6D 70 69 6C 61 74 69 6F 6E 20  JIT Compilation 
00007FDDA0250210: 54 68 72 65 61 64 2D 30 30 30 00                 Thread-000.
port_shutdown_library describing block at 00007FDDA02427B0 (header at 00007FDDA02425B0):
Wrapped block size is 32, allocation number is 1063
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDDA02427B0: 08 50 28 8C DD 7F 00 00 08 50 28 8C DD 7F 00 00  .P(......P(.....
00007FDDA02427C0: 00 50 48 8C DD 7F 00 00 A0 22 24 A0 DD 7F 00 00  .PH......"$.....
port_shutdown_library describing block at 00007FDDA02422A0 (header at 00007FDDA02420A0):
Wrapped block size is 192, allocation number is 1062
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDDA02422A0: E7 E7 A0 22 24 A0 E7 E7 E7 E7 A0 22 24 A0 E7 E7  ..."$......"$...
00007FDDA02422B0: E7 E7 A0 22 24 A0 E7 E7 E7 E7 A0 22 24 A0 E7 E7  ..."$......"$...
port_shutdown_library describing block at 00007FDDA0241480 (header at 00007FDDA0241280):
Wrapped block size is 272, allocation number is 1059
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDDA0241480: 00 00 00 00 00 00 00 00 40 A3 F5 0F 00 00 00 00  ........@.......
00007FDDA0241490: E7 E7 80 14 24 A0 E7 E7 E7 E7 80 14 24 A0 E7 E7  ....$.......$...
port_shutdown_library describing block at 00007FDDA0241010 (header at 00007FDDA0240E10):
Wrapped block size is 32, allocation number is 1058
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 32 bytes:
00007FDDA0241010: 00 50 28 8C DD 7F 00 00 00 50 A8 8C DD 7F 00 00  .P(......P......
00007FDDA0241020: 00 50 28 9C DD 7F 00 00 E8 7E 23 A0 DD 7F 00 00  .P(......~#.....
port_shutdown_library describing block at 00007FDDA0240750 (header at 00007FDDA0240550):
Wrapped block size is 24, allocation number is 1056
Block was allocated by /workspaces/openj9-openjdk-development/jdk17/openj9/runtime/compiler/env/RawAllocator.hpp:71
First 24 bytes:
00007FDDA0240750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00007FDDA0240760: 00 00 00 00 01 00 00 00                          ........
Memory checker statistics:
Total blocks allocated = 20730 ( = most recent allocationNumber)
Total blocks freed = 20692
Total bytes allocated = 27462791
Total bytes freed = 27451929
Total unknown blocks ignored = 0
High water blocks allocated = 5912
High water bytes allocated = 24305644
Largest block ever allocated = size 2097152, allocation number 1583
Failed allocation attempts = 0
38 allocated blocks totaling 10862 bytes were not freed before shutdown!
```

**Comment by mpirvu** [comment] 2023-08-23 14:15
Looking at the code I don't see any attempt to delete the data cache or code cache.
In order to do so we must be absolutely sure that all Java activity has stopped  and there is no chance to execute cached code. In past I have seen rare instances where, as part of stopping and detaching the compilation threads, some Java code gets executed.

The operating system is going to free all memory associated with the terminated JVM. The question is: if we attempt to delete every single piece of memory, will this delay the shutdown time? Also, how important is to have a short shutdown time?

**Comment by mpirvu** [comment] 2023-08-23 14:40
For reference:
openj9/runtime/compiler/runtime/MethodMetaData.c:189
This refers to allocations for the StackMapTable used to accelerate stack walking. It's an optional mechanism and in theory we should be able to free that memory provided we take precautions to avoid races (must ensure that no Java code is running)


openj9/runtime/compiler/runtime/J9CodeCacheManager.cpp:132
This refers to code cache allocations, though the line number does not seem right.

openj9/runtime/compiler/env/RawAllocator.hpp:71
This is too generic to tell what it is used for.

openj9/runtime/compiler/control/MethodToBeCompiled.cpp:40
This refers to allocations for compilation requests. We should be able to delete this after compilations have been shutdown.

openj9/runtime/compiler/control/CompilationThread.cpp:1106 and 1107
These refers to strings allocated to hold the names of the compilation thread. These too can be freed once the compilation threads have been shutdown.

**Comment by jmesyou** [comment] 2023-08-24 19:50
I'm going to close this issue for now as these unfreed blocks are seen as not worth freeing. As the JIT is already in the process of shutdown, these blocks will be eventually freed by the operating system.

As for the issue of longer/shorter shutdown times, there isn't a specific case to motivate one or the other. If/when such a case arises, I think a separate issue can be opened to tackle that problem.

**Closed by jmesyou** 2023-08-24 19:50 UTC
Labels: comp:jit

**Comment by hzongaro** [comment] 2023-08-28 12:54
Changing the reason for closing it. . . .
