### ISSUE TITLE
[aix_ppc-64] SE80_GIT cmdLineTester_LazyClassLoading_0 Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17266] opened 2023-04-25 11:42 UTC
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=58686159)(`aix71p9-02`):
```
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pap6480sr9-20230328_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20230424_49966 (JIT enabled, AOT enabled)
OpenJ9   - 109ad89
OMR      - 32fb3af
IBM      - b7435ac)
JCL - 20230320_01 based on Oracle jdk8u371-b10
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test cmdLineTester_LazyClassLoading_0 ...
===============================================
cmdLineTester_LazyClassLoading_0 Start Time: Mon Apr 24 22:21:02 2023 Epoch Time (ms): 1682389262444
"/bluebird/builds/bld_49966/sdk/ap6480/bin/java" -Xshareclasses:destroyAll; "/bluebird/builds/bld_49966/sdk/ap6480/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
JVMSHRC005I No shared class caches available
JVMSHRC005I No shared class caches available
cache cleanup done
variation: Mode110
JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 
{ itercnt=1; \
mkdir -p "/tmp/bld_49966/cmdLineTester_LazyClassLoading_0"; \
cd "/tmp/bld_49966/cmdLineTester_LazyClassLoading_0"; \
export LIBPATH=":/bluebird/builds/bld_49966/sdk/ap6480/jre/bin/../lib/default:/bluebird/builds/bld_49966/sdk/ap6480/jre/bin/../lib/ppc64/default:/bluebird/builds/bld_49966/sdk/ap6480/jre/bin/j9vm"; \
        "/bluebird/builds/bld_49966/sdk/ap6480/bin/java" "-Xshareclasses:none" -Xdump -DJ9JAR="/bluebird/builds/bld_49966/jvmtest/test/SE80/functional/cmdLineTests/lazyClassLoadingTest/lazyClassLoadingTest.jar" \
-DRESJAR="/bluebird/builds/bld_49966/jvmtest/test/SE80/functional/cmdline_options_testresources/cmdlinetestresources.jar" -DEXE='"/bluebird/builds/bld_49966/sdk/ap6480/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump' -jar "/bluebird/builds/bld_49966/jvmtest/test/SE80/functional/cmdline_options_tester/cmdlinetester.jar" \
-config "/bluebird/builds/bld_49966/jvmtest/test/SE80/functional/cmdLineTests/lazyClassLoadingTest/lazyClassLoading.xml" \
-nonZeroExitWhenError; \
if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_LazyClassLoading_0""_PASSED"; echo ""; cd /bluebird/builds/bld_49966/jvmtest/test/SE80;  else perl "-I/bluebird/builds/bld_49966/../../javatest/HEAD_382595/test/lib/perl" -mResultStore::Uploader -e "ResultStore::Uploader::upload('.',49966,58686159,'filesystem:/cores/tmp','results-58686159')"; echo ""; echo "cmdLineTester_LazyClassLoading_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/tmp/bld_49966/TestTargetResult";
*** Starting test suite: Lazy classloading tests ***
Testing: testJniDefineClass
Test start time: 2023/04/24 22:21:03 Eastern Standard Time
Running command: "/bluebird/builds/bld_49966/sdk/ap6480/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump -classpath "/bluebird/builds/bld_49966/jvmtest/test/SE80/functional/cmdLineTests/lazyClassLoadingTest/lazyClassLoadingTest.jar" j9vm.test.classloader.LazyClassLoaderInitTest testJniDefineClass
Time spent starting: 80 milliseconds
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000033
Handler1=09001000A935E400 Handler2=09001000A9335620
R0=FFFFFFFFFFFFFFFF R1=0000010022FF4F80 R2=09001000A94A2D68 R3=0000000000000000
R4=0000010010416B18 R5=0000010022F74000 R6=0000000000000000 R7=0000000000000000
R8=0000000000008000 R9=0000000000000000 R10=000000000000002F R11=0000000000000000
R12=09001000A01492C0 R13=0000010022FFF800 R14=00000000302349A8 R15=0000000030180D00
R16=0000010020E9E0B8 R17=0000010022994978 R18=0000000000000017 R19=0000000000000000
R20=0000010022FF5138 R21=0000000000000000 R22=09001000A930EE10 R23=09001000A930E3C0
R24=000001001017C7D0 R25=09001000A93EEE70 R26=0000000000000000 R27=09001000A93E9458
R28=0000000030234A60 R29=0000000000000000 R30=0000010010416B18 R31=0000000000000000
IAR=09000000E91335F0 LR=09000000E9130050 MSR=A00000000200D032 CTR=0900000000597680
CR=221488202000000C FPSCR=8200000000000000 XER=2000000C82000000
FPR0 0000000000000001 (f: 1.000000, d: 4.940656e-324)
FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
FPR2 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
FPR3 433000000003702d (f: 225325.000000, d: 4.503600e+15)
FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
FPR6 410b816800000000 (f: 0.000000, d: 2.253250e+05)
FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR8 43300000000274b3 (f: 160947.000000, d: 4.503600e+15)
FPR9 3f41d8f5c50d5c80 (f: 3305987072.000000, d: 5.446625e-04)
FPR10 4028bbd12a16a514 (f: 706127104.000000, d: 1.236683e+01)
FPR11 3fd55555555450ef (f: 1431589120.000000, d: 3.333333e-01)
FPR12 4530000000000000 (f: 0.000000, d: 1.934281e+25)
FPR13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/bluebird/builds/bld_49966/sdk/ap6480/jre/bin/../lib/ppc64/default/libj9thr29.so
Module_base_address=09000000E912B000
Target=2_90_20230424_49966 (AIX 7.1)
CPU=ppc64 (32 logical CPUs) (0x100000000 RAM)
----------- Stack Backtrace -----------
(0x09000000E9130050 [libj9thr29.so+0x5050])
JVM_GetSystemPackage_Impl+0x400 (0x09000000E8C17304 [libjclse29.so+0x95304])
JVM_GetSystemPackage+0x4c (0x09000000E69183B0 [libjvm.so+0x103b0])
JVM_GetSystemPackage+0x4c (0x09000000E68E4090 [libjvm.so+0x5090])
Java_java_lang_Package_getSystemPackage0+0x10 (0x09000000E8C5D094 [libjava.so+0x16094])
(0x00000100105FD900)
sendLoadClass+0x274 (0x09000000E69C7918 [libj9vm29.so+0x63918])
internalFindClassInModule+0x28f0 (0x09000000E69A14D4 [libj9vm29.so+0x3d4d4])
resolveClassRef+0x1c8 (0x09000000E69E5FCC [libj9vm29.so+0x81fcc])
(0x09000000E6B7F8A8 [libj9vm29.so+0x21b8a8])
(0x09000000E69CEB68 [libj9vm29.so+0x6ab68])
runJavaThread+0x268 (0x09000000E69CCFAC [libj9vm29.so+0x68fac])
javaProtectedThreadProc__FP13J9PortLibraryPv+0x120 (0x09000000E6966B24 [libj9vm29.so+0x2b24])
(0x09000000E6C90444 [libj9prt29.so+0x58444])
javaThreadProc+0x7c (0x09000000E69668E0 [libj9vm29.so+0x28e0])
(0x09000000E6C1A4F0 [libj9thr29.so+0x44f0])
_pthread_body+0xf0 (0x0900000000571E14 [libpthreads.a+0x3e14])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2023/04/24 22:21:04 - please wait.

FAILED test targets:
        cmdLineTester_LazyClassLoading_0

TOTAL: 1   EXECUTED: 1   PASSED: 0   FAILED: 1   DISABLED: 0   SKIPPED: 0
```

[50x internal grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=50029)

The native stacktrace is similar w/
* https://github.com/eclipse-openj9/openj9/issues/11839
which failed consistently.

This test passed on April 4th and earlier runs. (probably marked by other failure/pt)

[Internal OpenJ9 diff](https://github.ibm.com/runtimes/openj9/compare/720505531152ba...cebc4407ed7f64)

**Comment by pshipton** [comment] 2023-04-25 15:30
Dup of https://github.com/eclipse-openj9/openj9/issues/17198

We believe this was caused by https://github.com/eclipse-openj9/openj9/pull/17109

It should be already fixed via https://github.com/eclipse-openj9/openj9/pull/17246 which didn't make it into the build last night, we can verify it tonight.

**Comment by pshipton** [comment] 2023-04-26 02:46
Passing [now](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=58786094)

**Closed by pshipton** 2023-04-26 02:46 UTC
Labels: comp:vm, test failure
