### ISSUE TITLE
JDK17 0.28 M1 ParallelStreamsLoadTest_special_J9_27_FAILED - Segmentation error vmState=0x00000000 - Compiled_method=java/util/TimSort.binarySort([Ljava/lang/Object;IIILjava/util/Comparator;)V

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13410] opened 2021-08-30 13:07 UTC
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_x86-64_mac_Release/2/tapResults/ (`osx1011-x86-2`)
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64macRelease)
Eclipse OpenJ9 VM (build v0.28.0-release-18bebe9f4e3, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210828_2 (JIT enabled, AOT enabled)
OpenJ9   - 18bebe9f4e3
OMR      - 1d0a329e26b
JCL      - 712145ee3f5 based on jdk-17+35)
```
[Re-run the Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=system&PLATFORM=x86-64_mac&TARGET=ParallelStreamsLoadTest_special_J9_27)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test ParallelStreamsLoadTest_special_J9_27 ...
===============================================
ParallelStreamsLoadTest_special_J9_27 Start Time: Sun Aug 29 04:49:04 2021 Epoch Time (ms): 1630226944660
variation: -Xgcpolicy:gencon -Xgc:dynamicBreadthFirstScanOrdering
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:dynamicBreadthFirstScanOrdering 

LT  stderr EFlags 10602, EFlags & 0x400 = 400, DF flag is set
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000000
LT  stderr Handler1=0000000003C37CC0 Handler2=000000000332B020
LT  stderr RDI=00000000C54285AC RSI=00000000C54285A8 RAX=00000000C53C9928 RBX=0000000000000065
LT  stderr RCX=0000000000000002 RDX=0000000000017B1B R8=0000000000000063 R9=0000000000000002
LT  stderr R10=00000000C3E15BD8 R11=00000000C3E16078 R12=0000000000000013 R13=0000000000017B1B
LT  stderr R14=0000000000000002 R15=0000000000000004
LT  stderr RIP=000000001CA47FC6 GS=0000 FS=0000 RSP=0000000006558370
LT  stderr RFlags=0000000000010602 CS=002B RBP=0000000006550B00 ERR=428AC01000000000
LT  stderr TRAPNO=000000000000000D CPU=C010000000000000 FAULTVADDR=00000000428AC010
LT  stderr XMM0 000000002da4d8d8 (f: 765778112.000000, d: 3.783447e-315)
LT  stderr XMM1 00000000c02ad930 (f: 3224033536.000000, d: 1.592884e-314)
LT  stderr XMM2 00000000065583e8 (f: 106267624.000000, d: 5.250318e-316)
LT  stderr XMM3 0000000000000019 (f: 25.000000, d: 1.235164e-322)
LT  stderr XMM4 0000000000017b19 (f: 97049.000000, d: 4.794858e-319)
LT  stderr XMM5 000000000e1f0000 (f: 236912640.000000, d: 1.170504e-315)
LT  stderr XMM6 3fde24881a7c6c26 (f: 444361760.000000, d: 4.709797e-01)
LT  stderr XMM7 402fe2804e87b348 (f: 1317516160.000000, d: 1.594239e+01)
LT  stderr XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr 
LT  stderr Compiled_method=java/util/TimSort.binarySort([Ljava/lang/Object;IIILjava/util/Comparator;)V
LT  stderr Target=2_90_20210828_2 (Mac OS X 10.11.6)
LT  stderr CPU=amd64 (4 logical CPUs) (0x200000000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr ---------------------------------------
LT  stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/29 04:49:39 - please wait.

STF 04:49:45.771 - =====================   R E S U L T S   =====================
STF 04:49:45.771 - Stage results:
STF 04:49:45.771 -   setUp:     pass
STF 04:49:45.771 -   execute:  *fail*
STF 04:49:45.771 -   teardown:  pass
STF 04:49:45.771 - 
STF 04:49:45.771 - Overall result: **FAILED**

ParallelStreamsLoadTest_special_J9_27_FAILED
```

**Comment by JasonFengJ9** [comment] 2021-09-03 17:56
`TestJlmRemoteClassAuth_0` failed w/  `Segmentation error vmState=0x00000000` at `Compiled_method=net/adoptopenjdk/stf/environment/properties/OrderedProperties.getProperty(Ljava/lang/String;)Ljava/lang/String;` [1]
A separated issue can be raised if they are determined not same problem.

```
===============================================
Running test TestJlmRemoteClassAuth_0 ...
===============================================
TestJlmRemoteClassAuth_0 Start Time: Fri Sep  3 00:45:23 2021 Epoch Time (ms): 1630644323763
variation: Mode150
JVM_OPTIONS:  -XX:+UseCompressedOops 

GEN stderr Unhandled exception
GEN stderr Type=Segmentation error vmState=0x00000000
GEN stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
GEN stderr Handler1=000076949F2B4970 Handler2=000076949F1EC300
GEN stderr R0=000076947DF51CA8 R1=00007694A012CC00 R2=0000000000000000 R3=0000000100000016
GEN stderr R4=0000000000000000 R5=0000000080A13BC0 R6=FFFFFFFFFFFFFFFF R7=000076949C030038
GEN stderr R8=0000000000186398 R9=000000000000000E R10=000076947DF51CA8 R11=00000000005A7778
GEN stderr R12=0000000042002442 R13=00007694A01368E0 R14=0000000000186390 R15=00000000000A0700
GEN stderr R16=000076949C030038 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=0000000000000000
GEN stderr R20=0000000000000000 R21=0000000000000000 R22=0000000000000001 R23=0000000000000001
GEN stderr R24=0000000000000009 R25=000000008092D218 R26=00000000FFC9FA40 R27=0000000080BB8998
GEN stderr R28=0000000080A13BC0 R29=0000000080A13BC0 R30=0000000080BB8998 R31=00000000FFE3BF18
GEN stderr NIP=000076947DF51CBC MSR=800000010280F033 ORIG_GPR3=00000000000081C8 CTR=000076947DF51CA8
GEN stderr LINK=000076947DF51CA8 XER=0000000000000000 CCR=0000000082002844 SOFTE=0000000000000001
GEN stderr TRAP=0000000000000300 DAR=0000000000000020 dsisr=0000000040000000 RESULT=0000000000000000
GEN stderr FPR0 0000000000000005 (f: 5.000000, d: 2.470328e-323)
GEN stderr FPR1 40543ae020000000 (f: 536870912.000000, d: 8.091993e+01)
GEN stderr FPR2 3fe8000000000000 (f: 0.000000, d: 7.500000e-01)
GEN stderr FPR3 3fee666660000000 (f: 1610612736.000000, d: 9.500000e-01)
GEN stderr FPR4 3fce840b4ac4e4d2 (f: 1254417664.000000, d: 2.384047e-01)
GEN stderr FPR5 bfe7154748bef6c8 (f: 1220474624.000000, d: -7.213475e-01)
GEN stderr FPR6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
GEN stderr FPR7 3fcbc2860d224770 (f: 220350320.000000, d: 2.168739e-01)
GEN stderr FPR8 006900750073002d (f: 7536685.000000, d: 1.112616e-306)
GEN stderr FPR9 3809401d00000000 (f: 0.000000, d: 9.275548e-39)
GEN stderr FPR10 bfe034c9f18318b9 (f: 4051900672.000000, d: -5.064440e-01)
GEN stderr FPR11 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
GEN stderr FPR12 4113639c00000000 (f: 0.000000, d: 3.176710e+05)
GEN stderr FPR13 0000000000000003 (f: 3.000000, d: 1.482197e-323)
GEN stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
GEN stderr 
GEN stderr Compiled_method=net/adoptopenjdk/stf/environment/properties/OrderedProperties.getProperty(Ljava/lang/String;)Ljava/lang/String;
GEN stderr Target=2_90_20210902_12 (Linux 4.15.0-96-generic)
GEN stderr CPU=ppc64le (16 logical CPUs) (0x1fdc70000 RAM)
GEN stderr ----------- Stack Backtrace -----------
GEN stderr (0x000076947DF51CBC [<unknown>+0x0])
GEN stderr (0x000076949F28ECD0 [libj9vm29.so+0x1ecd0])
GEN stderr (0x000076949F290168 [libj9vm29.so+0x20168])
GEN stderr (0x000076949D627CE4 [libjclse29.so+0x87ce4])
GEN stderr JVM_InvokeMethod+0x40 (0x000076949F8D76E0 [libjvm.so+0x276e0])
GEN stderr JVM_InvokeMethod+0x34 (0x00007694A0136814 [libjvm.so+0x6814])
GEN stderr Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x000076947C15C5B4 [libjava.so+0xc5b4])
GEN stderr (0x000076947D53E524 [<unknown>+0x0])
GEN stderr (0x000076949F28E5C0 [libj9vm29.so+0x1e5c0])
GEN stderr (0x000076949F2B9060 [libj9vm29.so+0x49060])
GEN stderr (0x000076949F3E9998 [libj9vm29.so+0x179998])
GEN stderr (0x000076949F1ED708 [libj9prt29.so+0x3d708])
GEN stderr (0x000076949F3E9A6C [libj9vm29.so+0x179a6c])
GEN stderr (0x000076949F2BBA94 [libj9vm29.so+0x4ba94])
GEN stderr (0x000076949F2B8678 [libj9vm29.so+0x48678])
GEN stderr (0x00007694A042CD98 [libjli.so+0xcd98])
GEN stderr (0x00007694A0431E28 [libjli.so+0x11e28])
GEN stderr (0x00007694A03D885C [libpthread.so.0+0x885c])
GEN stderr clone+0x98 (0x00007694A02C9028 [libc.so.6+0x159028])
GEN stderr ---------------------------------------
GEN stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/09/03 00:45:26 - please wait.

TestJlmRemoteClassAuth_0_FAILED
```

[1] https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64le_linux_Nightly/13/tapResults/

**Comment by pshipton** [comment] 2021-09-08 22:45
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_2/2
DaaLoadTest_daa2_special_5m_1
-Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_special.system_x86-64_mac_Personal_testList_2/2/system_test_output.tar.gz
```
DLT stderr Type=Segmentation error vmState=0x00000000
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000000
DLT stderr Handler1=000000000E837D80 Handler2=000000000EAF8FC0
DLT stderr RDI=000000001174D590 RSI=000000001174D588 RAX=0000000000000015 RBX=0000000000000000
DLT stderr RCX=0000000000000004 RDX=0000000000000001 R8=0000000000000002 R9=0000000000000000
DLT stderr R10=0000000000000017 R11=0000000011746D30 R12=0000000011746C08 R13=000000001174D558
DLT stderr R14=000000001174D558 R15=00000000000000B8
DLT stderr RIP=000000009C7D328A GS=0000 FS=0000 RSP=00007FCA8982EF50
DLT stderr RFlags=0000000000010602 CS=002B RBP=00007FCA89386100 ERR=0000000000000000
DLT stderr TRAPNO=000000000000000D CPU=0000000000000000 FAULTVADDR=0000000000000000
DLT stderr XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM1 000000004e800000 (f: 1317011456.000000, d: 6.506901e-315)
DLT stderr XMM2 002e006e00750073 (f: 7667827.000000, d: 8.344494e-308)
DLT stderr XMM3 3e21c8b6b27fb757 (f: 2994714368.000000, d: 2.070334e-09)
DLT stderr XMM4 3ebc581f0388d4e2 (f: 59299040.000000, d: 1.689447e-06)
DLT stderr XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM6 3fe41d8fe84672ae (f: 3896931072.000000, d: 6.286087e-01)
DLT stderr XMM7 402e7f9c1e980fa9 (f: 513281952.000000, d: 1.524924e+01)
DLT stderr XMM8 0000000041400000 (f: 1094713344.000000, d: 5.408603e-315)
DLT stderr XMM9 00000000009d84b9 (f: 10323129.000000, d: 5.100303e-317)
DLT stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr 
DLT stderr Compiled_method=java/util/TimSort.binarySort([Ljava/lang/Object;IIILjava/util/Comparator;)V
DLT stderr Target=2_90_20210904_6 (Mac OS X 10.11.6)
DLT stderr CPU=amd64 (4 logical CPUs) (0x200000000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr ---------------------------------------
```

**Comment by pshipton** [comment] 2021-09-08 22:45
I'm going to set this as blocker since the first two failures aren't count=0

**Comment by jdmpapin** [comment] 2021-09-09 23:39
I ran a few grinders based on the first two crashes posted here:
- [Mac passed 30/30](https://openj9-jenkins.osuosl.org/job/Grinder/191/)
- [Linux PPCLE passed 30/30](https://openj9-jenkins.osuosl.org/job/Grinder/192/)
- [Mac passed another 100/100](https://openj9-jenkins.osuosl.org/job/Grinder/193/)

**Comment by pshipton** [comment] 2021-09-10 00:36
Maybe fixed. Doesn't look like a blocker anyway.

**Comment by jdmpapin** [comment] 2021-09-10 21:04
My grinders just above were running builds from May, e.g.
```
[2021-09-07T19:44:28.899Z] openjdk version "17" 2021-09-14
[2021-09-07T19:44:28.899Z] OpenJDK Runtime Environment AdoptOpenJDK-17+18-202105042338 (build 17+18-202105042338)
[2021-09-07T19:44:28.899Z] Eclipse OpenJ9 VM AdoptOpenJDK-17+18-202105042338 (build master-ea475bb65, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210505_282 (JIT enabled, AOT enabled)
[2021-09-07T19:44:28.899Z] OpenJ9   - ea475bb65
[2021-09-07T19:44:28.899Z] OMR      - 79c52c726
[2021-09-07T19:44:28.899Z] JCL      - 780fa63b0b based on jdk-17+18)
```
This is apparently the default thing that happens when following the links under "For example, to rebuild the failed tests" and leaving SDK_RESOURCE set to nightly

So please disregard the above links. I will re-test

**Comment by pshipton** [comment] 2021-09-11 01:16
@llxia fyi the previous comment, I'm thinking the nightly option in grinders should be removed or disabled for OpenJ9 builds until such time as it works, Not sure how many people are hitting this issue when trying to recreate problems.

**Comment by JasonFengJ9** [comment] 2021-09-11 02:49
This is a known issue `backlog/issues/542`. The grinder nightly uses Adopt builds which stopped update since this May.

**Comment by llxia** [comment] 2021-09-13 20:47
Please use the `Rerun in Grinder` link in the [jenkins job](https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_x86-64_mac_Release/2/), not the link in the console output.

<img src=https://user-images.githubusercontent.com/19273206/133152523-5dfc7431-8471-4736-8177-7527d67ae830.png width=400/>

We will change the default option of SDK_RESOURCE in openj9 and hyc jenkins and maybe remove the rerun link from the console output.

**Comment by jdmpapin** [comment] 2021-09-13 21:15
The link in the console output is more convenient because it pre-populates TARGET. Could it be made to work rather than removed?

**Comment by llxia** [comment] 2021-09-14 12:50
The `nightly` feature in Grinder uses Adopt API which does not have openj9 nightly anymore. What you will get from Adopt API is the last uploaded SDK in May. Currently, we do not have API setup for openj9 nightly builds. 
Once we have the API setup for openj9 nightly, then we can update `nightly` in Grinder to point to the new API.

**Comment by 0xdaryl** [comment] 2021-09-14 14:11
We did the work to verify that the floating point semantics are correctly followed by the JIT for JDK17 for all the processor architectures OpenJ9 supports.  There is cleanup work required to remove legacy strictFP paths from the JIT.  I don't plan on forcing the cleanup work into JDK17.

**Comment by 0xdaryl** [comment] 2021-09-15 14:10
What is the next action on this issue?  Re-launching grinders ensuring the latest build is being used to try and reproduce the problem?

**Comment by llxia** [comment] 2021-09-16 14:56
Running ParallelStreamsLoadTest_special_J9_27 in [ Grinder (100x) ](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/18181/) with the latest nightly.
```
00:02:07.057  openjdk version "17-beta" 2021-09-14
00:02:07.057  IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17-beta+35-202109160424)
00:02:07.057  Eclipse OpenJ9 VM 17.0.0.0-m1 (build master-3b519ed3e, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210916_32 (JIT enabled, AOT enabled)
00:02:07.057  OpenJ9   - 3b519ed3e
00:02:07.057  OMR      - c818b04c6
00:02:07.057  JCL      - 23999d8072 based on jdk-17+35)
```

**Comment by JasonFengJ9** [comment] 2021-09-17 20:43
A `segmentation error` similar w/ https://github.com/eclipse-openj9/openj9/issues/13410#issuecomment-912711246 observed at `job/Test_openjdk17_j9_sanity.system_ppc64le_linux_testList_2/51/` (`rhel8le-rt1-2`)
```
openjdk version "17-beta" 2021-09-14
IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17-beta+35-202109170405)
Eclipse OpenJ9 VM 17.0.0.0-m1 (build master-6450b817d, JRE 17 Linux ppc64le-64-Bit Compressed References 20210917_36 (JIT enabled, AOT enabled)
OpenJ9   - 6450b817d
OMR      - c92c51518
JCL      - 23999d8072 based on jdk-17+35)

[2021-09-17T12:33:34.707Z] Running test DaaLoadTest_daa2_CS_5m_0 ...
[2021-09-17T12:33:34.707Z] ===============================================
[2021-09-17T12:33:34.707Z] DaaLoadTest_daa2_CS_5m_0 Start Time: Fri Sep 17 05:33:33 2021 Epoch Time (ms): 1631882013932
[2021-09-17T12:33:34.707Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-09-17T12:33:34.707Z] JVMSHRC005I No shared class caches available
[2021-09-17T12:33:34.707Z] JVMSHRC005I No shared class caches available
[2021-09-17T12:33:34.707Z] cache cleanup done
[2021-09-17T12:33:34.707Z] variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
[2021-09-17T12:33:34.707Z] JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge 

[2021-09-17T12:33:38.681Z] GEN 05:33:38.064 - Using Mode NoOptions. Values = ''
[2021-09-17T12:33:38.681Z] GEN stderr Unhandled exception
[2021-09-17T12:33:38.681Z] GEN stderr Type=Segmentation error vmState=0x00000000
[2021-09-17T12:33:38.681Z] GEN stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2021-09-17T12:33:38.681Z] GEN stderr Handler1=00007FFFAFDB4F90 Handler2=00007FFFAFCEC300
[2021-09-17T12:33:38.681Z] GEN stderr R0=00007FFF92955410 R1=00007FFFB4C0CC60 R2=0000000000000000 R3=000000010000001F
[2021-09-17T12:33:38.681Z] GEN stderr R4=0000000000000000 R5=0000000088CB6F10 R6=FFFFFFFFFFFFFFFF R7=00007FFF90A50038
[2021-09-17T12:33:38.681Z] GEN stderr R8=000000000017B388 R9=000000000000000E R10=00007FFF92955410 R11=0000000000580D78
[2021-09-17T12:33:38.682Z] GEN stderr R12=0000000048002424 R13=00007FFFB4C168E0 R14=000000000017B380 R15=0000000000095700
[2021-09-17T12:33:38.682Z] GEN stderr R16=00007FFF90A50038 R17=FFFFFFFFFFFFFFFF R18=0000000100000000 R19=00000000FFE049B8
[2021-09-17T12:33:38.682Z] GEN stderr R20=00007FFFB4C0CF20 R21=0000000000000001 R22=0000000000000000 R23=00000000000BC100
[2021-09-17T12:33:38.682Z] GEN stderr R24=000000000000007B R25=00000000FFCF6D08 R26=0000000088CB6F10 R27=0000000088CB6F10
[2021-09-17T12:33:38.682Z] GEN stderr R28=00000000FFF706F8 R29=0000000088E52D18 R30=0000000088E52D18 R31=00000000FFD36CD0
[2021-09-17T12:33:38.682Z] GEN stderr NIP=00007FFF92955424 MSR=800000000280F033 ORIG_GPR3=C0000000000027E0 CTR=00007FFF92955410
[2021-09-17T12:33:38.682Z] GEN stderr LINK=00007FFF92955410 XER=0000000000000000 CCR=0000000088002844 SOFTE=0000000000000001
[2021-09-17T12:33:38.682Z] GEN stderr TRAP=0000000000000300 DAR=0000000000000020 dsisr=0000000040000000 RESULT=0000000000000000
[2021-09-17T12:33:38.682Z] GEN stderr FPR0 0000000000000005 (f: 5.000000, d: 2.470328e-323)
[2021-09-17T12:33:38.682Z] GEN stderr FPR1 40540405a0000000 (f: 2684354560.000000, d: 8.006284e+01)
[2021-09-17T12:33:38.682Z] GEN stderr FPR2 3fe8000000000000 (f: 0.000000, d: 7.500000e-01)
[2021-09-17T12:33:38.682Z] GEN stderr FPR3 3fee666660000000 (f: 1610612736.000000, d: 9.500000e-01)
[2021-09-17T12:33:38.682Z] GEN stderr FPR4 3fce840b4ac4e4d2 (f: 1254417664.000000, d: 2.384047e-01)
[2021-09-17T12:33:38.682Z] GEN stderr FPR5 bfe7154748bef6c8 (f: 1220474624.000000, d: -7.213475e-01)
[2021-09-17T12:33:38.682Z] GEN stderr FPR6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
[2021-09-17T12:33:38.682Z] GEN stderr FPR7 3faaa5aa5df25984 (f: 1576163712.000000, d: 5.204518e-02)
[2021-09-17T12:33:38.682Z] GEN stderr FPR8 006b006400730032 (f: 7536690.000000, d: 1.201608e-306)
[2021-09-17T12:33:38.682Z] GEN stderr FPR9 0061006d0069002d (f: 6881325.000000, d: 7.565991e-307)
[2021-09-17T12:33:38.682Z] GEN stderr FPR10 38094019c0000000 (f: 3221225472.000000, d: 9.275529e-39)
[2021-09-17T12:33:38.682Z] GEN stderr FPR11 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR13 0000000000000003 (f: 3.000000, d: 1.482197e-323)
[2021-09-17T12:33:38.682Z] GEN stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.682Z] GEN stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-09-17T12:33:38.683Z] GEN stderr 
[2021-09-17T12:33:38.688Z] GEN stderr Compiled_method=net/adoptopenjdk/stf/environment/properties/OrderedProperties.getProperty(Ljava/lang/String;)Ljava/lang/String;
[2021-09-17T12:33:38.688Z] GEN stderr Target=2_90_20210917_36 (Linux 4.18.0-305.17.1.el8_4.ppc64le)
[2021-09-17T12:33:38.688Z] GEN stderr CPU=ppc64le (4 logical CPUs) (0x1dd1f0000 RAM)
[2021-09-17T12:33:38.688Z] GEN stderr ----------- Stack Backtrace -----------
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFF92955424 [<unknown>+0x0])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFD8ECF0 [libj9vm29.so+0x1ecf0])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFD90188 [libj9vm29.so+0x20188])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAD837724 [libjclse29.so+0x87724])
[2021-09-17T12:33:38.688Z] GEN stderr JVM_InvokeMethod+0x40 (0x00007FFFB43C76E0 [libjvm.so+0x276e0])
[2021-09-17T12:33:38.688Z] GEN stderr JVM_InvokeMethod+0x34 (0x00007FFFB4C16814 [libjvm.so+0x6814])
[2021-09-17T12:33:38.688Z] GEN stderr Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00007FFF9065C5B4 [libjava.so+0xc5b4])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFF924D08A4 [<unknown>+0x0])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFD8E5E0 [libj9vm29.so+0x1e5e0])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFDB9680 [libj9vm29.so+0x49680])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFEE9ED8 [libj9vm29.so+0x179ed8])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFCED708 [libj9prt29.so+0x3d708])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFEE9FAC [libj9vm29.so+0x179fac])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFDBC0B4 [libj9vm29.so+0x4c0b4])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFAFDB8C98 [libj9vm29.so+0x48c98])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFB4EFCD98 [libjli.so+0xcd98])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFB4F01E28 [libjli.so+0x11e28])
[2021-09-17T12:33:38.688Z] GEN stderr (0x00007FFFB4EA8878 [libpthread.so.0+0x8878])
[2021-09-17T12:33:38.688Z] GEN stderr clone+0x74 (0x00007FFFB4D82F68 [libc.so.6+0x132f68])
[2021-09-17T12:33:38.688Z] GEN stderr ---------------------------------------
[2021-09-17T12:33:38.688Z] GEN stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/09/17 05:33:38 - please wait.

[2021-09-17T12:33:43.416Z] DaaLoadTest_daa2_CS_5m_0_FAILED
```

**Comment by 0xdaryl** [comment] 2021-09-20 15:17
The original problem (https://github.com/eclipse-openj9/openj9/issues/13410#issue-982773471) and the other macOS reported problem (https://github.com/eclipse-openj9/openj9/issues/13410#issuecomment-915622936) are duplicates of the backwards arraycopy problem #9782 which has only ever been observed on macOS.

The Power Linux crashes reported above must be a different problem and warrant a separate issue, which I'll open.

**Comment by 0xdaryl** [comment] 2021-09-20 15:24
Closing the originally reported macOS problem as a dup of #9782.  Power failures are tracked by #13537.

**Closed by 0xdaryl** 2021-09-20 15:24 UTC
Labels: comp:jit, test failure, blocker, segfault
