### ISSUE TITLE
JDK19 OpenJDK java/lang/reflect/exeCallerAccessTest/CallerAccessTest.java IllegalAccessException JNI attached native thread (null caller frame) cannot access class jdk.internal.misc.Unsafe

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16132] opened 2022-10-19 17:21 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_Nightly/29
jdk_lang_1
java/lang/reflect/exeCallerAccessTest/CallerAccessTest.java
```
23:27:02  STDERR:
23:27:02  Exception in thread "main" java.lang.IllegalAccessException: JNI attached native thread (null caller frame) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc
23:27:02  	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:447)
23:27:02  	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:396)
23:27:02  	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:709)
23:27:02  	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1140)
23:27:02  	at java.base/java.lang.reflect.Field.get(Field.java:425)
23:27:02  Exception in thread "main" java.lang.IllegalAccessException: JNI attached native thread (null caller frame) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc
23:27:02  	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:447)
23:27:02  	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessEx
```

**Comment by pshipton** [comment] 2022-10-19 17:26
@tajila fyi

**Comment by mikezhang1234567890** [comment] 2022-10-24 15:02
Taking a look at this.

**Comment by mikezhang1234567890** [comment] 2022-10-24 16:29
The exception occurs on successful runs too. The reason for the test failure is a timeout:

```
[2022-10-19T03:27:02.622Z] TEST RESULT: Error. Agent error: java.lang.Exception: Agent 16 timed out with a timeout of 960 seconds; check console log for any additional details
```

Seems to be a similar issue as https://github.com/eclipse-openj9/openj9/issues/16134 and https://github.com/eclipse-openj9/openj9/issues/16083.

**Comment by tajila** [comment] 2022-10-24 20:51
@mikezhang1234567890 is the test intermittent? If we double the timeout will it pass?

**Comment by mikezhang1234567890** [comment] 2022-10-24 20:57
Looks intermittent for `java/util/concurrent/ThreadPoolExecutor/ConfigChanges.java` and `java/lang/System/LoggerFinder/internal/BootstrapLogger/BootstrapLoggerTest.java` from grinders. I haven't managed to reproduce the error for `CallerAccessTest.java` here. Will try with a higher timeout.

**Comment by tajila** [comment] 2022-11-01 13:58
@mikezhang1234567890 was this reproduce-able with external machines, if not we can close it

**Comment by mikezhang1234567890** [comment] 2022-11-01 15:25
Was not able to reproduce this or https://github.com/eclipse-openj9/openj9/issues/16134 and https://github.com/eclipse-openj9/openj9/issues/16083 on external machines.

**Comment by tajila** [comment] 2022-11-01 19:34
okay thanks

**Closed by tajila** 2022-11-01 19:34 UTC
Labels: comp:vm, test failure, jdk19
