### ISSUE TITLE
JDK11 0.27.1 : cmdLineTester_GCCheck tests fail on Power10 pLinux due to core file not found

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse-openj9/openj9#13464] opened 2021-09-07 20:59 UTC
On Power10 pLinux, `cmdLineTester_GCCheck` fails due to  java.lang.ClassNotFoundException: org.openj9.test.nogc.Main. 

Details: 

```
Testing: Create core file
Test start time: 2021/09/02 20:01:47 Eastern Standard Time
Running command: "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs -XX:+PortableSharedCache -Xmx256m -cp /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar:/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcCheck/gcCheck.jar -Xdump:system:file=j9core.dmp,events=vmstop,request=exclusive+compact org.openj9.test.nogc.Main
Time spent starting: 10 milliseconds
Time spent executing: 7197 milliseconds
Test result: FAILED
Output from test:
 [ERR] Error: Could not find or load main class org.openj9.test.nogc.Main
 [ERR] Caused by: java.lang.ClassNotFoundException: org.openj9.test.nogc.Main
 [ERR] JVMDUMP039I Processing dump event "vmstop", detail "#0000000000000001" at 2021/09/02 20:01:47 - please wait.
 [ERR] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16306270675781/cmdLineTester_GCCheck_0/j9core.dmp' in response to an event
 [ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.170387.
 [ERR] 
 [ERR] JVMDUMP012E Error in System dump: The core file created by child process with pid = 170387 was not found. Expected to find core file with name "/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16306270675781/cmdLineTester_GCCheck_0/core.170387"
 [ERR] JVMDUMP013I Processed dump event "vmstop", detail "#0000000000000001".
>> Success condition was not found: [Output match: System dump written]

Testing: Run gccheck
Test start time: 2021/09/02 20:01:55 Eastern Standard Time
Running command: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
Time spent starting: 2 milliseconds
Time spent executing: 1070 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Could not load dump file and/or could not load XML file: Image file '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16306270675781/cmdLineTester_GCCheck_0/j9core.dmp' not found.
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: Checking HEAP...done]
>> Failure condition was not found: [Output match: gc check]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: Exception]
```

Jenkins build link: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/17905/

Grinder link (reproduced 5/5 times): https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/17949 

Note: The issue is [not reproducible](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/17953/console) on non-power10 pLinux machines using the same SDK: 

```
16:53:52  Testing: Create core file
16:53:53  Test start time: 2021/09/07 13:53:52 Pacific Standard Time
16:53:53  Running command: "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xmx256m -cp /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar:/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcCheck/gcCheck.jar -Xdump:system:file=j9core.dmp,events=vmstop,request=exclusive+compact org.openj9.test.nogc.Main
16:53:53  Time spent starting: 34 milliseconds
16:53:54  Time spent executing: 1410 milliseconds
16:53:54  Test result: PASSED
16:53:54  
16:53:54  Testing: Run gccheck
16:53:54  Test start time: 2021/09/07 13:53:53 Pacific Standard Time
16:53:54  Running command: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
16:53:54  Time spent starting: 7 milliseconds
16:54:14  Time spent executing: 19449 milliseconds
16:54:14  Test result: PASSED
16:54:14  
16:54:14  
16:54:14  ---TEST RESULTS---
16:54:14  Number of PASSED tests: 2 out of 2
16:54:14  Number of FAILED tests: 0 out of 2
```

Java Version details: 

```
16:33:11  java version "11.0.12" 2021-07-20
16:33:11  IBM Semeru Runtime Certified Edition 11.0.12.1 (build 11.0.12+7)
16:33:11  Eclipse OpenJ9 VM 11.0.12.1 (build openj9-0.27.1, JRE 11 Linux ppc64le-64-Bit Compressed References 20210828_160 (JIT enabled, AOT enabled)
16:33:11  OpenJ9   - c8200b180
16:33:11  OMR      - 3965a1655
16:33:11  JCL      - 821ace41e2 based on jdk-11.0.12+7)
16:33:11  =JAVA VERSION OUTPUT END=
16:33:11  =RELEASE INFO BEGIN=
16:33:11  IMPLEMENTOR="International Business Machines Corporation"
16:33:11  IMPLEMENTOR_VERSION="11.0.12.1"
16:33:11  JAVA_VERSION="11.0.12"
16:33:11  JAVA_VERSION_DATE="2021-07-20"
```

**Comment by pshipton** [comment] 2021-09-07 21:06
Does the `/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcCheck/gcCheck.jar` contain the expected class?

**Comment by pshipton** [comment] 2021-09-07 21:07
Is this specific to using `-XX:+PortableSharedCache` ?

**Comment by Mesbah-Alam** [comment] 2021-09-07 21:34
>Is this specific to using -XX:+PortableSharedCache ?

No. The same failure is reproducible on `p10rhel005` even without -XX:+PortableSharedCache option: 
 
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/17955/console

>Does the /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcCheck/gcCheck.jar contain the expected class?

It should, as the same test is [working fine](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/17953/console) on a different pLinux machine (not power10) where we compile the gcCheck.jar in exactly the same way: 

```
16:47:25        [jar] Building jar: /home/jenkins/workspace/Grinder/jvmtest/functional/cmdLineTests/gcCheck/gcCheck.jar
16:47:25       [copy] Copying 4 files to /home/jenkins/workspace/Grinder/jvmtest/functional/cmdLineTests/gcCheck
```

The error seems to be only happening on `p10rhel005` (both with and without -XX:+PortableSharedCache).

**Comment by pshipton** [comment] 2021-09-07 22:21
@zl-wang fyi

**Comment by pshipton** [comment] 2021-09-08 12:40
The problem here is not the missing class, which I believe is a long standing known issue with the test, as per https://github.com/eclipse-openj9/openj9/issues/12463

I believe the problem is the core file pattern and configured limits i.e. a machine setup issue, same as https://github.com/eclipse-openj9/openj9/issues/13462#issuecomment-914663647
```
 [ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.170387.
 [ERR] 
 [ERR] JVMDUMP012E Error in System dump: The core file created by child process with pid = 170387 was not found. Expected to find core file with name "/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16306270675781/cmdLineTester_GCCheck_0/core.170387"
```

**Comment by llxia** [comment] 2021-09-13 12:59
The only p10 (p10rhel005) is down (see runtimes/infrastructure/issues/5920). We will rerun the test once the machine is back online.

**Comment by llxia** [comment] 2021-09-14 19:56
The core file pattern problem is fixed on the machine and the [test passed](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/18133). Close this issue.

**Closed by llxia** 2021-09-14 19:56 UTC
Labels: test failure, arch:power
