### ISSUE TITLE
DaaLoadTest_all_CS_5m_0 crash vmState=0x00020003

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13206] opened 2021-07-15 19:34 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly_testList_1/45/ - cent6-x64-6
DaaLoadTest_all_CS_5m_0
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly_testList_1/45/system_test_output.tar.gz
```
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00020003
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
DLT stderr Handler1=00007F8D65A01DC0 Handler2=00007F8D65760AE0 InaccessibleAddress=0000000000000018
DLT stderr RDI=0000000000000000 RSI=00007F8D6039AAC8 RAX=00007F8D64A70988 RBX=0000000083958E60
DLT stderr RCX=0000000083958E60 RDX=0000000083A54C00 R8=000000000001F7B4 R9=0000000083958E58
DLT stderr R10=000000008334D618 R11=00007F8D646E95A0 R12=00007F8D683B4000 R13=0000000000000000
DLT stderr R14=00007F8D6003F780 R15=00007F8D60064070
DLT stderr RIP=00007F8D646E7E73 GS=0000 FS=0000 RSP=00007F8D4559DE00
DLT stderr EFlags=0000000000010246 CS=0033 RBP=00000000000FBDA0 ERR=0000000000000004
DLT stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000018
DLT stderr xmm0 0000000042a96db4 (f: 1118399872.000000, d: 5.525630e-315)
DLT stderr xmm1 000000003e3ab283 (f: 1044034176.000000, d: 5.158214e-315)
DLT stderr xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr xmm3 000000003e572c23 (f: 1045900352.000000, d: 5.167434e-315)
DLT stderr xmm4 000000003dc81097 (f: 1036521600.000000, d: 5.121097e-315)
DLT stderr xmm5 3f05d84bb950f4bf (f: 3109090560.000000, d: 4.166585e-05)
DLT stderr xmm6 3fc5cfbfd40a3947 (f: 3557439744.000000, d: 1.704025e-01)
DLT stderr xmm7 0000000042843512 (f: 1115960576.000000, d: 5.513578e-315)
DLT stderr xmm8 3fee1b00f62e015a (f: 4130210048.000000, d: 9.407964e-01)
DLT stderr xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr xmm10 41612a8800000000 (f: 0.000000, d: 9.000000e+06)
DLT stderr xmm11 bfd180bb4b651000 (f: 1264914432.000000, d: -2.734822e-01)
DLT stderr xmm12 3f80ecf4c2a50800 (f: 3265595392.000000, d: 8.264458e-03)
DLT stderr xmm13 4008000000000000 (f: 0.000000, d: 3.000000e+00)
DLT stderr xmm14 4018000000000000 (f: 0.000000, d: 6.000000e+00)
DLT stderr xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/jre/lib/amd64/default/libj9gc29.so
DLT stderr Module_base_address=00007F8D645B2000
DLT stderr Target=2_90_20210714_58 (Linux 2.6.32-754.35.1.el6.x86_64)
DLT stderr CPU=amd64 (4 logical CPUs) (0x1f40ff000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr (0x00007F8D646E7E73 [libj9gc29.so+0x135e73])
DLT stderr (0x00007F8D64701330 [libj9gc29.so+0x14f330])
DLT stderr (0x00007F8D64701A8E [libj9gc29.so+0x14fa8e])
DLT stderr (0x00007F8D64701F3D [libj9gc29.so+0x14ff3d])
DLT stderr (0x00007F8D646E447E [libj9gc29.so+0x13247e])
DLT stderr (0x00007F8D647005D7 [libj9gc29.so+0x14e5d7])
DLT stderr (0x00007F8D646FEFB4 [libj9gc29.so+0x14cfb4])
DLT stderr (0x00007F8D646FF6AC [libj9gc29.so+0x14d6ac])
DLT stderr (0x00007F8D647787F6 [libj9gc29.so+0x1c67f6])
DLT stderr (0x00007F8D646C20E6 [libj9gc29.so+0x1100e6])
DLT stderr (0x00007F8D646DEAEA [libj9gc29.so+0x12caea])
DLT stderr (0x00007F8D646D813A [libj9gc29.so+0x12613a])
DLT stderr (0x00007F8D64723EBA [libj9gc29.so+0x171eba])
DLT stderr (0x00007F8D64728A51 [libj9gc29.so+0x176a51])
DLT stderr (0x00007F8D646C20E6 [libj9gc29.so+0x1100e6])
DLT stderr (0x00007F8D6478C50D [libj9gc29.so+0x1da50d])
DLT stderr (0x00007F8D6476C228 [libj9gc29.so+0x1ba228])
DLT stderr (0x00007F8D646EACD5 [libj9gc29.so+0x138cd5])
DLT stderr (0x00007F8D646EAEA6 [libj9gc29.so+0x138ea6])
DLT stderr (0x00007F8D646E9FF5 [libj9gc29.so+0x137ff5])
DLT stderr (0x00007F8D646EFAAB [libj9gc29.so+0x13daab])
DLT stderr (0x00007F8D645F90A9 [libj9gc29.so+0x470a9])
DLT stderr (0x00007F8D59C93C4D [libj9jit29.so+0x938c4d])
DLT stderr (0x00007F8D59CA8401 [libj9jit29.so+0x94d401])
DLT stderr ---------------------------------------
```

@dmitripivkine fyi

**Comment by dmitripivkine** [comment] 2021-07-15 20:15
reconstructed top of the c-stack manually
```
DLT stderr (0x00007F8D646E7E73 [libj9gc29.so+0x135e73])	<_ZN41MM_SweepPoolManagerAddressOrderedListBase13addFreeMemoryEP18MM_EnvironmentBaseP21MM_ParallelSweepChunkPmm+83>
DLT stderr (0x00007F8D64701330 [libj9gc29.so+0x14f330])	<_ZN22MM_ParallelSweepScheme10sweepChunkEP18MM_EnvironmentBaseP21MM_ParallelSweepChunk+432>
DLT stderr (0x00007F8D64701A8E [libj9gc29.so+0x14fa8e])	<_ZN22MM_ParallelSweepScheme14sweepAllChunksEP18MM_EnvironmentBasem+302
DLT stderr (0x00007F8D64701F3D [libj9gc29.so+0x14ff3d])	<_ZN22MM_ParallelSweepScheme13internalSweepEP18MM_EnvironmentBase+61>
DLT stderr (0x00007F8D646E447E [libj9gc29.so+0x13247e])	<_ZN21MM_ParallelDispatcher3runEP18MM_EnvironmentBaseP7MM_Taskm+158>
DLT stderr (0x00007F8D647005D7 [libj9gc29.so+0x14e5d7])	<_ZN22MM_ParallelSweepScheme19sweepForMinimumSizeEP18MM_EnvironmentBaseP17MM_MemorySubSpaceP22MM_AllocateDescription+263>
DLT stderr (0x00007F8D646FEFB4 [libj9gc29.so+0x14cfb4])	<_ZN19MM_ParallelGlobalGC5sweepEP18MM_EnvironmentBaseP22MM_AllocateDescriptionb+68>
DLT stderr (0x00007F8D646FF6AC [libj9gc29.so+0x14d6ac])	<_ZN19MM_ParallelGlobalGC24mainThreadGarbageCollectEP18MM_EnvironmentBaseP22MM_AllocateDescriptionbb+444>
DLT stderr (0x00007F8D647787F6 [libj9gc29.so+0x1c67f6])	<_ZN15MM_ConcurrentGC22internalGarbageCollectEP18MM_EnvironmentBaseP17MM_MemorySubSpaceP22MM_AllocateDescription+38>
DLT stderr (0x00007F8D646C20E6 [libj9gc29.so+0x1100e6])	<_ZN12MM_Collector14garbageCollectEP18MM_EnvironmentBaseP17MM_MemorySubSpaceP22MM_AllocateDescriptionjP28MM_ObjectAllocationInterfaceS3_P20MM_AllocationContext+182>
DLT stderr (0x00007F8D646DEAEA [libj9gc29.so+0x12caea])	<_ZN17MM_MemorySubSpace14garbageCollectEP18MM_EnvironmentBaseP22MM_AllocateDescriptionj+266>
```

ad instruction it crashed at
```
0x7f8d646e7e73 <_ZN41MM_SweepPoolManagerAddressOrderedListBase13addFreeMemoryEP18MM_EnvironmentBaseP21MM_ParallelSweepChunkPmm+83>:
    mov    0x18(%rdi),%rax
```

**Comment by dmitripivkine** [comment] 2021-07-15 21:35
In `!mm_parallelsweepchunk 0x00007F8D683B4000` there is `freeListTail = !mm_heaplinkedfreeheader 0x000000008347AC68`
```
> !mm_heaplinkedfreeheader 0x000000008347AC68
MM_HeapLinkedFreeHeader at 0x8347ac68 {
  Fields for MM_HeapLinkedFreeHeader:
	0x0: U64 _next = 0x0000000000000001 (1)
	0x8: U64 _size = 0x00000000004DDB98 (5102488)
}
```
0x8347ac68 + 0x4DDB98 = 0x83958800 <--- and this address GC Check shows as corruption as well
and there is nothing in memory:
```
0x839587F0 :  00000000 00000000 00000000 00000000 [ ................ ]
0x83958800 :  00000000 00000000 00000000 00000000 [ ................ ]
0x83958810 :  00000000 00000000 00000000 00000000 [ ................ ]
```

**Comment by dmitripivkine** [comment] 2021-07-16 15:12
The Mark Map for problematic range has garbage:
```
0x7F8D56F65210 :  0000000000000000 0000000000000000 [ ................ ]
0x7F8D56F65220 :  000000008334feab 2000000000000000 [ ..4............  ]
0x7F8D56F65230 :  000000008334ff3b 0000000000000840 [ ;.4.....@....... ]
0x7F8D56F65240 :  0000000000000000 0000000000000000 [ ................ ]
```
This range has been added to Tenure recently (just before Concurrent Kickoff event)
I wondering was correspondent Mark Map interval zeroed properly

**Comment by dmitripivkine** [comment] 2021-07-16 18:11
Looks like Heap Expansion (and correspondent Mark Map expansion) happen about the same time another thread executed Concurrent Kickoff:
```
06:22:33.403471000  0x107F00 j9mm.92              Entry      >MM_MemorySubSpace_calculateCollectorExpandSize Entry Bytes required = 1016
06:22:33.403474000  0x107F00 j9mm.93              Exit       <MM_MemorySubSpace_calculateCollectorExpandSize Exit1 returning expand size of 65536 bytes
06:22:33.403477000  0x107F00 j9mm.22              Entry      >MM_MemorySubSpace_expand Entry Required expansion size = 65536 bytes
06:22:33.403487000  0x107F00 j9mm.505             Event       Successfully committed memory: address=0x83950000, size=65536 <--- commit heap
06:22:33.403490000  0x107F00 j9mm.259             Entry      >MM_ConcurrentGC_heapAddRange subspace=0x7f8d60076cb0 size=65536 (0x83950000-0x83960000)
06:22:33.403497000  0x107F00 j9mm.505             Event       Successfully committed memory: address=0x7f8d56f65000, size=1024 <--- commit Mark Map (this memory seems is missed to be zeroed)
06:22:33.403500000  0x107F00 j9mm.260             Exit       <MM_ConcurrentGC_heapAddRange
06:22:33.403506000  0x107F00 j9mm.505             Event       Successfully committed memory: address=0x7f8d5674ac00, size=128
06:22:33.403529000  0x107F00 j9mm.697             Event       LOA resized on heap expansion: heapSize 10027008,  LOA ratio is 0.01 --> LOA base is now 0x83947800 LOA size 100352
06:22:33.403536000  0x107F00 j9mm.252             Entry      >MM_ConcurrentGC_tuneToHeap
06:22:33.403541000  0x107F00 j9mm.254             Exit       <MM_ConcurrentGC_tuneToHeap target=2311556 initWorkRequired=896000 kickoffthreshold=306873
06:22:33.403542000 *0x44FF00 j9mm.69              Event       Concurrent kickoff, tracesizetarget=2296446 kickoffthreshold=304967 remainingfree=203264 <--- kickoff event in another thread
06:22:33.403546000 *0x107F00 j9mm.24              Exit       <MM_MemorySubSpace_expand Exit2 Heap Expanded by 65536 bytes.
06:22:33.403547000 *0x0 j9mm.69              Event       Concurrent kickoff, tracesizetarget=2296446 kickoffthreshold=304967 remainingfree=203264
06:22:33.403549000 *0x107F00 j9mm.48              Exit       <MM_MemorySubSpace_collectorExpand Exit2 Expanded by 65536 bytes
06:22:33.403918000 *0x44FF00 j9mm.251             Exit       <MM_ConcurrentGC_getInitRange return false
06:22:33.403926000  0x44FF00 j9vm.242             Entry      >J9SignalAsyncEvent targetThread=0x44ff00 handlerKey=5
06:22:33.403929000  0x44FF00 j9vm.243             Exit       <J9SignalAsyncEvent returning 0
06:22:33.403934000  0x44FF00 j9vm.246             Entry      >dispatchAsyncEvents asyncEventFlags=0x20
06:22:33.403936000  0x44FF00 j9vm.247             Event       call event handler: handlerKey=5 eventHandler=0x7f8d647921d0 userData=0x7f8d6004c910
06:22:33.403946000  0x44FF00 j9vm.361             Entry      >Attempting to acquire exclusive VM access.
06:22:33.403949000  0x44FF00 j9vm.366             Event       First thread to try for exclusive access. Setting the exclusive access state to J9_XACCESS_PENDING
06:22:33.403958000 *0x107F00 j9mm.715             Event       Thread:  0 -> timeToStartCollection: -1626243753393036  scanStall:     0  syncStall:     0  notifyStall:     0
```
We need to check is it possible Kickoff missed to zero newly expanded part of Mark Map

**Comment by dmitripivkine** [comment] 2021-07-16 20:24
@RSalman I am going to be on vacation next week. Would you please take a look to this item?

**Comment by RSalman** [comment] 2021-07-27 15:38
**Here is a summary of findings so far:**
- Results from very small time hole with Tenure Expansion and Concurrent Kickoff
- Its rare/extremely intermittent
  - Nearly impossible to reproduce without hacking the code to slow down expansion at right spots
- [Similar to the issue that we saw last time](https://github.com/eclipse-openj9/openj9/issues/8020#issuecomment-573843125), mark map missed to get initialized.
  - Same set of things causing it, expect this is even more rare.
- This issue has been around since the beginning _(with and without CS - any case where expansion can happen during CK… but more likely to happen with CS)_
- [Lin’s changes]( https://github.com/eclipse/omr/pull/6089) are not involved, they were not merged for the nightly run

All things point to these, but there’s somethings that I’m not fully sure about, so I’m confirming and trying to reproduce.

**Closed** 2021-09-01 15:59 UTC
Labels: comp:gc, test failure, segfault
