### ISSUE TITLE
Differences in OpenJ9 JDK8 Outcomes with Default JIT vs. JIT Disabled

### ISSUE THREAD

**Issue by Qeryu** [eclipse-openj9/openj9#18756] opened 2024-01-13 13:26 UTC
Java -version output
--------------------

```bash
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -version
openjdk version "1.8.0_402-internal"  
OpenJDK Runtime Environment (build 1.8.0_402-internal_2024_01_05_11_05-b00)  
Eclipse OpenJ9 VM (build master-1b60ab828, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240105_000000 (JIT enabled, AOT enabled)  
OpenJ9   - 1b60ab828  
OMR      - 3a4787401  
JCL      - b058bf977e based on jdk8u402-b05)

$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/javac -version
javac 1.8.0_402-internal
```

Summary of problem
------------------

The following `Test.java` makes OpenJ9 (with above version) to produce different result from HotSpot (jdk11, jdk17 and jdk 21). This should be a JIT compiler's bug since `-Xint` gives the same result as HotSpot. I believe this situation might indicate a bug in some JIT optimization of OpenJ9.

```java
public class Test {
    public static final int N = 400;

    public static long instanceCount = 3L;
    public static int[] iArrFld = new int[N];

    public void mainTest(String[] strArr1) {
        for (int i0 = 0; i0 < N; i0++) {
            Test.iArrFld[i0] = -1;
        }

        for (int i14 = 343; i14 > 21; --i14) {
            Test.instanceCount += (i14 ^ Test.instanceCount);
        }

        for (int i1 = 0; i1 < N; ++i1) {
            for (int var6 = 0; var6 < 10000; ++var6) { if (var6 == 4) { } }

            int[] tmp = new int[N];
            for (int i2 = 0; i2 < N; i2++) {
                tmp[i2] = 9;
            }
            Test.iArrFld = tmp;

            for (int i18 = 3; i18 < 63; i18++) {
                Test.iArrFld[i18 - 1] <<= (int) Test.instanceCount;
            }
        }

        long sum = 0;
        for (int i : Test.iArrFld) {
            sum += i;
        }
        System.out.println("sum: " + sum);
    }

    public static void main(String[] strArr) {
        Test _instance = new Test();
        _instance.mainTest(strArr);
    }
}

```

Results of OpenJ9:

```bash
# run on openj9-openjdk-jdk8 without -Xint
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java Test  
1811942388
```

Results of OpenJ9-Xint (HotSpot also give the same result):

```bash
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -Xint Test  
9059699700
```

Diagnostic files
----------------

If you exclude `Test.mainTest()` from compilation, then it gives the same result as HotSpot/OpenJ9-Xint

```bash
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:exclude={Test.mainTest(*)*}' -cp "11/:0/" Test
9059699700
```

Testing each JIT compilation level individually, it was observed that the program produced different results under the `veryhot` level compared to other levels.

```bash
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=noOpt)' -cp "11/:0/" Test
9059699700
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=cold)' -cp "11/:0/" Test
9059699700
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=warm)' -cp "11/:0/" Test
9059699700
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=hot)' -cp "11/:0/" Test
9059699700
$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=scorching)' -cp "11/:0/" Test
9059699700

$ /data/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=veryHot)' -cp "11/:0/" Test
1811942388
```

**Comment by hzongaro** [comment] 2024-01-15 17:55
@BradleyWood, may I ask you to take a look at this problem?  I was able to reproduce the failure with a recent Java 17 build.  We get the expected output with the `disableAutoSIMD` option:

```
$ java -Xjit:optLevel=hot,count=1,disableAsyncCompilation Test
sum: 1811942388
java -Xjit:optLevel=hot,count=1,disableAsyncCompilation,disableAutoSIMD Test
sum: 9059699700
```

**Comment by BradleyWood** [comment] 2024-01-15 22:36
As I understand it, it looks like our VSHL opcode violates java semantics. The evaluator needs to AND (int) Test.instanceCount with 0x1f.

```
Test.iArrFld[i18 - 1] <<= (int) Test.instanceCount;
```

**Comment by Qeryu** [comment] 2024-01-16 11:58
We have found another test case that may also be related to this bug, as follows:

```java
class Test {
    int a = 400;
    long c = 116;
    long o = 0;

    void d(boolean b, int e) {
        int f;
        int[] g = new int[a];
        for (int h = 0; h < a; h++)
            g[h] = 3;
        for (f = 6; f < 73; f++)
            g[f] <<= c;
        for (int h = 0; h < a; h++)
            o += g[h];
    }

    void i(String[] j) {
        for (int l = 0; l < 200; l++)
            for (int m = 0; m < 20; m++)
                d(true, 1);
        System.out.println(o);
    }

    public static void main(String[] n) {
        Test p = new Test();
        p.i(n);
    }
}
```

```bash
$ java -Xjit:optLevel=veryhot Test
246729734496

$ /openjdk/java Test
843059100000
$ java -Xint Test
843059100000
```

This code also uses VSHL, and no erroneous results are produced after setting `-Xjit:disableAutoSIMD`. Hopefully, this test case will be helpful in fixing the bug.

**Comment by pshipton** [comment] 2024-01-16 13:53
Is this a regression from the previous (0.41) release?

**Comment by hzongaro** [comment] 2024-01-16 14:10
> Is this a regression from the previous (0.41) release?

No.  I can reproduce the failure with the 0.41 release, but I didn't see it with the 0.38 release - though I'm not sure whether there's some subtle difference that prevents the problem from being exposed there.

**Comment by BradleyWood** [comment] 2024-01-16 16:48
> > Is this a regression from the previous (0.41) release?
> 
> No. I can reproduce the failure with the 0.41 release, but I didn't see it with the 0.38 release - though I'm not sure whether there's some subtle difference that prevents the problem from being exposed there.

I don't think shift and rotate opcodes made the 0.38 release.

@gita-omr @r30shah @Akira1Saitoh Can you try this test case on POWER/Z/ARM? I suspect the same issue could be present there because we don't have a test case for this scenario.

**Comment by Akira1Saitoh** [comment] 2024-01-17 02:06
I can reproduce the failure with the 0.41 release on AArch64 machine. I did not see the failure with the 0.40 release.

**Comment by Qeryu** [comment] 2024-01-19 01:50
```java
class Test {
  int a = 400;
  long b;
  byte c = 8;
  long n;
  void d() {
    int[] e = new int[a];
    for (int f = 0; f < a; f++)
      e[f] = 4;
    for (int g = 4; g < 311; g++)
      e[g] >>= b;
    for (int h = 1; 295 > h; ++h)
      for (int i = 1; 6 > i; ++i)
        b += c;
    for (int f = 0; f < a; f++)
      n += e[f];
  }
  void j(String[] k) {
    for (int f = 9; f < 291; f++)
      for (int l = 8; l < 272; l++)
        d();
    System.out.println(n);
  }
  public static void main(String[] m) {
    Test o = new Test();
    o.j(m);
  }
}
```

This test also uses shift operators and generates output different from HotSpot, and it does not produce any error output when set with `-Xjit:disableAutoSIMD`. However, it differs from the previously mentioned test in that it uses `>>`. Could this also be an issue related to SIMD?

**Comment by gita-omr** [comment] 2024-01-19 15:43
Fixed by https://github.com/eclipse/omr/pull/7232

**Comment by pshipton** [comment] 2024-01-19 15:47
and https://github.com/eclipse-openj9/openj9-omr/pull/195 for 0.43

**Closed by pshipton** 2024-01-19 15:47 UTC
Labels: comp:jit, userRaised

**Comment by BradleyWood** [comment] 2024-01-19 19:31
> This test also uses shift operators and generates output different from HotSpot, and it does not produce any error output when set with -Xjit:disableAutoSIMD. However, it differs from the previously mentioned test in that it uses >>. Could this also be an issue related to SIMD?

Yes, thats the same issue.
