### ISSUE TITLE
jdk16-linux-aarch64-openj9-linuxXL: build break: error unclear?

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse-openj9/openj9#11902] opened 2021-02-08 10:44 UTC
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk16/job/jdk16-linux-aarch64-openj9-linuxXL/50/console
```
10:23:01  === Output from failing command(s) repeated here ===
10:23:01  * For target jdk_modules_java.sql.rowset__the.java.sql.rowset_batch:
10:23:01  * For target jdk_modules_java.xml.crypto__the.java.xml.crypto_batch:
10:23:01  * For target jdk_modules_jdk.javadoc__the.jdk.javadoc_batch:
10:23:01  * For target jdk_modules_jdk.jshell__the.jdk.jshell_batch:
10:23:01  
10:23:01  * All command lines available in /home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-server-release/make-support/failure-logs.
10:23:01  === End of repeated output ===
10:23:01  
10:23:01  === Make failed targets repeated here ===
10:23:01  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/jdk.jshell/_the.jdk.jshell_batch' failed
10:23:01  make/Main.gmk:197: recipe for target 'jdk.jshell-java' failed
10:23:01  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.xml.crypto/_the.java.xml.crypto_batch' failed
10:23:01  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.sql.rowset/_the.java.sql.rowset_batch' failed
10:23:01  make/Main.gmk:197: recipe for target 'java.xml.crypto-java' failed
10:23:01  make/Main.gmk:197: recipe for target 'java.sql.rowset-java' failed
10:23:01  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/jdk.javadoc/_the.jdk.javadoc_batch' failed
10:23:01  make/Main.gmk:197: recipe for target 'jdk.javadoc-java' failed
10:23:01  === End of repeated output ===
10:23:01  
10:23:01  Hint: Try searching the build log for the name of the first failed target.
10:23:01  Hint: See doc/building.html#troubleshooting for assistance.
10:23:01  
10:23:01  /home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/make/Init.gmk:310: recipe for target 'main' failed
10:23:01  make[1]: *** [main] Error 1
10:23:01  /home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/make/Init.gmk:186: recipe for target 'product-images' failed
10:23:01  make: *** [product-images] Error 2
```

**Comment by sxa** [comment] 2021-02-08 11:50
I think we should archive the command-lines used for the builds (either as a tarball or somehow making them appear in the build log) which are in the directory mentioned in the log fragment below - as you say it's difficult to see what's happening here in the `cmake` output, and particularly if we're starting to remove `build/src/build` as per https://github.com/AdoptOpenJDK/openjdk-build/pull/2416/files#diff-b4bb07e2f448f9ad2986d69423ad0b704dcdc4d217d947f465e6ace3fde7a4b3R1005
```
All command lines available in /home/jenkins/workspace/build-scripts/jobs/jdk16/jdk16-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-server-release/make-support/failure-logs.
```

**Comment by pshipton** [comment] 2021-02-08 13:11
@knn-k @keithc-ca fyi

Is the problem repeatable? Did this start occurring when cmake was enabled 10 days ago for jdk16?
https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/11

**Comment by andrew-m-leonard** [comment] 2021-02-08 13:54
Just tried again now and it built fine...?!

**Comment by andrew-m-leonard** [comment] 2021-02-08 13:55
There is no console output form cmake?

**Comment by sxa** [comment] 2021-02-08 13:56
I can't reproduce it when running a bulid manually on my aarch64 system.

**Comment by keithc-ca** [comment] 2021-02-08 14:00
> There is no console output from cmake?

The failure is outside of the part of the build that uses cmake.

Those failures should have associated log files that might provide more information. Are they still available?

**Comment by sxa** [comment] 2021-02-08 16:35
> Those failures should have associated log files that might provide more information. Are they still available?

Adopt now builds aarch64 in dynamically created systems on a docker host, so unfortunately not.

**Comment by keithc-ca** [comment] 2021-02-08 17:06
Perhaps the build scripts can be enhanced to capture those files on failure, like openj9 does - see [build.groovy](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/build.groovy#L439). Can anyone offer pointers to where that could be added for adopt?

**Comment by sxa** [comment] 2021-02-08 17:36
Yeah that's the same alongside the comment I made about capturing the command line files. I suspect it pretty just needs a new `if` clause in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L850 and the appropriate variables set. I'm sure @m-davies can advise and/or review any PR in this area :-)

**Comment by keithc-ca** [comment] 2021-02-08 20:38
If the build fails, it won't get there: see [line 451](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L451).
On the other hand, that gave me the hint I needed to collect some files that will help diagnose problems such as this.

**Comment by M-Davies** [comment] 2021-02-08 21:17
> Yeah that's the same alongside the comment I made about capturing the command line files. I suspect it pretty just needs a new `if` clause in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L850 and the appropriate variables set. I'm sure @M-Davies can advise and/or review any PR in this area :-)

https://github.com/AdoptOpenJDK/openjdk-build/issues/2461

**Comment by andrew-m-leonard** [comment] 2021-02-09 08:31
@keithc-ca @M-Davies @sxa i'll take a look, as this is going to make triage difficult so needs fixing soon

**Comment by knn-k** [comment] 2021-02-09 09:22
One thing that comes to my mind is Issue #9048 (wrong hash value during jlink).
I have no evidence, and I will wait for the command logs.

**Comment by knn-k** [comment] 2021-02-09 10:15
My guess above (jlink) is wrong.  It seems the failures are from the following phase:
```
[2021-02-08T10:21:28.793Z] Compiling 275 files for java.xml.crypto
[2021-02-08T10:21:28.793Z] Compiling 225 files for jdk.javadoc
(snip)
[2021-02-08T10:21:31.940Z] Compiling 95 files for jdk.jshell
[2021-02-08T10:21:33.181Z] Compiling 56 files for java.sql.rowset
```

**Comment by keithc-ca** [comment] 2021-05-05 16:37
What is the goal of this issue?

**Comment by pshipton** [comment] 2021-05-05 21:41
It seems obsolete so I'll just close it. XL isn't used since Java 16 moved to mixed refs builds. We managed to put out the Java 16 release successfully, which includes aarch64 builds. https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/tag/jdk-16%2B36_openj9-0.25.0

**Closed by pshipton** 2021-05-05 21:41 UTC
Labels: arch:aarch64, comp:build
