### ISSUE TITLE
testDefaultDisclaimMemory_zlinux_3 crash vmState=0x00020002

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14428] opened 2022-02-03 13:13 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/203 - ub20-390-1
testDefaultDisclaimMemory_zlinux_3 `-Xjit -Xgcpolicy:balanced -Xnocompressedrefs`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/203/functional_test_output.tar.gz
```
Unhandled exception
Type=Segmentation error vmState=0x00020002
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=000003FFABAC7D58 Handler2=000003FFAB9B2340 InaccessibleAddress=0000000000000000
gpr0=0000000000000001 gpr1=0000000099669966 gpr2=000003FFAC08B060 gpr3=000003FEF80042F8
gpr4=000003FF00000003 gpr5=0000000000000001 gpr6=000003FF6A492C90 gpr7=000003FFA9CEC848
gpr8=000003FFAC08B060 gpr9=0000000000000001 gpr10=0000000000000000 gpr11=000003FF6A492C90
gpr12=000003FFB0726F88 gpr13=000003FEF80042F8 gpr14=000003FFA9B0EBBE gpr15=000003FFAA9FE7D0
psw=000003FFA9B0CE4C mask=0705200180000000 fpc=00880000 bea=000003FFA9B0EBB8
fpr0 0000000000000001 (f: 1.000000, d: 4.940656e-324)
fpr1 4088000000000000 (f: 0.000000, d: 7.680000e+02)
fpr2 000003ffac3f64b4 (f: 2889835776.000000, d: 2.172229e-311)
fpr3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr4 4088000000000000 (f: 0.000000, d: 7.680000e+02)
fpr5 3fe0000000000000 (f: 0.000000, d: 5.000000e-01)
fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr7 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
fpr8 0000000000041000 (f: 266240.000000, d: 1.315400e-318)
fpr9 000002aa123ab3a0 (f: 305836960.000000, d: 1.447352e-311)
fpr10 000003ffaa9bf000 (f: 2862346240.000000, d: 2.172216e-311)
fpr11 000003ffd3ef86d0 (f: 3555690240.000000, d: 2.172558e-311)
fpr12 000000000059ada0 (f: 5877152.000000, d: 2.903699e-317)
fpr13 000002aa10da2938 (f: 282732864.000000, d: 1.447341e-311)
fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9gc_full29.so
Module_base_address=000003FFA9A00000
Target=2_90_20220202_205 (Linux 5.4.0-84-generic)
CPU=s390x (4 logical CPUs) (0x1f648b000 RAM)
----------- Stack Backtrace -----------
(0x000003FFA9B0CE4C [libj9gc_full29.so+0x10ce4c])
(0x000003FFA9B0EBBE [libj9gc_full29.so+0x10ebbe])
(0x000003FFA9B106C0 [libj9gc_full29.so+0x1106c0])
(0x000003FFA9B48BF0 [libj9gc_full29.so+0x148bf0])
(0x000003FFA9B48260 [libj9gc_full29.so+0x148260])
(0x000003FFAB9B34AE [libj9prt29.so+0x334ae])
(0x000003FFA9B47C20 [libj9gc_full29.so+0x147c20])
(0x000003FFAB905A14 [libj9thr29.so+0x5a14])
(0x000003FFB0589986 [libpthread.so.0+0x9986])
(0x000003FFB0383CC6 [libc.so.6+0x103cc6])
(0x0000000000000000 [<unknown>+0x0])
---------------------------------------
```

@dmitripivkine

**Comment by dmitripivkine** [comment] 2022-02-03 15:46
this is duplicate of https://github.com/eclipse-openj9/openj9/issues/14382

There is non-marked object in WP, actually pointed to the Linked Free Header:
```
> !mm_packet 0x000003FFAAB96390
MM_Packet at 0x3ffaab96390 {
  Fields for MM_Base:
  Fields for MM_BaseNonVirtual:
	0x0: const U8* _typeId = !j9x 0x0000000000000000
  Fields for MM_Packet:
	0x8: U64* _baseAddress = !j9x 0x000003FFAABA3D70
	0x10: U64* _basePtr = !j9x 0x000003FFAABA3D70
	0x18: U64* _topPtr = !j9x 0x000003FFAABA4D70
	0x20: U64* _currentPtr = !j9x 0x000003FFAABA4678 <-------------
	0x28: U64 _sublistIndex = 0x0000000000000000 (0)
	0x30: class MM_EnvironmentBase* _owner = !mm_environmentvlhgc 0x000003FEFC0042F8
	0x38: class MM_Packet* _next = !mm_packet 0x000003FFAAB96108
	0x40: class MM_Packet* _previous = !mm_packet 0x0000000000000000
}
> !j9x 0x000003FFAABA4600,100
0x3FFAABA4600 :  000003ff6a28a5a0 000003ff69f46048 [ ....j(......i.`H ]
0x3FFAABA4610 :  000003ff6a0e89a8 000003ff6a28a570 [ ....j.......j(.p ]
0x3FFAABA4620 :  000003ff6a09a430 000003ff6a0e8970 [ ....j..0....j..p ]
0x3FFAABA4630 :  000003ff6a28a558 000003ff6a0e8900 [ ....j(.X....j... ]
0x3FFAABA4640 :  000003ff6a28a4e0 000003ff6a0e88c8 [ ....j(......j... ]
0x3FFAABA4650 :  000003ff6a28a4b0 000003ff6a0e8890 [ ....j(......j... ]
0x3FFAABA4660 :  000003ff6a28a480 000003ff6a0e8858 [ ....j(......j..X ]
0x3FFAABA4670 :  000003ff6a28a450 000003ff69b872b8 [ ....j(.P....i.r. ] <----- 0x3ff69b872b8 is a hole and not marked
0x3FFAABA4680 :  000003ff6a3e7ea0 000003ff6a2e4cf8 [ ....j>~.....j.L. ]
0x3FFAABA4690 :  000003ff6a2e4d68 000003ff6a3bb0e8 [ ....j.Mh....j;.. ]
0x3FFAABA46A0 :  000003ff6a3ba918 000003ff6a3baf20 [ ....j;......j;.  ]
0x3FFAABA46B0 :  000003ff6a3baf48 000003ff6a3ba658 [ ....j;.H....j;.X ]
0x3FFAABA46C0 :  000003ff6a3baf70 000003ff6a3baed8 [ ....j;.p....j;.. ]
0x3FFAABA46D0 :  000003ff6a3bafa8 000003ff6a0d11e0 [ ....j;......j... ]
0x3FFAABA46E0 :  000003ff6a0d11c8 000003ff69bd3c70 [ ....j.......i.<p ]
0x3FFAABA46F0 :  000003ff69bd3cf8 000003ff6a3f8418 [ ....i.<.....j?.. ]
> !j9object 0x000003ff69b872b8
<can not read RAM class address>
0x3FF69B87280 :  007200650066006c 006500630074002e [ .r.e.f.l.e.c.t.. ]
0x3FF69B87290 :  004d006500740068 006f0064004d0061 [ .M.e.t.h.o.d.M.a ]
0x3FF69B872A0 :  0074006300680065 00720043006f006e [ .t.c.h.e.r.C.o.n ]
0x3FF69B872B0 :  0074006500780074 0000000000000001 [ .t.e.x.t........ ] <-------
0x3FF69B872C0 :  0000000000000148 000003ff69b860f8 [ .......H....i.`. ]
0x3FF69B872D0 :  0000000000000001 00000000000003d8 [ ................ ]
0x3FF69B872E0 :  0000000000000000 0000000000000000 [ ................ ]
0x3FF69B872F0 :  0000000000000000 0000000000000000 [ ................ ]
> !markmap ismarked 0x000003ff69b872b8
Object 0x000003FF69B872B8 is not marked
> !markmap ismarked 0x000003ff6a28a450
Object 0x000003FF6A28A450 is marked
> !markmap ismarked 0x000003ff6a3e7ea0
Object 0x000003FF6A3E7EA0 is marked
>
```
Also there is attempt to scan last element of array `!j9indexableobject 0x000003FF6A4920B8 0 340` pointed to the "hole" too. This array is not marked. And BTW this is reference array of `jdk/internal/math/FDBigInteger` objects.

Closing as duplicate

**Closed by dmitripivkine** 2022-02-03 15:46 UTC
Labels: comp:gc, test failure, segfault
