### ISSUE TITLE
Jep425Tests_testVirtualThread test_YieldedVirtualThreadGetStackTrace Expected 11 frames, got 7

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16722] opened 2023-02-14 19:56 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_Nightly_testList_1/109
Jep425Tests_testVirtualThread_1
```
02:10:08  FAILED: test_YieldedVirtualThreadGetStackTrace
02:10:08  java.lang.AssertionError: Expected 11 frames, got 7
02:10:08  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
02:10:08  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
02:10:08  	at org.openj9.test.jep425.VirtualThreadTests.test_YieldedVirtualThreadGetStackTrace(VirtualThreadTests.java:182)
```

**Comment by fengxue-IS** [comment] 2023-02-15 20:52
Without knowing what the 7 frames are, it is very hard to say how this test failed.
Based on code inspection, it is possible the the `LockSupport.park()` call exceeded the 500ms delay (very unlikely though).

I will add some debug output and re-run in grinder to verify how this occurred.

**Comment by fengxue-IS** [comment] 2023-02-15 21:55
[100x Grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/31104/) all passed

**Comment by fengxue-IS** [comment] 2023-02-15 23:25
another 100x still unable to reproduce this failure.
I will add the print stack frame code to our test code so next time when we see this error, there will be some data to investigate. Once that change have been merged, I think we can close this issue unless failure is seen again.

**Comment by JasonFengJ9** [comment] 2023-03-10 14:38
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.functional_ppc64_aix_OMR_testList_1/81/consoleFull
```
08:44:34  openjdk version "19.0.2-internal" 2023-01-17
08:44:34  OpenJDK Runtime Environment (build 19.0.2-internal-adhoc.****.BuildJDK19ppc64aixOMR)
08:44:34  Eclipse OpenJ9 VM (build master-5a4ab53779e, JRE 19 AIX ppc64-64-Bit Compressed References 20230308_90 (JIT enabled, AOT enabled)
08:44:34  OpenJ9   - 5a4ab53779e
08:44:34  OMR      - c40c4ac92f4
08:44:34  JCL      - 9d52294be4f based on jdk-19.0.2+7)

09:02:33  variation: --enable-preview -Xgcpolicy:gencon
09:02:33  JVM_OPTIONS:  --enable-preview -Xgcpolicy:gencon 

09:02:44  FAILED: test_YieldedVirtualThreadGetStackTrace
09:02:44  java.lang.AssertionError: Expected 12 frames, got 7
09:02:44  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
09:02:44  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
09:02:44  	at org.openj9.test.jep425.VirtualThreadTests.test_YieldedVirtualThreadGetStackTrace(VirtualThreadTests.java:191)

09:02:44      Jep425Tests_testVirtualThread
09:02:44      Tests run: 7, Failures: 1, Skips: 0
09:02:44  ===============================================
09:02:44  
09:02:44  
09:02:44  ===============================================
09:02:44  Java19 test suite
09:02:44  Total tests run: 7, Failures: 1, Skips: 0
09:02:44  ===============================================
09:02:44  
09:02:45  -----------------------------------
09:02:45  Jep425Tests_testVirtualThread_1_FAILED
```
500x grinder - https://openj9-jenkins.osuosl.org/job/Grinder/2071/

**Comment by JasonFengJ9** [comment] 2023-03-13 16:18
> The grinder didn't start: https://openj9-jenkins.osuosl.org/job/Grinder/2071/.

Re-launched at https://openj9-jenkins.osuosl.org/job/Grinder/2073/console to check the failure rate though this is a test issue as per https://github.com/eclipse-openj9/openj9/issues/16722#issuecomment-1466434428

**Comment by babsingh** [comment] 2023-03-13 16:21
> the failure rate

It will depend on the execution time of [LockSupport.park(...)](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/util/concurrent/locks/LockSupport.java#L367-L373). The failure will mostly be seen on slower machines where [LockSupport.park(...)](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/util/concurrent/locks/LockSupport.java#L367-L373) takes greater than 500 ms.

**Comment by fengxue-IS** [comment] 2023-03-13 18:00
> The virtual thread's stack trace during the crash:
> 
> ```
> 10:02:42  java.base/java.lang.VMAccess.findClassOrNull(Native Method)
> 10:02:42  java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1097)
> 10:02:42  java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:369)
> 10:02:42  org.openj9.test.jep425.VirtualThreadTests.lambda$test_YieldedVirtualThreadGetStackTrace$5(VirtualThreadTests.java:175)
> 10:02:42  java.base/java.lang.VirtualThread.run(VirtualThread.java:292)
> 10:02:42  java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:179)
> 10:02:42  java.base/jdk.internal.vm.Continuation.enter(Continuation.java:170)
> ```
> 
> The virtual thread has not parked yet since we are still loading the `VirtualThreads` class: [LockSupport.park(...)](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/util/concurrent/locks/LockSupport.java#L367-L373).

Not sure if this stack is valid, as VirtualThread class must be loaded for a vthread the be launched right? Unless the `LockSupport.park()` is trying to load a different class. though I don't see any other class being used in the code https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/java/util/concurrent/locks/LockSupport.java#L367-L373

Without a corefile at the time of the failure, it will be hard to say what is the problem here.

Increasing the test wait time here is an option to see if it is due to machine too slow.

**Comment by babsingh** [comment] 2023-03-13 18:02
> Not sure if this stack is valid, as VirtualThread class must be loaded

Class name is []VirtualThreads(https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/jdk/internal/misc/VirtualThreads.java) not `VirtualThread`.

**Comment by fengxue-IS** [comment] 2023-03-13 18:04
> > Not sure if this stack is valid, as VirtualThread class must be loaded
> 
> Class name is [VirtualThreads](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/java.base/share/classes/jdk/internal/misc/VirtualThreads.java) not `VirtualThread`.

You are right, totally missed that s. pls ignore previous comment.

**Closed** 2023-04-14 22:10 UTC
Labels: comp:vm, test failure, jdk19
