### ISSUE TITLE
metronome gc strange behavior

### ISSUE THREAD

**Issue by siyy123** [eclipse-openj9/openj9#16744] opened 2023-02-21 06:00 UTC
Java -version output
--------------------

java version "17.0.5" 2022-10-18
IBM Semeru Runtime Certified Edition 17.0.5.0 (build 17.0.5+8)
Eclipse OpenJ9 VM 17.0.5.0 (build openj9-0.35.0, JRE 17 Linux amd64-64-Bit Compressed References 20221018_272 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - e1263b46ebe based on jdk-17.0.5+8)

Summary of problem
------------------

I'm trying to run a minecraft server with 1GB heap. I tried balanced, optavgpause, and metronome gc policies (balanced and metronome target pause time set to 50ms, one tick in minecraft) but only metronome throws a OOM exception, while however, the heap is nearly half free (at least from the minecraft server panel).
The situation is even more strange if I set the target pause time back to the default 3ms, OOM happens slower, not as quick as the 50ms one.

![image](https://user-images.githubusercontent.com/11704754/220252979-d40b5b3c-83ee-4432-9190-3fae2d0e33d9.png)
with metronome gc 50ms pause time

![image](https://user-images.githubusercontent.com/11704754/220255174-6f72c852-1aae-4591-bfc3-267732e433b7.png)
with metronome gc 3ms pause time

A possible reason is that the server allocates objects too fast (it's the case how minecraft works, especially when generating new chunks), and triggering a gc nearly just after a gc finish. However, if that is the cause, balanced and optavgpause should both throw OOM while in fact they aren't, and gc log shows that metronome really OOM when heap is actually half full!

![image](https://user-images.githubusercontent.com/11704754/220254360-fe73f8ad-9590-42c9-86a0-846526dccdb9.png)
with balanced gc

Diagnostic files
----------------
[gc.7z.004.zip](https://github.com/eclipse-openj9/openj9/files/10790105/gc.7z.004.zip)
[gc.7z.003.zip](https://github.com/eclipse-openj9/openj9/files/10790106/gc.7z.003.zip)
[gc.7z.002.zip](https://github.com/eclipse-openj9/openj9/files/10790108/gc.7z.002.zip)
[gc.7z.001.zip](https://github.com/eclipse-openj9/openj9/files/10790109/gc.7z.001.zip)
[gc.7z.008.zip](https://github.com/eclipse-openj9/openj9/files/10790110/gc.7z.008.zip)
[gc.7z.007.zip](https://github.com/eclipse-openj9/openj9/files/10790111/gc.7z.007.zip)
[gc.7z.006.zip](https://github.com/eclipse-openj9/openj9/files/10790112/gc.7z.006.zip)
[gc.7z.005.zip](https://github.com/eclipse-openj9/openj9/files/10790113/gc.7z.005.zip)

OutOfMemoryError: Java Heap Space
---------------------------------
[metronome gc.log](https://github.com/eclipse-openj9/openj9/files/10790053/metronome.gc.log)

**Comment by dmitripivkine** [comment] 2023-02-21 14:03
@amicic FYI

**Comment by amicic** [comment] 2023-03-01 16:33
When overriding target pause, there is indeed a subtle bug where an internal party (Scheduler) is not properly notified of size of timing window within which we schedule mutator and GC increments. That window is supposed to be 20x of target pause. VGC does report that it's been properly calculated, but really the default 60ms is used (3ms x 20), and being very close to the increment of 50ms, scheduler math was confused.

    <attribute name="beatsPerMeasure" value="50000" />
    <attribute name="timeInterval" value="1000000" />   <<<<<<<<<<<  1s = 20 x 50ms

I'll work on fixing this, but as temp workaround you can explicitly specify the window size:

-XXgc:timeInterval=1000000

Note that this option being an -XXgc variant is undocumented and officially unsupported (behaviour could be unexpected if provided ratio is different than 20x).

This workaround alone should only make GC behave incrementally and kick-off GCs earlier (at 50% free heap), rather then waiting for it to be depleted (0% free heap) and performing a full GC cycle in one STW increment. Other than obviously helping with pauses, it would probably help with fragmentation, making it hit OOM later.

Note also that Metronome trades off some part of application throughput to be able to mention low pauses (order of 1ms). It does not really make much sense running it with 50ms target pause - the lost throughput will not be regain with longer target pause. Generation GC policies (Gencon and Balanced), while optimizing for less frequent global GCs, might be more suitable for ~50ms target. Concurrent Scavenger (within Gencon GC policy) can further improve average GC pauses, although it will not improve the worst case pause times. If global GC in Gencon cause compactions, Balanced GC is preferred (since it's able to incrementally defragment heap).

As for why Metronome hit OOM, as I already hinted, but I can't say for sure, it could be that heap was fragmented. While there might be free space around it might be unusable for specific allocation sizes. Fragmentation should converge eventually (for a steady workload), but it indeed may take a long time for that (minutes or even hours).

Metronome does not support defragmention, so the only workaround would be to increase heap, and hope that fragmentation will converge before heap is depleted.

We have some more detailed breakdown of heap that can be generated with -Xtgc:heap,file=tgc.log, which can tell is if fragmentation is indeed the cause.

**Comment by amicic** [comment] 2023-07-21 04:42
fixed by https://github.com/eclipse-openj9/openj9/pull/16837

**Closed by amicic** 2023-07-21 04:42 UTC
Labels: comp:gc, userRaised
