### ISSUE TITLE
[Jtreg_JDK21] IOException detected in TestByteBuffer.java

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17870] opened 2023-07-27 18:26 UTC
There is a subtest failure in TestByteBuffer.java at https://openj9-jenkins.osuosl.org/job/Grinder/2619/consoleText
```
test TestByteBuffer.testMappedSegmentAsByteBuffer(): failure
java.io.UncheckedIOException: java.io.IOException: Invalid argument (msync with parameter MS_SYNC failed)
	at java.base/java.nio.MappedMemoryUtils.force(MappedMemoryUtils.java:105)
	at java.base/java.nio.Buffer$2.force(Buffer.java:890)
	at java.base/jdk.internal.misc.ScopedMemoryAccess.forceInternal(ScopedMemoryAccess.java:317)
	at java.base/jdk.internal.misc.ScopedMemoryAccess.force(ScopedMemoryAccess.java:305)
	at java.base/jdk.internal.foreign.MappedMemorySegmentImpl.force(MappedMemorySegmentImpl.java:92)
	at TestByteBuffer.testMappedSegmentAsByteBuffer(TestByteBuffer.java:321)
```
which is most likely related to `ScopedMemoryAccess`.

Note:
the failure was only detected on AIX for the moment.

FYI: @babsingh, @tajila, @pshipton

**Comment by babsingh** [comment] 2023-07-28 15:43
All the elements in the above stack trace are implemented in the extension repo (OpenJDK). The test fails because `msysc` fails on AIX: 
- There is an OpenJDK issue to track this failure: https://bugs.openjdk.org/browse/JDK-8312180.
- The fix is still pending merge: https://github.com/openjdk/jdk/pull/14963.

@backwaterred Are there plans to backport the above fix to JDK21?

**Comment by backwaterred** [comment] 2023-07-28 19:59
I'm happy to backport this fix when it's merged :-)

**Comment by babsingh** [comment] 2023-07-28 20:15
> I'm happy to backport this fix when it's merged :-)

Thanks, let us know once the backport is delivered. We will use it to close this issue.

**Comment by tajila** [comment] 2023-09-12 17:35
@backwaterred any update on this?

**Comment by backwaterred** [comment] 2023-09-12 18:00
Yeah, sorry. The backport merged in the last week or so. These changes are now in the headstream for jdk 22, & 21.

**Comment by babsingh** [comment] 2023-09-12 18:03
Thanks @backwaterred. Closing as per https://github.com/eclipse-openj9/openj9/issues/17870#issuecomment-1716185910.

**Comment by pshipton** [comment] 2023-09-12 18:25
We should keep this open until we have the fix. Not sure if it will be in 20.0.1, we might be waiting for 20.0.2. Or we can bring it manually for now.

**Comment by babsingh** [comment] 2023-09-12 18:38
> https://github.com/adoptium/aqa-tests/blob/1c9bad0f19205223df3a26bbce4ab929a12f5eb2/openjdk/excludes/ProblemList_openjdk21-openj9.txt#L491

Added the exclude label since the test is currently excluded.

> Not sure if it will be in 20.0.1, we might be waiting for 20.0.2. Or we can bring it manually for now.

For Java 21? Since Java 20 is no longer supported.

**Comment by pshipton** [comment] 2023-09-12 18:41
Yes, I meant 21.0.1 and 21.0.2.

**Comment by babsingh** [comment] 2023-09-12 18:44
@backwaterred https://github.com/openjdk/jdk/pull/14963 seems RI specific. Will this fix also apply to OpenJ9?

**Comment by backwaterred** [comment] 2023-09-12 20:13
Ah, I see you have linked part 1 of the fix above, which is Hotspot specific.

The main part of the issue is here: https://github.com/openjdk/jdk/pull/14964

**Comment by babsingh** [comment] 2023-09-13 01:53
@backwaterred Has https://github.com/openjdk/jdk/pull/14964 also been merged into the headstream for jdk 22, & 21?

**Comment by backwaterred** [comment] 2023-09-15 15:51
Yes it has. Both the PR against 22 and the backport to 21 are merged.

**Comment by babsingh** [comment] 2023-09-15 17:45
> We should keep this open until we have the fix. Not sure if it will be in 21.0.1, we might be waiting for 21.0.2. Or we can bring it manually for now.

The fix already exists in JDK-next: https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/13fa40bdfeb6083a1114fbce24abc51e1ea8282f.

We should manually bring the fix to JDK21. It will allow us to enable the test and identify other OpenJ9 specific issues with the test quicker. @pshipton https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/44 backports the fix to JDK21.

**Comment by pshipton** [comment] 2023-09-19 18:45
@babsingh I think the test can be unexcluded now and this closed?

**Comment by babsingh** [comment] 2023-09-19 19:00
yes, i was looking for a nightly build to run a grinder. but, i didn't find a build with the fix yet. i will run a grinder from a personal build to verify the fix and re-enable the test.

**Comment by pshipton** [comment] 2023-09-19 19:02
The latest nightly jdk21 build contains the fix. We have builds for all platforms but AIX. In the grinder you can use the default, which is the latest.

**Comment by pshipton** [comment] 2023-09-19 19:04
Right, duh, AIX is the platform we need. I'll re-run the build.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK21/114/

**Comment by babsingh** [comment] 2023-09-19 20:42
> https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK21/114/

Thanks, the build successfully completed. Started a grinder to verify the fix: https://openj9-jenkins.osuosl.org/job/Grinder/2929/.

**Comment by babsingh** [comment] 2023-09-19 21:30
https://openj9-jenkins.osuosl.org/job/Grinder/2929 confirms that `TestByteBuffer` passes on AIX. Opened https://github.com/adoptium/aqa-tests/pull/4776 to re-enable the test.

**Closed** 2023-09-20 17:58 UTC
Labels: comp:test, project:panama, test failure, jdk21
