### ISSUE TITLE
JDK19 jdk/internal/vm/Continuation/ClassUnloading.java timed out

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16053] opened 2022-10-05 20:31 UTC
Timed out with and without JIT
```
"main" prio=5 Id=2 WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2146)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2222)
        at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)

"Common-Cleaner" prio=8 Id=3 TIMED_WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
        at java.base@19-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)
        at java.base@19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

"GC Worker" prio=5 Id=4 RUNNABLE

"GC Worker" prio=5 Id=5 RUNNABLE

"GC Worker" prio=5 Id=6 RUNNABLE

"GC Worker" prio=5 Id=7 RUNNABLE

"GC Worker" prio=5 Id=8 RUNNABLE

"GC Worker" prio=5 Id=9 RUNNABLE

"GC Worker" prio=5 Id=10 RUNNABLE

"Attach API wait loop" prio=10 Id=13 TIMED_WAITING
        at java.base@19-internal/java.lang.Thread.sleepImpl(Native Method)
        at java.base@19-internal/java.lang.Thread.sleep0(Thread.java:477)
        at java.base@19-internal/java.lang.Thread.sleep(Thread.java:472)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:142)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)

"MainThread" prio=5 Id=15 WAITING
        at java.base@19-internal/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@19-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
        at java.base@19-internal/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3744)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3689)
        at java.base@19-internal/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
        at java.base@19-internal/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
        at app//ClassUnloading.main(ClassUnloading.java:58)
        at java.base@19-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base@19-internal/java.lang.reflect.Method.invoke(Method.java:578)
        at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)

"Finalizer thread" prio=5 Id=16 RUNNABLE

"VirtualThread-unparker" prio=5 Id=20 WAITING
        at java.base@19-internal/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@19-internal/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
        at java.base@19-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3744)
        at java.base@19-internal/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3689)
        at java.base@19-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1625)
        at java.base@19-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170)
        at java.base@19-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@19-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
        at java.base@19-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base@19-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)
        at java.base@19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

"Attachment portNumber: 43951" prio=10 Id=21 RUNNABLE
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
        at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
        at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)

"file lock watchdog" prio=10 Id=22 TIMED_WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.util.TimerThread.mainLoop(Timer.java:563)
        at java.base@19-internal/java.util.TimerThread.run(Timer.java:516)


--- Timeout information end.
finished: Wed Oct 05 13:21:32 PDT 2022
elapsed time (seconds): 121.191
configuration:
STDOUT:
Thread[#15,MainThread,5,MainThreadGroup]
try unload Dummy/0x0000000000000000
..........
unload Dummy/0x0000000000000000
.

VirtualThread[#17]/runnable@ForkJoinPool-1-worker-1
try unload Dummy/0x0000000000000000
Timeout refired 120 times
.
STDERR:
```

**Comment by babsingh** [comment] 2022-10-06 16:59
In my local run, I didn't notice a hang. With `optthruput`, the below assertion was triggered:
```
STDOUT:
Thread[#25,MainThread,5,MainThreadGroup]
try unload Dummy/0x0000000000000000
..........
unload Dummy/0x0000000000000000
.

VirtualThread[#27]/runnable@ForkJoinPool-1-worker-1
try unload Dummy/0x0000000000000000
..
STDERR:
Pointer: FFFF000000040005 has is not object aligned (to 8 bytes)
16:57:25.099 0x7f01f4016300    j9mm.141    *   ** ASSERTION FAILED ** at /root/openj9-openjdk-jdk/omr/gc/base/MarkingScheme.hpp:70: ((false))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/10/06 09:57:25 - please wait.
```

fyi @LinHu2016

**Comment by babsingh** [comment] 2022-10-06 17:04
With `nogc`,
```
STDOUT:
Thread[#18,MainThread,5,MainThreadGroup]
try unload Dummy/0x0000000000000000
..........
unload Dummy/0x0000000000000000
..........
STDERR:
java.lang.RuntimeException: weak reference not cleared!!
	at ClassUnloading.unload(ClassUnloading.java:91)
	at ClassUnloading.test(ClassUnloading.java:81)
	at ClassUnloading.main(ClassUnloading.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:1573)
```

**Comment by LinHu2016** [comment] 2022-10-06 17:33
@babsingh Could you please provide a guideline to run this test locally, I will try to debug the issue, Thanks

**Comment by babsingh** [comment] 2022-10-06 17:42
> Could you please provide a guideline to run this test locally

```
cd <EXTENSION_REPO>

// Download and unzip JTREG in your extension repo: https://openj9-jenkins.osuosl.org/view/Infrastructure/job/test.getDependency/512/artifact/jtreg_7_1.tar.gz
// Then, rerun configure with --with-jtreg:
bash ./configure --with-freemarker-jar=/root/freemarker.jar --with-jtreg=$PWD/jtreg

make test TEST="jtreg:test/jdk/jdk/internal/vm/Continuation/ClassUnloading.java" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true -Xgcpolicy:optthruput;VERBOSE=all"
```

**Comment by dmitripivkine** [comment] 2022-10-06 17:50
@babsingh Is system core still be available for the failure with assertion in GC?

**Comment by babsingh** [comment] 2022-10-06 18:02
@dmitripivkine Core files from my local run: https://ibm.box.com/s/cpek5g8seedknb20hev3v1qsdua1l0et

**Comment by LinHu2016** [comment] 2022-10-06 23:43
I have retried the test with the latest build, it is passed, I am wondering if it was related with the compaction issue, which related fix has been merged last night. or it is intermittent issue.

**Comment by thallium** [comment] 2022-10-07 00:47
I re-ran the test and it passed as well, probably got fixed by a recent PR.

**Closed** 2022-10-20 14:49 UTC
Labels: test failure, project:loom, jdk19

**Comment by dmitripivkine** [comment] 2022-11-03 16:16
Just for the record:
Assertion in GC is caused by bad `classNameString` value `0xffff000000040005`  in class object (heap corruption?):
```
> !j9object 0x7fe457245a10
!J9Object 0x00007FE457245A10 {
	struct J9Class* clazz = !j9class 0x7FE488136900 // java/lang/Class
	Object flags = 0x0000000A;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	J vmRef = 0x00007FE3DC064900 (offset = 8) (java/lang/Class)
	Ljava/lang/ClassLoader; classLoader = !fj9object 0x7fe45712c2c8 (offset = 16) (java/lang/Class)
	Ljava/lang/Module; module = !fj9object 0x7fe457181840 (offset = 24) (java/lang/Class)
	Ljava/security/ProtectionDomain; protectionDomain = !fj9object 0x0 (offset = 32) (java/lang/Class)
	Ljava/lang/String; classNameString = !fj9object 0xffff000000040005 (offset = 40) (java/lang/Class) <-----
	Ljava/lang/String; cachedToString = !fj9object 0x0 (offset = 48) (java/lang/Class)
	Ljava/lang/String; fileNameString = !fj9object 0x0 (offset = 56) (java/lang/Class)
	Ljava/lang/String; packageNameString = !fj9object 0x0 (offset = 64) (java/lang/Class)
	Ljava/lang/Class$AnnotationVars; annotationVars = !fj9object 0x0 (offset = 72) (java/lang/Class)
	Ljava/lang/ClassValue$ClassValueMap; classValueMap = !fj9object 0x0 (offset = 80) (java/lang/Class)
	Ljava/lang/Class$EnumVars; enumVars = !fj9object 0x0 (offset = 88) (java/lang/Class)
	Ljava/lang/J9VMInternals$ClassInitializationLock; initializationLock = !fj9object 0x0 (offset = 96) (java/lang/Class)
	Ljava/lang/Object; methodHandleCache = !fj9object 0x0 (offset = 104) (java/lang/Class)
	Ljava/lang/Class$ClassRepositoryHolder; classRepoHolder = !fj9object 0x0 (offset = 112) (java/lang/Class)
	Ljava/lang/Class$AnnotationCache; annotationCache = !fj9object 0x0 (offset = 120) (java/lang/Class)
	Ljava/lang/Class$MetadataCache; metadataCache = !fj9object 0x0 (offset = 128) (java/lang/Class)
	[Ljava/lang/Class; cachedInterfaces = !fj9object 0x0 (offset = 136) (java/lang/Class)
	Ljava/lang/Class; cachedDeclaringClass = !fj9object 0x0 (offset = 144) (java/lang/Class)
	Ljava/lang/Class; cachedEnclosingClass = !fj9object 0x0 (offset = 152) (java/lang/Class)
	Z cachedCheckInnerClassAttr = 0x00000000 (offset = 192) (java/lang/Class)
	Ljava/lang/Class; nestHost = !fj9object 0x0 (offset = 160) (java/lang/Class)
	Ljava/lang/Object; classData = !fj9object 0x0 (offset = 168) (java/lang/Class)
	[Ljava/lang/Class; cachedPermittedSubclasses = !fj9object 0x0 (offset = 176) (java/lang/Class)
	Ljava/lang/Class$ReflectCache; reflectCache = !fj9object 0x0 (offset = 184) (java/lang/Class)
}
```
There is another suspicious (possibly corrupted) place in the heap discovered by GC Check:
```
  <gc check (1): from debugger: HEAP: Object slot 7fe457245a10(7fe457245a40) -> ffff000000040005: corrupt data exception>
  <gc check (2): from debugger: HEAP: Object slot 7fe4572462e8(7fe457246300) -> 7fe4d70f0550: corrupt data exception>

> !j9object 0x7fe4572462e8
!J9Object 0x00007FE4572462E8 {
	struct J9Class* clazz = !j9class 0x7FE488219900 // java/util/ImmutableCollections$List12
	Object flags = 0x00000000;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	Ljava/lang/Object; e0 = !fj9object 0x7fe457246200 (offset = 8) (java/util/ImmutableCollections$List12)
	Ljava/lang/Object; e1 = !fj9object 0x7fe4d70f0550 (offset = 16) (java/util/ImmutableCollections$List12)
}
```
address `0x7fe4d70f0550` is out of heap range `[0x7fe4570f0000,0x7fe4578f0000]`
I suspect it is corrupted, most likely instead of `d7` should be `57` (one bit 0x80 difference)
