### ISSUE TITLE
AArch64: javac OutOfMemoryErrors in openjdk tests with XL builds

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#10597] opened 2020-09-15 04:40 UTC
There are random and intermittent OutOfMemoryErrors with javac in AArch64 Java 11 XL builds.

Failure link
------------

- https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/204/ (2 failures)
- https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/205/ (4 failures)
- https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/206/ (2 failures)
- https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/207/ (2 failures)

Optional info
-------------

- intermittent failure: yes
- regression or new test: regression
- if regression, what are the last passing : https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/203/

Failure output (captured from console output)
---------------------------------------------

From https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/204/
```
09:54:39  TEST: java/util/regex/PatternStreamTest.java
(... snip ...)
09:54:39  rerun:
09:54:39  cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29 && \
09:54:39  DISPLAY=:0 \
09:54:39  HOME=/home/jenkins \
09:54:39  LANG=en_US.UTF-8 \
09:54:39  PATH=/bin:/usr/bin:/usr/sbin \
09:54:39      /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image/bin/javac \
09:54:39          -J-ea \
09:54:39          -J-esa \
09:54:39          -J-Xmx512m \
09:54:39          -J-Xdump:system:none \
09:54:39          -J-Xdump:heap:none \
09:54:39          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
09:54:39          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache' \
09:54:39          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache' \
09:54:39          -J-Dtest.compiler.opts= \
09:54:39          -J-Dtest.java.opts= \
09:54:39          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image \
09:54:39          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image \
09:54:39          -J-Dtest.timeout.factor=8.0 \
09:54:39          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
09:54:39          -J-Dtest.name=java/util/regex/PatternStreamTest.java \
09:54:39          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/regex/PatternStreamTest.java \
09:54:39          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/regex \
09:54:39          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/regex \
09:54:39          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/classes/30/java/util/regex/PatternStreamTest.d \
09:54:39          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/classes/30/java/util/regex/PatternStreamTest.d \
09:54:39          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/regex \
09:54:39          -J-Dtest.patch.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/classes/30/lib/testlibrary/bootlib \
09:54:39          -d /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/classes/30/lib/testlibrary/bootlib/java.base \
09:54:39          --patch-module java.base=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/bootlib/java.base:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/classes/30/lib/testlibrary/bootlib/java.base \
09:54:39          -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/jcommander.jar \
09:54:39          --add-reads java.base=ALL-UNNAMED /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/bootlib/java.base/java/util/stream/OpTestCase.java
09:54:39  stderr:
09:54:39  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/09/12 00:54:08 - please wait.
09:54:39  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/09/12 00:54:12 - please wait.
09:54:39  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/javacore.20200912.005408.49560.0001.txt' in response to an event
09:54:39  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/javacore.20200912.005408.49560.0001.txt
09:54:39  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/Snap.20200912.005408.49560.0003.trc' in response to an event
09:54:39  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/09/12 00:54:29 - please wait.
09:54:39  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/Snap.20200912.005408.49560.0003.trc
09:54:39  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
09:54:39  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/javacore.20200912.005412.49560.0002.txt' in response to an event
09:54:39  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/javacore.20200912.005412.49560.0002.txt
09:54:39  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_15998709532762/jdk_util_j9_0/work/scratch/29/Snap.20200912.005412.49560.0005.trc' in response to an event
09:54:39  JVMDUMP010I Snap dump written to {nothing to snap}
09:54:39  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
09:54:39  direct.log:
09:54:39  java.lang.reflect.InvocationTargetException
09:54:39  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
09:54:39  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:54:39  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:54:39  	at com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
09:54:39  	at com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
09:54:39  	at com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:262)
09:54:39  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:229)
09:54:39  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
09:54:39  Caused by: java.lang.ClassCastException: com.sun.tools.javac.util.List incompatible with java.io.Closeable
09:54:39  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.close(JavaCompiler.java:1808)
09:54:39  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:352)
09:54:39  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
09:54:39  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)
09:54:39  	... 8 more
09:54:39  
09:54:39  TEST RESULT: Error. Error invoking compiler
```

**Comment by dmitripivkine** [comment] 2020-09-15 14:27
Looks like tests failed more or less randomly so most likely not related to particular JVM pattern

**Comment by andrew-m-leonard** [comment] 2020-10-23 11:27
Re-occurred GA jdk-11.0.9+11_openj9-0.23.0: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/238/console

**Comment by lumpfish** [comment] 2020-12-17 16:06
Reoccurred on jdk11 AdoptOpenJDK nightly build: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/286/console:
```
00:47:50  TEST: java/util/jar/JarFile/mrjar/MultiReleaseJarSecurity.java
00:47:50  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image
00:47:50  
00:47:50  ACTION: build -- Error. Error invoking compiler
00:47:50  REASON: User specified action: run build Compiler JarBuilder CreateMultiReleaseTestJars 
00:47:50  TIME:   263.281 seconds
00:47:50  messages:
00:47:50  command: build Compiler JarBuilder CreateMultiReleaseTestJars
00:47:50  reason: User specified action: run build Compiler JarBuilder CreateMultiReleaseTestJars 
00:47:50  Library /lib/testlibrary/java/util/jar:
00:47:50    compile: Compiler, JarBuilder, CreateMultiReleaseTestJars
00:47:50  elapsed time (seconds): 263.281
00:47:50  
00:47:50  ACTION: compile -- Error. Error invoking compiler
00:47:50  REASON: .class file out of date or does not exist
00:47:50  TIME:   263.278 seconds
00:47:50  messages:
00:47:50  command: compile /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar/Compiler.java /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar/JarBuilder.java /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar/CreateMultiReleaseTestJars.java
00:47:50  reason: .class file out of date or does not exist
00:47:50  Additional options from @modules: --add-modules jdk.compiler,jdk.jartool
00:47:50  Mode: agentvm
00:47:50  Agent id: 20
00:47:50  elapsed time (seconds): 263.278
00:47:50  configuration:
00:47:50  Boot Layer (javac runtime environment)
00:47:50    class path: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/javatest.jar 
00:47:50                /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/jtreg.jar 
00:47:50    patch:      java.base /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/patches/java.base
00:47:50  
00:47:50  javac compilation environment
00:47:50    add modules: jdk.compiler jdk.jartool
00:47:50    source path: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar
00:47:50    class path:  /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/lib/testlibrary/java/util/jar
00:47:50                 /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/testng.jar
00:47:50                 /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/jcommander.jar
00:47:50  
00:47:50  rerun:
00:47:50  cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24 && \
00:47:50  DISPLAY=:0 \
00:47:50  HOME=/home/jenkins \
00:47:50  LANG=en_US.UTF-8 \
00:47:50  PATH=/bin:/usr/bin:/usr/sbin \
00:47:50      /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image/bin/javac \
00:47:50          -J-ea \
00:47:50          -J-esa \
00:47:50          -J-Xmx512m \
00:47:50          -J-Xdump:system:none \
00:47:50          -J-Xdump:heap:none \
00:47:50          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
00:47:50          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache' \
00:47:50          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache' \
00:47:50          -J-Dtest.compiler.opts= \
00:47:50          -J-Dtest.java.opts= \
00:47:50          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image \
00:47:50          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image \
00:47:50          -J-Dtest.timeout.factor=8.0 \
00:47:50          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
00:47:50          -J-Dtest.name=java/util/jar/JarFile/mrjar/MultiReleaseJarSecurity.java \
00:47:50          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/jar/JarFile/mrjar/MultiReleaseJarSecurity.java \
00:47:50          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/jar/JarFile/mrjar \
00:47:50          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/jar/JarFile/mrjar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar \
00:47:50          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/java/util/jar/JarFile/mrjar/MultiReleaseJarSecurity.d \
00:47:50          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/java/util/jar/JarFile/mrjar/MultiReleaseJarSecurity.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/lib/testlibrary/java/util/jar \
00:47:50          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/jar/JarFile/mrjar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/lib/testlibrary/java/util/jar \
00:47:50          -J-Dtest.modules='jdk.compiler jdk.jartool' \
00:47:50          --add-modules jdk.compiler,jdk.jartool \
00:47:50          -d /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/lib/testlibrary/java/util/jar \
00:47:50          -sourcepath /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar \
00:47:50          -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/classes/16/lib/testlibrary/java/util/jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/jvmtest/openjdk/jtreg/lib/jcommander.jar /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar/Compiler.java /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar/JarBuilder.java /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/openjdk/openjdk-jdk/test/jdk/lib/testlibrary/java/util/jar/CreateMultiReleaseTestJars.java
00:47:50  stderr:
00:47:50  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/12/17 00:47:16 - please wait.
00:47:50  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/12/17 00:47:16 - please wait.
00:47:50  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/javacore.20201217.004716.28703.0002.txt' in response to an event
00:47:50  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/javacore.20201217.004716.28703.0002.txt
00:47:50  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/Snap.20201217.004716.28703.0003.trc' in response to an event
00:47:50  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/Snap.20201217.004716.28703.0003.trc
00:47:50  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
00:47:50  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/javacore.20201217.004716.28703.0001.txt' in response to an event
00:47:50  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/javacore.20201217.004716.28703.0001.txt
00:47:50  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/12/17 00:47:24 - please wait.
00:47:50  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/Snap.20201217.004716.28703.0004.trc' in response to an event
00:47:50  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/Snap.20201217.004716.28703.0004.trc
00:47:50  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
00:47:50  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/javacore.20201217.004724.28703.0005.txt' in response to an event
00:47:50  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/javacore.20201217.004724.28703.0005.txt
00:47:50  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/Snap.20201217.004724.28703.0006.trc' in response to an event
00:47:50  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/12/17 00:47:44 - please wait.
00:47:50  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdk-tests/TKG/test_output_16081649425237/jdk_util_j9_0/work/scratch/24/Snap.20201217.004724.28703.0006.trc
00:47:50  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
00:47:50  direct.log:
00:47:50  java.lang.reflect.InvocationTargetException
00:47:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:47:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:47:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:47:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:47:50  	at com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
00:47:50  	at com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
00:47:50  	at com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:262)
00:47:50  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:229)
00:47:50  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
00:47:50  Caused by: java.lang.ClassCastException: com.sun.tools.javac.util.List incompatible with java.io.Closeable
00:47:50  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.close(JavaCompiler.java:1808)
00:47:50  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:352)
00:47:50  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
00:47:50  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)
00:47:50  	... 9 more
00:47:50  
00:47:50  TEST RESULT: Error. Error invoking compiler
```

**Comment by 0xdaryl** [comment] 2021-04-01 13:02
XL builds are no more, so this issue may be moot.  But we need to check if this is still a reproducible problem for large heap.  This won't happen for 0.26.

**Comment by pshipton** [comment] 2022-01-04 19:22
Since we're not seeing problem in the nightly builds I'm going to assume this is fixed and close it.

**Closed by pshipton** 2022-01-04 19:22 UTC
Labels: test failure, arch:aarch64
