### ISSUE TITLE
jdk19 OpenJDK java/nio/Buffer/ReachabilityTest.java crash vmstate 5FF04

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16747] opened 2023-02-21 13:38 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/114
jdk11_tier1_buffer_1
java/nio/Buffer/ReachabilityTest.java

vmState [0x5ff04]: {J9VMSTATE_JIT} {InstructionSelection}

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/114/openjdk_test_output.tar.gz
```
23:09:16  rerun:
23:09:16  cd /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0 && \
23:09:16  DISPLAY=:0 \
23:09:16  HOME=/home/jenkins \
23:09:16  LANG=C.UTF-8 \
23:09:16  PATH=/bin:/usr/bin:/usr/sbin \
23:09:16      /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
23:09:16          -Dtest.vm.opts='-ea -esa -Xmx512m -XX:-UseCompressedOops' \
23:09:16          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:-UseCompressedOops' \
23:09:16          -Dtest.compiler.opts= \
23:09:16          -Dtest.java.opts= \
23:09:16          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
23:09:16          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/j2sdk-image \
23:09:16          -Dtest.timeout.factor=8.0 \
23:09:16          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
23:09:16          -Dtest.root=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
23:09:16          -Dtest.name=java/nio/Buffer/ReachabilityTest.java \
23:09:16          -Dtest.file=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/Buffer/ReachabilityTest.java \
23:09:16          -Dtest.src=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/Buffer \
23:09:16          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/Buffer \
23:09:16          -Dtest.classes=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/classes/0/java/nio/Buffer/ReachabilityTest.d \
23:09:16          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/classes/0/java/nio/Buffer/ReachabilityTest.d \
23:09:16          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/classes/0/java/nio/Buffer/ReachabilityTest.d:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/Buffer \
23:09:16          -classpath /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/classes/0/java/nio/Buffer/ReachabilityTest.d:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/Buffer:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/guice.jar:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
23:09:16          com.sun.javatest.regtest.agent.TestNGRunner java/nio/Buffer/ReachabilityTest.java false ReachabilityTest
23:09:16  stderr:
23:09:16  JVMDUMP012E Error in System dump: The core file created by child process with pid = 2070001 was not found.  Expected to find core file with name "/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/core.2070001"
23:09:16  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/javacore.20230218.040857.2069897.0002.txt' in response to an event
23:09:16  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/javacore.20230218.040857.2069897.0002.txt
23:09:16  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/Snap.20230218.040857.2069897.0003.trc' in response to an event
23:09:16  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/Snap.20230218.040857.2069897.0003.trc
23:09:16  JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/jitdump.20230218.040857.2069897.0004.dmp' in response to an event
23:09:16  JVMDUMP051I JIT dump occurred in 'JIT Compilation Thread-000' thread 0x0000FFFF4C002400
23:09:16  JVMDUMP049I JIT dump notified all waiting threads of the current method to be compiled
23:09:16  JVMDUMP054I JIT dump is tracing the IL of the method on the crashed compilation thread
23:09:16  JVMDUMP052I JIT dump recursive crash occurred on diagnostic thread
23:09:16  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/jitdump.20230218.040857.2069897.0004.dmp
23:09:16  JVMDUMP013I Processed dump event "gpf", detail "".
```
```
1TISIGINFO     Dump Event "gpf" (00002000) received
1TIDATETIMEUTC Date: 2023/02/18 at 04:09:12:080 (UTC)
1TIDATETIME    Date: 2023/02/18 at 04:09:12:080
1TITIMEZONE    Timezone: UTC (UTC)
1TINANOTIME    System nanotime: 16526204100888790
1TIFILENAME    Javacore filename:    /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_16766863559305/jdk11_tier1_buffer_1/work/scratch/0/javacore.20230218.040857.2069897.0002.txt
1TIREQFLAGS    Request Flags: 0x41 (exclusive+preempt)
1TIPREPSTATE   Prep State: 0x80 (trace_disabled)
1TIPREPINFO    Exclusive VM access not taken: data may not be consistent across javacore sections
NULL           ------------------------------------------------------------------------
0SECTION       GPINFO subcomponent dump routine
NULL           ================================
2XHOSLEVEL     OS Level         : Linux 5.4.0-122-generic
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : aarch64
3XHNUMCPUS       How Many       : 4
3XHNUMASUP       NUMA is either not supported or has been disabled by user
NULL
1XHEXCPCODE    J9Generic_Signal_Number: 00000108
1XHEXCPCODE    Signal_Number: 00000005
1XHEXCPCODE    Error_Value: 00000000
1XHEXCPCODE    Signal_Code: FFFFFFFA
1XHEXCPCODE    Handler1: 0000FFFF91BBC744
1XHEXCPCODE    Handler2: 0000FFFF91B23AC0
NULL
1XHEXCPMODULE  Module: /lib/aarch64-linux-gnu/libpthread.so.0
1XHEXCPMODULE  Module_base_address: 0000FFFF922AA000
1XHEXCPMODULE  Symbol: raise
1XHEXCPMODULE  Symbol_address: 0000FFFF922BD6F8
NULL
1XHREGISTERS   Registers:
2XHREGISTER      R0: 0000000000000000
2XHREGISTER      R1: 0000FFFF52629B38
2XHREGISTER      R2: 0000000000000000
2XHREGISTER      R3: 0000000000000008
2XHREGISTER      R4: 0000000000000000
2XHREGISTER      R5: 0000FFFF922D5000
2XHREGISTER      R6: FFFFFFFFFFFFFFFF
2XHREGISTER      R7: FFFFFFFFFFFFFFFF
2XHREGISTER      R8: 0000000000000087
2XHREGISTER      R9: 0000FFFF52629D10
2XHREGISTER      R10: FFFFFFFFFFFFFFFF
2XHREGISTER      R11: FFFFFFFFFFFFFFFF
2XHREGISTER      R12: FFFFFFFFFFFFFFFF
2XHREGISTER      R13: FFFFFFFFFFFFFFFF
2XHREGISTER      R14: FFFFFFFFFFFFFFFF
2XHREGISTER      R15: FFFFFFFFFFFFFFFF
2XHREGISTER      R16: FFFFFFFFFFFFFFFF
2XHREGISTER      R17: FFFFFFFFFFFFFFFF
2XHREGISTER      R18: FFFFFFFFFFFFFFFF
2XHREGISTER      R19: FFFFFFFFFFFFFFFF
2XHREGISTER      R20: 0000FFFF913C2828
2XHREGISTER      R21: 0000FFFF51537990
2XHREGISTER      R22: 00000000FFFFFFFF
2XHREGISTER      R23: 0000FFFF515B4E90
2XHREGISTER      R24: 0000FFFF515B4EE0
2XHREGISTER      R25: 0000000000000002
2XHREGISTER      R26: 0000000000000001
2XHREGISTER      R27: 0000000000000004
2XHREGISTER      R28: 0000000000000000
2XHREGISTER      R29: 0000FFFF52629B10
2XHREGISTER      R30: 0000FFFF52629B38
2XHREGISTER      R31: 0000FFFF52629B10
2XHREGISTER      V0: 2525252525252525
2XHREGISTER      V1: 0A7325203A642523
2XHREGISTER      V2: 2073616820474643
2XHREGISTER      V3: 0000000000000000
2XHREGISTER      V4: 0000000000000000
2XHREGISTER      V5: 0000040000000400
2XHREGISTER      V6: 0000000000000000
2XHREGISTER      V7: 4010040140100401
2XHREGISTER      V8: 0000000000000000
2XHREGISTER      V9: 0000000000000000
2XHREGISTER      V10: 0000000000000000
2XHREGISTER      V11: 0000000000000000
2XHREGISTER      V12: 0000000000000000
2XHREGISTER      V13: 0000000000000000
2XHREGISTER      V14: 0000000000000000
2XHREGISTER      V15: 0000000000000000
2XHREGISTER      V16: 0000000055550404
2XHREGISTER      V17: 00000000A8000000
2XHREGISTER      V18: 0000000000000000
2XHREGISTER      V19: 0000000000000000
2XHREGISTER      V20: 3FB1EB851EB851EC
2XHREGISTER      V21: 0000000000000008
2XHREGISTER      V22: 3F0000003F800000
2XHREGISTER      V23: 3FC999999999999A
2XHREGISTER      V24: 3FD6666666666666
2XHREGISTER      V25: 0000000000000000
2XHREGISTER      V26: 3FB999999999999A
2XHREGISTER      V27: 0000000000000300
2XHREGISTER      V28: 0000000000000800
2XHREGISTER      V29: 0000000000000300
2XHREGISTER      V30: 0000000000000000
2XHREGISTER      V31: 0000000000000000
2XHREGISTER      PC: 0000FFFF922BD7D8
2XHREGISTER      SP: 0000FFFF52629B10
2XHREGISTER      PSTATE: 0000000000000000
1XHEXCPMODULE  Compiling method: CopyDirectByteMemory.test()V
NULL
1XHFLAGS       VM flags:000000000005FF04
```

**Comment by JasonFengJ9** [comment] 2023-03-10 14:30
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/127/consoleFull
```
23:14:46  ===============================================
23:14:46  Running test jdk11_tier1_buffer_1 ...
23:14:46  ===============================================
23:14:46  jdk11_tier1_buffer_1 Start Time: Thu Mar  9 04:14:46 2023 Epoch Time (ms): 1678335286177
23:14:46  variation: Mode650
23:14:46  JVM_OPTIONS:  -XX:-UseCompressedOops 

23:15:56  TEST: java/nio/Buffer/ReachabilityTest.java

23:15:56  stderr:
23:15:56  JVMDUMP012E Error in System dump: The core file created by child process with pid = 4052620 was not found.  Expected to find core file with name "/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/core.4052620"
23:15:56  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/javacore.20230309.041535.4052514.0002.txt' in response to an event
23:15:56  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/javacore.20230309.041535.4052514.0002.txt
23:15:56  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/Snap.20230309.041535.4052514.0003.trc' in response to an event
23:15:56  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/Snap.20230309.041535.4052514.0003.trc
23:15:56  JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/jitdump.20230309.041535.4052514.0004.dmp' in response to an event
23:15:56  JVMDUMP051I JIT dump occurred in 'JIT Compilation Thread-000' thread 0x0000FFFF3C002400
23:15:56  JVMDUMP049I JIT dump notified all waiting threads of the current method to be compiled
23:15:56  JVMDUMP054I JIT dump is tracing the IL of the method on the crashed compilation thread
23:15:56  JVMDUMP052I JIT dump recursive crash occurred on diagnostic thread
23:15:56  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/scratch/1/jitdump.20230309.041535.4052514.0004.dmp
23:15:56  JVMDUMP013I Processed dump event "gpf", detail "".
23:15:56  
23:15:56  TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details
23:15:56  --------------------------------------------------
23:15:56  Test results: passed: 11; error: 1
23:16:11  Report written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/report/html/report.html
23:16:11  Results written to /home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work
23:16:11  Error: Some tests failed or other problems occurred.
23:16:11  -----------------------------------
23:16:11  jdk11_tier1_buffer_1_FAILED
```

`aqa-tests/TKG/output_1678328527861/jdk11_tier1_buffer_1/work/java/nio/Buffer/ReachabilityTest/javacore.20230309.041535.4052514.0002.txt`
```
1XHEXCPMODULE  Compiling method: CopyDirectByteMemory.test()V
NULL
1XHFLAGS       VM flags:000000000005FF04
```

**Comment by pshipton** [comment] 2023-03-13 18:15
@JasonFengJ9 pls run a grinder on this one.

**Comment by pshipton** [comment] 2023-03-13 21:52
@0xdaryl fyi

**Comment by pshipton** [comment] 2023-03-14 14:07
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/130/
jdk11_tier1_buffer_1
java/nio/Buffer/ReachabilityTest.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_Nightly/130/openjdk_test_output.tar.gz
```
1XHEXCPMODULE  Compiling method: CopyDirectByteMemory.test()V
NULL
1XHFLAGS       VM flags:000000000005FF04
```

**Comment by Akira1Saitoh** [comment] 2023-03-14 23:57
I will take a look.

**Comment by Akira1Saitoh** [comment] 2023-03-15 03:18
The failing test is not RechabilityTest.java but CopyDirectMemory.java.
It crashes because opcode b2s is not implemented.
```
    229 Assertion failed at /home/jenkins/workspace/Build_JDK19_aarch64_linux_Nightly/omr/compiler/aarch64/codegen/OMRTreeEvaluator.cpp:5225: false
    230 VMState: 0x0005ff04
    231         Opcode b2s is not implemented
    232 compiling CopyDirectByteMemory.test()V at level: cold
```

**Comment by Akira1Saitoh** [comment] 2023-03-15 06:01
Found jitdump in the artifact. The return value of `Basic.ic` is converted by `l2b`(n58n). Then `su2i` (n202n), `b2s` (n201n) are used to convert byte to char.
```
    137 n56n      treetop                                                                             [    0xffff9c526140] bci=[-1,45,59] rc=0 vc=189 vn=- li=4 udi=- nc=1
    138 n54n        lcall  Basic.ic(I)J[#365  static Method] [flags 0x500 0x0 ]                       [    0xffff9c5260a0] bci=[-1,45,59] rc=0 vc=189 vn=- li=4 udi=55904
    138 nc=1
    139 n53n          isub (cannotOverflow )                                                          [    0xffff9c526050] bci=[-1,44,59] rc=0 vc=189 vn=- li=4 udi=55648
    139 nc=2 flg=0x1000
    140 n37n            ==>iload
    141 n52n            iconst -1 (X!=0 X<=0 )                                                        [    0xffff9c526000] bci=[-1,43,59] rc=0 vc=189 vn=- li=4 udi=- nc=0
    141  flg=0x204
    142 n231n     lstore  <temp slot 6>[#399  Auto] [flags 0x20000004 0x0 ] (privatizedInlinerArg )   [    0xffff9c5297f0] bci=[-1,41,59] rc=0 vc=189 vn=- li=4 udi=- nc=1
    142  flg=0x2000
    143 n50n        i2l                                                                               [    0xffff9c4ab730] bci=[-1,41,59] rc=0 vc=189 vn=- li=4 udi=64384
    143 nc=1
    144 n48n          ==>icalli
    145 n232n     lstore  <temp slot 7>[#400  Auto] [flags 0x20000004 0x0 ] (privatizedInlinerArg )   [    0xffff9c529840] bci=[-1,50,59] rc=0 vc=189 vn=- li=4 udi=- nc=1
    145  flg=0x2000
    146 n60n        b2l                                                                               [    0xffff9c526280] bci=[-1,50,59] rc=0 vc=189 vn=- li=4 udi=64864
    146 nc=1
    147 n58n          l2b                                                                             [    0xffff9c5261e0] bci=[-1,49,59] rc=1 vc=189 vn=- li=4 udi=55904
    147 nc=1
    148 n54n            ==>lcall
...
    178 n211n     treetop                                                                             [    0xffff9c5291b0] bci=[1,15,105] rc=0 vc=189 vn=- li=15 udi=- nc= 1
    179 n210n       call  Basic.fail(Ljava/nio/Buffer;Ljava/lang/String;CLjava/lang/String;C)V[#397  static Method] [flags 0x500 0x0 ] ()  [    0xffff9c529160] bci=[1,15, 105] rc=1 vc=189 vn=- li=15 udi=- nc=5 flg=0x20
    180 n45n          ==>aload
    181 n197n         ==>acall
    182 n202n         su2i (X>=0 )                                                                    [    0xffff9c528ee0] bci=[1,7,106] rc=1 vc=189 vn=- li=15 udi=- nc=1  flg=0x100
    183 n201n           b2s (cannotOverflow )                                                         [    0xffff9c528e90] bci=[1,7,106] rc=1 vc=189 vn=- li=15 udi=- nc=1  flg=0x1000
    184 n58n              ==>l2b
    185 n204n         ==>acall
    186 n209n         su2i (X>=0 )                                                                    [    0xffff9c529110] bci=[1,14,107] rc=1 vc=189 vn=- li=15 udi=- nc=1 flg=0x100
    187 n208n           i2s                                                                           [    0xffff9c5290c0] bci=[1,14,107] rc=1 vc=189 vn=- li=15 udi=- nc=1
    188 n48n              ==>icalli
    189 n179n     BBEnd </block_15> =====                                                             [    0xffff9c5287b0] bci=[0,12,118] rc=0 vc=189 vn=- li=15 udi=- nc=0


```

**Comment by Akira1Saitoh** [comment] 2023-03-15 08:06
I will implement b2sEvaluator. I have not been able to reproduce the crash so far, though.
100x grinder on jdk11_tier1_buffer_1 in internal Jenkins passed. `/job/Grinder/31635/`

**Comment by Akira1Saitoh** [comment] 2023-03-17 06:59
Opened https://github.com/eclipse/omr/pull/6928.

**Comment by Akira1Saitoh** [comment] 2023-03-22 03:07
https://github.com/eclipse/omr/pull/6928 has been merged.

**Comment by knn-k** [comment] 2023-03-23 00:13
Thank you @Akira1Saitoh.

I ran the following Grinder jobs (90 runs in total) for jdk11_tier1_buffer_1 with the latest nightly build that contains eclipse/omr#6928, and all of them finished successfully.
https://openj9-jenkins.osuosl.org/job/Grinder/2106/
https://openj9-jenkins.osuosl.org/job/Grinder/2107/
https://openj9-jenkins.osuosl.org/job/Grinder/2108/

Is it too late to deliver the b2s change to v0.37/v0.38?
I think its risk is minimum, because it only replaces a call to an unimplemented JIT evaluator by a call to an existing one.

**Comment by pshipton** [comment] 2023-03-23 00:58
Pls create PRs for 0.37 and 0.38.

**Comment by Akira1Saitoh** [comment] 2023-03-23 01:33
Created PRs for 0.37 and 0.38.
https://github.com/eclipse-openj9/openj9-omr/pull/168
https://github.com/eclipse-openj9/openj9-omr/pull/169

**Comment by knn-k** [comment] 2023-03-23 01:36
I reviewed and merged both of them.

**Closed** 2023-03-27 00:35 UTC
Labels: comp:jit, test failure, arch:aarch64, segfault, jdk19
