### ISSUE TITLE
JDK 19 MiniMix_5m_1 hang in Thread.getStateImpl

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16036] opened 2022-10-04 13:29 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.system_s390x_linux_Nightly_testList_1/19
MiniMix_5m_1

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_extended.system_s390x_linux_Nightly_testList_1/19/system_test_output.tar.gz

```
LT  04:08:01.390 - Completed 13.4%. Number of tests started=10586 (+3937)
STF 04:12:19.367 - Heartbeat: Process LT  is still running
STF 04:17:19.211 - Heartbeat: Process LT  is still running
STF 04:22:19.069 - Heartbeat: Process LT  is still running
STF 04:27:19.047 - Heartbeat: Process LT  is still running
STF 04:32:19.283 - Heartbeat: Process LT  is still running
STF 04:37:19.023 - Heartbeat: Process LT  is still running
STF 04:42:19.203 - Heartbeat: Process LT  is still running
STF 04:47:19.411 - Heartbeat: Process LT  is still running
STF 04:52:19.009 - Heartbeat: Process LT  is still running
STF 04:57:19.398 - Heartbeat: Process LT  is still running
STF 05:02:19.487 - Heartbeat: Process LT  is still running
STF 05:07:19.427 - Heartbeat: Process LT  is still running
STF 05:12:19.456 - Heartbeat: Process LT  is still running
STF 05:12:20.457 - **FAILED** Process LT  has timed out
```

```
3XMTHREADINFO      "load-9" J9VMThread:0x000000000060BE00, omrthread_t:0x000003FF8C5B5040, java/lang/Thread:0x000000003A012EF0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x21, isDaemon:false)
3XMJAVALTHRCCL            jdk/internal/loader/ClassLoaders$AppClassLoader(0x0000000039A7D7F8)
3XMTHREADINFO1            (native thread ID:0xEE4E, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00001001)
3XMTHREADINFO2            (native stack address range from:0x000003FF6C1BC000, to:0x000003FF6C1FC000, size:0x40000)
3XMCPUTIME               CPU usage total: 3.111664071 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=2331328 (0x2392C0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.getStateImpl(Native Method)
4XESTACKTRACE                at java/lang/Thread.threadState(Thread.java:2864(Compiled Code))
5XESTACKTRACE                   (entered lock: java/lang/Object@0x000000003A07F8C8, entry count: 1)
4XESTACKTRACE                at java/lang/Thread.isTerminated(Thread.java:2872(Compiled Code))
4XESTACKTRACE                at java/lang/Thread.getThreadGroup(Thread.java:2025(Compiled Code))
4XESTACKTRACE                at java/lang/ThreadGroup.enumerate(ThreadGroup.java:450)
4XESTACKTRACE                at gnu/testlet/java/lang/ThreadGroup/enumerate.test(enumerate.java:48)
4XESTACKTRACE                at java/lang/invoke/LambdaForm$DMH/0x00000000d80054f0.invokeVirtual(LambdaForm$DMH(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x00000000d8005be0.invoke(LambdaForm$MH(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/LambdaForm$MH/0x000000008c40ee70.invokeExact_MT(LambdaForm$MH(Compiled Code))
4XESTACKTRACE                at jdk/internal/reflect/DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155(Compiled Code))
4XESTACKTRACE                at jdk/internal/reflect/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:578(Compiled Code))
4XESTACKTRACE                at net/adoptopenjdk/loadTest/adaptors/MauveAdaptor.executeTest(MauveAdaptor.java:74(Compiled Code))
4XESTACKTRACE                at net/adoptopenjdk/loadTest/LoadTestRunner$2.run(LoadTestRunner.java:182)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:1573)
```

**Comment by pshipton** [comment] 2022-10-04 13:29
@babsingh @tajila fyi

**Comment by tajila** [comment] 2022-10-04 13:39
@ChengJin01 Please take a look at this

**Comment by ChengJin01** [comment] 2022-10-05 03:13
1) I went through the dumps at https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_extended.system_s390x_linux_Nightly_testList_1/19/system_test_output.tar.gz and didn't find any suspicious thread that might trigger the hang in the failing job. In addition, there was no deadlock detected via jdmpview.

As for the J9VMThread `load-9` mentioned in the description, it was waiting for a unowned mutex lock, which doesn't seem to be hung in there.
```
2LKREGMON          Thread public flags mutex lock (0x000003FF8C421268): <unowned> <------
3LKNOTIFYQ            Waiting to be notified:
3LKWAITNOTIFY            "load-9" (J9VMThread:0x000000000060BE00)
```

2) I manually ran the failing test suite `MiniMix_5m_1` on one of Jenkins zLinux machines and it always passed without any issue.
3) There is no hang detected so far in the Grinder (X50/still ongoing) at https://openj9-jenkins.osuosl.org/job/Grinder/1321/consoleText.

**Comment by pshipton** [comment] 2022-10-05 03:22
There are a couple of javacore files, taken a minute apart, and both showed the same stack for the "load-9" thread.

**Comment by ChengJin01** [comment] 2022-10-05 04:03
Assuming there was something happening for "load-9" thread according to the javacores,
```
3XMTHREADINFO      "load-9" J9VMThread:0x000000000060BE00, omrthread_t:0x000003FF8C5B5040, java/lang/Thread:0x000000003A012EF0, state:R, prio=5
...
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.getStateImpl(Native Method) <------
4XESTACKTRACE                at java/lang/Thread.threadState(Thread.java:2864(Compiled Code))
5XESTACKTRACE                   (entered lock: java/lang/Object@0x000000003A07F8C8, entry count: 1)
4XESTACKTRACE                at java/lang/Thread.isTerminated(Thread.java:2872(Compiled Code))
4XESTACKTRACE                at java/lang/Thread.getThreadGroup(Thread.java:2025(Compiled Code))
4XESTACKTRACE                at java/lang/ThreadGroup.enumerate(ThreadGroup.java:450)
4XESTACKTRACE                at gnu/testlet/java/lang/ThreadGroup/enumerate.test(enumerate.java:48)
...
3XMTHREADINFO3           Native callstack:
...
4XENATIVESTACK                (0x000003FF6C1F9B10 [<unknown>+0x0])
4XENATIVESTACK               pthread_cond_wait+0x138 (0x000003FF9108C3B0 [libpthread.so.0+0xc3b0])
4XENATIVESTACK                (0x000003FF90607B26 [libj9thr29.so+0x7b26])
4XENATIVESTACK               omrthread_monitor_wait+0x60 (0x000003FF9060B690 [libj9thr29.so+0xb690])
4XENATIVESTACK                (0x000003FF90818D9A [libj9vm29.so+0x98d9a]) <--- internalAcquireVMAccessNoMutexWithMask
4XENATIVESTACK                (0x000003FF9081C8EA [libj9vm29.so+0x9c8ea]) <--- haltThreadForInspection (via objdump)
4XENATIVESTACK               Java_java_lang_Thread_getStateImpl+0x90 (0x000003FF8AC55E08 [libjclse29.so+0x55e08])
4XENATIVESTACK                (0x000003FF6FB5839A [<unknown>+0x0])
```
it should be stuck at the native method `getStateImpl()` in `Thread.threadState` at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/b9e3daf582ff40b3a187281241c3cb691e4fec73/src/java.base/share/classes/java/lang/Thread.java#L2864
```
    boolean isTerminated() {
        return threadState() == State.TERMINATED;
    }

    State threadState() {
        synchronized (interruptLock) {
            if (eetop == NO_REF) {
                if (isDead()) {
                    return State.TERMINATED;
                }
                return State.NEW;
            }
            return State.values()[getStateImpl(eetop)]; <-------
        }
    }
```
where the native code of `getStateImpl` was at https://github.com/eclipse-openj9/openj9/blob/96fe9b858827d90eb7ad49817a29b0da2e73c2b5/runtime/jcl/common/thread.cpp#L87
```
Java_java_lang_Thread_getStateImpl(JNIEnv *env, jobject recv, jlong threadRef)
{
...
	Trc_JCL_Thread_getStateImpl_Entry(currentThread, vmThread);
	currentThread->javaVM->internalVMFunctions->internalEnterVMFromJNI(currentThread);
	currentThread->javaVM->internalVMFunctions->haltThreadForInspection(currentThread, vmThread); <------
```
and https://github.com/eclipse-openj9/openj9/blob/e6744487bdab6ba75dd7299ba98fff260bfbba2e/runtime/vm/VMAccess.cpp#L1296
```
haltThreadForInspection(J9VMThread * currentThread, J9VMThread * vmThread)
{

_tryAgain:

	Assert_VM_mustHaveVMAccess(currentThread);

	/* Inspecting the current thread does not require any halting */
	if (currentThread != vmThread) {
		VM_VMAccess::setPublicFlags(currentThread, J9_PUBLIC_FLAGS_NOT_AT_SAFE_POINT);

		omrthread_monitor_enter(vmThread->publicFlagsMutex);

		/* increment the inspection count but don't try to short circuit -- the thread might not actually be halted yet */
		vmThread->inspectionSuspendCount += 1;

		/* Now halt the thread for inspection */
		setHaltFlag(vmThread, J9_PUBLIC_FLAGS_HALT_THREAD_INSPECTION);

		/* If the thread doesn't have VM access and it not queued for exclusive we can proceed immediately */
		if (vmThread->publicFlags & (J9_PUBLIC_FLAGS_VM_ACCESS | J9_PUBLIC_FLAGS_QUEUED_FOR_EXCLUSIVE)) {
			/* Release VM access while waiting */
			/* (We must release the other thread's publicFlagsMutex to avoid deadlock here) */
			omrthread_monitor_exit(vmThread->publicFlagsMutex);
			internalReleaseVMAccess(currentThread);
			omrthread_monitor_enter(vmThread->publicFlagsMutex);
#if defined(J9VM_INTERP_ATOMIC_FREE_JNI)
#if defined(J9VM_INTERP_ATOMIC_FREE_JNI_USES_FLUSH)
			flushProcessWriteBuffers(currentThread->javaVM);
#endif /* J9VM_INTERP_ATOMIC_FREE_JNI_USES_FLUSH */
			VM_AtomicSupport::readWriteBarrier(); // necessary?
#endif /* J9VM_INTERP_ATOMIC_FREE_JNI */
			if (VM_VMAccess::mustWaitForVMAccessRelease(vmThread)) {
				while (J9_ARE_ANY_BITS_SET(vmThread->publicFlags, J9_PUBLIC_FLAGS_VM_ACCESS | J9_PUBLIC_FLAGS_QUEUED_FOR_EXCLUSIVE)) {
					omrthread_monitor_wait(vmThread->publicFlagsMutex);
				}
			}
			omrthread_monitor_exit(vmThread->publicFlagsMutex);

			/* Thread is halted - reacquire VM access */
	
			omrthread_monitor_enter(currentThread->publicFlagsMutex);
----------->     internalAcquireVMAccessNoMutexWithMask(currentThread, J9_PUBLIC_FLAGS_HALT_THREAD_ANY - J9_PUBLIC_FLAGS_HALT_THREAD_INSPECTION);
			omrthread_monitor_exit(currentThread->publicFlagsMutex);
```

**Comment by ChengJin01** [comment] 2022-10-05 04:08
It seems `haltThreadForInspection` was only modified via https://github.com/eclipse-openj9/openj9/pull/15227 recently to fixed a couple of hang related issues. So I am wondering whether there was any connection between this issue and the PR.

**Comment by ChengJin01** [comment] 2022-10-05 04:08
FYI: @amicic

**Comment by ChengJin01** [comment] 2022-10-06 16:24
Launched another Grinder (x200) at https://openj9-jenkins.osuosl.org/job/Grinder/1327/ with the latest passing build at https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/167/ to see how it goes.

**Comment by tajila** [comment] 2022-10-07 13:27
@ChengJin01 Do you know if this fails on JDK17?

**Comment by ChengJin01** [comment] 2022-10-07 14:52
> @ChengJin01 Do you know if this fails on JDK17?

This job never fails on JDK17 in recent history at https://openj9-jenkins.osuosl.org/view/Test_System_Nightly/job/Test_openjdk17_j9_extended.system_s390x_linux_Nightly/, but we can launch a Grinder with the latest build to double-check.

**Comment by ChengJin01** [comment] 2022-10-07 14:58
Launched a Grinder (x200) at https://openj9-jenkins.osuosl.org/job/Grinder/1329/  with the latest build at https://openj9-jenkins.osuosl.org/view/Test_System_Nightly/job/Test_openjdk17_j9_extended.system_s390x_linux_Nightly/328/.

**Comment by ChengJin01** [comment] 2022-10-07 15:12
The previously completed Grinder at https://openj9-jenkins.osuosl.org/job/Grinder/1327/ ended without any issue (killed by after 98 runs due to timeout) at https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/161/consoleText
```
[2022-10-07T02:18:56.782Z] LT  02:18:54.278 - Completed 46.9%. Number of tests started=34837 (+5415)
[2022-10-07T02:19:15.668Z] Cancelling nested steps due to timeout
[2022-10-07T02:19:15.835Z] Sending interrupt signal to process
[2022-10-07T02:19:17.071Z] LT  02:19:14.265 - Completed 53.6%. Number of tests started=39086 (+4249)
```

So it seems the hang was only triggered by the changes between https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/168/
```
OpenJ9: [c19e4267798](https://github.com/eclipse-openj9/openj9/commit/c19e4267798b13e6ee21c71290a2877c07fc4abb)
OMR: [b8f2f89464c](https://github.com/eclipse-openj9/openj9-omr/commit/b8f2f89464ca71f38dd7d63f49bd3fc0f945224d)
OpenJDK19: [b9e3daf582f](https://github.com/ibmruntimes/openj9-openjdk-jdk19/commit/b9e3daf582ff40b3a187281241c3cb691e4fec73) - openj9-openjdk-jdk19
```
and https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK19/167/
```
OpenJ9: [710fd952924](https://github.com/eclipse-openj9/openj9/commit/710fd952924c673ee702fcbc311c99d70095ecde)
OMR: [f99c9dd2248](https://github.com/eclipse-openj9/openj9-omr/commit/f99c9dd2248e6ee35e40536b3c243eee33924407)
OpenJDK19: [05db3773ec3](https://github.com/ibmruntimes/openj9-openjdk-jdk19/commit/05db3773ec323ac48a721cc22e59b0a768e5d4e7) - openj9-openjdk-jdk19
```

**Comment by gacholio** [comment] 2022-10-07 16:34
If I understand the above comments, this rules out https://github.com/eclipse-openj9/openj9/pull/15227 as the cause (committed in June).

It would be helpful to see the `!threads stack` and `!threads flags` output.

**Comment by ChengJin01** [comment] 2022-10-11 15:18
There was no hang detected in the Grinder at https://openj9-jenkins.osuosl.org/job/Grinder/1327/ for JDK17. So the problem is mostly likely related to Project Loom in JDK19 for the merged changes in OpenJ9 between https://github.com/eclipse-openj9/openj9/commit/c19e4267798b13e6ee21c71290a2877c07fc4abb  and  https://github.com/eclipse-openj9/openj9/commit/710fd952924c673ee702fcbc311c99d70095ecde given there is nothing suspicious in OMR changes.

**Comment by gacholio** [comment] 2022-10-11 15:26
https://github.com/eclipse-openj9/openj9/compare/710fd952924c673ee702fcbc311c99d70095ecde...c19e4267798b13e6ee21c71290a2877c07fc4abb

**Comment by gacholio** [comment] 2022-10-11 15:35
Nothing immediately suspicious - does the test fail with `-Xint` or on platforms other than 390?

**Comment by ChengJin01** [comment] 2022-10-11 15:51
Just Launched a couple of Grinders (x100) with the latest build on other platforms plus the failing build with `-Xint` on Linux/s390x see how it goes.
https://openj9-jenkins.osuosl.org/job/Grinder/1349/ (Linux/x86_64)
https://openj9-jenkins.osuosl.org/job/Grinder/1350/ (macOS/Aarch64)
https://openj9-jenkins.osuosl.org/job/Grinder/1351/ (AIX/PPC64)
https://openj9-jenkins.osuosl.org/job/Grinder/1352/ (with -Xint on Linux/s390x)

**Comment by pshipton** [comment] 2022-10-11 18:32
So far we've only ever seen this hang once, in jdk19 nightly builds.

**Comment by ChengJin01** [comment] 2022-10-12 17:25
All grinders at https://github.com/eclipse-openj9/openj9/issues/16036#issuecomment-1274917568 passed without any issue:
https://openj9-jenkins.osuosl.org/job/Grinder/1352/tapTestReport/ (with -Xint on Linux/s390x)
https://openj9-jenkins.osuosl.org/job/Grinder/1351/tapTestReport/ (AIX/PPC64)
https://openj9-jenkins.osuosl.org/job/Grinder/1350/tapTestReport/ (macOS/Aarch64)
https://openj9-jenkins.osuosl.org/job/Grinder/1349/tapTestReport/ (Linux/x86_64)

So it seems the hang only occurred on Linux/s390x with JIT enabled and was captured only once in Grinder(x50) at https://openj9-jenkins.osuosl.org/job/Grinder/1321/consoleText.

**Comment by gacholio** [comment] 2022-10-14 16:46
If that's the case, getting the information I requested earlier (thread flags, java stacks and native stacks) will help us figure out what's going on.

**Comment by ChengJin01** [comment] 2022-10-14 22:31
1) The flags of threads in the core don't seem to be problematic as follows:
```
> !threads flags
Attached Threads List. For more options, run !threads help

    !j9vmthread 0x69700 publicFlags=1 privateFlags=1008 inNative=0 // main <---J9_PUBLIC_FLAGS_HALT_THREAD_EXCLUSIVE 
    !j9vmthread 0x6bd00 publicFlags=1 privateFlags=101a inNative=0 // JIT Compilation Thread-000
    !j9vmthread 0x6e300 publicFlags=1 privateFlags=101a inNative=0 // JIT Compilation Thread-001
    !j9vmthread 0x204900 publicFlags=49000 privateFlags=0 inNative=0 // load-0 <-- J9_PUBLIC_FLAGS_EXCLUSIVE_SET_NOT_SAFE  |  J9_PUBLIC_FLAGS_HALT_THREAD_INSPECTION  |  J9_PUBLIC_FLAGS_NOT_AT_SAFE_POINT 
    !j9vmthread 0x5f9000 publicFlags=1 privateFlags=0 inNative=0 // load-1
    !j9vmthread 0x5fb600 publicFlags=1 privateFlags=0 inNative=0 // load-2
    !j9vmthread 0x5fdb00 publicFlags=20001 privateFlags=0 inNative=0 // load-3 <--- J9_PUBLIC_FLAGS_THREAD_PARKED  | J9_PUBLIC_FLAGS_HALT_THREAD_EXCLUSIVE 
    !j9vmthread 0x600100 publicFlags=20001 privateFlags=0 inNative=0 // load-4
    !j9vmthread 0x602700 publicFlags=1 privateFlags=0 inNative=0 // load-5
    !j9vmthread 0x604d00 publicFlags=20001 privateFlags=0 inNative=0 // load-6
    !j9vmthread 0x607300 publicFlags=20001 privateFlags=0 inNative=0 // load-7
    !j9vmthread 0x609900 publicFlags=20001 privateFlags=0 inNative=0 // load-8
    !j9vmthread 0x60be00 publicFlags=1001 privateFlags=0 inNative=0 // load-9 <---- J9_PUBLIC_FLAGS_NOT_AT_SAFE_POINT |  J9_PUBLIC_FLAGS_HALT_THREAD_EXCLUSIVE 
    !j9vmthread 0x6ef800 publicFlags=20001 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-1
    !j9vmthread 0x6fe300 publicFlags=20001 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-2
    !j9vmthread 0x737500 publicFlags=20001 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-3
    !j9vmthread 0x745c00 publicFlags=20001 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-4
    !j9vmthread 0x748200 publicFlags=20001 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-5
    !j9vmthread 0x74e800 publicFlags=20001 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-6
    !j9vmthread 0x754e00 publicFlags=1 privateFlags=2 inNative=0 // ForkJoinPool-2-worker-8
...
```
#define J9_PUBLIC_FLAGS_HALT_THREAD_EXCLUSIVE 0x1
#define J9_PUBLIC_FLAGS_NOT_AT_SAFE_POINT 0x1000
#define J9_PUBLIC_FLAGS_THREAD_PARKED 0x20000
#define J9_PUBLIC_FLAGS_EXCLUSIVE_SET_NOT_SAFE 0x40000
#define J9_PUBLIC_FLAGS_HALT_THREAD_INSPECTION 0x8000

2) I went through the code changes listed at https://github.com/eclipse-openj9/openj9/compare/710fd952924c673ee702fcbc311c99d70095ecde...c19e4267798b13e6ee21c71290a2877c07fc4abb, in which the only PR that looks suspicious is https://github.com/eclipse-openj9/openj9/pull/15752 (which was to support Virtual
Threads in JIT on zLinux) given the hang never happens on other platforms and never occurs with JIT off on zLinux.

So I will revert the changes to see how it goes in Grinder.

**Comment by gacholio** [comment] 2022-10-17 15:28
The impression I get from @pshipton is that this happened exactly once and has never been reproduced, so I'm not sure there's any reason to blame any change. Was the pinning support updated in the next build?

**Comment by ChengJin01** [comment] 2022-10-17 15:54
> The impression I get from @pshipton is that this happened exactly once and has never been reproduced

As I mentioned above, the hang is only reproduced on the failing build but never on the build right before the failing build or the latest build.

> Was the pinning support updated in the next build?

I didn't see any update on these two files in https://github.com/eclipse-openj9/openj9/pull/15752 or anything related to pinning support after it was merged.

**Comment by ChengJin01** [comment] 2022-10-18 16:11
Just talked to GAC, we close the issue given  there is no way to reproduce it in the latest build and no further evidence to prove the hang was caused by any change unless the problem shows up again.

**Closed by ChengJin01** 2022-10-18 16:11 UTC
Labels: comp:vm, test failure, jdk19
