### ISSUE TITLE
JDK8 JDK build finished with error: cannot find symbol

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18500] opened 2023-11-21 15:33 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-openj9/778/consoleFull)(`ubu20-aarch64-2`):
```
13:26:38  openjdk version "1.8.0_392"
13:26:38  IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
13:26:38  Eclipse OpenJ9 VM (build v0.41.0-release-461bf3c70, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20231120_778 (JIT enabled, AOT enabled)
13:26:38  OpenJ9   - 461bf3c70
13:26:38  OMR      - 5eee6ad9d
13:26:38  JCL      - b73cbdd342 based on jdk8u392-b08)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
13:19:17  ## Starting jdk
13:19:18  Importing CORBA classes.jar
13:19:18  Importing CORBA src.zip
13:19:18  Importing CORBA bin.zip
13:19:18  Importing JAXP classes.jar
13:19:18  Importing JAXP src.zip
13:19:19  Importing JAXWS classes.jar
13:19:19  Importing JAXWS src.zip
13:19:20  Importing LANGTOOLS src.zip
13:19:20  Importing LANGTOOLS classes.jar
13:19:27  Generating charsetmapping classes
13:19:27  Generating buffer classes
13:19:27  Compiling 165 files for BUILD_TOOLS
13:19:27  Generating exceptions classes
13:19:27  Generating icon classes
13:19:31  Note: Some input files use unchecked or unsafe operations.
13:19:31  Note: Recompile with -Xlint:unchecked for details.
13:19:31  Compiling 521 properties into resource bundles
13:19:31  Copying and cleaning 53 properties
13:19:31  Creating sun/util/LocaleDataMetaInfo.java from 423 found resources.
13:19:32  Generating sun/misc/Version.java
13:19:32  Generating sun/misc/Version.java compact1
13:19:32  Generating sun/misc/Version.java compact2
13:19:32  Generating sun/misc/Version.java compact3
13:19:33  Aliases: Table size 1024 (10 bits), shift 0, max chain depth 3
13:19:33  Classes: Table size 32 (5 bits), shift 1, max chain depth 3
13:19:34  Cache: Table size 32 (5 bits), shift 1, max chain depth 3
13:19:38  Generating X11 wrapper (64-bit version)
13:19:39  Generating beaninfo
13:19:39  Generating Nimbus source files
13:19:41  [Error] encoded value was less than 0: encode(-8.326673E-17, 5.0, 11.0, 16.0)
13:19:41  Verifying /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/gensrc_x11wrappers/sizes.64.verification.tmp to /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/gensrc_x11wrappers/sizes.64
13:19:41  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:41  [Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
13:19:41  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:41  [Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
13:19:41  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:41  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:41  [Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
13:19:41  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:41  [Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
13:19:41  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:42  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:42  [Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
13:19:42  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:42  [Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
13:19:42  [Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
13:19:42  [Error] Encountered Infinity: encode(-0.00877193, 0.0, 7.0, 7.0)
13:19:46  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/io/ObjectInputStream.java:378: error: cannot find symbol
13:19:46      private static final ClassByNameCache classByNameCache;
13:19:46                           ^
13:19:46    symbol:   class ClassByNameCache
13:19:46    location: class ObjectInputStream
13:19:46  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/sun/misc/URLClassPath.java:66: error: package com.ibm.oti.shared does not exist
13:19:46  import com.ibm.oti.shared.CannotSetClasspathException;                          
13:19:46                           ^
13:19:46  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/sun/misc/URLClassPath.java:67: error: package com.ibm.oti.shared does not exist
13:19:46  import com.ibm.oti.shared.SharedClassURLClasspathHelper;
13:19:46                           ^
13:19:46  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/security/Provider.java:43: error: package openj9.internal.security does not exist
13:19:46  import openj9.internal.security.RestrictedSecurity;
13:19:46                                 ^
13:19:46  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/sun/misc/URLClassPath.java:126: error: cannot find symbol
13:19:46      private SharedClassURLClasspathHelper sharedClassURLClasspathHelper = null; 
13:19:46              ^
13:19:46    symbol:   class SharedClassURLClasspathHelper
13:19:46    location: class URLClassPath
13:19:46  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/sun/misc/URLClassPath.java:179: error: cannot find symbol
13:19:46                          SharedClassURLClasspathHelper helper) {                 
13:19:46                          ^
13:19:46    symbol:   class SharedClassURLClasspathHelper
13:19:46    location: class URLClassPath
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/security/SecureRandom.java:43: error: package openj9.internal.security does not exist
13:19:48  import openj9.internal.security.RestrictedSecurity;
13:19:48                                 ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/net/URLClassLoader.java:68: error: package com.ibm.oti.shared does not exist
13:19:48  import com.ibm.oti.shared.Shared;                                               
13:19:48                           ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/net/URLClassLoader.java:69: error: package com.ibm.oti.shared does not exist
13:19:48  import com.ibm.oti.shared.SharedClassHelperFactory;                             
13:19:48                           ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/net/URLClassLoader.java:70: error: package com.ibm.oti.shared does not exist
13:19:48  import com.ibm.oti.shared.SharedClassURLClasspathHelper;                        
13:19:48                           ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/net/URLClassLoader.java:71: error: package com.ibm.oti.shared does not exist
13:19:48  import com.ibm.oti.shared.HelperAlreadyDefinedException;                        
13:19:48                           ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/net/URLClassLoader.java:96: error: cannot find symbol
13:19:48      private SharedClassURLClasspathHelper sharedClassURLClasspathHelper;         
13:19:48              ^
13:19:48    symbol:   class SharedClassURLClasspathHelper
13:19:48    location: class URLClassLoader
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/util/ServiceLoader.java:48: error: package openj9.internal.security does not exist
13:19:48  import openj9.internal.security.RestrictedSecurity;
13:19:48                                 ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/security/Security.java:44: error: package openj9.internal.security does not exist
13:19:48  import openj9.internal.security.RestrictedSecurity;
13:19:48                                 ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/java/net/URLClassLoader.java:103: error: package SharedClassURLClasspathHelper does not exist
13:19:48      private class SharedClassIndexHolder implements SharedClassURLClasspathHelper.IndexHolder {  
13:19:48                                                                                   ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/sun/security/jca/ProviderList.java:39: error: package openj9.internal.security does not exist
13:19:48  import openj9.internal.security.RestrictedSecurity;
13:19:48                                 ^
13:19:48  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/jdk/src/share/classes/sun/security/jca/ProviderConfig.java:41: error: package openj9.internal.security does not exist
13:19:48  import openj9.internal.security.RestrictedSecurity;
13:19:48                                 ^
13:19:54  Generating HTML DTD file
13:19:54  Compiling 4 files for BUILD_BREAKITERATOR
13:19:54  [Parsed DTD html32 in 103ms]
13:20:24  Compiling 10714 files for BUILD_JDK

13:26:38  ## Finished images (build time 00:03:29)
13:26:38  
13:26:38  rc=0; /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/images/j2re-image/bin/java -version >/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/images/test/openj9/java-version.txt 2>&1 || rc="$?"; /usr/bin/cat /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/images/test/openj9/java-version.txt; exit "$rc"
13:26:38  openjdk version "1.8.0_392"
13:26:38  IBM Semeru Runtime Open Edition (build 1.8.0_392-b08)
13:26:38  Eclipse OpenJ9 VM (build v0.41.0-release-461bf3c70, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20231120_778 (JIT enabled, AOT enabled)
13:26:38  OpenJ9   - 461bf3c70
13:26:38  OMR      - 5eee6ad9d
13:26:38  JCL      - b73cbdd342 based on jdk8u392-b08)
13:26:39  build.sh : 18:26:39 : Build complete ...
```

Similar issue occurred at [JDK8 linux-ppc64le weekly build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/782/)

**Comment by pshipton** [comment] 2023-11-21 15:46
This doesn't appear to be an error that blocks the builds. I don't think it's new either. It's a dup of https://github.com/eclipse-openj9/openj9/issues/15665

**Comment by JasonFengJ9** [comment] 2023-11-21 16:09
> This doesn't appear to be an error that blocks the builds. I don't think it's new either. It's a dup of https://github.com/eclipse-openj9/openj9/issues/15665

Agreed, this is not a blocker, I didn't assign it w/ a milestone.
The build/test seems not affected by these errors.
Open this issue for tracking purposes and hopefully find out the cause.

**Comment by pshipton** [comment] 2023-11-21 17:13
@keithc-ca any ideas why this occurs?

**Comment by keithc-ca** [comment] 2023-11-21 18:05
I reproduced this by trying to build with `OPENJDK=true` in my environment. This should either always happen or never happen unless the build environment has changed. Could this be due to https://github.com/eclipse-openj9/openj9/pull/18498?

**Comment by pshipton** [comment] 2023-11-21 18:17
> Could this be due to https://github.com/eclipse-openj9/openj9/pull/18498?

I don't think so, it's been happening for a long time. See https://github.com/eclipse-openj9/openj9/issues/15665 where it was reported in 2022, and ignored.

**Comment by pshipton** [comment] 2023-11-21 18:19
Also note
- this occurs on a 0.41 build, which doesn't have any compiler changes
- it's reported on aarch64, although it probably happens on all platforms

**Comment by keithc-ca** [comment] 2023-11-21 18:49
`OPENJDK=true` has nothing to do with this: it is normally defined in `spec.gmk`:
```sh
$ grep -w OPENJDK spec.gmk 
OPENJDK=true
```

**Comment by keithc-ca** [comment] 2023-11-21 19:30
I can now build without these errors. I will reduce the change to a minimum and then open a pull request.

**Comment by pshipton** [comment] 2023-11-21 22:54
Should be fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/708

**Closed** 2023-11-21 22:55 UTC
Labels: test failure
