### ISSUE TITLE
DaaLoadTest_daa2 net.openj9.test.binaryData.TestBinaryConverters FAILURE: testDoubleNormals

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17320] opened 2023-05-02 14:04 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_special.system_aarch64_linux_testList_1/424/)(`ub18-aarch64-6`):
```
openjdk version "1.8.0_372"
IBM Semeru Runtime Open Edition (build 1.8.0_372-b07)
Eclipse OpenJ9 VM (build master-d4443d666, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20230429_621 (JIT enabled, AOT enabled)
OpenJ9   - d4443d666
OMR      - 7ddb743ea
JCL      - 9837b5b6b based on jdk8u372-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=DaaLoadTest_daa2_special_5m_28&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F621%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2023-04-29-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=451&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-04-29T13:41:51.965Z] variation: Mode645
[2023-04-29T13:41:51.965Z] JVM_OPTIONS:  -Xcompressedrefs -Xgcpolicy:gencon -Xshareclasses -Xjit 

[2023-04-29T13:42:52.391Z] DLT class net.openj9.test.binaryData.TestBinaryConverters Total: 10 Fail: 1 Ignore: 0
[2023-04-29T13:42:52.391Z] DLT 	FAILURE: testDoubleNormals(net.openj9.test.binaryData.TestBinaryConverters) - expected:<9218868437227405311> but was:<9221120237041090560>

[2023-04-29T13:42:52.392Z] DLT class net.openj9.test.binaryData.TestBinaryConverters Total: 10 Fail: 1 Ignore: 0
[2023-04-29T13:42:52.392Z] DLT 	FAILURE: testDoubleNormals(net.openj9.test.binaryData.TestBinaryConverters) - expected:<9218868437227405311> but was:<9221120237041090560>

[2023-04-29T13:42:52.392Z] DLT class net.openj9.test.binaryData.TestBinaryConverters Total: 10 Fail: 1 Ignore: 0
[2023-04-29T13:42:52.392Z] DLT 	FAILURE: testDoubleNormals(net.openj9.test.binaryData.TestBinaryConverters) - expected:<9218868437227405311> but was:<9221120237041090560>

[2023-04-29T13:42:52.392Z] DLT class net.openj9.test.binaryData.TestBinaryConverters Total: 10 Fail: 1 Ignore: 0
[2023-04-29T13:42:52.392Z] DLT 	FAILURE: testDoubleNormals(net.openj9.test.binaryData.TestBinaryConverters) - expected:<9218868437227405311> but was:<9221120237041090560>

[2023-04-29T13:42:52.392Z] DLT class net.openj9.test.binaryData.TestBinaryConverters Total: 10 Fail: 1 Ignore: 0
[2023-04-29T13:42:52.392Z] DLT 	FAILURE: testDoubleNormals(net.openj9.test.binaryData.TestBinaryConverters) - expected:<9218868437227405311> but was:<9221120237041090560>

[2023-04-29T13:42:52.392Z] DLT class net.openj9.test.binaryData.TestBinaryConverters Total: 10 Fail: 1 Ignore: 0
[2023-04-29T13:42:52.392Z] DLT 	FAILURE: testDoubleNormals(net.openj9.test.binaryData.TestBinaryConverters) - expected:<9218868437227405311> but was:<9221120237041090560>

[2023-04-29T13:42:52.392Z] DLT Test failed:
[2023-04-29T13:42:52.392Z] DLT net.adoptopenjdk.loadTest.BlockedExitException
[2023-04-29T13:42:52.392Z] DLT 	at net.adoptopenjdk.loadTest.LoadTest$1.checkExit(LoadTest.java:140)
[2023-04-29T13:42:52.392Z] DLT 	at java.lang.Runtime.exit(Runtime.java:101)
[2023-04-29T13:42:52.392Z] DLT 	at java.lang.System.exit(System.java:382)
[2023-04-29T13:42:52.392Z] DLT 	at net.openj9.test.MarshallingTestRunner.invokeTest(MarshallingTestRunner.java:89)
[2023-04-29T13:42:52.392Z] DLT 	at sun.reflect.GeneratedMethodAccessor859.invoke(Unknown Source)
[2023-04-29T13:42:52.392Z] DLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-04-29T13:42:52.392Z] DLT 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-04-29T13:42:52.392Z] DLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
[2023-04-29T13:42:52.392Z] DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
[2023-04-29T13:42:52.392Z] DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-04-29T13:42:52.392Z] DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-04-29T13:42:52.392Z] DLT 	at java.lang.Thread.run(Thread.java:826)
[2023-04-29T13:42:52.392Z] DLT <<<

[2023-04-29T13:42:52.393Z] STF 09:42:52.213 - Overall result: **FAILED**
[2023-04-29T13:42:52.393Z] -----------------------------------
[2023-04-29T13:42:52.393Z] DaaLoadTest_daa2_special_5m_28_FAILED

```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32616/) - 14/50 failed

**Comment by pshipton** [comment] 2023-05-02 20:12
Failed 14 / 50.

@0xdaryl I'm guessing JIT, can someone start looking at this failure in 0.38 pls. 

Started a grinder with -Xint
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32625/

**Comment by pshipton** [comment] 2023-05-02 20:14
Also a [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32626/) on the 0.36 release.

**Comment by 0xdaryl** [comment] 2023-05-03 02:03
@nbhuiyan : can you take an initial look at this please?

**Comment by pshipton** [comment] 2023-05-03 19:54
My bad, this is a failure on the head stream and not 0.38.

Check again it still fails on head.
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32640/ - still failing, cancelled it
Try again with 0.36
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32651/ - seems to be passing
Try with 0.38 m2
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32652/ - passed
Try with 0.38 m1
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32653/ - seems to be passing

**Comment by nbhuiyan** [comment] 2023-05-04 00:25
I have identified the latest nightly build where this problem did not exist: [JDK8 aarch64 Linux Nightly 3 April 2023](https://openj9-jenkins.osuosl.org/view/Build_Nightly/job/Build_JDK8_aarch64_linux_Nightly/395/)
```
Eclipse OpenJ9 VM (build master-ff024fc4240, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20230403_395 (JIT enabled, AOT enabled)
OpenJ9   - ff024fc4240
OMR      - 2d7aff0254f
JCL      - dd50bfd81e6 based on jdk8u372-b06)
```

The earliest build with which this test failure is reproducible: [JDK8 aarch64 Linux Nightly 4 April 2023](https://openj9-jenkins.osuosl.org/view/Build_Nightly/job/Build_JDK8_aarch64_linux_Nightly/396/)
```
17:54:33  Eclipse OpenJ9 VM (build master-ff3512b5664, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20230404_396 (JIT enabled, AOT enabled)
OpenJ9   - ff3512b5664
OMR      - 2d7aff0254f
JCL      - dd50bfd81e6 based on jdk8u372-b06)
```

Between the 2 OpenJ9 versions, we had  #17015 merged which enabled arrayset optimization on aarch64, for which the aarch64 support was implemented in eclipse/omr#6934. I re-ran with -Xjit:disableArraySetOpts but was still able to reproduce the failure. Perhaps the option was not being applied properly, or was not actually negating the change in #17015.

**Comment by 0xdaryl** [comment] 2023-05-04 00:38
Thanks @nbhuiyan.  A quick re-review of the PRs seems to suggest that `Xjit:disableArraySetOpts` should do what it says.  If you're able to build, maybe try a build reverting #17015 that enabled this to see if it fails.

@Akira1Saitoh FYI.  This might need a look from you when you are back.

**Comment by nbhuiyan** [comment] 2023-05-04 19:10
Seems like the options were not being passed properly through the test framework. This test [no longer fails](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32687/) using my [change](https://github.com/nbhuiyan/openj9/commit/d3e60d3bcbe1bc4a692fae366a8563292c2d22af) that just reverts #17015.

**Comment by 0xdaryl** [comment] 2023-05-04 19:12
Thanks @nbhuiyan.   @Akira1Saitoh : could you take over the investigation please?

**Comment by pshipton** [comment] 2023-05-04 19:21
Since this is a regression, I'm setting the blocker label. 
It's currently in the 0.40 plan, but we should consider including the fix in the 0.39 release for 20.0.1.

**Comment by Akira1Saitoh** [comment] 2023-05-08 07:49
I took the core dump when AssertionError was thrown.
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32756/

- stack frame of [testDoubleNormals](https://github.com/eclipse-openj9/openj9-systemtest/blob/07823bfaba2795e03acfe7e55208603c2811a094/openj9.test.daa/src/test.daa/net/openj9/test/binaryData/TestBinaryConverters.java#L3489-L3893)
```
<462800> JIT frame: bp = 0x000000000047D2F8, pc = 0x0000FFFF61931258, unwindSP = 0x000000000047D270, cp = 0x00000000004D7050, arg0EA = 0x000000000047D300, jitInfo = 0x0000FFFF60B6CD38
<462800>        Method: net/openj9/test/binaryData/TestBinaryConverters.testDoubleNormals()V !j9method 0x00000000004CF6A0
<462800>        Bytecode index = 1,564, inlineDepth = 0, PC offset = 0x00000000000013B0
<462800>        stackMap=0x0000FFFF60B6D648, slots=I16(0x0001) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0001), localBaseOffset=I16(0xFFF8)
<462800>        Described JIT args starting at 0x000000000047D300 for U16(0x0001) slots
<462800>                O-Slot: : a0[0x000000000047D300] = 0x00000000FE320938
<462800>        Described JIT temps starting at 0x000000000047D2F0 for IDATA(0x0000000000000001) slots
<462800> Address 0x0000FFFF60B6F408
<462800> Num internal ptr map bytes U8(0x03)
<462800> Address 0x0000FFFF60B6F409
<462800> Index of first internal ptr I16(0x0001)
<462800> Address 0x0000FFFF60B6F40B
<462800> Offset of first internal ptr I16(0xFFF8)
<462800> Address 0x0000FFFF60B6F40D
<462800> Num distinct pinning arrays U8(0x01)
<462800> Before object slot walk &address : 0x000000000047D2F0 address : 0x00000000FE320C08 bp 0x000000000047D2F8 offset of first internal ptr I16(0xFFF8)
<462800> After object slot walk for pinning array with &address : 0x000000000047D2F0 old address 0x00000000FE320C08 new address 0x00000000FE320C08 displacement IDATA(0x0000000000000000)
<462800> For pinning array U8(0x00) num internal pointer stack slots U8(0x00)
<462800>                I-Slot: : t0[0x000000000047D2F0] = 0x00000000FE320C08
<462800>        JIT-RegisterMap = UDATA(0x0000000080800000)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D258] = UDATA(0x00000000004D9E88) (jit_r21)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D1E8] = UDATA(0x00000000FE320C1C) (jit_r22)
<462800>                JIT-RegisterMap-O-Slot[0x000000000047D1F0] = 0x00000000FE320C08 (jit_r23)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D1F8] = UDATA(0x00000000FE2B31F8) (jit_r24)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D200] = UDATA(0x00000000FE2B3810) (jit_r25)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D208] = UDATA(0x00000000FE2B37E0) (jit_r26)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D210] = UDATA(0x00000000FE2BC118) (jit_r27)
<462800>                JIT-RegisterMap-I-Slot[0x000000000047D218] = UDATA(0x00000000FE2B31F8) (jit_r28)
```

- JIT generated instructions for `testDoubleNormals` before the failing call to `assertDoubleEquals`.
```
   0xffff61931158:      b.ge    0xffff6193196c  // b.tcont                                                              
   0xffff6193115c:      ldr     x1, [x20, #128]                    <-- byte_array                                                                       
   0xffff61931160:      sxtw    x2, w3                                                                                  
   0xffff61931164:      add     x2, x2, #0x10                                                                           
   0xffff61931168:      add     x0, x1, x2                                                                              
   0xffff6193116c:      mov     w2, #0x10                       // #16                                                  
   0xffff61931170:      sub     w2, w2, w3                                                                              
   0xffff61931174:      sxtw    x2, w2                                                                                  
   0xffff61931178:      movi    v0.16b, #0x0                                                                            
   0xffff6193117c:      cbz     x2, 0xffff619311f4                                                                      
   0xffff61931180:      add     x4, x0, x2                                                                              
   0xffff61931184:      cmp     x2, #0x20                                                                               
   0xffff61931188:      b.cc    0xffff619311d8  // b.lo, b.ul, b.last                                                   
   0xffff6193118c:      stp     q0, q0, [x0]                                                                            
   0xffff61931190:      cmp     x2, #0x60                                                                               
   0xffff61931194:      b.ls    0xffff619311c8  // b.plast                                                              
   0xffff61931198:      sub     x2, x2, #0x60                                                                           
   0xffff6193119c:      and     x3, x0, #0xf                                                                            
   0xffff619311a0:      add     x2, x2, x3                                                                              
   0xffff619311a4:      and     x0, x0, #0xfffffffffffffff0                                                             
   0xffff619311a8:      subs    x2, x2, #0x40                                                                           
   0xffff619311ac:      stp     q0, q0, [x0, #32]                                                                       
   0xffff619311b0:      stp     q0, q0, [x0, #64]!                                                                      
   0xffff619311b4:      b.hi    0xffff619311a8  // b.pmore                                                              
   0xffff619311b8:      add     x0, x0, x2                                                                              
   0xffff619311bc:      stp     q0, q0, [x0, #32]                                                                       
   0xffff619311c0:      stp     q0, q0, [x0, #64]                                                                       
   0xffff619311c4:      b       0xffff619311f4                                                                          
   0xffff619311c8:      tbz     w2, #6, 0xffff619311d0                                                                  
   0xffff619311cc:      stp     q0, q0, [x0, #32]                                                                       
   0xffff619311d0:      stp     q0, q0, [x4, #-32]                                                                      
   0xffff619311d4:      b       0xffff619311f4                                                                          
   0xffff619311d8:      tbz     w2, #4, 0xffff619311e8
   0xffff619311dc:      str     q0, [x0] 
   0xffff619311e0:      stur    q0, [x4, #-16]            
   0xffff619311e4:      b       0xffff619311f4
   0xffff619311e8:      subs    x2, x2, #0x1
   0xffff619311ec:      strb    wzr, [x0], #1
   0xffff619311f0:      b.hi    0xffff619311e8  // b.pmore 
   0xffff619311f4:      str     d31, [x20, #104]
   0xffff619311f8:      nop                                 
   0xffff619311fc:      nop                                 
   0xffff61931200:      ldr     w0, [x1, #4]              
   0xffff61931204:      cmp     w0, #0xb  
   0xffff61931208:      b.ls    0xffff61934494  // b.plast
   0xffff6193120c:      ldr     d0, [x20, #104]                                                                         
   0xffff61931210:      fmov    x0, d0                    
   0xffff61931214:      rev     x0, x0         
   0xffff61931218:      str     x0, [x1, #16]                 <-- storing value to the first element of byte_array
   0xffff6193121c:      nop                                 
   0xffff61931220:      nop                                 
   0xffff61931224:      fmov    d0, d31                                                                                 
   0xffff61931228:      ldr     x23, [x20, #128]          <-- loading byte_array to x23
   0xffff6193122c:      ldr     w0, [x23, #4]
   0xffff61931230:      cmp     w0, #0xb    
   0xffff61931234:      b.ls    0xffff61934498  // b.plast
   0xffff61931238:      add     x22, x23, #0x14
   0xffff6193123c:      ldr     x0, [x22]                      <-- loading value at byte_array + 4
   0xffff61931240:      rev     x0, x0                                                                                  
   0xffff61931244:      fmov    d1, x0      
   0xffff61931248:      str     d1, [x20, #104]
   0xffff6193124c:      ldr     x0, [x20, #144]           
   0xffff61931250:      ldr     d1, [x20, #104]
   0xffff61931254:      bl      0xffff61cb61e4
```

It seems that inlined `ByteArrayMarshaller.writeDouble` writes the value to the beginning of the data address of byte_array, but `ByteArrayUnmarshaller.readDouble` (this was also inlined) reads the value from the address 4bytes from the beginning. I am not sure either one is wrong. Trying to get a trace file for this method.

**Comment by Akira1Saitoh** [comment] 2023-05-09 04:24
I was able to obtain the trace, and it appears that the following tree is storing a long value into the address 20 bytes from the aload address, but the generated code is using the immediate offset form incorrectly. The immediate offset of the `strimmx` instruction must be 8-byte aligned. As a 20-byte offset cannot be encoded, it should be encoded as `str x0, [x1, #16]`, which is what I saw in the dump.

I am not sure why the problem disappears when the arrayset optimization is disabled, but I suspect that it somehow changes the reference count of the `aladd` node. If the reference count of `aladd` is greater than 1, the problem would not occur because the immediate offset form would not be used.

I am preparing a fix which validates the immediate offset of memory references.
```
403217	------------------------------
403218	 n16688n  (  0)  lstorei  <generic int shadow>[#1325  Shadow] [flags 0x603 0x0 ] ()                   [    0xffff7a633000] bci=[55,78,-] rc=0 vc=6831 vn=- li=908 udi=- nc=2 flg=0x20
403219	 n16689n  (  0)    aladd (X>=0 internalPtr )                                                          [    0xffff7a633050] bci=[55,75,-] rc=0 vc=6831 vn=- li=908 udi=- nc=2 flg=0x8100
403220	 n15943n  (  0)      ==>aload (in &GPR_3008) (X!=0 )
403221	 n16690n  (  0)      lconst 20 (highWordZero X!=0 X>=0 )                                              [    0xffff7a6330a0] bci=[55,78,-] rc=0 vc=6831 vn=- li=908 udi=- nc=0 flg=0x4104
403222	 n16693n  (  0)    lbyteswap (in GPR_3026)                                                            [    0xffff7a633190] bci=[55,74,-] rc=0 vc=6831 vn=- li=908 udi=52032 nc=1
403223	 n16694n  (  0)      dbits2l (in GPR_3026)                                                            [    0xffff7a6331e0] bci=[55,74,-] rc=0 vc=6831 vn=- li=908 udi=52032 nc=1
403224	 n16695n  (  1)        dload  <temp slot 6>[#1147  Auto] [flags 0x20000006 0x0 ] (in FPR_3025)        [    0xffff7a633230] bci=[55,74,-] rc=1 vc=6831 vn=- li=908 udi=51696 nc=0
403225	------------------------------
403226	
403227	 [    0xfffef33bcab0]	74 	vldrimmd 	FPR_3025, [w20, 0]		# SymRef  <temp slot 6>[#1147  Auto] [flags 0x20000006 0x0 ]	
403228	 [    0xfffef33bcbb0]	74 	fmov_dtox 	GPR_3026, FPR_3025
403229	 [    0xfffef33bcc40]	74 	revx 	GPR_3026, GPR_3026
403230	 [    0xfffef33bccd0]	78 	strimmx 	GPR_3026, [&GPR_3008, 20]		# SymRef  <generic int shadow>[#1325  Shadow] [flags 0x603 0x0 ]	
403231	
```

**Comment by Akira1Saitoh** [comment] 2023-05-09 08:13
Opened https://github.com/eclipse/omr/pull/6981.

50x internal grinder passed with the personal build containing the PR.
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32769/

**Comment by Akira1Saitoh** [comment] 2023-05-09 23:45
https://github.com/eclipse/omr/pull/6981 has been merged.

**Comment by knn-k** [comment] 2023-05-11 00:53
The OMR fix above has promoted to the openj9 branch of openj9-omr.

**Comment by pshipton** [comment] 2023-05-11 01:08
If https://github.com/eclipse/omr/pull/6981 is supposed to fix this, we can close it. We will reopen if seen again.

**Closed by pshipton** 2023-05-11 01:08 UTC
Labels: comp:jit, test failure, blocker, arch:aarch64
