### ISSUE TITLE
JDK19 java/lang/Thread/virtual/stress/YieldALot.java#id0 timed out with JIT enabled

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16051] opened 2022-10-05 19:52 UTC
```
"main" prio=5 Id=2 WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2146)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2222)
        at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:72)

"JIT Compilation Thread-000" prio=10 Id=4 RUNNABLE

"JIT Compilation Thread-001" prio=10 Id=5 RUNNABLE

"JIT Compilation Thread-002 Suspended" prio=10 Id=6 RUNNABLE

"JIT Compilation Thread-003 Suspended" prio=10 Id=7 RUNNABLE

"JIT Compilation Thread-004 Suspended" prio=10 Id=8 RUNNABLE

"JIT Compilation Thread-005 Suspended" prio=10 Id=9 RUNNABLE

"JIT Compilation Thread-006 Suspended" prio=10 Id=10 RUNNABLE

"JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=11 RUNNABLE

"JIT-SamplerThread" prio=10 Id=12 TIMED_WAITING

"IProfiler" prio=5 Id=13 RUNNABLE

"Common-Cleaner" prio=8 Id=3 TIMED_WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:137)
        at java.base@19-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)
        at java.base@19-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

"GC Worker" prio=5 Id=14 RUNNABLE

"GC Worker" prio=5 Id=15 RUNNABLE

"GC Worker" prio=5 Id=16 RUNNABLE

"GC Worker" prio=5 Id=17 RUNNABLE

"GC Worker" prio=5 Id=18 RUNNABLE

"GC Worker" prio=5 Id=19 RUNNABLE

"GC Worker" prio=5 Id=20 RUNNABLE

"Attach API wait loop" prio=10 Id=23 TIMED_WAITING
        at java.base@19-internal/java.lang.Thread.sleepImpl(Native Method)
        at java.base@19-internal/java.lang.Thread.sleep0(Thread.java:477)
        at java.base@19-internal/java.lang.Thread.sleep(Thread.java:472)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:142)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
        at java.base@19-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:157)

"MainThread" prio=5 Id=25 TIMED_WAITING
        at java.base@19-internal/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@19-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
        at java.base@19-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:717)
        at java.base@19-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1074)
        at java.base@19-internal/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
        at java.base@19-internal/java.lang.VirtualThread.joinNanos(VirtualThread.java:751)
        at java.base@19-internal/java.lang.Thread.join(Thread.java:2260)
        at app//YieldALot.main(YieldALot.java:61)
        at java.base@19-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base@19-internal/java.lang.reflect.Method.invoke(Method.java:578)
        at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base@19-internal/java.lang.Thread.run(Thread.java:1573)

"Attachment portNumber: 36575" prio=10 Id=28 RUNNABLE
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
        at java.base@19-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
        at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:248)
        at java.base@19-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:159)

"file lock watchdog" prio=10 Id=29 TIMED_WAITING
        at java.base@19-internal/java.lang.Object.wait(Native Method)
        at java.base@19-internal/java.lang.Object.wait(Object.java:219)
        at java.base@19-internal/java.util.TimerThread.mainLoop(Timer.java:563)
        at java.base@19-internal/java.util.TimerThread.run(Timer.java:516)


--- Timeout information end.
finished: Tue Oct 04 12:57:39 PDT 2022
elapsed time (seconds): 120.843
configuration:
STDOUT:
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
1001
Timeout refired 120 times
1001
1001
STDERR:
```

**Comment by babsingh** [comment] 2022-10-06 16:55
In my local run, I don't notice a hang. Instead, I see the assertion in yieldContinuation trigger. Potential duplicate of https://github.com/eclipse-openj9/openj9/issues/16047. Symptoms similar to https://github.com/eclipse-openj9/openj9/issues/16047#issuecomment-1270217444.

**Comment by tajila** [comment] 2022-10-20 15:16
@thallium does this still fail?

**Comment by thallium** [comment] 2022-10-20 16:02
> @thallium does this still fail?

Passes now

**Closed** 2022-10-20 17:06 UTC
Labels: test failure, project:loom, jdk19
