### ISSUE TITLE
JDK21 serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default Fatal error: test_vthread_resume_all: error in JVMTI ResumeThread

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18364] opened 2023-10-27 20:16 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux/12/)(`sles12x86-rtp-rt2-1`):
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202310260910 (build 21.0.1-beta+12-202310260910)
Eclipse OpenJ9 VM 21.0.1+12-202310260910 (build master-66e3fd1da, JRE 21 Linux amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
OpenJ9   - 66e3fd1da
OMR      - 071c0c25b
JCL      - c06eaf638 based on jdk-21.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=serviceability_jvmti_j9_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-x64-openj9-IBM%2F22%2Fibm-semeru-certified-jdk_x64_linux_JDK21U_2023-10-26-09-08.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-linux-x64-openj9-IBM%2F22%2Fibm-semeru-certified-testimage_x64_linux_JDK21U_2023-10-26-09-08.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=%21%28sw.os.cent.6%7C%7Csw.os.rhel.6%29&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-10-26T10:05:28.672Z] variation: Mode650
[2023-10-26T10:05:28.672Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-10-26T10:10:20.851Z] TEST: serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default

[2023-10-26T10:10:20.853Z] STDERR:
[2023-10-26T10:10:20.853Z] 
[2023-10-26T10:10:20.853Z] Fatal error: test_vthread_resume_all: error in JVMTI ResumeThread

[2023-10-26T10:10:20.853Z] TEST RESULT: Failed. Unexpected exit from test [exit code: 87]
[2023-10-26T10:10:20.853Z] --------------------------------------------------
[2023-10-26T10:10:33.864Z] Test results: passed: 152; failed: 1
[2023-10-26T10:10:44.219Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2023-10-26T10:10:44.219Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux/aqa-tests/TKG/output_16983143442893/serviceability_jvmti_j9_1/work
[2023-10-26T10:10:44.219Z] Error: Some tests failed or other problems occurred.
[2023-10-26T10:10:44.219Z] -----------------------------------
[2023-10-26T10:10:44.219Z] serviceability_jvmti_j9_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35695/)

FYI @babsingh

**Comment by babsingh** [comment] 2023-10-28 01:39
Closing, duplicate of https://github.com/eclipse-openj9/openj9/issues/17869. The reported failure is a variant of the failure seen in https://github.com/eclipse-openj9/openj9/issues/17869. Similar failures can be reported in https://github.com/eclipse-openj9/openj9/issues/17869.

**Closed by babsingh** 2023-10-28 01:39 UTC
Labels: comp:vm, test failure, comp:jvmti, jdk21
