### ISSUE TITLE
Segmentation-Error during code change in debug session

### ISSUE THREAD

**Issue by c-koell** [eclipse-openj9/openj9#20229] opened 2024-09-25 12:33 UTC
Java -version output
--------------------
openjdk version "21.0.4" 2024-07-16 LTS
IBM Semeru Runtime Open Edition 21.0.4.1 (build 21.0.4+7-LTS)
Eclipse OpenJ9 VM 21.0.4.1 (build openj9-0.46.1, JRE 21 Windows 10 amd64-64-Bit Compressed References 20240716_260 (JIT enabled, AOT enabled)
OpenJ9   - 4760d5d320
OMR      - 840a9adba
JCL      - db3fffb417c based on jdk-21.0.4+7)

Summary of problem
------------------

If i try to change the code during debug session the jvm crashes with segmentation error.

Diagnostic files
----------------

```
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFBCF7ADB69 ContextFlags=0010005f
Handler1=00007FFBCF81E340 Handler2=00007FFBFEC3AC60 InaccessibleReadAddress=0000000000000818
RDI=0000004EFC3CF3C8 RSI=0000000000000090 RAX=0000000000000808 RBX=0000004EFC3CF3D0
RCX=0000000000000000 RDX=000001B06D7D76A2 R8=0000000000000000 R9=00000000000F4240
R10=0000000000989680 R11=000001B0776A9F8A R12=0000000000133778 R13=000000060543EBA0
R14=0000004EFC3CF3C8 R15=0000000000133770
RIP=00007FFBCF7ADB69 RSP=0000004EFC3CEF00 RBP=0000004EFC3CF3D8 EFLAGS=0000000000010206
FS=0053 ES=002B DS=002B
XMM0=43e0000000000000 (f: 0.000000, d: 9.223372e+18)
XMM1=4098dccccccccccd (f: 3435973888.000000, d: 1.591200e+03)
XMM2=4024000000000000 (f: 0.000000, d: 1.000000e+01)
XMM3=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM7=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM8=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14=0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15=0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\Program Files\openjdk-21\bin\default\j9vm29.dll
Module_base_address=00007FFBCF750000 Offset_in_DLL=000000000005db69
Target=2_90_20240716_260 (Windows 10 10.0 build 19045)
CPU=amd64 (12 logical CPUs) (0x7ec12d000 RAM)
----------- Stack Backtrace -----------
(0x00007FFBCF7ADB69 [j9vm29+0x5db69])
(0x0000000000494580)
---------------------------------------
```
I have also dump files if needed

**Comment by pshipton** [comment] 2024-09-25 12:41
@tajila fyi

**Comment by pshipton** [comment] 2024-09-25 12:43
Pls provide the diagnostic files, the most important being the "core" file (not to be confused with the javacore).

**Comment by c-koell** [comment] 2024-09-25 12:45
You can find the dump under following cloud storage https://tbox.tirol.gv.at/index.php/s/4GrR9CpkZrawBaJ with "7RDEMYbTGt" as password

**Comment by pshipton** [comment] 2024-09-26 14:49
For some reason I can't open that link (or even https://tbox.tirol.gv.at), I get a timeout. I don't think it's my work network connection, I can't open it from my phone (different network) either.

**Comment by c-koell** [comment] 2024-09-27 05:25
@pshipton Oh sorry. We have at the moment some problems with a ddos attack. I think we have activated some geo blocking.
I will check ist and come back to you soon.

**Comment by c-koell** [comment] 2024-09-27 05:30
@pshipton from where are you trying to connect ? EU and UK should work.

**Comment by pshipton** [comment] 2024-09-27 11:22
We are in Canada.

**Comment by c-koell** [comment] 2024-09-29 16:55
@pshipton i have checked the geo blocking. You should be able to access the site now.

**Comment by pshipton** [comment] 2024-09-30 16:49
@TobiAjila pls take a look.

**Comment by tajila** [comment] 2024-09-30 19:08
Looking at the core, I can see that we do a decompile of all thread stacks due to a `SINGLE_STEP` event. Afterwards it looks like we attempt to call a method handle and fail in the `linkToVirtual` in the Interpreter. The cause for the crash is due to the memberName object being corrupt, instead of a memberName, its a user object `at/gv/tirol/csb/sap/elko/ejb/NeuePersonalMassnahmeIT`

**Comment by tajila** [comment] 2024-09-30 19:08
@hzongaro @nbhuiyan Can you please take a look?

**Comment by hzongaro** [comment] 2024-10-01 14:20
@jdmpapin, is there any chance this is another instance of the problem fixed by your pull request #20232?

**Comment by jdmpapin** [comment] 2024-10-01 14:28
I don't think so. `SINGLE_STEP` sounds like debug mode, i.e. FSD with pre-execution OSR, but argument stashing happens [only for post-execution OSR](https://github.com/eclipse-openj9/openj9/blob/b279a6d49ff88c01eaf98aa317adab11c93bd3d5/runtime/compiler/ilgen/Walker.cpp#L1585-L1589)

**Comment by c-koell** [comment] 2024-10-15 11:43
Recently i have got again a segmentation error with the latest version. I don't know if it is the same problem but i have attached the dmp file to our cloud storage (issue-20229-2.zip)
https://tbox.tirol.gv.at/index.php/s/4GrR9CpkZrawBaJ with "7RDEMYbTGt" as password.

**Comment by pshipton** [comment] 2024-10-22 18:59
The new dmp file shows a crash in the same place.
`[0xc]   j9vm29!VM_DebugBytecodeInterpreterCompressed::run+0x14a49   0xf58a77f240   0xf58a77f718   `

**Comment by jdmpapin** [comment] 2024-11-15 16:30
As a crash due to redefinition (IIUC) in debug mode, this might have been a dup of #19813

**Closed** 2024-11-15 16:33 UTC
Labels: comp:jit, userRaised
