### ISSUE TITLE
JDK16 Valhalla : ValueTypeTestsJIT_0_FAILED - Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#10365] opened 2020-08-11 12:48 UTC
Failure link
------------

From an internal build `Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/52`:
```
21:45:10  openjdk version "16-internal" 2021-03-16
21:45:10  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
21:45:10  Eclipse OpenJ9 VM (build master-d3ca26b528e, JRE 16 Linux amd64-64-Bit Compressed References 20200810_117 (JIT enabled, AOT enabled)
21:45:10  OpenJ9   - d3ca26b528e
21:45:10  OMR      - e27fe46829b
21:45:10  JCL      - 98badf86fb4 based on jdk-16+9)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
Handler1=00007F6A68E29A20 Handler2=00007F6A68705D90 InaccessibleAddress=00000000FFF700C0
RDI=0000000000000000 RSI=00000000FFE40128 RAX=00000000FFDCAA48 RBX=00000000FFDCAA48
RCX=00000000FFF79B00 RDX=00000000FFDCAA48 R8=00000000FFFFFFFF R9=000000000004A100
R10=0000000000000008 R11=00000000FFE40000 R12=00000000FFE40138 R13=00000000000000C6
R14=00000000FFE40138 R15=00000000FFE40128
RIP=00000000FFF700C0 GS=0000 FS=0000 RSP=000000000010C2C8
EFlags=0000000000010206 CS=0033 RBP=0000000000016700 ERR=0000000000000015
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFF700C0
xmm0 0000000048b8bfa0 (f: 1220067200.000000, d: 6.027933e-315)
xmm1 000000004804cc40 (f: 1208273920.000000, d: 5.969667e-315)
xmm2 0000000047a27333 (f: 1201828608.000000, d: 5.937823e-315)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
xmm5 000000003e6119bf (f: 1046550976.000000, d: 5.170649e-315)
xmm6 0000000048b8bfa0 (f: 1220067200.000000, d: 6.027933e-315)
xmm7 000000003dfab536 (f: 1039840576.000000, d: 5.137495e-315)
xmm8 ffdc5f3800000000 (f: 0.000000, d: -7.969384e+307)
xmm9 ffdc5f80ffdc5f68 (f: 4292632320.000000, d: -7.969697e+307)
xmm10 3f847ae147ae147b (f: 1202590848.000000, d: 1.000000e-02)
xmm11 00000000ffdc5ff8 (f: 4292632576.000000, d: 2.120842e-314)
xmm12 ffdc6040ffdc6028 (f: 4292632576.000000, d: -7.970520e+307)
xmm13 74757074756f5f74 (f: 1970233216.000000, d: 9.823958e+252)
xmm14 2f36373438303234 (f: 942682688.000000, d: 2.927521e-81)
xmm15 494a737473655465 (f: 1936020608.000000, d: 1.179754e+45)
Target=2_90_20200810_117 (Linux 4.4.0-174-generic)
CPU=amd64 (4 logical CPUs) (0xf6f3a000 RAM)
----------- Stack Backtrace -----------
(0x00007F6A68737362 [libj9prt29.so+0x4d362])
(0x00007F6A68706AF3 [libj9prt29.so+0x1caf3])
(0x00007F6A687373DE [libj9prt29.so+0x4d3de])
(0x00007F6A687374D4 [libj9prt29.so+0x4d4d4])
(0x00007F6A68706AF3 [libj9prt29.so+0x1caf3])
(0x00007F6A6873723B [libj9prt29.so+0x4d23b])
(0x00007F6A68E29564 [libj9vm29.so+0xa4564])
(0x00007F6A68706AF3 [libj9prt29.so+0x1caf3])
(0x00007F6A68E297D5 [libj9vm29.so+0xa47d5])
(0x00007F6A68E57475 [libj9vm29.so+0xd2475])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/08/10 18:47:35 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/core.20200810.184735.464.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.507.

JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/core.20200810.184735.464.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/javacore.20200810.184735.464.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/javacore.20200810.184735.464.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/Snap.20200810.184735.464.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/Snap.20200810.184735.464.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/jitdump.20200810.184735.464.0004.dmp' in response to an event
JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_15971104208476/ValueTypeTestsJIT_0/jitdump.20200810.184735.464.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".

ValueTypeTestsJIT_0_FAILED
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
21:47:40  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=Valhalla&JDK_IMPL=openj9&BUILD_LIST=functional/Valhalla,functional/cmdline_options_tester,functional/cmdLineTests/valuetypeddrtests&PLATFORM=x86-64_linux&TARGET=ValueTypeTestsJIT_0

**Comment by hzongaro** [comment] 2020-08-12 13:47
One thing to note is that the unhandled exception seems to occur after running the tests.  From the output in https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly/109/tapResults/:

```
...
PASSED: testGCFlattenedValueArrayWithLongAlignment
PASSED: testGCFlattenedValueArrayWithObjectAlignment
PASSED: testGCFlattenedValueArrayWithSingleAlignment
PASSED: testMultiDimentionalArrays
PASSED: testStaticFieldsWithLongAlignmenDefaultValues
PASSED: testStaticFieldsWithObjectAlignmenDefaultValues
PASSED: testStaticFieldsWithSingleAlignmenDefaultValues
PASSED: testACMPTestOnAssortedValues

===============================================
    ValueTypeTestsJIT
    Tests run: 71, Failures: 0, Skips: 0
===============================================


===============================================
Valhalla suite
Total tests run: 71, Failures: 0, Skips: 0
===============================================

Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
Handler1=00007F6A68E29A20 Handler2=00007F6A68705D90 InaccessibleAddress=00000000FFF700C0
RDI=0000000000000000 RSI=00000000FFE40128 RAX=00000000FFDCAA48 RBX=00000000FFDCAA48
RCX=00000000FFF79B00 RDX=00000000FFDCAA48 R8=00000000FFFFFFFF R9=000000000004A100
R10=0000000000000008 R11=00000000FFE40000 R12=00000000FFE40138 R13=00000000000000C6
R14=00000000FFE40138 R15=00000000FFE40128
RIP=00000000FFF700C0 GS=0000 FS=0000 RSP=000000000010C2C8
EFlags=0000000000010206 CS=0033 RBP=0000000000016700 ERR=0000000000000015
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFF700C0
...
```

**Comment by a7ehuo** [comment] 2020-09-09 19:58
I ran into this intermittent crash locally. Many thanks to @liqunl. She helped narrow down the crash to `"java/lang/AbstractStringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/AbstractStringBuilder;"` Some of her findings below. She might have more to add on the investigation of this issue.
- Didn't find the difference in the trace logs from this method between the passed case and the failed case
- This crash doesn't seem to happen after excluding this method and `java/lang/StringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/StringBuilder;` which inlines `AbstractStringBuilder.append`

```
===============================================
Valhalla suite
Total tests run: 99, Failures: 0, Skips: 0
===============================================

Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F30E18D6160 Handler2=00007F30E0E96FE0 InaccessibleAddress=00000003003E8310
RDI=0000000000000000 RSI=00000000FFE90248 RAX=00000000FFDE6A40 RBX=00000000FFDE6A40
RCX=00000000FFF35F00 RDX=00000000FFDE6A40 R8=00000000FFFFFFFF R9=000000000004C600
R10=0000000000000008 R11=00000000FFE90120 R12=00000000FFE90258 R13=00000000000000B4
R14=00000000FFE90258 R15=00000000FFE90248
RIP=00000003003E8310 GS=0000 FS=0000 RSP=000000000010F5C8
EFlags=0000000000010206 CS=0033 RBP=0000000000019A00 ERR=0000000000000014
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000003003E8310
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 0000000048b3b280 (f: 1219736192.000000, d: 6.026297e-315)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 bfdf6a9aeea7ec10 (f: 4003982336.000000, d: -4.908817e-01)
xmm4 3fbc5e53aa362eb4 (f: 2855677696.000000, d: 1.108143e-01)
xmm5 000000003d8e2170 (f: 1032724864.000000, d: 5.102339e-315)
xmm6 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
xmm7 000000004798b000 (f: 1201188864.000000, d: 5.934662e-315)
xmm8 0000000041400000 (f: 1094713344.000000, d: 5.408603e-315)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Target=2_90_20200908_000000 (Linux 4.15.0-46-generic)
CPU=amd64 (8 logical CPUs) (0x1f27da000 RAM)
----------- Stack Backtrace -----------
(0x00007F30E0E93A12 [libj9prt29.so+0x24a12])
(0x00007F30E0E97D43 [libj9prt29.so+0x28d43])
(0x00007F30E0E93A8E [libj9prt29.so+0x24a8e])
(0x00007F30E0E93B84 [libj9prt29.so+0x24b84])
(0x00007F30E0E97D43 [libj9prt29.so+0x28d43])
(0x00007F30E0E938EB [libj9prt29.so+0x248eb])
(0x00007F30E18D5CA4 [libj9vm29.so+0x34ca4])
(0x00007F30E0E97D43 [libj9prt29.so+0x28d43])
(0x00007F30E18D5F15 [libj9vm29.so+0x34f15])
(0x00007F30E1982255 [libj9vm29.so+0xe1255])
---------------------------------------

RSP=000000000010F5C8

(kca) what (0x000000000010F5C8)/20l
0x10f5c8: 0x00007f30c03b46c4 {java/lang/AbstractStringBuilder.append} +324
0x10f5d0: 0x0000002c8379f920 return FALSE;Unknown!
0x10f5d8: 0x00000000fff35d30 Obj - {org/testng/reporters/FileStringBuffer}
0x10f5e0: 0x0000000000000000 return FALSE;Unknown!
0x10f5e8: 0x0000000083615348 Obj - {java/lang/String} ""
0x10f5f0: 0x00000000fff35d30 Obj - {org/testng/reporters/FileStringBuffer}
0x10f5f8: 0x00000000ffe90248 Obj - {java/lang/String} "                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
0x10f600: 0x000000000004c600 J9Class - {java/lang/String}
0x10f608: 0x00000000ffe90248 Obj - {java/lang/String} "                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
0x10f610: 0x00000000ffde6a40 Ptr Obj - {java/lang/StringBuilder} +4 
0x10f618: 0x00007f30c03e1507 {org/testng/reporters/FileStringBuffer.append} +295
0x10f620: 0x00000000ffe90248 Obj - {java/lang/String} "                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
0x10f628: 0x00000000ffde6a40 Ptr Obj - {java/lang/StringBuilder} +4 
0x10f630: 0x00000000ffe90120 Obj - {[B}
0x10f638: 0x00000000fff35d30 Obj - {org/testng/reporters/FileStringBuffer}
0x10f640: 0x00000000ffe90248 Obj - {java/lang/String} "                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
0x10f648: 0x0000000083744d38 Obj - {java/lang/String} "testCreateAssortedRefWithLongAlignment"
0x10f650: 0x0000e45bffde66b0 return FALSE;Unknown!
0x10f658: 0x00000000ffde6a40 Ptr Obj - {java/lang/StringBuilder} +4 
0x10f660: 0x0000000000000000 return FALSE;Unknown!

(kca) m 0x00007f30c03b46c4
         Method Signature: {java/lang/AbstractStringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/AbstractStringBuilder;}
                 MetaData: 0x00007f30bd3ff0b8 (optLevel: cold)
               Frame Size: 72 bytes
                   Access: Public 
         J9Class/J9Method: 0x00000000000b8300 / 0x00000000000b6e20
               MethodInfo: 0x00007f30bc2b9da0
                 BodyInfo: 0x00007f30bc2b9e30 (Flags: UsesGCR)
Compiled Method Start/End: 0x00007f30c03b4544 / 0x00007f30c03b4822 (734 bytes)


=====================
 \\ java/lang/AbstractStringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/AbstractStringBuilder;
 \\   16 JBaload0 

0x7f30c03b46a8 00000128 [0x7f30bee7e450] 48 8b 54 24 58                     mov	rdx, qword ptr [rsp+0x58]		# L8RegMem, SymRef  this<'this' parm Ljava/lang/AbstractStringBuilder;>[#414  Parm +88] [flags 0xc0000107 0x0 ]
0x7f30c03b46ad 0000012d [0x7f30bee7e590] 48 8b c2                           mov	rax, rdx		# MOV8RegReg

 \\ java/lang/AbstractStringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/AbstractStringBuilder;
 \\   17 JBaload1 

0x7f30c03b46b0 00000130 [0x7f30bee7e730] 48 8b 74 24 50                     mov	rsi, qword ptr [rsp+0x50]		# L8RegMem, SymRef  s<parm 1 Ljava/lang/CharSequence;>[#415  Parm +80] [flags 0xc0000107 0x0 ]
0x7f30c03b46b5 00000135 [0x7f30bee7f6b0]                                    Label L0128:			# LABEL	# (Start of internal control flow)

 \\ java/lang/AbstractStringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/AbstractStringBuilder;
 \\   21 JBinvokevirtual 49 java/lang/AbstractStringBuilder.append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;

0x7f30c03b46b5 00000135 [0x7f30bee7ea70] 8b 0a                              mov	ecx, dword ptr [rdx]		# L4RegMem, SymRef  <vft-symbol>[#302  Shadow] [flags 0x18607 0x0 ]
0x7f30c03b46b7 00000137 [0x7f30bee7eb00] 48 81 e1 00 ff ff ff               and	rcx, 0xffffffffffffff00	# AND8RegImm4
0x7f30c03b46be 0000013e [0x7f30bee7ec20] ff 91 50 ff ff ff                  call	dword ptr [rcx-0xb0]		# CALLMem, SymRef [#417 -176]
0x7f30c03b46c4 00000144 [0x7f30bee7f9a0]                                    assocRegs                       # ASSOCREGS
0x7f30c03b46c4 00000144 [0x7f30bee7f750]                                    Label L0129:			# LABEL	# (End of internal control flow)
0x7f30c03b46c4 00000144 [0x7f30bee803d0]                                    assocRegs                       # ASSOCREGS
0x7f30c03b46c4 00000144 [0x7f30bee9e3a0] 4c 8b 4c 24 30                     mov	r9, qword ptr [rsp+0x30]		# L8RegMem, SymRef [#450 +48]
0x7f30c03b46c9 00000149 [0x7f30bee9e4c0] 48 8b 5c 24 28                     mov	rbx, qword ptr [rsp+0x28]		# L8RegMem, SymRef [#451 +40]
0x7f30c03b46ce 0000014e [0x7f30bee9e550] 48 83 c4 48                        add	rsp, 0x00000048	# ADD8RegImms
=====================


[rcx-0xb0] => RIP=00000003003E8310
(kca) what (0xFFF35E50)
0xfff35e50: 0x00000003003e8310 return FALSE;Unknown!

[rsp+0x58]  RSP=000000000010F5C8
(kca)  what (0x10F620)/10l
0x10f620: 0x00000000ffe90248 Obj - {java/lang/String} "                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
0x10f628: 0x00000000ffde6a40 Ptr Obj - {java/lang/StringBuilder} +4 
0x10f630: 0x00000000ffe90120 Obj - {[B}
0x10f638: 0x00000000fff35d30 Obj - {org/testng/reporters/FileStringBuffer}
0x10f640: 0x00000000ffe90248 Obj - {java/lang/String} "                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
0x10f648: 0x0000000083744d38 Obj - {java/lang/String} "testCreateAssortedRefWithLongAlignment"
0x10f650: 0x0000e45bffde66b0 return FALSE;Unknown!
0x10f658: 0x00000000ffde6a40 Ptr Obj - {java/lang/StringBuilder} +4 
0x10f660: 0x0000000000000000 return FALSE;Unknown!
0x10f668: 0x0000000000000000 return FALSE;Unknown!

>  !j9object 0x00000000ffe90248
J9VMJavaLangString at 0x00000000FFE90248 {
struct J9Class* clazz = !j9class 0x4C600 // java/lang/String
Object flags = 0x00000000;
[B value = !fj9object 0xffe90258 (offset = 0) (java/lang/String)
B coder = 0x00000001 (offset = 4) (java/lang/String)
I hashCode = 0x00000000 (offset = 8) (java/lang/String)
"                  <span class="method-name">testCreateAssortedRefWithLongAlignment</span>
"
}

> !j9object 0x00000000ffde6a40
Unable to read object clazz at 0x00000000FFDE6A40 (clazz = 0x00000000FFF35F00)
> 
```

**Comment by liqunl** [comment] 2020-09-11 13:48
The internal gc map at the call instruction has the stack map and mark the slot containing the object as live, but the final gc map doesn't have the stack map. Can't tell why we remove the stack map from the trace log, will add some traces to find out.

**Comment by JasonFengJ9** [comment] 2020-09-18 21:13
Another occurrence from last nightly build `Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/86`:
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
Handler1=00007F7ACB88BF30 Handler2=00007F7ACB161FD0 InaccessibleAddress=00000000FFF79B98
RDI=0000000000000000 RSI=00000000FFE80128 RAX=00000000FFE1B1A8 RBX=00000000FFE1B1A8
RCX=00000000FFF79B00 RDX=00000000FFE1B1A8 R8=00000000FFFFFFFF R9=000000000004A200
R10=00000000FFE80138 R11=0000000000000090 R12=00000000FFE80138 R13=0000000000000000
R14=0000000000000010 R15=0000000000000000
RIP=00000000FFF79B98 GS=0000 FS=0000 RSP=0000000000114358
EFlags=0000000000010206 CS=0033 RBP=0000000000016700 ERR=0000000000000015
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFF79B98
xmm0 00000000488e8400 (f: 1217299456.000000, d: 6.014258e-315)
xmm1 0000000047c96a00 (f: 1204382208.000000, d: 5.950439e-315)
xmm2 00000000479fd933 (f: 1201658112.000000, d: 5.936980e-315)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
xmm5 000000003e8f9114 (f: 1049596160.000000, d: 5.185694e-315)
xmm6 00000000488e8400 (f: 1217299456.000000, d: 6.014258e-315)
xmm7 00000000bde52e8f (f: 3185913600.000000, d: 1.574050e-314)
xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 3f847ae147ae147b (f: 1202590848.000000, d: 1.000000e-02)
xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 00780075006e0069 (f: 7209065.000000, d: 2.136230e-306)
xmm14 00650067002e002a (f: 3014698.000000, d: 9.346010e-307)
xmm15 006c0061002d0063 (f: 2949219.000000, d: 1.246107e-306)
Target=2_90_20200917_153 (Linux 4.4.0-189-generic)
CPU=amd64 (4 logical CPUs) (0xf6f34000 RAM)
----------- Stack Backtrace -----------
(0x00007F7ACB195012 [libj9prt29.so+0x58012])
(0x00007F7ACB162D33 [libj9prt29.so+0x25d33])
(0x00007F7ACB19508E [libj9prt29.so+0x5808e])
(0x00007F7ACB195184 [libj9prt29.so+0x58184])
(0x00007F7ACB162D33 [libj9prt29.so+0x25d33])
(0x00007F7ACB194EEB [libj9prt29.so+0x57eeb])
(0x00007F7ACB88BA74 [libj9vm29.so+0xa4a74])
(0x00007F7ACB162D33 [libj9prt29.so+0x25d33])
(0x00007F7ACB88BCE5 [libj9vm29.so+0xa4ce5])
(0x00007F7ACB8B9B95 [libj9vm29.so+0xd2b95])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/09/17 21:17:33 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/core.20200917.211733.24263.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.24332.

JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/core.20200917.211733.24263.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/javacore.20200917.211733.24263.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/javacore.20200917.211733.24263.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/Snap.20200917.211733.24263.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/Snap.20200917.211733.24263.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/jitdump.20200917.211733.24263.0004.dmp' in response to an event
JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/openjdk-tests/TKG/test_output_16004026204586/ValueTypeTestsJIT_0/jitdump.20200917.211733.24263.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".

ValueTypeTestsJIT_0_FAILED
```

**Comment by a7ehuo** [comment] 2020-10-26 18:51
I could still reproduce this crash with the fix from #10976. 

- Not able to reproduce the crash when limiting the compilation only to the 2 previously suspected methods [1].
- However it still seems related to `AbstractStringBuilder.append` based on the backtrace from one of the crashes [2]. I'm trying to reproduce it with trace logs to get more information. 
- The crash is also reproducible after adding `disableMergeStackMaps`. 

[1]
```
java/lang/StringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/StringBuilder;
java/lang/AbstractStringBuilder.append(Ljava/lang/CharSequence;)Ljava/lang/AbstractStringBuilder; 
```

[2]
```
(gdb) bt
#0  0x00000000ffe00080 in ?? ()
#1  0x00007ff68a753b56 in ?? ()
#2  0x0000001a837cc640 in ?? ()
#3  0x00000000ffe05db0 in ?? ()
#4  0x0000000000000000 in ?? ()

(kca) what (0x00000000ffe05db0)
0xffe05db0: 0x0000000000361e10  (0000000000361e00) J9Class - {org/testng/reporters/FileStringBuffer}
(kca) what 0x0000001a837cc640
return FALSE;Unknown!
(kca) what 0x00007ff68a753b56
{java/lang/AbstractStringBuilder.append} +374
(kca) what (0x00000000ffe00080)
0xffe00080: 0x00000000003e4830  (00000000003e4800) J9Class - {org/testng/reporters/jq/Model}
```

**Comment by Leonardo2718** [comment] 2021-02-25 16:33
#11968 has been merged now so we should keep an eye on this job to see if it continues to fail.

**Comment by theresa-m** [comment] 2024-10-10 18:42
@hzongaro can this issue be closed?

**Comment by hzongaro** [comment] 2024-10-11 13:49
> can this issue be closed?

I _guess_ we're safe after three-and-a-half years. . . .  Closing.

**Closed by hzongaro** 2024-10-11 13:49 UTC
Labels: comp:jit, project:valhalla, test failure
