### ISSUE TITLE
OpenJ9-17 reports IllegalAccessError, but other versions perform normally

### ISSUE THREAD

**Issue by TheSail28** [eclipse-openj9/openj9#18611] opened 2023-12-13 11:36 UTC
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Java -version output

```
openjdk version "1.8.0_382"
IBM Semeru Runtime Open Edition (build 1.8.0_382-b05)
Eclipse OpenJ9 VM (build openj9-0.40.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230810_729 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - c4d2c2bafb based on jdk8u382-b05)
```

```
openjdk version "11.0.20.1" 2023-08-24
IBM Semeru Runtime Open Edition 11.0.20.1 (build 11.0.20.1+1)
Eclipse OpenJ9 VM 11.0.20.1 (build openj9-0.40.0, JRE 11 Linux amd64-64-Bit Compressed References 20230824_836 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - 0880e8df04 based on jdk-11.0.20.1+1)
```

```
openjdk version "17.0.8.1" 2023-08-24
IBM Semeru Runtime Open Edition 17.0.8.1 (build 17.0.8.1+1)
Eclipse OpenJ9 VM 17.0.8.1 (build openj9-0.40.0, JRE 17 Linux amd64-64-Bit Compressed References 20230824_549 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - 8ecf238a124 based on jdk-17.0.8.1+1)
```

## Reproduce

```
jdk_linux_8_openj9/bin/java -cp ./ ysoserial.payloads.CommonsBeanutils3

jdk_linux_11_openj9/bin/java -cp ./ ysoserial.payloads.CommonsBeanutils3

jdk_linux_17_openj9/bin/java -cp ./ ysoserial.payloads.CommonsBeanutils3
```

Expected Result

```
---------------jdk_linux_8_openj9---------------
nothing
---------------jdk_linux_11_openj9---------------
nothing
---------------jdk_linux_17_openj9---------------
nothing
```

Actual Result

```
---------------jdk_linux_8_openj9---------------
nothing
---------------jdk_linux_11_openj9---------------
nothing
---------------jdk_linux_17_openj9---------------
Exception in thread "main" java.lang.IllegalAccessError: class ysoserial.payloads.CommonsBeanutils3 (in unnamed module @0x7fab5ad6) cannot access class com.sun.rowset.JdbcRowSetImpl (in module java.sql.rowset) because module java.sql.rowset does not export com.sun.rowset to unnamed module @0x7fab5ad6
	at ysoserial.payloads.CommonsBeanutils3.getObject(Unknown Source)
	at ysoserial.payloads.util.PayloadRunner$1.call(Unknown Source)
	at ysoserial.payloads.util.PayloadRunner$1.call(Unknown Source)
	at ysoserial.ExecBlockingSecurityManager.wrap(Unknown Source)
	at ysoserial.payloads.util.PayloadRunner.run(Unknown Source)
	at ysoserial.payloads.CommonsBeanutils3.main(Unknown Source)
```

## Problem summary

This issue is similar to the previously submitted #18608 , but behaves differently. #18608 behaved as `BUG! UNCAUGHT EXCEPTION`, but this issue reports `IllegalAccessError`. we can't confirm if this is the result of the same root cause or not!

## Attachment

[testcase4.zip](https://github.com/eclipse-openj9/openj9/files/13660177/testcase4.zip)

**Comment by pshipton** [comment] 2023-12-13 14:32
Hotspot has the same behavior.

**Comment by pshipton** [comment] 2023-12-17 16:25
This one is caused by [Strongly Encapsulate JDK Internals](https://openjdk.org/jeps/403)

Access to internals should be fixed. Internals are subject to change without notice. There are options to expose internals, the testcase passes with `--add-exports java.sql.rowset/com.sun.rowset=ALL-UNNAMED`

**Closed by pshipton** 2023-12-17 16:25 UTC
Labels: userRaised
