### ISSUE TITLE
jdk20 OpenjDK java/lang/Thread/jni/AttachCurrentThread/AttachTest NullPointerException Cannot invoke "java.lang.invoke.MethodHandle.type()" because "target" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16656] opened 2023-02-02 19:11 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_aarch64_linux_OpenJDK20/1
Most platforms, not platform specific. Didn't fail on Windows, AIX.
jdk_lang
java/lang/Thread/jni/AttachCurrentThread/AttachTest.java
```
10:29:53  Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.type()" because "target" is null
10:29:53  	at java.base/java.lang.invoke.MethodHandles.insertArgumentsChecks(MethodHandles.java:5218)
10:29:53  	at java.base/java.lang.invoke.MethodHandles.insertArguments(MethodHandles.java:5187)
10:29:53  	at java.base/jdk.internal.foreign.abi.SharedUtils.maybeInsertAllocator(SharedUtils.java:292)
10:29:53  	at java.base/jdk.internal.foreign.abi.AbstractLinker.lambda$downcallHandle$0(AbstractLinker.java:72)
10:29:53  	at java.base/jdk.internal.foreign.abi.SoftReferenceCache$Node.get(SoftReferenceCache.java:52)
10:29:53  	at java.base/jdk.internal.foreign.abi.SoftReferenceCache.get(SoftReferenceCache.java:38)
10:29:53  	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle(AbstractLinker.java:68)
10:29:53  	at java.base/java.lang.foreign.Linker.downcallHandle(Linker.java:213)
10:29:53  	at ImplicitAttach.main(ImplicitAttach.java:67)
```

**Comment by pshipton** [comment] 2023-02-02 19:14
@tajila fyi

**Comment by babsingh** [comment] 2023-02-07 22:49
[jdk/internal/foreign/abi/AbstractLinker.java#L71-L72](https://github.com/ibmruntimes/openj9-openjdk-jdk20/blob/1f8c85a0f8c6174040d230eca033750142400b96/src/java.base/share/classes/jdk/internal/foreign/abi/AbstractLinker.java#L71-L72)

```
AbstractLinker.downcallHandle(...) {
            MethodHandle handle = arrangeDowncall(type, fd, linkRequest.options());
            handle = SharedUtils.maybeInsertAllocator(fd, handle);
            return handle;
```

The `MethodHandle` generated by `arrangeDowncall` is `NULL`. The `NULL` `MethodHandle` is passed from `AbstractLinker.lambda$downcallHandle$0` to `MethodHandles.insertArgumentsChecks`.

This failure is due to missing features for Foreign Function & Memory API (Second Preview): https://openjdk.org/jeps/434.

Related: https://github.com/eclipse-openj9/openj9/issues/16329.

++@ChengJin01 to confirm the above details and decide if the test should be disabled since FFI specific code has been temporarily disabled in JDK20, ref: https://github.com/eclipse-openj9/openj9/issues/16329#issuecomment-1398698205?

**Comment by ChengJin01** [comment] 2023-02-07 22:54
@babsingh, the test suite should be excluded given all FFI related code are disabled in JDK20 for the moment and not yet updated against the latest APIs in which case we have been working on.

**Comment by ChengJin01** [comment] 2023-02-08 15:32
@pshipton, given we have https://github.com/eclipse-openj9/openj9/issues/16565 opened to keep track of all excluded FFI jtreg test suites, can we close this issue as this failing test suite was excluded via https://github.com/adoptium/aqa-tests/pull/4318?

**Comment by babsingh** [comment] 2023-02-08 20:27
> can we close this issue as a duplicate?

@ChengJin01 Yes. In https://github.com/adoptium/aqa-tests/pull/4318, the test is currently disabled by referring to this issue (#16656). Before closing this issue as a duplicate of #16565, we will have to disable the test by referring to #16565.

**Comment by ChengJin01** [comment] 2023-02-08 22:08
PR is created at https://github.com/adoptium/aqa-tests/pull/4324 to replace #16656 with #16565.

**Comment by ChengJin01** [comment] 2023-02-10 17:42
https://github.com/adoptium/aqa-tests/pull/4324 was merged.

**Closed** 2023-02-10 17:47 UTC
Labels: comp:vm, project:panama, test failure, jdk20
