### ISSUE TITLE
JDK8 testServerComesUpAfterClient - Expected an exit value of 0 or 143, got 1 instead

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#10920] opened 2020-10-18 15:40 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/138/tapResults/
To rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
00:24:55  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=testJITServer_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
FAILED: testServerComesUpAfterClient
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerComesUpAfterClient(JITServerTest.java:340)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    JITServerTest
    Tests run: 6, Failures: 1, Skips: 0
===============================================
```

This is similar with https://github.com/eclipse/openj9/issues/10359 (closed with code change) instead of https://github.com/eclipse/openj9/issues/10622.

**Comment by pshipton** [comment] 2020-10-21 01:26
@mpirvu

**Comment by dmitry-ten** [comment] 2021-07-19 20:36
@mpirvu this is another duplicate of `testJITServer` failures. Since we closed all others, this one should be closed as well.

**Comment by mpirvu** [comment] 2021-07-21 11:34
Closing based on the comment above. We haven't seen such a failure in a long while.

**Closed by mpirvu** 2021-07-21 11:34 UTC
Labels: comp:jitserver, test failure
