### ISSUE TITLE
"CASE".toUpperCase() != "CASE" occurs in JDK8 and JDK11 when the balanced gcpolicy is not used

### ISSUE THREAD

**Issue by BurryPotter** [eclipse-openj9/openj9#17433] opened 2023-05-18 13:30 UTC
Java -version output
--------------------

> openjdk8/jdk8u362-b09_openj9/bin/java -version
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b09)
Eclipse OpenJ9 VM (build openj9-0.36.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230206_588 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - eebde685ec based on jdk8u362-b09)

> openjdk11/jdk-11.0.18+10_openj9/bin/java -version
openjdk version "11.0.18" 2023-01-17
IBM Semeru Runtime Open Edition 11.0.18.0 (build 11.0.18+10)
Eclipse OpenJ9 VM 11.0.18.0 (build openj9-0.36.1, JRE 11 Linux amd64-64-Bit Compressed References 20230214_644 (JIT enabled, AOT enabled)
OpenJ9   - 0592661e4
OMR      - f491bbf6f
JCL      - 4e060ceb0b based on jdk-11.0.18+10)

Summary of problem
------------------

The toUpperCase/toLowerCase function of a string will return the original string when the string is all uppercase/lowercase letters. That is, `"CASE".toUpperCase() != "CASE"` should return false. But when I execute this code multiple times,  the program keeps executing correctly, only when using balanced gcpolicy in JDK8 & JDK11. It is suspect that the GC behavior of the program at runtime caused the string reference to change, because using more memory will trigger this problem earlier.

P.S. I can reproduce it on Linux but not Windows.

Reproduce Steps
----------------

1. Copy the source code
```
class Case {
    public static void main(String[] var0) throws Exception {
        int[][] arr = new int[1024][1024];
        if ("CASE".toUpperCase() != "CASE") {
            throw new RuntimeException("\"CASE\".toUpperCase() != \"CASE\"");
        } else {
            main(new String[256]);
        }
    }
}
```
2. Run this case with following command

JDK8 with optavgpause 
```
openjdk8/jdk8u362-b09_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:optavgpause Case
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
        at Case.main(Case.java:6)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        ...
```
JDK8 with gencon 
```
openjdk8/jdk8u362-b09_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:gencon Case
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
        at Case.main(Case.java:6)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        ...
``` 
JDK8 with optavgpause 
```
openjdk8/jdk8u362-b09_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:optavgpause Case
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
        at Case.main(Case.java:6)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        ...
```
JDK8 with balanced 
```
openjdk8/jdk8u362-b09_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:balanced Case
<execute long time>
```
JDK11 with optthruput 
```
openjdk11/jdk-11.0.18+10_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:optthruput Case
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
        at Case.main(Case.java:6)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        ...
```
JDK11 with optavgpause
```
openjdk11/jdk-11.0.18+10_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:optavgpause Case
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
        at Case.main(Case.java:6)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        ...
```
JDK11 with gencon 
```
openjdk11/jdk-11.0.18+10_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:gencon Case
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
        at Case.main(Case.java:6)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        at Case.main(Case.java:8)
        ...
```
JDK11 with balanced 
```
openjdk11/jdk-11.0.18+10_openj9/bin/java -Xms512m -Xmx512m -Xgcpolicy:balanced Case
<execute long time>
```

**Comment by dmitripivkine** [comment] 2023-05-18 16:24
The problem exist with `nogc` GC policy (no GC executed at all, just need larger heap to reach failure point). So, it is unrelated with GC behaviour:
```
java -Xgcpolicy:nogc -Xmx25g -Xms25g Case.java
Exception in thread "main" java.lang.RuntimeException: "CASE".toUpperCase() != "CASE"
	at Case.main(Case.java:5)
	at Case.main(Case.java:7)
	at Case.main(Case.java:7)
	at Case.main(Case.java:7)
	at Case.main(Case.java:7)
	at Case.main(Case.java:7)
	at Case.main(Case.java:7)
	at Case.main(Case.java:7)
```
Also interesting the problem seems reproducible with Java 8 and Java 11 but not with Java 17 and up.

@0xdaryl Would you please comment from JIT point of view?
@tajila FYI

**Comment by 0xdaryl** [comment] 2023-05-19 02:14
The problem seems to be in the `java/lang/String.toUpperCase(Ljava/util/Locale;)Ljava/lang/String;` method and can be reproduced with:
```
java -Xnoaot -Xms512m -Xmx512m '-Xjit:limit={*String.toUpperCase(Ljava/*},tracefull,log=lll,lastOptIndex=2' Case
```
The optimizer doesn't do anything with this method and the only interesting thing that happens on failure is an inline transformation of `com/ibm/jit/JITHelpers.toUpperIntrinsicUTF16([C[CI)Z` by the codegen.

This transformation won't happen with balanced which probably explains why that using that GC policy avoids this problem.

Since the finger is pointing at the backend, @BradleyWood please take a look.

**Comment by BradleyWood** [comment] 2023-05-19 03:30
I don't think is a bug. The spec doesn't require String.toUpperCase() to return the same instance, and comparing objects with '==' or '!=' only compares refernces. As for @0xdaryl's comment, inlining `com/ibm/jit/JITHelpers.toUpperIntrinsicUTF16([C[CI)Z` requires a new instance to be created.

In this case, a new array is allocated for the destination buffer which is passed to `com/ibm/jit/JITHelpers.toUpperIntrinsicUTF16([C[CI)Z`. Then a new string object is allocated and initialized using that buffer.

```
n60n      BBStart <block_10>                                                                  
n68n      treetop                                                                             
n67n        newarray  jitNewArray[#102  helper Method] [flags 0x400 0x0 ]                     
n65n          ishl                                                                            
n62n            iload  sLength<auto slot 3>[#424  Auto] [flags 0x3 0x0 ]                      
n64n            iloadi  java/lang/String.coder B[#432  final Shadow +8] [flags 0xa0601 0x0 ]  
n63n              aload  this<'this' parm Ljava/lang/String;>[#417  Parm] [flags 0x40000107 0x0
n66n          iconst 8   ; array type is byte                                                 
n69n      astore  output<auto slot 5>[#433  Auto] [flags 0x7 0x0 ]                            
n67n        ==>newarray
n74n      compressedRefs                                                                      
n72n        aloadi  java/lang/String.value [B[#434  final Shadow +4] [flags 0x400a0607 0x0 ]  
n71n          aload  this<'this' parm Ljava/lang/String;>[#417  Parm] [flags 0x40000107 0x0 ] (
n73n        lconst 0                                                                          
n80n      NULLCHK on n70n [#32]                                                               
n79n        icall  com/ibm/jit/JITHelpers.toUpperIntrinsicUTF16([B[BI)Z[#439  final virtual Met
n70n          aload  java/lang/String.helpers Lcom/ibm/jit/JITHelpers;[#425  final Static] (obj
n72n          ==>aload
n75n          aload  output<auto slot 5>[#433  Auto] [flags 0x7 0x0 ]                         
n78n          imul                                                                            
n76n            iload  sLength<auto slot 3>[#424  Auto] [flags 0x3 0x0 ]                      
n77n            iconst 2                                                                    
n84n      ificmpeq --> block_12 BBStart at n14n ()                                            
n79n        ==>icall
n81n        iconst 0                                                                          
n59n      BBEnd </block_10> =====                                                             
n83n      BBStart <block_11>                                                                  
n96n      treetop                                                                             
n95n        new  jitNewObject[#91  helper Method] [flags 0x400 0x0 ]                          
n94n          loadaddr  java/lang/String[# 444  Static] [flags 0x18307 0x0 ]                   
n100n     NULLCHK on n95n [#32]                                                               
n99n        call  java/lang/String.<init>([BB)V[#448  final special Method] [flags 0x20500 0x0]
n95n          ==>new
n97n          aload  output<auto slot 5>[#433  Auto] [flags 0x7 0x0 ]                         
n98n          iconst 1                                                                        
n101n     areturn                                                                             
n95n        ==>new
n82n      BBEnd </block_11> =====                                    
```

**Comment by 0xdaryl** [comment] 2023-05-23 13:32
From the analysis above, the test is relying on un-speced behaviour.  It does demonstrate a future enhancement to a backend optimization under `String.toUpperCase()` to not return a new string when the original is unchanged, but a test case cannot rely on that happening.

Thanks for reporting this behaviour, but I will close this now.

**Closed by 0xdaryl** 2023-05-23 13:32 UTC
Labels: comp:jit, userRaised
