### ISSUE TITLE
SSL routines errors

### ISSUE THREAD

**Issue by trourance** [eclipse-openj9/openj9#9132] opened 2020-04-06 14:59 UTC
Hi,

We are randomly facing the two following issues with the PotgreSQL JDBC driver using SSL.

`org.postgresql.util.PSQLException: SSL error: point has incorrect order`
and
` org.postgresql.util.PSQLException: SSL error: Received fatal alert: bad_record_mac`

This is the java version used by the driver.
```
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit Compressed References 20191016_358 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```

**Comment by pshipton** [comment] 2020-04-06 15:32
@ashbm5 fyi

@trourance can you please try the testcase with `-Djdk.nativeCrypto=false` to see if it does resolve the problem. Note this will affect performance. If this option does resolve it, there are other more specific options that can be tried as well, see https://www.eclipse.org/openj9/docs/djdknativecrypto/

**Comment by trourance** [comment] 2020-04-07 09:06
The issue here is that it looks random for me, but probably it's not. I would like to be able to reproduce it in order to know if the parameter `-Djdk.nativeCrypto=false` fixes it.

**Comment by pshipton** [comment] 2020-04-07 14:48
This is very unlikely to be resolved for the 0.20.0 release which occurs next week, moving to the next milestone.

**Comment by trourance** [comment] 2020-04-14 07:26
I've tried the parameter `-Djdk.nativeCrypto=false` and it fixes the issue. 
Most probably this could be changed to `-Djdk.nativeGCM=false` as the client uses the following algorithm to establish the connection `tls=TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384/ECDH=prime256v1`

**Comment by DanHeidinga** [comment] 2020-06-17 15:14
Moving this forward but it needs to be looked at for the 0.22 release.

**Comment by pshipton** [comment] 2020-06-17 15:15
@ashbm5 can someone take a look at this. We've had to move it forward to the next milestone again.

**Comment by ashbm5** [comment] 2020-06-17 16:14
@pshipton we have no way to reproduce right now this error. if we can get a full stacktrace of the error or a java dump file that would help.

**Comment by pshipton** [comment] 2020-06-17 17:37
@ashbm5 why are you asking me.
@trourance is there any more information you can provide as per https://github.com/eclipse/openj9/issues/9132#issuecomment-645471725 to help track down the problem?

**Comment by trourance** [comment] 2020-06-29 07:20
I was finally able to reproduce one of them and I've printed the full stack trace.

```
Server: Caused by: org.postgresql.util.PSQLException: SSL error: point has incorrect order
Server: 	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:64)
Server: 	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:361)
Server: 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:148)
Server: 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
Server: 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
Server: 	at org.postgresql.Driver.makeConnection(Driver.java:404)
Server: 	at org.postgresql.Driver.connect(Driver.java:272)
Server: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
Server: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
Server: 	at com.mirth.connect.server.userutil.DatabaseConnection.<init>(DatabaseConnection.java:65)
Server: 	at com.mirth.connect.server.userutil.DatabaseConnectionFactory.createDatabaseConnection(DatabaseConnectionFactory.java:62)
Server: 	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
Server: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Server: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Server: 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
Server: 	... 15 more
Server: Caused by: javax.net.ssl.SSLException: point has incorrect order
Server: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
Server: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
Server: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
Server: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
Server: 	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1313)
Server: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
Server: 	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:59)
Server: 	... 29 more
Server: Caused by: java.security.ProviderException: point has incorrect order
Server: 	at jdk.crypto.ec/sun.security.ec.ECDHKeyAgreement.validate(ECDHKeyAgreement.java:157)
Server: 	at jdk.crypto.ec/sun.security.ec.ECDHKeyAgreement.deriveKeyImpl(ECDHKeyAgreement.java:222)
Server: 	at jdk.crypto.ec/sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:169)
Server: 	at jdk.crypto.ec/sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:201)
Server: 	at java.base/javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:660)
Server: 	at java.base/sun.security.ssl.ECDHKeyExchange$ECDHEKAKeyDerivation.t12DeriveKey(ECDHKeyExchange.java:430)
Server: 	at java.base/sun.security.ssl.ECDHKeyExchange$ECDHEKAKeyDerivation.deriveKey(ECDHKeyExchange.java:417)
Server: 	at java.base/sun.security.ssl.ECDHClientKeyExchange$ECDHEClientKeyExchangeProducer.produce(ECDHClientKeyExchange.java:415)
Server: 	at java.base/sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(ClientKeyExchange.java:65)
Server: 	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
Server: 	at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)
Server: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
Server: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
Server: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
Server: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
Server: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
Server: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
Server: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
Server: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
Server: 	... 30 more
```

HTH

**Comment by DanHeidinga** [comment] 2020-09-02 15:10
Moving forward as this won't close in the next few days to make 0.22

**Comment by tajila** [comment] 2020-12-02 16:33
@ashbm5 Any update on this?

**Comment by pshipton** [comment] 2020-12-11 04:16
I assume nothing is going to happen for 0.24, or probably ever without more information. Moving this forward again.

**Comment by trourance** [comment] 2021-01-26 16:39
@pshipton What more information do you need ? I've provided the full stacktrace that has been requested.

**Comment by pshipton** [comment] 2021-01-26 16:46
@ashbm5 pls see the previous comment.

**Comment by ashbm5** [comment] 2021-01-27 13:50
@trourance I would need a test case that duplicates this issue.

**Comment by ashbm5** [comment] 2021-03-17 19:05
the stack trace above shows the failure coming from ECDH code which does not use OpenSSL so I don't know how the disable native crypto flag is helping.

There is a similar error here at https://support.oracle.com/knowledge/Oracle%20Database%20Products/2738433_1.html

I would speculate its an application error so perhaps try to upgrade your database version. At this point, it looks like this error is not related to OpenSSL use as per stacktrace

To help further I would need a simple test case that will reproduce this issue. 

@pshipton please move this issue to the next milestone.

**Comment by ashbm5** [comment] 2021-12-14 15:27
@trourance 

some further comments on this issue: The error "point has incorrect order" thrown during the KeyExchange stage of the TLS handshake likely indicates something is wrong with your server certificate.

This error was thrown during the validation of the public key which is done as part of the TLS handshake key material derivation.

FYI @pshipton

**Comment by pshipton** [comment] 2022-02-10 19:30
Doesn't seem anything further to do here, closing.

**Closed by pshipton** 2022-02-10 19:30 UTC
Labels: userRaised, comp:openssl
