### ISSUE TITLE
OpenJDK java/lang/invoke/LFCaching/LFSingleThreadCachingTest 1 of 1989 test cases FAILED

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17312] opened 2023-05-01 13:11 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_Nightly/46/
jdk_lang_j9_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs`
java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java

Actual failed test is not included in the output due to Output overflow.
```
23:52:34  STDOUT:
23:52:34  -Dseed=306289303208519990
23:52:34  -DtestLimit=2000
23:52:34  Number of iterations according to -DtestLimit is 117 (1989 cases)
23:52:34  Number of iterations is set to 117 (1989 cases)
23:52:34  STDERR:
...
23:52:34  java.lang.Error: 1 of 1989 test cases FAILED! 
23:52:34  Rerun the test with the same "-Dseed=" option as in the log file!
```

### TODO before closing the issue

Revert the below test changes for supported JDKs:
- JDK17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/217;
- JDK20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/46; and
- JDK-next: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/607.

**Comment by pshipton** [comment] 2023-05-10 15:47
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_Nightly/52/'
jdk_lang_j9_0
java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java
```
22:41:25  Tested LF caching feature with MethodHandles.
22:41:25  
22:41:25  ...
22:41:25  Output overflow:
22:41:25  JT Harness has limited the test output to the text
22:41:25  at the beginning and the end, so that you can see how the
22:41:25  test began, and how it completed.
22:41:25  
22:41:25  If you need to see more of the output from the test,
22:41:25  set the system property javatest.maxOutputSize to a higher
22:41:25  value. The current value is 100000
22:41:25  ...
22:41:25  
22:41:25  84:I,a185:I,a186:I,a187:I,a188:I,a189:I,a190:I,a191:I,a192:I,a193:I,a194:I,a195:I,a196:I,a197:I,a198:I,a199:I,a200:I,a201:I,a202:I,a203:I,a204:I,a205:I,a206:I,a207:I,a208:I,a209:I,a210:I,a211:I,a212:I,a213:I,a214:I,a215:I,a216:I,a217:I,a218:I,a219:I,a220:I,a221:I,a222:I,a223:I,a224:I,a225:I,a226:I)=>{
22:41:25      t227:J=BoundMethodHandle$Species_J.argJ0(a0:L);t227:J}
22:41:25  Lambda form 1 toString is:
22:41:25  invoke=Lambda(a0:L/SpeciesData[J => BoundMethodHandle$Species_J],a1:D,a2:I,a3:I,a4:I,a5:I,a6:I,a7:I,a8:I,a9:I,a10:F,a11:I,a12:I,a13:I,a14:I,a15:F,a16:I,a17:I,a18:D,a19:I,a20:I,a21:L,a22:I,a23:F,a24:D,a25:F,a26:I,a27:I,a28:D,a29:I,a30:I,a31:I,a32:I,a33:I,a34:I,a35:L,a36:D,a37:I,a38:I,a39:F,a40:F,a41:I,a42:J,a43:L,a44:J,a45:F,a46:I,a47:I,a48:J,a49:I,a50:I,a51:D,a52:I,a53:I,a54:I,a55:I,a56:I,a57:I,a58:L,a59:L,a60:I,a61:L,a62:F,a63:F,a64:D,a65:L,a66:I,a67:I,a68:I,a69:L,a70:I,a71:I,a72:I,a73:I,a74:I,a75:I,a76:I,a77:D,a78:I,a79:I,a80:L,a81:I,a82:J,a83:I,a84:J,a85:I,a86:F,a87:F,a88:I,a89:I,a90:J,a91:I,a92:L,a93:F,a94:L,a95:I,a96:I,a97:I,a98:I,a99:I,a100:D,a101:L,a102:I,a103:I,a104:I,a105:D,a106:I,a107:I,a108:F,a109:I,a110:L,a111:L,a112:J,a113:I,a114:J,a115:D,a116:I,a117:F,a118:J,a119:L,a120:F,a121:L,a122:I,a123:F,a124:I,a125:D,a126:L,a127:I,a128:I,a129:I,a130:I,a131:I,a132:D,a133:F,a134:F,a135:D,a136:I,a137:I,a138:I,a139:I,a140:I,a141:D,a142:I,a143:I,a144:I,a145:D,a146:I,a147:I,a148:I,a149:I,a150:F,a151:I,a152:L,a153:F,a154:I,a155:D,a156:F,a157:D,a158:F,a159:I,a160:I,a161:I,a162:I,a163:I,a164:I,a165:I,a166:I,a167:I,a168:I,a169:I,a170:I,a171:I,a172:I,a173:I,a174:I,a175:I,a176:I,a177:I,a178:I,a179:I,a180:I,a181:I,a182:I,a183:I,a184:I,a185:I,a186:I,a187:I,a188:I,a189:I,a190:I,a191:I,a192:I,a193:I,a194:I,a195:I,a196:I,a197:I,a198:I,a199:I,a200:I,a201:I,a202:I,a203:I,a204:I,a205:I,a206:I,a207:I,a208:I,a209:I,a210:I,a211:I,a212:I,a213:I,a214:I,a215:I,a216:I,a217:I,a218:I,a219:I,a220:I,a221:I,a222:I,a223:I,a224:I,a225:I,a226:I)=>{
22:41:25      t227:J=BoundMethodHandle$Species_J.argJ0(a0:L);t227:J}
22:41:25  java.lang.AssertionError: Error: Lambda forms of the two method handles are not the same. LF cahing does not work
22:41:25  	at LFCachingTestCase.checkLFCaching(LFCachingTestCase.java:72)
22:41:25  	at LFSingleThreadCachingTest.doTest(LFSingleThreadCachingTest.java:72)
22:41:25  	at jdk.test.lib.Utils.filterException(Utils.java:641)
22:41:25  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
22:41:25  	at LambdaFormTestCase$TestRun.doIteration(LambdaFormTestCase.java:127)
22:41:25  	at jdk.test.lib.TimeLimitedRunner.call(TimeLimitedRunner.java:71)
22:41:25  	at LambdaFormTestCase.runTests(LambdaFormTestCase.java:188)
22:41:25  	at LFSingleThreadCachingTest.main(LFSingleThreadCachingTest.java:81)
22:41:25  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
22:41:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
22:41:25  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
22:41:25  	at java.base/java.lang.Thread.run(Thread.java:1639)
22:41:25  FAILED. Caused by Error: Lambda forms of the two method handles are not the same. LF cahing does not work
```

**Comment by pshipton** [comment] 2023-05-10 15:48
@tajila fyi

**Comment by tajila** [comment] 2023-05-10 17:14
@babsingh Please take a look

**Comment by babsingh** [comment] 2023-05-12 17:53
Ran multiple grinders across the two failing platforms (Win and pLinux):
- 100x Win: https://openj9-jenkins.osuosl.org/job/Grinder/2337/ (ran on the same machine where the previous failure was seen) 
- 100x pLinux: https://openj9-jenkins.osuosl.org/job/Grinder/2336/ (ran on the same machine where the previous failure was seen)
- 200x Win: https://openj9-jenkins.osuosl.org/job/Grinder/2335/

Unable to reproduce the failure locally or in a grinder. Had also run other grinders; but only noticed infra issues in them.

**Comment by babsingh** [comment] 2023-05-12 18:18
LambdaForm (LF) caching is implemented on the Java/JCL side in the `java.lang.invoke` package. No OpenJ9 VM support exists for LF caching.

We will need a system core file when the failure happens again. We can add `-Xdump:system:events=catch,filter=*AssertionError*` to the `@run ...` section in [LFSingleThreadCachingTest](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/b174079f728a9ea761e23a56a9cfba25ac06170b/test/jdk/java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java#LL39C26-L39C47); this will generate the system core file when the failure re-occurs; but the test can't be run with the RI since `-Xdump` is not available in the RI. @pshipton Shall we take this approach?

**Comment by pshipton** [comment] 2023-05-12 18:23
We can try.

**Comment by pshipton** [comment] 2023-05-12 18:25
You should confirm the dump will occur, given the default options for jdk_lang_j9 are `-Xdump:system:none  -Xdump:system:events=gpf+abort+traceassert+corruptcache`.

**Comment by babsingh** [comment] 2023-05-12 19:54
> You should confirm the dump will occur, given the default options for jdk_lang_j9 are `-Xdump:system:none -Xdump:system:events=gpf+abort+traceassert+corruptcache`.

Confirmed that the core files generate using this approach. The options from `@run` are appended at the end. Created https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/46 to update the `@run` section.

**Comment by JasonFengJ9** [comment] 2023-05-26 15:27
[JDK17 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_0/302/)(`win10x64vs6`)
```
[2023-05-26T01:18:49.851Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
[2023-05-26T01:18:50.697Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 

[2023-05-26T01:22:06.381Z] TEST: java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java

[2023-05-26T01:22:06.419Z] java.lang.AssertionError: Error: Lambda forms of the two method handles are not the same. LF cahing does not work
[2023-05-26T01:22:06.419Z] 	at LFCachingTestCase.checkLFCaching(LFCachingTestCase.java:72)
[2023-05-26T01:22:06.419Z] 	at LFSingleThreadCachingTest.doTest(LFSingleThreadCachingTest.java:72)
[2023-05-26T01:22:06.419Z] 	at jdk.test.lib.Utils.filterException(Utils.java:624)
[2023-05-26T01:22:06.419Z] 	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
[2023-05-26T01:22:06.419Z] 	at LambdaFormTestCase$TestRun.doIteration(LambdaFormTestCase.java:127)
[2023-05-26T01:22:06.419Z] 	at jdk.test.lib.TimeLimitedRunner.call(TimeLimitedRunner.java:71)
[2023-05-26T01:22:06.419Z] 	at LambdaFormTestCase.runTests(LambdaFormTestCase.java:188)
[2023-05-26T01:22:06.419Z] 	at LFSingleThreadCachingTest.main(LFSingleThreadCachingTest.java:81)
[2023-05-26T01:22:06.419Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-05-26T01:22:06.419Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-05-26T01:22:06.419Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-05-26T01:22:06.419Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-05-26T01:22:06.419Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-05-26T01:22:06.419Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-05-26T01:22:06.419Z] FAILED. Caused by Error: Lambda forms of the two method handles are not the same. LF cahing does not work

[2023-05-26T01:22:06.425Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Error: 1 of 1989 test cases FAILED! Rerun the test with the same "-Dseed=" option as in the log file!
[2023-05-26T01:22:06.425Z] --------------------------------------------------
[2023-05-26T01:31:00.719Z] Test results: passed: 809; failed: 1
[2023-05-26T01:31:10.954Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_16850632053978\jdk_lang_j9_0\report\html\report.html
[2023-05-26T01:31:10.954Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_16850632053978\jdk_lang_j9_0\work
[2023-05-26T01:31:10.954Z] Error: Some tests failed or other problems occurred.
[2023-05-26T01:31:11.367Z] -----------------------------------
[2023-05-26T01:31:11.367Z] jdk_lang_j9_0_FAILED
```

**Comment by babsingh** [comment] 2023-05-26 16:08
https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/46 was only applied to JDK20. The most recent failure happened on JDK17.

Started a 500x grinder on the failing machine with `-Xdump:system+java:events=catch,filter=java/lang/AssertionError`: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33091/. Will start a 1000x grinder if the failure is still irreproducible.

**Comment by babsingh** [comment] 2023-05-30 13:19
No failures seen in the 500x grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33091/.

Started a 100x grinder across 5 different machines: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33124/.

**Comment by pshipton** [comment] 2023-06-01 20:35
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/67

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk20_j9_sanity.openjdk_s390x_linux_Nightly/67/openjdk_test_output.tar.gz

**Comment by babsingh** [comment] 2023-06-02 16:33
Reverting the extension repo changes for core file generation since the failure can easily be reproduced locally, and this will save memory on the Artifactory.

**Comment by pshipton** [comment] 2023-06-05 13:28
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/497

**Comment by dmitripivkine** [comment] 2023-06-07 15:40
- In Balanced, Soft Ref can be collected during PGC (in Copy Forward)
- `GarbageCollectorMXBean::getCollectionCount` is incremented by triggering of `J9HOOK_MM_OMR_GLOBAL_GC_END` or `J9HOOK_MM_OMR_LOCAL_GC_END` hooks
- I can not see gc end hook triggering at the end of PGC
I guess it means Soft Ref can be cleared but `noGCHappened()` still return `true` and test fail.

Investigating the location of the problem:
- should PGC trigger `J9HOOK_MM_OMR_LOCAL_GC_END`?
- should `GarbageCollectorMXBean::getCollectionCount` be incremented by some other hook?
- is it legitimate for the test use this logic?

@babsingh @pshipton  Does this test fail with Balanced only? Is theory above explains all failures?

**Comment by pshipton** [comment] 2023-06-07 15:46
I only see failures with balanced recorded in this issue.

**Comment by babsingh** [comment] 2023-06-07 17:16
@dmitripivkine The failure is very intermittent, and I haven't thoroughly tried to reproduce the failure with other GC policies. So, I don't know if the failure is reproducible with other GC policies.

**Comment by pshipton** [comment] 2023-06-15 17:30
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/492
jdk_lang_j9_0

**Comment by pshipton** [comment] 2023-06-22 17:25
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_ppc64le_linux_OMR/28/
jdk_lang_j9_0

**Comment by pshipton** [comment] 2023-06-30 14:07
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_0/1
jdk_lang_j9_0

**Comment by JasonFengJ9** [comment] 2023-07-05 20:47
[JDK20 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_testList_0/53/)
```
openjdk version "20.0.1-beta" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9-202307011503 (build 20.0.1-beta+9-202307011503)
Eclipse OpenJ9 VM 20.0.1+9-202307011503 (build master-7c0f636b3, JRE 20 AIX ppc64-64-Bit Compressed References 20230701_61 (JIT enabled, AOT enabled)
OpenJ9   - 7c0f636b3
OMR      - 6b5f1b79b
JCL      - 47ad18f4c based on jdk-20.0.1+9)

[2023-07-01T20:11:49.560Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
[2023-07-01T20:11:49.560Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 

[2023-07-01T20:23:12.442Z] java.lang.Error: 1 of 1989 test cases FAILED! 
[2023-07-01T20:23:12.442Z] Rerun the test with the same "-Dseed=" option as in the log file!
[2023-07-01T20:23:12.442Z] 	at LambdaFormTestCase.runTests(LambdaFormTestCase.java:194)
[2023-07-01T20:23:12.442Z] 	at LFSingleThreadCachingTest.main(LFSingleThreadCachingTest.java:81)
[2023-07-01T20:23:12.442Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2023-07-01T20:23:12.442Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[2023-07-01T20:23:12.442Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
[2023-07-01T20:23:12.442Z] 	at java.base/java.lang.Thread.run(Thread.java:1639)
[2023-07-01T20:23:12.442Z] 
[2023-07-01T20:23:12.442Z] JavaTest Message: Test threw exception: java.lang.Error: 1 of 1989 test cases FAILED! 

[2023-07-01T20:23:12.443Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Error: 1 of 1989 test cases FAILED! Rerun the test with the same "-Dseed=" option as in the log file!
[2023-07-01T20:23:12.443Z] --------------------------------------------------
[2023-07-01T20:57:49.567Z] Test results: passed: 859; failed: 1
[2023-07-01T20:57:55.627Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_16882397913619/jdk_lang_j9_0/report/html/report.html
[2023-07-01T20:57:55.627Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_sanity.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_16882397913619/jdk_lang_j9_0/work
[2023-07-01T20:57:55.627Z] Error: Some tests failed or other problems occurred.
[2023-07-01T20:57:55.627Z] -----------------------------------
[2023-07-01T20:57:55.627Z] jdk_lang_j9_0_FAILED
```

**Comment by pshipton** [comment] 2023-07-06 21:13
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OMR_testList_0/1

**Comment by pshipton** [comment] 2023-07-06 21:35
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.openjdk_x86-64_windows_OMR_testList_0/3
jdk_lang_j9_0
java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java
```
08:43:20  Tested LF caching feature with MethodHandles.filterReturnValue method.
08:43:20  Lambda form 0 toString is:
08:43:20  invoke=Lambda(a0:L/SpeciesData[IL => BoundMethodHandle$Species_IL],a1:J,a2:I,a3:I,a4:I,a5:I,a6:I,a7:L,a8:I,a9:I,a10:L,a11:D,a12:L,a13:L,a14:D,a15:J,a16:D,a17:I,a18:I,a19:I,a20:I,a21:I,a22:I,a23:I,a24:J,a25:D,a26:I,a27:I,a28:D,a29:I,a30:I,a31:I,a32:I,a33:D,a34:F,a35:I,a36:F,a37:I,a38:J,a39:I,a40:L,a41:I,a42:F,a43:J,a44:L,a45:L,a46:L,a47:I,a48:D,a49:I,a50:I,a51:I,a52:J,a53:I,a54:I,a55:I,a56:D,a57:I,a58:I,a59:I,a60:I,a61:I,a62:I,a63:L,a64:I,a65:L,a66:I,a67:J,a68:D,a69:I,a70:I,a71:I,a72:I,a73:L,a74:D,a75:J,a76:I,a77:I,a78:I,a79:L,a80:F,a81:F,a82:I,a83:I,a84:I,a85:I,a86:F,a87:I,a88:I,a89:L,a90:I,a91:D,a92:L,a93:I,a94:L,a95:F,a96:L,a97:I,a98:F,a99:I,a100:I,a101:D,a102:D,a103:I,a104:I,a105:F,a106:I,a107:I,a108:I,a109:L,a110:I,a111:I,a112:J,a113:I,a114:I,a115:F,a116:J,a117:I,a118:I,a119:F,a120:F,a121:I,a122:D,a123:F,a124:I,a125:L,a126:D,a127:L,a128:L,a129:L,a130:L,a131:L,a132:L,a133:L,a134:L,a135:L,a136:L,a137:L,a138:L,a139:L,a140:L,a141:L,a142:L,a143:L,a144:L,a145:L,a146:L,a147:L,a148:L,a149:L,a150:L,a151:L,a152:L,a153:L,a154:L,a155:L,a156:L,a157:L,a158:L,a159:L,a160:L,a161:L)=>{
08:43:20      t162:I=BoundMethodHandle$Species_IL.argI0(a0:L);
08:43:20      t163:L=BoundMethodHandle$Species_IL.argL1(a0:L);
08:43:20      t164:I=MethodHandle.invokeBasic(t163:L,t162:I);t164:I}
08:43:20  Lambda form 1 toString is:
08:43:20  invoke=Lambda(a0:L/SpeciesData[IL => BoundMethodHandle$Species_IL],a1:J,a2:I,a3:I,a4:I,a5:I,a6:I,a7:L,a8:I,a9:I,a10:L,a11:D,a12:L,a13:L,a14:D,a15:J,a16:D,a17:I,a18:I,a19:I,a20:I,a21:I,a22:I,a23:I,a24:J,a25:D,a26:I,a27:I,a28:D,a29:I,a30:I,a31:I,a32:I,a33:D,a34:F,a35:I,a36:F,a37:I,a38:J,a39:I,a40:L,a41:I,a42:F,a43:J,a44:L,a45:L,a46:L,a47:I,a48:D,a49:I,a50:I,a51:I,a52:J,a53:I,a54:I,a55:I,a56:D,a57:I,a58:I,a59:I,a60:I,a61:I,a62:I,a63:L,a64:I,a65:L,a66:I,a67:J,a68:D,a69:I,a70:I,a71:I,a72:I,a73:L,a74:D,a75:J,a76:I,a77:I,a78:I,a79:L,a80:F,a81:F,a82:I,a83:I,a84:I,a85:I,a86:F,a87:I,a88:I,a89:L,a90:I,a91:D,a92:L,a93:I,a94:L,a95:F,a96:L,a97:I,a98:F,a99:I,a100:I,a101:D,a102:D,a103:I,a104:I,a105:F,a106:I,a107:I,a108:I,a109:L,a110:I,a111:I,a112:J,a113:I,a114:I,a115:F,a116:J,a117:I,a118:I,a119:F,a120:F,a121:I,a122:D,a123:F,a124:I,a125:L,a126:D,a127:L,a128:L,a129:L,a130:L,a131:L,a132:L,a133:L,a134:L,a135:L,a136:L,a137:L,a138:L,a139:L,a140:L,a141:L,a142:L,a143:L,a144:L,a145:L,a146:L,a147:L,a148:L,a149:L,a150:L,a151:L,a152:L,a153:L,a154:L,a155:L,a156:L,a157:L,a158:L,a159:L,a160:L,a161:L)=>{
08:43:20      t162:I=BoundMethodHandle$Species_IL.argI0(a0:L);
08:43:20      t163:L=BoundMethodHandle$Species_IL.argL1(a0:L);
08:43:20      t164:I=MethodHandle.invokeBasic(t163:L,t162:I);t164:I}
08:43:20  java.lang.AssertionError: Error: Lambda forms of the two method handles are not the same. LF cahing does not work
08:43:20  	at LFCachingTestCase.checkLFCaching(LFCachingTestCase.java:72)
```

**Comment by dmitripivkine** [comment] 2023-07-17 19:43
> * In Balanced, Soft Ref can be collected during PGC (in Copy Forward)
> * `GarbageCollectorMXBean::getCollectionCount` is incremented by triggering of `J9HOOK_MM_OMR_GLOBAL_GC_END` or `J9HOOK_MM_OMR_LOCAL_GC_END` hooks
> * I can not see gc end hook triggering at the end of PGC
>   I guess it means Soft Ref can be cleared but `noGCHappened()` still return `true` and test fail.
> 
> Investigating the location of the problem:
> 
> * should PGC trigger `J9HOOK_MM_OMR_LOCAL_GC_END`?
> * should `GarbageCollectorMXBean::getCollectionCount` be incremented by some other hook?
> * is it legitimate for the test use this logic?
> 

We have looked to the code again. There is a reporting for end of PGC and GGC increments, so my statement was not correct. There are a few hypothetical possibilities to get GC count wrong but none of them should be intermittent. So, at the moment I have no explanation for the failure from GC point of view.

@babsingh Is it possible to get more from system core trying to investigate caching state? There are two different objects indeed but I don't know where to look at.

**Comment by babsingh** [comment] 2023-07-18 22:02
> @babsingh Is it possible to get more from system core trying to investigate caching state? There are two different objects indeed but I don't know where to look at.

The test is comparing two instances of `LambdaForm` (`lambdaForm0` vs `lambdaForm1`): [LFCachingTestCase.java#L58-L59](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/d5def33610286e9199b030631cd767687874fdd1/test/jdk/java/lang/invoke/LFCaching/LFCachingTestCase.java#L58-L59).

Test method, [LFCachingTestCase.checkLFCaching](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/d5def33610286e9199b030631cd767687874fdd1/test/jdk/java/lang/invoke/LFCaching/LFCachingTestCase.java#L51), takes two input arguments (`adapter1` vs `adapter2`), which are instances of `MethodHandle`.

The `LambdaForm` instance is a field named `form` within `MethodHandle`. The test code retrieves the `LambdaForm` for a `MethodHandle` by invoking the [MethodHandle.internalForm](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/737f940cd67989a5eeb8dcb79c94a1d2d7266b27/src/java.base/share/classes/java/lang/invoke/MethodHandle.java#L1749) method.

### jdmpview cmds and output

```
> !threads

	!stack 0x7f82c0637b00	!j9vmthread 0x7f82c0637b00	!j9thread 0x7f82c0633960	tid 0x227d0 (141264) // (MainThread)

> !stack 0x7f82c0637b00

<7f82c0637b00> 	                        known but unhandled frame type com.ibm.j9ddr.vm29.pointer.U8Pointer @ 0x00000005

 FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT  FAULT

<7f82c0637b00> 	!j9method 0x00007F82C067B6E0   LFCachingTestCase.checkLFCaching(Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodHandle;)V
<7f82c0637b00> 	!j9method 0x00007F82C067BC38   LFSingleThreadCachingTest.doTest()V
<7f82c0637b00> 	!j9method 0x00007F8230107458   LambdaFormTestCase$TestRun$$Lambda/0x000000009cd9d7d8.run()V
...

> !stackslots 0x7f82c0637b00
<7f82c0637b00> JIT frame: bp = 0x00007F8230009F68, pc = 0x00007F829FD786BD, unwindSP = 0x00007F8230009EB0, cp = 0x00007F82C067B9E0, arg0EA = 0x00007F8230009F80, jitInfo = 0x00007F829D807478
<7f82c0637b00> 	Method: LFCachingTestCase.checkLFCaching(Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodHandle;)V !j9method 0x00007F82C067B6E0
<7f82c0637b00> 	Bytecode index = 121, inlineDepth = 0, PC offset = 0x0000000000000B75
<7f82c0637b00> 	stackMap=0x00007F829D807DD1, slots=I16(0x0003) parmBaseOffset=I16(0x0008), parmSlots=U16(0x0003), localBaseOffset=I16(0xFF88)
<7f82c0637b00> 	Described JIT args starting at 0x00007F8230009F70 for U16(0x0003) slots
<7f82c0637b00> 		O-Slot: : a2[0x00007F8230009F70] = 0x00007F82BE967658 <--- adapter1
<7f82c0637b00> 		O-Slot: : a1[0x00007F8230009F78] = 0x00007F82BE9F4818 <--- adapter2
<7f82c0637b00> 		O-Slot: : a0[0x00007F8230009F80] = 0x00007F82BECFC708
... 

> !j9object 0x00007F82BE967658 <--- adapter1
!J9Object 0x00007F82BE967658 {
	struct J9Class* clazz = !j9class 0x7F8231905700 // java/lang/invoke/BoundMethodHandle$Species_LLFFIJJJIIFIFJLI
	Object flags = 0x00000000;
	Ljava/lang/invoke/MethodType; type = !fj9object 0x7f82be9d3c48 (offset = 0) (java/lang/invoke/MethodHandle)
	<--- lambdaForm0 --->	
	Ljava/lang/invoke/LambdaForm; form = !fj9object 0x7f82be9675c8 (offset = 8) (java/lang/invoke/MethodHandle)
	...

> !j9object 0x00007F82BE9F4818 <--- adapter2
!J9Object 0x00007F82BE9F4818 {
	struct J9Class* clazz = !j9class 0x7F8231905700 // java/lang/invoke/BoundMethodHandle$Species_LLFFIJJJIIFIFJLI
	Object flags = 0x00000000;
	Ljava/lang/invoke/MethodType; type = !fj9object 0x7f82be9d3c48 (offset = 0) (java/lang/invoke/MethodHandle)
	<--- lambdaForm1 --->
	Ljava/lang/invoke/LambdaForm; form = !fj9object 0x7f82be9f43a8 (offset = 8) (java/lang/invoke/MethodHandle)
	...

// The test compares the references of lambdaForm0 (0x7f82be9675c8) and lambdaForm1 (0x7f82be9f43a8).
// The test expects lambdaForm0 and lambdaForm1 to have the same reference if no GC occurred.
```

@dmitripivkine I have annotated the DDR output above. Please let me know if more details are required.

**Comment by dmitripivkine** [comment] 2023-07-19 13:17
@babsingh Thank you! Yes, there is about the point I have reached myself too, I found these objects. I am wondering about missed cache details if we can get any. Is there any other (than have Soft Reference collected) reason to loose cache? We should separate somehow possibilities of unreliable GC count from any other possible reasons.
Also if we can get GC verbose log for this test we can see is there any Soft Reference processed (if none, there is not a reason).

**Comment by babsingh** [comment] 2023-07-19 13:45
> cache details ... Is there any other (than have Soft Reference collected) reason to loose cache?

Yes, LambdaForms as well as MethodHandles are cached. The corresponding SoftReferences are manged in MethodTypeForm. Please see the below links for more details.

- [MethodTypeForm.java#L53-L94)
](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/737f940cd67989a5eeb8dcb79c94a1d2d7266b27/src/java.base/share/classes/java/lang/invoke/MethodTypeForm.java#L53-L94)
- [MethodTypeForm.java#L112-L146](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/737f940cd67989a5eeb8dcb79c94a1d2d7266b27/src/java.base/share/classes/java/lang/invoke/MethodTypeForm.java#L112-L146)

**Comment by babsingh** [comment] 2023-07-19 13:54
> Also if we can get GC verbose log for this test we can see is there any Soft Reference processed (if none, there is not a reason).

https://ibm.box.com/shared/static/e98p1z9558lcw0a1evy9d958nvqv2ne3.zip: includes the system cores, java cores and verbose GC log.

**Comment by dmitripivkine** [comment] 2023-07-31 20:05
There is a bug in GC code: GC cycle state `OMR_GC_CYCLE_TYPE_VLHGC_GLOBAL_MARK_PHASE` used by Balanced for taxation based GMP is missed in the switch in `j9gc_get_collector_id()`. As a result this function returns 0 which is treated in `managementGC()` as non-STW event and `gcEndEvent()` (where GC count should be incremented) never called.
We know last GC cycle before test failure was GMP increment and there were a few Soft References cleared there. So, GC counter has not been incremented in GMP but Soft Reference has been cleared. This is a reason for test failure.

**Comment by babsingh** [comment] 2023-08-03 02:01
> Would you please confirm?

Yes, confirming that the issue is fixed by https://github.com/eclipse-openj9/openj9/pull/17891. Ran the test 250 times locally with the instructions from https://github.com/eclipse-openj9/openj9/issues/17312#issuecomment-1574011587; and the failure was not seen.

**Closed by babsingh** 2023-08-03 02:01 UTC
Labels: comp:gc, test failure, jdk-head, project:MH, jdk17, jdk20, jdk21
