### ISSUE TITLE
AWTError: Can't connect to X11 window server using 'unix:0'

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#14943] opened 2022-04-20 14:41 UTC
Failure link
------------
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_Personal_testList_0/82

Optional info
-------------

- intermittent failure (yes): 
- regression or new test:  N/A

Occurs periodically on AIX AOT tests; see https://github.com/eclipse-openj9/openj9/pull/14894#issuecomment-1103043451. This error has been happening for a while; opening this issue to give reviewers something to refer to in order to justify merging PRs where this error shows up in PR builds.

Failure output (captured from console output)
---------------------------------------------
```
[2022-04-20T00:28:59.944Z]  [OUT] fontmanger LIB: libfontmanager.so
[2022-04-20T00:28:59.944Z]  [ERR] Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'unix:0' as the value of the DISPLAY variable.
[2022-04-20T00:28:59.944Z]  [ERR] 	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
[2022-04-20T00:28:59.944Z]  [ERR] 	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
[2022-04-20T00:28:59.944Z]  [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
```

**Comment by pshipton** [comment] 2022-04-20 16:29
@AdamBrousseau

**Comment by pshipton** [comment] 2022-05-26 15:52
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/279/ - [p8-java1-ibm08](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm08)
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.functional_ppc64_aix_Nightly_testList_0/74/  - [p8-java1-ibm12](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm12)

**Comment by AdamBrousseau** [comment] 2022-06-08 02:46
Number 8 appears to have X11 installed correctly.

**Comment by pshipton** [comment] 2022-08-30 18:26
Try more grinders https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1260/

**Comment by pshipton** [comment] 2022-08-30 18:40
> Number 8 appears to have X11 installed correctly.

Perhaps having X11 installed correctly isn't the problem. Is it running?

**Comment by pshipton** [comment] 2022-08-31 21:29
@llxia can someone take a look at this pls.

**Comment by llxia** [comment] 2022-09-01 18:08
Sure, we will look into this.

**Comment by llxia** [comment] 2022-09-07 15:00
I can only reproduce this issue when setting iterations as we repeatedly start an X server within each iteration. So far, I am not able to reproduce the error when repeatedly triggering new jobs on the same machine.

- ITERATIONS=5: [Grinder/27199/](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27199/)
1st iteration passed and the rest failed as expected error - `Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'unix:0' as the value of the DISPLAY variable.`
- same Grinder job with ITERATIONS=1 right after and it passed: [Grinder/27200](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27200/)

I will move x11 cmd out of the loop. I suspect that we do not need `nohup` in the cmd.

**Comment by llxia** [comment] 2022-09-12 16:58
PR is delivered. Close this issue. Please reopen if the problem still occurs.

**Closed by llxia** 2022-09-12 16:58 UTC
Labels: test failure, comp:infra, os:aix

**Comment by pshipton** [comment] 2026-05-12 13:41
https://github.com/eclipse-openj9/openj9/pull/23879 excludes libpathTestRtf on AIX.
