### ISSUE TITLE
jdk_vector_0_FAILED jdk/incubator/vector/Long64VectorLoadStoreTests.java - Segmentation error vmState=0x00000000 - Object neither in heap nor stack-allocated in thread MainThread

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14215] opened 2022-01-06 14:16 UTC
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/37/`(`ubu20le-rt1-3`):
```
java version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1.0 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0 (build openj9-0.29.1, JRE 17 Linux ppc64le-64-Bit Compressed References 20211220_63 (JIT enabled, AOT enabled)
OpenJ9   - 7d055dfcb
OMR      - e30892e2b
JCL      - 233aee461cd based on jdk-17.0.1+12)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_vector_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F63%2Fibm-semeru-certified-jdk_ppc64le_linux_17.0.1.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F63%2Fibm-semeru-certified-debugimage_ppc64le_linux_17.0.1.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-ppc64le-openj9-IBM%2F63%2Fibm-semeru-certified-testimage_ppc64le_linux_17.0.1.0.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=v0.29.1-release&amp;OPENJ9_BRANCH=v0.29.1-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.29.1-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=3&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-12-21T07:38:10.768Z] variation: Mode150
[2021-12-21T07:38:10.768Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-12-21T08:15:23.614Z] --------------------------------------------------
[2021-12-21T09:41:58.921Z] TEST: jdk/incubator/vector/Long64VectorLoadStoreTests.java

[2021-12-21T09:41:58.923Z] STDERR:
[2021-12-21T09:41:58.923Z] WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
[2021-12-21T09:41:58.923Z] Unhandled exception
[2021-12-21T09:41:58.923Z] Type=Segmentation error vmState=0x00000000
[2021-12-21T09:41:58.923Z] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2021-12-21T09:41:58.923Z] Handler1=00007F200F7C54D0 Handler2=00007F200F6FC300
[2021-12-21T09:41:58.923Z] R0=0000000000000000 R1=00007F1FEE6EA070 R2=00000000E01E4580 R3=00000000FFFFFFF8
[2021-12-21T09:41:58.923Z] R4=00000000FFFFDDB8 R5=000000000000000E R6=00000000E01AE198 R7=00007F1FEF310038
[2021-12-21T09:41:58.923Z] R8=00000000FFFFDDB8 R9=000000000000000E R10=00007F1FEF913B94 R11=000000000028C038
[2021-12-21T09:41:58.923Z] R12=0000000084004844 R13=00007F1FEE6F68F0 R14=000000000028FB00 R15=0000000000239400
[2021-12-21T09:41:58.923Z] R16=00007F1FEF310038 R17=00000000E01AE198 R18=00000000E01B2A20 R19=0000000000000000
[2021-12-21T09:41:58.923Z] R20=00000000FFFFDDB8 R21=0000000000000008 R22=00000000FFFFD108 R23=0000000000000C30
[2021-12-21T09:41:58.923Z] R24=0000000000000448 R25=00000000E01E4580 R26=00000000E004D538 R27=0000000000000448
[2021-12-21T09:41:58.923Z] R28=00000000FFFFD108 R29=0000000000000448 R30=0000000000000C29 R31=0000000000000448
[2021-12-21T09:41:58.923Z] NIP=00007F1FEF913D24 MSR=800000000280F033 ORIG_GPR3=C0000000000027E0 CTR=00007F1FEF913B94
[2021-12-21T09:41:58.923Z] LINK=00007F1FEF913D3C XER=0000000020000000 CCR=0000000088004824 SOFTE=0000000000000001
[2021-12-21T09:41:58.923Z] TRAP=0000000000000300 DAR=0000000100000008 dsisr=0000000042000000 RESULT=0000000000000000
[2021-12-21T09:41:58.923Z] FPR0 000000000028fb10 (f: 2685712.000000, d: 1.326918e-317)
[2021-12-21T09:41:58.923Z] FPR1 404f577300000000 (f: 0.000000, d: 6.268320e+01)
[2021-12-21T09:41:58.923Z] FPR2 3fd5df1100000000 (f: 0.000000, d: 3.417399e-01)
[2021-12-21T09:41:58.923Z] FPR3 3fee666660000000 (f: 1610612736.000000, d: 9.500000e-01)
[2021-12-21T09:41:58.923Z] FPR4 4000cb0b40000000 (f: 1073741824.000000, d: 2.099143e+00)
[2021-12-21T09:41:58.923Z] FPR5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
[2021-12-21T09:41:58.923Z] FPR7 bfd57bf7808caade (f: 2156702464.000000, d: -3.356913e-01)
[2021-12-21T09:41:58.923Z] FPR8 002000720065006b (f: 6619243.000000, d: 4.450632e-308)
[2021-12-21T09:41:58.923Z] FPR9 0034003000360036 (f: 3538998.000000, d: 1.112578e-307)
[2021-12-21T09:41:58.923Z] FPR10 0038003400370031 (f: 3604529.000000, d: 1.335088e-307)
[2021-12-21T09:41:58.923Z] FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR12 40d1758000000000 (f: 0.000000, d: 1.787800e+04)
[2021-12-21T09:41:58.923Z] FPR13 4020800000000000 (f: 0.000000, d: 8.250000e+00)
[2021-12-21T09:41:58.923Z] FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2021-12-21T09:41:58.923Z] 
[2021-12-21T09:41:58.923Z] Compiled_method=Long64VectorLoadStoreTests.loadByteArrayIOOBE(Ljava/util/function/IntFunction;Ljava/util/function/IntFunction;)V
[2021-12-21T09:41:58.923Z] Target=2_90_20211220_63 (Linux 5.4.0-89-generic)
[2021-12-21T09:41:58.923Z] CPU=ppc64le (4 logical CPUs) (0x1fd030000 RAM)
[2021-12-21T09:41:58.923Z] ----------- Stack Backtrace -----------
[2021-12-21T09:41:58.923Z] (0x00007F1FEF913D24 [<unknown>+0x0])
[2021-12-21T09:41:58.923Z] (0x00007F200F79EED0 [libj9vm29.so+0x1eed0])
[2021-12-21T09:41:58.923Z] (0x00007F200F7A0368 [libj9vm29.so+0x20368])
[2021-12-21T09:41:58.923Z] (0x00007F200DBB6764 [libjclse29.so+0x86764])
[2021-12-21T09:41:58.923Z] JVM_InvokeMethod+0x40 (0x00007F200FE674C0 [libjvm.so+0x274c0])
[2021-12-21T09:41:58.923Z] JVM_InvokeMethod+0x34 (0x00007F20106B6814 [libjvm.so+0x6814])
[2021-12-21T09:41:58.923Z] Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00007F1FEEF4C5B4 [libjava.so+0xc5b4])
[2021-12-21T09:41:58.923Z] (0x00007F1FEF57D824 [<unknown>+0x0])
[2021-12-21T09:41:58.923Z] (0x00007F200F79EED0 [libj9vm29.so+0x1eed0])
[2021-12-21T09:41:58.923Z] (0x00007F200F7A0368 [libj9vm29.so+0x20368])
[2021-12-21T09:41:58.923Z] (0x00007F200DBB6764 [libjclse29.so+0x86764])
[2021-12-21T09:41:58.923Z] JVM_InvokeMethod+0x40 (0x00007F200FE674C0 [libjvm.so+0x274c0])
[2021-12-21T09:41:58.923Z] JVM_InvokeMethod+0x34 (0x00007F20106B6814 [libjvm.so+0x6814])
[2021-12-21T09:41:58.923Z] Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00007F1FEEF4C5B4 [libjava.so+0xc5b4])
[2021-12-21T09:41:58.923Z] (0x00007F1FEF57D824 [<unknown>+0x0])
[2021-12-21T09:41:58.923Z] (0x00007F200F799650 [libj9vm29.so+0x19650])
[2021-12-21T09:41:58.923Z] (0x00007F200F835370 [libj9vm29.so+0xb5370])
[2021-12-21T09:41:58.923Z] (0x00007F200F6FD708 [libj9prt29.so+0x3d708])
[2021-12-21T09:41:58.923Z] (0x00007F200F830524 [libj9vm29.so+0xb0524])
[2021-12-21T09:41:58.923Z] (0x00007F200F6913E8 [libj9thr29.so+0x113e8])
[2021-12-21T09:41:58.923Z] (0x00007F2010969818 [libpthread.so.0+0x9818])
[2021-12-21T09:41:58.923Z] clone+0x74 (0x00007F201083EB24 [libc.so.6+0x14eb24])
[2021-12-21T09:41:58.923Z] ---------------------------------------
[2021-12-21T09:41:58.923Z] JVMDUMP039I Processing dump event "gpf", detail "" at 2021/12/21 01:41:28 - please wait.
[2021-12-21T09:41:58.923Z] JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/core.20211221.014128.4170217.0001.dmp' in response to an event
[2021-12-21T09:41:58.923Z] JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/core.20211221.014128.4170217.0001.dmp
[2021-12-21T09:41:58.923Z] JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/javacore.20211221.014128.4170217.0002.txt' in response to an event
[2021-12-21T09:41:58.923Z] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/javacore.20211221.014128.4170217.0002.txt
[2021-12-21T09:41:58.923Z] 0000000000239400: Object neither in heap nor stack-allocated in thread MainThread
[2021-12-21T09:41:58.923Z] 0000000000239400:	O-Slot=000000000028FC08
[2021-12-21T09:41:58.923Z] 0000000000239400:	O-Slot value=000000000033A580
[2021-12-21T09:41:58.923Z] 0000000000239400:	PC=00007F1FEF913D24
[2021-12-21T09:41:58.923Z] 0000000000239400:	framesWalked=1
[2021-12-21T09:41:58.923Z] 0000000000239400:	arg0EA=000000000028FC28
[2021-12-21T09:41:58.923Z] 0000000000239400:	walkSP=000000000028FAD8
[2021-12-21T09:41:58.923Z] 0000000000239400:	literals=0000000000000000
[2021-12-21T09:41:58.923Z] 0000000000239400:	jitInfo=00007F1FEF470078
[2021-12-21T09:41:58.923Z] 0000000000239400:	method=000000000027FD90 (Long64VectorLoadStoreTests.loadByteArrayIOOBE(Ljava/util/function/IntFunction;Ljava/util/function/IntFunction;)V) (JIT)
[2021-12-21T09:41:58.923Z] 0000000000239400:	stack=000000000028B058-00000000002908C0
[2021-12-21T09:41:58.923Z] 0000000000239400: Object neither in heap nor stack-allocated in thread MainThread
[2021-12-21T09:41:58.923Z] 0000000000239400:	O-Slot=000000000028FC10
[2021-12-21T09:41:58.923Z] 0000000000239400:	O-Slot value=00007F1FB58E0BA8
[2021-12-21T09:41:58.923Z] 0000000000239400:	PC=00007F1FEF913D24
[2021-12-21T09:41:58.923Z] 0000000000239400:	framesWalked=1
[2021-12-21T09:41:58.923Z] 0000000000239400:	arg0EA=000000000028FC28
[2021-12-21T09:41:58.923Z] 0000000000239400:	walkSP=000000000028FAD8
[2021-12-21T09:41:58.923Z] 0000000000239400:	literals=0000000000000000
[2021-12-21T09:41:58.923Z] 0000000000239400:	jitInfo=00007F1FEF470078
[2021-12-21T09:41:58.923Z] 0000000000239400:	method=000000000027FD90 (Long64VectorLoadStoreTests.loadByteArrayIOOBE(Ljava/util/function/IntFunction;Ljava/util/function/IntFunction;)V) (JIT)
[2021-12-21T09:41:58.923Z] 0000000000239400:	stack=000000000028B058-00000000002908C0
[2021-12-21T09:41:58.923Z] JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/Snap.20211221.014128.4170217.0003.trc' in response to an event
[2021-12-21T09:41:58.923Z] JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/Snap.20211221.014128.4170217.0003.trc
[2021-12-21T09:41:58.923Z] JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/jitdump.20211221.014128.4170217.0004.dmp' in response to an event
[2021-12-21T09:41:58.923Z] JVMDUMP051I JIT dump occurred in 'MainThread' thread 0x0000000000239400
[2021-12-21T09:41:58.923Z] JVMDUMP053I JIT dump is recompiling Long64VectorLoadStoreTests.loadByteArrayIOOBE(Ljava/util/function/IntFunction;Ljava/util/function/IntFunction;)V
[2021-12-21T09:41:58.923Z] JVMDUMP053I JIT dump is recompiling Long64VectorLoadStoreTests.loadByteArrayIOOBE(Ljava/util/function/IntFunction;Ljava/util/function/IntFunction;)V
[2021-12-21T09:41:58.923Z] JVMDUMP053I JIT dump is recompiling jdk/internal/reflect/NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
[2021-12-21T09:41:58.923Z] JVMDUMP053I JIT dump is recompiling jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
[2021-12-21T09:41:58.923Z] JVMDUMP053I JIT dump is recompiling java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
[2021-12-21T09:41:58.923Z] JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16400192462034/jdk_vector_0/work/scratch/0/jitdump.20211221.014128.4170217.0004.dmp
[2021-12-21T09:41:58.923Z] JVMDUMP013I Processed dump event "gpf", detail "".

[2021-12-21T10:49:40.871Z] jdk_vector_0_FAILED
```
This failure occurred at JDK17 GA (`0.29.1`) release build.

fyi @gita-omr

**Comment by pshipton** [comment] 2022-01-06 18:37
It seems strange to be testing a build which is released and done. We'd only care about this problem if it still occurs on the latest.

**Comment by gita-omr** [comment] 2022-01-10 18:04
> It seems strange to be testing a build which is released and done. We'd only care about this problem if it still occurs on the latest.

Yeah, I was wondering about the priority of this defect too.

**Comment by pshipton** [comment] 2022-01-10 18:28
It's a failure in an incubator feature. I'm just going to close it as obsolete, it should be reopened if the problem is seen on a current build.

**Closed by pshipton** 2022-01-10 18:29 UTC
Labels: test failure

**Comment by JasonFengJ9** [comment] 2022-01-10 18:32
The failure was observed in JDK17 CE release build which hasn't been published yet.
Agreed this is a failure in an incubator feature, not affect release exit criteria.
