### ISSUE TITLE
JDK19 Windows serviceability_jvmti_j9_0_FAILED serviceability/jvmti/vthread/SuspendResume1/SuspendResume1.java Fatal error: check_resumed_state: expected SUSPENDED flag in thread state

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16827] opened 2023-03-06 13:57 UTC
This test was timedout at [JDK19 x86-64_windows milestone 1 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_x86-64_windows/31/)(`win16x64rt-1-8`)
```
[2023-03-02T23:30:55.210Z] variation: Mode650
[2023-03-02T23:30:55.648Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-03-03T00:06:44.109Z] TEST: serviceability/jvmti/vthread/BreakpointInYieldTest/BreakpointInYieldTest.java

[2023-03-03T00:06:44.111Z] TEST RESULT: Error. Program `C:\Users\jenkins\workspace\Test_openjdk19_j9_extended.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1702937ms).
[2023-03-03T00:06:44.112Z] --------------------------------------------------
[2023-03-03T00:06:44.112Z] Test results: passed: 117; error: 1
[2023-03-03T00:07:09.055Z] Report written to C:\Users\jenkins\workspace\Test_openjdk19_j9_extended.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
[2023-03-03T00:07:09.055Z] Results written to C:\Users\jenkins\workspace\Test_openjdk19_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16777989179269\serviceability_jvmti_j9_1\work
[2023-03-03T00:07:09.055Z] Error: Some tests failed or other problems occurred.
[2023-03-03T00:07:09.055Z] -----------------------------------
[2023-03-03T00:07:09.055Z] serviceability_jvmti_j9_1_FAILED
```
_Originally posted by @JasonFengJ9 in https://github.com/eclipse-openj9/openj9/issues/16756#issuecomment-1454204483_

[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31373/) - 17/50 failed w/ `Fatal error: check_resumed_state: expected SUSPENDED flag in thread state`
            
[Grinder_iteration_2](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/1941/consoleFull)
[Grinder_iteration_4](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/1650/consoleFull)
[Grinder_iteration_1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/2134/consoleFull)

```
17:26:06  openjdk version "19.0.2" 2023-01-17
17:26:06  IBM Semeru Runtime Open Edition 19.0.2.0-m1 (build 19.0.2+7)
17:26:06  Eclipse OpenJ9 VM 19.0.2.0-m1 (build v0.37.0-release-042864b42, JRE 19 Windows Server 2019 amd64-64-Bit Compressed References 20230117_56 (JIT enabled, AOT enabled)
17:26:06  OpenJ9   - 042864b42
17:26:06  OMR      - 79f110f00
17:26:06  JCL      - be7d0c27852 based on jdk-19.0.2+7)

17:35:41  variation: Mode650
17:35:41  JVM_OPTIONS:  -XX:-UseCompressedOops  

18:46:26  TEST: serviceability/jvmti/vthread/SuspendResume1/SuspendResume1.java

18:46:26  Fatal error: check_resumed_state: expected SUSPENDED flag in thread state

18:46:26  TEST RESULT: Failed. Unexpected exit from test [exit code: 1111]
18:46:26  --------------------------------------------------
18:47:26  Test results: passed: 118; failed: 1
18:47:37  Report written to C:\Users\jenkins\workspace\Grinder_iteration_2\jvmtest\openjdk\report\html\report.html
18:47:37  Results written to C:\Users\jenkins\workspace\Grinder_iteration_2\aqa-tests\TKG\output_16778829266396\serviceability_jvmti_j9_1_ITER_4\work
18:47:37  Error: Some tests failed or other problems occurred.
18:47:37  
18:47:37  serviceability_jvmti_j9_1_FAILED(ITER_4)
```

**Comment by babsingh** [comment] 2023-03-06 22:12
@dipak-bagadiya The above failure looks similar to #16689. Can you confirm if this failure is a duplicate of https://github.com/eclipse-openj9/openj9/issues/16689? If yes, we will close this issue, document this failure under #16689 and re-exclude `SuspendResume1` under #16689.

**Comment by babsingh** [comment] 2023-03-09 18:03
This failure should be fixed by https://github.com/eclipse-openj9/openj9/pull/16843 in the JDK19 release branch. The [first grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31473/) didn't run completely due to infra issues. So, launched a [second grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31508/), which is still running. The SuspendResume1 failure was not seen in the first grinder.

**Closed** 2023-03-13 14:56 UTC
Labels: comp:vm, test failure
