### ISSUE TITLE
AIX OpenJDK java/foreign/TestFallbackLookup Cannot invoke "jdk.internal.loader.NativeLibrary.lookup(java.lang.String)" because "lib" is null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19573] opened 2024-05-29 13:57 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/211/ - [p8-java1-ibm04](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm04)
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/211 - [p8-java1-ibm12](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm12)
jdk_foreign_0
java/foreign/TestFallbackLookup.java
```
20:03:59  test TestFallbackLookup.testBadSystemLookupRequest(): failure
20:03:59  java.lang.ExceptionInInitializerError
20:03:59  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
20:03:59  	at java.base/jdk.internal.foreign.abi.AbstractLinker.defaultLookup(AbstractLinker.java:147)
20:03:59  	at java.base/jdk.internal.foreign.abi.AbstractLinker.defaultLookup(AbstractLinker.java:70)
20:03:59  	at TestFallbackLookup.testBadSystemLookupRequest(TestFallbackLookup.java:41)
20:03:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:03:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
20:03:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
20:03:59  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
20:03:59  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
20:03:59  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
20:03:59  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
20:03:59  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
20:03:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
20:03:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
20:03:59  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
20:03:59  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
20:03:59  	at org.testng.TestRunner.run(TestRunner.java:585)
20:03:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
20:03:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
20:03:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
20:03:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
20:03:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
20:03:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
20:03:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
20:03:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
20:03:59  	at org.testng.TestNG.runSuites(TestNG.java:1069)
20:03:59  	at org.testng.TestNG.run(TestNG.java:1037)
20:03:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
20:03:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
20:03:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
20:03:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
20:03:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
20:03:59  	at java.base/java.lang.Thread.run(Thread.java:1595)
20:03:59  Caused by: java.lang.NullPointerException: Cannot invoke "jdk.internal.loader.NativeLibrary.lookup(java.lang.String)" because "lib" is null
20:03:59  	at java.base/jdk.internal.foreign.SystemLookup.lambda$libLookup$10(SystemLookup.java:181)
20:03:59  	at java.base/jdk.internal.foreign.SystemLookup.getInlinedFunctListAddr(SystemLookup.java:106)
20:03:59  	at java.base/jdk.internal.foreign.SystemLookup.<clinit>(SystemLookup.java:63)
20:03:59  	... 32 more
```

Changes
https://github.com/eclipse-openj9/openj9/compare/4ff10c9cd...7c623220d1f
https://github.com/eclipse-openj9/openj9-omr/compare/01374a448...5c74758cf6b
https://github.com/ibmruntimes/openj9-openjdk-jdk21/compare/4bd6a610bb2...c67fccdb064

**Comment by pshipton** [comment] 2024-05-29 13:58
@ChengJin01 did https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/159 break AIX?

**Comment by pshipton** [comment] 2024-05-29 14:00
jdk22 as well https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_ppc64_aix_Nightly/73
https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/61

**Comment by ChengJin01** [comment] 2024-05-29 16:03
The failing test at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/TestFallbackLookup.java is intended to verify whether an exception is triggered by loading a non-existent `ucrtbase.dll`
```
public class TestFallbackLookup {
    @Test
    void testBadSystemLookupRequest() {
        // we request a Linker, forcing OS name to be "Windows". This should trigger an exception when
        // attempting to load a non-existent ucrtbase.dll. Make sure that no error is generated at this stage.
        assertTrue(Linker.nativeLinker().defaultLookup().find("nonExistentSymbol").isEmpty()); <------
    }
}
```
in which `NullPointerException` came from `getInlinedFunctListAddr()` added in https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/159 which should never fail at 
```
        SymbolLookup funcsLibLookup = libLookup(libs -> libs.load(jdkLibraryPath("syslookup")));
```
given `https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/closed/src/java.base/aix/native/libsyslookup/syslookup.c` exists out there (unless `libsyslookup.so` was not generated in compilation). I will need to investigate to see what really happened in there.

**Comment by ChengJin01** [comment] 2024-05-29 19:38
I think the problem came from the option ` -Dos.name=Windows` specified at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/TestFallbackLookup.java:
```
/*
 * @test
 * @enablePreview
 * @requires jdk.foreign.linker != "UNSUPPORTED"
 * @run testng/othervm -Dos.name=Windows --enable-native-access=ALL-UNNAMED TestFallbackLookup
 */
```
which is intended to verify the unexpected behavior if the `os.name` changes to `Windows` in which case it skips `OperatingSystem.isAix()` without checking `System.getProperty("os.name")` in getInlinedFunctListAddr(), which means we have to get System.getProperty("os.name") back in the code to prevent such abnormal situation.

FYI: @keithc-ca

**Comment by keithc-ca** [comment] 2024-05-29 20:35
I'd rather see a solution that doesn't involve making changes to `Utils`.

**Comment by ChengJin01** [comment] 2024-05-29 20:57
> I'd rather see a solution that doesn't involve making changes to `Utils`.

There is no easy around this situation given the problem essentially comes from the inconsistency between the platform property specified in `OperatingSystem`  and system property `os.name` unless we are able to consolidate both of them in dealing with this platform specific case.

**Comment by keithc-ca** [comment] 2024-05-30 13:49
I think the root of the problem here is in `SystemLookup.java` because `jdkLibraryPath("syslookup")` is answering `${java.home}/bin/libsyslookup.so` when, on AIX, `os.name=Windows`. I suggest this would be solved by replacing the two uses of `Utils.IS_WINDOWS` with `OperatingSystem.isWindows()`.

I'll create a pull request to validate that.

**Comment by ChengJin01** [comment] 2024-05-31 21:16
Close the issue as resolved.

**Closed by ChengJin01** 2024-05-31 21:16 UTC
Labels: test failure, blocker
