### ISSUE TITLE
testRASAPI_0 testSetBadOptions Did not expect to be able to set a bad dump option

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16958] opened 2023-03-20 14:21 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/475
testRASAPI_0
```
     [test]     [junit] Testcase: testSetBadOptions took 0.004 sec
     [test]     [junit] 	FAILED
     [test]     [junit] Did not expect to be able to set a bad dump option: java:events=throw,filter=not/a/real/Exception, queryDumpOptions() found: [java:events=throw,filter=not/a/real/Exception,file=/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/jvmtest/functional/RasapiTest/javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,range=1..0,priority=400,request=exclusive+preempt]
     [test]     [junit] junit.framework.AssertionFailedError: Did not expect to be able to set a bad dump option: java:events=throw,filter=not/a/real/Exception, queryDumpOptions() found: [java:events=throw,filter=not/a/real/Exception,file=/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/jvmtest/functional/RasapiTest/javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,range=1..0,priority=400,request=exclusive+preempt]
     [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPIQuerySetReset.testSetBadOptions(DumpAPIQuerySetReset.java:475)
     [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by pshipton** [comment] 2023-03-21 13:34
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/476
testRASAPI_0
```
     [test]     [junit] Testcase: testSetBadOptions took 0.008 sec
     [test]     [junit] 	FAILED
     [test]     [junit] Did not expect to be able to set a bad dump option: java:events=throw,filter=not/a/real/Exception, queryDumpOptions() found: [java:events=throw,filter=not/a/real/Exception,file=/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/jvmtest/functional/RasapiTest/javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,range=1..0,priority=400,request=exclusive+preempt]
     [test]     [junit] junit.framework.AssertionFailedError: Did not expect to be able to set a bad dump option: java:events=throw,filter=not/a/real/Exception, queryDumpOptions() found: [java:events=throw,filter=not/a/real/Exception,file=/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/jvmtest/functional/RasapiTest/javacore.%Y%m%d.%H%M%S.%pid.%seq.txt,range=1..0,priority=400,request=exclusive+preempt]
     [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPIQuerySetReset.testSetBadOptions(DumpAPIQuerySetReset.java:475)
```

**Comment by pshipton** [comment] 2023-03-21 13:38
Changes between last working and first failing build.

OpenJ9: ad1aa216fca
OMR: 3070c7f5504
OpenJDK11: 6a7291a42bb - openj9-openjdk-jdk11

OpenJ9: 9e9fe327f9d
OMR: e07b5edc181
OpenJDK11: a6a55907b48 - openj9-openjdk-jdk11

https://github.com/eclipse-openj9/openj9/compare/ad1aa216fca...9e9fe327f9d
https://github.com/eclipse-openj9/openj9-omr/compare/3070c7f5504...e07b5edc181
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/6a7291a42bb...a6a55907b48

**Comment by pshipton** [comment] 2023-03-21 13:43
https://github.com/eclipse-openj9/openj9/pull/16926 seems the most likely cause of this regression.

@tajila @JasonFengJ9 @keithc-ca

**Comment by pshipton** [comment] 2023-03-21 13:53
Also failing on zlinux now that CRIU is enabled.
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_0/495

**Comment by JasonFengJ9** [comment] 2023-03-21 14:24
Will have a look.

**Comment by JasonFengJ9** [comment] 2023-03-22 13:18
This test result difference was caused by removing `J9HookDisable(vmHooks, J9HOOK_VM_EXCEPTION_THROW)` for CRIU builds. 
https://github.com/eclipse-openj9/openj9/blob/d0a6950ce2d69d89f321c38a69fbf51fe8c3306b/runtime/compiler/control/J9Options.cpp#L2894-L2898
https://github.com/eclipse-openj9/openj9/blob/d0a6950ce2d69d89f321c38a69fbf51fe8c3306b/runtime/compiler/env/VMJ9.cpp#L2971-L2975

The test code in question expects `InvalidDumpOptionException` to pass.
https://github.com/eclipse-openj9/openj9/blob/d0a6950ce2d69d89f321c38a69fbf51fe8c3306b/test/functional/RasapiTest/src/com/ibm/jvm/ras/tests/DumpAPIQuerySetReset.java#L470-L478
The exception is raised according to `setDumpOption()` result.
https://github.com/eclipse-openj9/openj9/blob/d0a6950ce2d69d89f321c38a69fbf51fe8c3306b/runtime/jcl/common/dump.c#L255-L259
The unsuccessful result was actually from `J9HookRegisterWithCallSite`
https://github.com/eclipse-openj9/openj9/blob/d0a6950ce2d69d89f321c38a69fbf51fe8c3306b/runtime/rasdump/trigger.c#L1112
```
#0  rasDumpEnableHooks (vm=0x7ffff000fe90, eventFlags=16) at /root/builds/jdk11-raspass-0321/openj9-openjdk-jdk11/openj9/runtime/rasdump/trigger.c:1151
#1  0x00007ffff53c55cf in insertDumpAgent (vm=0x7ffff000fe90, agent=0x7ffff0026840) at /root/builds/jdk11-raspass-0321/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpqueue.c:40
#2  0x00007ffff53c1de0 in loadDumpAgent (vm=0x7ffff000fe90, kind=4, optionString=0x7ffff014c3a5 "events=throw,filter=not/a/real/Exception") at /root/builds/jdk11-raspass-0321/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpagent.c:2573
#3  0x00007ffff53c83c8 in setDumpOption (vm=0x7ffff000fe90, optionString=0x7ffff014c3a5 "events=throw,filter=not/a/real/Exception") at /root/builds/jdk11-raspass-0321/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpsup.c:984
#4  0x00007fffeda61c36 in Java_com_ibm_jvm_Dump_setDumpOptionsImpl (env=0x1aa00, clazz=0x244530, jopts=0x110aa8) at /root/builds/jdk11-raspass-0321/openj9-openjdk-jdk11/openj9/runtime/jcl/common/dump.c:255
```
Confirmed that the test passes if `J9HookDisable()` is restored.
Apparently, the test doesn't properly verify the processing of garbage options.

This is a test issue, will comment out the failing sub-tests first since it is within `extended.functional` test suits.

**Comment by pshipton** [comment] 2023-03-22 13:27
The test is confirming you can't set an -Xdump event at runtime when -Xdump:dynamic isn't enabled. It seems valid to me.

**Comment by pshipton** [comment] 2023-03-26 14:21
Keep this open until https://github.com/eclipse-openj9/openj9/pull/17026 is merged.

**Comment by JasonFengJ9** [comment] 2023-03-27 14:06
Closing since https://github.com/eclipse-openj9/openj9/pull/17026 has been merged.

**Closed by JasonFengJ9** 2023-03-27 14:06 UTC
Labels: comp:test, test failure, blocker
