### ISSUE TITLE
JDK11 jdmpview doesn't work on some OS version/machines

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15638] opened 2022-07-27 20:54 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_x86-64_linux_testList_1/253/tapResults/)(`rhel9x86-rt2-1.fyre.ibm.com`):
```
23:24:16  java version "11.0.16" 2022-07-19
23:24:16  IBM Semeru Runtime Certified Edition 11.0.16.0-rc1 (build 11.0.16+8)
23:24:16  Eclipse OpenJ9 VM 11.0.16.0-rc1 (build openj9-0.33.0-rc1, JRE 11 Linux amd64-64-Bit Compressed References 20220720_388 (JIT enabled, AOT enabled)
23:24:16  OpenJ9   - 8cb527940
23:24:16  OMR      - b58aa2708
23:24:16  JCL      - 8b2d4875e9 based on jdk-11.0.16+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_x86-64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F388%2Fibm-semeru-certified-jre_x64_linux_11.0.16.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F388%2Fibm-semeru-certified-jdk_x64_linux_11.0.16.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F388%2Fibm-semeru-certified-debugimage_x64_linux_11.0.16.0-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F388%2Fibm-semeru-certified-testimage_x64_linux_11.0.16.0-rc1.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.3-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&RELEASE_TAG=v0.33.0-release&OPENJ9_BRANCH=v0.33.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.33.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=288&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=true&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
Testing: Run !allclasses
Test start time: 2022/07/19 20:50:51 Pacific Standard Time
Running command: /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_linux_testList_1/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
Time spent starting: 3 milliseconds
Time spent executing: 6524 milliseconds
Test result: FAILED
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Problem running command: 
 [OUT] null
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: java/lang/Object]
>> Failure condition was not found: [Output match: DDRInteractiveCommandException]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: could not read]
>> Failure condition was not found: [Output match: dump event]

---TEST RESULTS---
Number of PASSED tests: 3 out of 8
Number of FAILED tests: 5 out of 8

---SUMMARY OF FAILED TESTS---
Run !allclasses
Run !dumpallromclasslinear 10
Run !dumpallramclasslinear 10
Run !romclasssummary
Run !ramclasssummary
-----------------------------


cmdLineTester_classesdbgddrext_0_FAILED
```

The failure is consistent at this machine - [grinder in same machine](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26254/tapResults/) - all failed
Login to the machine, the core generation was successful, but jdmpview failed to load/parse it.

[grinder in 5 different machines](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26259/) passed four machines
[rhel7x64cudart1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/1284)
[cent7x64-1-10](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/1137)
[ub18x64rt1-1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/1522)
[cent7x64-1-7](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_1/1373)
failed at [ubu22x86-rt4-1](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_3/1188)

Related to [an internal infra issue](https://github.ibm.com/runtimes/infrastructure/issues/6328)

**Comment by keithc-ca** [comment] 2022-07-28 18:11
I tried the build referenced in the description with the core file used in the failing `!allclasses` test on a Ubuntu 22.04 system: it passes. There must be something peculiar about uu22x86-rt4-1: I'll try again there.

**Comment by keithc-ca** [comment] 2022-07-28 18:22
The test passes on ubu22x86-rt4-1 as well.

**Comment by pshipton** [comment] 2022-07-28 18:58
I expect this is another one of those problems where it doesn't work on the original machine with all the original libraries available, but works when you try it otherwise.

**Comment by keithc-ca** [comment] 2022-07-28 19:10
In my first test on ubuntu22, I ran the test in the same way as the build so everything was in the same place as when the core was created: that seems to discount that theory.

**Comment by pshipton** [comment] 2022-07-28 20:15
Can we modify the test to get more logging about the failure when it does occur?

**Comment by pshipton** [comment] 2022-08-26 13:05
I'm not seeing any problem running the test on ubu22x86-rt4-1 with the latest builds. I wonder if the problem was related to https://github.com/eclipse-openj9/openj9/pull/15734 which was added to the 0.33.1 release. I'll go ahead and close this until the problem is seen again.

**Closed by pshipton** 2022-08-26 13:05 UTC
Labels: comp:vm, test failure, triageRequired
