### ISSUE TITLE
JDK22 serviceability_jvmti_j9_0_FAILED serviceability/jvmti/vthread/SelfSuspendDisablerTest/SelfSuspendDisablerTest.java#no-vmcontinuations Fatal error: Error in ResumeThread

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19031] opened 2024-02-27 22:46 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_x86-64_linux_Personal/42/consoleFull)(`cent9x86-rtp-rt8-1`):
```
19:58:34  openjdk version "22-internal" 2024-03-19
19:58:34  OpenJDK Runtime Environment (build 22-internal-adhoc.jenkins.BuildJDK22x86-64linuxPersonal)
19:58:34  Eclipse OpenJ9 VM (build master-b9f7880c225, JRE 22 Linux amd64-64-Bit Compressed References 20240226_76 (JIT enabled, AOT enabled)
19:58:34  OpenJ9   - b9f7880c225
19:58:34  OMR      - b399f9e8c0f
19:58:34  JCL      - cdc12a56665 based on jdk-22+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,jdk_nio_0,jdk_nio_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK22_x86-64_linux_Personal%2F76%2FOpenJ9-JDK22-x86-64_linux-20240226-155552.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK22_x86-64_linux_Personal%2F76%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk22.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=b9f7880c225639b7e4724e0028ef05257341e3ca&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
19:59:42  variation: Mode150
19:59:42  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

20:04:17  TEST: serviceability/jvmti/vthread/SelfSuspendDisablerTest/SelfSuspendDisablerTest.java#no-vmcontinuations

20:04:17  STDOUT:
20:04:17  Agent init started
20:04:17  Agent init finished
20:04:17  Expected platform thread state: 000000 got: 000000
20:04:17  Expected virtual  thread state: 000000 got: 000000
20:04:17  Expected virtual  thread state: 000005 got: 000005
20:04:17  Expected platform thread state: 000005 got: 000005
20:04:17  Expected platform thread state: 100005 got: 500005
20:04:17  check_jvmti_status: JVMTI function returned error: JVMTI_ERROR_THREAD_NOT_SUSPENDED (13)
20:04:17  STDERR:
20:04:17  
20:04:17  Fatal error: Error in ResumeThread

20:04:17  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]
20:04:17  --------------------------------------------------
20:04:50  Test results: passed: 157; failed: 1
20:05:03  Report written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_x86-64_linux_Personal/jvmtest/openjdk/report/html/report.html
20:05:03  Results written to /home/jenkins/workspace/Test_openjdk22_j9_extended.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_17089955812724/serviceability_jvmti_j9_0/work
20:05:03  Error: Some tests failed or other problems occurred.
20:05:03  -----------------------------------
20:05:03  serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/38134/) - `Fatal error: Error in ResumeThread` wasn't reproduced, one time out error same as https://github.com/eclipse-openj9/openj9/issues/18675

**Comment by tajila** [comment] 2024-02-28 00:32
@babsingh

**Comment by pshipton** [comment] 2024-02-28 04:17
The failure didn't reoccur in the grinder.
49 of the runs passed, there was one failure on rhel9x86-rtp-rt3-1, which is mentioned in https://github.com/eclipse-openj9/openj9/issues/18763 and https://github.com/eclipse-openj9/openj9/issues/18675, both of which are assigned to the 3Q release.
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default

**Comment by babsingh** [comment] 2024-03-04 20:54
I am unable to reproduce this failure. The failure symptoms are similar to the issue reported in #18735. Closing this as a duplicate of #18735.

```
20:04:17  check_jvmti_status: JVMTI function returned error: JVMTI_ERROR_THREAD_NOT_SUSPENDED (13)
20:04:17  Fatal error: Error in ResumeThread
```

**Closed by babsingh** 2024-03-04 20:54 UTC
Labels: comp:vm, test failure, comp:jvmti
