### ISSUE TITLE
JDK23 java/io/PipedInputStream/CloseAndAvailableRC.java Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19598] opened 2024-05-31 20:43 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_mac_Personal/19/consoleFull)(`macaarch64rt5`):
```
18:22:13  openjdk version "23-internal" 2024-09-17
18:22:13  OpenJDK Runtime Environment (build 23-internal-adhoc.jenkins.BuildJDKnextaarch64macPersonal)
18:22:13  Eclipse OpenJ9 VM (build master-7c623220d1f, JRE 23 Mac OS X aarch64-64-Bit 20240528_81 (JIT enabled, AOT enabled)
18:22:13  OpenJ9   - 7c623220d1f
18:22:13  OMR      - 5c74758cf6b
18:22:13  JCL      - 82245b78fb6 based on jdk-23+24)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_1,jdk_io_1,jdk_security3_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_mac_Personal%2F81%2FOpenJ9-JDKnext-aarch64_mac-20240528-180149.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_mac_Personal%2F81%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=7c623220d1ff7b87835139226b126b3d306b76f3&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
18:24:14  variation: Mode650
18:24:14  JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

18:40:54  TEST: java/io/PipedInputStream/CloseAndAvailableRC.java

18:40:54  stderr:
18:40:54  Unhandled exception
18:40:54  Type=Segmentation error vmState=0x00000000
18:40:54  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
18:40:54  Handler1=0000000104C2D208 Handler2=0000000104E0DD44 InaccessibleAddress=00000000000004A0
18:40:54  x0=00000000000004A0 x1=0000000000000000 x2=0000000000001E00 x3=0000000000000000
18:40:54  x4=00000000000020A0 x5=000000017C27E7C0 x6=000000012A2C8908 x7=00000002B0008700
18:40:54  x8=00000000000020A0 x9=0000000000000000 x10=0000000000000001 x11=0000000000001F02
18:40:54  x12=00001E0000001E02 x13=0000000000000000 x14=00001E0000001F02 x15=0000000000000000
18:40:54  x16=0000000186BE1D9C x17=00000001F553EE58 x18=000000017C27EC10 x19=0000000134816358
18:40:54  x20=00000000000004A0 x21=0000000000000000 x22=0000000000000004 x23=0000000000000011
18:40:54  x24=0000000000000001 x25=0000000000000407 x26=000000000000001A x27=000000010A8DD868
18:40:54  x28=000000010A8A6D10 x29(FP)=000000017C27E7A0 x30(LR)=0000000104E8F138 x31(SP)=000000017C27E770
18:40:54  PC=0000000186BE1D9C SP=000000017C27E770
18:40:54  v0=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v1=0073006f006c0043 (f: 7077955.000000, d: 1.691207e-306)
18:40:54  v2=41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
18:40:54  v3=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v4=40d1ed124731676e (f: 1194420096.000000, d: 1.835629e+04)
18:40:54  v5=be86e824f5f20db5 (f: 4126281216.000000, d: -1.706691e-07)
18:40:54  v6=40c0000000000000 (f: 0.000000, d: 8.192000e+03)
18:40:54  v7=c0c0000000000000 (f: 0.000000, d: -8.192000e+03)
18:40:54  v8=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v9=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v10=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v11=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v12=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v13=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v14=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v15=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v16=bfd0000000000000 (f: 0.000000, d: -2.500000e-01)
18:40:54  v17=3fd55191a1955555 (f: 2710918400.000000, d: 3.331036e-01)
18:40:54  v18=3f4e1a1399b3d1c2 (f: 2578698752.000000, d: 9.186359e-04)
18:40:54  v19=3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
18:40:54  v20=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v21=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v22=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v23=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v24=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v25=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v26=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v27=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v28=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v29=0000000000000000 (f: 0.000000, d: 0.000000e+00)
18:40:54  v30=65747379530a0003 (f: 1393164288.000000, d: 5.303877e+180)
18:40:54  v31=0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
18:40:54  Module=/usr/lib/system/libsystem_pthread.dylib
18:40:54  Module_base_address=0000000186BE0000 Symbol=pthread_mutex_lock
18:40:54  Symbol_address=0000000186BE1D9C
18:40:54  Target=2_90_20240528_81 (Mac OS X 11.4)
18:40:54  CPU=aarch64 (8 logical CPUs) (0x400000000 RAM)
18:40:54  ----------- Stack Backtrace -----------
18:40:54  ---------------------------------------
18:40:54  JVMDUMP039I Processing dump event "gpf", detail "" at 2024/05/28 18:24:42 - please wait.
18:40:54  JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_17169349568079/jdk_io_1/work/scratch/2/core.20240528.182442.3399.0001.dmp' in response to an event
18:40:54  JVMDUMP010I System dump written to /Users/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_17169349568079/jdk_io_1/work/scratch/2/core.20240528.182442.3399.0001.dmp
18:40:54  JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_17169349568079/jdk_io_1/work/scratch/2/javacore.20240528.182442.3399.0002.txt' in response to an event
18:40:54  
18:40:54  TEST RESULT: Error. Agent error: java.lang.Exception: Agent 10 timed out with a timeout of 960 seconds; check console log for any additional details
18:40:54  --------------------------------------------------
18:40:54  Test results: passed: 423; error: 1
18:40:54  Report written to /Users/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_17169349568079/jdk_io_1/report/html/report.html
18:40:54  Results written to /Users/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_mac_Personal/aqa-tests/TKG/output_17169349568079/jdk_io_1/work
18:40:54  Error: Some tests failed or other problems occurred.
18:40:54  -----------------------------------
18:40:54  jdk_io_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/41053/) - 9/50 failed

[JDK23 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_x86-64_mac_Personal/15/consoleFull)(`osxrt6`)

There was a similar error before
* https://github.com/eclipse-openj9/openj9/issues/15628

**Comment by knn-k** [comment] 2024-06-03 02:58
This looks more similar to #19544:
- Failure with JDK 23
- SEGV in pthread_mutex_lock() with x0=0x4A0 (offset of `mutex` in `J9Thread`)

**Comment by babsingh** [comment] 2024-06-11 03:28
This is a duplicate of https://github.com/eclipse-openj9/openj9/issues/19544. Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/803 to resolve this failure.

**Closed by babsingh** 2024-06-11 03:28 UTC
Labels: test failure, segfault, jdk23
