### ISSUE TITLE
JDK21 serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java RuntimeException: JVMTI multi thread state is wrong

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18089] opened 2023-09-07 14:50 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_mac_Personal/27/consoleFull)(`osxrt1`):
```
03:27:31  openjdk version "21-internal" 2023-09-19
03:27:31  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21x86-64macPersonal)
03:27:31  Eclipse OpenJ9 VM (build master-7599bde8a13, JRE 21 Mac OS X amd64-64-Bit Compressed References 20230906_50 (JIT enabled, AOT enabled)
03:27:31  OpenJ9   - 7599bde8a13
03:27:31  OMR      - 873ac5d377a
03:27:31  JCL      - 154f45ddce4 based on jdk-21+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_x86-64_mac_Personal%2F50%2FOpenJ9-JDK21-x86-64_mac-20230906-221524.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_x86-64_mac_Personal%2F50%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=7599bde8a134c25aee722cd5ec66023c91f99631&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
03:29:53  variation: Mode150
03:29:53  JVM_OPTIONS:  -XX:+UseCompressedOops 

03:32:59  TEST: serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java

03:32:59  STDERR:
03:32:59  java.lang.RuntimeException: JVMTI multi thread state is wrong
03:32:59  	at ThreadListStackTracesTest.failed(ThreadListStackTracesTest.java:87)
03:32:59  	at ThreadListStackTracesTest.checkStates(ThreadListStackTracesTest.java:132)
03:32:59  	at ThreadListStackTracesTest.checkReentrantLock(ThreadListStackTracesTest.java:101)
03:32:59  	at ThreadListStackTracesTest.main(ThreadListStackTracesTest.java:90)
03:32:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
03:32:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
03:32:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
03:32:59  	at java.base/java.lang.Thread.run(Thread.java:1595)
03:32:59  
03:32:59  JavaTest Message: Test threw exception: java.lang.RuntimeException: JVMTI multi thread state is wrong

03:33:09  serviceability_jvmti_j9_0_FAILED
```

[50x serviceability_jvmti_j9_0 internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34808/) - this failure wasn't reproduced

FYI @babsingh

**Comment by babsingh** [comment] 2023-09-13 16:48
Locally, I was able to reproduce the failure 1 time in 250 runs. The default test output is insufficient to properly triage. The test will need to be updated to print/output more debug information. @thallium Shall I assign this issue to you?

**Comment by thallium** [comment] 2023-09-13 16:55
@babsingh Sure I can take a look at this.

**Comment by thallium** [comment] 2023-09-22 20:50
A few things that I have observed:
- when the test failed, it got RUNNABLE state instead of WAITING
- the thread state changed to WAITING after `singleState` and `multiState` is set, so the check `vt.getState() != expState` passed

**Comment by babsingh** [comment] 2023-09-28 14:40
@thallium Documenting my notes (Slack conversation) from Monday here since they highlight the next steps for the issue. Can you provide me a progress update, what will be your next steps and a time estimate to resolve this issue?

### Test source code

https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/c2fb960c3951006ffe09af0241e95028e3cc8c09/test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java#L128-L132

```
        // [ERROR] 03:32:59  java.lang.RuntimeException: JVMTI multi thread state is wrong

        if ((singleState & jvmtiExpState) == 0) {
            failed("JVMTI single thread state is wrong");
        }
        if ((multiState & jvmtiExpState) == 0) {
            failed("JVMTI multi thread state is wrong");
        }
```

The above two checks fail intermittently.

```
        int singleState = getStateSingle(vt);
        int multiState = getStateMultiple(vt, Thread.currentThread());
```

- `getStateSingle` and `getStateMultiple` use `JVMTI GetThreadListStackTraces` to get the thread state.
- Check the code for `JVMTI GetThreadListStackTraces`.
- Find under what circumstances `JVMTI GetThreadListStackTraces` can return `RUNNABLE` instead of `WAITING` (expected).
- Two perspectives to explore:
   - the test might be wrong, and it doesn't check the correct behaviour which is specified in the JVMTI specification; OR
   - our implementation is wrong, and we don't follow the JVMTI specification for `GetThreadListStackTraces`.

**Comment by thallium** [comment] 2023-09-29 01:54
Current update: `JVMTI GetThreadListStackTraces` calls `getVirtualThreadState` which uses `VirtualThread.state` to make the JVMTI thread state. I tried to get a dump right after the test failed but `VirtualThread.state` appeared to be normal in the dump. I'll try to run the test more times to catch the bad state, but I'm not sure what I can look at if I got a useful dump.

**Comment by babsingh** [comment] 2023-09-29 15:57
> `getVirtualThreadState` which uses `VirtualThread.state` to make the JVMTI thread state

`VirtualThread.state` is not always used.

- For mounted virtual threads `(NULL != targetThread)`, `getThreadStateHelper` is used. 

https://github.com/eclipse-openj9/openj9/blob/da4cabf7552dee6fc942ccecd2a933e669991304/runtime/jvmti/jvmtiHelpers.c#L821-L826

- Even for unmounted threads, `java.lang.Thread.container` field is used in some cases.
 
https://github.com/eclipse-openj9/openj9/blob/da4cabf7552dee6fc942ccecd2a933e669991304/runtime/jvmti/jvmtiHelpers.c#L841-L852

> but I'm not sure what I can look at if I got a useful dump.

Add debug code (print statements) in `getVirtualThreadState` (at multiple points) to see how the thread state is being evaluated. Once we know the code path taken to evaluate the incorrect state, then we can figure out what is causing this failure.

**Comment by babsingh** [comment] 2023-10-23 18:11
Moving to the 0.44 release since the failure is highly intermittent.

**Comment by babsingh** [comment] 2023-10-26 02:07
During failure, the test output is ...
```
STDOUT:
grabbing reentrantLock
State: expected: RUNNABLE single: 191 multi: 5
STDERR:
java.lang.RuntimeException: JVMTI multi thread state is wrong
```

When the test passes, the test output is ...
```
STDOUT:
grabbing reentrantLock
State: expected: WAITING single: 291 multi: 291
entering synchronized statement
State: expected: BLOCKED single: 401 multi: 401
entered synchronized statement
STDERR:
STATUS:Passed.
```

**The problem is in the TEST.** Test code, [ThreadListStackTracesTest.checkStates](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/eb3c4eeea1a903f274dd029ea85f7707a3231406/test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java#L115-L134):
```
    private static void checkStates(Thread vt, Thread.State expState) {
        int singleState = getStateSingle(vt);
        int multiState = getStateMultiple(vt, Thread.currentThread());
        int jvmtiExpState = (expState == Thread.State.WAITING) ?
                            JVMTI_THREAD_STATE_WAITING :
                            JVMTI_THREAD_STATE_BLOCKED_ON_MONITOR_ENTER;

        System.out.printf("State: expected: %s single: %x multi: %x\n",
                          vt.getState(), singleState, multiState);

        if (vt.getState() != expState) {
            failed("Java thread state is wrong");
        }
        if ((singleState & jvmtiExpState) == 0) {
            failed("JVMTI single thread state is wrong");
        }
        if ((multiState & jvmtiExpState) == 0) {
            failed("JVMTI multi thread state is wrong");
        }
    }

```

`getStateSingle` and `getStateMultiple` use [JVMTI GetThreadListStackTraces](https://docs.oracle.com/en/java/javase/21/docs/specs/jvmti.html#GetThreadListStackTraces) to get the thread state.

Test code, [ReentrantLockTestTask.run](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/eb3c4eeea1a903f274dd029ea85f7707a3231406/test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java#L58-L63) represents the virtual thread:
```
class ReentrantLockTestTask extends TestTask {
    public void run() {
        log("grabbing reentrantLock");
        threadReady = true;
        ThreadListStackTracesTest.reentrantLock.lock();
        log("grabbed reentrantLock");
    }
}
```

`checkStates` is invoked when the virtual thread runs `reentrantLock.lock()`.


Test code, [ThreadListStackTracesTest.checkReentrantLock](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/eb3c4eeea1a903f274dd029ea85f7707a3231406/test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java#L94-L102):

```
    private static void checkReentrantLock() throws InterruptedException {
        final Thread.State expState = Thread.State.WAITING;
        reentrantLock.lock();
        String name = "ReentrantLockTestTask";
        TestTask task = new ReentrantLockTestTask();
        Thread vt = Thread.ofVirtual().name(name).start(task);
        task.ensureReady(vt, expState);
        checkStates(vt, expState);
    }
```

`task.ensureReady` pauses execution until `threadReady` is `true` and `vt.getState()` reaches the expected state. The expected thread state in `checkReentrantLock` is `Thread.State.WAITING`. The test assumes that the expected thread state is only achieved when `reentrantLock.lock()` is invoked. This is not true. `Thread.State.WAITING` can also be achieved when the virtual thread scheduler unmounts and parks the virtual thread. There is ambiguity in the test code. To resolve this issue, we need to make sure that `checkStates` is invoked once the virtual thread is waiting to acquire the lock, `reentrantLock.lock()`.

The below changes to the test code should resolve the reported failure:
```
    public void ensureReady(Thread vt, Thread.State expState) {
    	// sleep for 1 second to allow the thread to reach the expected state
    	sleep(1000);
        // wait while the thread is not ready or thread state is unexpected
        while (!threadReady || (vt.getState() != expState)) {
            sleep(1);
        }
    }
    
    ...

    private static void checkReentrantLock() throws InterruptedException {
        final Thread.State expState = Thread.State.WAITING;
        reentrantLock.lock();
        String name = "ReentrantLockTestTask";
        TestTask task = new ReentrantLockTestTask();
        Thread vt = Thread.ofVirtual().name(name).start(task);
        task.ensureReady(vt, expState);
        // wait until vt is waiting to acquire the lock
        while (!reentrantLock.hasQueuedThread(vt)) {
        	sleep(1);
        }
        checkStates(vt, expState);
    }
```

Refer to the [Javadoc for ReentrantLock](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html#hasQueuedThread(java.lang.Thread)) to understand the `ReentrantLock.hasQueuedThread` method.

@singh264 Can you verify the above analysis? If you agree, can you create PRs that modify the test in the JDK21 and JDK-next repos?
- JDK21: https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java
- JDK-next: https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java

**Comment by JasonFengJ9** [comment] 2023-10-27 21:09
[JDK21 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_mac/11/)(`mac11x64rt04`)
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202310261403 (build 21.0.1-beta+12-202310261403)
Eclipse OpenJ9 VM 21.0.1+12-202310261403 (build master-66e3fd1da, JRE 21 Mac OS X amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
OpenJ9   - 66e3fd1da
OMR      - 071c0c25b
JCL      - c06eaf638 based on jdk-21.0.1+12)

[2023-10-26T15:00:50.188Z] variation: Mode650
[2023-10-26T15:00:50.188Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-10-26T15:03:11.619Z] TEST: serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java

[2023-10-26T15:03:11.620Z] STDERR:
[2023-10-26T15:03:11.620Z] java.lang.RuntimeException: JVMTI multi thread state is wrong
[2023-10-26T15:03:11.620Z] 	at ThreadListStackTracesTest.failed(ThreadListStackTracesTest.java:87)
[2023-10-26T15:03:11.620Z] 	at ThreadListStackTracesTest.checkStates(ThreadListStackTracesTest.java:132)
[2023-10-26T15:03:11.620Z] 	at ThreadListStackTracesTest.checkReentrantLock(ThreadListStackTracesTest.java:101)
[2023-10-26T15:03:11.620Z] 	at ThreadListStackTracesTest.main(ThreadListStackTracesTest.java:90)
[2023-10-26T15:03:11.620Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-10-26T15:03:11.620Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-10-26T15:03:11.620Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-10-26T15:03:11.620Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2023-10-26T15:03:30.804Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by singh264** [comment] 2023-11-13 21:35
> @babsingh I will verify the analysis.

It seems like the virtual thread scheduler does not unmount and park the virtual thread when the state of the thread changes from `Thread.State.RUNNABLE` to `Thread.State.WAITING` in `ensureReady(..)` as `virtualThreadUnmountBegin(..)`  and `virtualThreadUnmountEnd(..)` are only called when the `reentrantLock` parks the virtual thread, **which occurs after the main thread indicates the test failure** by completing `ensureReady(..)` and `checkStates(..)`. 

Before `ReentrantLockTestTask` starts, I observe that `VirtualThread.compareAndSetState(..)` is called to update the state from `VirtualThread.NEW <-> Thread.State.NEW` to `VirtualThread.STARTED <-> Thread.State.RUNNABLE`, and from `VirtualThread.STARTED <-> Thread.State.RUNNABLE` to `VirtualThread.RUNNING <-> (Thread.State.RUNNABLE or carrierThread.threadState())`. 

Since the `reentrantLock` parks the virtual thread **after the main thread indicates the test failure**, it seems like `carrierThread.threadState()` transitions from `Thread.State.WAITING` to `Thread.State.RUNNING` (before `getStateMultiple (..)`) and back to `Thread.State.WAITING` (before` if (vt.getState() != expState)`).

After the `reentrantLock` parks the virtual thread, I observe that  `VirtualThread.setState(..)` is called to update the state from `VirtualThread.RUNNING <-> (Thread.State.RUNNABLE or carrierThread.threadState())` to `VirtualThread.PARKING <-> Thread.State.RUNNABLE` in `VirtualThread.park()`, and from `VirtualThread.PARKING <-> Thread.State.RUNNABLE` to `VirtualThread.PARKED <-> Thread.State.WAITING` in `VirtualThread.afterYield()`.

**Comment by singh264** [comment] 2023-11-16 17:10
> If you agree, can you create PRs that modify the test in the JDK21 and JDK-next repos?

@babsingh the PRs that modify the test in the JDK21 and JDK-next repos are at https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/63 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/693. 

I adjusted the test, which passed 2500 times locally, by including `while (!reentrantLock.hasQueuedThread(vt)) {` before `task.ensureReady(vt, expState);` since the reentrant lock modifies the state of the virtual thread to `Thread.State.WAITING` by parking the virtual thread after it is added to the wait queue of the reentrant lock.

**Closed** 2023-11-20 18:02 UTC
Labels: comp:vm, test failure, project:loom, comp:jvmti, jdk21
