### ISSUE TITLE
harmony crash vmState=0x0005ffff

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20546] opened 2024-11-08 14:38 UTC
[Internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=95620582)
[Linux PPC 64bit] 80 Load_Level_2.harmony.5mins.Mode112 `-Xgcpolicy:gencon -Xjit:count=0 -Xnocompressedrefs`
rhel7p8vm14

vmState [0x5ffff]: {J9VMSTATE_JIT} {Illegal optimization number}

[30x grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=81255) failed 1/30

```
j> 08:31:55 #0: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x16d954c) [0x3fff7eb6954c]
j> 08:31:55 #1: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x16fdf08) [0x3fff7eb8df08]
j> 08:31:55 #2: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x5aa1a0) [0x3fff7da3a1a0]
j> 08:31:55 #3: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so(+0x61160) [0x3fff7f671160]
j> 08:31:55 #4: [0x3fff80760478]
j> 08:31:55 #5: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x63c820) [0x3fff7dacc820]
j> 08:31:55 #6: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x5a7c28) [0x3fff7da37c28]
j> 08:31:55 #7: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so(+0x5cec8) [0x3fff7f66cec8]
j> 08:31:55 #8: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x5a06c4) [0x3fff7da306c4]
j> 08:31:55 #9: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x59f700) [0x3fff7da2f700]
j> 08:31:55 #10: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x59dff8) [0x3fff7da2dff8]
j> 08:31:55 #11: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x59ddf4) [0x3fff7da2ddf4]
j> 08:31:55 #12: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so(+0x5cec8) [0x3fff7f66cec8]
j> 08:31:55 #13: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so(+0x59b8c8) [0x3fff7da2b8c8]
j> 08:31:55 #14: /bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9thr29.so(+0xcd44) [0x3fff7f72cd44]
j> 08:31:55 #15: /usr/lib64/libpthread.so.0(+0xcafc) [0x3fff8071cafc]
j> 08:31:55 #16: /usr/lib64/libc.so.6(clone-0xc453c) [0x3fff805b704c]
j> 08:31:55 Unhandled exception
j> 08:31:55 Type=Segmentation error vmState=0x0005ffff
j> 08:31:55 J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
j> 08:31:55 Handler1=00003FFF7FA1A968 Handler2=00003FFF7F6EF4B8
j> 08:31:55 R0=FFFFFFFFFF830000 R1=00003FFEB53AA0F0 R2=00003FFF7F2F0400 R3=0000000000000001
j> 08:31:55 R4=00003FFF7F222350 R5=0000000000001000 R6=FFFFFFFFFF000000 R7=00006A6176612F69
j> 08:31:55 R8=0000000000000010 R9=FFFFFFFFFFFFFFF4 R10=00000000000000C0 R11=0000000000000000
j> 08:31:55 R12=00003FFF7DA39F50 R13=00003FFEB53B6900 R14=00003FFEB53AA658 R15=00003FFEB53AA6D8
j> 08:31:55 R16=00003FFEB53AA6B8 R17=00003FFEB53AA698 R18=0000000000000001 R19=0000000000000000
j> 08:31:55 R20=00003FFF7F6E7D10 R21=00003FFF7F6F5F70 R22=00003FFEB53ABAE8 R23=00003FFCF402CB68
j> 08:31:55 R24=00003FFF780FE670 R25=00003FFEA4002200 R26=00003FFEB53AA948 R27=00003FFEA4022940
j> 08:31:55 R28=00003FFF7C171BA0 R29=00003FFEB53ABAE8 R30=0000000000000001 R31=0000000000000000
j> 08:31:55 NIP=00003FFF7DCBCC84 MSR=800000010280F032 ORIG_GPR3=C0000000000093BC CTR=00003FFF7DAD9EC0
j> 08:31:55 LINK=00003FFF7DAD9F74 XER=0000000020000000 CCR=0000000048004088 SOFTE=0000000000000001
j> 08:31:55 TRAP=0000000000000300 DAR=FFFFFFFFFFFFFFFD dsisr=0000000040000000 RESULT=0000000000000000
j> 08:31:55 FPR0=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR1=c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
j> 08:31:55 FPR2=41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
j> 08:31:55 FPR3=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR4=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR5=c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
j> 08:31:55 FPR6=405a000000000000 (f: 0.000000, d: 1.040000e+02)
j> 08:31:55 FPR7=412e848000000000 (f: 0.000000, d: 1.000000e+06)
j> 08:31:55 FPR8=4000000000000000 (f: 0.000000, d: 2.000000e+00)
j> 08:31:55 FPR9=4530000000000000 (f: 0.000000, d: 1.934281e+25)
j> 08:31:55 FPR10=412e848000000000 (f: 0.000000, d: 1.000000e+06)
j> 08:31:55 FPR11=43300000000f4240 (f: 1000000.000000, d: 4.503600e+15)
j> 08:31:55 FPR12=4530000000000000 (f: 0.000000, d: 1.934281e+25)
j> 08:31:55 FPR13=3fb745d100000000 (f: 0.000000, d: 9.090906e-02)
j> 08:31:55 FPR14=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR15=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR16=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR17=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR18=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR19=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR20=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR21=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR22=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR23=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR24=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR25=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR26=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR27=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR28=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR29=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR30=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 FPR31=0000000000000000 (f: 0.000000, d: 0.000000e+00)
j> 08:31:55 Module=/bluebird/builds/bld_81252/sdk/xp6480/jre/lib/ppc64/default/libj9jit29.so
j> 08:31:55 Module_base_address=00003FFF7D490000
j> 08:31:55 
j> 08:31:55 Method_being_compiled=java/io/ObjectInputStream.defaultReadFields(Ljava/lang/Object;Ljava/io/ObjectStreamClass;)V
j> 08:31:55 Target=2_90_20241108_81252 (Linux 3.10.0-1160.119.1.el7.ppc64)
j> 08:31:55 CPU=ppc64 (16 logical CPUs) (0xfc2e0000 RAM)
j> 08:31:55 ----------- Stack Backtrace -----------
j> 08:31:55  (0x00003FFF7F6AACB8 [libj9prt29.so+0x9acb8])
j> 08:31:55  (0x00003FFF7F66CEC8 [libj9prt29.so+0x5cec8])
j> 08:31:55  (0x00003FFF7F6AB428 [libj9prt29.so+0x9b428])
j> 08:31:55  (0x00003FFF7F6AA7BC [libj9prt29.so+0x9a7bc])
j> 08:31:55  (0x00003FFF7F66CEC8 [libj9prt29.so+0x5cec8])
j> 08:31:55  (0x00003FFF7F6AA878 [libj9prt29.so+0x9a878])
j> 08:31:55  (0x00003FFF7F87AED4 [libj9vm29.so+0x11aed4])
j> 08:31:55  (0x00003FFF7F66CEC8 [libj9prt29.so+0x5cec8])
j> 08:31:55  (0x00003FFF7F87A688 [libj9vm29.so+0x11a688])
j> 08:31:55  (0x00003FFF7F671160 [libj9prt29.so+0x61160])
j> 08:31:55 __kernel_sigtramp_rt64+0x0 (0x00003FFF80760478)
j> 08:31:55  (0x00003FFF7DACC820 [libj9jit29.so+0x63c820])
j> 08:31:55  (0x00003FFF7DA37C28 [libj9jit29.so+0x5a7c28])
j> 08:31:55  (0x00003FFF7F66CEC8 [libj9prt29.so+0x5cec8])
j> 08:31:55  (0x00003FFF7DA306C4 [libj9jit29.so+0x5a06c4])
j> 08:31:55  (0x00003FFF7DA2F700 [libj9jit29.so+0x59f700])
j> 08:31:55  (0x00003FFF7DA2DFF8 [libj9jit29.so+0x59dff8])
j> 08:31:55  (0x00003FFF7DA2DDF4 [libj9jit29.so+0x59ddf4])
j> 08:31:55  (0x00003FFF7F66CEC8 [libj9prt29.so+0x5cec8])
j> 08:31:55  (0x00003FFF7DA2B8C8 [libj9jit29.so+0x59b8c8])
j> 08:31:55  (0x00003FFF7F72CD44 [libj9thr29.so+0xcd44])
j> 08:31:55  (0x00003FFF8071CAFC [libpthread.so.0+0xcafc])
j> 08:31:55 clone+0xfff3bac4 (0x00003FFF805B704C [libc.so.6+0x14704c])
j> 08:31:55 ---------------------------------------
```

**Comment by pshipton** [comment] 2024-11-08 14:39
@zl-wang fyi

**Comment by pshipton** [comment] 2024-11-11 22:45
See also https://github.com/eclipse-openj9/openj9/issues/20567

**Comment by pshipton** [comment] 2024-11-14 16:05
@hzongaro pls take a look

**Comment by hzongaro** [comment] 2024-11-15 17:31
@pshipton, sorry for the basic question, but it's been a long time since I looked at a failure reported in vmfarm.  Where should I be looking for the Linux x86 builds that you mentioned in https://github.com/eclipse-openj9/openj9/issues/20546#issuecomment-2476653785 and https://github.com/eclipse-openj9/openj9/issues/20546#issuecomment-2477139090?

```
j9build@rtv-rhel8le-cuda-1 ~]$ ls /bluebird/builds/bld_81617
ls: cannot access '/bluebird/builds/bld_81617': No such file or directory
[j9build@rtv-rhel8le-cuda-1 ~]$ ls /bluebird/builds/bld_81633
ls: cannot access '/bluebird/builds/bld_81633': No such file or directory
[j9build@rtv-rhel8le-cuda-1 ~]$ ls /bluebird/builds
'""'   bld_81404   bld_81485   bld_81552   bld_81567   bld_81619   bld_81656   bld_81696   bld_81702
 77    bld_81412   bld_81503   bld_81554   bld_81618   bld_81629   bld_81660   bld_81700   generate
```

**Comment by pshipton** [comment] 2024-11-15 18:03
The builds are retired and no longer on disk, you can find them in artifactory.
i.e. https://na.artifactory.swg-devops.com/ui/native/sys-rt-vmfarm-generic-local/R29/acceptance/xa6480/81617

**Comment by pshipton** [comment] 2024-11-18 22:10
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=96192205
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=96192543

**Comment by pshipton** [comment] 2024-11-19 20:38
AIX core files can be found under http://vmfarm.rtp.raleigh.ibm.com/etc/cores/tmp/

**Comment by hzongaro** [comment] 2024-11-19 22:16
> i.e. https://na.artifactory.swg-devops.com/ui/native/sys-rt-vmfarm-generic-local/R29/acceptance/xa6480/81617

@pshipton, do you know where I might find the debug image for that build?

**Comment by pshipton** [comment] 2024-11-20 03:27
We have https://na.artifactory.swg-devops.com/ui/native/sys-rt-vmfarm-generic-local/R29/acceptance/jvmxa6480/81617/jvmxa6480.zip which appear to contain debug.

**Comment by hzongaro** [comment] 2024-11-20 13:47
Though the root cause of the problem is the same as that reported in #20567, the location where it occurs is different.  That debug build helped move me further in investigating the problem.  I was unable to tie addresses reported in the core file directly to line numbers in the source code, but I managed to piece together where exactly the problem occurred by looking for method calls that weren't virtual.

It looks like the problem in this case occurs at the call to [`TR_ResolvedJ9Method::getExistingJittedBodyInfo()` from `TR_ResolvedJ9Method::getExistingJittedBodyInfo()`](https://github.com/eclipse-openj9/openj9/blob/e6ae080900837d8a498b4df693bb7e3312665703/runtime/compiler/control/CompilationThread.cpp#L8473), which in turn calls [`TR::Recompilation::getJittedBodyInfoFromPC`](https://github.com/eclipse-openj9/openj9/blob/e6ae080900837d8a498b4df693bb7e3312665703/runtime/compiler/env/j9method.cpp#L5546-L5551).

**Comment by pshipton** [comment] 2024-11-26 12:47
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=96675227

**Comment by vij-singh** [comment] 2024-11-26 12:55
@IBMJimmyk @zl-wang Can we verify this one with the fix for #20567 ?

**Comment by IBMJimmyk** [comment] 2024-11-26 14:43
Based on Henry's comments, my fix for https://github.com/eclipse-openj9/openj9/issues/20567 would not help. My understanding is `getExistingJittedBodyInfo` calls `startAddressForInterpreterOfJittedMethod` which reads the `extra` field and returns -3 because the latest compilation failed. `getExistingJittedBodyInfo` then calls `getJittedBodyInfoFromPC` with -3 and crashes since that's not a real start PC.

This is similar to the problem I saw but is taking a different path. I think the solution might also be to add error checking for invalid startPCs and take appropriate action. I would need to look at the code in more detail to determine what the best way to handle an error would be. It might be possible for `getJittedBodyInfoFromPC` to return NULL for invalid startPCs and then check that everywhere that uses it can handle a NULL return.

**Comment by pshipton** [comment] 2024-11-26 22:50
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=96726917
[Win64 Hammer Compressed Pointers] 80 Load_Level_2.harmony.5mins.Mode688

**Comment by hzongaro** [comment] 2024-12-10 03:29
@IBMJimmyk, I know you were thinking about a fix for this.  Do you think it can make it into 0.49 or should this move out to 0.51?

**Comment by pshipton** [comment] 2024-12-10 03:40
We need a good justification to move a regression/blocker out. This failure has been occurring frequently and also occurred in a 25_01 build.

**Comment by pshipton** [comment] 2024-12-10 12:47
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=97597711 - 25_01

**Comment by IBMJimmyk** [comment] 2024-12-10 15:58
I just talked to @dsouzai and it looks like this issue might be fixed by this recently merged PR:
https://github.com/eclipse-openj9/openj9/pull/20763

It reverts a problematic PR that was messing with the extra field and was originally merged in on Nov 7. I think this is just before these Harmony -3 start PC problems showed up (This issue was opened on Nov 8). The problematic PR was causing a bad start PC to cause problems in other places as well.

I am currently in the middle of trying to see if I can verify that reverting the change will fix the problem.

**Comment by pshipton** [comment] 2024-12-12 13:09
@IBMJimmyk do you have any conclusions? Something seems to have fixed the problem as I haven't been seeing it in the head stream builds any more. We should get the fix backported asap.

**Comment by dsouzai** [comment] 2024-12-12 15:03
I opened https://github.com/eclipse-openj9/openj9/pull/20825; the original issue I had fixed wasn't tagged for any release, so I never double delivered.

**Comment by IBMJimmyk** [comment] 2024-12-12 15:04
It does seem like the (now reverted) change that modified the extra field can potentially cause the problem in this issue. So the PR that reverts it should fix this issue as well.

**Closed** 2024-12-12 16:33 UTC
Labels: comp:jit, test failure, blocker, segfault
