### ISSUE TITLE
JDK20 com/sun/crypto/provider/Mac/HmacSHA512.java RuntimeException: assertTrue: expected true, was false

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16968] opened 2023-03-20 18:41 UTC
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_s390x_linux_Personal/1/consoleFull)(`rhel7s390x-4-1`):
```
09:00:53  openjdk version "20-internal" 2023-03-21
09:00:53  OpenJDK Runtime Environment (build 20-internal-adhoc.jenkins.BuildJDK20s390xlinuxPersonal)
09:00:53  Eclipse OpenJ9 VM (build master-8cc902bc75f, JRE 20 Linux s390x-64-Bit Compressed References 20230316_13 (JIT enabled, AOT enabled)
09:00:53  OpenJ9   - 8cc902bc75f
09:00:53  OMR      - 035ec68ec0c
09:00:53  JCL      - 10a35739269 based on jdk-20+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_io_0,jdk_io_1,jdk_other_0,jdk_other_1,jdk_security1_0,jdk_security1_1,jdk_security2_0,jdk_security2_1,jdk_security3_0,jdk_security3_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=3&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK20_s390x_linux_Personal%2F13%2FOpenJ9-JDK20-s390x_linux-20230316-051333.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK20_s390x_linux_Personal%2F13%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=20&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk20.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=8cc902bc75ffa8e24f4beef2a1f8726a383771eb&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=034d4edd4350276a2d01aade526b242fb70f4eee&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:35:48  variation: Mode150
10:35:48  JVM_OPTIONS:  -XX:+UseCompressedOops 

10:38:31  TEST: com/sun/crypto/provider/Mac/HmacSHA512.java

10:38:31  STDERR:
10:38:31  java.lang.RuntimeException: assertTrue: expected true, was false
10:38:31  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
10:38:31  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
10:38:31  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:472)
10:38:31  	at HmacSHA512.main(HmacSHA512.java:46)
10:38:31  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:38:31  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:38:31  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:38:31  	at java.base/java.lang.Thread.run(Thread.java:1639)
10:38:31  
10:38:31  JavaTest Message: Test threw exception: java.lang.RuntimeException

10:40:14  jdk_security2_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31766/)

**Comment by pshipton** [comment] 2023-03-21 02:49
It failed quite a bit. 4(rhel7s390x-4-8)+4(rhel7s390x-4-5)+10(ub18s390xrt-1-9)+10(rhel8s390x-svl-rt3-1)+6(rhel7s390x-3-4)

**Comment by pshipton** [comment] 2023-03-21 02:53
Another [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31795/) with `-Djdk.nativeCrypto=false`.

**Comment by pshipton** [comment] 2023-04-18 14:01
Based on the way it fails, seems like a JIT problem, we should start investigation there.
@0xdaryl @joransiu

**Comment by pshipton** [comment] 2023-04-18 14:04
@JasonFengJ9 does this only fail on zLinux?

**Comment by Spencer-Comin** [comment] 2023-04-26 19:17
I've managed to consistently reproduce this failure, and with @r30shah's fix for https://github.com/eclipse-openj9/openj9/issues/16969 it consistently passes. Seems to be the same problem.

**Comment by pshipton** [comment] 2023-05-03 23:18
Closing as dup of https://github.com/eclipse-openj9/openj9/issues/16969

**Closed by pshipton** 2023-05-03 23:18 UTC
Labels: comp:jit, test failure, arch:z, jdk20
