### ISSUE TITLE
JDK19 java/lang/Thread/virtual/stress/GetStackTraceALot.java#id0 failed with JIT enabled

### ISSUE THREAD

**Issue by thallium** [eclipse-openj9/openj9#16046] opened 2022-10-05 19:16 UTC
```
STDOUT:
547
950
STDERR:
19:11:09.163 0x280b00    j9vm.579    *   ** ASSERTION FAILED ** at /root/openj9-openjdk-jdk19/openj9/runtime/vm/ContinuationHelpers.cpp:98: ((currentThread->currentContinuation) == NULL)
```

**Comment by babsingh** [comment] 2022-10-06 16:24
Potential duplicate of https://github.com/eclipse-openj9/openj9/issues/16047. Symptoms similar to https://github.com/eclipse-openj9/openj9/issues/16047#issuecomment-1270217444.

**Comment by tajila** [comment] 2022-10-20 15:14
@thallium is this still failing?

**Comment by thallium** [comment] 2022-10-20 16:00
> @thallium is this still failing?

No, it passes now

**Closed** 2022-10-20 17:06 UTC
Labels: test failure, project:loom, jdk19
