### ISSUE TITLE
JDK19 LambdaLoadTest_CS_5m_0_FAILED j9mm.479    *   ** ASSERTION FAILED ** at runtime\gc_glue_java\MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15410] opened 2022-06-23 12:22 UTC
Failure link
------------

From an internal build `job/Test_openjdk19_j9_sanity.system_x86-64_windows_Personal/2/tapResults/`(`win16x64rt-1-2`):
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.buildjdk19x86-64windowspersonal)
Eclipse OpenJ9 VM (build master-ac82c9067c5, JRE 19 Windows Server 2016 amd64-64-Bit Compressed References 20220622_4 (JIT enabled, AOT enabled)
OpenJ9   - ac82c9067c5
OMR      - 342963cee6d
JCL      - abd1f9e6083 based on jdk-19+27)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=sanity.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK19_x86-64_windows_Personal%2F4%2FOpenJ9-JDK19-x86-64_windows-20220622-202417.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK19_x86-64_windows_Personal%2F4%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk19.git&OPENJ9_BRANCH=master&OPENJ9_SHA=ac82c9067c5a4983407b1d2996b98f8f5714968c&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=3&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test LambdaLoadTest_CS_5m_0 ...
===============================================
LambdaLoadTest_CS_5m_0 Start Time: Wed Jun 22 23:43:16 2022 Epoch Time (ms): 1655966596444
variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge 

LT  23:45:12.952 - Completed 33.5%. Number of tests started=3030 (+785)
LT  stderr 00000000005D2800: Object neither in heap nor stack-allocated in thread load-4
LT  stderr 00000000005D2800:	O-Slot=0000000000AB9990
LT  stderr 00000000005D2800:	O-Slot value=00000000000B2188
LT  stderr 00000000005D2800:	PC=00007FFEBD837B65
LT  stderr 00000000005D2800:	framesWalked=1
LT  stderr 00000000005D2800:	arg0EA=0000000000AB99A8
LT  stderr 00000000005D2800:	walkSP=0000000000AB9920
LT  stderr 00000000005D2800:	literals=0000000000000000
LT  stderr 00000000005D2800:	jitInfo=00000241C21659A8
LT  stderr 00000000005D2800:	method=0000000000079900 (java/lang/Thread.genThreadName()Ljava/lang/String;) (JIT)
LT  stderr 00000000005D2800:	stack=0000000000A5E518-0000000000ABA1D0
LT  stderr 06:45:31.373 0x173900    j9mm.479    *   ** ASSERTION FAILED ** at c:\users\jenkins\workspace\build_jdk19_x86-64_windows_personal\openj9\runtime\gc_glue_java\MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))
LT  stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/06/22 23:45:31 - please wait.

LambdaLoadTest_CS_5m_0_FAILED
```

This assertion appeared in a few other issues (all closed)
[j9mm.479 * ** ASSERTION FAILED ** at openj9/runtime/gc_glue_java/MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))](https://github.com/eclipse-openj9/openj9/issues/13369)
[JDK16 aarch64_linux : j9mm.479 * ** ASSERTION FAILED ** at openj9/runtime/gc_glue_java/MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))](https://github.com/eclipse-openj9/openj9/issues/13017)
[JDK8 JIT Server j9mm.479 * ** ASSERTION FAILED ** at ../../gc_glue_java/MarkingSchemeRootMarker.cpp:53](https://github.com/eclipse-openj9/openj9/issues/9424)

**Comment by pshipton** [comment] 2022-06-23 12:37
@dmitripivkine fyi

**Comment by JasonFengJ9** [comment] 2022-06-23 13:29
Another occurrence at **Mac** - `job/Test_openjdk19_j9_special.system_x86-64_mac_Personal/2/tapResults/`
```
LT  stderr 0000000015BB1E00: Object neither in heap nor stack-allocated in thread load-5
LT  stderr 0000000015BB1E00:	O-Slot=0000000015F07348
LT  stderr 0000000015BB1E00:	O-Slot value=00000000156AC2A8
LT  stderr 0000000015BB1E00:	PC=000000002BC620E9
LT  stderr 0000000015BB1E00:	framesWalked=4
LT  stderr 0000000015BB1E00:	arg0EA=0000000015F073A8
LT  stderr 0000000015BB1E00:	walkSP=0000000015F07048
LT  stderr 0000000015BB1E00:	literals=0000000000000000
LT  stderr 0000000015BB1E00:	jitInfo=00007F9A358EA9E8
LT  stderr 0000000015BB1E00:	method=000000001566BCD8 (java/lang/Thread.<init>(Ljava/lang/Runnable;)V) (JIT)
LT  stderr 0000000015BB1E00:	stack=0000000015ED4800-0000000015F07DF0
LT  stderr 08:22:43.871 0x15dcb200    j9mm.479    *   ** ASSERTION FAILED ** at /Users/jenkins/workspace/Build_JDK19_x86-64_mac_Personal/openj9/runtime/gc_glue_java/MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))
LT  stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/06/23 04:22:43 - please wait.
```

**Comment by dmitripivkine** [comment] 2022-06-28 15:27
from one of the failures in this build - bad O-slot `0xf5bb728` contain `0xef4dd18` JIT frame for `method=0xef13d78 (java/lang/Thread.<init>(Ljava/lang/Runnable;)V) (JIT)`
```
19:29:17.562182019 *0xF001900 j9mm.481             Exception  * Object neither in heap nor stack-allocated in thread load-5
19:29:17.562190229  0xF001900 j9mm.482             Exception  * O-Slot=0xf5bb728
19:29:17.562197007  0xF001900 j9mm.483             Exception  * O-Slot value=0xef4dd18
19:29:17.562203586  0xF001900 j9mm.484             Exception  * PC=0x28eb2c09
19:29:17.562210328  0xF001900 j9mm.485             Exception  * framesWalked=5
19:29:17.562216899  0xF001900 j9mm.486             Exception  * arg0EA=0xf5bb788
19:29:17.562223240  0xF001900 j9mm.487             Exception  * walkSP=0xf5bb458
19:29:17.562229613  0xF001900 j9mm.488             Exception  * literals=0x0
19:29:17.562236419  0xF001900 j9mm.489             Exception  * jitInfo=0x7fa90d37e868
19:29:17.562244333  0xF001900 j9mm.490             Exception  * method=0xef13d78 (java/lang/Thread.<init>(Ljava/lang/Runnable;)V) (JIT)
19:29:17.562251539  0xF001900 j9mm.493             Exception  * stack=0xf580d38-0xf5bc180
19:29:17.562252073  0xF001900 j9mm.491             Exit       *<StackSlotValidator::reportStackSlot
19:29:17.562252467  0xF001900 j9mm.479             Assert     * ** ASSERTION FAILED ** at /Users/jenkins/workspace/Build_JDK19_x86-64_mac_Personal/openj9/runtime/gc_glue_java/MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))
```
Bogus value `0xef4dd18` is an address of `ramStatics` section for `!j9class 0xEF54400` `java/lang/Thread$ThreadNumbering`

This is duplicate of https://github.com/eclipse-openj9/openj9/issues/15251
@0xdaryl I am going to close this item as duplicate, there are a few more cores in the build in case you need them

**Closed by dmitripivkine** 2022-06-28 15:27 UTC
Labels: comp:jit, test failure, jdk19
