### ISSUE TITLE
jdk19 OpenJDK  java/lang/Thread/jni/AttachCurrentThread/AttachTest.java crash walkStackFrames

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16298] opened 2022-11-09 12:59 UTC
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_s390x_linux_Nightly/46
jdk_lang_0 
 java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk19_j9_sanity.openjdk_s390x_linux_Nightly/46/openjdk_test_output.tar.gz
```
23:15:34  Unhandled exception
23:15:34  Type=Segmentation error vmState=0x00000000
23:15:34  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
23:15:34  Handler1=000003FFB03444B8 Handler2=000003FFB0231CB8 InaccessibleAddress=0000000000000000
23:15:34  gpr0=000003FF00001710 gpr1=00000000016FE350 gpr2=0000000000000000 gpr3=0000000000000000
23:15:34  gpr4=00000000A42C0000 gpr5=000003FFAC0D0AF8 gpr6=0000000001607700 gpr7=00000000016FE330
23:15:34  gpr8=000003FFB056E490 gpr9=0000000000000000 gpr10=0000000001607700 gpr11=0000000001607A00
23:15:34  gpr12=000000000166C700 gpr13=00000000A42C0000 gpr14=000003FFB039102A gpr15=000003FFB0F6FC18
23:15:34  psw=000003FFB0391B2A mask=0705100180000000 fpc=00080000 bea=000003FFB03916B2
23:15:34  fpr0 000003ffac0008e0 (f: 2885683456.000000, d: 2.172227e-311)
23:15:34  fpr1 483acb00b0f6d6b0 (f: 2968966912.000000, d: 9.117178e+39)
23:15:34  fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:15:34  fpr3 3f336e21dbeabbfe (f: 3689593856.000000, d: 2.964814e-04)
23:15:34  fpr4 0000000000000007 (f: 7.000000, d: 3.458460e-323)
23:15:34  fpr5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:15:34  fpr6 000003ffac000910 (f: 2885683456.000000, d: 2.172227e-311)
23:15:34  fpr7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:15:34  fpr8 00000000015e1c40 (f: 22944832.000000, d: 1.133625e-316)
23:15:34  fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:15:34  fpr10 00000000015e1f68 (f: 22945640.000000, d: 1.133665e-316)
23:15:34  fpr11 000003fffbc7c2e0 (f: 4224172800.000000, d: 2.172889e-311)
23:15:34  fpr12 0005ed01e704fe3e (f: 3875864064.000000, d: 8.240853e-309)
23:15:34  fpr13 000003ff180fbfb8 (f: 403685312.000000, d: 2.171001e-311)
23:15:34  fpr14 000003ff9c1c65e0 (f: 2619106816.000000, d: 2.172096e-311)
23:15:34  fpr15 000003ff181abd78 (f: 404405632.000000, d: 2.171001e-311)
23:15:34  Module=/home/jenkins/workspace/Test_openjdk19_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
23:15:34  Module_base_address=000003FFB0300000
23:15:34  Target=2_90_20221108_111 (Linux 5.4.0-124-generic)
23:15:34  CPU=s390x (4 logical CPUs) (0x1f5906000 RAM)
23:15:34  ----------- Stack Backtrace -----------
23:15:34  walkStackFrames+0xbc2 (0x000003FFB0391B2A [libj9vm29.so+0x91b2a])
23:15:34  walkStackForExceptionThrow+0xa2 (0x000003FFB033704A [libj9vm29.so+0x3704a])
23:15:34  _ZN32VM_BytecodeInterpreterCompressed3runEP10J9VMThread+0x430 (0x000003FFB03A8060 [libj9vm29.so+0xa8060])
23:15:34  bytecodeLoopCompressed+0xce (0x000003FFB03A7C1E [libj9vm29.so+0xa7c1e])
23:15:34  c_cInterpreter+0x64 (0x000003FFB0490A54 [libj9vm29.so+0x190a54])
23:15:34  ---------------------------------------
```

Changes from previous build
https://github.com/eclipse-openj9/openj9/compare/11ff01df1...6e7218b9ca5
https://github.com/eclipse-openj9/openj9-omr/compare/0c0a8a660...1c49c4a411f

**Comment by pshipton** [comment] 2022-11-09 12:59
@tajila fyi this new issue

**Comment by gacholio** [comment] 2022-11-09 19:46
None of the changes look relevant. I've downloaded the core. For the future, it would be helpful to also include the VM download link (I know it can be found, but it always takes me a while).

**Comment by gacholio** [comment] 2022-11-09 20:16
```
> !stackslots 0x01607700
<1607700> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x0000000001607700 ***
<1607700> 	ITERATE_O_SLOTS
<1607700> 	RECORD_BYTECODE_PC_OFFSET
<1607700> Initial values: walkSP = 0x00000000016FE330, PC = 0x0000000000000006, literals = 0x0000000000000000, A0 = 0x00000000016FE360, j2iFrame = 0x0000000000000000, ELS = 0x000003FFB0F708B0, decomp = 0x0000000000000000
Nov 09, 2022 8:15:28 PM com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
WARNING: CorruptDataException thrown walking stack. walkThread = 0x0000000001607700
com.ibm.j9ddr.NullPointerDereference: Memory Fault reading 0x00000000 : 
	at com.ibm.j9ddr.vm29.pointer.AbstractPointer.getPointerAtOffset(AbstractPointer.java:351)
	at com.ibm.j9ddr.vm29.pointer.generated.J9MethodPointer.constantPool(Unknown Source)
	at com.ibm.j9ddr.vm29.j9.ConstantPoolHelpers.J9_CP_FROM_METHOD(ConstantPoolHelpers.java:60)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkJITJNICalloutFrame(StackWalker.java:1243)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:427)
	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:103)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.StackWalkCommand.run(StackWalkCommand.java:139)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
	at openj9.dtfj/com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:78)
	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:813)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:767)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:741)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:665)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)

Stack walk result: STACK_CORRUPT
```

**Comment by gacholio** [comment] 2022-11-09 20:23
```
#define J9SF_FRAME_TYPE_JIT_JNI_CALLOUT  6

> !J9SFJNINativeMethodFrame 0x00000000016FE330
J9SFJNINativeMethodFrame at 0x16fe330 {
  Fields for J9SFJNINativeMethodFrame:
	0x0: struct J9Method* method = !j9method 0x0000000000000000
	0x8: UDATA specialFrameFlags = 0x0000000001637EC8 (23297736)
	0x10: struct J9Method* savedCP = !j9method 0x000003FF5A05A3CA // <FAULT>
	0x18: U8* savedPC = !j9x 0x00000000016FE3D8 // ""
	0x20: UDATA* savedA0 = !j9x 0x000000002DC15330
}
> !jitmetadatafrompc 0x000003FF5A05A3CA
> !findmethodfrompc 0x000003FF5A05A3CA
Searching for PC=0x000003FF5A05A3CA in VM=0x000003FFAC02C6F0...
!j9method 0x0000000001637EC8 openj9/internal/foreign/abi/InternalUpcallHandler.getUpcallThunkAddr(Ljava/lang/invoke/MethodHandle;Ljava/lang/foreign/MemorySession;)J
Bytecode PC offset = 0x00000000000000B2
```

**Comment by gacholio** [comment] 2022-11-09 20:25
0xB2 is bytecode 178 here:
```
> !bytecodes 0x0000000001637EC8
  Name: getUpcallThunkAddr
  Signature: (Ljava/lang/invoke/MethodHandle;Ljava/lang/foreign/MemorySession;)J
  Access Flags (10260002): private 
  Internal Attribute Flags:
  Max Stack: 5
  Caught Exceptions (2):
     start   end   handler   catch type
     -----   ---   -------   ----------
     87  200  203   (any)
     203  208  203   (any)
  Argument Count: 3
  Temp Count: 9

    0 aload0getfield 
    1 getfield 12 openj9/internal/foreign/abi/InternalUpcallHandler.argLayoutArray [Ljava/lang/foreign/MemoryLayout;
    4 arraylength 
    5 istore3 
    6 iload3 
    7 iconst1 
    8 iadd 
    9 anewarray 20 java/lang/String
   12 astore 4
   14 iconst0 
   15 istore 5
   17 iload 5
   19 iload3 
   20 ificmpge 49
   23 aload0getfield 
   24 getfield 12 openj9/internal/foreign/abi/InternalUpcallHandler.argLayoutArray [Ljava/lang/foreign/MemoryLayout;
   27 iload 5
   29 aaload 
   30 astore 6
   32 aload 4
   34 iload 5
   36 aload 6
   38 iconst0 
   39 invokestatic 21 openj9/internal/foreign/abi/LayoutStrPreprocessor.getSimplifiedLayoutString(Ljava/lang/foreign/MemoryLayout;Z)Ljava/lang/String;
   42 aastore 
   43 iinc 5 1
   46 goto 17
   49 aload0getfield 
   50 getfield 17 openj9/internal/foreign/abi/InternalUpcallHandler.realReturnLayout Ljava/lang/foreign/MemoryLayout;
   53 ifnonnull 65
   56 aload 4
   58 iload3 
   59 ldc 1 (java.lang.String) 0#V
   61 aastore 
   62 goto 77
   65 aload 4
   67 iload3 
   68 aload0getfield 
   69 getfield 17 openj9/internal/foreign/abi/InternalUpcallHandler.realReturnLayout Ljava/lang/foreign/MemoryLayout;
   72 iconst0 
   73 invokestatic 21 openj9/internal/foreign/abi/LayoutStrPreprocessor.getSimplifiedLayoutString(Ljava/lang/foreign/MemoryLayout;Z)Ljava/lang/String;
   76 aastore 
   77 lconst0 
   78 lstore 5
   80 getstatic 23 openj9/internal/foreign/abi/InternalUpcallHandler.privateUpcallClassLock Ljava/lang/Object;
   83 dup 
   84 astore 7
   86 monitorenter 
   87 newdup 24 java/lang/StringBuilder
   90 dup 
   91 invokespecial 25 java/lang/StringBuilder.<init>()V
   94 aload1 
   95 invokevirtual 26 java/lang/Object.hashCode()I
   98 invokevirtual 27 java/lang/StringBuilder.append(I)Ljava/lang/StringBuilder;
  101 ldc 2 (java.lang.String) #
  103 invokevirtual 28 java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
  106 aload2 
  107 invokeinterface2 
  109 invokeinterface 29 java/lang/foreign/MemorySession.toString()Ljava/lang/String;
  112 invokevirtual 28 java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
  115 invokevirtual 31 java/lang/StringBuilder.toString()Ljava/lang/String;
  118 astore 8
  120 aload 8
  122 invokevirtual 32 java/lang/String.hashCode()I
  125 invokestatic 33 java/lang/Integer.valueOf(I)Ljava/lang/Integer;
  128 astore 9
  130 getstatic 35 openj9/internal/foreign/abi/InternalUpcallHandler.cachedUpcallThunkAddr Ljava/util/HashMap;
  133 aload 9
  135 invokevirtual 36 java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;
  138 checkcast 38 java/lang/Long
  141 astore 10
  143 aload 10
  145 ifnull 158
  148 aload 10
  150 invokevirtual 39 java/lang/Long.longValue()J
  153 lstore 5
  155 goto 197
  158 aload0 
  159 newdup 40 openj9/internal/foreign/abi/UpcallMHMetaData
  162 dup 
  163 aload1 
  164 aload2 
  165 invokespecial 41 openj9/internal/foreign/abi/UpcallMHMetaData.<init>(Ljava/lang/invoke/MethodHandle;Ljava/lang/foreign/MemorySession;)V
  168 putfield 42 openj9/internal/foreign/abi/InternalUpcallHandler.metaData Lopenj9/internal/foreign/abi/UpcallMHMetaData;
  171 aload0 
  172 aload0getfield 
  173 getfield 42 openj9/internal/foreign/abi/InternalUpcallHandler.metaData Lopenj9/internal/foreign/abi/UpcallMHMetaData;
  176 aload 4
  178 invokespecial 43 openj9/internal/foreign/abi/InternalUpcallHandler.allocateUpcallStub(Lopenj9/internal/foreign/abi/UpcallMHMetaData;[Ljava/lang/String;)J
  181 lstore 5
  183 getstatic 35 openj9/internal/foreign/abi/InternalUpcallHandler.cachedUpcallThunkAddr Ljava/util/HashMap;
  186 aload 9
  188 lload 5
  190 invokestatic 44 java/lang/Long.valueOf(J)Ljava/lang/Long;
  193 invokevirtual 45 java/util/HashMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
  196 pop 
  197 aload 7
  199 monitorexit 
  200 goto 211
  203 astore 11
  205 aload 7
  207 monitorexit 
  208 aload 11
  210 athrow 
  211 lload 5
  213 return2 
```

**Comment by gacholio** [comment] 2022-11-09 20:25
@ChengJin01 Looks like an upcall issue.

**Comment by ChengJin01** [comment] 2022-11-10 00:05
The bytecode at 178 (0xB2):
```
 !bytecodes 0x0000000001637EC8
  Name: getUpcallThunkAddr
  Signature: (Ljava/lang/invoke/MethodHandle;Ljava/lang/foreign/MemorySession;)J
---> 178 invokespecial 43 openj9/internal/foreign/abi/InternalUpcallHandler.allocateUpcallStub(Lopenj9/internal/foreign/abi/UpcallMHMetaData;[Ljava/lang/String;)J
  181 lstore 5
```
is to call `allocateUpcallStub()` at https://github.com/eclipse-openj9/openj9/blob/fafe18409d2f290ea955e27db5be17e0f5be413d/jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java#L170, which is a native method at https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalUpcallHandler.cpp that aims to allocate thunk address for upcall.

I went through the code in `allocateUpcallStub` and didn't find out any clue causing the crash (if the crash occurred there, the dumps should be very straightforward in identifying where it occurred). Meanwhile, I tried reproducing the issue many times but ended up with nothing (it always passed in the test).  So it seems the problem randomly happens but not sure whether it is specific to zLinux or a generic issue in upcall.

**Comment by ChengJin01** [comment] 2022-11-10 00:29
Launched a Grinder (x100) for `jdk_lang_0` to see whether it can be reproduced.

**Comment by gacholio** [comment] 2022-11-10 04:17
I can't imagine why this test would be using upcall, but it seems suspicious to me that upcall is present at all, even is the stack is off by a slot of two.

**Comment by ChengJin01** [comment] 2022-11-10 04:37
> I can't imagine why this test would be using upcall, but it seems suspicious to me that upcall is present at all, even is the stack is off by a slot of two.

This is a special case in
https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/master/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java that tests native threads attaching implicitly to the VM in upcall:
```
public class AttachTest {
    static final String TEST_CLASSES = System.getProperty("test.classes");
    static final String JAVA_LIBRARY_PATH = System.getProperty("java.library.path");

    public static void main(String[] args) throws Exception {
        // prepend -cp ${test.classes} -Djava.library.path=${java.library.path}
        String[] opts = Stream.concat(Stream.of(
                        "-cp", TEST_CLASSES,
                        "-Djava.library.path=" + JAVA_LIBRARY_PATH),
                        Stream.of(args))
                .toArray(String[]::new);
        OutputAnalyzer outputAnalyzer = ProcessTools
                .executeTestJava(opts)
                .outputTo(System.out)
                .errorTo(System.out);
        outputAnalyzer.shouldHaveExitValue(0);
    }
}
```
The `main` method above is to kick off another process for the real test at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/test/jdk/java/lang/Thread/jni/AttachCurrentThread/ImplicitAttach.java to create a couple of native threads (from 1 to 4) in downcall to trigger upcall.
```
public class ImplicitAttach {
...
    public static void main(String[] args) throws Throwable {
        int threadCount;
        if (args.length > 0) {
            threadCount = Integer.parseInt(args[0]);
        } else {
            threadCount = 2;
        }
        latch = new CountDownLatch(threadCount);

        Linker abi = Linker.nativeLinker(); <---------------------------

        // stub to invoke callback
        MethodHandle callback = MethodHandles.lookup()
                .findStatic(ImplicitAttach.class, "callback", MethodType.methodType(void.class));
        MemorySegment upcallStub = abi.upcallStub(callback, <------------------- set up the upcall stub
                FunctionDescriptor.ofVoid(),
                MemorySession.global());

        // void start_threads(int count, void *(*f)(void *))
        SymbolLookup symbolLookup = SymbolLookup.loaderLookup();
        MemorySegment symbol = symbolLookup.lookup("start_threads").orElseThrow();
        FunctionDescriptor desc = FunctionDescriptor.ofVoid(C_INT, C_POINTER);
        MethodHandle start_threads = abi.downcallHandle(symbol, desc);

        // start the threads and wait for the threads to call home
        start_threads.invoke(threadCount, upcallStub); <--------- call start_threads() to trigger upcall
        latch.await();
    }

    /**
     * Invoked from native thread.
     */
    private static void callback() { <----- This is the upcall method called by start_threads() in upcall
        System.out.println(Thread.currentThread());
        latch.countDown();
    }

    static {
        System.loadLibrary("ImplicitAttach");
    }
}
```
plus the native function at https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/test/jdk/java/lang/Thread/jni/AttachCurrentThread/libImplicitAttach.c
```
void start_threads(int n, void *(*f)(void *)) {
    pthread_t tid;
    pthread_attr_t attr;
    int i;

    pthread_attr_init(&attr);
    pthread_attr_setstacksize(&attr, STACK_SIZE);
    for (i = 0; i < n ; i++) {
        int res = pthread_create(&tid, &attr, f, NULL); <------ create a couple of native threads that triggers upcall
        if (res != 0) {
            fprintf(stderr, "pthread_create failed: %d\n", res);
        }
    }
}
```

**Comment by ChengJin01** [comment] 2022-11-10 05:33
Assuming that the corrupted dumps was correct as the crash happened to somewhere in `allocateUpcallStub`, it should be around `abi.upcallStub` in preparation for the upcall stub in which case the downcall & upcall invocation had not yet started.
```
public class ImplicitAttach {
...
    public static void main(String[] args) throws Throwable {
...
        MemorySegment upcallStub = abi.upcallStub(callback, <------------- crash occurred here
                FunctionDescriptor.ofVoid(),
                MemorySession.global());
....
      MethodHandle start_threads = abi.downcallHandle(symbol, desc); <---- set up the downcall handler

        // start the threads and wait for the threads to call home
        start_threads.invoke(threadCount, upcallStub);  <------- kick off a downcall to the native
```

**Comment by ChengJin01** [comment] 2022-11-10 22:35
The Grinder (x100) previously launched at https://openj9-jenkins.osuosl.org/job/Grinder/1507/#showFailuresLink didn't capture anything wrong with `AttachTest`, in which case the problem can't be reproduced for the moment.

Given there is no solid evidence to prove the crash was literally triggered by `allocateUpcallStub` (and the crash has nothing to do with downcall & upcall invocation as it occurred prior to downcall & upcall) and the reason behind this still remains unclear, I'd suggest to close this issue till it shows up again.

**Closed** 2022-11-11 17:24 UTC
Labels: comp:vm, test failure, segfault, jdk19
